from robot.libraries.BuiltIn import BuiltIn

# Credentials
admin_credentials = {'userName': 'Administrator', 'password': 'wpsthpvse1'}
oa_credentials = {'username': 'Administrator', 'password': 'hpvse14'}
ilo_credentials = {'username': 'Administrator', 'password': 'hpvse1-ilo'}
cliq_credentials = {
    'mgmt_ip': '16.71.149.173',
    'username': 'admin',
    'password': 'admin'}

# Resource types for X-API-Version=1000
SERVER_PROFILE_TYPE = 'ServerProfileV10'

# Enclosures, Interconnects, Server Hardware, Networks, ULS, LIG, and EG
# Enclosures
ENC1 = 'wpst22'
ENC1_OA1 = "16.125.77.71"
ENC2 = 'wpst23'
ENC2_OA1 = "16.125.77.80"
ENC3 = 'wpst26'
ENC3_OA1 = "16.125.79.45"
# Interconnects
ENC1ICBAY1 = '%s, interconnect 1' % ENC1
ENC1ICBAY2 = '%s, interconnect 2' % ENC1
ENC1ICBAY3 = '%s, interconnect 3' % ENC1
ENC1ICBAY4 = '%s, interconnect 4' % ENC1
ENC1ICBAY5 = '%s, interconnect 5' % ENC1
ENC1ICBAY6 = '%s, interconnect 6' % ENC1
ENC2ICBAY1 = '%s, interconnect 1' % ENC2
ENC2ICBAY2 = '%s, interconnect 2' % ENC2
ENC2ICBAY3 = '%s, interconnect 3' % ENC2
ENC2ICBAY4 = '%s, interconnect 4' % ENC2
ENC2ICBAY5 = '%s, interconnect 5' % ENC2
ENC2ICBAY6 = '%s, interconnect 6' % ENC2
ENC3ICBAY1 = '%s, interconnect 1' % ENC3
ENC3ICBAY2 = '%s, interconnect 2' % ENC3
ENC3ICBAY3 = '%s, interconnect 3' % ENC3
ENC3ICBAY4 = '%s, interconnect 4' % ENC3
ENC3ICBAY5 = '%s, interconnect 5' % ENC3
ENC3ICBAY6 = '%s, interconnect 6' % ENC3
# Server Hardware
ENC1SHBAY1 = '%s, bay 1' % ENC1    # BL465c Gen8
ENC1SHBAY2 = '%s, bay 2' % ENC1    # BL465c Gen8
ENC1SHBAY3 = '%s, bay 3' % ENC1    # BL465c Gen8
ENC1SHBAY4 = '%s, bay 4' % ENC1    # BL420c Gen8
ENC1SHBAY5 = '%s, bay 5' % ENC1    # BL460c Gen9
ENC1SHBAY6 = '%s, bay 6' % ENC1    # BL460c G6
ENC1SHBAY8 = '%s, bay 7' % ENC1    # BL495c G5
ENC1SHBAY14 = '%s, bay 14' % ENC1  # BL460c Gen10
ENC1SHBAY16 = '%s, bay 16' % ENC1  # BL460c Gen10
ENC2SHBAY1 = '%s, bay 1' % ENC2    # BL465c Gen8
ENC2SHBAY2 = '%s, bay 2' % ENC2    # BL465c Gen8
ENC2SHBAY3 = '%s, bay 3' % ENC2    # BL465c Gen8
ENC2SHBAY4 = '%s, bay 4' % ENC2    # BL420c Gen8
ENC2SHBAY5 = '%s, bay 5' % ENC2    # BL460c Gen9
ENC2SHBAY6 = '%s, bay 6' % ENC2    # BL460c G6
ENC2SHBAY7 = '%s, bay 7' % ENC2    # BL2x220c G5
ENC2SHBAY10 = '%s, bay 10' % ENC2  # BL460c Gen10
ENC2SHBAY16 = '%s, bay 16' % ENC2  # BL460c Gen10
ENC3SHBAY1 = '%s, bay 1' % ENC3    # BL465c Gen8
ENC3SHBAY2 = '%s, bay 2' % ENC3    # BL465c Gen8
ENC3SHBAY3 = '%s, bay 3' % ENC3    # BL465c Gen8
ENC3SHBAY4 = '%s, bay 4' % ENC3    # BL420c Gen8
ENC3SHBAY5 = '%s, bay 5' % ENC3    # BL460c Gen9
ENC3SHBAY7 = '%s, bay 7' % ENC3    # BL660c Gen9
ENC3SHBAY8 = '%s, bay 8' % ENC3    # BL660c Gen8
ENC3SHBAY9 = '%s, bay 9' % ENC3    # BL460c G7
ENC3SHBAY10 = '%s, bay 10' % ENC3  # BL465c G7
# LIGs and EGs
LIG1_NAME = 'LIG22'
EG1_NAME = 'EG22'
LIG2_NAME = 'LIG23'
EG2_NAME = 'EG23'
LIG3_NAME = 'LIG26'
EG3_NAME = 'EG26'

# Name prefixes
NAME_PREFIX = 'OVF2101-C7000-'
PROFILE_NAME_PREFIX = NAME_PREFIX
# SH
SERVER = ENC2SHBAY16
GEN9_SERVER = ENC1SHBAY5
# Profile
PROFILE_NAME = PROFILE_NAME_PREFIX + 'pts2-profile'
PROFILE_SERVER = SERVER
PROFILE_EG = EG2_NAME
PTS2_PROFILE_NAME = PROFILE_NAME_PREFIX + 'pts2-profile'
PTS2_PROFILE_SERVER = SERVER
PTS2_PROFILE_EG = EG2_NAME

suite_setup_profile = {
    "type": SERVER_PROFILE_TYPE, "name": PROFILE_NAME,
    "serverHardwareUri": 'SH:' + PROFILE_SERVER, "enclosureGroupUri": 'EG:' + PROFILE_EG,
    "iscsiInitiatorNameType": "AutoGenerated", "serialNumberType": "Virtual", "macType": "Virtual", "wwnType": "Virtual", "affinity": "Bay",
    "connectionSettings": {"connections": []},
    "boot": {"manageBoot": False, "order": []},
    "bootMode": {"manageMode": False, "mode": None, "secureBoot": "Unmanaged", "pxeBootPolicy": None},
    "firmware": {"manageFirmware": False, },
    "bios": {"manageBios": False, "overriddenSettings": []},
    "sanStorage": {'manageSanStorage': False, 'volumeAttachments': []},
    "hideUnusedFlexNics": True, "osDeploymentSettings": None,
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [
            {
                "deviceSlot": "Embedded",
                "mode": "Mixed",
                "initialize": True,
                "importConfiguration": False,
                "driveWriteCache": None,
                "logicalDrives": []
            }
        ]
    },

}

pts2_profile_create = {
    "type": SERVER_PROFILE_TYPE, "name": PTS2_PROFILE_NAME,
    "serverHardwareUri": 'SH:' + PTS2_PROFILE_SERVER, "enclosureGroupUri": 'EG:' + PTS2_PROFILE_EG,
    "iscsiInitiatorNameType": "AutoGenerated", "serialNumberType": "Virtual", "macType": "Virtual", "wwnType": "Virtual", "affinity": "Bay",
    "connectionSettings": {"connections": []},
    "boot": {"manageBoot": False, "order": []},
    "bootMode": {"manageMode": False, "mode": None, "secureBoot": "Unmanaged", "pxeBootPolicy": None},
    "firmware": {"manageFirmware": False, },
    "bios": {"manageBios": False, "overriddenSettings": []},
    "sanStorage": {'manageSanStorage': False, 'volumeAttachments': []},
    "hideUnusedFlexNics": True, "osDeploymentSettings": None,
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [
            {
                "deviceSlot": "Embedded",
                "mode": "Mixed",
                "initialize": True,
                "importConfiguration": False,
                "driveWriteCache": "Enabled",
                "logicalDrives": [
                    {
                        "name": "LD1",
                        "raidLevel": "RAID0",
                        "bootable": False,
                        "numPhysicalDrives": 1,
                        "driveTechnology": "SasHdd",
                        "sasLogicalJBODId": None,
                        "accelerator": "ControllerCache",
                    },
                    {
                        "name": "LD2",
                        "raidLevel": "RAID0",
                        "bootable": False,
                        "numPhysicalDrives": 1,
                        "driveTechnology": "SasHdd",
                        "sasLogicalJBODId": None,
                        "accelerator": "ControllerCache",
                    }
                ]
            }
        ]
    }
}

suite_setup_profiles = [suite_setup_profile.copy()]

pts2_profiles_create = [pts2_profile_create.copy()]
