# Login Credentials
admin_credentials = {'userName': 'Administrator', 'password': 'wpsthpvse1'}

# Error Message
Invalid_key_length = 'Certificate validation failed.'
Invalid_certificate_less_than_1024 = 'Please import valid certificate and try again.'

# Server Name
OpenLDAP_self_signed_server_name = '16.114.222.3'
OpenLDAP_rootCA_server_name = '16.114.222.3'
OpenLDAP_subCA_server_name = '16.114.222.3'
AD_rootCA_server_name = '16.125.77.30'
AD_subCA_server_name = '16.125.77.30'
Repo_server_self_signed_server_name = '16.114.220.138'
Repo_server_rootCA_server_name = '16.114.220.138'
Repo_server_subCA_server_name = '16.114.220.138'
Expired_self_signed_server_name = '16.114.222.3'
Key_length_less_than_1024_server_name = '16.114.222.3'
Key_length_grater_than_4096_server_name = '16.114.222.3'

# Remote server IP
OpenLDAP_rootCA_server_with_Port = '16.114.222.3:636'
OpenLDAP_self_signed = ['%s:636' % OpenLDAP_self_signed_server_name]
OpenLDAP_subCA_signed = ['%s:636' % OpenLDAP_subCA_server_name]
AD_rootCA_signed = ['%s:636' % AD_rootCA_server_name]
AD_subCA_signed = ['%s:636' % AD_subCA_server_name]
Repo_server_self_signed = ['%s' % Repo_server_self_signed_server_name]
Repo_server_rootCA_signed = ['%s' % Repo_server_rootCA_server_name]
Repo_server_subCA_signed = ['%s' % Repo_server_subCA_server_name]
Expired_self_signed = ['%s:636' % Expired_self_signed_server_name]
Key_length_less_than_1024 = ['%s:636' % Key_length_less_than_1024_server_name]

# Alias Name/Friendly Name of Trust Store
Delete_OpenLDAP_self_signed = 'OpenLDAP_self_signed'
Delete_rootCA_signed = ['AD_RootCA']
Delete_LDAP_rootCA_signed_certs = ['LDAP_RootCA', 'LDAP_RootCA_1024', 'LDAP_RootCA_4096', 'HP TestHead Root']
Delete_LDAP_subCA_signed = ['RootCA', 'SubCA1', 'SubCA2', 'SubCA3', 'SubCA4', 'SubCA5', 'SubCA6', 'SubCA7', 'SubCA8']
Delete_repo_server_self_signed = 'Repo_server_self_signed'

# LDAP RootCA&&SubCA certificate
LDAP_RootCA_certificate = "-----BEGIN CERTIFICATE-----\nMIIEczCCA1ugAwIBAgIJAIieaG9LaZxaMA0GCSqGSIb3DQEBCwUAMGsxCzAJBgNV\nBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRIwEAYDVQQHDAlQYWxvIEFsdG8x\nGDAWBgNVBAoMD0hld2xldHQtUGFja2FyZDEZMBcGA1UEAwwQSFAgVGVzdEhlYWQg\nUm9vdDAgFw0xODA2MjcyMTIyNTVaGA8yMTE4MDYwMzIxMjI1NVowazELMAkGA1UE\nBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEY\nMBYGA1UECgwPSGV3bGV0dC1QYWNrYXJkMRkwFwYDVQQDDBBIUCBUZXN0SGVhZCBS\nb290MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0mKKQkAOWK2d0RMt\ntCY+2wjxKX7q14XcuO+62YqUIiTgogwnW7Ef3NC10Nm8MbMKvz2stLZoRvFhyUCs\nlFhk/Ntd5nw+HBRRNBu7dkxIR/lLTd6fLBAUt31uRDyGYQU/Zmr0842s/U7zppd9\nedLRLjN7IreyThtfjSbKpq5BustIhOrrANrLt1moFiC4Em/6baRFTVvfe5kj5U5Z\nmALqcQ7QFc6ezsh5PvosAC5OZc5pE9L8sC0czPjdOTcQS3UPc3GShCg1MUArv5Bp\nPwEDVc1+ncuEmArxbgSb8N9tgC1x1il7GdHnRqqw78Zqrh5ncH5SGt9DAqh1vKfE\nxNh36QIDAQABo4IBFjCCARIwHQYDVR0OBBYEFKoBlOnbtZR/cCdBqPtorHX4EJI+\nMIGdBgNVHSMEgZUwgZKAFKoBlOnbtZR/cCdBqPtorHX4EJI+oW+kbTBrMQswCQYD\nVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRv\nMRgwFgYDVQQKDA9IZXdsZXR0LVBhY2thcmQxGTAXBgNVBAMMEEhQIFRlc3RIZWFk\nIFJvb3SCCQCInmhvS2mcWjALBgNVHQ8EBAMCAbYwDAYDVR0TBAUwAwEB/zA2Bggr\nBgEFBQcBAQQqMCgwJgYIKwYBBQUHMAGGGmh0dHA6Ly9sb2NhbGhvc3Q6MjU2MC9v\nY3NwMA0GCSqGSIb3DQEBCwUAA4IBAQCD4ecmZQCcmepykKNAnXnXbDwCBsHze13b\niuOn0I+eHi7nmam9vU5YgnpVo3U1aOOE+e9RV0y9U00yL4YbTJM9D72RF/0TAREJ\nffFvvWqNmA4CoJ1n0AZ+TIT/jS76y7A3ToDvtPB7do+hG+7a1gurmyvgSZwP83Va\nhusmK1FEAv/d7c+40QRlTfPcNVggGYlsPF5tUtyq2DhzfQVPkXjULgAm7P0M5d9+\nTFOYw6zKptgpIAoM7CVRTx9VTpOiHzUl2cffdlia+GzPKKIyKjfOettv+0VVSr5L\nOm0WU9D0QVxK1/sW3OfWdTlv+LlybPv8WUjdp49KZsOuaYLD9Fm4\n-----END CERTIFICATE-----"
SubCA1_certificate = "-----BEGIN CERTIFICATE-----\nMIIEHjCCAwagAwIBAgICWOMwDQYJKoZIhvcNAQELBQAwazELMAkGA1UEBhMCVVMx\nEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEYMBYGA1UE\nCgwPSGV3bGV0dC1QYWNrYXJkMRkwFwYDVQQDDBBIUCBUZXN0SGVhZCBSb290MCAX\nDTE4MDYyNzIxMjI1NVoYDzIxMTgwNjAzMjEyMjU1WjBuMQswCQYDVQQGEwJVUzET\nMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRvMRgwFgYDVQQK\nDA9IZXdsZXR0LVBhY2thcmQxHDAaBgNVBAMME0hQIFRlc3RIZWFkIGludGVyLTEw\nggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAaNkQ/boCSJi0d+TYUovr\nFkxMtjQ//TI/IS7WlpmYwwfIylT4yCVYjMxGstSF15YG3spPw1zIXfdxqFj5jqyj\nioJGodhXa7xH46UK5Ewte2+laHSd2KQCUhoWJScI7BjKOJmjhPipouS438ygl6KX\np24Kn9f6j/1x9K3YS8mhawOpA3AGJQ4Et9BMwg+VxR4KbD/J5fxoIf62b8Bm5yzl\nrrIxctawBpemxCctzrOMDPq7xgl5KwUMNh+pCKYf5fbuYnqsYoISYtTbT+6ABYmM\nHSVKRp7r4jKbEIgfSqbFkSHGtiR8KglNl5/DFv4Y8wZ0BeIoU7mIiHiu+6NfBXrd\nAgMBAAGjgcYwgcMwHQYDVR0OBBYEFPAcauqjokDg7axmDF6r6Ec+spA+MB8GA1Ud\nIwQYMBaAFKoBlOnbtZR/cCdBqPtorHX4EJI+MA8GA1UdEwEB/wQFMAMBAf8wDgYD\nVR0PAQH/BAQDAgGGMCgGA1UdHwQhMB8wHaAboBmGF2h0dHA6Ly9sb2NhbGhvc3Qv\nY2EuY3JsMDYGCCsGAQUFBwEBBCowKDAmBggrBgEFBQcwAYYaaHR0cDovL2xvY2Fs\naG9zdDoyNTYwL29jc3AwDQYJKoZIhvcNAQELBQADggEBAG2DIJ3rlc79hO5K9dYU\nvuZGtmsSl6HLBUSwjW+ts0W+TzoReWekWigxxCIH/qQEp3Gv3INKIBEos4cfvCEw\nepEFsjMOZ/Ol9At9qVM1Hy1MzdBclQjhbQSfkPGuV+cLjWyZmk+pvnNTBp4GqtPY\nBaeGGLbFG7gWduYBetsEEZMhkiKbFeOK4bsLdFdbJz2v9mmOIE5qFkn/xnDAnMvr\npxuNWyPMvr5CJWsns1KyUKuO98Hph03O8kFdoW123F5KHDJsvt3KhT8oyMn0DZWM\nYPgNzu27whlispHC4+Sd/9HcWIJhyysklYIKbrCgSDDo2V9pLruwTGpo+fNjyAfq\n4PE=\n-----END CERTIFICATE-----"
SubCA2_certificate = "-----BEGIN CERTIFICATE-----\nMIIEITCCAwmgAwIBAgICJ0owDQYJKoZIhvcNAQELBQAwbjELMAkGA1UEBhMCVVMx\nEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEYMBYGA1UE\nCgwPSGV3bGV0dC1QYWNrYXJkMRwwGgYDVQQDDBNIUCBUZXN0SGVhZCBpbnRlci0x\nMCAXDTE4MDYyNzIxMjI1NVoYDzIxMTgwNjAzMjEyMjU1WjBuMQswCQYDVQQGEwJV\nUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRvMRgwFgYD\nVQQKDA9IZXdsZXR0LVBhY2thcmQxHDAaBgNVBAMME0hQIFRlc3RIZWFkIGludGVy\nLTIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDFVUdL1+wcrK8Yq1og\nVvWbmghJ3mSH+xqUIzW1F2GE1exa/2V+ow2p7YwvD+Yv8YMXtJK3nxIiTDvYiLt2\nggdvhKCqDezm24mXE+m6HZWlm74U3LYSrFB/zmw12KMYM3qqzKJv36TKt9UTG9WZ\ne6ybRLiVy5E+lkVPOdE5x/36WysZQftyhFzeuQjnErDzVYRdwuwo0vy/U0Oyqf43\ntJqQV98LWjJc6NBGuvbQvnIDcjE6Ed8cgNN2nZ/5JfSsvVv67AlseeYTdPzbmo9u\nR8M4EU/tQVVJGm+phziJxfjEtiU+GLB6ItFGQfDgeAFRzBu7PKNWzVeMNGt2u6ad\nfbKtAgMBAAGjgcYwgcMwHQYDVR0OBBYEFDJXqfIciJP1M2VHDK8z2jPa8tspMB8G\nA1UdIwQYMBaAFPAcauqjokDg7axmDF6r6Ec+spA+MA8GA1UdEwEB/wQFMAMBAf8w\nDgYDVR0PAQH/BAQDAgGGMCgGA1UdHwQhMB8wHaAboBmGF2h0dHA6Ly9sb2NhbGhv\nc3QvY2EuY3JsMDYGCCsGAQUFBwEBBCowKDAmBggrBgEFBQcwAYYaaHR0cDovL2xv\nY2FsaG9zdDoyNTYwL29jc3AwDQYJKoZIhvcNAQELBQADggEBAFXBa5kZSeX/GkXS\nNhagoLa1pMhNTLpk5/1ti/fRy4TLu9qpS84AHJC5zdTesyh/Ys/6BhydrYcAqC/g\nv61nH5QumqSpnaiLnuqmOHleUceuIEEmRtYBYNpIHQnvJ3lhLX1DFNzCmp0hY8Zl\nmpYj6NFkc3NtP4K46DrcV8OyDyMTZAKQwlEnDrRErhkL8v8HCY96PHCWayAw9cXK\nU4QaIyGy0nRYBRHAm2IPUoTJBiDK6BMamX0trEpuT56YOLGglWsiMQwlXWzjs8E+\nJI33hQPXuAR6ddZNf9WgC7kfbLEIqpOiR9Pk+O5JT7rSUMsF9M36PeVRqURXrG06\nFFEzRE4=\n-----END CERTIFICATE-----"
SubCA3_certificate = "-----BEGIN CERTIFICATE-----\nMIIEITCCAwmgAwIBAgICbsIwDQYJKoZIhvcNAQELBQAwbjELMAkGA1UEBhMCVVMx\nEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEYMBYGA1UE\nCgwPSGV3bGV0dC1QYWNrYXJkMRwwGgYDVQQDDBNIUCBUZXN0SGVhZCBpbnRlci0y\nMCAXDTE4MDYyNzIxMjI1NloYDzIxMTgwNjAzMjEyMjU2WjBuMQswCQYDVQQGEwJV\nUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRvMRgwFgYD\nVQQKDA9IZXdsZXR0LVBhY2thcmQxHDAaBgNVBAMME0hQIFRlc3RIZWFkIGludGVy\nLTMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCv96iHGDulf3KpM/+/\nQaQ4wBd/tsZ4H+6i983qkgsea49TqloIxR5SVrIDMvNGJ+ShLXxv7gTMukEE4G+z\nfk6sDsx9Z2NqbfMfEgFM1TDeVPaoBSFmdi92hB2hIFttjgZYdDD7sOrFAb0vHusT\nszimNYD8O85gt20DP2JiqWiUw0WOjG3UHpIIU2PQzdF+chzEggAJ/JXWXOsJg4t7\nvoFptbi2wlxqFZbbGofUM8NDYgGw64sdKHCpPFOBJFYQVKs6mv4skeS4uZzo2R41\nngcX+r8E+qwOtvyPCmUPofcLsqerWAo8+oTlNrYrEXd41Rfz4eNwb8UmLac/FL9C\nbmbbAgMBAAGjgcYwgcMwHQYDVR0OBBYEFEvNumU9JX6cmBpr6JwcNeCvoh5pMB8G\nA1UdIwQYMBaAFDJXqfIciJP1M2VHDK8z2jPa8tspMA8GA1UdEwEB/wQFMAMBAf8w\nDgYDVR0PAQH/BAQDAgGGMCgGA1UdHwQhMB8wHaAboBmGF2h0dHA6Ly9sb2NhbGhv\nc3QvY2EuY3JsMDYGCCsGAQUFBwEBBCowKDAmBggrBgEFBQcwAYYaaHR0cDovL2xv\nY2FsaG9zdDoyNTYwL29jc3AwDQYJKoZIhvcNAQELBQADggEBAB//k8CfJ5whixwa\nEnp4TCDNuRny0eO/jhBsGfOT7h7i2on1li7tNtTCpTgG/JFMkb/ergwSCHgq01zR\n6Jo9YBJlYi6BLZ4UG1cQGFPbWrx9sWsqatqmS3BmSclhhhxxGJWZnSFI9mKPJ+gN\nysD05V+KUaqm+P24dJN1UGhwS6NK6wV0UJMGCRTvFR4DcmBe5v5ngUUrC22pyp7v\nk/mCu1c6PZL4It0ct/TVM8w9DQt2cLWJtLV83OMKcS27N5ouzuS0zXIX0+cM1MkK\nqydkG6KtukrnSXsYfgJeuUaBKYumDcgvWXt/dUWK4KRLlBG/+JWBwZjR8tp0ijKJ\n/h7lABE=\n-----END CERTIFICATE-----"
SubCA4_certificate = "-----BEGIN CERTIFICATE-----\nMIIEITCCAwmgAwIBAgICFTAwDQYJKoZIhvcNAQELBQAwbjELMAkGA1UEBhMCVVMx\nEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEYMBYGA1UE\nCgwPSGV3bGV0dC1QYWNrYXJkMRwwGgYDVQQDDBNIUCBUZXN0SGVhZCBpbnRlci0z\nMCAXDTE4MDYyNzIxMjI1NloYDzIxMTgwNjAzMjEyMjU2WjBuMQswCQYDVQQGEwJV\nUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRvMRgwFgYD\nVQQKDA9IZXdsZXR0LVBhY2thcmQxHDAaBgNVBAMME0hQIFRlc3RIZWFkIGludGVy\nLTQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTz2kHp4nl07Dt73DF\n24/jAgrOoCBZfY59aHoc/5eBAk9t8Sm60IsO0d60xPJMbDtZhyZPr4TZn7cdUHDj\nCdBHJZOHnFES3iJArbq0vSu+pEfWSKyyq4ryFKIc5gcUrmEfGWkHCGEHHgMaBTfl\nD7giWsGMtY7SeWpg0vCSXM6Lv4/wXxUhrDRkPUzP889usrvSLvbCycmb1WhH95PN\njB7B57MRQibQFje70LAxtPAlgVKyTqOVh9THzOZww5M0canZ/TTZV3XX9E9WPVIu\nrhwgSgRp/YB5odTEjkveqMPd+GqMBl+xCtt9vycZxr84mremaGXFJ03hdcB29lit\nzQ/HAgMBAAGjgcYwgcMwHQYDVR0OBBYEFA8FhK2LlCuQfyG1ifmYow7fbyHBMB8G\nA1UdIwQYMBaAFEvNumU9JX6cmBpr6JwcNeCvoh5pMA8GA1UdEwEB/wQFMAMBAf8w\nDgYDVR0PAQH/BAQDAgGGMCgGA1UdHwQhMB8wHaAboBmGF2h0dHA6Ly9sb2NhbGhv\nc3QvY2EuY3JsMDYGCCsGAQUFBwEBBCowKDAmBggrBgEFBQcwAYYaaHR0cDovL2xv\nY2FsaG9zdDoyNTYwL29jc3AwDQYJKoZIhvcNAQELBQADggEBADmDsSHQsmXrYZQL\nOJwqjw+qP/qTSUse1cB/e1X6Gz9sweQDaKQDQID2KA2/MmeG85J9PFKm6FUUqYPB\n+5QF2kYwgkXLtZfdGIVXLgNK4fLg9PraFac5moj8A5aPvMF9tqX6TzBUUB1oFh73\nhOuRKpe73M0op3uRRh1O2st8RcXN1/DsZcSx2cVoJwKzmN8qRPjUcXgbmHt6/bSQ\nCZXd7n3JnEBVah4rA3u5RSq/v/8J0Qs4tMc85pQZn6eJ97V2Mu6f4hq3rS8sEfUQ\nSZ+3x+lV5HB1wEWCGwWK9geJXulz44r7CGA7H30jpJoJ8MYQ8lOZEuKcel3PdH0K\nZzMwaP4=\n-----END CERTIFICATE-----"
SubCA5_certificate = "-----BEGIN CERTIFICATE-----\nMIIEITCCAwmgAwIBAgICA4cwDQYJKoZIhvcNAQELBQAwbjELMAkGA1UEBhMCVVMx\nEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEYMBYGA1UE\nCgwPSGV3bGV0dC1QYWNrYXJkMRwwGgYDVQQDDBNIUCBUZXN0SGVhZCBpbnRlci00\nMCAXDTE4MDYyNzIxMjI1NloYDzIxMTgwNjAzMjEyMjU2WjBuMQswCQYDVQQGEwJV\nUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRvMRgwFgYD\nVQQKDA9IZXdsZXR0LVBhY2thcmQxHDAaBgNVBAMME0hQIFRlc3RIZWFkIGludGVy\nLTUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/vjpzBSVd3OyZPbUU\nQ9LerHi2TOlnZPw736iAdEgIaQKvvXCFdKQvvPZxjraMkBTmDDeBX7BCt59XoKNU\n2J/VuyIhCWB0J5nvGvt7EBj8dO3jlyP+yv3MFte9eJRlNB9L6LY3b2Cj5x3xGbYF\nr43mN6dINJ3PKv1YknUyoPaaKABseZH+TQFP/ajsmoAVODQJMAG4BY8Of+Ddw70t\nHJlyBd/PA8KMLG2/+HE12oGWNck1WfSh+4H2nWbCiQJetU2lXvBms/bU0EcrR7Ya\nYya+pb/TVtSog5NSd2YoRk9dOrIdjh25fI6IXS/cjPdHR8wVLwuBp8FOZiGxl87C\nX9/BAgMBAAGjgcYwgcMwHQYDVR0OBBYEFMGHx1lhKNKbXk4CdWgIQoe0b3/jMB8G\nA1UdIwQYMBaAFA8FhK2LlCuQfyG1ifmYow7fbyHBMA8GA1UdEwEB/wQFMAMBAf8w\nDgYDVR0PAQH/BAQDAgGGMCgGA1UdHwQhMB8wHaAboBmGF2h0dHA6Ly9sb2NhbGhv\nc3QvY2EuY3JsMDYGCCsGAQUFBwEBBCowKDAmBggrBgEFBQcwAYYaaHR0cDovL2xv\nY2FsaG9zdDoyNTYwL29jc3AwDQYJKoZIhvcNAQELBQADggEBALSgyKZ3DtkA8L81\nDVNfgyMK/+5+FfKqozdcQtRZq5kgEXJ7VWV+jrWYQOSK5q7S4/TndCRBKzMvHnsn\nBc+FWBlqN1AIEqo5A0JFN5z/3S0WfNWJo0QvWOCcDM/Zj7sFo5X5+yUBhHTVgH66\nDKR0TE38mthK56EvifgQmF0/P6Q0LtfGNd7JZuCMZP46bCgYJjMLnG4pHkNEqK2Y\nVXDr4MIxApTiYlABJOe9RdjXeoXPedwFv/5a9ptnGH8F2FaUAKodoVpR7lKV1Ff4\nTxe8RokXFZlN8xbtG0Rm6LMhxK9VRaE1IlG8bCiVpSCNUjittDCOel4PNMh6FUkg\nbWR/wCc=\n-----END CERTIFICATE-----"
SubCA6_certificate = "-----BEGIN CERTIFICATE-----\nMIIEITCCAwmgAwIBAgICTpEwDQYJKoZIhvcNAQELBQAwbjELMAkGA1UEBhMCVVMx\nEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEYMBYGA1UE\nCgwPSGV3bGV0dC1QYWNrYXJkMRwwGgYDVQQDDBNIUCBUZXN0SGVhZCBpbnRlci01\nMCAXDTE4MDYyNzIxMjI1NloYDzIxMTgwNjAzMjEyMjU2WjBuMQswCQYDVQQGEwJV\nUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRvMRgwFgYD\nVQQKDA9IZXdsZXR0LVBhY2thcmQxHDAaBgNVBAMME0hQIFRlc3RIZWFkIGludGVy\nLTYwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3Byt3jdu6Foujrogd\nJSrdMOUXGa4JJhQkTo5r+eIdQiJnkY29bGz30Cmb79le/ATtCrdRAgOqXETY4j0K\nSejmFvzl5r4G0W3XryofSzO6/NO+bfsimzzC8OGXxRfzZuLyYZCBGhInuCoNrewA\nRxmd2ltEuJQZ6yc7Dd10OR5nTnGzWcaH/0Gd8oP4THKBLc29vIck0QMn/UGybznr\nXgZAKD2hDUinUQRrrjZW8AI2h+Xkn4Y48+9y7OFl+YYxcCPsjuRgE9zTydJmXMCH\nlmMr6hYwy0ExawRZapwHFOw++aq6ns/bgyRWXsnzDG4ncgBiUGZGWKDOJ2NL3Lk+\nYY8JAgMBAAGjgcYwgcMwHQYDVR0OBBYEFLHnY7Bx7Q3pQj/dXnv8WDGG1veqMB8G\nA1UdIwQYMBaAFMGHx1lhKNKbXk4CdWgIQoe0b3/jMA8GA1UdEwEB/wQFMAMBAf8w\nDgYDVR0PAQH/BAQDAgGGMCgGA1UdHwQhMB8wHaAboBmGF2h0dHA6Ly9sb2NhbGhv\nc3QvY2EuY3JsMDYGCCsGAQUFBwEBBCowKDAmBggrBgEFBQcwAYYaaHR0cDovL2xv\nY2FsaG9zdDoyNTYwL29jc3AwDQYJKoZIhvcNAQELBQADggEBAFbxiz1+EhZNZByx\nOer5aDVePubuxlPAzPbblDNxnCYVnbSPv0HV1Nd0LpnhSAU1Be3GW5+WMeGvBXUX\nz9iI+wNJafCkfzXAN2+g4sm99tv6KOhaJ2jinC6zbtmyOhP/mmPXf1Xj4LW5rM7C\n+APov8rm6OM0+4ZUHyhBhdDL/20mtKvH5arC0ax6RPnUUMXjiWk2t3DD26kBw6KI\npXNLaLQD6DyhdeI1bFDd7UMT2J5yDDzpWIyebxAHcnzNX3E4KZ8aXP1DaHAQsi1X\nhgo9/FBA56tLQwYHQa5NaQKcQ21fIs95MzucvoWp7R7HSN1ujmvuttahbyYcnqer\ntpt6LHs=\n-----END CERTIFICATE-----"
SubCA7_certificate = "-----BEGIN CERTIFICATE-----\nMIIEITCCAwmgAwIBAgICLicwDQYJKoZIhvcNAQELBQAwbjELMAkGA1UEBhMCVVMx\nEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEYMBYGA1UE\nCgwPSGV3bGV0dC1QYWNrYXJkMRwwGgYDVQQDDBNIUCBUZXN0SGVhZCBpbnRlci02\nMCAXDTE4MDYyNzIxMjI1NloYDzIxMTgwNjAzMjEyMjU2WjBuMQswCQYDVQQGEwJV\nUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRvMRgwFgYD\nVQQKDA9IZXdsZXR0LVBhY2thcmQxHDAaBgNVBAMME0hQIFRlc3RIZWFkIGludGVy\nLTcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDD8j/2/XYLBs24CfxV\njOfcF1d1HXzAe2cfse6MR5WPqJmk2rosEcOa2fdlTowACeC8FLeeQbYUOr8Trvxy\n1JdFKjp2fViueqO731DqqdwkfDl6uNlHGXDKFZJ51nYiMpV9lK2cGb55wDh4RYk2\nGM5SqqWnD7v6c46O6Jaw0zxIgtVJLd156OtR7Ki9IsA+3n1e6d/I3+JJias4jE5d\nRD2FDaE6A6mJTMS+qL2X9gde9rtYWS/zS2WajDk5xjIe1lyH4OLPUjCLRabgY20F\nMg2OdvANTPbbYfT8gbkzReVIdXMtkfGyDYnjuZSW9mvujoCA8sND1Xo6TiGENtip\noXO3AgMBAAGjgcYwgcMwHQYDVR0OBBYEFNDwaAslWUqX+v89rB4mKsJJ02wnMB8G\nA1UdIwQYMBaAFLHnY7Bx7Q3pQj/dXnv8WDGG1veqMA8GA1UdEwEB/wQFMAMBAf8w\nDgYDVR0PAQH/BAQDAgGGMCgGA1UdHwQhMB8wHaAboBmGF2h0dHA6Ly9sb2NhbGhv\nc3QvY2EuY3JsMDYGCCsGAQUFBwEBBCowKDAmBggrBgEFBQcwAYYaaHR0cDovL2xv\nY2FsaG9zdDoyNTYwL29jc3AwDQYJKoZIhvcNAQELBQADggEBAC6MR0NV/ik0D53Q\nNgkm4M1sONW0781pRFmDaT4l12muV3Xz2pbHZUUAXrjogDaKDJl5pSP+KHAahEv0\nRUZ+6PvHhFc3of2ALWQhfhzwy9VsFNwfhw7Cg89v/V0/tKI7zPn9Y2B74KUZGYoH\nH9bp8PpvXQpCJgcQ0YNOEt9JYB9tIEdxt1l21JgeHFkkSPHkutE/BSVvJy0TsL10\nMy9zlcvT4eTeyjv2r9an+AEOqV6R9EJg69vzd9Mn9u/NtOD5UsFUPbRj1fKNIAS/\nFCdC3QSExmEfaTDyZiUYMwbB3TeEdcflLoyxAcQyjQvf8xvNmsKvmYPenc6tJMkJ\nVHKap00=\n-----END CERTIFICATE-----"
SubCA8_certificate = "-----BEGIN CERTIFICATE-----\nMIIEITCCAwmgAwIBAgICH5EwDQYJKoZIhvcNAQELBQAwbjELMAkGA1UEBhMCVVMx\nEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEYMBYGA1UE\nCgwPSGV3bGV0dC1QYWNrYXJkMRwwGgYDVQQDDBNIUCBUZXN0SGVhZCBpbnRlci03\nMCAXDTE4MDYyNzIxMjI1NloYDzIxMTgwNjAzMjEyMjU2WjBuMQswCQYDVQQGEwJV\nUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRvMRgwFgYD\nVQQKDA9IZXdsZXR0LVBhY2thcmQxHDAaBgNVBAMME0hQIFRlc3RIZWFkIGludGVy\nLTgwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC0FXsH6D7HJZ5Ou+34\ns8JhKdxit8SXEC6S3d2MYj1NMIhiyIUblZcK6HUnymI0w2So+0chOetxai5wjnmD\ni9TTXf7hQp/kD1e+pc3ylkoJkInddTzMzaL0+6p53HazKbVBUG5GsKsOwe2/KPAK\nBD0UAWZd6/yuZbRGZFsAoYkUKGW1bsV2cTg8RhkgqR5fniHr+1zxqoev1SGol1L9\nm21JPmxMz28sKW5rC7sYu1ZY4Fszjm+x5qDI0sC3dC3Ho+l//kvyXwCtmgkpaSSC\nn4qzOKA1YKqkjghxcxJTfiSeVrU634INdbufn6PVS5/l98YSo4ijkM/ccazMeaUQ\n7hNJAgMBAAGjgcYwgcMwHQYDVR0OBBYEFMJYVcWFVYF45pNY767fZEdIKrpZMB8G\nA1UdIwQYMBaAFNDwaAslWUqX+v89rB4mKsJJ02wnMA8GA1UdEwEB/wQFMAMBAf8w\nDgYDVR0PAQH/BAQDAgGGMCgGA1UdHwQhMB8wHaAboBmGF2h0dHA6Ly9sb2NhbGhv\nc3QvY2EuY3JsMDYGCCsGAQUFBwEBBCowKDAmBggrBgEFBQcwAYYaaHR0cDovL2xv\nY2FsaG9zdDoyNTYwL29jc3AwDQYJKoZIhvcNAQELBQADggEBALh0KUHXiR4v6zv8\nA9zX2jnqlUbH+72dx9Wi8ACm0JiAdefsJgoSy1UG9uXastznwusII2B4B3gGTc0R\n1K5Y2RrUkZEEdu9Dd2nlOfxAdXrsbhkkGbAzlzQOK4o8qGBxZe2swsvZLGbuE5qG\nl3vHjucEceHdb3BheF2xwjh7QB7Oj/f4F5M3KqjXB897fhd6Fou1ZsO7hqatneF7\nrqwVqMWJ6oHpF7MvJymw6a/cKiHBeZczNyPeCJeEx7VasMfox7fPJCCtQI/gyka5\n8eiCIQ+jEAQhUk0ESXCkV4l1p+3581INuY8Bahzw0CPC4klrdDongSptUv05UUdK\n2cvj4h0=\n-----END CERTIFICATE-----"

# Certificates
OpenLDAP_self_signed_certificate = "-----BEGIN CERTIFICATE-----\nMIIDzTCCArWgAwIBAgIJAN2m6mDN6pPYMA0GCSqGSIb3DQEBCwUAMH0xCzAJBgNV\r\nBAYTAklOMQwwCgYDVQQIDANLQVIxDDAKBgNVBAcMA0JORzEMMAoGA1UECgwDSFBF\r\nMQ0wCwYDVQQLDARSSVNUMQ0wCwYDVQQDDARUZXN0MSYwJAYJKoZIhvcNAQkBFhdz\r\nYW50b3NocmV2YW5ha2lAaHBlLmNvbTAeFw0xODA2MjExNjAxMjFaFw0yMTA0MTAx\r\nNjAxMjFaMH0xCzAJBgNVBAYTAklOMQwwCgYDVQQIDANLQVIxDDAKBgNVBAcMA0JO\r\nRzEMMAoGA1UECgwDSFBFMQ0wCwYDVQQLDARSSVNUMQ0wCwYDVQQDDARUZXN0MSYw\r\nJAYJKoZIhvcNAQkBFhdzYW50b3NocmV2YW5ha2lAaHBlLmNvbTCCASIwDQYJKoZI\r\nhvcNAQEBBQADggEPADCCAQoCggEBANeoPjG5ar9SC0joYDEX+Rzc7iN+GF+0ouHv\r\nI6DqIWDmSTUEukOAL0rif6GkQ45RD2OfUqy/hPWSx6KLW4rX1Myhqk+kGA/6f91f\r\nLK36zZj5VXpYcrxBmQMXQhX2mZtfEqH56spbtqo8s5ndQddlB+vFQOAgp9bgIEbz\r\ntBkQx4FhXW+eF2ZxxAR4dxOQ/YtvHiXDrMV1SlzTyILEj86hei++wQ+gZ9AkCzC5\r\n/UNvg2cD91xP3Oom01mKJSgQ9op3i/gjGgQpDw9+pEmyl4uininiDXFKe8ObZN7G\r\n0OTboVS7gRfE7SLO489MVoPQfcY/rhLLlYJHiZfKfGT80ggOzCsCAwEAAaNQME4w\r\nHQYDVR0OBBYEFNslLsWUZiiWvGLsEp7ox1JFc+l3MB8GA1UdIwQYMBaAFNslLsWU\r\nZiiWvGLsEp7ox1JFc+l3MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB\r\nAAjc5YRIJ1LumB+ew2cKJpAzbM04crIYkDacgZTubtlRUviLYfj9HxFSXVvVnnH9\r\nx7rXNgfni9j3T6imJIFd70irtrSF0E5MAZW2KbJh7y2EyRulE370oM6EVs2Qs09q\r\nR6Wr6pP/OTcpALPPZM9kyddiy1n7npXJH5eQ53rSQqJt+zqlD5N/ISbTBh1CrTry\r\nto6WaE0KDp5XrALozbMs1BWQbAQIgHLFYvd1DD+bMdo0/7HNQBY3kw2mYblPZt5J\r\n3uALhbqZ5n3pi+DARSBYMSQIA2OV9TcmmREp0Y0YKfPJCG9oeb/C8R2Zo/38UQrL\r\n/RA15bYF7P6wYNIUniWQqIg=\r\n-----END CERTIFICATE-----"
OpenLDAP_rootCA_certificate = "-----BEGIN CERTIFICATE-----\nMIIEczCCA1ugAwIBAgIJAI7XSzQ4TOj1MA0GCSqGSIb3DQEBCwUAMGsxCzAJBgNV\r\nBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRIwEAYDVQQHDAlQYWxvIEFsdG8x\r\nGDAWBgNVBAoMD0hld2xldHQtUGFja2FyZDEZMBcGA1UEAwwQSFAgVGVzdEhlYWQg\r\nUm9vdDAgFw0xODA3MDIxOTQ4MTBaGA8yMTE4MDYwODE5NDgxMFowazELMAkGA1UE\r\nBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEY\r\nMBYGA1UECgwPSGV3bGV0dC1QYWNrYXJkMRkwFwYDVQQDDBBIUCBUZXN0SGVhZCBS\r\nb290MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq7vV/Y0rKa650fMj\r\nYPe8ZU7Y57YzeOkGcqUwf9yZSrsXO8OQaMs+U6adALWQFE0u/lJ0NABIixDUJHhy\r\nK1u1OKfI/kCdTmCdZWWjv2MaW7QYGRWehvnJQ82fR+MwaohALwKThswtgoHrv9Cf\r\nYPxlCZVag5nIeJKjjVopoG8lCFskaIab0yhGvI+F9VZecsXdGhKt94g1fzmMXus1\r\nqaiLqN0EDtdsRuEWvmzjcA9NQp+KMwnBLm2Bq2hdtVWZGFmvZLqcJY8vGe4QAWzU\r\n/QbvxOm5ezvKB0eFimZ2Du/3+lMJG3K+wi6Z8XeNFhCPLaa7bEJls4jDtxyjDCIY\r\nGtWtHQIDAQABo4IBFjCCARIwHQYDVR0OBBYEFCUnG1Uad+e8hggNN3YAUdTFmfVB\r\nMIGdBgNVHSMEgZUwgZKAFCUnG1Uad+e8hggNN3YAUdTFmfVBoW+kbTBrMQswCQYD\r\nVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRv\r\nMRgwFgYDVQQKDA9IZXdsZXR0LVBhY2thcmQxGTAXBgNVBAMMEEhQIFRlc3RIZWFk\r\nIFJvb3SCCQCO10s0OEzo9TALBgNVHQ8EBAMCAbYwDAYDVR0TBAUwAwEB/zA2Bggr\r\nBgEFBQcBAQQqMCgwJgYIKwYBBQUHMAGGGmh0dHA6Ly9sb2NhbGhvc3Q6MjU2MC9v\r\nY3NwMA0GCSqGSIb3DQEBCwUAA4IBAQBZ0vMd6CHrVJU5XBPhNcjreLJlddOQ1UAr\r\nEU4UMETNKcGjbvnT5nF96mRcVZVS9QyVkongG1JNHavzK0/t1GPSql8rlfZvXHnD\r\nVEssWIxhTexWGq2PPQOdlrICd9ptZx2IBPgXGchj1WcQV4fQtMjKtHNzSIf9od/m\r\nDQ/LFQMcvnLzKq3X+i8oR3EvQpsQMhrIpvDM79ZyVtl2EC0R0oqSHNn3H0UKoM8b\r\n0LAVpip5DUrrtO/2CXjl12m78hggUC1YRReLjS6fLk0vcz6/B9fm+CdCYSyuJyE2\r\n9IrHhIp7/hgZIBsapgZpsuuSHhTESSu0+MsbQlKeUzf+dzej5gof\r\n-----END CERTIFICATE-----"
OpenLDAP_rootCA_1024_certificate = "-----BEGIN CERTIFICATE-----\nMIIEczCCA1ugAwIBAgIJAM4EGGm7++JqMA0GCSqGSIb3DQEBCwUAMGsxCzAJBgNV\r\nBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRIwEAYDVQQHDAlQYWxvIEFsdG8x\r\nGDAWBgNVBAoMD0hld2xldHQtUGFja2FyZDEZMBcGA1UEAwwQSFAgVGVzdEhlYWQg\r\nUm9vdDAgFw0xODA3MDIxNjUzNDJaGA8yMTE4MDYwODE2NTM0MlowazELMAkGA1UE\r\nBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEY\r\nMBYGA1UECgwPSGV3bGV0dC1QYWNrYXJkMRkwFwYDVQQDDBBIUCBUZXN0SGVhZCBS\r\nb290MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoNYzYlMzK3lT0Ru2\r\nFjlA/Q8iHQMhdUx0dB4qknN4Q4KO/TcHbbCvo17oBcjt+KIlq8jTaMHJxyiZyO6o\r\nb/4O0lGqxS4VFxj8OIyg0EX5H5EId80Y18owM0oUL8002ysZXjnvR+mAZowNlQDG\r\nAVWtv9r4P42r6euV9E1i7IhDvixnzVHCfrv6d0+9OpfVYlwouesTyrEGJRCmrS+D\r\nSNg63+49rra0iubhl23xJIEyi+OdqsANg9ACAbJKTnVeXRchI0pQI99aN2dQzuTy\r\nnUq5d2lRg+9qTsoy1HRdX1WKjCwmjW5tVFSDDMVD6q5FpPZo9keXROCSuFwn4Cc/\r\nq550PwIDAQABo4IBFjCCARIwHQYDVR0OBBYEFE1LgK36+sVKEPx7y28NVXNGZmur\r\nMIGdBgNVHSMEgZUwgZKAFE1LgK36+sVKEPx7y28NVXNGZmuroW+kbTBrMQswCQYD\r\nVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRv\r\nMRgwFgYDVQQKDA9IZXdsZXR0LVBhY2thcmQxGTAXBgNVBAMMEEhQIFRlc3RIZWFk\r\nIFJvb3SCCQDOBBhpu/viajALBgNVHQ8EBAMCAbYwDAYDVR0TBAUwAwEB/zA2Bggr\r\nBgEFBQcBAQQqMCgwJgYIKwYBBQUHMAGGGmh0dHA6Ly9sb2NhbGhvc3Q6MjU2MC9v\r\nY3NwMA0GCSqGSIb3DQEBCwUAA4IBAQA9iRQG6YOBBVSBQEYpnrT/XUOwfED0gFBL\r\nll5PxfZw2fCa4mMVPTz6Dxz3Dx2usSFKgflvC6j76ex2dHHxI/vEfAyPiByB2p6f\r\njHK36qMUCTznqk7BYYIxZh5U//Lc5Tx2zGRNg8/LJLidx8Sm7v5i24+mkBGWiL0Z\r\nvqgZRuZwFNDhPP1S3C310DGi7legihQwT4/mGzrhOoE3Kleig6IqOQEdy9GGxekB\r\njMEIytUBhWjKOQ77xbd3DrPna+AJUeHdCZTjj9Hz/2eLS/DiMjQb04+v0ZCU7ubS\r\n3obCNSbHfWBJqmaJUeM4tuJVTd/GoPooOEHZcQ6l+/l1rChS+y+6\r\n-----END CERTIFICATE-----"
OpenLDAP_rootCA_4096_certificate = "-----BEGIN CERTIFICATE-----\nMIIEczCCA1ugAwIBAgIJAM9U9K4FnetLMA0GCSqGSIb3DQEBCwUAMGsxCzAJBgNV\r\nBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRIwEAYDVQQHDAlQYWxvIEFsdG8x\r\nGDAWBgNVBAoMD0hld2xldHQtUGFja2FyZDEZMBcGA1UEAwwQSFAgVGVzdEhlYWQg\r\nUm9vdDAgFw0xODA3MDIxNzAwMDVaGA8yMTE4MDYwODE3MDAwNVowazELMAkGA1UE\r\nBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEY\r\nMBYGA1UECgwPSGV3bGV0dC1QYWNrYXJkMRkwFwYDVQQDDBBIUCBUZXN0SGVhZCBS\r\nb290MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr2BhxVaqE4OWNxmV\r\nCJEP9togNQbsxxThiyfAXwj7hKLtYZeo7PlIZ5pWiDFdmy8tE5HOL9WEZB1oC3CP\r\nu2h3MqPwLaD3pvuxK+HC+D9+8OBGvsyq7nlMG+KF84NiDENLQjdkoTUKTCZbBaRy\r\nDopudjq+ITEBPUoA9CwgYZN3FixfBhokV26xoOggR5cLMc+hmxOHsAhoaUl4Jjkv\r\nW1C6bwPdtEBTYNGUpkS73XLEmtVFLkLwVrtF76TFZDLL/dOuTbcHOKx2AddsR5T4\r\noibJVud0mGlOKqy2YgLQY7DYIaOPJt7tZIfQtlf0ZRx35PvRM4PjwqeeBAXA3Sr6\r\nPr7PbwIDAQABo4IBFjCCARIwHQYDVR0OBBYEFG3wNDgCH16yfEOyuaJHkoozoveK\r\nMIGdBgNVHSMEgZUwgZKAFG3wNDgCH16yfEOyuaJHkoozoveKoW+kbTBrMQswCQYD\r\nVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRv\r\nMRgwFgYDVQQKDA9IZXdsZXR0LVBhY2thcmQxGTAXBgNVBAMMEEhQIFRlc3RIZWFk\r\nIFJvb3SCCQDPVPSuBZ3rSzALBgNVHQ8EBAMCAbYwDAYDVR0TBAUwAwEB/zA2Bggr\r\nBgEFBQcBAQQqMCgwJgYIKwYBBQUHMAGGGmh0dHA6Ly9sb2NhbGhvc3Q6MjU2MC9v\r\nY3NwMA0GCSqGSIb3DQEBCwUAA4IBAQBjxwWVoQMllM5X1WCC5ZtrBRzWVo7S7JFp\r\nzZj0L6z83YxKQUxZmYWiP5UuJg0jEVjFOBfJG7p8hAezhYgxfid8D4XIxqs7KaJJ\r\nojtci7uA4F8DvdzxHd8HuI+iwlmvdd5bOxNqY5quHwQwv/ZCSqDAyD4T/WrgXVtx\r\n/Ex9YkkpO/sqjRVgOT8n+j7wYKkAxRR+SvaCym3BeA81mCkZfNRGGiKZzv+J/yl+\r\nZ31b+BuU5dMs3ey3GLvhW+t9+Ls47ynxyM7uUAGdt0g/eFTWE92OoRWlJ1ZVC501\r\nrJrz9AkB1Aycz2ey4g3hZ7CZN17CL1Bsq4KRPDTdY+qQasnOKL0C\r\n-----END CERTIFICATE-----"
AD_rootCA_signed_certificate = "-----BEGIN CERTIFICATE-----\nMIIDrjCCApagAwIBAgIQPMm63L7kEbJKQ0QpKb/udzANBgkqhkiG9w0BAQUFADBJ\nMRMwEQYKCZImiZPyLGQBGRYDY29tMRYwFAYKCZImiZPyLGQBGRYGd3BzdEFEMRow\nGAYDVQQDExF3cHN0QUQtV1BTVC1BRC1DQTAeFw0xODA1MjUwOTI5NTRaFw0yMzA1\nMjUwOTM5NTNaMEkxEzARBgoJkiaJk/IsZAEZFgNjb20xFjAUBgoJkiaJk/IsZAEZ\nFgZ3cHN0QUQxGjAYBgNVBAMTEXdwc3RBRC1XUFNULUFELUNBMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvvsi5cFUBbB7yIqshTXWG98bb195qg3qNnvZ\nT6HDldEPryc0Tt5UXbMsI1swvQzDcbgOIGS51/fJlS68Dguu5cV03207grkpFfRl\n8AAyrxeftWW+4x8Hy2sp4WFsEOM3hwKBIYOUhBrzyUZUv3u/nj8bMPJ52UEyvqiT\n/XqgEFlCTdFX3vGMRVowN9jARFfA9AMACby8kGHkt+lsBbC0QEuMWiBd55mqlf3o\nlvbb+EWh1nd+mVfu4ghuVr4ztY1SjyXcs6Ji71LGjidhI2js/Kc/Mu8zqlitf1q2\nPrUobXXAln3Yq99tWLaAx+WgAZ3ZBJYwHHzR3HqPHe52lqun4wIDAQABo4GRMIGO\nMBMGCSsGAQQBgjcUAgQGHgQAQwBBMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8E\nBTADAQH/MB0GA1UdDgQWBBSl4IMWKKfP1EKAPFWvgFReUVq2ozASBgkrBgEEAYI3\nFQEEBQIDAwADMCMGCSsGAQQBgjcVAgQWBBR/wd/nomlY2SxW+cy7T5VoLZMT/zAN\nBgkqhkiG9w0BAQUFAAOCAQEAmLl8cFATJyUZ979i3ZhMcj1WV1QhlP3eU3bsKgkW\nD/n9Q2SbgWSbKw08m8F9KetBEmZdvAmfojcOPAww/xQrxc9gLCfpUhnaUDe4fpcV\nuAnU+S3osPj3CL5W9pIkeaXol/Dnj9BmNbD5OxvxtZbEF8E353ikcytMTKggIT4S\n3Bst+ayI3m1gI4KA9ZKjR4USxZ5TM7E/kJJZNtK0aVniWc7o2WhECw2dUe2ZzufQ\nR+DfY56kTewvTiVAA2w5/+85Ywf/8V1yy4E6Di6h63FN/LUXX2lZKnMftekjjuWz\nzH1KNRrV8HG2hvN8FqkVTAcnWEWyjr7omTLi+0bDhI1BVw==\n-----END CERTIFICATE-----\n"
AD_subCA_signed_certificate = "-----BEGIN CERTIFICATE-----\nMIIFpzCCBI+gAwIBAgIKHthUcwACAAAAKzANBgkqhkiG9w0BAQUFADBJMRMwEQYK\r\nCZImiZPyLGQBGRYDY29tMRYwFAYKCZImiZPyLGQBGRYGd3BzdEFEMRowGAYDVQQD\r\nExF3cHN0QUQtV1BTVC1BRC1DQTAeFw0xODA1MTcwNTEyMDlaFw0yMDA1MTcwNTIy\r\nMDlaMBcxFTATBgNVBAMTDDE2LjEyNS43Ny4zMDCCASIwDQYJKoZIhvcNAQEBBQAD\r\nggEPADCCAQoCggEBALWW0pnPr3lWLi4EOYqBA/tvKWD4/0ZeRBny9h8JRDmOXOaf\r\nkMpj6xiAAM76vTpY6LNKK04YpIj3l7LHVstQBX41ltPR02zOwkQpcu8RJPWlYCFt\r\nrqAy+H8QEysdxwkaQDITF4kWcBH+i2Eit+Svucl3x0Ui9LCnUrBZkzGmoKwKGizQ\r\nDSA2oaYcmIZ5B4YlNuTVnKqEUnTz7yuGkOikYM0xT0V+MjMb4Xbgt28I08CkjcTL\r\nKCkZhfYSUua9gB8ME/9PJpjS64z+qGVnrVtsNZ3hqEMVP4aKRwn6s38J7SGI4HRO\r\nDxyzUZZsd4RS6sE+aFOPxOFtJrxpeAoji3rT2n0CAwEAAaOCAsEwggK9MD0GCSsG\r\nAQQBgjcVBwQwMC4GJisGAQQBgjcVCO+mZIK9lmeGhZ0fh9CrfIOe1WGBeIGUkzuH\r\n9pF9AgFkAgEDMDIGA1UdJQQrMCkGBysGAQUCAwUGCisGAQQBgjcUAgIGCCsGAQUF\r\nBwMBBggrBgEFBQcDAjAOBgNVHQ8BAf8EBAMCBaAwQAYJKwYBBAGCNxUKBDMwMTAJ\r\nBgcrBgEFAgMFMAwGCisGAQQBgjcUAgIwCgYIKwYBBQUHAwEwCgYIKwYBBQUHAwIw\r\nHQYDVR0OBBYEFKTMuYKp0QPNkat1LxTs+MAEbXj8MB0GA1UdEQQWMBSCEndwc3Qt\r\nYWQud3BzdGFkLmNvbTAfBgNVHSMEGDAWgBRIO04qEVeUVikGs4nLlXBT/1HohDCB\r\n0QYDVR0fBIHJMIHGMIHDoIHAoIG9hoG6bGRhcDovLy9DTj13cHN0QUQtV1BTVC1B\r\nRC1DQSgxKSxDTj13cHN0LWFkLENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2\r\naWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXdwc3RBRCxEQz1j\r\nb20/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNS\r\nTERpc3RyaWJ1dGlvblBvaW50MIHCBggrBgEFBQcBAQSBtTCBsjCBrwYIKwYBBQUH\r\nMAKGgaJsZGFwOi8vL0NOPXdwc3RBRC1XUFNULUFELUNBLENOPUFJQSxDTj1QdWJs\r\naWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9u\r\nLERDPXdwc3RBRCxEQz1jb20/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNz\r\nPWNlcnRpZmljYXRpb25BdXRob3JpdHkwDQYJKoZIhvcNAQEFBQADggEBAJM7bW3I\r\nwXbFBSzIIFqskvw/DXJXkV8QV0MWuhdIItSCm0i1uOdbnEIDv6tyys9tnVNZ3pdb\r\nhXcbsU3s4i2aYDqcHErBZfpj6Sl94Ib8Eg5Acpzrm8UFb1N+RZ2Ns3tAsjcJ7ViQ\r\n8qlsXWMmaWHSR7qRSjNKJuI2jLOaHVLfhIMdSNB9iEmvsQZHuZkKN+tfzhZIKL/T\r\nTQBOVpubr3Gbh9N9Gx8m4vyiA65LI3n5DH0SJd0M6N+EVlvZRYOjtKqz2kg/J6rJ\r\nB7qNgmBx+G/StFdmN5pZ8c6ieLfBBEdUS/sGFbWg1UCKoctzxZyLYIaWXUx3OSGX\r\nw7YcBXvMG2dPDWs=\r\n-----END CERTIFICATE-----"
Repo_server_self_signed_certificate = "-----BEGIN CERTIFICATE-----\nMIIC8TCCAdmgAwIBAgIQZAfEbCt9fJVDazFvKE92JjANBgkqhkiG9w0BAQUFADAg\r\nMR4wHAYDVQQDExVXTVN2Yy1CSEFSQVRISS1SRy1WTTIwHhcNMTgwNTI2MDY1MTAy\r\nWhcNMjgwNTIzMDY1MTAyWjAgMR4wHAYDVQQDExVXTVN2Yy1CSEFSQVRISS1SRy1W\r\nTTIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCsnDUSl0Uopfy4JWSa\r\nKFryCQlDPsjtd5Cvs26ZkMaJqBMpvGxtjjLgx4BeeJuod/SLQjMruNXZ9yDucYgt\r\nYRnOcAjS0m3+gr8Xt2E0WSEchu5wPc5E8lJTfA0ym8gZkfqwh1KkIL2c3EFzng7X\r\nEMvOxczBhBq5HcT9vmSM1Mk0I84w9TRmTzOKo4TQlfqHvPiHUECL06/JacANQMSl\r\n3UhynaI5kn+MHEqaS2yv0ZDgj+/680Xaxc5FV6ElWsJjYzL/FjgchE7L9nd40SlM\r\nqefb8Er8YhWEl0xp5deHAY8Fbc4aKBJ4LU2gKJtE+/RE60RK++6ilJrGWuBv8qN7\r\n4FUzAgMBAAGjJzAlMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA4GA1UdDwQHAwUAsAAA\r\nADANBgkqhkiG9w0BAQUFAAOCAQEAbeaUepa/e6w4WoHOipIJCZcMvcEFvtAfYnj7\r\nQ+bCb/H4CCZC6H05ErfOC+gXgo1FeV32eGoL0VaGxw1wgekFw4GDk4CivtADqoVL\r\nKK0C9snJy+1AiOIt+cllsZX92aI1lC4vWQMhVOa+FwpMkEPXy79zwUB1vMjokVzN\r\nuucHzcubAufQGqp7ofMXdk0VU3tY4J29NSxZdcE2D4FcSBXvZil+8LoWzf86cIMk\r\nVPjDx9j9xr7Q992KZEOjPjG2UCTJdx0hJ/yvURgA2osWw9vjsjiNuE/G+OG9MHIp\r\nOjlTT4p0rQXrplPGkVSBbvfbsIPLi9bo1eHgIzTIfFAVLtP/mQ==\r\n-----END CERTIFICATE-----"
Repo_server_rootCA_certificate = '-----BEGIN CERTIFICATE-----\nMIIEczCCA1ugAwIBAgIJAKBroQLn+5DzMA0GCSqGSIb3DQEBCwUAMGsxCzAJBgNV\nBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRIwEAYDVQQHEwlQYWxvIEFsdG8x\nGDAWBgNVBAoTD0hld2xldHQtUGFja2FyZDEZMBcGA1UEAxMQSFAgVGVzdEhlYWQg\nUm9vdDAgFw0xODA2MTUxNTAxMDdaGA8yMTE4MDUyMjE1MDEwN1owazELMAkGA1UE\nBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExEjAQBgNVBAcTCVBhbG8gQWx0bzEY\nMBYGA1UEChMPSGV3bGV0dC1QYWNrYXJkMRkwFwYDVQQDExBIUCBUZXN0SGVhZCBS\nb290MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuXQxIHAWP3jeilH5\nkxYwb1hUazXlfRFZtswhMTFAB5uhyyiSXHlFM7/v/sYLfrc7xTGz0jxh4ZJoWrOp\nd3gsXI70Q0YFMb7rSC94qyDlvcNW8C2CnGsuIb/cfDEOWa/4DfL3Ch37W3TNA+ek\nrPXcrSrrKjgl6sCTrnwd/AUmBycoseX1rUpnC9jFshkFhJ/PWCpajh3Q05ZjY3FA\nM1eb/KiB5jZnI/7HUywCXbKVuMgyn3QwAWAfHtCDhZH03nAWH0vfWbPEia3+NJpO\n09X9dPDQtulwbhqyQ26PRLfl7LJIwhdxOWvgrJ5ASWm/nH7C+NIDkxlRMR8XNPCt\n5m7xdQIDAQABo4IBFjCCARIwHQYDVR0OBBYEFBxp6HhJ3TD4al/+ES4LPIy64fO/\nMIGdBgNVHSMEgZUwgZKAFBxp6HhJ3TD4al/+ES4LPIy64fO/oW+kbTBrMQswCQYD\nVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTESMBAGA1UEBxMJUGFsbyBBbHRv\nMRgwFgYDVQQKEw9IZXdsZXR0LVBhY2thcmQxGTAXBgNVBAMTEEhQIFRlc3RIZWFk\nIFJvb3SCCQCga6EC5/uQ8zALBgNVHQ8EBAMCAbYwDAYDVR0TBAUwAwEB/zA2Bggr\nBgEFBQcBAQQqMCgwJgYIKwYBBQUHMAGGGmh0dHA6Ly9sb2NhbGhvc3Q6MjU2MC9v\nY3NwMA0GCSqGSIb3DQEBCwUAA4IBAQB1SjyeKcU0v3q7BkXefaRdycIRzWkshz2Z\nk+VZS668D3dc1w84kmK7ng+XuzBpvkgefHdA0WnkXjuCs0bSSsnkDZopP5nkWzqV\n5e/Mms/E7dXW3KRP3/mBlcpWc4EXHb9TUKVPh9/HPas6LpHbe3B3L3/J6LbTVLOW\nod8ZxrVv8xFU83b4EZOaFl/rcwFPLdDI+8oJK87Ievuzo2dLrwG/2K2c1BMJpeCF\neWOuDidlVZzXuy3/JjzltOFIKEVdl+ah4YSmufYvQGFwxwxfrkTeeLZMbF8gPmwQ\nGP/hv9eH8kiqttO4zhsu3U+W2vFHFXissrLn6WWvA+HSvz0thSlt\n-----END CERTIFICATE-----\n'
Repo_server_subCA_certificate = '-----BEGIN CERTIFICATE-----\nMIIEvzCCA6egAwIBAgIBCDANBgkqhkiG9w0BAQsFADBUMRowGAYDVQQKExFPbmVWaWV3IENlcnQg\nVGVzdDEUMBIGA1UECxMLcGtpLXN1YmNhLTkxIDAeBgNVBAMTF0NlcnRpZmljYXRlIEF1dGhvcml0\neSA5MB4XDTE2MTExMDIyMzY1NVoXDTE4MTAyOTE2MzA0MlowdTELMAkGA1UEBhMCQ04xETAPBgNV\nBAgTCFNoYW5naGFpMREwDwYDVQQHEwhTaGFuZ2hhaTESMBAGA1UEChMJSFBFIFBvaW50MRQwEgYD\nVQQLEwtyZXBvIHNlcnZlcjEWMBQGA1UEAxMNMTUuMTE0LjExNC40NzCCASIwDQYJKoZIhvcNAQEB\nBQADggEPADCCAQoCggEBAMhJrWHurZYnFwkGImLP0U3BmYOJ6sKj3uF4IeWmxtteSiJShqY86j64\nco6q2l7oqiPWKR1lgx8MpetcRaSb77wLz+KPQ3MJnqhguhGhq4bTHRMZI5Rp2KaPmmPVyMvuuRcd\nq7tN47gK3y5FuoQE/5Ply6wRuj/wf1+98JL3mSU4RLWIWVzmnerB9gbQm42R9LZr8TcWoUqAXCz3\nJzIRwsgiNsvwiFwiNG0A4PZQ5MsZA5ithsW2FLO01rKk/h2/AdqnNOspp3M33lcyghlUG4nXIeN/\nNl0ts60gS2I5iLI5UjWtYfmVFlXx1+jcq5rRiKURgb6654mcd88lXVhhPR0CAwEAAaOCAXkwggF1\nMB8GA1UdIwQYMBaAFFH4vk+mZWlLIzJWnCNcLzGaWWumMFIGCCsGAQUFBwEBBEYwRDBCBggrBgEF\nBQcwAYY2aHR0cDovL292LWNhLXRlc3QudnNlLnJkbGFicy5ocGVjb3JwLm5ldDoxMDM4MC9jYS9v\nY3NwMA4GA1UdDwEB/wQEAwIE8DAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwgc4GA1Ud\nHwSBxjCBwzCBwKBnoGWGY2h0dHBzOi8vb3YtY2EtdGVzdC52c2UucmRsYWJzLmhwZWNvcnAubmV0\nOjEwMzQ0L2NhL2VlL2NhL2dldENSTD9vcD1nZXRDUkwmY3JsSXNzdWluZ1BvaW50PU1hc3RlckNS\nTKJVpFMwUTEaMBgGA1UEChMRT25lVmlldyBDZXJ0IFRlc3QxETAPBgNVBAsTCHBraS1jYS05MSAw\nHgYDVQQDExdDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgOTANBgkqhkiG9w0BAQsFAAOCAQEAUikirjcD\nMzbDHnfd1dk5Epsy1z5y9XkLojRmSvGX0WRF7Opbxwx2GqcfeKscHioySIyLCT7pp48wMmoiR2XZ\neOi6pGqR8wPOJpi8htoLh/yKaqfkeVPzXLEI1KRkBPZ5oKKZJOz0mFYXTbX6WJSM8FaL3rQyRSMA\nXiApV2+dWJP+KR9noqSdH8mdjR9C2ELYmDfLZtzdKWPrdy+sbtb1GE6gg+qkl+icz/P5kddqfYTA\nRoIqP5CxG5NPnaFh9M5KrmFTOyvCvyB6DK22fH2XBVbFmNvDXV9JRli3wOLqwqCKoCUmE1fMfrin\nS3b3eMfVcsoO70Bf/9HKsQkAbQmSMg==\n-----END CERTIFICATE-----\n'
Expired_self_signed_certificate = '-----BEGIN CERTIFICATE-----\nMIIEuDCCAyCgAwIBAgIJAOcbsYbuH2jzMA0GCSqGSIb3DQEBCwUAMHQxCzAJBgNVBAYTAkNOMREw\nDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwIU2hhbmdoYWkxEjAQBgNVBAoMCUhQRSBQb2ludDES\nMBAGA1UECwwJVGVzdC1TSFFBMRcwFQYDVQQDDA4xNS4xMTQuMTE0LjExOTAeFw0xNzAyMjMwNTA4\nMzlaFw0xNzAyMjQwNTA4MzlaMHQxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8G\nA1UEBwwIU2hhbmdoYWkxEjAQBgNVBAoMCUhQRSBQb2ludDESMBAGA1UECwwJVGVzdC1TSFFBMRcw\nFQYDVQQDDA4xNS4xMTQuMTE0LjExOTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAOuW\nL06ek9uiBAYUf99WpkBGDCI9SAlJnjb3jQrUESLvN0kAnOK0D09bxalxOFRlBeHPMqAbzslIhf58\nM/hAIiLuCeppS4hFAKIiZddbSxjH03uWof8M2s3FOP99qQEBW4aFQksLLJAqe3sjuTlrYSel2avQ\nOiMpPpFhqiAl2cYz7B4itFS20aiWb3KLlAirsHPI9v7Gd3ybeZYNdtDiCLBIOpEu3oRCIoyEpsCM\nUJihxYMIrdJ2KR/2/qZwx5+NYHHhXmZj2OtM1SMSehLDeJAZjgrGn6YCnvjtz5Z3PzQ986sh5poy\nGzLXWOrb0kmpfLDnTLo3QmmYq83t3lCzzYhR+znDLi0O4TaRHl5ZUDdU5FPmdwWaGcprr214bemX\nr1d/qD+LoSKIbgNHHV+MfrjBrvyAV71d/vn3mIgyvqz8Bp6w31thkCQNy1kfnMxxHgQH4q0d7FLW\nYfhWpBMas+gYRZ5vyfkZqFyROKFD2vniPmP4fqydDhsitL+HQ58vkQIDAQABo00wSzAdBgNVHQ4E\nFgQUKCFExmG+9zFeBrigI/iNM9ibhkwwHwYDVR0jBBgwFoAUKCFExmG+9zFeBrigI/iNM9ibhkww\nCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAYEANjhJH8KleOH52oyXEAHuEglVaScQ72CzUBw5\nWFdYN70UYavXu0H9JYc4Q+e3K4WnpA9Z0k7bfVlEj0fgYL7a4xm7KantojYtLjQYI6+g9H0ibuSc\n2XwOHl96OrKsOAOu9SvRDIix3r1OMs/Da+F7HZKiQ3fc1RWyPfl7774dNxYR530kMhGfySpMkGoC\n/blqdmfba/DDojpaCaVSGqLyPcOdkKpaeEpupdYTPS6jmZcPFqc9YyuBo3B/PJIXdvVKbbdvEpUd\nwbms+mydh7hEO8O0YbGRho/NrUnEjmS3x8VBFhRfSM1dWxHG1Bt8usRVII66v8MZqn70PiwTdHNA\nYmvDlbNZZMNXszdE6RHlJQqeZ7RtMg5pijU+Yxf/6LiWqvTozHMYo3cDvJzTKJTXIZ0bHVk5d1m3\nE7PYAe/Ov/4EG6YUrbNOxrR8i7mMdzYwBHNYHwCnHIop6+Je27h9+/7DGn3RMqbkxejyqMYr7WYH\nAKSG01n61Fwi1q6tBPRw\n-----END CERTIFICATE-----\n'
Key_length_less_than_1024_certificate = '-----BEGIN CERTIFICATE-----\nMIICLjCCAdigAwIBAgIJAKf3WJ2i85NHMA0GCSqGSIb3DQEBCwUAMHQxCzAJBgNVBAYTAkNOMREw\nDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwIU2hhbmdoYWkxEjAQBgNVBAoMCUhQRSBQb2ludDES\nMBAGA1UECwwJVGVzdC1TSFFBMRcwFQYDVQQDDA4xNS4xMTQuMTE0LjEwOTAeFw0xNzA0MTMwNjQy\nNDNaFw0yMTA1MjIwNjQyNDNaMHQxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8G\nA1UEBwwIU2hhbmdoYWkxEjAQBgNVBAoMCUhQRSBQb2ludDESMBAGA1UECwwJVGVzdC1TSFFBMRcw\nFQYDVQQDDA4xNS4xMTQuMTE0LjEwOTBcMA0GCSqGSIb3DQEBAQUAA0sAMEgCQQDBT7x2AjfbREcx\n4/jaiLTTBR67JsEf9r8F9kEEX5VliAcFcJgGJo779fg9lK4tEBthCxJa5Imw7ivOx26Nw4MbAgMB\nAAGjTTBLMB0GA1UdDgQWBBROMaK3WO7cFsWAVx9HvkBMOQYPRzAfBgNVHSMEGDAWgBROMaK3WO7c\nFsWAVx9HvkBMOQYPRzAJBgNVHRMEAjAAMA0GCSqGSIb3DQEBCwUAA0EAEZTJ+vfM6RuVb49k1lV4\nneIMuwNe+0JlQNDd7nit+9Q7p15NXnzEshEE3FuuRwVS0Y7hRjCb5+4cuGxLZEhHBA==\n-----END CERTIFICATE-----\n'
Key_length_greater_than_4096_certificate = '-----BEGIN CERTIFICATE-----\nMIIGtjCCBB6gAwIBAgIJALA0JVFnBdqVMA0GCSqGSIb3DQEBCwUAMHMxCzAJBgNVBAYTAkNOMREw\nDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwIU2hhbmdoYWkxEjAQBgNVBAoMCUhQRSBQb2ludDES\nMBAGA1UECwwJVGVzdC1TSFFBMRYwFAYDVQQDDA0xNS4xMTQuMTEzLjkwMB4XDTE3MDQxMzA2NDM1\nN1oXDTIxMDUyMjA2NDM1N1owczELMAkGA1UEBhMCQ04xETAPBgNVBAgMCFNoYW5naGFpMREwDwYD\nVQQHDAhTaGFuZ2hhaTESMBAGA1UECgwJSFBFIFBvaW50MRIwEAYDVQQLDAlUZXN0LVNIUUExFjAU\nBgNVBAMMDTE1LjExNC4xMTMuOTAwggKiMA0GCSqGSIb3DQEBAQUAA4ICjwAwggKKAoICgQDaJwiT\nWJPXg4+ggf7lG6v/NOL2r5sxm+30egxcyNQ1Es3iLCxc1jIRp50C3mNaAc4h6jgEZm4ONQgoXPqC\ndhNdqlt/kGqVEEyznUD1iGPZ3I8eAURMYTX9vpMWJxrWx/qVvPxtxGqeIuxzMGp0n5wc02TlOHTX\nfS0rjf8jHW3+7YBkkF10c39e9Owk4bYKsPy/pTUXDPwXOdy2fnEK3FkMK7+sTr1czrr/Ax0jqgfj\nEsTPJM0gsq8Zo3MqeE++J/zqs8kde1Nxs7IjwVaQB0qOT6p5rXO3n8ocr89ec/s1Zen6zRBxU5eS\neWg4RXUx0gHv7JupWlKBfSv8hiISYXsYAAJqRfUWACJV+5+5i2J+JXPi811QqwGsY/4bbBxCTtVD\ncmi9BfQJ+cQDQHkdclzBAfHEoyZnHIlLCLJIjowMsxkXAJB02BpGo9zFQ28WVgT0v4pfOgkNvhyQ\n6HXFxFwTYmOjzZv8U3f2EzyzjqbDMdEf5PEtPwCw9pmK1laNIGD1TdYEVJZBOOps0pVlBXclPY5O\nQHOMmvTVcaxnpwQnhqJft3gZleTUhMsKkunOZCA9qB7+6olrr8UJwZT5TVuq8TVTPXsFDdRZCxEu\nLWiMoV0TvEclDmMaolJx9y65k4t3RdaB1a1lnaVnKjCVwoqHr6T+WoDPlM+I37/g/XqMxxR3RKCw\n5kAirNzi2XK6X0H3n1eOqtVbKdnB2wGO3QytL+Y3F1lE2CIik6C2l4Ela7AB8YFy2Nzt6/7qyPjb\n0TN5G3eFjrVQyNtgYY1V1Z0hGMLLkus6wQdX7gAlF4ua4qtGBIW980Ob5ENvNNgUFovWKvWwRoI0\nQgRFNhQFU3PBAgMBAAGjTTBLMB0GA1UdDgQWBBTD+dvGAAChZpHLoWa22Q0oYsIw5TAfBgNVHSME\nGDAWgBTD+dvGAAChZpHLoWa22Q0oYsIw5TAJBgNVHRMEAjAAMA0GCSqGSIb3DQEBCwUAA4ICgQCg\n0UXYg8dxGoU6WZCkd755GWMR0q+zihFjl/vut7FL7VYmWOQyOE7U1t7hvr/jU3jtn+Q6pqEpB0K9\nj7m5BU1QAYsXNiHb6XA8zXB0h9KttnIpIDAmbWV9hXit74/ebeF9SrjYuDpi5wsj2Zc2K1LE4W7N\nAePcVvUN9u4+wWzDHMt1uG9RYTJ6v55IS7/ABpLKz03FMQbE03VDEO4W+IWFBsC7ZBM8jaGz365B\nIpiVpVRRjbWg5bVRb0eZLk9wb0KT6TCWxU+nIIpDdzeX/lUgEwZ3c8GVgvupzorRyMdlEXN83jP6\nEwzAxNTpX9Og15kJ6L6dh1LENlscdZHQi/shURm580GhtXbwP6/XW7gon2IwlbcMibO83vZ+6Arj\nqq+1abcI1vZBXoiYpie/y4KdfuIIAVF645g3090u5Eyz/+i+M22Ni8owO9Jkx1Y0O5b0QjTJsKYT\nx0ee9HbHToL7XFkgyMMHjMfWoSMV2ysh+iutwRMGAqJx8DiprhY8CQp46qugzzdql8++Xt8fHMsD\nW0m0sl8fUqYWu8NbqPUgEHTDeAJyAYgQx/DZjq9/6pOK1lAdVabDryxSsV9LZyn20pMtjnnfgZkq\nvcIGg7h7Fg4S4tgxf71w/g15iXmB4Lwxg0YItd25igbC2gN4kwzaIKKWIC5LHcJdNZJATht1onFy\n/nO8vAWzjaYDC2H5rsDnVQa0BKIHrlaHJVmVAz1VwyldQjjyu9JxcvkLA0Fm4H29LmjX68mXnWjo\nd9Adg5KM0xuJOe3+bOt7lwZmx4M6MfhTTIpQ023KiRSG4CTQ0LL/JylZhhe8zfM2lZ9S2UwS8Xwr\nTeH8EP+bP3rVu5oB\n-----END CERTIFICATE-----\n'


# Trust remote server in OneView
OpenLDAP_self_signed_certs_trust_body = [
    {"certificateDetails":
        [
            {"base64Data": OpenLDAP_self_signed_certificate,
             "aliasName": "OpenLDAP_self_signed",
             "type": "CertificateDetailV2"}
        ],
        "type": "CertificateInfoV2"}
]

Repo_server_self_signed_certs_trust_body = [
    {"certificateDetails":
        [
            {"base64Data": Repo_server_self_signed_certificate,
             "aliasName": "Repo_server_self_signed",
             "type": "CertificateDetailV2"}
        ],
        "type": "CertificateInfoV2"}
]

Expired_self_signed_certs_trust_body = [
    {"certificateDetails":
        [
            {"base64Data": Expired_self_signed_certificate,
             "aliasName": "expired_self_signed",
             "type": "CertificateDetailV2"}
        ],
        "type": "CertificateInfoV2"}
]

Key_length_less_than_1024_trust_body = [
    {"certificateDetails":
        [
            {"base64Data": Key_length_less_than_1024_certificate,
             "aliasName": "less_than_1024",
             "type": "CertificateDetailV2"}
        ],
        "type": "CertificateInfoV2"
     }
]

LDAP_RootCA_signed_certs_trust_body = [
    {"members": [
        {
            "certificateDetails":
                {"aliasName": "LDAP_RootCA",
                 "base64Data": LDAP_RootCA_certificate,
                 "type": "CertificateDetailV2"},
            "type": "CertificateAuthorityInfo"}
    ],
        "type": "CertificateAuthorityInfoCollection"},
    {"members": [
        {
            "certificateDetails":
                {"aliasName": "LDAP_RootCA_1024",
                 "base64Data": OpenLDAP_rootCA_1024_certificate,
                 "type": "CertificateDetailV2"},
            "type": "CertificateAuthorityInfo"}
    ],
        "type": "CertificateAuthorityInfoCollection"},
    {"members": [
        {
            "certificateDetails":
                {"aliasName": "LDAP_RootCA_4096",
                 "base64Data": OpenLDAP_rootCA_4096_certificate,
                 "type": "CertificateDetailV2"},
            "type": "CertificateAuthorityInfo"}
    ],
        "type": "CertificateAuthorityInfoCollection"}]

AD_RootCA_signed_certs_trust_body = [
    {"members": [
        {
            "certificateDetails":
                {"aliasName": "AD_RootCA",
                 "base64Data": AD_rootCA_signed_certificate,
                 "type": "CertificateDetailV2"},
            "type": "CertificateAuthorityInfo"}
    ],
        "type": "CertificateAuthorityInfoCollection"}]

LDAP_SubCA_signed_certs_trust_body = [
    {"members":
        [
            {
                "certificateDetails":
                    {
                        "aliasName": "RootCA",
                        "base64Data": LDAP_RootCA_certificate,
                        "type": "CertificateDetailV2"},
                "type": "CertificateAuthorityInfo"}
        ],
        "type": "CertificateAuthorityInfoCollection"},
    {"members":
        [
            {
                "certificateDetails":
                    {"aliasName": "SubCA1",
                     "base64Data": SubCA1_certificate,
                     "type": "CertificateDetailV2"},
                "type": "CertificateAuthorityInfo"}
        ],
        "type": "CertificateAuthorityInfoCollection"},
    {"members":
        [
            {
                "certificateDetails":
                    {"aliasName": "SubCA2",
                     "base64Data": SubCA2_certificate,
                     "type": "CertificateDetailV2"},
                "type": "CertificateAuthorityInfo"}
        ],
     "type": "CertificateAuthorityInfoCollection"},
    {"members":
        [
            {
                "certificateDetails":
                    {"aliasName": "SubCA3",
                     "base64Data": SubCA3_certificate,
                     "type": "CertificateDetailV2"},
                "type": "CertificateAuthorityInfo"}
        ],
     "type": "CertificateAuthorityInfoCollection"},
    {"members":
        [
            {
                "certificateDetails":
                    {"aliasName": "SubCA4",
                     "base64Data": SubCA4_certificate,
                     "type": "CertificateDetailV2"},
                "type": "CertificateAuthorityInfo"}
        ],
        "type": "CertificateAuthorityInfoCollection"},
    {"members":
        [
            {
                "certificateDetails":
                    {"aliasName": "SubCA5",
                     "base64Data": SubCA5_certificate,
                     "type": "CertificateDetailV2"},
                "type": "CertificateAuthorityInfo"}
        ],
        "type": "CertificateAuthorityInfoCollection"},
    {"members":
        [
            {
                "certificateDetails":
                    {"aliasName": "SubCA6",
                     "base64Data": SubCA6_certificate,
                     "type": "CertificateDetailV2"},
                "type": "CertificateAuthorityInfo"}
        ],
        "type": "CertificateAuthorityInfoCollection"},
    {"members":
        [
            {
                "certificateDetails":
                    {"aliasName": "SubCA7",
                     "base64Data": SubCA7_certificate,
                     "type": "CertificateDetailV2"},
                "type": "CertificateAuthorityInfo"}
        ],
        "type": "CertificateAuthorityInfoCollection"},
    {"members":
        [
            {
                "certificateDetails":
                    {"aliasName": "SubCA8",
                     "base64Data": SubCA8_certificate,
                     "type": "CertificateDetailV2"},
                "type": "CertificateAuthorityInfo"}
        ],
        "type": "CertificateAuthorityInfoCollection"}
]


# Add OpenLDAP server into OneView
OpenLDAP_self_signed_certs = [
    {
        "type": "LoginDomainConfigV600",
        "authnType": "CREDENTIAL",
        "directoryBindingType": "USER_ACCOUNT",
        "name": OpenLDAP_self_signed_server_name,
        "credential": {"userName": "ldapuser1", "password": "Cosmos123"},
        "authProtocol": "LDAP",
        "orgUnits": ["ou=people"],
        "userNamingAttribute": "UID",
        "baseDN": "dc=hpe,dc=com",
        "directoryServers": [
            {"type": "LoginDomainDirectoryServerInfoDto",
             "directoryServerSSLPortNumber": "636",
             "directoryServerIpAddress": OpenLDAP_self_signed_server_name,
             "directoryServerCertificateStatus": "",
             "serverStatus": "",
             "directoryServerCertificateBase64Data": OpenLDAP_self_signed_certificate
             }
        ]
    }
]

Expired_self_signed_certs = [
    {
        "type": "LoginDomainConfigV600",
        "authnType": "CREDENTIAL",
        "directoryBindingType": "USER_ACCOUNT",
        "name": Expired_self_signed_server_name,
        "credential": {"userName": "ldapuser1", "password": "Cosmos123"},
        "authProtocol": "LDAP",
        "orgUnits": ["ou=people"],
        "userNamingAttribute": "UID",
        "baseDN": "dc=hpe,dc=com",
        "directoryServers": [
            {"type": "LoginDomainDirectoryServerInfoDto",
             "directoryServerSSLPortNumber": "636",
             "directoryServerIpAddress": Expired_self_signed_server_name,
             "directoryServerCertificateStatus": "",
             "serverStatus": "",
             "directoryServerCertificateBase64Data": Expired_self_signed_certificate
             }
        ]
    }
]

OpenLDAP_rootCA_signed_1024_4096_certs = [
    {
        "type": "LoginDomainConfigV600",
        "authnType": "CREDENTIAL",
        "directoryBindingType": "USER_ACCOUNT",
        "name": OpenLDAP_rootCA_server_name,
        "credential": {"userName": "ldapuser1", "password": "Cosmos123"},
        "authProtocol": "LDAP",
        "orgUnits": ["ou=people"],
        "userNamingAttribute": "UID",
        "baseDN": "dc=hpe,dc=com",
        "directoryServers": [
            {"type": "LoginDomainDirectoryServerInfoDto",
             "directoryServerSSLPortNumber": "636",
             "directoryServerIpAddress": OpenLDAP_rootCA_server_name,
             "directoryServerCertificateStatus": "",
             "serverStatus": "",
             "directoryServerCertificateBase64Data": OpenLDAP_rootCA_certificate
             }
        ]
    },
    {
        "type": "LoginDomainConfigV600",
        "authnType": "CREDENTIAL",
        "directoryBindingType": "USER_ACCOUNT",
        "name": '%s_1024_KeyLength_Cert' % OpenLDAP_rootCA_server_name,
        "credential": {"userName": "ldapuser1", "password": "Cosmos123"},
        "authProtocol": "LDAP",
        "orgUnits": ["ou=people"],
        "userNamingAttribute": "UID",
        "baseDN": "dc=hpe,dc=com",
        "directoryServers": [
            {"type": "LoginDomainDirectoryServerInfoDto",
             "directoryServerSSLPortNumber": "636",
             "directoryServerIpAddress": OpenLDAP_rootCA_server_name,
             "directoryServerCertificateStatus": "",
             "serverStatus": "",
             "directoryServerCertificateBase64Data": OpenLDAP_rootCA_1024_certificate
             }
        ]
    },
    {
        "type": "LoginDomainConfigV600",
        "authnType": "CREDENTIAL",
        "directoryBindingType": "USER_ACCOUNT",
        "name": '%s_4096_KeyLength_Cert' % OpenLDAP_rootCA_server_name,
        "credential": {"userName": "ldapuser1", "password": "Cosmos123"},
        "authProtocol": "LDAP",
        "orgUnits": ["ou=people"],
        "userNamingAttribute": "UID",
        "baseDN": "dc=hpe,dc=com",
        "directoryServers": [
            {"type": "LoginDomainDirectoryServerInfoDto",
             "directoryServerSSLPortNumber": "636",
             "directoryServerIpAddress": OpenLDAP_rootCA_server_name,
             "directoryServerCertificateStatus": "",
             "serverStatus": "",
             "directoryServerCertificateBase64Data": OpenLDAP_rootCA_4096_certificate
             }
        ]
    }
]

Key_length_less_than_1024_certs = [
    {
        "type": "LoginDomainConfigV600",
        "authnType": "CREDENTIAL",
        "directoryBindingType": "USER_ACCOUNT",
        "name": Key_length_less_than_1024_server_name,
        "credential": {"userName": "ldapuser1", "password": "Cosmos123"},
        "authProtocol": "LDAP",
        "orgUnits": ["ou=people"],
        "userNamingAttribute": "UID",
        "baseDN": "dc=hpe,dc=com",
        "directoryServers": [
            {"type": "LoginDomainDirectoryServerInfoDto",
             "directoryServerSSLPortNumber": "636",
             "directoryServerIpAddress": Key_length_less_than_1024_server_name,
             "directoryServerCertificateStatus": "",
             "serverStatus": "",
             "directoryServerCertificateBase64Data": Key_length_less_than_1024_certificate
             }
        ]
    }
]

OpenLDAP_SubCA_Signed_certs = [
    {
        "type": "LoginDomainConfigV600",
        "authnType": "CREDENTIAL",
        "directoryBindingType": "USER_ACCOUNT",
        "name": OpenLDAP_rootCA_server_name,
        "credential": {"userName": "ldapuser1", "password": "Cosmos123"},
        "authProtocol": "LDAP",
        "orgUnits": ["ou=people"],
        "userNamingAttribute": "UID",
        "baseDN": "dc=hpe,dc=com",
        "directoryServers": [
            {"type": "LoginDomainDirectoryServerInfoDto",
             "directoryServerSSLPortNumber": "636",
             "directoryServerIpAddress": OpenLDAP_rootCA_server_name,
             "directoryServerCertificateStatus": "",
             "serverStatus": "",
             "directoryServerCertificateBase64Data": LDAP_RootCA_certificate
             }
        ]
    }
]

AD_rootCA_signed_certs = [
    {
        "name": AD_rootCA_server_name,
        "credential":
            {"userName": "Administrator", "password": "Wpsthpvse1234"},
        "authProtocol": "AD",
        "orgUnits": [],
        "userNamingAttribute": "UID",
        "baseDN": "dc=wpstAD,dc=com",
        "directoryServers":[
            {"type": "LoginDomainDirectoryServerInfoDto",
             "directoryServerSSLPortNumber": "636",
             "directoryServerIpAddress": AD_rootCA_server_name,
             "directoryServerCertificateStatus": "",
             "serverStatus": "",
             "directoryServerCertificateBase64Data": AD_rootCA_signed_certificate}],
        "type": "LoginDomainConfigV600",
        "authnType": "CREDENTIAL",
        "directoryBindingType": "USER_ACCOUNT"
    }
]

AD_subCA_signed_certs = [
    {
        "type": "LoginDomainConfigV600",
        "name": AD_subCA_server_name,
        "credential": {"userName": "pengl", "password": "!QAZ2wsx"},
        "authProtocol": "AD",
        "orgUnits": [],
        "userNamingAttribute": "UID",
        "baseDN": "dc=test,dc=com",
        "directoryServers": [
            {"type": "LoginDomainDirectoryServerInfoDto",
             "directoryServerSSLPortNumber": "636",
             "directoryServerIpAddress": AD_subCA_server_name,
             "directoryServerCertificateStatus": "",
             "serverStatus": "",
             "directoryServerCertificateBase64Data": AD_subCA_signed_certificate}],
        "authnType": "CREDENTIAL",
        "directoryBindingType": "USER_ACCOUNT"
    }
]

Repo_server_self_signed_certs = {
    "repositoryName": Repo_server_self_signed_server_name,
    "repositoryURI": "https://%s/webdav/" % Repo_server_self_signed_server_name,
    "userName": "Administrator",
    "password": "Lsdt4acsl",
    "base64Data": Repo_server_self_signed_certificate
}

Repo_server_rootCA_certs = {
    "repositoryName": Repo_server_rootCA_server_name,
    "repositoryURI": "https://%s/webdav/" % Repo_server_rootCA_server_name,
    "userName": "Administrator",
    "password": "Lsdt4acsl",
    "base64Data": Repo_server_rootCA_certificate
}

Repo_server_subCA_certs = {
    "repositoryName": Repo_server_subCA_server_name,
    "repositoryURI": "https://%s/webdav/" % Repo_server_subCA_server_name,
    "userName": "Administrator",
    "password": "Lsdt4acsl",
    "base64Data": Repo_server_subCA_certificate
}

OpenLDAP_Backup_DBConfig_CMD = 'cat /etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif > /tmp/LDAP_DBConfig_Backup.ldif'
OpenLDAP_Restore_DBConfig_CMD = 'cat /tmp/LDAP_DBConfig_Backup.ldif > /etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif'
OpenLDAP_ModifyDB_SelfSigned_Cert_CMD = 'cat /root/OVF688_OVS6749/LDAP_Cert_SelfSigned/olcDatabase={2}bdb.ldif > /etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif'
OpenLDAP_ModifyDB_Expired_Cert_CMD = 'cat /root/OVF688_OVS6749/LDAP_Cert_SelfSigned_Expired/olcDatabase={2}bdb.ldif > /etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif'
OpenLDAP_ModifyDB_KeyLength_LessThan_1024_Cert_CMD = 'cat /root/OVF688_OVS6749/LDAP_Cert_SelfSigned_KeyLength_LessThan_1024/olcDatabase={2}bdb.ldif > /etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif'
OpenLDAP_ModifyDB_RootCASigned_CMD = 'cat /etc/openldap/certs/OVF688_OVS6749/LDAP_Cert_RootCA_Signed/olcDatabase\=\{2\}bdb.ldif > /etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif'
OpenLDAP_ModifyDB_RootCASigned_KeyLength_1024Cert_CMD = 'cat /etc/openldap/certs/OVF688_OVS6749/LDAP_Cert_RootCA_Signed_KeyLength_1024/olcDatabase\=\{2\}bdb.ldif > /etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif'
OpenLDAP_ModifyDB_RootCASigned_KeyLength_4096Cert_CMD = 'cat /etc/openldap/certs/OVF688_OVS6749/LDAP_Cert_RootCA_Signed_KeyLength_4096/olcDatabase\=\{2\}bdb.ldif > /etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif'
OpenLDAP_RootCASigned_Cert_CMDS = [OpenLDAP_ModifyDB_RootCASigned_CMD, OpenLDAP_ModifyDB_RootCASigned_KeyLength_1024Cert_CMD, OpenLDAP_ModifyDB_RootCASigned_KeyLength_4096Cert_CMD]
LDAP_Service_Restart = '/etc/init.d/slapd restart'
