import sys
import os

import environment_data as env

serverprofiles = {
    "type": "ServerProfileV9",
    "serverHardwareUri": 'SH:' + env.servers[0]['serverHardwareUri'],
    "serverHardwareTypeUri": 'SHT:' + env.servers[0]['serverHardwareTypeUri'],
    "enclosureGroupUri": 'EG:' + env.egs[0]['enclosureGroupUri'],
    "serialNumberType": "Virtual", "iscsiInitiatorNameType": "AutoGenerated",
    "macType": "Virtual", "wwnType": "Virtual",
    "name": "ovf1092_Serverprofile",
    "description": "", "affinity": "Bay",
    "connectionSettings": env.me_connSettings,
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bootMode": {"manageMode": True, "mode": "UEFIOptimized",
                 "secureBoot": "Unmanaged", "pxeBootPolicy": "Auto"},
    "firmware": {"manageFirmware": False, "firmwareBaselineUri": "",
                 "forceInstallFirmware": False, "firmwareInstallType": None,
                 "firmwareScheduleDateTime": "", "firmwareActivationType": "Immediate"},
    "bios": {"manageBios": False, "overriddenSettings": []},
    "hideUnusedFlexNics": True,
    "iscsiInitiatorName": "",
    "osDeploymentSettings": {
        "osDeploymentPlanUri": "dp1With1Nic_StaticAndDhcpNic",
        "osCustomAttributes": [{"name": "DomainName", "value": "lab.local", "constraints": "{\"helpText\":\"\"}", "type": "fqdn"},
                               {"name": "Hostname", "value": "{enclosure}", "constraints": "{\"helpText\":\"\"}", "type": "hostname"},
                               {"name": "ManagementNIC.connectionid", "value": "3"},
                               {"name": "ManagementNIC.dhcp", "value": "False"},
                               {"name": "ManagementNIC.ipv4disable", "value": "False"},
                               {"name": "ManagementNIC.networkuri", "value": 'ETH:' + env.networks['mgmt']},
                               {"name": "ManagementNIC.constraint", "value": "auto"},
                               {"name": "ManagementNIC.vlanid", "value": "0"},
                               {"name": "Password", "value": None},
                               {"name": "SSH", "value": "enabled", "constraints": "{\"options\":[\"enabled\"]}", "type": "option"}],
        "osVolumeUri": None,
        "forceOsDeployment": False},
    "localStorage": {"sasLogicalJBODs": [], "controllers": []},
    "sanStorage": None,
    "initialScopeUris": []}
