import copy


def rlist(start, end, prefix='net_', suffix=''):
    rlist = []
    for x in xrange(start, end + 1):
        rlist.append(prefix + str(x) + suffix)
    return rlist


def deepcopy(self, obj):
    return copy.deepcopy(obj)


admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}

vcenter = {'server': '15.199.230.130', 'user': 'rbriggs', 'password': 'hpvse1'}

ranges = [{'name': 'FCOE-MAC', 'type': 'Range', 'category': 'id-range-VMAC', 'rangeCategory': 'CUSTOM',
           'startAddress': 'AA:AA:AA:00:00:00', 'endAddress': 'AA:AA:AA:00:00:80', 'enabled': True},
          {'name': 'FCOE-WWN', 'type': 'Range', 'category': 'id-range-VWWN', 'rangeCategory': 'CUSTOM',
           'startAddress': '2A:AA:AA:AA:AA:AA:AA:AA', 'endAddress': '2A:AA:AA:AA:AA:AA:AB:29', 'enabled': True},
          {'name': 'FCOE-SN', 'type': 'Range', 'category': 'id-range-VSN', 'rangeCategory': 'CUSTOM',
           'startAddress': 'VCUAAAAAAA', 'endAddress': 'VCUAAAAADT', 'enabled': True}]

ENC1 = 'WPST-PABA58-EN3'
LE = 'WPST-PABA58-EN3'
LIG1 = 'FEX-LIG1'
LIG2 = 'VC-LIG1'
LSG1 = 'LSG1'
LS1 = 'LS1'

BAY1_IP = '192.169.0.76'
BAY1 = ENC1 + ', bay 1'
BAY2_IP = '192.169.0.77'
BAY2 = ENC1 + ', bay 2'
SERVERS = [BAY1, BAY2]
GW_IP = '192.169.0.1'

OA_HOST = '15.245.129.78'
OA_USER = 'Administrator'
OA_PASS = 'hpvse1'
SWITCH1 = '15.245.128.170'
SWITCH1_USER = 'admin'
SWITCH1_PASS = 'Wpst@hpvse1#'

"""
IP 15.199.230.78
User- Administrator
Password- hpvse1

Nexus 5548 (Nexus-1)
IP- 15.199.230.70
NEW IP - 15.245.128.170
DNS- nexus-1.usa.hp.com
User- admin
Password- Wpst@hpvse1#

FEX 1: port 1 -> Nexus port 1
FEX 1: port 2 -> Nexus port 2

FEX2: port 1 -> Nexus port 14
FEX2: port 2 -> Nexus port 13


"""
appliance = {'type': 'ApplianceNetworkConfigurationV2',
             'applianceNetworks':
                 [{'device': 'eth0',
                   'macAddress': None,
                   'interfaceName': 'LIT',
                   'activeNode': '1',
                   'unconfigure': False,
                   'ipv4Type': 'DHCP',
                   'ipv6Type': 'UNCONFIGURE',
                   'hostname': 'f749-f751.rdlabs.hpecorp.net',
                   'confOneNode': True,
                   'domainName': 'usa.hp.com',
                   'aliasDisabled': True,
                   }],
             }

timeandlocale = {'type': 'TimeAndLocale', 'dateTime': None, 'timezone': 'UTC', 'ntpServers': ['ntp.hpecorp.net'],
                 'locale': 'en_US.UTF-8'}

users = [
    {'userName': 'Serveradmin', 'password': 'Serveradmin', 'fullName': 'Serveradmin',
     'permissions': [{'roleName': 'Server administrator'}],
     'emailAddress': 'sarah@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
     'type': 'UserAndPermissions'},
    {'userName': 'Networkadmin', 'password': 'Networkadmin', 'fullName': 'Networkadmin',
     'permissions': [{'roleName': 'Network administrator'}], 'emailAddress': 'nat@hp.com',
     'officePhone': '970-555-0003',
     'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'},
    {'userName': 'Backupadmin', 'password': 'Backupadmin', 'fullName': 'Backupadmin',
     'permissions': [{'roleName': 'Backup administrator'}],
     'emailAddress': 'backup@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
     'type': 'UserAndPermissions'},
    {'userName': 'Noprivledge', 'password': 'Noprivledge', 'fullName': 'Noprivledge',
     'permissions': [{'roleName': 'Read only'}],
     'emailAddress': 'rheid@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
     'type': 'UserAndPermissions'}
]

licenses = [{
    'key': 'YCDE D9MA H9P9 8HUZ U7B5 HWW5 Y9JL KMPL MHND 7AJ9 DXAU 2CSM GHTG L762 LFH6 F4R4 KJVT D5KM EFVW DT5J 83HJ 8VC6 AK2P 3EW2 L9YE HUNJ TZZ7 MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEG 3F9V JQY5 "423207356 HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR H3TCJHCGAYAY"'},
    {
        'key': 'QC3C A9MA H9PQ GHVZ U7B5 HWW5 Y9JL KMPL 2HVF 4FZ9 DXAU 2CSM GHTG L762 7JX5 V5FU KJVT D5KM EFVW DV5J 43LL PSS6 AK2P 3EW2 T9YE XUNJ TZZ7 MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEG 3F9V JQY5 "423207566 HPOV-NFR2 HP_OneView_w/o_iLO_48_Seat_NFR 6H72JHCGY5AU"'}
]

ethernet_networks = [{'name': 'net_1',
                      'type': 'ethernet-networkV4',
                      'vlanId': 1,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'net_101',
                      'type': 'ethernet-networkV4',
                      'vlanId': 101,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'net_102',
                      'type': 'ethernet-networkV4',
                      'vlanId': 102,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'net_4094',
                      'type': 'ethernet-networkV4',
                      'vlanId': 4094,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-a',
                      'type': 'ethernet-networkV4',
                      'vlanId': 200,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-b',
                      'type': 'ethernet-networkV4',
                      'vlanId': 201,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-c',
                      'type': 'ethernet-networkV4',
                      'vlanId': 202,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-d',
                      'type': 'ethernet-networkV4',
                      'vlanId': 203,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-e',
                      'type': 'ethernet-networkV4',
                      'vlanId': 204,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'Untagged',
                      'type': 'ethernet-networkV4',
                      'vlanId': None,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Untagged'},
                     {'name': 'Tunnel',
                      'type': 'ethernet-networkV4',
                      'vlanId': None,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tunnel'}
                     ]

ethernet_ranges = [
    {'prefix': 'net_', 'suffix': 'a', 'start': 100, 'end': 132, 'name': None, 'type': 'ethernet-networkV4',
     'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False, 'connectionTemplateUri': None,
     'ethernetNetworkType': 'Tagged'},
    {'prefix': 'net_', 'suffix': 'b', 'start': 100, 'end': 132, 'name': None, 'type': 'ethernet-networkV4',
     'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False, 'connectionTemplateUri': None,
     'ethernetNetworkType': 'Tagged'},
    {'prefix': 'net_', 'suffix': '', 'start': 1001, 'end': 1032, 'name': None, 'type': 'ethernet-networkV4',
     'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False, 'connectionTemplateUri': None,
     'ethernetNetworkType': 'Tagged'},
    {'prefix': 'net_', 'suffix': 'a', 'start': 1001, 'end': 1032, 'name': None, 'type': 'ethernet-networkV4',
     'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False, 'connectionTemplateUri': None,
     'ethernetNetworkType': 'Tagged'},
    {'prefix': 'net_', 'suffix': 'b', 'start': 1001, 'end': 1032, 'name': None, 'type': 'ethernet-networkV4',
     'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False, 'connectionTemplateUri': None,
     'ethernetNetworkType': 'Tagged'},
    {'prefix': 'net_', 'suffix': '', 'start': 2000, 'end': 3000, 'name': None, 'type': 'ethernet-networkV4',
     'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False, 'connectionTemplateUri': None,
     'ethernetNetworkType': 'Tagged'},
    {'prefix': 'net_', 'suffix': '', 'start': 3968, 'end': 4047, 'name': None, 'type': 'ethernet-networkV4',
     'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False, 'connectionTemplateUri': None,
     'ethernetNetworkType': 'Tagged'}]

network_sets = [
    {'name': 'netset1', 'type': 'network-setV4', 'networkUris': ['network-a'], 'nativeNetworkUri': 'network-a'}]

f1 = [{'name': 'fcoe_1', 'type': 'fcoe-networkV4', 'vlanId': 1},
      {'name': 'fcoe_4094', 'type': 'fcoe-networkV4', 'vlanId': 4094}]
f2 = [{'name': 'fcoe_%ia' % i, 'type': 'fcoe-networkV4', 'vlanId': i} for i in range(1001, 1033)]
f3 = [{'name': 'fcoe_%ib' % i, 'type': 'fcoe-networkV4', 'vlanId': i} for i in range(1001, 1033)]
f4 = [{'name': 'fcoe_%ic' % i, 'type': 'fcoe-networkV4', 'vlanId': i} for i in range(1001, 1033)]
f5 = [{'name': 'fcoe_%i' % i, 'type': 'fcoe-networkV4', 'vlanId': i} for i in range(3968, 4049)]
fcoe_networks = f1 + f2 + f3 + f4 + f5

fc_networks = [{'type': 'fc-networkV4',
                'linkStabilityTime': 30,
                'autoLoginRedistribution': True,
                'name': 'fcnetwork-a',
                'connectionTemplateUri': None,
                'managedSanUri': None,
                'fabricType': 'FabricAttach'}]

enc_group = {'name': 'EG',
             'interconnectBayMappings':
                 [{'interconnectBay': 1, 'logicalInterconnectGroupUri': 'LIG:FEX-LIG1'},
                  {'interconnectBay': 2, 'logicalInterconnectGroupUri': 'LIG:FEX-LIG1'},
                  {'interconnectBay': 3, 'logicalInterconnectGroupUri': 'LIG:VC-LIG1'},
                  {'interconnectBay': 4, 'logicalInterconnectGroupUri': 'LIG:VC-LIG1'},
                  {'interconnectBay': 5, 'logicalInterconnectGroupUri': None},
                  {'interconnectBay': 6, 'logicalInterconnectGroupUri': None},
                  {'interconnectBay': 7, 'logicalInterconnectGroupUri': None},
                  {'interconnectBay': 8, 'logicalInterconnectGroupUri': None}]}

encs = [{'hostname': OA_HOST, 'username': OA_USER, 'password': OA_PASS, 'enclosureGroupUri': 'EG:EG', 'force': False,
         'licensingIntent': 'OneViewNoiLO'}]

uplink_sets = {'VC-US1': {'name': 'VC-US1',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': rlist(100, 132, 'net_', 'a') + rlist(1001, 1008, 'fcoe_', 'a'),
                          'primaryPort': None,
                          'nativeNetworkUri': None,
                          'mode': 'Auto',
                          'logicalPortConfigInfos': [{'bay': '3', 'port': 'X1', 'speed': 'Auto'},
                                                     {'bay': '3', 'port': 'X2', 'speed': 'Auto'},
                                                     {'bay': '3', 'port': 'X3', 'speed': 'Auto'},
                                                     {'bay': '3', 'port': 'X4', 'speed': 'Auto'}]},
               'VC-US2': {'name': 'VC-US2',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': rlist(100, 132, 'net_', 'b') + rlist(1001, 1008, 'fcoe_', 'b'),
                          'primaryPort': None,
                          'nativeNetworkUri': None,
                          'mode': 'Auto',
                          'logicalPortConfigInfos': [{'bay': '4', 'port': 'X1', 'speed': 'Auto'},
                                                     {'bay': '4', 'port': 'X2', 'speed': 'Auto'},
                                                     {'bay': '4', 'port': 'X3', 'speed': 'Auto'},
                                                     {'bay': '4', 'port': 'X4', 'speed': 'Auto'}]},
               'FEX-w-untagged-NS': {'name': 'FEX-w-untagged-NS',
                                     'ethernetNetworkType': 'Tagged',
                                     'networkType': 'Ethernet',
                                     'networkUris': ['network-a'],
                                     'primaryPort': None,
                                     'nativeNetworkUri': None,
                                     'mode': 'Auto',
                                     'logicalPortConfigInfos': [{'bay': '2', 'port': '7', 'speed': 'Auto'},
                                                                {'bay': '2', 'port': '8', 'speed': 'Auto'}]},
               'FEX-edit-ports': {'name': 'FEX-w-untagged-NS',
                                  'ethernetNetworkType': 'Tagged',
                                  'networkType': 'Ethernet',
                                  'networkUris': ['network-a'],
                                  'primaryPort': None,
                                  'nativeNetworkUri': None,
                                  'mode': 'Auto',
                                  'logicalPortConfigInfos': [{'bay': '2', 'port': '5', 'speed': 'Auto'},
                                                             {'bay': '2', 'port': '6', 'speed': 'Auto'},
                                                             {'bay': '2', 'port': '7', 'speed': 'Auto'},
                                                             {'bay': '2', 'port': '8', 'speed': 'Auto'}]},
               'FEX-w-untagged-US': {'name': 'FEX-w-untagged-US',
                                     'ethernetNetworkType': 'Untagged',
                                     'networkType': 'Ethernet',
                                     'networkUris': ['Untagged'],
                                     'primaryPort': None,
                                     'nativeNetworkUri': None,
                                     'mode': 'Auto',
                                     'logicalPortConfigInfos': [{'bay': '2', 'port': '5', 'speed': 'Auto'},
                                                                {'bay': '2', 'port': '6', 'speed': 'Auto'}]},
               'FEX-w-untagged-net': {'name': 'FEX-w-untagged-net',
                                      'ethernetNetworkType': 'Tagged',
                                      'networkType': 'Ethernet',
                                      'networkUris': ['Untagged'],
                                      'primaryPort': None,
                                      'nativeNetworkUri': None,
                                      'mode': 'Auto',
                                      'logicalPortConfigInfos': [{'bay': '2', 'port': '5', 'speed': 'Auto'},
                                                                 {'bay': '2', 'port': '6', 'speed': 'Auto'}]},
               'FEX-w-tunnel-US': {'name': 'FEX-w-tunnel-US',
                                   'ethernetNetworkType': 'Tunnel',
                                   'networkType': 'Ethernet',
                                   'networkUris': ['Tunnel'],
                                   'primaryPort': None,
                                   'nativeNetworkUri': None,
                                   'mode': 'Auto',
                                   'logicalPortConfigInfos': [{'bay': '2', 'port': '4', 'speed': 'Auto'},
                                                              ]},

               'FEX-w-tunnel-net': {'name': 'FEX-w-tunnel-net',
                                    'ethernetNetworkType': 'Tagged',
                                    'networkType': 'Ethernet',
                                    'networkUris': ['Tunnel'],
                                    'primaryPort': None,
                                    'nativeNetworkUri': None,
                                    'mode': 'Auto',
                                    'logicalPortConfigInfos': [{'bay': '2', 'port': '4', 'speed': 'Auto'},
                                                               ]},
               'FEX-US-cannot-span-ICMs': {'name': 'FEX-US-cannot-span-ICMs',
                                           'ethernetNetworkType': 'Tagged',
                                           'networkType': 'Ethernet',
                                           'networkUris': ['Tunnel'],
                                           'primaryPort': None,
                                           'nativeNetworkUri': None,
                                           'mode': 'Auto',
                                           'logicalPortConfigInfos': [{'bay': '1', 'port': '3', 'speed': 'Auto'},
                                                                      {'bay': '2', 'port': '3', 'speed': 'Auto'}
                                                                      ]},
               'FEX-with-FC-US': {'name': 'FEX-with-FC-US',
                                  'ethernetNetworkType': 'NotApplicable',
                                  'networkType': 'FibreChannel',
                                  'networkUris': ['fcnetwork-a'],
                                  'primaryPort': None,
                                  'nativeNetworkUri': None,
                                  'mode': 'Auto',
                                  'logicalPortConfigInfos': [{'bay': '2', 'port': '3', 'speed': 'Auto'},
                                                             ]},

               'FEX-reserved-vlans': {'name': 'FEX-reserved-vlans',
                                      'ethernetNetworkType': 'Tagged',
                                      'networkType': 'Ethernet',
                                      'networkUris': ['net_3968', 'net_4000', 'net_4047', 'net_4094'],
                                      'primaryPort': None,
                                      'nativeNetworkUri': None,
                                      'mode': 'Auto',
                                      'logicalPortConfigInfos': [{'bay': '2', 'port': '3', 'speed': 'Auto'},
                                                                 ]},
               'FEX-max-vlans-per-LI': {'name': 'FEX-max-vlans-per-LI',
                                        'ethernetNetworkType': 'Tagged',
                                        'networkType': 'Ethernet',
                                        'networkUris': rlist(2000, 2999, 'net_', '') + rlist(1001, 1033, 'fcoe_', 'c'),
                                        'primaryPort': None,
                                        'nativeNetworkUri': None,
                                        'mode': 'Auto',
                                        'logicalPortConfigInfos': [{'bay': '1', 'port': '1', 'speed': 'Auto'},
                                                                   ]},

               'FEX-exceeds-max-vlans-per-LI': {'name': 'FEX-exceeds-max-vlans-per-LI',
                                                'ethernetNetworkType': 'Tagged',
                                                'networkType': 'Ethernet',
                                                'networkUris': rlist(2000, 3000, 'net_', ''),
                                                'primaryPort': None,
                                                'nativeNetworkUri': None,
                                                'mode': 'Auto',
                                                'logicalPortConfigInfos': [{'bay': '1', 'port': '1', 'speed': 'Auto'},
                                                                           ]},
               'FEX-exceeds-max-fcoe-per-LI': {'name': 'FEX-exceeds-max-fcoe-per-LI',
                                               'ethernetNetworkType': 'Tagged',
                                               'networkType': 'Ethernet',
                                               'networkUris': rlist(1001, 1033, 'fcoe_', 'c') + ['fcoe_1001b'],
                                               'primaryPort': None,
                                               'nativeNetworkUri': None,
                                               'mode': 'Auto',
                                               'logicalPortConfigInfos': [{'bay': '1', 'port': '1', 'speed': 'Auto'},
                                                                          ]},

               'us3': {'name': 'us3',
                       'ethernetNetworkType': 'Tagged',
                       'networkType': 'Ethernet',
                       'networkUris': rlist(1001, 1032, 'net_', 'c'),
                       'primaryPort': None,
                       'nativeNetworkUri': None,
                       'mode': 'Auto',
                       'logicalPortConfigInfos': [{'bay': '5', 'port': 'X1', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X2', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X3', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X4', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X5', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X6', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X7', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X8', 'speed': 'Auto'}]},
               'BFS-A': {'name': 'FEX-BFS-A',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': ['net_102a', 'fcoe_1002a'],
                         'primaryPort': None,
                         'nativeNetworkUri': None,
                         'mode': 'Auto',
                         'logicalPortConfigInfos': [{'bay': '1', 'port': '1', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': '2', 'speed': 'Auto'}]},
               'BFS-B': {'name': 'FEX-BFS-B',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': ['net_102b', 'fcoe_1002b'],
                         'primaryPort': None,
                         'nativeNetworkUri': None,
                         'mode': 'Auto',
                         'logicalPortConfigInfos': [{'bay': '2', 'port': '1', 'speed': 'Auto'},
                                                    {'bay': '2', 'port': '2', 'speed': 'Auto'}]},
               'BFS-fcoe': {'name': 'BFS-fcoe',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': ['fcoe_1002'],
                            'primaryPort': None,
                            'nativeNetworkUri': None,
                            'mode': 'Auto',
                            'logicalPortConfigInfos': [{'bay': '1', 'port': 'X2', 'speed': 'Auto'}]},
               }

li_uplink_sets = {'us1': {'name': 'us1',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': [],
                          'fcNetworkUris': [],
                          'fcoeNetworkUris': rlist(1001, 1032, 'fcoe_', 'a'),
                          'lacpTimer': 'Short',
                          'logicalInterconnectUri': None,
                          'primaryPortLocation': None,
                          'manualLoginRedistributionState': 'NotSupported',
                          'connectionMode': 'Auto',
                          'nativeNetworkUri': None,
                          'portConfigInfos': [{'bay': '1', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X5', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X6', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X7', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X8', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X9', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X10', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'us2': {'name': 'us2',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': [],
                          'fcNetworkUris': [],
                          'fcoeNetworkUris': rlist(1001, 1032, 'fcoe_', 'b'),
                          'lacpTimer': 'Short',
                          'logicalInterconnectUri': None,
                          'primaryPortLocation': None,
                          'manualLoginRedistributionState': 'NotSupported',
                          'connectionMode': 'Auto',
                          'nativeNetworkUri': None,
                          'portConfigInfos': [{'bay': '3', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '3', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '3', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '3', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'us3': {'name': 'us3',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': [],
                          'fcNetworkUris': [],
                          'fcoeNetworkUris': rlist(1001, 1032, 'fcoe_', 'c'),
                          'lacpTimer': 'Short',
                          'logicalInterconnectUri': None,
                          'primaryPortLocation': None,
                          'manualLoginRedistributionState': 'NotSupported',
                          'connectionMode': 'Auto',
                          'nativeNetworkUri': None,
                          'portConfigInfos': [{'bay': '5', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X5', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X6', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X7', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X8', 'desiredSpeed': 'Auto', 'enclosure': None}
                                              ]},
                  'FEX-US-ETH': {'name': 'FEX-US-ETH',
                                 'ethernetNetworkType': 'Tagged',
                                 'networkType': 'Ethernet',
                                 'networkUris': ['net_1001', 'net_1003', 'net_1005'],
                                 'fcNetworkUris': [],
                                 'fcoeNetworkUris': [],
                                 'lacpTimer': 'Short',
                                 'logicalInterconnectUri': None,
                                 'primaryPortLocation': None,
                                 'manualLoginRedistributionState': 'NotSupported',
                                 'connectionMode': 'Auto',
                                 'nativeNetworkUri': None,
                                 'portConfigInfos': [
                                     {'bay': '2', 'port': '1', 'desiredSpeed': 'Auto', 'enclosure': ENC1},
                                     {'bay': '2', 'port': '2', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-US-FCOE': {'name': 'FEX-US-FCOE',
                                  'ethernetNetworkType': 'Tagged',
                                  'networkType': 'Ethernet',
                                  'networkUris': [],
                                  'fcNetworkUris': [],
                                  'fcoeNetworkUris': ['fcoe_1001c'],
                                  'lacpTimer': 'Short',
                                  'logicalInterconnectUri': None,
                                  'primaryPortLocation': None,
                                  'manualLoginRedistributionState': 'NotSupported',
                                  'connectionMode': 'Auto',
                                  'nativeNetworkUri': None,
                                  'portConfigInfos': [
                                      {'bay': '2', 'port': '3', 'desiredSpeed': 'Auto', 'enclosure': ENC1},
                                      {'bay': '2', 'port': '4', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-US-ETH-AND-FCOE': {'name': 'FEX-US-ETH-AND-FCOE',
                                          'ethernetNetworkType': 'Tagged',
                                          'networkType': 'Ethernet',
                                          'networkUris': ['net_102'],
                                          'fcNetworkUris': [],
                                          'fcoeNetworkUris': ['fcoe_1002c'],
                                          'lacpTimer': 'Short',
                                          'logicalInterconnectUri': None,
                                          'primaryPortLocation': None,
                                          'manualLoginRedistributionState': 'NotSupported',
                                          'connectionMode': 'Auto',
                                          'nativeNetworkUri': None,
                                          'portConfigInfos': [
                                              {'bay': '2', 'port': '5', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-US-w-untagged-NS': {'name': 'FEX-US-w-untagged-NS',
                                           'ethernetNetworkType': 'Tagged',
                                           'networkType': 'Ethernet',
                                           'networkUris': ['network-a'],
                                           'fcNetworkUris': [],
                                           'fcoeNetworkUris': [],
                                           'lacpTimer': 'Short',
                                           'logicalInterconnectUri': None,
                                           'primaryPortLocation': None,
                                           'manualLoginRedistributionState': 'NotSupported',
                                           'connectionMode': 'Auto',
                                           'nativeNetworkUri': None,
                                           'portConfigInfos': [
                                               {'bay': '2', 'port': '6', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-US-ETH-EDITED': {'name': 'FEX-US-ETH',
                                        'ethernetNetworkType': 'Tagged',
                                        'networkType': 'Ethernet',
                                        'networkUris': ['net_1001', 'net_1003', 'net_1005'],
                                        'fcNetworkUris': [],
                                        'fcoeNetworkUris': [],
                                        'lacpTimer': 'Short',
                                        'logicalInterconnectUri': None,
                                        'primaryPortLocation': None,
                                        'manualLoginRedistributionState': 'NotSupported',
                                        'connectionMode': 'Auto',
                                        'nativeNetworkUri': None,
                                        'portConfigInfos': [
                                            {'bay': '2', 'port': '1', 'desiredSpeed': 'Auto', 'enclosure': ENC1},
                                            {'bay': '2', 'port': '2', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-US-ETH-EDITED2': {'name': 'FEX-US-ETH',
                                         'ethernetNetworkType': 'Tagged',
                                         'networkType': 'Ethernet',
                                         'networkUris': ['net_1001'],
                                         'fcNetworkUris': [],
                                         'fcoeNetworkUris': [],
                                         'lacpTimer': 'Short',
                                         'logicalInterconnectUri': None,
                                         'primaryPortLocation': None,
                                         'manualLoginRedistributionState': 'NotSupported',
                                         'connectionMode': 'Auto',
                                         'nativeNetworkUri': None,
                                         'portConfigInfos': [
                                             {'bay': '2', 'port': '1', 'desiredSpeed': 'Auto', 'enclosure': ENC1},
                                             {'bay': '2', 'port': '2', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-US-ETH-EDITED3': {'name': 'FEX-US-ETH',
                                         'ethernetNetworkType': 'Tagged',
                                         'networkType': 'Ethernet',
                                         'networkUris': ['net_101'],
                                         'fcNetworkUris': [],
                                         'fcoeNetworkUris': ['fcoe_1001a'],
                                         'lacpTimer': 'Short',
                                         'logicalInterconnectUri': None,
                                         'primaryPortLocation': None,
                                         'manualLoginRedistributionState': 'NotSupported',
                                         'connectionMode': 'Auto',
                                         'nativeNetworkUri': None,
                                         'portConfigInfos': [
                                             {'bay': '2', 'port': '1', 'desiredSpeed': 'Auto', 'enclosure': ENC1},
                                             {'bay': '2', 'port': '2', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-US-cannot-span-ICMs': {'name': 'FEX-US-cannot-span-ICMs',
                                              'ethernetNetworkType': 'Tagged',
                                              'networkType': 'Ethernet',
                                              'networkUris': ['net_1009'],
                                              'fcNetworkUris': [],
                                              'fcoeNetworkUris': ['fcoe_1009'],
                                              'lacpTimer': 'Short',
                                              'logicalInterconnectUri': None,
                                              'primaryPortLocation': None,
                                              'manualLoginRedistributionState': 'NotSupported',
                                              'connectionMode': 'Auto',
                                              'nativeNetworkUri': None,
                                              'portConfigInfos': [
                                                  {'bay': '1', 'port': '8', 'desiredSpeed': 'Auto', 'enclosure': ENC1},
                                                  {'bay': '2', 'port': '8', 'desiredSpeed': 'Auto',
                                                   'enclosure': ENC1}]},

                  'FEX-with-FC-US': {'name': 'FEX-with-FC-US',
                                     'ethernetNetworkType': 'NotApplicable',
                                     'networkType': 'FibreChannel',
                                     'networkUris': [],
                                     'fcNetworkUris': ['fcnetwork-a'],
                                     'fcoeNetworkUris': [],
                                     'lacpTimer': 'Short',
                                     'logicalInterconnectUri': None,
                                     'primaryPortLocation': None,
                                     'manualLoginRedistributionState': 'NotSupported',
                                     'connectionMode': 'Auto',
                                     'nativeNetworkUri': None,
                                     'portConfigInfos': [
                                         {'bay': '2', 'port': '8', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-tunnel-US': {'name': 'FEX-tunnel-US',
                                    'ethernetNetworkType': 'Tunnel',
                                    'networkType': 'Ethernet',
                                    'networkUris': ['Tunnel'],
                                    'fcNetworkUris': [],
                                    'fcoeNetworkUris': [],
                                    'lacpTimer': 'Short',
                                    'logicalInterconnectUri': None,
                                    'primaryPortLocation': None,
                                    'manualLoginRedistributionState': 'NotSupported',
                                    'connectionMode': 'Auto',
                                    'nativeNetworkUri': None,
                                    'portConfigInfos': [
                                        {'bay': '2', 'port': '8', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-untagged-US': {'name': 'FEX-untagged-US',
                                      'ethernetNetworkType': 'Untagged',
                                      'networkType': 'Ethernet',
                                      'networkUris': ['Untagged'],
                                      'fcNetworkUris': [],
                                      'fcoeNetworkUris': [],
                                      'lacpTimer': 'Short',
                                      'logicalInterconnectUri': None,
                                      'primaryPortLocation': None,
                                      'manualLoginRedistributionState': 'NotSupported',
                                      'connectionMode': 'Auto',
                                      'nativeNetworkUri': None,
                                      'portConfigInfos': [
                                          {'bay': '2', 'port': '8', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-reserved-vlans': {'name': 'FEX-reserved-vlans',
                                         'ethernetNetworkType': 'Tagged',
                                         'networkType': 'Ethernet',
                                         'networkUris': ['net_3968', 'net_4000', 'net_4047', 'net_4094'],
                                         'fcNetworkUris': [],
                                         'fcoeNetworkUris': [],
                                         'lacpTimer': 'Short',
                                         'logicalInterconnectUri': None,
                                         'primaryPortLocation': None,
                                         'manualLoginRedistributionState': 'NotSupported',
                                         'connectionMode': 'Auto',
                                         'nativeNetworkUri': None,
                                         'portConfigInfos': [
                                             {'bay': '2', 'port': '8', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'FEX-exceeds-max-vlans-per-LI': {'name': 'FEX-exceeds-max-vlans-per-LI',
                                                   'ethernetNetworkType': 'Tagged',
                                                   'networkType': 'Ethernet',
                                                   'networkUris': rlist(2000, 3000, 'net_', ''),
                                                   'fcNetworkUris': [],
                                                   'fcoeNetworkUris': [],
                                                   'lacpTimer': 'Short',
                                                   'logicalInterconnectUri': None,
                                                   'primaryPortLocation': None,
                                                   'manualLoginRedistributionState': 'NotSupported',
                                                   'connectionMode': 'Auto',
                                                   'nativeNetworkUri': None,
                                                   'portConfigInfos': [{'bay': '2', 'port': '8', 'desiredSpeed': 'Auto',
                                                                        'enclosure': ENC1}]},

                  'FEX-exceeds-max-fcoe-per-LI': {'name': 'FEX-exceeds-max-fcoe-per-LI',
                                                  'ethernetNetworkType': 'Tagged',
                                                  'networkType': 'Ethernet',
                                                  'networkUris': [],
                                                  'fcNetworkUris': [],
                                                  'fcoeNetworkUris': rlist(1001, 1034, 'fcoe_', 'b') + ['fcoe_3969'],
                                                  'lacpTimer': 'Short',
                                                  'logicalInterconnectUri': None,
                                                  'primaryPortLocation': None,
                                                  'manualLoginRedistributionState': 'NotSupported',
                                                  'connectionMode': 'Auto',
                                                  'nativeNetworkUri': None,
                                                  'portConfigInfos': [{'bay': '2', 'port': '7', 'desiredSpeed': 'Auto',
                                                                       'enclosure': ENC1}]},

                  'FEX-max-vlans-per-LI': {'name': 'FEX-max-vlans-per-LI',
                                           'ethernetNetworkType': 'Tagged',
                                           'networkType': 'Ethernet',
                                           'networkUris': rlist(2000, 2999, 'net_', ''),
                                           'fcNetworkUris': [],
                                           'fcoeNetworkUris': rlist(1001, 1033, 'fcoe_', 'c'),
                                           'lacpTimer': 'Short',
                                           'logicalInterconnectUri': None,
                                           'primaryPortLocation': None,
                                           'manualLoginRedistributionState': 'NotSupported',
                                           'connectionMode': 'Auto',
                                           'nativeNetworkUri': None,
                                           'portConfigInfos': [
                                               {'bay': '2', 'port': '8', 'desiredSpeed': 'Auto', 'enclosure': ENC1}]},

                  'us-dup-vlanId': {'name': 'us-dup-vlanId',
                                    'ethernetNetworkType': 'Tagged',
                                    'networkType': 'Ethernet',
                                    'networkUris': ['eth-100'],
                                    'fcNetworkUris': [],
                                    'fcoeNetworkUris': ['fcoe-100'],
                                    'lacpTimer': 'Short',
                                    'logicalInterconnectUri': None,
                                    'primaryPortLocation': None,
                                    'manualLoginRedistributionState': 'NotSupported',
                                    'connectionMode': 'Auto',
                                    'nativeNetworkUri': None,
                                    'portConfigInfos': [
                                        {'bay': '2', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'BFS': {'name': 'us1',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': ['eth-102'],
                          'fcNetworkUris': [],
                          'fcoeNetworkUris': ['fcoe-1002'],
                          'lacpTimer': 'Short',
                          'logicalInterconnectUri': None,
                          'primaryPortLocation': None,
                          'manualLoginRedistributionState': 'NotSupported',
                          'connectionMode': 'Auto',
                          'nativeNetworkUri': None,
                          'portConfigInfos': [{'bay': '1', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  }

lsgs = [{'name': LSG1,
         'type': 'logical-switch-groupV4',
         'switchMapTemplate': {'switchMapEntryTemplates': [
             {'logicalLocation': {'locationEntries': [{'relativeValue': 1, 'type': 'StackingMemberId'}]},
              'permittedSwitchTypeUri': 'SWT:Cisco Nexus 55xx'}]}}
        ]

lss = [
    {"logicalSwitch": {"name": LS1, "state": "Active", "type": "logical-switchV4", "managementLevel": "BASIC_MANAGED",
                       "logicalSwitchGroupUri": "LSG:" + LSG1,
                       "switchCredentialConfiguration": [{"snmpV1Configuration": {"communityString": "public"},
                                                          "snmpV3Configuration": {"authorizationProtocol": None,
                                                                                  "privacyProtocol": None,
                                                                                  "securityLevel": None},
                                                          "logicalSwitchManagementHost": SWITCH1,
                                                          "snmpVersion": "SNMPv1", "snmpPort": 161}]},
     "logicalSwitchCredentials": [{"connectionProperties": [
         {"propertyName": "SshBasicAuthCredentialUser", "value": SWITCH1_USER, "valueFormat": "Unknown",
          "valueType": "String"}, {"propertyName": "SshBasicAuthCredentialPassword", "value": SWITCH1_PASS,
                                   "valueFormat": "SecuritySensitive", "valueType": "String"}]}]}]

icmap = [{'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'Cisco Fabric Extender for HP BladeSystem'},
         {'enclosure': 1, 'enclosureIndex': 1, 'bay': 2, 'type': 'Cisco Fabric Extender for HP BladeSystem'},
         ]

icmap2 = [{'enclosure': 1, 'enclosureIndex': 1, 'bay': 3, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 4, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
          ]

icmap3 = [{'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'Cisco Fabric Extender for HP BladeSystem'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 2, 'type': 'Cisco Fabric Extender for HP BladeSystem'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 3, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 4, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
          ]

ligs = {'FEX-LIG1': {'name': 'FEX-LIG1',
                     'type': 'logical-interconnect-groupV4',
                     'enclosureType': 'C7000',
                     'interconnectMapTemplate': icmap,
                     'uplinkSets': [uplink_sets['BFS-A'].copy(), uplink_sets['BFS-B'].copy()],
                     'stackingMode': 'Enclosure',
                     'ethernetSettings': None,
                     'state': 'Active',
                     'telemetryConfiguration': None,
                     'snmpConfiguration': None},

        'FEX-LIG-w-untagged-NS':
            {'name': 'FEX-LIG-w-untagged-NS',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-w-untagged-NS'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-LIG-edit':
            {'name': 'FEX-LIG-w-untagged-NS',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-edit-ports'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-LIG-w-untagged-US':
            {'name': 'FEX-LIG-w-untagged-US',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-w-untagged-US'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-LIG-w-untagged-net':
            {'name': 'FEX-LIG-w-untagged-net',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-w-untagged-net'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-LIG-w-tunnel-US':
            {'name': 'FEX-LIG-w-tunnel-US',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-w-tunnel-US'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-LIG-w-tunnel-net':
            {'name': 'FEX-LIG-w-tunnel-net',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-w-tunnel-net'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-and-VC-LIG':
            {'name': 'FEX-and-VC-LIG',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap3,
             'uplinkSets': [],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-US-cannot-span-ICMs':
            {'name': 'FEX-US-cannot-span-ICMs',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-US-cannot-span-ICMs'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-with-FC-US':
            {'name': 'FEX-with-FC-US',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-with-FC-US'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-US-reserved-vlans':
            {'name': 'FEX-US-reserved-vlans',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-reserved-vlans'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-exceeds-max-fcoe-per-LI':
            {'name': 'FEX-exceeds-max-fcoe-per-LI',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-exceeds-max-fcoe-per-LI'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-exceeds-max-vlans-per-LI':
            {'name': 'FEX-exceeds-max-vlans-per-LI',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-exceeds-max-vlans-per-LI'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'FEX-max-vlans-per-LI':
            {'name': 'FEX-max-vlans-per-LI',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['FEX-max-vlans-per-LI'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'VC-LIG1':
            {'name': 'VC-LIG1',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap2,
             'uplinkSets': [uplink_sets['VC-US1'].copy(), uplink_sets['VC-US2'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        }

server_profiles = [{'type': 'ServerProfileV8', 'serverHardwareUri': 'WPST-PABA58-EN3, bay 1',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PABA58-EN3', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'WPST-PABA58-EN3_Bay1-BFS-FEX', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [
                        {'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '0',
                         'networkUri': 'ETH:net_102a',
                         'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                        # for FCoE, requestedMbps must be 0, and can only use subport b.   MAC and WWN must be Physical
                        {'id': 2, 'name': '2', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b',
                         'requestedMbps': '0', 'networkUri': 'FCOE:fcoe_1002a',
                         'boot': {'priority': 'Primary', 'bootVolumeSource': 'UserDefined',
                                  'targets': [{'arrayWwpn': '21110002AC003655', 'lun': '0'}]}, 'mac': None, 'wwpn': '',
                         'wwnn': ''},
                        # {'id': 2, 'name': '2', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b', 'requestedMbps': '0', 'networkUri': 'FCOE:fcoe_1003b', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},

                    ]},
                   {'type': 'ServerProfileV8', 'serverHardwareUri': 'WPST-PABA58-EN3, bay 2',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PABA58-EN3', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'WPST-PABA58-EN3_Bay2-BFS-VC', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Mezz 1:1-a',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_102a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1-b',
                                     'requestedMbps': '2500', 'networkUri': 'FCOE:fcoe_1002a',
                                     'boot': {'priority': 'Primary', 'bootVolumeSource': 'UserDefined',
                                              'targets': [{'arrayWwpn': '21110002AC003655', 'lun': '0'}]}, 'mac': None,
                                     'wwpn': '', 'wwnn': ''},

                                    ]},
                   ]

fex_vc_profile = {'type': 'ServerProfileV8', 'serverHardwareUri': 'WPST-PABA58-EN3, bay 2',
                  'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PABA58-EN3', 'enclosureGroupUri': 'EG:EG',
                  'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                  'name': 'WPST-PABA58-EN3_Bay2-BFS-VC', 'description': '', 'affinity': 'Bay',
                  'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                  'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Mezz 1:1-a',
                                   'requestedMbps': '2500', 'networkUri': 'ETH:net_102a',
                                   'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                  {'id': 2, 'name': '2', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1-b',
                                   'requestedMbps': '2500', 'networkUri': 'FCOE:fcoe_1002a',
                                   'boot': {'priority': 'Primary', 'bootVolumeSource': 'UserDefined',
                                            'targets': [{'arrayWwpn': '21110002AC003655', 'lun': '0'}]}, 'mac': None,
                                   'wwpn': '', 'wwnn': ''},

                                  ]}

sp = [x for x in server_profiles if x['name'] == 'WPST-PABA58-EN3_Bay2-BFS-VC']
