# User Login Data
admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}

server_profiles_r5 = [
    {'name': 'r5-1-b1', 'serverHardwareUri': 'r5-1, bay 1', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    {'name': 'r5-1-b2', 'serverHardwareUri': 'r5-1, bay 2', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    {'name': 'r5-1-b3', 'serverHardwareUri': 'r5-1, bay 3', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-1-b4', 'serverHardwareUri': 'r5-1, bay 4', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-1-b5', 'serverHardwareUri': 'r5-1, bay 5', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-1-b6', 'serverHardwareUri': 'r5-1, bay 6', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-1-b7', 'serverHardwareUri': 'r5-1, bay 7', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-1-b8', 'serverHardwareUri': 'r5-1, bay 8', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-1-b9', 'serverHardwareUri': 'r5-1, bay 9', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-1-b10', 'serverHardwareUri': 'r5-1, bay 10', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-1-b11', 'serverHardwareUri': 'r5-1, bay 11', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-1-b12', 'serverHardwareUri': 'r5-1, bay 12', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    {'name': 'r5-2-b1', 'serverHardwareUri': 'r5-2, bay 1', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    {'name': 'r5-2-b2', 'serverHardwareUri': 'r5-2, bay 2', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    {'name': 'r5-2-b3', 'serverHardwareUri': 'r5-2, bay 3', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-2-b4', 'serverHardwareUri': 'r5-2, bay 4', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-2-b5', 'serverHardwareUri': 'r5-2, bay 5', 'serverHardwareTypeUri': 'SHT:r5','serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-2-b6', 'serverHardwareUri': 'r5-2, bay 6', 'serverHardwareTypeUri': 'SHT:r5','serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-2-b7', 'serverHardwareUri': 'r5-2, bay 7', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-2-b8', 'serverHardwareUri': 'r5-2, bay 8', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-2-b9', 'serverHardwareUri': 'r5-2, bay 9', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-2-b10', 'serverHardwareUri': 'r5-2, bay 10', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-2-b11', 'serverHardwareUri': 'r5-2, bay 11', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-2-b12', 'serverHardwareUri': 'r5-2, bay 12', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    {'name': 'r5-3-b1', 'serverHardwareUri': 'r5-3, bay 1', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    {'name': 'r5-3-b2', 'serverHardwareUri': 'r5-3, bay 2', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b3', 'serverHardwareUri': 'r5-3, bay 3', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b4', 'serverHardwareUri': 'r5-3, bay 4', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b5', 'serverHardwareUri': 'r5-3, bay 5', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b5', 'serverHardwareUri': 'r5-3, bay 5', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b6', 'serverHardwareUri': 'r5-3, bay 6', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b7', 'serverHardwareUri': 'r5-3, bay 7', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b8', 'serverHardwareUri': 'r5-3, bay 8', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b9', 'serverHardwareUri': 'r5-3, bay 9', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b10', 'serverHardwareUri': 'r5-3, bay 10', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b11', 'serverHardwareUri': 'r5-3, bay 11', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'},
    # {'name': 'r5-3-b12', 'serverHardwareUri': 'r5-3, bay 12', 'serverHardwareTypeUri': 'SHT:r5', 'serverProfileTemplateUri': 'SPT:r5', 'type': 'ServerProfileV8'}
]


server_profiles_r6 = [
    {'name': 'r6-1-b3', 'serverHardwareUri': 'r6-1, bay 3', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-1-b4', 'serverHardwareUri': 'r6-1, bay 4', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-1-b5', 'serverHardwareUri': 'r6-1, bay 5', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-1-b6', 'serverHardwareUri': 'r6-1, bay 6', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-1-b7', 'serverHardwareUri': 'r6-1, bay 7', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-1-b8', 'serverHardwareUri': 'r6-1, bay 8', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-1-b9', 'serverHardwareUri': 'r6-1, bay 9', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-1-b10', 'serverHardwareUri': 'r6-1, bay 10', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-1-b11', 'serverHardwareUri': 'r6-1, bay 11', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-1-b12', 'serverHardwareUri': 'r6-1, bay 12', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-2-b3', 'serverHardwareUri': 'r6-2, bay 3', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-2-b4', 'serverHardwareUri': 'r6-2, bay 4', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-2-b5', 'serverHardwareUri': 'r6-2, bay 5', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-2-b6', 'serverHardwareUri': 'r6-2, bay 6', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-2-b7', 'serverHardwareUri': 'r6-2, bay 7', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-2-b8', 'serverHardwareUri': 'r6-2, bay 8', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-2-b9', 'serverHardwareUri': 'r6-2, bay 9', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-2-b10', 'serverHardwareUri': 'r6-2, bay 10', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-2-b11', 'serverHardwareUri': 'r6-2, bay 11', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-2-b12', 'serverHardwareUri': 'r6-2, bay 12', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-3-b3', 'serverHardwareUri': 'r6-3, bay 3', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-3-b4', 'serverHardwareUri': 'r6-3, bay 4', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-3-b5', 'serverHardwareUri': 'r6-3, bay 5', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    {'name': 'r6-3-b6', 'serverHardwareUri': 'r6-3, bay 6', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-3-b7', 'serverHardwareUri': 'r6-3, bay 7', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-3-b8', 'serverHardwareUri': 'r6-3, bay 8', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-3-b9', 'serverHardwareUri': 'r6-3, bay 9', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-3-b10', 'serverHardwareUri': 'r6-3, bay 10', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-3-b11', 'serverHardwareUri': 'r6-3, bay 11', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'},
    # {'name': 'r6-3-b12', 'serverHardwareUri': 'r6-3, bay 12', 'serverHardwareTypeUri': 'SHT:r6', 'serverProfileTemplateUri': 'SPT:r6', 'type': 'ServerProfileV8'}
]

server_profiles_r11 = [
    {'name': 'r11-1-b3', 'serverHardwareUri': 'r11-1, bay 3', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-1-b4', 'serverHardwareUri': 'r11-1, bay 4', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-1-b5', 'serverHardwareUri': 'r11-1, bay 5', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    # {'name': 'r11-1-b6', 'serverHardwareUri': 'r11-1, bay 6', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-1-b7', 'serverHardwareUri': 'r11-1, bay 7', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-1-b8', 'serverHardwareUri': 'r11-1, bay 8', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-1-b9', 'serverHardwareUri': 'r11-1, bay 9', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-1-b10', 'serverHardwareUri': 'r11-1, bay 10', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-1-b11', 'serverHardwareUri': 'r11-1, bay 11', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-1-b12', 'serverHardwareUri': 'r11-1, bay 12', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b3', 'serverHardwareUri': 'r11-2, bay 3', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b4', 'serverHardwareUri': 'r11-2, bay 4', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b5', 'serverHardwareUri': 'r11-2, bay 5', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b6', 'serverHardwareUri': 'r11-2, bay 6', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b7', 'serverHardwareUri': 'r11-2, bay 7', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b8', 'serverHardwareUri': 'r11-2, bay 8', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b9', 'serverHardwareUri': 'r11-2, bay 9', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b10', 'serverHardwareUri': 'r11-2, bay 10', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b11', 'serverHardwareUri': 'r11-2, bay 11', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-2-b12', 'serverHardwareUri': 'r11-2, bay 12', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b3', 'serverHardwareUri': 'r11-3, bay 3', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b4', 'serverHardwareUri': 'r11-3, bay 4', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b5', 'serverHardwareUri': 'r11-3, bay 5', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b6', 'serverHardwareUri': 'r11-3, bay 6', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b7', 'serverHardwareUri': 'r11-3, bay 7', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b8', 'serverHardwareUri': 'r11-3, bay 8', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b9', 'serverHardwareUri': 'r11-3, bay 9', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b10', 'serverHardwareUri': 'r11-3, bay 10', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b11', 'serverHardwareUri': 'r11-3, bay 11', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'},
    {'name': 'r11-3-b12', 'serverHardwareUri': 'r11-3, bay 12', 'serverHardwareTypeUri': 'SHT:r11', 'serverProfileTemplateUri': 'SPT:r11', 'type': 'ServerProfileV8'}
]

server_profiles_r12 = [
    # {'name': 'r12-1-b1', 'serverHardwareUri': 'r12-1, bay 1', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    # {'name': 'r12-1-b2', 'serverHardwareUri': 'r12-1, bay 2', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b3', 'serverHardwareUri': 'r12-1, bay 3', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b4', 'serverHardwareUri': 'r12-1, bay 4', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b5', 'serverHardwareUri': 'r12-1, bay 5', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b6', 'serverHardwareUri': 'r12-1, bay 6', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b7', 'serverHardwareUri': 'r12-1, bay 7', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b8', 'serverHardwareUri': 'r12-1, bay 8', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b9', 'serverHardwareUri': 'r12-1, bay 9', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b10', 'serverHardwareUri': 'r12-1, bay 10', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b11', 'serverHardwareUri': 'r12-1, bay 11', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-1-b12', 'serverHardwareUri': 'r12-1, bay 12', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    # {'name': 'r12-2-b1', 'serverHardwareUri': 'r12-2, bay 1', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    # {'name': 'r12-2-b2', 'serverHardwareUri': 'r12-2, bay 2', 'serverHardwareTypeUri': 'SHT:r12','serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b3', 'serverHardwareUri': 'r12-2, bay 3', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b4', 'serverHardwareUri': 'r12-2, bay 4', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b5', 'serverHardwareUri': 'r12-2, bay 5', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b6', 'serverHardwareUri': 'r12-2, bay 6', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b7', 'serverHardwareUri': 'r12-2, bay 7', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b8', 'serverHardwareUri': 'r12-2, bay 8', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b9', 'serverHardwareUri': 'r12-2, bay 9', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b10', 'serverHardwareUri': 'r12-2, bay 10', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b11', 'serverHardwareUri': 'r12-2, bay 11', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-2-b12', 'serverHardwareUri': 'r12-2, bay 12', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b3', 'serverHardwareUri': 'r12-3, bay 3', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    # {'name': 'r12-3-b1', 'serverHardwareUri': 'r12-3, bay 1', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    # {'name': 'r12-3-b2', 'serverHardwareUri': 'r12-3, bay 2', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b4', 'serverHardwareUri': 'r12-3, bay 4', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b5', 'serverHardwareUri': 'r12-3, bay 5', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b6', 'serverHardwareUri': 'r12-3, bay 6', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b7', 'serverHardwareUri': 'r12-3, bay 7', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b8', 'serverHardwareUri': 'r12-3, bay 8', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b9', 'serverHardwareUri': 'r12-3, bay 9', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b10', 'serverHardwareUri': 'r12-3, bay 10', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b11', 'serverHardwareUri': 'r12-3, bay 11', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'},
    {'name': 'r12-3-b12', 'serverHardwareUri': 'r12-3, bay 12', 'serverHardwareTypeUri': 'SHT:r12', 'serverProfileTemplateUri': 'SPT:r12', 'type': 'ServerProfileV8'}
]

server_profiles_r13 = [
    {'name': 'r13-1-b3', 'serverHardwareUri': 'r13-1, bay 3', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-1-b4', 'serverHardwareUri': 'r13-1, bay 4', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-1-b5', 'serverHardwareUri': 'r13-1, bay 5', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-1-b6', 'serverHardwareUri': 'r13-1, bay 6', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-1-b7', 'serverHardwareUri': 'r13-1, bay 7', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-1-b8', 'serverHardwareUri': 'r13-1, bay 8', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-1-b9', 'serverHardwareUri': 'r13-1, bay 9', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-1-b10', 'serverHardwareUri': 'r13-1, bay 10', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-1-b11', 'serverHardwareUri': 'r13-1, bay 11', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-1-b12', 'serverHardwareUri': 'r13-1, bay 12', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b3', 'serverHardwareUri': 'r13-2, bay 3', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b4', 'serverHardwareUri': 'r13-2, bay 4', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b5', 'serverHardwareUri': 'r13-2, bay 5', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b6', 'serverHardwareUri': 'r13-2, bay 6', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b7', 'serverHardwareUri': 'r13-2, bay 7', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b8', 'serverHardwareUri': 'r13-2, bay 8', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b9', 'serverHardwareUri': 'r13-2, bay 9', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b10', 'serverHardwareUri': 'r13-2, bay 10', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b11', 'serverHardwareUri': 'r13-2, bay 11', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-2-b12', 'serverHardwareUri': 'r13-2, bay 12', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b3', 'serverHardwareUri': 'r13-3, bay 3', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b4', 'serverHardwareUri': 'r13-3, bay 4', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b5', 'serverHardwareUri': 'r13-3, bay 5', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b6', 'serverHardwareUri': 'r13-3, bay 6', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b7', 'serverHardwareUri': 'r13-3, bay 7', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b8', 'serverHardwareUri': 'r13-3, bay 8', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b9', 'serverHardwareUri': 'r13-3, bay 9', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b10', 'serverHardwareUri': 'r13-3, bay 10', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b11', 'serverHardwareUri': 'r13-3, bay 11', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'},
    {'name': 'r13-3-b12', 'serverHardwareUri': 'r13-3, bay 12', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r13', 'type': 'ServerProfileV8'}
]

server_profiles_r14 = [
    {'name': 'r14-1-b3', 'serverHardwareUri': 'r14-1, bay 3', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-1-b4', 'serverHardwareUri': 'r14-1, bay 4', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-1-b5', 'serverHardwareUri': 'r14-1, bay 5', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-1-b6', 'serverHardwareUri': 'r14-1, bay 6', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-1-b7', 'serverHardwareUri': 'r14-1, bay 7', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-1-b8', 'serverHardwareUri': 'r14-1, bay 8', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-1-b9', 'serverHardwareUri': 'r14-1, bay 9', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-1-b10', 'serverHardwareUri': 'r14-1, bay 10', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-1-b11', 'serverHardwareUri': 'r14-1, bay 11', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-1-b12', 'serverHardwareUri': 'r14-1, bay 12', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b3', 'serverHardwareUri': 'r14-2, bay 3', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b4', 'serverHardwareUri': 'r14-2, bay 4', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b5', 'serverHardwareUri': 'r14-2, bay 5', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b6', 'serverHardwareUri': 'r14-2, bay 6', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b7', 'serverHardwareUri': 'r14-2, bay 7', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b8', 'serverHardwareUri': 'r14-2, bay 8', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b9', 'serverHardwareUri': 'r14-2, bay 9', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b10', 'serverHardwareUri': 'r14-2, bay 10', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b11', 'serverHardwareUri': 'r14-2, bay 11', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-2-b12', 'serverHardwareUri': 'r14-2, bay 12', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b3', 'serverHardwareUri': 'r14-3, bay 3', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b4', 'serverHardwareUri': 'r14-3, bay 4', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b5', 'serverHardwareUri': 'r14-3, bay 5', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b6', 'serverHardwareUri': 'r14-3, bay 6', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b7', 'serverHardwareUri': 'r14-3, bay 7', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b8', 'serverHardwareUri': 'r14-3, bay 8', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b9', 'serverHardwareUri': 'r14-3, bay 9', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b10', 'serverHardwareUri': 'r14-3, bay 10', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b11', 'serverHardwareUri': 'r14-3, bay 11', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'},
    {'name': 'r14-3-b12', 'serverHardwareUri': 'r14-3, bay 12', 'serverHardwareTypeUri': 'SHT:r13-r14', 'serverProfileTemplateUri': 'SPT:r14', 'type': 'ServerProfileV8'}
]

server_profiles_r16 = [
    {'name': 'r16-1-b1', 'serverHardwareUri': 'r16-1, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-1-b2', 'serverHardwareUri': 'r16-1, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-1-b3', 'serverHardwareUri': 'r16-1, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-1-b4', 'serverHardwareUri': 'r16-1, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-1-b5', 'serverHardwareUri': 'r16-1, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-1-b6', 'serverHardwareUri': 'r16-1, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-1-b7', 'serverHardwareUri': 'r16-1, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-1-b8', 'serverHardwareUri': 'r16-1, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-1-b9', 'serverHardwareUri': 'r16-1, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-1-b10', 'serverHardwareUri': 'r16-1, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-1-b11', 'serverHardwareUri': 'r16-1, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-1-b12', 'serverHardwareUri': 'r16-1, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-2-b1', 'serverHardwareUri': 'r16-2, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-2-b2', 'serverHardwareUri': 'r16-2, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-2-b3', 'serverHardwareUri': 'r16-2, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-2-b4', 'serverHardwareUri': 'r16-2, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-2-b5', 'serverHardwareUri': 'r16-2, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-2-b6', 'serverHardwareUri': 'r16-2, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-2-b7', 'serverHardwareUri': 'r16-2, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-2-b8', 'serverHardwareUri': 'r16-2, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-2-b9', 'serverHardwareUri': 'r16-2, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-2-b10', 'serverHardwareUri': 'r16-2, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-2-b11', 'serverHardwareUri': 'r16-2, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-2-b12', 'serverHardwareUri': 'r16-2, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-3-b1', 'serverHardwareUri': 'r16-3, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-3-b2', 'serverHardwareUri': 'r16-3, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-3-b3', 'serverHardwareUri': 'r16-3, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    {'name': 'r16-3-b4', 'serverHardwareUri': 'r16-3, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'}
    # {'name': 'r16-3-b5', 'serverHardwareUri': 'r16-3, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-3-b7', 'serverHardwareUri': 'r16-3, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-3-b8', 'serverHardwareUri': 'r16-3, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-3-b9', 'serverHardwareUri': 'r16-3, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-3-b10', 'serverHardwareUri': 'r16-3, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-3-b11', 'serverHardwareUri': 'r16-3, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'},
    # {'name': 'r16-3-b12', 'serverHardwareUri': 'r16-3, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r16', 'serverProfileTemplateUri': 'SPT:r16', 'type': 'ServerProfileV8'}
]
