admin_credentials = {'userName': 'Administrator', 'password': 'wpsthpvse1'}
server_credentials = {'userName': 'Serveradmin', 'password': 'wpsthpvse1'}
network_credentials = {'userName': 'Networkadmin', 'password': 'wpsthpvse1'}

appliance = {"type": "ApplianceNetworkConfiguration",
             "applianceNetworks": [{"activeNode": 1, "unconfigure": False, "app1Ipv4Addr": "16.114.213.17", "app1Ipv6Addr": "",
                                    "app2Ipv4Addr": "16.114.213.18", "app2Ipv6Addr": "",
                                    "virtIpv4Addr": "16.114.213.16", "virtIpv6Addr": None, "app1Ipv4Alias": None, "app1Ipv6Alias": None,
                                    "app2Ipv4Alias": None, "app2Ipv6Alias": None, "hostname": "wpst-31.vse.rdlabs.hpecorp.net",
                                    "confOneNode": True, "interfaceName": "", "macAddress": None,
                                    "ipv4Type": "STATIC", "ipv6Type": "UNCONFIGURE", "overrideIpv4DhcpDnsServers": False,
                                    "ipv4Subnet": "255.255.240.0", "ipv4Gateway": "16.114.208.1", "ipv6Subnet": None, "ipv6Gateway": None,
                                    "domainName": "vse.rdlabs.hpecorp.net", "searchDomains": [], "ipv4NameServers":["16.125.25.81", "16.125.25.82"],
                                    "ipv6NameServers":["16.125.25.81", "16.125.25.82"], "bondedTo":None, "aliasDisabled":True,
                                    "configureRabbitMqSslListener":False, "configurePostgresSslListener":False, "webServerCertificate":None,
                                    "webServerCertificateChain":None, "webServerCertificateKey":None}
                                   ],
             "serverCertificate": {"rabbitMQCertificate": None, "rabbitMQRootCACertificate": None,
                                   "rabbitMQCertificateKey": None, "postgresCertificate": None,
                                   "postgresRootCACertificate": None, "postgresCertificateKey": None}
             }

timeandlocale = {'type': 'TimeAndLocale', 'dateTime': None, 'timezone': 'UTC', 'ntpServers': ['ntp.hpecorp.net'], 'locale': 'en_US.UTF-8'}

users = [{'userName': 'Serveradmin', 'password': 'wpsthpvse1', 'fullName': 'Serveradmin', 'roles': ['Server administrator'], 'emailAddress': 'sarah@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'},
         {'userName': 'Networkadmin', 'password': 'wpsthpvse1', 'fullName': 'Networkadmin', 'roles': ['Network administrator'], 'emailAddress': 'nat@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'},
         {'userName': 'Backupadmin', 'password': 'wpsthpvse1', 'fullName': 'Backupadmin', 'roles': ['Backup administrator'], 'emailAddress': 'backup@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'},
         {'userName': 'Noprivledge', 'password': 'wpsthpvse1', 'fullName': 'Noprivledge', 'roles': ['Read only'], 'emailAddress': 'rheid@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'}
         ]

licenses = [{'key': 'YCDC D9MA H9PQ KHX2 V7B5 HWWB Y9JL KMPL TA2E PDRA DXAU 2CSM GHTG L762 HUK7 GB5M KJVT D5KM EFRW DS5R TXXK 6Q22 AK2P 3EW2 AJQ4 HU5V TZZH AB6X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542007 HPOV-NFR1 HP_OneView_16_Seat_NFR 75YYJJECU46C"_3DWNY-6B2KD-D8Z6S-6YR4B-K8GDW'},
            {'key': '9CTC B9MA H9PA GHWY V7B5 HWWB Y9JL KMPL 3ASE NGRE DXAU 2CSM GHTG L762 FN83 EARE KJVT D5KM EFRW DS5R 3XPK 4T22 AK2P 3EW2 AJA6 XUNV TZZX MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542185 HPOV-NFR1 HP_OneView_16_Seat_NFR JJT5JJEC9DC5"_3JNBT-28349-3DJ6L-TBRPP-PDLNR'},
            {'key': '9B3C A99A H9P9 GHUZ U7B5 HWW5 Y9JL KMPL 5AWA 8CBE DXAU 2CSM GHTG L762 7NGZ GDV4 KJVT D5KM EFRW DS5R 5XP8 4XK2 GNSL 9F82 7JKT QVXB XZKH ABB4 NV2C LHXU KN7U 5NA6 BKRK 35QB D8UW R42A X3BN LQ6M 5V9A PM6Q 4MN9 9GGS EZU7 GEMX VUJW CDB5 JVRX 8HEN 2J98 ACPB "TKOPREN HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR ATJUJJEDAT2Y"'},
            {'key': 'QCTG B9MA H9P9 8HW3 V7B5 HWWB Y9JL KMPL 5AKE 8DBA DXAU 2CSM GHTG L762 VYW6 GCN9 KJVT D5KM EFVW DT5J 5XHK 5QK2 AK2P 3EW2 QJQ4 HU5V TZZ7 9B5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542022 HPOV-NFR1 HP_OneView_16_Seat_NFR AACUJJECUT2J"_3DWNY-DZZW8-24Y5Y-NZB2K-YH5R2'},
            {'key': '9CTC C9MA H9PY CHUY V7B5 HWWB Y9JL KMPL VACE 8GRE DXAU 2CSM GHTG L762 7RGY XHBE KJVT D5KM EFVW DT5J VX79 5T22 AK2P 3EW2 9JA6 XUNV TZZH MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542193 HPOV-NFR1 HP_OneView_16_Seat_NFR 9UH2JJECJ4AA"_3JNDQ-Z35J3-D6T6M-5XKZL-WC2W2'},
            {'key': 'YBLG B99A H9PQ 8HVZ U7B5 HWW5 Y9JL KMPL VAWA 8CBE DXAU 2CSM GHTG L762 5NW5 HDV4 KJVT D5KM EFVW DT5J VXP8 4XK2 GNSL 9F82 7JKT QVXB XZKH ABB4 NV2C LHXU KN7U 5NA6 BKRK 35QB D8UW R42A X3BN LQ6M 5V9A PM6Q 4MN9 9GGS EZU7 GEMX VUJW CDB5 JVRX 8HEN 2J98 ACPB "TKOPREN HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR JJADJJEDATCA"'},
            ]

# Enclosures
ENC1 = '0000A66101'
ENC2 = '0000A66102'
ENC3 = '0000A66103'
# Interconnects
ENC1ICBAY3 = '%s, interconnect 3' % ENC1
ENC1ICBAY6 = '%s, interconnect 6' % ENC1
ENC2ICBAY3 = '%s, interconnect 3' % ENC2
ENC2ICBAY6 = '%s, interconnect 6' % ENC2
ENC3ICBAY3 = '%s, interconnect 3' % ENC3
ENC3ICBAY6 = '%s, interconnect 6' % ENC3
# Sas Interconnects
ENC1SASICBAY1 = '%s, interconnect 1' % ENC1
ENC1SASICBAY4 = '%s, interconnect 4' % ENC1
ENC2SASICBAY1 = '%s, interconnect 1' % ENC2
ENC2SASICBAY4 = '%s, interconnect 4' % ENC2
ENC3SASICBAY1 = '%s, interconnect 1' % ENC3
ENC3SASICBAY4 = '%s, interconnect 4' % ENC3
# Drive Enclosures (Bigbird)
ENC1DEBAY1 = '%s, bay 1' % ENC1
ENC1DEBAY7 = '%s, bay 7' % ENC1
ENC2DEBAY1 = '%s, bay 1' % ENC2
ENC2DEBAY7 = '%s, bay 7' % ENC2
ENC3DEBAY1 = '%s, bay 1' % ENC3
ENC3DEBAY7 = '%s, bay 7' % ENC3
# Server Hardware
ENC1SHBAY3 = '%s, bay 3' % ENC1
ENC1SHBAY4 = '%s, bay 4' % ENC1
ENC1SHBAY5 = '%s, bay 5' % ENC1
ENC1SHBAY6 = '%s, bay 6' % ENC1
ENC1SHBAY9 = '%s, bay 9' % ENC1
ENC1SHBAY10 = '%s, bay 10' % ENC1
ENC1SHBAY11 = '%s, bay 11' % ENC1
ENC1SHBAY12 = '%s, bay 12' % ENC1
ENC2SHBAY3 = '%s, bay 3' % ENC2
ENC2SHBAY4 = '%s, bay 4' % ENC2
ENC2SHBAY5 = '%s, bay 5' % ENC2
ENC2SHBAY6 = '%s, bay 6' % ENC2
ENC2SHBAY9 = '%s, bay 9' % ENC2
ENC2SHBAY10 = '%s, bay 10' % ENC2
ENC2SHBAY11 = '%s, bay 11' % ENC2
ENC2SHBAY12 = '%s, bay 12' % ENC2
ENC3SHBAY3 = '%s, bay 3' % ENC3
ENC3SHBAY4 = '%s, bay 4' % ENC3
ENC3SHBAY5 = '%s, bay 5' % ENC3
ENC3SHBAY6 = '%s, bay 6' % ENC3
ENC3SHBAY9 = '%s, bay 9' % ENC3
ENC3SHBAY10 = '%s, bay 10' % ENC3
ENC3SHBAY11 = '%s, bay 11' % ENC3
ENC3SHBAY12 = '%s, bay 12' % ENC3

enclosures = [
    {"type": "EnclosureV300", "name": ENC1, },
    {"type": "EnclosureV300", "name": ENC2, },
    {"type": "EnclosureV300", "name": ENC3, },
]

sasics = [
    {"name": ENC1SASICBAY1, },
    {"name": ENC2SASICBAY1, },
    {"name": ENC3SASICBAY1, },
    {"name": ENC1SASICBAY4, },
    {"name": ENC2SASICBAY4, },
    {"name": ENC3SASICBAY4, },
]

sasics_bay1 = [
    {"name": ENC1SASICBAY1, },
    {"name": ENC2SASICBAY1, },
    {"name": ENC3SASICBAY1, },
]

sasics_bay4 = [
    {"name": ENC1SASICBAY4, },
    {"name": ENC2SASICBAY4, },
    {"name": ENC3SASICBAY4, },

]

ics = [
    {"name": ENC1ICBAY3, },
    {"name": ENC1ICBAY6, },
    {"name": ENC2ICBAY3, },
    {"name": ENC2ICBAY6, },
    {"name": ENC3ICBAY3, },
    {"name": ENC3ICBAY6, },
]

ethernet_networks = [{'name': 'net100',
                      'type': 'ethernet-networkV300',
                      'vlanId': 100,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'net300',
                      'type': 'ethernet-networkV300',
                      'vlanId': 300,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     ]

icmap = [{'bay': 3, 'enclosure': 1, 'type': 'Virtual Connect SE 40Gb F8 Module for Synergy', 'enclosureIndex': 1},
         {'bay': 6, 'enclosure': 2, 'type': 'Virtual Connect SE 40Gb F8 Module for Synergy', 'enclosureIndex': 2},
         {'bay': 6, 'enclosure': 1, 'type': 'Synergy 20Gb Interconnect Link Module', 'enclosureIndex': 1},
         {'bay': 3, 'enclosure': 2, 'type': 'Synergy 20Gb Interconnect Link Module', 'enclosureIndex': 2},
         {'bay': 3, 'enclosure': 3, 'type': 'Synergy 20Gb Interconnect Link Module', 'enclosureIndex': 3},
         {'bay': 6, 'enclosure': 3, 'type': 'Synergy 20Gb Interconnect Link Module', 'enclosureIndex': 3},
         ]

uplink_sets = {'us_ethernet': {'name': 'us_ethernet',
                               'ethernetNetworkType': 'Tagged',
                               'networkType': 'Ethernet',
                               'networkUris': ['net100', 'net300'],
                               'nativeNetworkUri': None,
                               'mode': 'Auto',
                               'lacpTimer': 'Long',
                               'logicalPortConfigInfos': [{'enclosure': '1', 'bay': '3', 'port': 'Q1', 'speed': 'Auto'},
                                                          ]
                               },
               }

ligs = [{'name': 'LIG1',
         'type': 'logical-interconnect-groupV300',
         'enclosureType': 'SY12000',
         'interconnectMapTemplate': icmap,
         'enclosureIndexes': [1, 2, 3],
         'interconnectBaySet': 3,
         'redundancyType': 'HighlyAvailable',
         'ethernetSettings': None,
         'fcoeSettings': {'fcoeMode': 'FcfNpv'},
         'stackingMode': 'Enclosure',
         'state': 'Active',
         'telemetryConfiguration': None,
         'snmpConfiguration': None,
         'uplinkSets': [uplink_sets['us_ethernet'].copy()],
         }
        ]

sasligs = [{'name': 'SASLIG1',  # Single SAS switch
            "type": "sas-logical-interconnect-group",
            "enclosureType": "SY12000",
            "enclosureIndexes": [1],
            "interconnectBaySet": "1",
            'interconnectMapTemplate': [{'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'Synergy 12Gb SAS Connection Module'},
                                        ],
            }
           ]

egs = [{'name': 'EG1',
        'type': 'EnclosureGroupV300',
        'enclosureCount': 3,
        'enclosureTypeUri': '/rest/enclosure-types/SY12000',
        'stackingMode': 'Enclosure',
        'interconnectBayMappingCount': 2,
        'configurationScript': None,
        'interconnectBayMappings':
        [{"interconnectBay": 1, "logicalInterconnectGroupUri": "SASLIG:SASLIG1"},
         {"interconnectBay": 3, "logicalInterconnectGroupUri": "LIG:LIG1"},
         {"interconnectBay": 6, "logicalInterconnectGroupUri": "LIG:LIG1"}
         ],
        'ipAddressingMode': "External",
        'ipRangeUris': [],
        'powerMode': "RedundantPowerFeed"
        }
       ]

les = [{'name': 'LE1',
        'enclosureUris': ['ENC:' + ENC1, 'ENC:' + ENC2, 'ENC:' + ENC3],
        'enclosureGroupUri': 'EG:EG1',
        'firmwareBaselineUri': None,
        'forceInstallFirmware': False
        }]

profile_templates = [{'type': 'ServerProfileTemplateV2',
                      'serverProfileDescription': '0000A66101, bay 3-withBothRaid',
                      'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                      'enclosureGroupUri': 'EG:EG1',
                      'serialNumberType': 'Virtual',
                      'macType': 'Virtual',
                      'wwnType': 'Virtual',
                      'name': '0000A66101, bay 3-SPT-withBothRaid',
                      'description': '0000A66101, bay 3-SPT-withBothRaid',
                      'affinity': 'Bay',
                      'connections': [{'id': 1,
                                       'name': '',
                                       'functionType': 'Ethernet',
                                       'portId': 'Auto',
                                       'requestedMbps': '2500',
                                       'networkUri': 'ETH:net100',
                                       'boot': {'priority': 'NotBootable'},
                                       'requestedVFs': 'Auto'}],
                      'boot': {'manageBoot': True, 'order': ['HardDisk']},
                      'bootMode':{'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                      'bios': {'manageBios': False, 'overriddenSettings': []},
                      'hideUnusedFlexNics': True,
                      'localStorage':{'sasLogicalJBODs': [{'id': 1,
                                                           'name': '0000A66101, bay 3-rd0',
                                                           'deviceSlot': 'Mezz 1',
                                                           'numPhysicalDrives': 3,
                                                           'driveMinSizeGB': 50000,
                                                           'driveMaxSizeGB': 5000000,
                                                           'driveTechnology': 'SasSsd'}],
                                      'controllers': [{'logicalDrives': [{'name': '0000A66101, bay 3-rd1',
                                                                          'raidLevel': 'RAID1',
                                                                          'bootable': False,
                                                                          'numPhysicalDrives': 2,
                                                                          'driveTechnology': 'SasSsd',
                                                                          'sasLogicalJBODId': None}],
                                                       'deviceSlot': 'Embedded',
                                                       'mode': 'RAID',
                                                       'initialize': True},
                                                      {'logicalDrives': [{'name': None,
                                                                          'raidLevel': 'RAID0',
                                                                          'bootable': False,
                                                                          'numPhysicalDrives': None,
                                                                          'driveTechnology': None,
                                                                          'sasLogicalJBODId': 1}],
                                                       'deviceSlot': 'Mezz 1',
                                                       'mode': 'RAID',
                                                       'initialize': False}]},
                      'sanStorage': None},
                     {
                     'type': 'ServerProfileTemplateV2',
                     'serverProfileDescription': '0000A66101, bay 4-withbothHBA',
                     'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                     'enclosureGroupUri': 'EG:EG1',
                     'serialNumberType': 'Virtual',
                     'macType': 'Virtual',
                     'wwnType': 'Virtual',
                     'name': '0000A66101, bay 4-SPT-withbothHBA',
                     'description': '0000A66101, bay 4-SPT-withbothHBA',
                     'affinity': 'Bay',
                     'connections': [{
                                     'id': 1,
                                     'name': '',
                                     'functionType': 'Ethernet',
                                     'portId': 'Auto',
                                     'requestedMbps': '2500',
                                     'networkUri': 'ETH:net100',
                                     'requestedVFs': 'Auto'
                                     }
                                     ],
                     'boot': None,
                     'bootMode': {'manageMode': False},
                     'bios': {'manageBios': False, 'overriddenSettings': []},
                     'hideUnusedFlexNics': True,
                     'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                           'deviceSlot': 'Mezz 1',
                                                           'name': '0000A66101, bay 4-jbod1',
                                                           'numPhysicalDrives': 3,
                                                           'driveMinSizeGB': 50000,
                                                           'driveMaxSizeGB': 5000000,
                                                           'driveTechnology': 'SasSsd'}],
                                      'controllers': [{'logicalDrives': [],
                                                       'deviceSlot': 'Embedded',
                                                       'mode': 'HBA',
                                                       'initialize': True},
                                                      {'logicalDrives': [],
                                                       'deviceSlot': 'Mezz 1',
                                                       'mode': 'HBA',
                                                       'initialize': False}]
                                      },
                     'sanStorage': None
                     },
                     ]

verify_profile_templates = [{'type': 'ServerProfileTemplateV2',
                             'serverProfileDescription': '0000A66101, bay 3-withBothRaid',
                             'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                             'enclosureGroupUri': 'EG:EG1',
                             'serialNumberType': 'Virtual',
                             'macType': 'Virtual',
                             'wwnType': 'Virtual',
                             'name': '0000A66101, bay 3-SPT-withBothRaid',
                             'description': '0000A66101, bay 3-SPT-withBothRaid',
                             'affinity': 'Bay',
                             'connections': [{'id': 1,
                                              'name': '',
                                              'functionType': 'Ethernet',
                                              'portId': 'Mezz 3:1-a',
                                              'requestedMbps': '2500',
                                              'networkUri': 'ETH:net100',
                                              'boot': {'priority': 'NotBootable'},
                                              'requestedVFs': 'Auto'}],
                             'boot': {'manageBoot': True, 'order': ['HardDisk']},
                             'bootMode':{'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                             'bios': {'manageBios': False, 'overriddenSettings': []},
                             'hideUnusedFlexNics': True,
                             'localStorage':{'sasLogicalJBODs': [{'id': 1,
                                                                  'name': '0000A66101, bay 3-rd0',
                                                                  'deviceSlot': 'Mezz 1',
                                                                  'numPhysicalDrives': 3,
                                                                  'driveMinSizeGB': 50000,
                                                                  'driveMaxSizeGB': 5000000,
                                                                  'driveTechnology': 'SasSsd'}],
                                             'controllers': [{'logicalDrives': [{'name': '0000A66101, bay 3-rd1',
                                                                                 'raidLevel': 'RAID1',
                                                                                 'bootable': False,
                                                                                 'numPhysicalDrives': 2,
                                                                                 'driveTechnology': 'SasSsd',
                                                                                 'sasLogicalJBODId': None}],
                                                              'deviceSlot': 'Embedded',
                                                              'mode': 'RAID',
                                                              'initialize': True},
                                                             {'logicalDrives': [{'name': None,
                                                                                 'raidLevel': 'RAID0',
                                                                                 'bootable': False,
                                                                                 'numPhysicalDrives': None,
                                                                                 'driveTechnology': None,
                                                                                 'sasLogicalJBODId': 1}],
                                                              'deviceSlot': 'Mezz 1',
                                                              'mode': 'RAID',
                                                              'initialize': False}]},
                             'sanStorage': {'manageSanStorage': False, 'volumeAttachments': []}
                             },
                            {
    'type': 'ServerProfileTemplateV2',
    'serverProfileDescription': '0000A66101, bay 4-withbothHBA',
    'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
    'enclosureGroupUri': 'EG:EG1',
    'serialNumberType': 'Virtual',
    'macType': 'Virtual',
    'wwnType': 'Virtual',
    'name': '0000A66101, bay 4-SPT-withbothHBA',
    'description': '0000A66101, bay 4-SPT-withbothHBA',
    'affinity': 'Bay',
    'connections': [{
        'id': 1,
        'name': '',
        'functionType': 'Ethernet',
        'portId': 'Mezz 3:1-a',
        'requestedMbps': '2500',
        'networkUri': 'ETH:net100',
        'requestedVFs': 'Auto'
    }
    ],
    'boot': {'manageBoot': False, 'order': []},
    'bootMode': {'manageMode': False},
    'bios': {'manageBios': False, 'overriddenSettings': []},
    'hideUnusedFlexNics': True,
    'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                          'deviceSlot': 'Mezz 1',
                                          'name': '0000A66101, bay 4-jbod1',
                                          'numPhysicalDrives': 3,
                                          'driveMinSizeGB': 50000,
                                          'driveMaxSizeGB': 5000000,
                                          'driveTechnology': 'SasSsd'}],
                     'controllers': [{'logicalDrives': [],
                                      'deviceSlot': 'Embedded',
                                      'mode': 'HBA',
                                      'initialize': True},
                                     {'logicalDrives': [],
                                      'deviceSlot': 'Mezz 1',
                                      'mode': 'HBA',
                                      'initialize': False}]
                     },
    'sanStorage': {'manageSanStorage': False, 'volumeAttachments': []}
},
]

server_profiles = [
    {'type': 'ServerProfileV6',
     'serverHardwareUri': 'SH:0000A66101, bay 4',
     'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
     'enclosureUri': 'ENC:0000A66101',
                     'enclosureGroupUri': 'EG:EG1',
                     'serialNumberType': 'Virtual',
                     'macType': 'Virtual',
                     'wwnType': 'Virtual',
                     'name': '0000A66101, bay 4',
                     'serverProfileTemplateUri': 'SPT:0000A66101, bay 4-SPT-withbothHBA',
                     'description': '',
                     'affinity': 'Bay',
                     'connections': [{
                                     'id': 1,
                                     'name': '',
                                     'functionType': 'Ethernet',
                                     'portId': 'Auto',
                                     'requestedMbps': '2500',
                                     'networkUri': 'ETH:net100',
                                     'requestedVFs': 'Auto'
                                     }
                                     ],
                     'boot': None,
                     'bootMode': {'manageMode': False},
                     'firmware': {'manageFirmware': False,
                                  'firmwareBaselineUri': '',
                                  'forceInstallFirmware': False,
                                  'firmwareInstallType': None
                                  },
                     'bios': {'manageBios': False,
                              'overriddenSettings': []
                              },
                     'hideUnusedFlexNics': True,
                     'iscsiInitiatorNameType': 'AutoGenerated',
                     'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                           'deviceSlot': 'Mezz 1',
                                                           'name': '0000A66101, bay 4-jbod1',
                                                           'numPhysicalDrives': 3,
                                                           'driveMinSizeGB': 50000,
                                                           'driveMaxSizeGB': 5000000,
                                                           'driveTechnology': 'SasSsd'}],
                                      'controllers': [{'logicalDrives': [],
                                                       'deviceSlot': 'Embedded',
                                                       'mode': 'HBA',
                                                       'initialize': True},
                                                      {'logicalDrives': [],
                                                       'deviceSlot': 'Mezz 1',
                                                       'mode': 'HBA',
                                                       'initialize': False}]
                                      },
                     'sanStorage': None
     },
    {'type': 'ServerProfileV6',
     'serverHardwareUri': 'SH:0000A66101, bay 5',
     'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
     'enclosureUri': 'ENC:0000A66101',
     'enclosureGroupUri': 'EG:EG1',
     'serialNumberType': 'Virtual',
     'macType': 'Virtual',
     'wwnType': 'Virtual',
     'name': '0000A66101, bay 5',
     'description': '',
     'affinity': 'Bay',
     'connections': [],
     'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                           'deviceSlot': 'Mezz 1',
                                           'name': '0000A66101, bay 5',
                                           'numPhysicalDrives': 1,
                                           'driveMinSizeGB': 50000,
                                           'driveMaxSizeGB': 5000000,
                                           'driveTechnology': 'SasSsd'},
                                          ]
                      },
     },
    {'type': 'ServerProfileV6',
     'serverHardwareUri': 'SH:0000A66101, bay 6',
     'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
     'enclosureUri': 'ENC:0000A66101',
     'enclosureGroupUri': 'EG:EG1',
     'serialNumberType': 'Virtual',
     'macType': 'Virtual',
     'wwnType': 'Virtual',
     'name': '0000A66101, bay 6',
     'description': '',
     'affinity': 'Bay',
     'connections': [],
     'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                           'deviceSlot': 'Mezz 1',
                                           'name': '0000A66101, bay 6',
                                           'numPhysicalDrives': 1,
                                           'driveMinSizeGB': 50000,
                                           'driveMaxSizeGB': 5000000,
                                           'driveTechnology': 'SasSsd'},
                                          ]
                      },
     },
    {'type': 'ServerProfileV6',
     'serverHardwareUri': 'SH:0000A66101, bay 11',
     'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
     'enclosureUri': 'ENC:0000A66101',
     'enclosureGroupUri': 'EG:EG1',
     'serialNumberType': 'Virtual',
     'macType': 'Virtual',
     'wwnType': 'Virtual',
     'name': '0000A66101, bay 11',
     'description': '',
     'affinity': 'Bay',
                     'connections': [],
                     'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                           'deviceSlot': 'Mezz 1',
                                                           'name': '0000A66101, bay 11',
                                                           'numPhysicalDrives': 1,
                                                           'driveMinSizeGB': 50000,
                                                           'driveMaxSizeGB': 5000000,
                                                           'driveTechnology': 'SasSsd'},
                                                          ]
                                      },
     },
    {'type': 'ServerProfileV6',
     'serverHardwareUri': 'SH:0000A66101, bay 3',
     'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
     'enclosureUri': 'ENC:0000A66101',
                     'enclosureGroupUri': 'EG:EG1',
                     'serialNumberType': 'Virtual',
                     'macType': 'Virtual',
                     'wwnType': 'Virtual',
                     'name': '0000A66101, bay 3',
                     'serverProfileTemplateUri': 'SPT:0000A66101, bay 3-SPT-withBothRaid',
                     'description': '',
                     'affinity': 'Bay',
                     'connections': [{
                         'id': 1,
                                     'name': '',
                                     'functionType': 'Ethernet',
                                     'portId': 'Auto',
                                     'requestedMbps': '2500',
                                     'networkUri': 'ETH:net100',
                                     'requestedVFs': 'Auto'
                                     }
                                     ],
                     'boot': {'manageBoot': True, 'order': ['HardDisk']},
                     'bootMode':{'manageMode': True,
                                 'mode': 'UEFI',
                                 'pxeBootPolicy': 'Auto'},
                     'firmware': {'manageFirmware': False,
                                  'firmwareBaselineUri': '',
                                  'forceInstallFirmware': False,
                                  'firmwareInstallType': None},
                     'bios': {'manageBios': False,
                              'overriddenSettings': []},
                     'hideUnusedFlexNics': True,
                     'iscsiInitiatorNameType': 'AutoGenerated',
                     'localStorage':{'sasLogicalJBODs': [{'id': 1,
                                                          'name': '0000A66101, bay 3-rd0',
                                                          'deviceSlot': 'Mezz 1',
                                                          'numPhysicalDrives': 3,
                                                          'driveMinSizeGB': 50000,
                                                          'driveMaxSizeGB': 5000000,
                                                          'driveTechnology': 'SasSsd'}],
                                     'controllers': [{'logicalDrives': [{'name': '0000A66101, bay 3-rd1',
                                                                         'raidLevel': 'RAID1',
                                                                         'bootable': False,
                                                                         'numPhysicalDrives': 2,
                                                                         'driveTechnology': 'SasSsd',
                                                                         'sasLogicalJBODId': None}],
                                                      'deviceSlot': 'Embedded',
                                                      'mode': 'RAID',
                                                      'initialize': True},
                                                     {'logicalDrives': [{'name': None,
                                                                         'raidLevel': 'RAID0',
                                                                         'bootable': False,
                                                                         'numPhysicalDrives': None,
                                                                         'driveTechnology': None,
                                                                         'sasLogicalJBODId': 1}],
                                                      'deviceSlot': 'Mezz 1',
                                                      'mode': 'RAID',
                                                      'initialize': False}]},
                     'sanStorage': None},

]
unassigned_server_profile = {'type': 'ServerProfileV6',
                             'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                             'enclosureGroupUri': 'EG:EG1',
                             'serialNumberType': 'Virtual',
                             'macType': 'Virtual',
                             'wwnType': 'Virtual',
                             'name': 'unassigned',
                             'description': 'unassigned',
                             'affinity': 'Bay',
                             'connections': [{'id': 1,
                                              'name': '',
                                              'functionType': 'Ethernet',
                                              'portId': 'Auto',
                                              'requestedMbps': '2500',
                                              'networkUri': 'ETH:net100',
                                              'requestedVFs': 'Auto'}],
                             'boot': {'manageBoot': True, 'order': ['HardDisk']},
                             'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                             'bios': {'manageBios': False, 'overriddenSettings': []},
                             'hideUnusedFlexNics': True,
                             'iscsiInitiatorNameType': 'AutoGenerated',
                             'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                                   'deviceSlot': 'Mezz 1',
                                                                   'name': 'unassigned1',
                                                                   'numPhysicalDrives': 1,
                                                                   'driveMinSizeGB': 50000,
                                                                   'driveMaxSizeGB': 5000000,
                                                                   'driveTechnology': 'SasSsd'},
                                                                  {'id': 2,
                                                                   'deviceSlot': 'Mezz 1',
                                                                   'name': 'unassigned2',
                                                                   'numPhysicalDrives': 1,
                                                                   'driveMinSizeGB': 50000,
                                                                   'driveMaxSizeGB': 5000000,
                                                                   'driveTechnology': 'SasSsd'}]},
                             'sanStorage': None},

move_server_profile = {'type': 'ServerProfileV6',
                       'serverHardwareUri': 'SH:0000A66101, bay 10',
                       'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                       'enclosureUri': 'ENC:0000A66101',
                       'enclosureGroupUri': 'EG:EG1',
                       'serialNumberType': 'Virtual',
                       'macType': 'Virtual',
                       'wwnType': 'Virtual',
                       'name': '0000A66101, bay 5',
                       'hideUnusedFlexNics': True,
                       'description': 'moved profile from Bay 5 to Bay10',
                       'affinity': 'Bay',
                       'bootMode': {'mode': None, 'manageMode': False, 'pxeBootPolicy': None},
                       'boot': {'manageBoot': False, 'order': []},
                       'bios': {'overriddenSettings': [], 'manageBios': False},
                       'category': 'server-profiles',
                       'connections': [],
                       'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                             'deviceSlot': 'Mezz 1',
                                                             'name': '0000A66101, bay 5',
                                                             'sasLogicalJBODUri': 'SASLJBOD:0000A66101, bay 5',
                                                             'numPhysicalDrives': 1,
                                                             'driveMinSizeGB': 50000,
                                                             'driveMaxSizeGB': 5000000,
                                                             'driveTechnology': 'SasSsd'}],
                                        'controllers': []},
                       'sanStorage': None}

move_server_profile_to_enc2 = {'type': 'ServerProfileV6',
                               'serverHardwareUri': 'SH:0000A66102, bay 11',
                               'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                               'enclosureUri': 'ENC:0000A66102',
                               'enclosureGroupUri': 'EG:EG1',
                               'serialNumberType': 'Virtual',
                               'macType': 'Virtual',
                               'wwnType': 'Virtual',
                               'name': '0000A66101, bay 11',
                               'hideUnusedFlexNics': True,
                               'description': 'moved profile from Enc1,Bay 11 to Enc2, Bay11',
                               'affinity': 'Bay',
                               'bootMode': {'mode': None, 'manageMode': False, 'pxeBootPolicy': None},
                               'boot': {'manageBoot': False, 'order': []},
                               'bios': {'overriddenSettings': [], 'manageBios': False},
                               'category': 'server-profiles',
                               'connections': [],
                               'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                                     'deviceSlot': 'Mezz 1',
                                                                     'name': '0000A66101, bay 11',
                                                                     'sasLogicalJBODUri': 'SASLJBOD:0000A66101, bay 11',
                                                                     'numPhysicalDrives': 1,
                                                                     'driveMinSizeGB': 50000,
                                                                     'driveMaxSizeGB': 5000000,
                                                                     'driveTechnology': 'SasSsd'}],
                                                'controllers': []},
                               'sanStorage': None}

edit_profile_add_jbod = {'type': 'ServerProfileV6',
                         'serverHardwareUri': 'SH:0000A66101, bay 6',
                         'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                         'enclosureUri': 'ENC:0000A66101',
                         'enclosureGroupUri': 'EG:EG1',
                         'serialNumberType': 'Virtual',
                         'macType': 'Virtual',
                         'wwnType': 'Virtual',
                         'name': '0000A66101, bay 6',
                         'hideUnusedFlexNics': True,
                         'description': 'added one more jbod',
                         'affinity': 'Bay',
                         'bootMode': {'mode': None, 'manageMode': False, 'pxeBootPolicy': None},
                         'boot': {'manageBoot': False, 'order': []},
                         'bios': {'overriddenSettings': [], 'manageBios': False},
                         'category': 'server-profiles',
                         'connections': [],
                         'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                               'deviceSlot': 'Mezz 1',
                                                               'name': '0000A66101, bay 6',
                                                               'sasLogicalJBODUri': 'SASLJBOD:0000A66101, bay 6',
                                                               'numPhysicalDrives': 1,
                                                               'driveMinSizeGB': 50000,
                                                               'driveMaxSizeGB': 5000000,
                                                               'driveTechnology': 'SasSsd'},
                                                              {'id': 2,
                                                               'deviceSlot': 'Mezz 1',
                                                               'name': '0000A66101, bay 6-jbod2',
                                                               'numPhysicalDrives': 3,
                                                               'driveMinSizeGB': 50000,
                                                               'driveMaxSizeGB': 5000000,
                                                               'driveTechnology': 'SasSsd'}
                                                              ]
                                          },
                         }
unassign_existing_profile = {'type': 'ServerProfileV6',
                             #                     'serverHardwareUri': None,
                             'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                             'enclosureGroupUri': 'EG:EG1',
                             #                     'enclosureUri': None,
                             #                     'enclosureBay': None,
                             'serialNumberType': 'Virtual',
                             'macType': 'Virtual',
                             'wwnType': 'Virtual',
                             'name': '0000A66101, bay 4',
                             'serverProfileTemplateUri': 'SPT:0000A66101, bay 4-SPT-withbothHBA',
                             'description': '',
                             'affinity': 'Bay',
                             'connections': [{
                                     'id': 1,
                                     'name': '',
                                     'functionType': 'Ethernet',
                                     'portId': 'Auto',
                                     'requestedMbps': '2500',
                                     'networkUri': 'ETH:net100',
                                     'requestedVFs': 'Auto'
                             }
                             ],
                             'boot': None,
                             'bootMode': {'manageMode': False},
                             'bios': {'manageBios': False, 'overriddenSettings': []},
                             'hideUnusedFlexNics': True,
                             'iscsiInitiatorNameType': 'AutoGenerated',
                             'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                                   'deviceSlot': 'Mezz 1',
                                                                   'name': '0000A66101, bay 4-jbod1',
                                                                   'sasLogicalJBODUri': 'SASLJBOD:0000A66101, bay 4-jbod1',
                                                                   'numPhysicalDrives': 3,
                                                                   'driveMinSizeGB': 50000,
                                                                   'driveMaxSizeGB': 5000000,
                                                                   'driveTechnology': 'SasSsd'}],
                                              'controllers': [{'logicalDrives': [],
                                                               'deviceSlot': 'Embedded',
                                                               'mode': 'HBA',
                                                               'initialize': True},
                                                              {'logicalDrives': [],
                                                               'deviceSlot': 'Mezz 1',
                                                               'mode': 'HBA',
                                                               'initialize': False}]
                                              },
                             'sanStorage': None
                             }

# Server profile with drives = 256 test case 10
server_profile_invalid_drives = {'type': 'ServerProfileV6',
                                 'serverHardwareUri': 'SH:0000A66102, bay 3',
                                 'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                                 'enclosureUri': 'ENC:0000A66102',
                                 'enclosureGroupUri': 'EG:EG1',
                                 'serialNumberType': 'Virtual',
                                 'macType': 'Virtual',
                                 'wwnType': 'Virtual',
                                 'name': '0000A66102, bay 3',
                                 'description': '',
                                 'affinity': 'Bay',
                                 'connections': [],
                                 'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                                       'deviceSlot': 'Mezz 1',
                                                                       'name': '0000A66102, bay 3',
                                                                       'numPhysicalDrives': 256,
                                                                       'driveMinSizeGB': 50000,
                                                                       'driveMaxSizeGB': 5000000,
                                                                       'driveTechnology': 'SasSsd'},
                                                                      ]
                                                  },

                                 }
# Logical JBOD min size > max size test case 11
server_profile_min_max_mismatch = {'type': 'ServerProfileV6',
                                   'serverHardwareUri': 'SH:0000A66102, bay 4',
                                   'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                                   'enclosureUri': 'ENC:0000A66102',
                                   'enclosureGroupUri': 'EG:EG1',
                                   'serialNumberType': 'Virtual',
                                   'macType': 'Virtual',
                                   'wwnType': 'Virtual',
                                   'name': '0000A66102, bay 4',
                                   'description': '',
                                   'affinity': 'Bay',
                                   'connections': [],
                                   'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                                         'deviceSlot': 'Mezz 1',
                                                                         'name': '0000A66102, bay 4',
                                                                         'numPhysicalDrives': 3,
                                                                         'driveMinSizeGB': 500000,
                                                                         'driveMaxSizeGB': 400000,
                                                                         'driveTechnology': 'SasSsd'},
                                                                        ]
                                                    },

                                   }
# Logical JBOD wrong Drive Techonology test case 12
server_profile_wrong_drive_type = {'type': 'ServerProfileV6',
                                   'serverHardwareUri': 'SH:0000A66102, bay 5',
                                   'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                                   'enclosureUri': 'ENC:0000A66102',
                                   'enclosureGroupUri': 'EG:EG1',
                                   'serialNumberType': 'Virtual',
                                   'macType': 'Virtual',
                                   'wwnType': 'Virtual',
                                   'name': '0000A66102, bay 5',
                                   'description': '',
                                   'affinity': 'Bay',
                                   'connections': [],
                                   'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                                         'deviceSlot': 'Mezz 1',
                                                                         'name': '0000A66102, bay 5',
                                                                         'numPhysicalDrives': 3,
                                                                         'driveMinSizeGB': 50000,
                                                                         'driveMaxSizeGB': 5000000,
                                                                         'driveTechnology': 'SasHdd'},
                                                                        ]
                                                    },

                                   }
# Create server profile - set more than one Boot local drive test case 13
server_profile_more_boot_drives = {'type': 'ServerProfileV6',
                                   'serverHardwareUri': 'SH:0000A66102, bay 6',
                                   'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                                   'enclosureUri': 'ENC:0000A66102',
                                   'enclosureGroupUri': 'EG:EG1',
                                   'serialNumberType': 'Virtual',
                                   'macType': 'Virtual',
                                   'wwnType': 'Virtual',
                                   'name': '0000A66102, bay 6',
                                   'description': '',
                                   'affinity': 'Bay',
                                   'bootMode': {'manageMode': True, 'mode': 'BIOS'},
                                   'boot': {'manageBoot': True, 'order': ['CD', 'USB', 'PXE', 'HardDisk']},
                                   'connections': [],
                                   'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                                         'name': '0000A66102, bay 6-rd0',
                                                                         'deviceSlot': 'Mezz 1',
                                                                         'numPhysicalDrives': 3,
                                                                         'driveMinSizeGB': 50000,
                                                                         'driveMaxSizeGB': 5000000,
                                                                         'driveTechnology': 'SasSsd'}],
                                                    'controllers': [{'logicalDrives': [{'name': '0000A66102, bay 6-rd1',
                                                                                        'raidLevel': 'RAID1',
                                                                                        'bootable': True,
                                                                                        'numPhysicalDrives': 2,
                                                                                        'driveTechnology': 'SasSsd',
                                                                                        'sasLogicalJBODId': None}],
                                                                     'deviceSlot': 'Embedded',
                                                                     'mode': 'RAID',
                                                                     'initialize': True},
                                                                    {'logicalDrives': [{'name': None,
                                                                                        'raidLevel': 'RAID0',
                                                                                        'bootable': True,
                                                                                        'numPhysicalDrives': None,
                                                                                        'driveTechnology': None,
                                                                                        'sasLogicalJBODId': 1}],
                                                                     'deviceSlot': 'Mezz 1',
                                                                     'mode': 'RAID',
                                                                     'initialize': False}]},

                                   }

# Create server profile - LD with both reinitialize and import config - test case 15
server_profile_ld_with_both = {'type': 'ServerProfileV6',
                               'serverHardwareUri': 'SH:0000A66102, bay 9',
                               'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                               'enclosureUri': 'ENC:0000A66102',
                               'enclosureGroupUri': 'EG:EG1',
                               'serialNumberType': 'Virtual',
                               'macType': 'Virtual',
                               'wwnType': 'Virtual',
                               'name': '0000A66102, bay 9',
                               'description': '',
                               'affinity': 'Bay',
                               'bootMode': {'manageMode': True, 'mode': 'BIOS'},
                               'boot': {'manageBoot': True, 'order': ['CD', 'USB', 'PXE', 'HardDisk']},
                               'connections': [],
                               'localStorage': {
                                   'controllers': [{'logicalDrives': [{'name': '0000A66102, bay 9-rd1',
                                                                       'raidLevel': 'RAID1',
                                                                       'bootable': True,
                                                                       'numPhysicalDrives': 2,
                                                                       'driveTechnology': 'SasSsd',
                                                                       'sasLogicalJBODId': None}],
                                                    'deviceSlot': 'Embedded',
                                                    'mode': 'RAID',
                                                    'initialize': True,
                                                    'importConfiguration': True},
                                                   ]
                               },

                               }
# Create server profile with wrong RAID type -test case 16
server_profile_wrong_raid = {'type': 'ServerProfileV6',
                             'serverHardwareUri': 'SH:0000A66102, bay 10',
                             'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1',
                             'enclosureUri': 'ENC:0000A66102',
                             'enclosureGroupUri': 'EG:EG1',
                             'serialNumberType': 'Virtual',
                             'macType': 'Virtual',
                             'wwnType': 'Virtual',
                             'name': '0000A66102, bay 10',
                             'description': '',
                             'affinity': 'Bay',
                             'bootMode': {'manageMode': True, 'mode': 'BIOS'},
                             'boot': {'manageBoot': True, 'order': ['CD', 'USB', 'PXE', 'HardDisk']},
                             'connections': [],
                             'localStorage': {
                                 'controllers': [{'logicalDrives': [{'name': '0000A66102, bay 10-rd1',
                                                                     'raidLevel': 'RAID22',
                                                                     'bootable': True,
                                                                     'numPhysicalDrives': 2,
                                                                     'driveTechnology': 'SasSsd',
                                                                     'sasLogicalJBODId': None}],
                                                  'deviceSlot': 'Embedded',
                                                  'mode': 'RAID',
                                                  'initialize': True},
                                                 ]
                             },
                             }

negative_server_profile_tasks = [
    {'keyword': 'Add Server Profile',
     'argument': server_profile_invalid_drives.copy(),
     'taskState': 'Error',
     'timeout': '120',
     'errorMessage': 'DFRM_INSUFFICIENT_DRIVE_COUNT'},
    {'keyword': 'Add Server Profile',
     'argument': server_profile_min_max_mismatch.copy(),
     'taskState': 'Error',
     'timeout': '120',
     'errorMessage': 'DirectFabricJbodInvalidNumMinSizeGb'},
    {'keyword': 'Add Server Profile',
     'argument': server_profile_wrong_drive_type.copy(),
     'taskState': 'Error',
     'timeout': '120',
     'errorMessage': 'DFRM_INSUFFICIENT_DRIVE_COUNT'},
    {'keyword': 'Add Server Profile',
     'argument': server_profile_ld_with_both.copy(),
     'taskState': 'Error',
     'timeout': '120',
     'errorMessage': 'DFRM_INSUFFICIENT_DRIVE_COUNT'},
    {'keyword': 'Add Server Profile',
     'argument': server_profile_wrong_raid.copy(),
     'taskState': 'Error',
     'timeout': '6000',
     'errorMessage': 'UNSUPPORTED_RAID_LEVEL'},
    {'keyword': 'Add Server Profile',
     'argument': server_profile_more_boot_drives.copy(),
     'taskState': 'Error',
     'timeout': '6000',
     'errorMessage': 'DFRM_INSUFFICIENT_DRIVE_COUNT'},
]

sas_logical_jbods = [
    {'type': 'sas-logical-jbod',
     'name': '0000A66101, bay 3-rd0',
     'clearMetaData': False,
     #                     'logicalDriveBayUris':,
     'minSizeGB': 50000,
     'maxSizeGB': 5000000,
     'numPhysicalDrives': 3,
     'driveTechnology': None,
     'sasLogicalInterconnectUri': 'SASLI:LE1-SASLIG1-1',
     'logicalDriveBays': None,
     'stateReason': None,
     'refreshState': 'NotRefreshing',
     'state': 'Configured',
     'description': None,
     'status': 'OK',
     'category': 'sas-logical-jbods',
     'uri': 'SASLJBOD:0000A66101, bay 3-rd0',
     },
    {'type': 'sas-logical-jbod',
     'name': '0000A66101, bay 4-jbod1',
     'clearMetaData': False,
     #                     'logicalDriveBayUris':,
     'minSizeGB': 50000,
     'maxSizeGB': 5000000,
     'numPhysicalDrives': 3,
     'driveTechnology': None,
     'sasLogicalInterconnectUri': 'SASLI:LE1-SASLIG1-1',
     'logicalDriveBays': None,
     'stateReason': None,
     'refreshState': 'NotRefreshing',
     'state': 'Configured',
     'description': None,
     'status': 'OK',
     'category': 'sas-logical-jbods',
     'uri': 'SASLJBOD:0000A66101, bay 4-jbod1',
     },
    {'type': 'sas-logical-jbod',
     'name': '0000A66101, bay 5',
     'clearMetaData': False,
     #                     'logicalDriveBayUris':,
     'minSizeGB': 50000,
     'maxSizeGB': 5000000,
     'numPhysicalDrives': 1,
     'driveTechnology': None,
     'sasLogicalInterconnectUri': 'SASLI:LE1-SASLIG1-1',
     'logicalDriveBays': None,
     'stateReason': None,
     'refreshState': 'NotRefreshing',
     'state': 'Configured',
     'description': None,
     'status': 'OK',
     'category': 'sas-logical-jbods',
     'uri': 'SASLJBOD:0000A66101, bay 5',
     },
    {'type': 'sas-logical-jbod',
     'clearMetaData': False,
     #                      'logicalDriveBayUris': [1]
     'numPhysicalDrives': 1,
     'driveTechnology': None,
     'sasLogicalInterconnectUri': 'SASLI:LE1-SASLIG1-1',
     'minSizeGB': 50000,
     'maxSizeGB': 5000000,
     'logicalDriveBays': None,
     'stateReason': None,
     'refreshState': 'NotRefreshing',
     'description': None,
     'status': 'OK',
     'name': '0000A66101, bay 6',
     'state': 'Configured',
     'category': 'sas-logical-jbods',
     'uri': 'SASLJBOD:0000A66101, bay 6'
     },
]

sas_logical_jbod_attachments = [{'type': 'sas-logical-jbod-attachment',
                                 'serverProfileUri': 'SP:0000A66101, bay 3',
                                 'serverHardwareUri': 'SH:0000A66101, bay 3',
                                 'sasLogicalJBODUri': 'SLJBOD:0000A66101, bay 3-rd0',
                                 'mezzSlotNumber': 1,
                                 'name': 'LE1-SASLIG1-1-SLJA-1',
                                 'state': 'Deployed',
                                 'description': None,
                                 'status': None,
                                 'category': 'sas-logical-jbod-attachments',
                                 #                                'uri': '/rest/sas-logical-jbod-attachments/fc0678d6-b30c-415c-8b5c-ba307b8ed018'
                                 },
                                {'type': 'sas-logical-jbod-attachment',
                                 'serverProfileUri': 'SP:0000A66101, bay 4',
                                 'serverHardwareUri': 'SH:0000A66101, bay 4',
                                 'sasLogicalJBODUri': 'SLJBOD:0000A66101, bay 4-jbod1',
                                 'mezzSlotNumber': 1,
                                 'name': 'LE1-SASLIG1-1-SLJA-2',
                                 'state': 'Deployed',
                                 'description': None,
                                 'status': None,
                                 'category': 'sas-logical-jbod-attachments',
                                 #                                'uri': '/rest/sas-logical-jbod-attachments/fc0678d6-b30c-415c-8b5c-ba307b8ed018'
                                 },
                                {'type': 'sas-logical-jbod-attachment',
                                 'serverProfileUri': 'SP:0000A66101, bay 5',
                                 'serverHardwareUri': 'SH:0000A66101, bay 5',
                                 'sasLogicalJBODUri': 'SLJBOD:0000A66101, bay 5',
                                 'mezzSlotNumber': 1,
                                 'name': 'LE1-SASLIG1-1-SLJA-3',
                                 'state': 'Deployed',
                                 'description': None,
                                 'status': None,
                                 'category': 'sas-logical-jbod-attachments',
                                 #                                'uri': '/rest/sas-logical-jbod-attachments/fc0678d6-b30c-415c-8b5c-ba307b8ed018'
                                 },
                                {'type': 'sas-logical-jbod-attachment',
                                 'serverProfileUri': 'SP:0000A66101, bay 6',
                                 'serverHardwareUri': 'SH:0000A66101, bay 6',
                                 'sasLogicalJBODUri': 'SLJBOD:0000A66101, bay 6',
                                 'mezzSlotNumber': 1,
                                 'name': 'LE1-SASLIG1-1-SLJA-4',
                                 'state': 'Deployed',
                                 'description': None,
                                 'status': None,
                                 'category': 'sas-logical-jbod-attachments',
                                 #                                'uri': '/rest/sas-logical-jbod-attachments/fc0678d6-b30c-415c-8b5c-ba307b8ed018'
                                 },
                                ]
