
admin_credentials = {'userName': 'Administrator', 'password': 'Cosmos123'}

ilo_credentials = {'userName': 'Administrator', 'password': 'Cosmos123'}

server_profile_E1bay2 = {'name': 'E1Bay2', 'type': 'ServerProfileV6', 'serverHardwareUri': 'SH:CN751302CG, bay 2', 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                         'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:net1038-a', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''}],
                         'boot': {'manageBoot': True, 'order': ['HardDisk']},
                         'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                         'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                         'bios': {'manageBios': False, 'overriddenSettings': []},
                         'hideUnusedFlexNics': True, 'iscsiInitiatorName': '', 'osDeploymentSettings': None,
                         'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': True, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': None}]}]},
                         'sanStorage': None}

server_profile_E1bay4 = {'name': 'E1Bay4', 'type': 'ServerProfileV6', 'serverHardwareUri': 'SH:CN751302CG, bay 4', 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                         'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:net1038-a', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''}],
                         'boot': {'manageBoot': True, 'order': ['HardDisk']},
                         'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                         'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                         'bios': {'manageBios': False, 'overriddenSettings': []},
                         'hideUnusedFlexNics': True, 'iscsiInitiatorName': '', 'osDeploymentSettings': None,
                         'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': True, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': None}]}]},
                         'sanStorage': None}

server_profile_E1bay5 = {'name': 'E1Bay5', 'type': 'ServerProfileV6', 'serverHardwareUri': 'SH:CN751302CG, bay 5', 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                         'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:net1038-a', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''}],
                         'boot': {'manageBoot': True, 'order': ['HardDisk']},
                         'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                         'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                         'bios': {'manageBios': False, 'overriddenSettings': []},
                         'hideUnusedFlexNics': True, 'iscsiInitiatorName': '', 'osDeploymentSettings': None,
                         'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': True, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': None}]}]},
                         'sanStorage': None}

expected_server_profile_E1bay2 = {'name': 'E1Bay2', 'type': 'ServerProfileV6', 'uri': 'SP:E1Bay2', 'serverHardwareUri': 'SH:CN751302CG, bay 2', 'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1', 'enclosureGroupUri': 'EG:CHO-EG-Multi', 'enclosureUri': 'ENC:CN751302CG', 'enclosureBay': 2, 'associatedServer': None, 'hideUnusedFlexNics': True, 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'category': 'server-profiles', 'affinity': 'Bay', 'status': 'OK', 'state': 'Normal', 'inProgress': False,
                                  'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'deploymentStatus': 'Deployed', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'maximumMbps': 10000, 'networkUri': 'ETH:net1038-a', 'allocatedMbps': 2500, 'requestedVFs': 'Auto', 'interconnectUri': 'IC:CN751302CG, interconnect 3', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'wwpn': None, 'wwnn': None,
                                                   'boot': {'priority': 'Primary', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}}],
                                  'boot': {'manageBoot': True, 'order': ['HardDisk']},
                                  'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                                  'firmware': {'manageFirmware': False, 'firmwareBaselineUri': None, 'forceInstallFirmware': False, 'firmwareInstallType': None},
                                  'bios': {'manageBios': False, 'overriddenSettings': []},
                                  'osDeploymentSettings': None,
                                  'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': False, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': 1}]}]},
                                  'sanStorage': {'volumeAttachments': [], 'manageSanStorage': False}
                                  }

expected_server_profile_E1bay4 = {'name': 'E1Bay4', 'type': 'ServerProfileV6', 'uri': 'SP:E1Bay4', 'serverHardwareUri': 'SH:CN751302CG, bay 4', 'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1', 'enclosureGroupUri': 'EG:CHO-EG-Multi', 'enclosureUri': 'ENC:CN751302CG', 'enclosureBay': 4, 'associatedServer': None, 'hideUnusedFlexNics': True, 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'category': 'server-profiles', 'affinity': 'Bay', 'status': 'OK', 'state': 'Normal', 'inProgress': False,
                                  'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'deploymentStatus': 'Deployed', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'maximumMbps': 10000, 'networkUri': 'ETH:net1038-a', 'allocatedMbps': 2500, 'requestedVFs': 'Auto', 'interconnectUri': 'IC:CN751302CG, interconnect 3', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'wwpn': None, 'wwnn': None,
                                                   'boot': {'priority': 'Primary', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}}],
                                  'boot': {'manageBoot': True, 'order': ['HardDisk']},
                                  'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                                  'firmware': {'manageFirmware': False, 'firmwareBaselineUri': None, 'forceInstallFirmware': False, 'firmwareInstallType': None},
                                  'bios': {'manageBios': False, 'overriddenSettings': []},
                                  'osDeploymentSettings': None,
                                  'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': False, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': 1}]}]},
                                  'sanStorage': {'volumeAttachments': [], 'manageSanStorage': False}
                                  }

expected_server_profile_E1bay5 = {'name': 'E1Bay5', 'type': 'ServerProfileV6', 'uri': 'SP:E1Bay5', 'serverHardwareUri': 'SH:CN751302CG, bay 5', 'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1', 'enclosureGroupUri': 'EG:CHO-EG-Multi', 'enclosureUri': 'ENC:CN751302CG', 'enclosureBay': 5, 'associatedServer': None, 'hideUnusedFlexNics': True, 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'category': 'server-profiles', 'affinity': 'Bay', 'status': 'OK', 'state': 'Normal', 'inProgress': False,
                                  'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'deploymentStatus': 'Deployed', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'maximumMbps': 10000, 'networkUri': 'ETH:net1038-a', 'allocatedMbps': 2500, 'requestedVFs': 'Auto', 'interconnectUri': 'IC:CN751302CG, interconnect 3', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'wwpn': None, 'wwnn': None,
                                                   'boot': {'priority': 'Primary', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}}],
                                  'boot': {'manageBoot': True, 'order': ['HardDisk']},
                                  'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                                  'firmware': {'manageFirmware': False, 'firmwareBaselineUri': None, 'forceInstallFirmware': False, 'firmwareInstallType': None},
                                  'bios': {'manageBios': False, 'overriddenSettings': []},
                                  'osDeploymentSettings': None,
                                  'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': False, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': 1}]}]},
                                  'sanStorage': {'volumeAttachments': [], 'manageSanStorage': False}
                                  }

edit_server_profile_E1bay2 = {'name': 'E1Bay2', 'type': 'ServerProfileV6', 'serverHardwareUri': 'SH:CN751302CG, bay 2', 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': 'Updated Profile', 'affinity': 'Bay',
                              'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'networkUri': 'NS:netset-1a', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                              {'id': 2, 'name': 'FCOE1', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:1-b', 'requestedMbps': '2500', 'networkUri': 'FCOE:FCOE-1084', 'boot': {'priority': 'NotBootable'}},
                                              {'id': 3, 'name': 'FCOE2', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:2-b', 'requestedMbps': '2500', 'networkUri': 'FCOE:FCOE-1085', 'boot': {'priority': 'NotBootable'}}],
                              'boot': {'manageBoot': True, 'order': ['HardDisk']},
                              'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                              'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                              'bios': {'manageBios': False, 'overriddenSettings': []},
                              'hideUnusedFlexNics': True, 'iscsiInitiatorName': '', 'osDeploymentSettings': None,
                              'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': False, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': 1}]}]},
                              'sanStorage': {'manageSanStorage': True, 'hostOSType': 'Windows 2012 / WS2012 R2',
                                             'volumeAttachments': [{'id': 1, 'volumeUri': None, 'volumeName': 'E1Bay2Volume1', 'volumeProvisionType': 'Thin', 'lunType': 'Manual', 'lun': 1, 'volumeProvisionedCapacityBytes': '53687091200', 'permanent': False, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'volumeShareable': False, 'storagePaths': [{'connectionId': 2, 'isEnabled': True}]},
                                                                   {'id': 2, 'volumeUri': None, 'volumeName': 'E1Bay2Volume2', 'volumeProvisionType': 'Thin', 'lunType': 'Manual', 'lun': 2, 'volumeProvisionedCapacityBytes': '53687091200', 'permanent': False, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'volumeShareable': False, 'storagePaths': [{'connectionId': 3, 'isEnabled': True}]}]
                                             }
                              }

edit_server_profile_E1bay4 = {'name': 'E1Bay4', 'type': 'ServerProfileV6', 'serverHardwareUri': 'SH:CN751302CG, bay 4', 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': 'Updated Profile', 'affinity': 'Bay',
                              'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'networkUri': 'NS:netset-1a', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                              {'id': 2, 'name': 'FCOE1', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:1-b', 'requestedMbps': '2500', 'networkUri': 'FCOE:FCOE-1084', 'boot': {'priority': 'NotBootable'}},
                                              {'id': 3, 'name': 'FCOE2', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:2-b', 'requestedMbps': '2500', 'networkUri': 'FCOE:FCOE-1085', 'boot': {'priority': 'NotBootable'}}],
                              'boot': {'manageBoot': True, 'order': ['HardDisk']},
                              'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                              'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                              'bios': {'manageBios': False, 'overriddenSettings': []},
                              'hideUnusedFlexNics': True, 'iscsiInitiatorName': '', 'osDeploymentSettings': None,
                              'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': False, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': 1}]}]},
                              'sanStorage': {'manageSanStorage': True, 'hostOSType': 'Windows 2012 / WS2012 R2',
                                             'volumeAttachments': [{'id': 1, 'volumeUri': None, 'volumeName': 'E1Bay4Volume1', 'volumeProvisionType': 'Thin', 'lunType': 'Manual', 'lun': 1, 'volumeProvisionedCapacityBytes': '53687091200', 'permanent': False, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'volumeShareable': False, 'storagePaths': [{'connectionId': 2, 'isEnabled': True}]},
                                                                   {'id': 2, 'volumeUri': None, 'volumeName': 'E1Bay4Volume2', 'volumeProvisionType': 'Thin', 'lunType': 'Manual', 'lun': 2, 'volumeProvisionedCapacityBytes': '53687091200', 'permanent': False, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'volumeShareable': False, 'storagePaths': [{'connectionId': 3, 'isEnabled': True}]}]
                                             }
                              }

edit_server_profile_E1bay5 = {'name': 'E1Bay5', 'type': 'ServerProfileV6', 'serverHardwareUri': 'SH:CN751302CG, bay 5', 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': 'Updated Profile', 'affinity': 'Bay',
                              'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'networkUri': 'NS:netset-1a', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                              {'id': 2, 'name': 'FCOE1', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:1-b', 'requestedMbps': '2500', 'networkUri': 'FCOE:FCOE-1084', 'boot': {'priority': 'NotBootable'}},
                                              {'id': 3, 'name': 'FCOE2', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:2-b', 'requestedMbps': '2500', 'networkUri': 'FCOE:FCOE-1085', 'boot': {'priority': 'NotBootable'}}],
                              'boot': {'manageBoot': True, 'order': ['HardDisk']},
                              'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                              'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                              'bios': {'manageBios': False, 'overriddenSettings': []},
                              'hideUnusedFlexNics': True, 'iscsiInitiatorName': '', 'osDeploymentSettings': None,
                              'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': False, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': 1}]}]},
                              'sanStorage': {'manageSanStorage': True, 'hostOSType': 'Windows 2012 / WS2012 R2',
                                             'volumeAttachments': [{'id': 1, 'volumeUri': None, 'volumeName': 'E1Bay5Volume1', 'volumeProvisionType': 'Thin', 'lunType': 'Manual', 'lun': 1, 'volumeProvisionedCapacityBytes': '53687091200', 'permanent': False, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'volumeShareable': False, 'storagePaths': [{'connectionId': 2, 'isEnabled': True}]},
                                                                   {'id': 2, 'volumeUri': None, 'volumeName': 'E1Bay5Volume2', 'volumeProvisionType': 'Thin', 'lunType': 'Manual', 'lun': 2, 'volumeProvisionedCapacityBytes': '53687091200', 'permanent': False, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'volumeShareable': False, 'storagePaths': [{'connectionId': 3, 'isEnabled': True}]}]
                                             }
                              }

expected_edit_server_profile_E1bay2 = {'name': 'E1Bay2', 'type': 'ServerProfileV6', 'uri': 'SP:E1Bay2', 'serverHardwareUri': 'SH:CN751302CG, bay 2', 'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1', 'enclosureGroupUri': 'EG:CHO-EG-Multi', 'enclosureUri': 'ENC:CN751302CG', 'enclosureBay': 2, 'associatedServer': None, 'hideUnusedFlexNics': True, 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': 'Updated Profile', 'category': 'server-profiles', 'affinity': 'Bay', 'status': 'OK', 'state': 'Normal', 'inProgress': False,
                                       'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'maximumMbps': 10000, 'allocatedMbps': 2500, 'requestedVFs': 'Auto', 'networkUri': 'NS:netset-1a', 'interconnectUri': 'IC:CN751302CG, interconnect 3', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'wwpn': None, 'wwnn': None, 'deploymentStatus': 'Deployed',
                                                        'boot': {'priority': 'NotBootable', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}},
                                                       {'id': 2, 'name': 'FCOE1', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:1-b', 'requestedMbps': '2500', 'maximumMbps': 20000, 'allocatedMbps': 2500, 'requestedVFs': None, 'allocatedVFs': None, 'networkUri': 'FCOE:FCOE-1084', 'interconnectUri': 'IC:CN751302CG, interconnect 3', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'deploymentStatus': 'Deployed',
                                                        'boot': {'priority': 'NotBootable', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}},
                                                       {'id': 3, 'name': 'FCOE2', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:2-b', 'requestedMbps': '2500', 'maximumMbps': 20000, 'allocatedMbps': 2500, 'requestedVFs': None, 'allocatedVFs': None, 'networkUri': 'FCOE:FCOE-1085', 'interconnectUri': 'IC:CN750163KV, interconnect 6', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'deploymentStatus': 'Deployed',
                                                        'boot': {'priority': 'NotBootable', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}}],
                                       'boot': {'manageBoot': True, 'order': ['HardDisk']},
                                       'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                                       'firmware': {'manageFirmware': False, 'firmwareBaselineUri': None, 'forceInstallFirmware': False, 'firmwareInstallType': None},
                                       'bios': {'manageBios': False, 'overriddenSettings': []},
                                       'osDeploymentSettings': None,
                                       'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': False, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': 1}]}]},
                                       'sanStorage': {'manageSanStorage': True, 'hostOSType': 'Windows 2012 / WS2012 R2',
                                                      'volumeAttachments': [{'id': 1, 'volumeUri': 'SVOL:E1Bay2Volume1', 'lunType': 'Manual', 'lun': 1, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'status': 'OK', 'state': 'Attached',
                                                                             'storagePaths': [{'connectionId': 2, 'isEnabled': True, 'status': 'OK', 'storageTargetType': 'Auto', 'storageTargets': ['20:21:00:02:AC:00:C3:12', '21:21:00:02:AC:00:C3:12']}]},
                                                                            {'id': 2, 'volumeUri': 'SVOL:E1Bay2Volume2', 'lunType': 'Manual', 'lun': 2, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'status': 'OK', 'state': 'Attached',
                                                                             'storagePaths': [{'connectionId': 3, 'isEnabled': True, 'status': 'OK', 'storageTargetType': 'Auto', 'storageTargets': ['20:22:00:02:AC:00:C3:12', '21:22:00:02:AC:00:C3:12']}]}]
                                                      }
                                       }

expected_edit_server_profile_E1bay4 = {'name': 'E1Bay4', 'type': 'ServerProfileV6', 'uri': 'SP:E1Bay4', 'serverHardwareUri': 'SH:CN751302CG, bay 4', 'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1', 'enclosureGroupUri': 'EG:CHO-EG-Multi', 'enclosureUri': 'ENC:CN751302CG', 'enclosureBay': 4, 'associatedServer': None, 'hideUnusedFlexNics': True, 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': 'Updated Profile', 'category': 'server-profiles', 'affinity': 'Bay', 'status': 'OK', 'state': 'Normal', 'inProgress': False,
                                       'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'maximumMbps': 10000, 'allocatedMbps': 2500, 'requestedVFs': 'Auto', 'networkUri': 'NS:netset-1a', 'interconnectUri': 'IC:CN751302CG, interconnect 3', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'wwpn': None, 'wwnn': None, 'deploymentStatus': 'Deployed',
                                                        'boot': {'priority': 'NotBootable', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}},
                                                       {'id': 2, 'name': 'FCOE1', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:1-b', 'requestedMbps': '2500', 'maximumMbps': 20000, 'allocatedMbps': 2500, 'requestedVFs': None, 'allocatedVFs': None, 'networkUri': 'FCOE:FCOE-1084', 'interconnectUri': 'IC:CN751302CG, interconnect 3', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'deploymentStatus': 'Deployed',
                                                        'boot': {'priority': 'NotBootable', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}},
                                                       {'id': 3, 'name': 'FCOE2', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:2-b', 'requestedMbps': '2500', 'maximumMbps': 20000, 'allocatedMbps': 2500, 'requestedVFs': None, 'allocatedVFs': None, 'networkUri': 'FCOE:FCOE-1085', 'interconnectUri': 'IC:CN750163KV, interconnect 6', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'deploymentStatus': 'Deployed',
                                                        'boot': {'priority': 'NotBootable', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}}],
                                       'boot': {'manageBoot': True, 'order': ['HardDisk']},
                                       'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                                       'firmware': {'manageFirmware': False, 'firmwareBaselineUri': None, 'forceInstallFirmware': False, 'firmwareInstallType': None},
                                       'bios': {'manageBios': False, 'overriddenSettings': []},
                                       'osDeploymentSettings': None,
                                       'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': False, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': 1}]}]},
                                       'sanStorage': {'manageSanStorage': True, 'hostOSType': 'Windows 2012 / WS2012 R2',
                                                      'volumeAttachments': [{'id': 1, 'volumeUri': 'SVOL:E1Bay4Volume1', 'lunType': 'Manual', 'lun': 1, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'status': 'OK', 'state': 'Attached',
                                                                             'storagePaths': [{'connectionId': 2, 'isEnabled': True, 'status': 'OK', 'storageTargetType': 'Auto', 'storageTargets': ['20:21:00:02:AC:00:C3:12', '21:21:00:02:AC:00:C3:12']}]},
                                                                            {'id': 2, 'volumeUri': 'SVOL:E1Bay4Volume2', 'lunType': 'Manual', 'lun': 2, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'status': 'OK', 'state': 'Attached',
                                                                             'storagePaths': [{'connectionId': 3, 'isEnabled': True, 'status': 'OK', 'storageTargetType': 'Auto', 'storageTargets': ['20:22:00:02:AC:00:C3:12', '21:22:00:02:AC:00:C3:12']}]}]
                                                      }
                                       }

expected_edit_server_profile_E1bay5 = {'name': 'E1Bay5', 'type': 'ServerProfileV6', 'uri': 'SP:E1Bay5', 'serverHardwareUri': 'SH:CN751302CG, bay 5', 'serverHardwareTypeUri': 'SHT:SY 480 Gen9 1', 'enclosureGroupUri': 'EG:CHO-EG-Multi', 'enclosureUri': 'ENC:CN751302CG', 'enclosureBay': 5, 'associatedServer': None, 'hideUnusedFlexNics': True, 'serialNumberType': 'Virtual', 'iscsiInitiatorNameType': 'AutoGenerated', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': 'Updated Profile', 'category': 'server-profiles', 'affinity': 'Bay', 'status': 'OK', 'state': 'Normal', 'inProgress': False,
                                       'connections': [{'id': 1, 'name': 'Ethernet1', 'functionType': 'Ethernet', 'portId': 'Mezz 3:1-a', 'requestedMbps': '2500', 'maximumMbps': 10000, 'allocatedMbps': 2500, 'requestedVFs': 'Auto', 'networkUri': 'NS:netset-1a', 'interconnectUri': 'IC:CN751302CG, interconnect 3', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'wwpn': None, 'wwnn': None, 'deploymentStatus': 'Deployed',
                                                        'boot': {'priority': 'NotBootable', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}},
                                                       {'id': 2, 'name': 'FCOE1', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:1-b', 'requestedMbps': '2500', 'maximumMbps': 20000, 'allocatedMbps': 2500, 'requestedVFs': None, 'allocatedVFs': None, 'networkUri': 'FCOE:FCOE-1084', 'interconnectUri': 'IC:CN751302CG, interconnect 3', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'deploymentStatus': 'Deployed',
                                                        'boot': {'priority': 'NotBootable', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}},
                                                       {'id': 3, 'name': 'FCOE2', 'functionType': 'FibreChannel', 'portId': 'Mezz 3:2-b', 'requestedMbps': '2500', 'maximumMbps': 20000, 'allocatedMbps': 2500, 'requestedVFs': None, 'allocatedVFs': None, 'networkUri': 'FCOE:FCOE-1085', 'interconnectUri': 'IC:CN750163KV, interconnect 6', 'macType': 'Virtual', 'wwpnType': 'Virtual', 'deploymentStatus': 'Deployed',
                                                        'boot': {'priority': 'NotBootable', 'initiatorNameSource': 'ProfileInitiatorName', 'initiatorVlanId': 1}}],
                                       'boot': {'manageBoot': True, 'order': ['HardDisk']},
                                       'bootMode': {'manageMode': True, 'mode': 'UEFI', 'pxeBootPolicy': 'Auto'},
                                       'firmware': {'manageFirmware': False, 'firmwareBaselineUri': None, 'forceInstallFirmware': False, 'firmwareInstallType': None},
                                       'bios': {'manageBios': False, 'overriddenSettings': []},
                                       'osDeploymentSettings': None,
                                       'localStorage': {'sasLogicalJBODs': [], 'controllers': [{'deviceSlot': 'Embedded', 'mode': 'RAID', 'initialize': False, 'importConfiguration': False, 'logicalDrives': [{'name': 'OSDisk', 'raidLevel': 'RAID0', 'bootable': True, 'numPhysicalDrives': 1, 'driveTechnology': 'SasHdd', 'sasLogicalJBODId': None, 'driveNumber': 1}]}]},
                                       'sanStorage': {'manageSanStorage': True, 'hostOSType': 'Windows 2012 / WS2012 R2',
                                                      'volumeAttachments': [{'id': 1, 'volumeUri': 'SVOL:E1Bay5Volume1', 'lunType': 'Manual', 'lun': 1, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'status': 'OK', 'state': 'Attached',
                                                                             'storagePaths': [{'connectionId': 2, 'isEnabled': True, 'status': 'OK', 'storageTargetType': 'Auto', 'storageTargets': ['20:21:00:02:AC:00:C3:12', '21:21:00:02:AC:00:C3:12']}]},
                                                                            {'id': 2, 'volumeUri': 'SVOL:E1Bay5Volume2', 'lunType': 'Manual', 'lun': 2, 'volumeStoragePoolUri': 'SPOOL:TB4-Raid5-FC', 'volumeStorageSystemUri': 'SSYS:tbr13par', 'status': 'OK', 'state': 'Attached',
                                                                             'storagePaths': [{'connectionId': 3, 'isEnabled': True, 'status': 'OK', 'storageTargetType': 'Auto', 'storageTargets': ['20:22:00:02:AC:00:C3:12', '21:22:00:02:AC:00:C3:12']}]}]
                                                      }
                                       }
