
class C7000_GeneralNetworingElements(object):
    ID_NETWORKING = "xpath=.//*[@id='fs-settings-network-panel']/div/header/h2/a"
    ID_DROPDOWN_ACTIONS = "xpath=.//*[@id='hp-settings-actions']/label"
    ID_TEXT_HOST_NAME_VALUE = "xpath=.//*[@id='cic-network-hostname' and text()='%s']"  # hostname
    ID_TEXT_HOST_NAME = "xpath=.//*[@id='cic-network-hostname']"
    ID_TEXT_IPV4_ASSIGNMENT = "xpath=.//*[@id='fs-settings-appliance-IPv4-addrtype']"
    ID_TEXT_IPV4_ADDRESS = "xpath=.//*[@id='fs-settings-appliance-IPv4-address-1node']"
    ID_TEXT_IPV4_SUBNET_MASK_OR_CIDR = "xpath=.//*[@id='fs-settings-appliance-IPv4-subnet']"
    ID_TEXT_IPV4_GATEWAY_ADDRESS = "xpath=.//*[@id='fs-settings-appliance-IPv4-gateway']"
    ID_TEXT_IPV6_ASSIGNMENT = "xpath=.//*[@id='fs-settings-appliance-IPv6-addrtype']"
    ID_TEXT_IPV6_ADDRESS = "xpath=.//*[@id='fs-settings-appliance-IPv6-address-1node']"
    ID_TEXT_IPV6_SUBNET_MASK_OR_CIDR = "xpath=.//*[@id='fs-settings-appliance-IPv6-subnet']"
    ID_TEXT_IPV6_GATEWAY_ADDRESS = "xpath=.//*[@id='fs-settings-appliance-IPv6-gateway']"
    ID_TEXT_PREFERRED_DNS_SERVER = "xpath=.//*[@id='fs-settings-appliance-DNS-preferred']"
    ID_TEXT_ALTERNATE_DNS_SERVER = "xpath=.//*[@id='fs-settings-appliance-DNS-alternate']"
    ID_SELECT_ACTION_PING = "xpath=.//*[@id='fs-settings-ping']"
    ID_INPUT_IPADDR_TO_PING = "xpath=.//div/input[@name='hostname']"
    ID_BUTTON_PING = "xpath=.//*[@id='fs-setting-ping-button']"
    ID_TEXT_PING_RESULTS = "xpath=//*[@id='fs-setting-ping-results']"
    ID_BUTTON_CLOSE = "xpath=.//*[@id='fs-ping-show-close']"


class C7000_EditNetworkingElements(object):
    ID_SELECT_ACTION_EDIT = "xpath=.//*[@id='hp-edit-network']"
    ID_DIALOG_EDIT_NETWORKING = "id=cic-settings-networking-form"
    ID_SELECT_GENERAL_PANEL = "xpath=.//*[@id='cic-setting-network-panel-selector']/ol/li/a[text()='General']"
    ID_SELECT_IPV4_PANEL = "xpath=.//*[@id='cic-setting-network-panel-selector']/ol/li/a[text()='IPv4']"
    ID_SELECT_IPV6_PANEL = "xpath=.//*[@id='cic-setting-network-panel-selector']/ol/li/a[text()='IPv6']"
    ID_SELECT_DNS_PANEL = "xpath=.//*[@id='cic-setting-network-panel-selector']/ol/li/a[text()='DNS']"
    ID_INPUT_APPLIANCE_HOST_NAME = "xpath=.//*[@id='cic-network-hostname']"
    ID_RADIO_IPV4_ADDRESS_ASSIGNMENT_MANUAL = "xpath=.//*[@id='cic-network-ipv4-static']"
    ID_RADIO_IPV4_ADDRESS_ASSIGNMENT_DHCP = "xpath=.//*[@id='cic-network-ipv4-dhcp']"
    ID_DROPDOWN_NETWORKINGTYPE_SELECTOR = "xpath=.//*[@id='cic-setting-network-panel-selector']"
    ID_INPUT_IPV4_ADDRESS = "xpath=.//*[@id='cic-network-ip-ipv4']"
    ID_INPUT_IPV4_SUBNET_MASK_OR_CIDR = "xpath=.//*[@id='cic-network-mask-ipv4']"
    ID_INPUT_IPV4_GATEWAY_ADDRESS = "xpath=.//*[@id='cic-network-gateway-ipv4']"
    ID_INPUT_PREFERRED_DNS_SERVER = "xpath=.//*[@id='cic-network-preferred-dns']"
    ID_INPUT_ALTERNATE_DNS_SERVER = "xpath=.//*[@id='cic-network-alternate-dns']"
    ID_RADIO_IPV6_ADDRESS_ASSIGNMENT_MANUAL = "xpath=.//*[@id='cic-network-ipv6-static']"
    ID_RADIO_IPV6_ADDRESS_ASSIGNMENT_UNASSIGN = "xpath=.//*[@id='cic-network-ipv6-unassign']"
    ID_RADIO_IPV6_ADDRESS_ASSIGNMENT_DHCPV6 = "xpath=.//*[@id='cic-network-ipv6-dhcp']"
    ID_BUTTON_OK = "xpath=.//*[@id='cic-networking-edit-ok']"
    ID_BUTTON_CANCEL = "xpath=.//*[@id='cic-networking-edit-cancel']"
    ID_INPUT_IPV6_ADDRESS = "xpath=.//*[@id='cic-network-ip-ipv6']"
    ID_INPUT_IPV6_SUBNET_MASK_OR_CIDR = "xpath=.//*[@id='cic-network-mask-ipv6']"
    ID_INPUT_IPV6_GATEWAY_ADDRESS = "xpath=.//*[@id='cic-network-gateway-ipv6']"
    ID_PROGRESS_BAR_APPLYING_NETWORK_SETTINGS = "xpath=.//*[@id='cic-network-splash-dialog-edit']"
    ID_PROGRESS_BAR_APPLYING_INITIAL_NETWORK_SETTINGS = "xpath=.//*[@id='cic-network-splash-dialog-init']"
    ID_TEXT_HOST_NAME = "id=fs-settings-appliance-overview-hostname1"
    ID_TEXT_APPLIANCE_IP_ADDRESS = "id=fs-settings-appliance-overview-ipaddr1"
    ID_TEXT_SETTINGS = "//*[@id='hp-settings-page']//a[text()='Settings']"
