'''
Created on July 02, 2013

This file contains all element ID on Fusion Settings Page
'''

__version__ = "$Revision: 98f42236d1af $"
# $Source$


class FusionSettingsPage(object):
    """
    This file contains all element ID on Fusion Settings Page
    """
    ID_EDIT_IPV4_ADDRESS_UPDATE_BUTTON = "cic-settings-ipv4-subnetattributes-update"
    ID_EDIT_ADDRESS_IDENTIFIERS_FORM = "id=cic-addresses-edit"
    XPATH_IPV4_ADDRESS_TABLE_NO_DATA = "xpath=//*[@id='cic-settings-edit-ipv4-table']/tbody//*[contains(text(),'No data')]"
    ID_EDIT_IPV4_POOLS_ENABLE_RANGES_CHECKBOX = "id=cic-settings-ipv4-use-pool"
    XPATH_ADDRESS_AND_IDENTIFIERS_HEADER = "xpath=//div[@id='hp-settings-show']//h1[text()='Addresses and Identifiers']"
    XPATH_ADDRESS_AND_IDENTIFIERS_PAGE_SETTINGS_LINK = "xpath=//div[@class='hp-page-label hp-preserve']//a[text()='Settings']"
    XPATH_ADDRESS_IDENTIFIERS_PAGE_IPV4_TABLE = "xpath=//*[@id='cic-settings-ipv4-table-more_wrapper']"
    XPATH_ADDRESS_IDENTIFIERS_IPV4_RANGE_TABLE_LABEL = "xpath=//*[@id='hp-settings-show']//label[text()='IPv4 Address Ranges']"
    ID_SECURITY_LINK = "xpath=.//*[@id='fs-settings-security-panel']//a[text()='Security']"
    ID_SETTINGS_LINK = "xpath=.//*[@id='hp-settings-page']/nav/div[1]/h1/a[text()='Settings']"
    ID_SETTINGS_TEMP_LINK = "xpath=//a[@href='#/settings']"
    ID_DIAGNOSTIC_TOOLS_LINK = "xpath=.//*[@id='fs-diagnostics-tool-link']"

    ID_BTN_UPDATE_IPV4_ADDRESS = "id=cic-settings-ipv4update"
    ID_UPDATE_IPV4_ADDRESS_RANGE_NAME = "id=cic-settings-ipv4-name-update"
    ID_UPDATE_IPV4_ADDRESS_RANGE_FROM = "id=cic-settings-from-update-input"
    ID_UPDATE_IPV4_ADDRESS_RANGE_TO = "id=cic-settings-to-update"
    ID_UPDATE_IPV4_ADDRESS_RANGE_DOMAIN = "id=cic-settings-ipv4-domain-update"
    ID_UPDATE_IPV4_ADDRESS_RANGE_SUBNETMASK = "id=cic-settings-ipv4-subnet-update-input"
    ID_UPDATE_IPV4_ADDRESS_RANGE_GATEWAY = "id=cic-settings-ipv4-gateway-update"
    ID_UPDATE_IPV4_ADDRESS_DNS1 = "id=cic-settings-ipv4-dns1-update"
    ID_UPDATE_IPV4_ADDRESS_DNS2 = "id=cic-settings-ipv4-dns2-update"
    ID_UPDATE_IPV4_ADDRESS_DNS3 = "id=cic-settings-ipv4-dns3-update"
    ID_BTN_CANCEL_UPDATE_RANGE = "id=cic-settings-guid-update-cancel"

    XPATH_ADD_IPV4_ADDRESS_SEARCH_COMBO_MENU = "xpath=//*[@id='cic-settings-ipv4-add-form']//div[@class='hp-search-combo-menu']"
    XPATH_IPV4_ADDRESS_NETID_SUGGESTION_HEADER = "//*[@id='cic-settings-ipv4-add-form']//div[@class='hp-search-combo-menu']/div[@class='hp-header']"
    XPATH_IPV4_ADDRESS_NETID_SEARCH_BUTTON = "xpath=//*[@id='cic-settings-ipv4-add-form']//div[@class='hp-search-combo-control']"
    XPATH_IPV4_ADDRESS_NETID_DROPDOWN_LIST_ELEMENT = "xpath=//*[@id='cic-settings-ipv4-add-form']//div[@class='hp-search-combo-menu']//li[@data-id='%s']"

    ID_INPUT_ADD_IPV4_ADDRESS_NETWORK_ID = "id=cic-settings-ipv4-networkid-select-input"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_SUBNETMASK = "id=cic-settings-ipv4-subnet-custom-input"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_GATEWAY = "id=cic-settings-ipv4-gateway-custom-input"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_DOMAIN = "id=cic-settings-ipv4-domain-custom-input"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_DNS1 = "id=cic-settings-ipv4-dns1-custom-input"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_DNS2 = "id=cic-settings-ipv4-dns2-custom-input"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_DNS3 = "id=cic-settings-ipv4-dns3-custom-input"

    ID_CUSTOM_IPV4_ADDRESS_RANGE_SUBNETMASK = "id=cic-settings-ipv4-subnet-custom"
    ID_CUSTOM_IPV4_ADDRESS_RANGE_GATEWAY = "id=cic-settings-ipv4-gateway-custom"
    ID_CUSTOM_IPV4_ADDRESS_RANGE_DOMAIN = "id=cic-settings-ipv4-domain-custom"
    ID_CUSTOM_IPV4_ADDRESS_RANGE_DNS1 = "id=cic-settings-ipv4-dns1-custom"
    ID_CUSTOM_IPV4_ADDRESS_RANGE_DNS2 = "id=cic-settings-ipv4-dns2-custom"
    ID_CUSTOM_IPV4_ADDRESS_RANGE_DNS3 = "id=cic-settings-ipv4-dns3-custom"

    ID_SETTINGS_GUID_PANEL = "id=cic-settings-guid-panel"
    ID_ADD_IPV4_RANGE_FORM = "cic-settings-ipv4-add-dialog"
    ID_EDIT_IPV4_RANGE_FORM = "cic-settings-ipv4update-dialog"

    XPATH_IP_RANGE_ENABLE_CEHCKBOX = "xpath=//*[@id='cic-settings-edit-checkbox-id-range-IPV4-%s' and @disabled]"

    XPATH_ADDRESS_AND_IDENTIFIERS_PAGE_TABLE_CELL_TEXTS = "xpath=//*[@id='cic-settings-ipv4-table-more']/tbody/tr[*]//*[text()='%s']/parent::*/following-sibling::*[text()='%s']"
    XPATH_ADDRESS_AND_IDENTIFIERS_PAGE_RANGE_NAME = "xpath=//*[@id='cic-settings-ipv4-table-more']/tbody/tr//*[text()='%s']"
    XPATH_ADDRESS_AND_IDENTIFIERS_PAGE_RANGE_REMAINING = "xpath=//*[@id='cic-settings-ipv4-table-more']/tbody/tr//*[text()='%s']/following::td[6]"
    XPATH_ADDRESS_AND_IDENTIFIERS_RANGE_CHECKBOX = "xpath=//*[@id='cic-settings-ipv4-table-more']/tbody/tr//*[text()='%s']/following::td[1]"

    XPATH_IPV4_RANGE_NAME_COMMON = "xpath=//*[@id='%s']/tbody/tr//*[text()='%s']"
    XPATH_IPV4_RANGE_TABLE_CELLS_COMMON = "xpath=//*[@id='%s']/tbody/tr[*]//*[text()='%s']/parent::*/following-sibling::*[text()='%s']"

    XPATH_EDIT_MESSAGE_DETAILS = "xpath=//*[@id='hp-form-message']/div[@class='hp-form-message-details']"

    XPATH_IP_RANGE_EDIT_TO_SCROLL = "//*[@id='cic-settings-edit-ipv4-table']/tbody/tr//*[text()='%s']/parent::*/following-sibling::*/*[@class='hp-edit crm-ipv4-edit']"
    XPATH_IP_RANGEDELETE_TO_SCROLL = "//*[@id='cic-settings-edit-ipv4-table']/tbody/tr//*[text()='%s']/parent::*/following-sibling::*/*[@class='hp-close crm-guid-close']"

    ID_IPV4_MENU_EDIT_IPV4_ADDRESS = "xpath=//*[@id='cic-settings-edit-ipv4-table']/tbody/tr//*[text()='%s']/parent::*/following-sibling::*/*[@class='hp-edit crm-ipv4-edit']"
    ID_IPV4_MENU_DELETE_IPV4_ADDRESS = "xpath=//*[@id='cic-settings-edit-ipv4-table']/tbody/tr//*[text()='%s']/parent::*/following-sibling::*/*[@class='hp-close crm-guid-close']"

    XPATH_IPV4_RANGE_COUNT_COMMON = "xpath=//*[@id='%s']/tbody/tr//*[text()='%s']/following::td[5]"
    XPATH_IPV4_RANGE_ALLOCATED_COMMON = "xpath=//*[@id='%s']/tbody/tr//*[text()='%s']/following::td[6]"
    XPATH_IPV4_RANGE_REMAINING_COMMON = "xpath=//*[@id='%s']/tbody/tr//*[text()='%s']/following::td[7]"

    XPATH_IPV4_VERIFY_RANGE_NETWORK_ID = "//*[@id='%s']/tbody//*[text()='%s']/parent::*/parent::*/following-sibling::node()[position()=1]//*[@class='template-ipv4-row-details-network-id' and text()='%s']"
    XPATH_IPV4_VERIFY_RANGE_SUBNET = "//*[@id='%s']/tbody//*[text()='%s']/parent::*/parent::*/following-sibling::node()[position()=1]//*[@class='template-ipv4-row-details-subnet-mask' and text()='%s']"
    XPATH_IPV4_VERIFY_RANGE_GATEWAY = "//*[@id='%s']/tbody//*[text()='%s']/parent::*/parent::*/following-sibling::node()[position()=1]//*[@class='template-ipv4-row-details-gateway' and text()='%s']"
    XPATH_IPV4_VERIFY_RANGE_DOMAIN = "//*[@id='%s']/tbody//*[text()='%s']/parent::*/parent::*/following-sibling::node()[position()=1]//*[@class='template-ipv4-row-details-domain' and text()='%s']"
    XPATH_IPV4_VERIFY_RANGE_DNS = "//*[@id='%s']/tbody//*[text()='%s']/parent::*/parent::*/following-sibling::node()[position()=1]//*[@class='template-ipv4-row-details-dns' and text()='%s']"

    ID_BTN_ADD_IPV4_RANGE = "id=cic-settings-ipv4-add-range"
    ID_BTN_CANCEL_IPV4_RANGE = "cic-settings-ipv4-cancel"
    ID_BTN_CANCEL_SETTINGS_EDIT_IDENTIFIERS = "id=cic-settings-edit-cancel"
    ID_BTN_IPV4_ADD_ADDRESS_RANGE = "id=cic-settings-ipv4-add"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_NAME = "id=cic-settings-ipv4-name-custom"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_FROM = "id=cic-settings-from-ipv4"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_TO = "id=cic-settings-to-ipv4"
    ID_INPUT_ADD_IPV4_ADDRESS_RANGE_COUNT = "id=cic-settings-count-custom"

    ID_HP_NAVIGATE_AWAY_DIALOG = "id=hp-form-navigate-away-dialog"
    IP_HP_NAVIGATE_AWAY_BUTTON = "id=hp-form-navigate-away-proceed"
    ID_IPV4_ADDRESS_IDENTIFIERS_EDIT_FORM = "id=cic-addresses-edit-form"

    ID_IPV4_EDIT_FORM_ADDRESS_RANGE_TABLE = "cic-settings-edit-ipv4-table"
    ID_IPV4_ADDRESS_IDENTIFIERS_PAGE_RANGE_TABLE = "cic-settings-ipv4-table-more"

    ID_IPV4_MENU_STARTING_ADDRESS_RANGE = "xpath=//*[@id='cic-settings-edit-ipv4-table']/tbody/tr//*[text()='%s']/following::td[2]"

    ID_CHKBOX_IPV4_ADDRESS_ENABLE = "cic-settings-edit-checkbox-id-range-IPV4-%s"
    ID_IPV4_DELETE_DIALOG = "id=cic-settings-ipv4delete-dialog"
    ID_IPV4_ADDRESS_LABEL_ERROR_DELETE_CUSTOM = "xpath=//*[@id='cic-settings-ipv4delete-dialog']//*[@class='hp-dialog-notification']//*[@class='hp-message']"
    ID_IPV4_ADDRESS_BTN_DELETE_CLOSE = "id=cic-settings-guid-delete-close"
    ID_LABEL_ERROR_UPDATE_CUSTOM = "//label[@class='hp-error']"
    ID_IPV4_ADDRESSES_LIST_FOR_OTHERS = "id=cic-settings-ipv4-table-more_wrapper"

    ID_IPV4_ADDRESS_RANGE_COUNT = "xpath=//*[@id='cic-settings-edit-ipv4-table']/tbody/tr//*[text()='%s']/following::td[5]"
    ID_IPV4_ADDRESS_RANGE_ALLOCATED = "xpath=//*[@id='cic-settings-edit-ipv4-table']/tbody/tr//*[text()='%s']/following::td[6]"
    ID_IPV4_ADDRESS_RANGE_REMAINING = "xpath=//*[@id='cic-settings-edit-ipv4-table']/tbody/tr//*[text()='%s']/following::td[7]"

    XPATH_IPV4_ADDRESS_EDIT_TABLE_CELL_TEXTS = "xpath=//*[@id='cic-settings-edit-ipv4-table']/tbody/tr[*]//*[text()='%s']/parent::*/following-sibling::*[text()='%s']"
    ID_ELEMENT_IPV4_ADDRESS_NAME_BASE = "xpath=//*[@id='cic-settings-edit-ipv4-table']/tbody/tr//*[text()='%s']"
    ID_IPV4_ADDRESSES_LIST = "xpath=//*[@id='cic-settings-edit-ipv4-table_wrapper']//tbody"

    ID_PAGE_LABEL = "xpath=//h1[text()='Settings' and @class='hp-parent-page-label']"
    ID_LABEL_LICENSES_TITLE = "xpath=//h1[@id='hp-settings-details-title' and .='Licenses']"
    ID_MENU_ACTION_MAIN_BTN = "xpath=//label[text()='Actions']"
    ID_MENU_ACTION_CREATE_SUPPORT_DUMP = "hp-create-dump-link"
    ID_MENU_ACTION_DOWNLOAD_AUDIT_LOGS = "fs-security-settings-more-download-auditlogs-action"
    ID_MENU_ACTION_DOWNLOAD_CIDEBUG_LOGS = "xpath=.//*[@id='fs-settings-diagnostics-more-downloadlog-action']/a"
    ID_MENU_ACTION_CREATE_SELF_SIGNED_CERT = "hp-create-cert-link"
    ID_MENU_ACTION_CREATE_CERT_SIGNING_REQ = "id=hp-create-csr-link"
    ID_MENU_ACTION_IMPORT_CERTIFICATE = "id=hp-import-cert-link"
    ID_MENU_ACTION_UPDATE = "id=hp-update-appliance"
    ID_MENU_ACTION_EDIT_SUPPORT_ACCESS = "id=hp-support-access"
    ID_MENU_ACTION_CREATE_BACKUP = "id=hp-backup-appliance"
    ID_MENU_ACTION_DOWNLOAD_BACKUP = "xpath = .//*[@id='hp-settings-actions-admin']/li//a[text()='Download backup']"
    ID_MENU_ACTION_RESTORE_FROM_BACKUP = "id=hp-restore-appliance"
    ID_MENU_ACTION_SHUTDOWN = "id=hp-appliance-reset-link"
    ID_MENU_ACTION_RESTART = "link=Restart"
    ID_BACKUP_LINK = "xpath = .//*[@id='fs-settings-backup-panel']//a[text()='Backup']"

    ID_CHECKBOX_RESTORE = "xpath =.//*[@id='fs-restore-confirmation-checkbox']"
    ID_BTN_RESTORE_CONFIRM = "xpath =.//*[@id='fs-settings-restore-confirm-restoreFromBackup']"
    ID_MENU_ACTION_RESTORE_BACKUP = "xpath =.//*[@id='hp-restore-appliance']"
    ID_MENU_ACTION_RESTORE_LABEL = "xpath=.//*[@id='fs-settings-restore-restoreFromStagedBackup']"

    ID_BACKUP_FILENAME_LABEL = "xpath=.//*[@id='fs-settings-backup-created']/div[contains(@class,'backup-created-filename')]"
    ID_SETTINGS_LABEL = "xpath=.//*[@id='hp-settings-page']/nav/div[1]/h1/a[text()='Settings']"
    ID_RADIOBTN_SELECT_A_BACKUP = "xpath =.//*[@id='fs-settings-restore-backup-uploaded-file']"
    # Support Dump
    ID_BTN_YES_CREATE_SUPPORT_DUMP = "id=hp-details-create-dump"
    ID_BTN_CANCEL_SUPPORT_DUMP = "id=hp-details-cancel-dump"
    # Create Self Signed Cert
    ID_INPUT_SELF_SIGN_CERT_COUNTRY = "id=cic-selfsigned-country"
    ID_INPUT_SELF_SIGN_CERT_STATE = "id=cic-selfsigned-state"
    ID_INPUT_SELF_SIGN_CERT_CITY = "id=cic-selfsigned-locality"
    ID_INPUT_SELF_SIGN_CERT_ORGANIZATION_NAME = "id=cic-selfsigned-org"
    ID_INPUT_SELF_SIGN_CERT_ORGANIZATIONAL_UNIT = "id=cic-selfsigned-ou"
    ID_INPUT_SELF_SIGN_CERT_ALTERNATIVE_NAME = "id=cic-selfsigned-alt-name"
    ID_SELF_SIGN_CERT_ID_INPUT_CONTACT_PERSON = "id=cic-selfsigned-contact"
    ID_SELF_SIGN_CERT_ID_INPUT_EMAIL_ADDRESS = "id=cic-selfsigned-email"
    ID_SELF_SIGN_CERT_ID_INPUT_SURNAME = "id=cic-selfsigned-surname"
    ID_INPUT_SELF_SIGN_CERT_GIVEN_NAME = "id=cic-selfsigned-given-name"
    ID_INPUT_SELF_SIGN_CERT_INITIALS = "id=cic-selfsigned-initials"
    ID_INPUT_SELF_SIGN_CERT_DNQUALIFIER = "id=cic-selfsigned-dn"
    ID_BTN_SELF_SIGN_CERT_OK = "id=cic-selfsigned-create-ok"
    ID_BTN_SELF_SIGN_CERT_CANCEL = "id=cic-selfsigned-create-cancel"
    ID_TEXT_SELF_SIGN_CERT_COUNTRY = "xpath=.//*[@id='fs-settings-security-certificate-country']"
    ID_TEXT_SELF_SIGN_CERT_STATE = "xpath=.//*[@id='fs-settings-security-certificate-state']"
    ID_TEXT_SELF_SIGN_CERT_LOCALITY = "xpath=.//*[@id='fs-settings-security-certificate-locality']"
    ID_TEXT_SELF_SIGN_CERT_ORG = "xpath=.//*[@id='fs-settings-security-certificate-org']"
    ID_TEXT_SELF_SIGN_CERT_ALTERNATE_NAME = "xpath=.//*[@id='fs-settings-security-certificate-alt-name']"
    ID_TEXT_SELF_SIGN_CERT_ORGANIZATIONAL_UNIT = "xpath=.//*[@id='fs-settings-security-certificate-ou']"
    ID_TEXT_SELF_SIGN_CERT_CONTACT_PERSON = "xpath=.//*[@id='fs-settings-security-certificate-contact']"
    ID_TEXT_SELF_SIGN_CERT_EMAIL_ADDRESS = "xpath=.//*[@id='fs-settings-security-certificate-email']"
    ID_TEXT_SELF_SIGN_CERT_SURNAME = "xpath=.//*[@id='fs-settings-security-certificate-surname']"
    ID_TEXT_SELF_SIGN_CERT_GIVEN_NAME = "xpath=.//*[@id='fs-settings-security-certificate-given-name']"
    ID_TEXT_SELF_SIGN_CERT_INITIALS = "xpath=.//*[@id='fs-settings-security-certificate-initials']"
    ID_TEXT_SELF_SIGN_CERT_DN = "xpath=.//*[@id='fs-settings-security-certificate-dn']"
    ID_TEXT_SELF_SIGN_CERT_CN = "xpath=.//*[@id='fs-settings-security-certificate-common-name']"
    # Create Self Sign Request
    ID_BTN_CREAT_SELF_SIGNED_CERT = "xpath=//*[@id='fs-security-settings-more-create-selfsignedcert-action']"
    ID_INPUT_SELF_SIGN_REQUEST_COUNTRY = "id=cic-csr-country"
    ID_INPUT_SELF_SIGN_REQUEST_STATE = "id=cic-csr-state"
    ID_INPUT_SELF_SIGN_REQUEST_CITY = "id=cic-csr-locality"
    ID_INPUT_SELF_SIGN_REQUEST_ORG_NAME = "id=cic-csr-org"
    ID_INPUT_SELF_SIGN_REQUEST_ORG_UNIT = "id=cic-csr-ou"
    ID_INPUT_SELF_SIGN_REQUEST_ALTERNATIVE_NAME = "id=cic-csr-alt-name"
    ID_INPUT_ELF_SIGN_REQUEST_CONTACT_PERSON = "id=cic-csr-contact"
    ID_INPUT_SELF_SIGN_REQUEST_EMAIL_ADDRESS = "id=cic-csr-email"
    ID_INPUT_SELF_SIGN_REQUEST_SURNAME = "id=cic-csr-surname"
    ID_INPUT_SELF_SIGN_REQUEST_GIVEN_NAME = "id=cic-csr-given-name"
    ID_INPUT_SELF_SIGN_REQUEST_INITIALS = "id=cic-csr-initials"
    ID_INPUT_SELF_SIGN_REQUEST_DN_QUALIFY = "id=cic-csr-dn"
    ID_INPUT_SELF_SIGN_REQUEST_CHALLENGE_PWD = "id=cic-csr-challenge-password"
    ID_INPUT_SELF_SIGN_REQUEST_CONFIRM_PWD = "id=cic-csr-confirm-password"
    ID_INPUT_SELF_SIGN_REQUEST_UNSTRUCTURED_NAME = "id=cic-csr-unstructured-name"
    ID_BTN_ADD_SELF_SIGN_REQUEST = "id=cic-csr-create-ok"
    ID_BTN_CANCEL_SELF_SIGN_REQUEST = "id=cic-csr-create-cance"
    ID_TEXT_CERT_VALID_FROM = "xpath=//*[@id='fs-settings-security-certificate-valid-from']"
    ID_TEXT_CERT_VALID_TILL = "xpath=.//*[@id='fs-settings-security-certificate-valid-until']"
    # IMPORT CERT
    ID_BTN_OTHER_USER_IS_LOGGED = "id=cic-import-logged-in-msg"
    ID_INPUT_CERT = "id=cic-import-base64-text"
    ID_BTN_OK_IMPORT_CERT = "id=cic-import-base64-ok"
    ID_BTN_CANCEL_IMPORT_CERT = "id=cic-import-base64-cancel"
    # EDIT SUPPORT ACCESS
    ID_TOGGLE_ON = "css=li.hp-on"
    ID_TOGGLE_OFF = "css=li.hp-off"
    ID_BTN_OK_SUPPORT_ACCESS = "id=hp-supportaccess-ok-button"
    ID_BTN_CANCEL_SUPPORT_ACCESS = "id=hp-supportaccess-cancel-button"
    # SHUTDOWN and #RESTART APPLIANCE
    ID_APPLIANCE_LINK = "xpath=.//*[@id='fs-settings-appliance-panel']/div/header/h2/a"
    ID_BTN_CANCEL_SHUTDOWN = "id=hp-cancel-shutdown"
    ID_BTN_YES_CONFIRM_SHUTDOWN = "id=hp-start-shutdown"
    # VIEW
    ID_COMBO_MENU_VIEW = "css=div.hp-value"
    ID_LINK_OVERVIEW = "id=hp-settings-panel-selector"  # changed from Overview to panel
    ID_LINK_OVERVIEW_DROPDOWN = "xpath=.//*[@id='hp-settings-panel-selector']/div[text()='%s']"
    ID_LICENSE_AVAILABILITY = "xpath=.//*[@id='fs-settings-license-summary-gridPanels']//header/h2[text()='%s']"  # HP OneView w/o iLO, HP OneView
    ID_LINK_DNS = "//span[text()='DNS']"
    ID_LINK_IPV4 = "//span[text()='IPv6']"
    ID_LINK_TIME_PLACE = "//span[text()='Time and Place']"
    ID_LINK_BACKUP = "//span[text()='Backup']"
    ID_LINK_AUTHENTICATION = "//span[text()='Authentication']"
    ID_LINK_DIRECTORIES = "//span[text()='Directories']"
    ID_LINK_CERTIFICATE = "//span[text()='Certificate']"
    ID_LINK_HP_PUBLIC_KEY = "//span[text()='HP Public Key']"
    ID_LINK_SUPPORT = "//span[text()='Support']"
    ID_LINK_LICENSE = "//a[text()='Licenses']"  # added s to License
    ID_LINK_ADDRESS_IDENTIFIER = "//span[text()='Addresses and Identifiers']"
    ID_MENU_ACTION_ADDLICENSE = "id=hp-add-license"
    ID_DLG_ADDLICENSE = "xpath=.//*[@id='fs-addLicense-dialog']"
    ID_INPUT_LICENSEKEY = "xpath=.//*[@id='fs-license-licenseKeyValue']"
    ID_DLG_BTN_ADD = "xpath=.//*[@id='fs-license-add']"
    ID_DLG_BTN_ADDPLUS = "xpath=.//*[@id='fs-license-add-again']"
    ID_DLG_BTN_CANCEL = "xpath=.//*[@id='fs-addLicense-cancel']"
    ID_ADDLICENSE_ERR_MSG = "xpath=.//*[@id='hp-form-message']/div[1]/span[contains(text(),'Unable to add')]"
    ID_AVAILABLE_LICENSE = "xpath=.//header/h2[text()='%s']/following::div[contains(@id,'fs-settings-license-summary-availableLicenses')]"
    # CREATE BACKUP
    ID_LABEL_BACKUP_NOTIFICATION = "//div[@id='hp-page-notifications']/div/header"
    ID_LABEL_BACKUP_DETAILS = "css=div.hp-details"
    ID_LABEL_CREATE_BACKUP = "//div[@id='hp-page-notifications']//div[text()='Create backup']"
    # RESTORE BACKUP
    ID_BTN_BROWSE_FILE = "xpath=//input[@id='hp-file-chooser-file' and @class='hp-button hp-file-chooser-file' and @type='file' and  @value='Choose File Button' and @name='file']"
    ID_BTN_UPLOAD_AND_RESTORE = "xpath=.//*[@id='fs-settings-restore-uploadAndRestore']"
    ID_CHECKBOX_RESTORE_CONFIRMATION = "xpath=.//*[@id='fs-restore-confirmation-checkbox']"
    ID_BTN_RESTORE_FROM_BACKUP = "id=fs-settings-restore-restoreFromBackup"
    ID_BTN_YES_RESTORE_CONFIRMATION = "xpath=.//*[@id='fs-settings-restore-confirm-restoreFromBackup']"
    ID_LABEL_RESTORING_FROM_BACKUP = "//div[@id='hp-form-message']/div/span[text() = 'Restoring from backp ...']"
    ID_LABEL_RESTORING = "//div[text() = 'Restoring']"
    ID_LABEL_EDIT_SUPPORT_ACCESS = "xpath=.//*[@id='hp-change-page-container']/section/header/h1"
    ID_LABEL_WAITING = "xpath=//div/div/div/div[text()='Waiting']"
    ID_LABEL_PROGRESS = "xpath=//div[@id='hp-starting-progress' and @style='display: block;']"
    ID_LABEL_RESTART = "xpath=//div[@id='shutdown-warning' and text()='Restarting the appliance will cause users to be disconnected and running tasks to be interrupted.']"
    ID_TEXT_RESTARTING = "xpath=//div[@id='cic-appliance-restarting-msg-id']/p[text()='Restarting']"
    ID_LABEL_STARTING = "xpath=//div/div[text()='Starting']"
    ID_LABEL_UNAVAILABLE = "xpath=//div/div[text()='Temporarily unavailable']"
    ID_TEXT_SHUTDOWN = "xpath=//form/div[text()='Shutdown will cause all users to be logged out and all ongoing tasks to be cancelled.']"
    ID_LABEL_CREATE_SUPPORTDUMP = "xpath=//p[contains(.,'Creating a support dump may take a few minutes after which the file download will begin automatically. Meanwhile, you can continue to use the UI normally.')]"
    ID_ACTVITY_SUPPORT_DUMP = "css=nav.hp-sub-nav > div.hp-sidebar-control > div.hp-pin-right"
    ID_CLICK_ACTIVITY = "xpath = .//*[@id='hp-flyout-activities']/li/div[@class='hp-brief']/div[@class='hp-status hp-status-changing']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    ID_TIMESTAMP_SUPPORT_DUMP = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-changing']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    ID_VALIDATE_SUCCESS = "xpath = //header[@class='hp-active']/div[@class='hp-status hp-status-ok']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"  # %s replace with name of interconnect
    ID_TOGGLE_BTN_SERVICE_ACCESS = "xpath=.//*[@id='hp-eula-service-access-toggle-button-hpToggle']"
    ID_TOGGLE_BTN_SERVICE_ACCESS_ON = "xpath=.//*[@id='hp-eula-service-access-toggle-button-hpToggle']//li[@class='hp-on']"
    ID_TOGGLE_BTN_SERVICE_ACCESS_OFF = "xpath=.//*[@id='hp-eula-service-access-toggle-button-hpToggle']//li[@class='hp-off']"
    ID_LABEL_STATUS = "xpath=.//*[@id='statusLabel']"

    # REMOTE BACKUP SETTINGS
    ID_CHECKBOX_EDIT_BACKUP = "xpath=//*[@id='fs-settings-backup-enableRemoteBackupLocation']"
    ID_INPUT_REMOTESERVER_IP_HOST_NAME = "xpath=//*[@id='fs-settings-backup-edit-remote-host']"
    ID_INPUT_REMOTE_BACKUP_FOLDER = "xpath=//*[@id='fs-settings-backup-edit-folder']"
    ID_INPUT_REMOTESERVER_USERNAME = "xpath=//*[@id='fs-settings-backup-edit-remote-username']"
    ID_INPUT_REMOTESERVER_PASSWORD = "xpath=//*[@id='fs-settings-backup-edit-remote-password']"
    ID_INPUT_REMOTESERVER_SSHKEY = "xpath=//*[@id='fs-settings-backup-sshkey']"
    ID_DROPDOWN_FREQUENCY_SELECTOR = "xpath=//*[@id='fs-settings-backup-panel-schedule']//div[@class='hp-select']"
    ID_DROPDOWN_FREQUENCY_SELECTOR_NEW = "xpath=.//*[@id='fs-settings-backup-panel']//div[@class='hp-value']"
    ID_BACKUP_EDIT_OK_BUTTON = "id=fs-settings-backup-edit-ok"
    ID_BACKUP_EDIT_SSH_KEY_VERIFY_CHECKBOX = "id=fs-settings-backup-edit-ssh-confirmation-checkbox"
    ID_BACKUP_EDIT_SSH_OK_BUTTON = "id=fs-settings-backup-edit-ssh-ok"
    ID_BACKUP_EDIT_TIME = "id=fs-settings-backup-edit-time"
    ID_BACKUP_DOWNLOAD_OK = "xpath=.//*[@id='fs-settings-backup-download-ok']"
    ID_BACKUP_PAGE_REMOTE_PROTOCOL = "id=fs-settings-backup-remote-protocol"
    ID_BACKUP_PAGE_REMOTE_HOST = "id=fs-settings-backup-remote-host"
    ID_BACKUP_PAGE_REMOTE_FOLDER = "id=fs-settings-backup-remote-folder"
    ID_BACKUP_PAGE_REMOTE_USERNAME = "id=fs-settings-backup-remote-username"

    # Directory server function objects
    ID_BTN_ADD_DIRECTORY_SETTINGS = "id=add-directory-button"
    ID_LINK_SECURITY_PAGE = "link=Security"
    ID_SECURITY_EDIT = "xpath=//*[@id='fs-settings-security-panel-edit']"
    # ID_DIRECTORY_NAME = "xpath=//table[@id='security-directories-table']/tbody//td[contains(text(), '%s')]"
    ID_DIRECTORY_NAME = "xpath=//*[@id='security-directories-table']/tbody/tr[*]/td[contains(text(),'%s')]"
    ID_HP_FORM_MESSAGE_DETAILS = "xpath=//span[@class='hp-form-message-details']"
    ID_TRUST_BUTTON = "id=fs-trust-certificate-trustok"
    ID_CERT_CHECKBOX = "id=fs-settings-authn-specify-certificate"
    ID_BASE_DN = "id=fs-settings-authn-base-dn-text"
    ID_AD_OK_BUTTON = "id=fs-settings-authn-credentials-ok"
    ID_SECURITY_OK_BUTTON = "xpath=.//*[@id='hp-settings-edit-ok']"

    # Added for 1.10 to fix in 27_remove_directory_servers
    ID_REMOVE_SERVER_X_BUTTON_XPATH = ".//*[@id='security-directories-table']/tbody/tr[1]/td[3]"
    ID_REMOVE_SERVER_YES_BUTTON = "xpath=//button[.='Yes, delete']"
    ID_DIRECTORY_DEL = "xpath=//*[@id='security-directories-table']/tbody/tr[*]/td[contains(text(),'%s')]/parent::*/td[3]/div"

    # directory name
    ID_INPUT_DIR_NAME = "xpath=//*[@id='fs-settings-authn-dir-name-text']"
    # Credentials
    ID_INPUT_AUTHN_USERNAME = "xpath=//*[@id='fs-settings-authn-service-account-username']"
    ID_INPUT_AUTHN_PASSWORD = "xpath=//*[@id='fs-settings-authn-service-account-password']"
    # add directory button
    ID_BTN_ADD_DIRECTORY = "//*[@id='fs-settings-authn-add-dir-servers']"
    # ip address or host name
    ID_INPUT_IPADDRESS = "xpath=//*[@id='fs-settings-authn-host-name-text']"
    ID_INPUT_SERVER_PORT = "xpath=//*[@id='fs-settings-authn-port-text']"
    ID_INPUT_CERTIFICATE = "xpath=//*[@id='fs-settings-authn-certificate']"
    JS_ID_INPUT_CERTIFICATE = "fs-settings-authn-certificate"
    ID_BTN_DIRECTORY_SERVER_ADD = "xpath=.//*[@id='fs-settings-authn-add-dir-server-add']"
    ID_ERROR_MESSAGE = "xpath=.//*[@id='hp-form-message']/div[*]/span"
    ID_BTN_ADD_DIR = "xpath=//*[@id='fs-authn-add-dir-add']"
    ID_SERVER = "xpath=//ol[@id='fs-settings-security-overview-directories']/li[2]/span[text()='%s']"

    # Search context
    ID_INPUT_UID = "xpath=//input[@id='fs-settings-authn-search-context' and @name='uid']"
    ID_INPUT_ORG = "xpath=//input[@id='fs-settings-authn-search-context' and @name='org']"
    ID_INPUT_TOP = "xpath=//input[@id='fs-settings-authn-search-context' and @name='top']"
    ID_BTN_SETTINGS_EDIT_CANCEL = "id=hp-settings-edit-cancel"
    ID_ELEMENT_DIRECTORIES = "xpath=//*[@id='fs-settings-security-overview-directories']"

    ID_ELEMENT_SERVER_ALREADY_ADDED = "xpath=//div/span[text()='The specified authentication login domain is already configured in the system.']"
    ID_BTN_DIR_SERVER_CANCEL = "id=fs-cancel-add-dir"
    ID_ELEMENT_SECURYTY_HEADER = "xpath=//*[@id='fs-settings-security-panel']/header/a[text()='Security']"

    # EDIT ADDRESS AND IDENTIFIER
    ID_LINK_ADDRESS_AND_IDENTIFIER = "xpath=//*[@id='cic-settings-guid-panel']/header//a[text()='Addresses and Identifiers']"
    ID_LINK_CLICK_ADDRESS_AND_IDENTIFIER = "xpath=//*[@id='cic-settings-guid-panel']//header//a"
    ID_LINK_EDIT_ADDRESS_AND_IDENTIFIER = "xpath=//*[@id='cic-settings-guid-panel']/header/a[text()='Edit']"
    ID_DIALOG_EDIT_ADDRESS_AND_IDENTIFIER = "id=cic-addresses-edit"
    ID_PAGE_ADDRESS_AND_IDENTIFIER = "xpath=//*[@id='hp-settings-show']/section/header/h1[@class='hp-dynamic hp-ellipsised']"
    ID_TEXT_MAC_COUNT = "xpath=//div[@id='cic-settings-mac-table-more_wrapper']//div[@class='dataTables_scrollFoot']//td[5]"
    ID_TEXT_MAC_ALLOCATED = "xpath=//div[@id='cic-settings-mac-table-more_wrapper']//div[@class='dataTables_scrollFoot']//td[6]"
    ID_TEXT_MAC_REMAINING = "xpath=//div[@id='cic-settings-mac-table-more_wrapper']//div[@class='dataTables_scrollFoot']//td[7]"
    ID_TEXT_WWN_COUNT = "xpath=//div[@id='cic-settings-wwn-table-more_wrapper']//div[@class='dataTables_scrollFoot']//td[5]"
    ID_TEXT_WWN_ALLOCATED = "xpath=//div[@id='cic-settings-wwn-table-more_wrapper']//div[@class='dataTables_scrollFoot']//td[6]"
    ID_TEXT_WWN_REMAINING = "xpath=//div[@id='cic-settings-wwn-table-more_wrapper']//div[@class='dataTables_scrollFoot']//td[7]"
    ID_TEXT_SN_COUNT = "xpath=//div[@id='cic-settings-sn-table-more_wrapper']//div[@class='dataTables_scrollFoot']//td[5]"
    ID_TEXT_SN_ALLOCATED = "xpath=//div[@id='cic-settings-sn-table-more_wrapper']//div[@class='dataTables_scrollFoot']//td[6]"
    ID_TEXT_SN_REMAINING = "xpath=//div[@id='cic-settings-sn-table-more_wrapper']//div[@class='dataTables_scrollFoot']//td[7]"
    ID_DROPDOWN_EDIT_SELECTOR = "css=#cic-addresses-panel-edit-selector > div.hp-value"
    ID_LINK_WWN = "link=World Wide Names"
    ID_LINK_MAC_ADDRESS = "link=MAC Addresses"
    ID_LINK_SERIAL_NO = "link=Serial Numbers"
    ID_CHKBOX_MAC_ENABLE_VIRTUAL = "id=cic-settings-mac-use-virtual"
    ID_BTN_MAC_ADD_CUSTOM_RANGE = "id=cic-settings-macs-add"
    ID_INPUT_ADD_CUSTOM_RANGE_FROM = "id=cic-settings-from-custom"
    ID_INPUT_ADD_CUSTOM_RANGE_TO = "id=cic-settings-to-custom"
    ID_INPUT_ADD_CUSTOM_RANGE_COUNT = "id=cic-settings-count-custom"
    ID_BTN_ADD_CUSTOM_RANGE = "id=cic-settings-guid-add"
    ID_CHKBOX_MAC_ENABLE = "id=cic-settings-edit-checkbox-id-range-VMAC-%s"
    ID_LABEL_ERROR_ADD_CUSTOM = "//label[@class='hp-error']"
    ID_BTN_CANCEL_MAC_CUSTOM_ADD = "id=cic-settings-guid-cancel"
    ID_BTN_AUTO_GENERATED_MAC = "id=cic-settings-macs-add-generated"
    ID_LABEL_AUTO_GENERATED_FROM = "id=cic-settings-from-generated"
    ID_LABEL_AUTO_GENERATED_TO = "id=cic-settings-to-generated"
    ID_BTN_GENERATE = "id=cic-settings-regenerate"
    ID_BTN_AUTO_GENERATE_ADD = "id=cic-settings-guid-add"
    ID_BTN_AUTO_GENERATE_ADD_PLUS = "id=cic-settings-guid-add-again"
    ID_BTN_AUTO_GENERATE_CANCEL = "id=cic-settings-guid-cancel"
    ID_TABLE_MAC_BASE = "xpath=//*[@id='cic-settings-edit-mac-table']"
    ID_CHKBOX_WWN_ENABLE_VIRTUAL = "id=cic-settings-wwn-use-virtual"
    ID_BTN_WWN_ADD_CUSTOM_RANGE = "id=cic-settings-wwns-add"
    ID_CHKBOX_WWN_ENABLE = "id=cic-settings-edit-checkbox-id-range-VWWN-%s"
    ID_BTN_AUTO_GENERATED_WWN = "id=cic-settings-wwns-add-generated"
    ID_TABLE_WWN_BASE = "xpath=//*[@id='cic-settings-edit-wwn-table']"
    ID_CHKBOX_SERIAL_NO_ENABLE_VIRTUAL = "id=cic-settings-sn-use-virtual"
    ID_CHKBOX_SERIAL_NO_ENABLE = "id=cic-settings-edit-checkbox-id-range-VSNN-%s"
    ID_BTN_SERIAL_NO_ADD_CUSTOM_RANGE = "id=cic-settings-sns-add"
    ID_BTN_AUTO_GENERATED_SERIAL_NO = "id=cic-settings-sns-add-generated"
    ID_TABLE_SERIAL_NO_BASE = "xpath=//*[@id='cic-settings-edit-sn-table']"
    ID_BTN_OK = "id=cic-settings-edit-ok"
    ID_EDIT_MESSAGE_SUMMARY = "xpath=//*[@id='hp-form-message']/div[@class='hp-form-message-summary']"
    ID_LABEL_CUSTOM_ADD_OVERLAPPING_ERROR = "xpath=//*[@id='cic-settings-error-field-custom-container']/label"

    # LDAP server objects
    ID_ELEMENT_AD_OR_LDAP_SELECTION = "xpath=//select[@id='fs-settings-authn-dir-type-select']/../div/div"
    ID_ELEMENT_LDAP_SELECT = "xpath=//select[@id='fs-settings-authn-dir-type-select']/../div/div"
    ID_ELEMENT_SELECT_OPTION = "xpath=//span[text()='%s']"
    ID_LABEL_DIRECTORY_SERVERS = "xpath=//label[.='Directory servers']"
    ID_ORGANIZATIONAL_UNIT = "xpath=.//*[@id='fs-settings-authn-organizational-unit-text']"
    ID_ADD_ORG_UNIT = "xpath=.//*[@id='fs-settings-auth-add-organizational-unit']"

    # Add alert notifications
    ID_LABEL_NOTIFICATIONS = "id=cic-notification-emailview-link"
    ID_LINK_EDIT_NOTIFICATIONS = "xpath=//a[@id='fs-settings-emailnotifications-panel-edit' and text()='Edit']"
    ID_LABEL_EDIT_NOTIFICATIONS = "xpath=//*[@id='hp-change-page-container']//span[text()='Edit Notifications']"
    ID_TXT_EDIT_NOTIFICATIONS_SENDER_EMAIL = "id=cic-notification-emailedit-senderemail"
    ID_TXT_EDIT_NOTIFICATIONS_SENDER_PASSWORD = "id=cic-notification-emailedit-senderemailpassword"
    ID_TXT_EDIT_NOTIFICATIONS_SENDER_SMTP_SERVER = "id=cic-notification-emailedit-smtpserver-servername"
    ID_TXT_EDIT_NOTIFICATIONS_SENDER_SMTP_PORT = "id=cic-notification-emailedit-smtpserver-serverport"
    ID_CHCKBOX_SMTP_OPTIONS = "xpath=//*[@id='cic-notification-emailedit-smtpoptions']"
    ID_ENABLE_ALTER_EMAIL = "//a[@id='cic-notification-alerts-enablebutton-hpToggle' and @class='hp-toggle hp-checked']"
    ID_BTN_ALERTS_ENABLED = "xpath=//*[@id='cic-notification-alerts-enablebutton-hpToggle']//li[@class='hp-on']"
    ID_BTN_OK_EDIT_NOTIFICATIONS = "id=cic-notification-emailedit-ok"

    # Add email alert filter
    ID_BTN_ADD_ALERT_EMAIL_FILTER = "id=cic-notification-alerts-addnotify-button"
    ID_LABEL_ADD_EMAIL_FILTER = "xpath=//*[@id='cic-notification-alert-add-header']/h1[text()='Add Alert Email Filter']"
    ID_BTN_EMAIL_FILTER = "id=cic-notification-addemail-enabled"
    ID_BTN_EMAIL_FILTER_ENABLED = "xpath=//*[@id='cic-notification-addemail-enabled-hpToggle']//li[@class='hp-on']"
    ID_BTN_EMAIL_FILTER_DISABLED = "xpath=//*[@id='cic-notification-addemail-enabled-hpToggle']//li[@class='hp-off']"
    ID_TXT_FILTER = "id=cic-notification-addemail-filter"
    ID_TXT_FILTER_EMAILADDRESSES = "id=cic-notification-addemail-emailaddresses"
    ID_BTN_ADD_EMAIL_FILTER = "cic-notification-alerts-add-button"
    ID_ADD_ALERT_EMAIL_NAME = "xpath=//*[@id='cic-notification-addemail-name']"

    # Factory reset
    ID_LINK_APPLIANCE = "link=Appliance"
    ID_ELEMENT_FACTORY_RESET = "id=hp-reset-factory-link"
    ID_FACTORY_RESET_PAGE_HEADER = "xpath=//div[@id='hp-factory-reset-dialog']/header/h1/span[text()='Factory Reset']"
    ID_FACTORY_RESET_WARNING = "xpath=//form[@id='hp-factory-reset-form']/div/div[@class='hp-dialog-notification']"
    ID_BTN_START_FACTORY_RESET = "id=hp-start-factory-reset"
    ID_CHECKBOX_CONFIRM_FACTORY_RESET = "id=hp-factory-reset-confirmation-checkbox"
    ID_BTN_CONFIRM_FACTORY_RESET = "id=hp-confirm-factory-reset"
    ID_BTN_CANCEL_FACTORY_RESET = "hp-cancel-factory-reset"
    ID_CHECKBOX_PREVENT_NEWORK_SETTINGS = "id=hp-factory-reset-network-checkbox"
    ID_ELEMENT_RESETTING_PROGRESS = "xpath=//div[text()='Resetting']/following::div[@id='factory-reset-progress']"
    ID_DISABLE_ACCESS_SUPPORT_ERROR = "xpath=//*[@id='hp-eula-support-access-warning-message']"

    # SNMP SETTINGS
    ID_LINK_SNMP_PANEL = "xpath=.//*[@id='cic-settings-snmp-panel']/div"
    ID_LABEL_SNMP_TRAP_DESTINATION_COUNT = "xpath=.//*[@id='cic-settings-snmp-overview-snmp']"
    ID_LINK_SNMP = "xpath=.//*[@id='cic-settings-snmp-panel']/div/header/h2/a"
    ID_LINK_EDIT_SNMP = "xpath=.//*[@id='cic-settings-snmp-panel-edit']"
    ID_LABEL_EDIT_SNMP_SETTINGS = "xpath=.//*[@id='hp-change-page-container']/section/header/h1/span"
    ID_LABEL_TRAP_DESTINATION = "xpath=.//*[@id='cic-settings-snmp-edit-form']/div[1]/fieldset/ol/li[2]"
    ID_BTN_ADD_TRAP_DESTINATION = "xpath=.//*[@id='cic-settings-snmp-edit-addtrapdestination']"
    ID_INPUT_TRAP_DESTINATION_ADD_TRAP_DESTINATION = "xpath=.//*[@id='cic-snmp-add-trapdestination']"
    ID_INPUT_PORT_ADD_TRAP_DESTINATION = "xpath=.//*[@id='cic-snmp-port']"
    ID_INPUT_COMMUNITY_STRING_ADD_TRAP_DESTINATION = "xpath=.//*[@id='cic-snmp-communitystring']"
    ID_BTN_ADD_ADD_TRAP_DESTINATION = "xpath=.//*[@id='cic-trapdestination-adddestination']"
    ID_BTN_OK_EDIT_SNMP_SETTINGS = "xpath=.//*[@id='cic-settings-snmp-edit-ok']"

    # Cluster Operations
    ID_BTN_APPLIANCE = "xpath=.//*[@id='fs-settings-appliance-panel']/div/header/h2/a"
    ID_BTN_ACTION = "xpath=//*[@id='hp-settings-actions']/label"
    ID_PAGE_TITLE = "xpath=.//*[@id='hp-settings-details-title']"
    ID_LABEL_STANDBY = "xpath=.//div[@id='fs-settings-status-map']//ol[@class='hp-related']"
    ID_LABEL_ACTIVE = "xpath=//div[@id='fs-settings-status-map']/div"
    ID_BTN_ACTIVATE_STANDBY = "xpath=//a[@id='hp-appliance-activate-standby-link']"
    ID_BTN_REMOVE_STANDBY = "xpath=.//*[@id='hp-appliance-remove-standby-link']"
    ID_BTN_ACTIVATE_STANDBY_OK = "xpath=//*[@id='hp-activate-standby-ok']"
    ID_BTN_ACTIVATE_STANDBY_CANCEL = "xpath=.//*[@id='hp-activate-standby-cancel']"
    ID_BTN_REMOVE_STANDBY_OK = "xpath=.//*[@id='hp-remove-standby-ok']"
    ID_BTN_REMOVE_STANDBY_CANCEL = "xpath=.//*[@id='hp-remove-standby-cancel']"
    ID_STANDBY_REMOVAL_TEXT = "xpath=.//*[@id='fs-settings-status-map']//div[@class='hp-detail'][contains(text(),'No standby')]"
    ID_BTN_UPDATE_APPLIANCE = "xpath=.//*[@id='hp-update-appliance-link']"
    ID_LABEL_WARNING_MSG = "xpath=.//*[@id='fs-settings-update-warning-no-backup']"
    ID_BTN_CANCEL = "xpath=.//*[@id='fs-settings-update-cancel']"
    ID_TEXT_STATUS = "xpath=.//*[@id='fs-settings-status-map']/ol//div[@class='hp-detail']"
    ID_LABEL_UPDATE = "xpath=.//*[@id='fs-settings-appliance-title']/h1"
    ID_TEXT_MESSAGE = "xpath=.//*[@id='fs-settings-update-warning-backup-ok']"

    # Oops Error Page
    ID_OOPS_PAGE_LABEL = "xpath=.//*[@id='hp-body-div']"
    ID_OOPS_PAGE_TITLE = "xpath=.//*[@id='fs-status-error-oops_title']"
    ID_OOPS_DETAILS_BTN = "xpath=.//*[@id='fs-status-error-authentication-dialog-link']"
    ID_INPUT_OOPS_DETAILS_USERNAME = "//input[@id='fs-error-summary-user-name']"
    ID_INPUT_OOPS_DETAILS_PASSWORD = "//input[@id='fs-error-summary-password']"
    ID_BTN_OPEN_ERRORSUMMARY_OK = "xpath=.//*[@id='fs-error-summary-credential-ok']"
    ID_ERRORSUMMARY_LABEL = "xpath=.//*[@id='fs-status-additional-details-collapse']/label/span"
    ID_SYSTEM_RESOURCES_LABEL = "xpath=.//*[@id='fs-status-error-precentage_resource']"
    ID_SYSTEMSUMMARY_TEXT = "xpath=.//*[@id='fs-status-error-listforsummary']"
    ID_ACTIONLIST_TEXT = "xpath=.//*[@id='fs-status-error-actionlist']"
    ID_ROOTCAUSE_TEXT = "xpath=.//*[@id='fs-status-error-rootcause']"

    ID_LINK_CREATESUPPORTDUMP = "xpath=.//*[@id='fs-status-error-support-dump-link_oops']"
    ID_INPUT_CREATESUPPORTDUMP_USERNAME = "//input[@id='hp-support-dump-user-name']"
    ID_INPUT_CREATESUPPORTDUMP_PASSWORD = "//input[@id='hp-support-dump-password']"
    ID_BUTTON_CREATESUPPORTDUMP_OK = "xpath=.//*[@id='hp-support-dump-credential-ok']"
    ID_TEXT_SUPPORTDUMP_PROGRESS_NOTIFICATION = "//*[contains(text(), 'Create support dump is in progress')]"
    ID_LINK_RESTART_ERRORPAGE = "//a[@id='fs-status-error-restart-link']"

    # Fixme installation details
    ID_DWNLD_FIXME_INSTALLATION_DETAILS = "//a[@id='fs-download-fixme-installation-details-link']"
