
ServerProfileTemplate_type = 'ServerProfileTemplateV5'
ServerProfile_type = 'ServerProfileV9'
FirmwareVersion = '2016.04.0'
FirmwareVersion2 = '2017.03.27.06'
Scope1_StoragePool_1 = "SPOOL:cpg-growth-limit-1TiB"
StoragePool1 = "SP:cpg-growth-limit-1TiB"
TemplateUri1 = 'ROOT:cpg-growth-limit-1TiB'
VolumeStorageSystemUri1 = "SSYS:ThreePAR-1"
ServerHardwareType = ['SHT:BL460c Gen8 1', 'SHT:BL660c Gen8 1']
Scope1_ServerHardware = ['SH:Encl1, bay 3', 'SH:Encl1, bay 4']
ServerHardware = ['Encl1, bay 3', 'Encl1, bay 4']


OVF3651_2_SPT = [{'name': 'OVF3651_2_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '',
                  'serverHardwareTypeUri': 'SHT:' + server_info['serverHardwareTypes'][0],
                  'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                  'connectionSettings': {'manageConnections': True,
                                         'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                         {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_2'},
                                                         {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                         {"id": 4, "name": "conn_prod1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"},
                                                         {"id": 5, "name": "conn_prod2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_2"}
                                                         ]
                                         },
                  'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                  'bootMode': None,
                  'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                  'bios': {'manageBios': False, 'overriddenSettings': []},
                  'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                  'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                  }
                 ]

OVF3651_5_SPT = [{'name': 'OVF3651_5_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '',
                  'serverHardwareTypeUri': 'SHT:' + server_info['serverHardwareTypes'][0],
                  'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                  'connectionSettings': {'manageConnections': True,
                                         'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                         {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_2'},
                                                         {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                         {"id": 4, "name": "conn_ns1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"},
                                                         {"id": 5, "name": "conn_ns2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_2"}
                                                         ]
                                         },
                  'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                  'bootMode': None,
                  'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                  'bios': {'manageBios': False, 'overriddenSettings': []},
                  'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                  'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                  }
                 ]
OVF3651_5_SP = [{'name': 'OVF3651_5_SP', 'serverHardwareUri': server_info['serverHardwares'][0], 'enclosureGroupUri': 'EG:enclgrp', "type": ServerProfile_type,
                 'connectionSettings': {
                     'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                     {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_2'},
                                     {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                     {"id": 4, "name": "conn_ns1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"},
                                     {"id": 5, "name": "conn_ns2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_2"}
                                     ]},
                 'serverProfileTemplateUri': 'SPT:OVF3651_5_SPT'
                 }
                ]

OVF3651_10_SPT = [{'name': 'OVF3651_10_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '',
                   'serverHardwareTypeUri': 'SHT:' + server_info['serverHardwareTypes'][0],
                   'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                   'connectionSettings': {'manageConnections': True,
                                          'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                          {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                                          {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                          {"id": 4, "name": "conn_ns1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"},
                                                          {"id": 5, "name": "conn_ns2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:net_3"}
                                                          ]
                                          },
                   'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                   'bootMode': None,
                   'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                   'bios': {'manageBios': False, 'overriddenSettings': []},
                   'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                   'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                   }
                  ]

OVF3651_13_SPT = [{'name': 'OVF3651_13_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '', 'serverHardwareTypeUri': ServerHardwareType[0], 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                   'connectionSettings': {'manageConnections': True,
                                          'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                          {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                                          {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                          {"id": 4, "name": "conn_prod1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"},
                                                          {"id": 5, "name": "conn_prod2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"}
                                                          ]
                                          },
                   'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                   'bootMode': None,
                   'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                   'bios': {'manageBios': False, 'overriddenSettings': []},
                   'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                   'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                   }
                  ]
OVF3651_13_SP = [{'name': 'OVF3651_13_SP', 'serverHardwareUri': ServerHardware[0], 'enclosureGroupUri': 'EG:enclgrp', "type": ServerProfile_type,
                  'connectionSettings': {
                      'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                      {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                      {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                      {"id": 4, "name": "conn_prod1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"},
                                      {"id": 5, "name": "conn_prod2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"}
                                      ]},
                  'serverProfileTemplateUri': 'SPT:OVF3651_13_SPT'
                  }
                 ]

OVF3651_13_SP_update = [{'name': 'OVF3651_13_SP', 'serverHardwareUri': ServerHardware[0], 'enclosureGroupUri': 'EG:enclgrp', "type": ServerProfile_type,
                         'connectionSettings': {
                             'connections': [{"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                             {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                             {"id": 4, "name": "conn_prod1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"},
                                             {"id": 5, "name": "conn_prod2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_2"},
                                             {"id": 6, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_2'}
                                             ]},
                         'serverProfileTemplateUri': 'SPT:OVF3651_13_SPT'
                         }
                        ]

OVF3651_14_SPT = [{'name': 'OVF3651_14_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '', 'serverHardwareTypeUri': ServerHardwareType[0], 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                   'connectionSettings': {'manageConnections': True,
                                          'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                          {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                                          {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                          {"id": 4, "name": "conn_prod1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"},
                                                          {"id": 5, "name": "conn_prod2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"}
                                                          ]
                                          },
                   'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                   'bootMode': None,
                   'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                   'bios': {'manageBios': False, 'overriddenSettings': []},
                   'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                   'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                   }
                  ]

OVF3651_14_SPT_update = [{'name': 'OVF3651_14_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '', 'serverHardwareTypeUri': ServerHardwareType[0], 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                          'connectionSettings': {'manageConnections': True,
                                                 'connections': [{"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                                                 {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                                 {"id": 4, "name": "conn_prod1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"},
                                                                 {"id": 5, "name": "conn_prod2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_2"},
                                                                 {"id": 6, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_2'}
                                                                 ]},
                          'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                          'bootMode': None,
                          'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                          'bios': {'manageBios': False, 'overriddenSettings': []},
                          'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                          'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                          }
                         ]

OVF3651_19_SPT = [{'name': 'OVF3651_19_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '', 'serverHardwareTypeUri': ServerHardwareType[0], 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                   'connectionSettings': {'manageConnections': True,
                                          'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                          {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                                          {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                          {"id": 4, "name": "conn_ns1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"},
                                                          {"id": 5, "name": "conn_ns2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"}
                                                          ]
                                          },
                   'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                   'bootMode': None,
                   'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                   'bios': {'manageBios': False, 'overriddenSettings': []},
                   'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                   'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                   }
                  ]
OVF3651_19_SP = [{'name': 'OVF3651_19_SP', 'serverHardwareUri': ServerHardware[0], 'enclosureGroupUri': 'EG:enclgrp', "type": ServerProfile_type,
                  'connectionSettings': {
                      'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                      {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                      {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                      {"id": 4, "name": "conn_ns1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"},
                                      {"id": 5, "name": "conn_ns2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"}
                                      ]},
                  'serverProfileTemplateUri': 'SPT:OVF3651_19_SPT'
                  }
                 ]

OVF3651_19_SP_update = [{'name': 'OVF3651_19_SP', 'serverHardwareUri': ServerHardware[0], 'enclosureGroupUri': 'EG:enclgrp', "type": ServerProfile_type,
                         'connectionSettings': {
                             'connections': [{"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                             {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                             {"id": 4, "name": "conn_ns1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"},
                                             {"id": 5, "name": "conn_ns2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_2"},
                                             {"id": 6, "name": "conn_ns22", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'NS:netset1_2'}
                                             ]},
                         'serverProfileTemplateUri': 'SPT:OVF3651_19_SPT'
                         }
                        ]

OVF3651_20_SPT = [{'name': 'OVF3651_20_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '', 'serverHardwareTypeUri': ServerHardwareType[0], 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                   'connectionSettings': {'manageConnections': True,
                                          'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                          {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                                          {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                          {"id": 4, "name": "conn_ns1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"},
                                                          {"id": 5, "name": "conn_ns2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"}
                                                          ]
                                          },
                   'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                   'bootMode': None,
                   'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                   'bios': {'manageBios': False, 'overriddenSettings': []},
                   'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                   'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                   }
                  ]

OVF3651_20_SPT_update = [{'name': 'OVF3651_20_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '', 'serverHardwareTypeUri': ServerHardwareType[0], 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                          'connectionSettings': {'manageConnections': True,
                                                 'connections': [{"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                                                 {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                                 {"id": 4, "name": "conn_ns1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_1"},
                                                                 {"id": 5, "name": "conn_ns2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "NS:netset1_2"},
                                                                 {"id": 6, "name": "conn_ns22", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'NS:netset1_2'}
                                                                 ]},
                          'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                          'bootMode': None,
                          'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                          'bios': {'manageBios': False, 'overriddenSettings': []},
                          'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                          'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                          }
                         ]

OVF3651_29_SPT = [{'name': 'OVF3651_29_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '', 'serverHardwareTypeUri': ServerHardwareType[0], 'enclosureGroupUri': 'EG:enclgrp', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                   'connectionSettings': {'manageConnections': True,
                                          'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                          {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                                          {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                          {"id": 4, "name": "conn_prod1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"},
                                                          {"id": 5, "name": "conn_prod2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"}
                                                          ]},
                   'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                   'bootMode': None,
                   'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                   'bios': {'manageBios': False, 'overriddenSettings': []},
                   'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                   'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                   }
                  ]
OVF3651_29_SPT_update = [{'name': 'OVF3651_29_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '', 'serverHardwareTypeUri': ServerHardwareType[0], 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                          'connectionSettings': {'manageConnections': True,
                                                 'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                                 {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_1'},
                                                                 {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_1"},
                                                                 {"id": 4, "name": "conn_prod1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"},
                                                                 {"id": 5, "name": "conn_prod2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_2"}
                                                                 ]},
                          'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                          'bootMode': None,
                          'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                          'bios': {'manageBios': False, 'overriddenSettings': []},
                          'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                          'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                          }
                         ]

OVF3651_34_SPT = [{'name': 'OVF3651_34_SPT', 'type': ServerProfileTemplate_type, 'serverProfileDescription': '', 'serverHardwareTypeUri': ServerHardwareType[0], 'enclosureGroupUri': 'EG:enclgrp', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual', 'description': '', 'affinity': 'Bay',
                   'connectionSettings': {'manageConnections': True,
                                          'connections': [{"id": 1, "name": "icsp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:icsp_1'},
                                                          {"id": 2, "name": "corp_conn", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": 'ETH:corp_2'},
                                                          {"id": 3, "name": "san_conn", "functionType": "FibreChannel", "portId": "Auto", "requestedMbps": "2500", "networkUri": "FC:san_2"},
                                                          {"id": 4, "name": "conn_prod1", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_1"},
                                                          {"id": 5, "name": "conn_prod2", "functionType": "Ethernet", "portId": "Auto", "requestedMbps": "2500", "networkUri": "ETH:production_2"}
                                                          ]},
                   'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'HardDisk', 'PXE']},
                   'bootMode': None,
                   'firmware': {'manageFirmware': False, 'firmwareBaselineUri': '', 'forceInstallFirmware': False, 'firmwareInstallType': None},
                   'bios': {'manageBios': False, 'overriddenSettings': []},
                   'hideUnusedFlexNics': True, 'iscsiInitiatorNameType': 'AutoGenerated',
                   'localStorage': {'sasLogicalJBODs': [], 'controllers': []}, 'sanStorage': {'hostOSType': 'VMware (ESXi)', 'manageSanStorage': False, 'volumeAttachments': []}
                   }
                  ]
