import copy
enclgrp = "EG-3enc"
ServerProfileTemplate_type = "ServerProfileTemplateV6"
ServerHardwareType = ["SHT:SY 480 Gen9 1", "SHT:SY 480 Gen9 2"]
osDeploymentPlans = ["Sneha_SPT_OSDP1", "Sneha_SPT_OSDP2", "Sneha_SPT_OSDP3", "Sneha_SPT_OSDP4"]
networks = {"iscsi": "i3s_deploy_nw",
            "mgmt": "mgmt_nw",
            "p_nw1": "private_nw1",
            "p_nw2": "private_nw2",
            "p_nw3": "private_nw3",
            "p_nw4": "private_nw4",
            "p_nw5": "private_nw5",
            "p_nw6": "private_nw6",
            "p_nw7": "private_nw7"}

user_credentials = {"Administrator": {"userName": "Administrator", "password": "admin123", "authLoginDomain": "LOCAL", "loginMsgAck": None},
                    "User2_InfraAdm": {"userName": "User2_InfraAdm", "password": "vsbqa*help", "authLoginDomain": "LOCAL", "loginMsgAck": None},
                    "User2_SPArch": {"userName": "User2_SPArch", "password": "vsbqa*help", "authLoginDomain": "LOCAL", "loginMsgAck": None},
                    "User2_SAdm": {"userName": "User2_SAdm", "password": "vsbqa*help", "authLoginDomain": "LOCAL", "loginMsgAck": None}}
scopes = [{"name": "Scope7",
           "description": "scopes for OVF2790",
           "type": "ScopeV3",
           "addedResourceUris": ["Osdp:" + osDeploymentPlans[0]],
           "removedResourceUris": []
           },
          {"name": "Scope8",
           "description": "scopes for OVF2790",
           "type": "ScopeV3",
           "addedResourceUris": ["Osdp:" + osDeploymentPlans[0]],
           "removedResourceUris": []
           },
          {"name": "Scope9",
           "description": "scopes for OVF2790",
           "type": "ScopeV3",
           "addedResourceUris": ["ETH:" + networks["mgmt"], "ETH:" + networks["iscsi"], "Osdp:" + osDeploymentPlans[0]],
           "removedResourceUris": []
           }
          ]
users = [{"type": "UserAndPermissions", "userName": "User2_SPArch", "fullName": "", "password": "vsbqa*help", "emailAddress": "", "officePhone": "", "mobilePhone": "", "enabled": True,
          "permissions": [{"roleName": "Read only", "scopeUri": None}]},
         {"type": "UserAndPermissions", "userName": "User2_InfraAdm", "fullName": "", "password": "vsbqa*help", "emailAddress": "", "officePhone": "", "mobilePhone": "", "enabled": True,
          "permissions": [{"roleName": "Read only", "scopeUri": None}]},
         {"type": "UserAndPermissions", "userName": "User2_SAdm", "fullName": "", "password": "vsbqa*help", "emailAddress": "", "officePhone": "", "mobilePhone": "", "enabled": True,
          "permissions": [{"roleName": "Read only", "scopeUri": None}]}
         ]

user_scope = {"Administrator": [],
              "User2_SPArch": ["Scope7", "Scope8", "Scope9"],
              "User2_SAdm": ["Scope9"], "User2_InfraAdm": ["Scope7", "Scope9"]}

update_users = [{"type": "UserAndPermissions", "userName": "User2_InfraAdm", "permissions": [{"roleName": "Infrastructure administrator", "scopeUri": "Scope7"}, {"roleName": "Infrastructure administrator", "scopeUri": "Scope9"}]},
                {"type": "UserAndPermissions", "userName": "User2_SPArch", "permissions": [{"roleName": "Server profile architect", "scopeUri": "Scope7"}, {"roleName": "Server profile architect", "scopeUri": "Scope8"}, {"roleName": "Server profile architect", "scopeUri": "Scope9"}]},
                {"type": "UserAndPermissions", "userName": "User2_SAdm", "permissions": [{"roleName": "Server administrator", "scopeUri": "Scope9"}]}]

ServerHardware660 = ["Encl1, bay 3"]

customAttribute = {"hostname": "sptNode",
                   "domain": "lab.local",
                   "password": "hpvse123"}

SPTPayloadTbird = {
    "type": ServerProfileTemplate_type,
    "name": "ServerProfileTemplate",
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareTypeUri": ServerHardwareType[0],
    "enclosureGroupUri": "EG:" + enclgrp, "affinity": "Bay",
    "hideUnusedFlexNics": True, "macType": "Virtual", "wwnType": "Virtual",
    "firmware": {"firmwareInstallType": None, "forceInstallFirmware": False,
                 "manageFirmware": False, "firmwareBaselineUri": None},
    "bootMode": {"manageMode": True, "pxeBootPolicy": "Auto", "mode": "UEFIOptimized", "secureBoot": "Unmanaged"},
    "osDeploymentSettings": {"osDeploymentPlanUri": osDeploymentPlans[0],
                             "osCustomAttributes": [{"name": "DomainName", "value": customAttribute["domain"], "constraints": "{\"helpText\":\"\"}", "type": "fqdn"},
                                                    {"name": "Hostname", "value": customAttribute["hostname"], "constraints": "{\"helpText\":\"\"}", "type": "hostname"},
                                                    {"name": "ManagementNIC.connectionid", "value": "3"},
                                                    {"name": "ManagementNIC.networkuri", "value": "ETH:" + networks["mgmt"]},
                                                    {"name": "ManagementNIC.constraint", "value": "auto"},
                                                    {"name": "ManagementNIC.vlanid", "value": "0"},
                                                    {"name": "ManagementNIC2.connectionid", "value": "4"},
                                                    {"name": "ManagementNIC2.networkuri", "value": "ETH:" + networks["mgmt"]},
                                                    {"name": "ManagementNIC2.constraint", "value": "auto"},
                                                    {"name": "ManagementNIC2.vlanid", "value": "0"},
                                                    {"name": "Password", "value": customAttribute["password"]},
                                                    {"name": "SSH", "value": "enabled", "constraints": "{\"options\":[\"enabled\"]}", "type": "option"}]
                             },
    "connectionSettings": {"manageConnections": True,
                           "connections": [{"id": 1,
                                            "name": "Deployment Network A", "functionType": "Ethernet",
                                            "portId": "Mezz 3:1-a", "requestedMbps": "2500",
                                            "networkUri": "ETH:" + networks["iscsi"],
                                            "requestedVFs": "Auto",
                                            "ipv4": {"ipAddressSource": "SubnetPool"},
                                            "boot": {"bootVolumeSource": "UserDefined",
                                                     "priority": "Primary",
                                                     "ethernetBootType": "iSCSI",
                                                     "iscsi": {"initiatorNameSource": "ProfileInitiatorName",
                                                               "firstBootTargetIp": None, "secondBootTargetIp": "",
                                                               "secondBootTargetPort": ""
                                                               }}},
                                           {"id": 2,
                                            "name": "Deployment Network B", "functionType": "Ethernet",
                                            "portId": "Mezz 3:2-a", "requestedMbps": "2500",
                                            "networkUri": "ETH:" + networks["iscsi"],
                                            "requestedVFs": "Auto",
                                            "ipv4": {"ipAddressSource": "SubnetPool"},
                                            "boot": {"bootVolumeSource": "UserDefined",
                                                     "priority": "Secondary",
                                                     "ethernetBootType": "iSCSI",
                                                     "iscsi": {"initiatorNameSource": "ProfileInitiatorName",
                                                               "firstBootTargetIp": None, "secondBootTargetIp": "",
                                                               "secondBootTargetPort": ""
                                                               }}},
                                           {"id": 3,
                                            "name": "", "functionType": "Ethernet",
                                            "portId": "Auto", "requestedMbps": "2500",
                                            "networkUri": "ETH:" + networks["mgmt"],
                                            "requestedVFs": "0", "ipv4": {},
                                            "boot": {"priority": "NotBootable", "iscsi": {}}},
                                           {"id": 4,
                                            "name": "", "functionType": "Ethernet",
                                            "portId": "Auto", "requestedMbps": "2500",
                                            "networkUri": "ETH:" + networks["mgmt"],
                                            "requestedVFs": "0", "ipv4": {},
                                            "boot": {"priority": "NotBootable", "iscsi": {}}}]},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False, "overriddenSettings": []},
    "localStorage": {"sasLogicalJBODs": [], "controllers": []},
    "sanStorage": None,
    "initialScopeUris": ["Scope:Scope9"]}

SPT_SBAC_OSDP_1 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_1[0]["name"] = "SPT_SBAC_OSDP_1"
SPT_SBAC_OSDP_1_EditScope = [{"name": "Scope9",
                              "description": "",
                              "type": "ScopeV3",
                              "addedResourceUris": ["Osdp:" + osDeploymentPlans[1], "Osdp:" + osDeploymentPlans[2], "Osdp:" + osDeploymentPlans[3]],
                              "removedResourceUris": []}]

SPT_SBAC_OSDP_1_ScopeResetToOldResources = [{"name": "Scope9",
                                             "description": "",
                                             "type": "ScopeV3",
                                             "addedResourceUris": [],
                                             "removedResourceUris": ["Osdp:" + osDeploymentPlans[1], "Osdp:" + osDeploymentPlans[2], "Osdp:" + osDeploymentPlans[3]]}]
SPT_SBAC_OSDP_1_Update_1 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_1_Update_1[0]["name"] = "SPT_SBAC_OSDP_1"
SPT_SBAC_OSDP_1_Update_1[0]["osDeploymentSettings"]["osDeploymentPlanUri"] = osDeploymentPlans[1]
SPT_SBAC_OSDP_1_Update_2 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_1_Update_2[0]["name"] = "SPT_SBAC_OSDP_1"
SPT_SBAC_OSDP_1_Update_2[0]["osDeploymentSettings"]["osDeploymentPlanUri"] = osDeploymentPlans[2]
SPT_SBAC_OSDP_1_Update_3 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_1_Update_3[0]["name"] = "SPT_SBAC_OSDP_1"
SPT_SBAC_OSDP_1_Update_3[0]["osDeploymentSettings"]["osDeploymentPlanUri"] = osDeploymentPlans[3]

SPT_SBAC_OSDP_2 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_2[0]["name"] = "SPT_SBAC_OSDP_2"
SPT_SBAC_OSDP_2[0]["initialScopeUris"] = ["Scope:Scope7", "Scope:Scope9"]
SPT_SBAC_OSDP_2_EditScope = [{"name": "Scope9",
                              "description": "",
                              "type": "ScopeV3",
                              "addedResourceUris": ["Osdp:" + osDeploymentPlans[1]],
                              "removedResourceUris": []},
                             {"name": "Scope7",
                              "description": "",
                              "type": "ScopeV3",
                              "addedResourceUris": ["Osdp:" + osDeploymentPlans[1]],
                              "removedResourceUris": []}]
SPT_SBAC_OSDP_2_ScopeResetToOldResources = [{"name": "Scope9",
                                             "description": "",
                                             "type": "ScopeV3",
                                             "addedResourceUris": [],
                                             "removedResourceUris": ["Osdp:" + osDeploymentPlans[1]]},
                                            {"name": "Scope7",
                                             "description": "",
                                             "type": "ScopeV3",
                                             "addedResourceUris": [],
                                             "removedResourceUris": ["Osdp:" + osDeploymentPlans[1]]}]
SPT_SBAC_OSDP_2_Update_1 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_2_Update_1[0]["name"] = "SPT_SBAC_OSDP_2"
SPT_SBAC_OSDP_2_Update_1[0]["osDeploymentSettings"]["osDeploymentPlanUri"] = osDeploymentPlans[1]
SPT_SBAC_OSDP_2_Update_1[0]["initialScopeUris"] = ["Scope:Scope8", "Scope:Scope9"]

SPT_SBAC_OSDP_3 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_3[0]["name"] = "SPT_SBAC_OSDP_3"
SPT_SBAC_OSDP_3[0]["initialScopeUris"] = ["Scope:Scope7", "Scope:Scope9"]
SPT_SBAC_OSDP_3_EditScope = [{"name": "Scope9",
                              "description": "",
                              "type": "ScopeV3",
                              "addedResourceUris": ["Osdp:" + osDeploymentPlans[2], "Osdp:" + osDeploymentPlans[3]],
                              "removedResourceUris": []},
                             {"name": "Scope7",
                              "description": "",
                              "type": "ScopeV3",
                              "addedResourceUris": ["Osdp:" + osDeploymentPlans[2], "Osdp:" + osDeploymentPlans[3]],
                              "removedResourceUris": []}]
SPT_SBAC_OSDP_3_ScopeResetToOldResources = [{"name": "Scope9",
                                             "description": "",
                                             "type": "ScopeV3",
                                             "addedResourceUris": [],
                                             "removedResourceUris": ["Osdp:" + osDeploymentPlans[2], "Osdp:" + osDeploymentPlans[3]]},
                                            {"name": "Scope7",
                                             "description": "",
                                             "type": "ScopeV3",
                                             "addedResourceUris": [],
                                             "removedResourceUris": ["Osdp:" + osDeploymentPlans[2], "Osdp:" + osDeploymentPlans[3]]}]
SPT_SBAC_OSDP_3_Update_1 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_3_Update_1[0]["name"] = "SPT_SBAC_OSDP_3"
SPT_SBAC_OSDP_3_Update_1[0]["initialScopeUris"] = ["Scope:Scope7", "Scope:Scope9"]
SPT_SBAC_OSDP_3_Update_1[0]["osDeploymentSettings"]["osDeploymentPlanUri"] = osDeploymentPlans[2]
SPT_SBAC_OSDP_3_Update_2 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_3_Update_2[0]["name"] = "SPT_SBAC_OSDP_3"
SPT_SBAC_OSDP_3_Update_2[0]["initialScopeUris"] = ["Scope:Scope7", "Scope:Scope9"]
SPT_SBAC_OSDP_3_Update_2[0]["osDeploymentSettings"]["osDeploymentPlanUri"] = osDeploymentPlans[3]

SPT_SBAC_OSDP_4 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_4[0]["name"] = "SPT_SBAC_OSDP_4"
SPT_SBAC_OSDP_4_EditScope = [{"name": "Scope9",
                              "description": "",
                              "type": "ScopeV3",
                              "addedResourceUris": [],
                              "removedResourceUris": ["Osdp:" + osDeploymentPlans[0]]}]
SPT_SBAC_OSDP_4_ScopeResetToOldResources = [{"name": "Scope9",
                                             "description": "",
                                             "type": "ScopeV3",
                                             "addedResourceUris": ["Osdp:" + osDeploymentPlans[0]],
                                             "removedResourceUris": []}]

SPT_SBAC_OSDP_5_EditScope_1 = [{"name": "Scope9",
                                "description": "",
                                "type": "ScopeV3",
                                "addedResourceUris": ["ETH:" + networks["iscsi"], "ETH:" + networks["mgmt"]],
                                "removedResourceUris": []}]
SPT_SBAC_OSDP_5 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_5[0]["name"] = "SPT_SBAC_OSDP_5"
SPT_SBAC_OSDP_5[0]["initialScopeUris"] = ["Scope:Scope7", "Scope:Scope9"]
SPT_SBAC_OSDP_5_EditScope_2 = [{"name": "Scope9",
                                "description": "",
                                "type": "ScopeV3",
                                "addedResourceUris": [],
                                "removedResourceUris": ["Osdp:" + osDeploymentPlans[0]]}]
SPT_SBAC_OSDP_5_ScopeResetToOldResources = [{"name": "Scope9",
                                             "description": "",
                                             "type": "ScopeV3",
                                             "addedResourceUris": ["Osdp:" + osDeploymentPlans[0]],
                                             "removedResourceUris": ["ETH:" + networks["iscsi"], "ETH:" + networks["mgmt"]],
                                             }]

SPT_SBAC_OSDP_6_EditScope_1 = [{"name": "Scope9",
                                "description": "",
                                "type": "ScopeV3",
                                "addedResourceUris": ["ETH:" + networks["mgmt"]],
                                "removedResourceUris": []},
                               {"name": "Scope7",
                                "description": "",
                                "type": "ScopeV3",
                                "addedResourceUris": ["ETH:" + networks["iscsi"], "ETH:" + networks["p_nw1"]],
                                "removedResourceUris": []}]
SPT_SBAC_OSDP_6 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_6[0]["name"] = "SPT_SBAC_OSDP_6"
SPT_SBAC_OSDP_6[0]["initialScopeUris"] = ["Scope:Scope7", "Scope:Scope9"]
SPT_SBAC_OSDP_6_EditScope_2 = [{"name": "Scope9",
                                "description": "",
                                "type": "ScopeV3",
                                "addedResourceUris": [],
                                "removedResourceUris": ["Osdp:" + osDeploymentPlans[0]]},
                               {"name": "Scope7",
                                "description": "",
                                "type": "ScopeV3",
                                "addedResourceUris": [],
                                "removedResourceUris": ["Osdp:" + osDeploymentPlans[0]]}]
SPT_SBAC_OSDP_6_Update_1 = [copy.deepcopy(SPTPayloadTbird)]
SPT_SBAC_OSDP_6_Update_1[0]["name"] = "SPT_SBAC_OSDP_6"
addConnection = {"id": 4,
                 "name": "", "functionType": "Ethernet",
                 "portId": "Auto", "requestedMbps": "2500",
                 "networkUri": "ETH:" + networks["p_nw1"],
                 "lagName": None, "mac": None,
                 "wwpn": None, "wwnn": None,
                 "requestedVFs": "0", "ipv4": {},
                 "boot": {"priority": "NotBootable", "iscsi": {}}}
SPT_SBAC_OSDP_6_Update_1[0]["connectionSettings"]["connections"].append(addConnection)
SPT_SBAC_OSDP_6_ScopeResetToOldResources = [{"name": "Scope9",
                                             "description": "",
                                             "type": "ScopeV3",
                                             "addedResourceUris": ["Osdp:" + osDeploymentPlans[0]],
                                             "removedResourceUris": ["ETH:" + networks["mgmt"]]},
                                            {"name": "Scope7",
                                             "description": "",
                                             "type": "ScopeV3",
                                             "addedResourceUris": ["Osdp:" + osDeploymentPlans[0]],
                                             "removedResourceUris": ["ETH:" + networks["iscsi"], "ETH:" + networks["p_nw1"]]}]
