ADMIN_CREDENTIALS = {'userName': 'Administrator', 'password': 'wpsthpvse1'}

SSH_SERVER = "16.114.210.116"
SSH_USERNAME = "root"
SSH_PASSWD = "hpvse1"
ROOT_DIR = "/root/automation_tools/fipsovs1860"
SETUP_SH = "ovs1860_setup.sh"
CLEANUP_SH = "ovs1860_cleanup.sh"

RESULT_DIR = "/tmp/ovs1860"
FOLDER = "OVF2072_OVS1860"
CA1_ALIASNAME = "testca1"
CA2_ALIASNAME = "testca2"
CA1_ORIG_DER_CRL_FILE = "origderca1.crl"
CA1_ORIG_PEM_CRL_FILE = "origpemca1.crl"
CA1_NEW_DER_CRL_FILE = "newderca1.crl"
CA1_NEW_PEM_CRL_FILE = "newpemca1.crl"
CA1_MAL_CRL_FILE = "malca1.crl"
CA2_ORIG_DER_CRL_FILE = "origderca2.crl"
CA2_ORIG_PEM_CRL_FILE = "origpemca2.crl"
CA2_NEW_DER_CRL_FILE = "newderca2.crl"
CA2_NEW_PEM_CRL_FILE = "newpemca2.crl"

ERR_MSG_WRONG_DETIAL = "CRL is not in valid X509 format."
ERR_MSG_WRONG_RECOMMAND = "Provide a valid X509 CRL and try again."
ERR_MSG_SIGNED_DETIAL = "Uploaded CRL is not signed by the specified CA."
ERR_MSG_SIGNED_RECOMMAND = "Supply CRL signed by the specified CA."
ERR_MSG_DUPLICATE_DETIAL = "Same CRL already exists on the appliance"
ERR_MSG_DUPLICATE_RECOMMAND = "Provide a different CRL."
ERR_MSG_OLDER_DETIAL = "newer CRL exists on the appliance."
ERR_MSG_OLDER_RECOMMAND = "Provide a newer CRL."
