*** Settings ***
Documentation    Add Logical Resources to OneView
Resource         ../resource.txt
Resource         ../plexxi.txt

Variables        ../Common.py
Variables        ../${DATA_FILE}

Suite Setup        QUAL Suite Setup    ${admin_credentials}
Suite Teardown     QUAL Suite Teardown


*** Test Cases ***
Add Logical Switch Groups
    [Documentation]    Add Logical Switch Group to OneView
    [Tags]    34    LSG
    Add Logical Switch Group From Variable   ${LSG}

Delete Existing LS Alerts
    [Documentation]    Deletes existing LS alerts.  Used to see if new alerts are created.
    [Tags]    34  DEL_LS_Alerts

    Delete All Alerts by Param    param=?filter=description like '*logical switch*'

Add Logical Switch
    [Documentation]    Add Logical Switches to OneView
    [Tags]    34    LS
    Add Logical Switch from variable   ${LS}

Get Logical Switch
    [Documentation]    GET LS, if not able then Fatal Error as Qual Test not worth executing.
    [Tags]    34    GET_LS
    ${uri} =    Get LS URI    ${LS_NAME}

    Run Keyword If    '${uri}'=='LS: ${LS_NAME} Not found'    Fatal Error    Logical Switch Not created, abort Qual run.

    Log    LS Uri for ${LS_NAME}: ${uri}    console=${CONSOLE}

    ${ls} =    Get Resource By Uri    ${uri}
    Run Keyword If    '${ls["status"]}'!='OK'    Run Keywords
    ...    Log    ${LS_NAME} status is ${ls["status"]}    level=WARN    console=${CONSOLE}
    ...    AND    Log    \t${LS_NAME} status is ${ls["status"]}    level=WARN    console=${CONSOLE}
    ...    AND    Log    \t\t${LS_NAME} status is ${ls["status"]}    level=WARN    console=${CONSOLE}

Confirm No LS Alerts
    [Documentation]    Confirm no alerts generated by creating the LS
    [Tags]    34    CONFIRM_NO_LS_ALERTS

    ${alerts} =    Get All Alerts by Param    param=?filter=description like '*logical switch*'

    :FOR    ${alert}    IN   @{alerts["members"]}
    \    Log    LS Alert: ${alert["urgency"]}    level=WARN    console=${CONSOLE}
    \    Log    description: ${alert["description"]}    level=WARN    console=${CONSOLE}
