#!/bin/bash
#######################################################################################
# Create vlans is used to create vlans and subnets on Linux TCS'.
# You must have the ethernet device name of the data/test network.
# CI-FIT Data Network: 172.x.x.x/255.255.255.0
#
# There are 2 sections available sections:
# - LOWER VLANS (STARTLOWERVLANS) - (ENDLOWERVLANS)  -- This is required
# - UPPER VLANS (STARTUPPERVLANS) - (ENDLOWERVLANS) -- Optional. Used if you have a gap in your
#   vlan ranges. Remarked out by default.
#
# USAGE:
# Enter the desired vlans (start/end) and starting subnet.
# Add entry to call this script in /etc/rc.local on TCS.
# Make sure the eth devices is set to start onboot.
# Set a static IP. Reboot the server.
# SYNTAX:
# /root/create_vlans <ETH#> <NUMBER_OF_VLANS>
# EXAMPLE:
# /root/create_vlans ens224 1000
#######################################################################################

# Set pipefail so that a unsuccessful multi-command pipe return code can be acknowledged
set -o pipefail

# NIC = data ethernet device name, VLANS = Just set to 1000
NIC=$1
VLANS=$2

# Lower VLANs/Subnets
STARTLOWERVLANS=1
ENDLOWERVLANS=500

# Upper VLANs/Subnets
#STARTUPPERVLANS=3000
#ENDUPPERVLANS=3010



if [ "$VLANS" = "" -o "$NIC" = "" ] ; then
	echo "usage: ./create_vlans <interface> <number of vlans>"
	exit
else
	cat /proc/net/dev | grep $NIC
	if [ $? -ne 0 ]; then
		echo "Interface $NIC is not in proc so exiting..."
		exit
	fi
fi

#################### LOW Subnets/vlans (STARTLOWERVLANS) - (ENDLOWERVLANS)
echo "Interface entered is: $NIC"
echo "Number entered is: $ENDLOWERVLANS"
FIRST_OCTET=172
SECOND_OCTET=16
THIRD_OCTET=1
FOURTH_OCTET=1

for vlan in $(eval echo {$STARTLOWERVLANS..$ENDLOWERVLANS})
do
	mod=`expr $vlan % 128`
	if [ $mod -eq 0 ]; then
		vconfig add $NIC $vlan
		ifconfig $NIC.$vlan $FIRST_OCTET.$SECOND_OCTET.$THIRD_OCTET.$FOURTH_OCTET netmask 255.255.255.0 up
		THIRD_OCTET=1
		let SECOND_OCTET=SECOND_OCTET+1
	else
		vconfig add $NIC $vlan
		ifconfig $NIC.$vlan $FIRST_OCTET.$SECOND_OCTET.$THIRD_OCTET.$FOURTH_OCTET netmask 255.255.255.0 up  
		let THIRD_OCTET=THIRD_OCTET+1	
	fi

done	

#################### High Subnets/vlans (STARTUPPERVLANS) - (ENDUPPERVLANS)
#echo "Interface entered is: $NIC"
#echo "Number entered is: $ENDUPPERVLANS"
#
#FIRST_OCTET=172
#SECOND_OCTET=24
#THIRD_OCTET=56
#FOURTH_OCTET=1
#
#for vlan in $(eval echo {$STARTUPPERVLANS..$ENDUPPERVLANS})
#do
#	mod=`expr $vlan % 128`
#	if [ $mod -eq 0 ]; then
#		vconfig add $NIC $vlan
#		ifconfig $NIC.$vlan $FIRST_OCTET.$SECOND_OCTET.$THIRD_OCTET.$FOURTH_OCTET netmask 255.255.255.0 up
#		THIRD_OCTET=1
#		let SECOND_OCTET=SECOND_OCTET+1
#	else
#		vconfig add $NIC $vlan
#		ifconfig $NIC.$vlan $FIRST_OCTET.$SECOND_OCTET.$THIRD_OCTET.$FOURTH_OCTET netmask 255.255.255.0 up  
#		let THIRD_OCTET=THIRD_OCTET+1	
#	fi
#
#done	
