#!/bin/bash

# VARS
NAME=$(basename $0)
MONTH=`date | awk '{print $2}'`
DAY=`date | awk '{print $3}'`
YEAR=`date | awk '{print $6}'`
TIME_OF_DAY=`date | awk '{print $4}'`
TEST_RUN="$MONTH"_"$DAY"_"$YEAR"_"$TIME_OF_DAY"
LOG_DIR="/tmp/$NAME/$TEST_RUN"

# FUNCTIONS:
function usage() {
	  echo "$0"
	  echo
	  echo "NAME"
	  echo "$0 - run sequential ping using IP addresses in HA file."
	  echo "Syntax:"
	  echo "        $0 [<HA File>]"
	  echo "        $0 [-q <Query String>] [-f <HA File> | <HA File>]"
          echo "Examples:"
	  echo "        $0 -q VCUZZZ0011 HA_ipaddr.conf"
	  echo "        $0 HA_ipaddr.conf"
	  echo "        $0 -q VCUZZZ0011 -f HA_ipaddr.conf"
}

IPADDR_FILE=$(echo ${@:${#@}})

# Validate command line parameters
while getopts ":q:h:f:" opt; do
    case ${opt} in
        q)
          QUERY_STRING=$OPTARG;
          ;;
	f)
	  IPADDR_FILE=$OPTARG;
	  ;;
        h|*)
          usage;
          exit -1;
          ;;
    esac
done
shift $((OPTIND -1))

# Check for command line parameters
if [ -z "$IPADDR_FILE" ]; then
    usage
    exit -1
fi

# Make log directories
mkdir -p "$LOG_DIR"

# Grep for ips to ping based on userdefined string/value or grep all ips in HA file.  
if [ -z $QUERY_STRING ]; then
	IPADDRS=(`cat $IPADDR_FILE | grep -o -E '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}'`)
else
	echo "Grepping for $QUERY_STRING in $IPADDR_FILE."
	IPADDRS=(`cat $IPADDR_FILE | grep $QUERY_STRING | grep -o -E '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}'`)
fi

# Set count vars and enter loop
nPASS=0
nFAIL=0

if [ -e /root/stop_ping ]
then
	rm -Rf /root/stop_ping
fi
# While loop to run until /root/stop_ping file exists:
echo "##########################################################################"
echo "To stop the pings open a second terminal and type: touch /root/stop_pings "
echo "Sleeping 5 seconds before starting the pings."
echo "##########################################################################"
sleep 5s
while [ ! -e /root/stop_ping ]
do
	for ip in "${IPADDRS[@]}"
	do
	        ping $ip -c 1 >/dev/null 2>&1
	        if [ $? -eq 0 ] ; then
	                nPASS=`expr $nPASS + 1`
	                echo "`date`: IP address $ip is reachable" 2>&1 | tee -a $LOG_DIR/$NAME.log
	        else
	                nFAIL=`expr $nFAIL + 1`
			device=`cat $IPADDR_FILE | grep -F $ip`
	                echo "`date`: IP address $device is NOT reachable" 2>&1 | tee -a $LOG_DIR/$NAME.log
	        fi
	done
	echo "checking for /root/stop_ping"

done
	
echo
echo "Total number of PASSES = $nPASS"
echo "Total number of FAILURES = $nFAIL"
echo

