#!/bin/bash

VCM_ACTIVE=0
while [ $VCM_ACTIVE -eq 0 ]; do
	echo "Start Time: `date`" >> $2
	if [ "$3" = "" ];then
		ping -c 60 $1 2>/dev/null >> $2 
	else
      		ping -c 60 -r -I $3 $1 2>/dev/null >> $2 
	fi
	echo "End Time: `date`" >> $2
	if [ -a vcm_active ]; then	
		VCM_ACTIVE=1
	fi
done


