#!/bin/bash

NAME=$0
if [ $# -eq 1 ]; then
	IPADDR_FILE=$1
else
	echo "usage: $0 </path to conf file>"
	echo "example:  $0 HA_ipaddr.conf"
	exit
fi

if [ ! -f $IPADDR_FILE ]; then
	echo "ERROR: The $IPADDR_FILE file is not found." 
	exit
fi

PING_SCRIPT="./ping_ip"
if [ ! -f $PING_SCRIPT ]; then
	echo "ERROR: The $PING_SCRIPT file is not found." 
	exit
fi

MONTH=`date | awk '{print $2}'`
DAY=`date | awk '{print $3}'`
YEAR=`date | awk '{print $6}'`
TIME_OF_DAY=`date | awk '{print $4}'`
TEST_RUN="$MONTH"_"$DAY"_"$YEAR"_"$TIME_OF_DAY"
LOG_DIR="/tmp/$NAME/$TEST_RUN"

mkdir -p "$LOG_DIR"

IPADDRS=(`cat $IPADDR_FILE | grep -o -E '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}'`)
for ip in ${IPADDRS[@]} 
do
	$PING_SCRIPT $ip "$LOG_DIR/$ip.log" &
done


