"""
 data variable file for import test case in C7K Setup
"""
ov_ip = '10.1.2.111'
ov_credentials = {'userName': 'Administrator', 'password': 'admin123'}
vol_storage_sys_uri = "SSYS:CLRM-QA-VSA"

server_hardware_list = ["EB1301-BOTTOM, bay 3", "EB1301-BOTTOM, bay 2"]
server_hardware_list_1 = ["EB1301-BOTTOM, bay 3", "EB1301-BOTTOM, bay 2"]

server_hardware_list_different_Hw = ["EB1301-BOTTOM, bay 1", "<provide_different_HW_Type>"]

target_vcenter = {'vc': '10.1.0.38', 'user': 'Administrator@vsphere.local', 'password': 'Orion!@#123',
                  'datacenter': 'Sushil_DC', 'cluster': 'Test Cluster'
                  }

target_vcenter_ipv6 = {'vc': 'fd17:3fc6:e357:6e4b:0:0:0:23', 'user': 'Administrator@vsphere.local', 'password': 'Welcome123#',
                       'datacenter': 'Sushil_DC', 'cluster': 'Import_Cluster_C7K'
                       }

mgmt_net = {'ips': ['10.1.1.231', '10.1.1.232', '10.1.1.233', '10.1.1.234', '10.1.1.235', '10.1.1.236'],
            'netmask': '255.255.252.0', 'gw': '10.1.0.1'
            }

mgmt_net_ipv6 = {'ips': ['fd17:3fc6:e357:6e4b:0:0:0:51', 'fd17:3fc6:e357:6e4b:0:0:0:52', 'fd17:3fc6:e357:6e4b:0:0:0:53',
                         'fd17:3fc6:e357:6e4b:0:0:0:54', 'fd17:3fc6:e357:6e4b:0:0:0:55', 'fd17:3fc6:e357:6e4b:0:0:0:56',
                         'fd17:3fc6:e357:6e4b:0:0:0:57', 'fd17:3fc6:e357:6e4b:0:0:0:58', 'fd17:3fc6:e357:6e4b:0:0:0:59'],
                 'netmask': '64'
                 }

ipv6 = "False"

if ipv6 == "True":
    target_vcenter = target_vcenter_ipv6
    mgmt_net = mgmt_net_ipv6

mgmt_nic = "vmnic2"

# parameters for Autodeploy
deploy_configs = {
    "deployment_vc": {'vc': '10.1.47.13', 'user': 'Administrator@vsphere.local', 'password': 'Welcome123#',
                      'datacenter': 'Deploy_DC', 'cluster': 'test_cluster1'
                      },
    "add_rule": "E:\\Shares\\testRepo\prod\\fusion\\tests\\clrm\\esxi_autodeploy\\Add_autodeploy_rule.ps1",
    "remove_rule": "E:\\Shares\\testRepo\prod\\fusion\\tests\\clrm\\esxi_autodeploy\\Remove_autodeploy_rule.ps1",
                "esxi_config": {'version': '6.7',
                                "depot_path": "E:\\Shares\\autodeploy\\HPE-ESXi-6.7.0-Update1-Gen9plus-670.U1.10.3.5.12.zip",
                                'image': "HPE-ESXi-6.7.0-Update1-Gen9plus-670.U1.10.3.5.12",
                                'profile': 'ESXI_67_C7k_G9',
                                'user': 'root',
                                'password': "Welcome123#"
                                }
}

# Parameters for ESXI Deployment via CPT tool
esxi_cred = {'user': 'root',
             'password': "HPvse123$"
             }

cpt_host = {"host": "10.1.0.34",
            "user": "root",
            "password": "iso*help"}

ESXi65 = {"os_name": "ESXi65x64",
          "os_repo": "http://10.1.0.34/iso/vmware/6.5/VMware-ESXi-6.5.0-Update2-8294253-HPE-Gen9plus-650.U2.10.2.0.14-May2018.iso",
          "deployment_network": "net_147",
          "ilo_user": "iloadmin",
          "ilo_pass": "admin123"}

ESXi67 = {"os_name": "ESXi67",
          "os_repo": "http://10.1.0.34/iso/vmware/6.7/VMware-VCSA-all-6.7.0-U1-10244745.iso",
          "deployment_network": "net_147",
          "ilo_user": "iloadmin",
          "ilo_pass": "admin123"}


EG_122 = 'EG-3enc'

virtualSwitchConfigPolicy = {
    "manageVirtualSwitches": True,
    "configurePortGroups": True
}

hypervisorClusterSettings = {
    "type": "Vmware",
    "drsEnabled": False,
    "haEnabled": False,
    "multiNicVMotion": False,
    "virtualSwitchType": "Standard"
}
EG = 'EG-ENC1301Mid'

SPT_Type = 'ServerProfileTemplateV6'
SP_Type = 'ServerProfileV10'
HCP_Type = 'HypervisorClusterProfileV3'
Server_hardware_type = ['SHT:BL460c Gen9 1', 'SHT:BL460c Gen9 2']

# SPT Import for AutoDeploy
SPT_Import = [
    {
        'name': 'OVTC29141_SPT', 'type': SPT_Type,
        'serverProfileDescription': '', 'serverHardwareTypeUri': Server_hardware_type[0],
        'enclosureGroupUri': 'EG:' + EG, 'affinity': 'Bay',
        'hideUnusedFlexNics': True,
        'macType': 'Virtual',
        'wwnType': 'Virtual',
        'serialNumberType': 'Virtual',
        'iscsiInitiatorNameType': 'AutoGenerated',
        'osDeploymentSettings': None,
        'firmware': {'complianceControl': 'Checked', 'manageFirmware': False, 'forceInstallFirmware': False},
        'connectionSettings': {'complianceControl': 'Checked', 'manageConnections': True,
                               'connections': [
                                   {'id': 1, 'name': 'net_147_1', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Flb 1:1-a', 'boot': {"priority": "Primary", "ethernetBootType": "PXE"}},
                                   {'id': 2, 'name': 'net_147_2', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Auto', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 3, 'name': 'mgmt1', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Auto', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 4, 'name': 'mgmt2', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Auto', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 5, 'name': 'vmotion1', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Auto', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 6, 'name': 'vmotion2', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Auto', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 7, 'name': 'iscsi1', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Auto', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 8, 'name': 'iscsi2', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Auto', 'boot': {'priority': 'NotBootable'}}
                               ]
                               },
        'bootMode': {'complianceControl': 'Checked', 'manageMode': True, 'mode': 'UEFIOptimized', 'pxeBootPolicy': 'Auto', 'secureBoot': 'Unmanaged'},
        'boot': {'complianceControl': 'Checked', 'manageBoot': True, 'order': ['HardDisk']},
        'bios': {'complianceControl': 'Unchecked', 'manageBios': False, 'overriddenSettings': []},
        'localStorage': {'complianceControl': 'Unchecked', 'sasLogicalJBODs': [], 'controllers': []},
        'sanStorage': {'complianceControl': 'Checked', 'manageSanStorage': True, 'hostOSType': 'VMware (ESXi)',
                       'sanSystemCredentials': [{'storageSystemUri': vol_storage_sys_uri, 'chapLevel': 'MutualChap'}],
                       'volumeAttachments': [
                           {'id': 1, 'lun': None, 'lunType': 'Auto',
                            'storagePaths': [{'connectionId': 8, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []},
                                             {'connectionId': 7, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []}
                                             ],
                            'volumeUri': 'v:vsa_vol1', 'volumeStorageSystemUri': vol_storage_sys_uri, 'bootVolumePriority': 'NotBootable'
                            },
                           {'id': 2, 'lun': None, 'lunType': 'Auto',
                            'storagePaths': [{'connectionId': 8, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []},
                                             {'connectionId': 7, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []}
                                             ],
                            'volumeUri': 'v:vsa_vol2', 'volumeStorageSystemUri': vol_storage_sys_uri, 'bootVolumePriority': 'NotBootable'
                            }
                       ]
                       }
    },
    {
        'name': 'OVTC29143_SPT', 'type': SPT_Type,
        'serverProfileDescription': '', 'serverHardwareTypeUri': Server_hardware_type[0],
        'enclosureGroupUri': 'EG:' + EG, 'affinity': 'Bay',
        'hideUnusedFlexNics': True,
        'macType': 'Virtual',
        'wwnType': 'Virtual',
        'serialNumberType': 'Virtual',
        'iscsiInitiatorNameType': 'AutoGenerated',
        'osDeploymentSettings': None,
        'firmware': {'complianceControl': 'Checked', 'manageFirmware': False, 'forceInstallFirmware': False},
        'connectionSettings': {'complianceControl': 'Checked', 'manageConnections': True,
                               'connections': [
                                   {'id': 1, 'name': 'net_147_1', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Flb 1:1-a', 'boot': {"priority": "Primary", "ethernetBootType": "PXE"}},
                                   {'id': 2, 'name': 'net_147_2', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Flb 1:2-a', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 3, 'name': 'mgmt1', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Flb 1:1-b', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 4, 'name': 'mgmt2', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Flb 1:2-b', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 5, 'name': 'vmotion1', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Flb 1:1-c', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 6, 'name': 'vmotion2', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Flb 1:2-c', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 7, 'name': 'iscsi1', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Flb 1:1-d', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 8, 'name': 'iscsi2', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Flb 1:2-d', 'boot': {'priority': 'NotBootable'}}
                               ]
                               },
        'bootMode': {'complianceControl': 'Checked', 'manageMode': True, 'mode': 'UEFIOptimized', 'pxeBootPolicy': 'Auto', 'secureBoot': 'Unmanaged'},
        'boot': {'complianceControl': 'Checked', 'manageBoot': True, 'order': ['HardDisk']},
        'bios': {'complianceControl': 'Unchecked', 'manageBios': False, 'overriddenSettings': []},
        'localStorage': {'complianceControl': 'Unchecked', 'sasLogicalJBODs': [], 'controllers': []},
        'sanStorage': {'complianceControl': 'Checked', 'manageSanStorage': True, 'hostOSType': 'VMware (ESXi)',
                       'sanSystemCredentials': [{'storageSystemUri': vol_storage_sys_uri, 'chapLevel': 'MutualChap'}],
                       'volumeAttachments': [
                           {'id': 1, 'lun': None, 'lunType': 'Auto',
                            'storagePaths': [{'connectionId': 8, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []},
                                             {'connectionId': 7, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []}
                                             ],
                            'volumeUri': 'v:vsa_vol1', 'volumeStorageSystemUri': vol_storage_sys_uri, 'bootVolumePriority': 'NotBootable'
                            }
                       ]
                       }
    },
    {
        'name': 'OVTC29144_SPT', 'type': SPT_Type,
        'serverProfileDescription': '', 'serverHardwareTypeUri': Server_hardware_type[0],
        'enclosureGroupUri': 'EG:' + EG, 'affinity': 'Bay',
        'hideUnusedFlexNics': True,
        'macType': 'Virtual',
        'wwnType': 'Virtual',
        'serialNumberType': 'Virtual',
        'iscsiInitiatorNameType': 'AutoGenerated',
        'osDeploymentSettings': None,
        'firmware': {'complianceControl': 'Checked', 'manageFirmware': False, 'forceInstallFirmware': False},
        'connectionSettings': {'complianceControl': 'Checked', 'manageConnections': True,
                               'connections': [
                                   {'id': 1, 'name': 'net_147_1', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Flb 1:1-a', 'boot': {"priority": "Primary", "ethernetBootType": "PXE"}},
                                   {'id': 2, 'name': 'net_147_2', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Flb 1:2-a', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 3, 'name': 'mgmt1', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Flb 1:1-b', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 4, 'name': 'mgmt2', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Flb 1:2-b', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 5, 'name': 'vmotion1', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Flb 1:1-c', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 6, 'name': 'vmotion2', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Flb 1:2-c', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 7, 'name': 'iscsi1', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Flb 1:1-d', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 8, 'name': 'iscsi2', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Flb 1:2-d', 'boot': {'priority': 'NotBootable'}}
                               ]
                               },
        'bootMode': {'complianceControl': 'Checked', 'manageMode': True, 'mode': 'UEFIOptimized', 'pxeBootPolicy': 'Auto', 'secureBoot': 'Unmanaged'},
        'boot': {'complianceControl': 'Checked', 'manageBoot': True, 'order': ['HardDisk']},
        'bios': {'complianceControl': 'Unchecked', 'manageBios': False, 'overriddenSettings': []},
        'localStorage': {'complianceControl': 'Unchecked', 'sasLogicalJBODs': [], 'controllers': []},
        'sanStorage': {'complianceControl': 'Checked', 'manageSanStorage': True, 'hostOSType': 'VMware (ESXi)',
                       'sanSystemCredentials': [{'storageSystemUri': vol_storage_sys_uri, 'chapLevel': 'MutualChap'}],
                       'volumeAttachments': [
                           {'id': 1, 'lun': None, 'lunType': 'Auto',
                            'storagePaths': [{'connectionId': 8, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []},
                                             {'connectionId': 7, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []}
                                             ],
                            'volumeUri': 'v:vsa_vol1', 'volumeStorageSystemUri': vol_storage_sys_uri, 'bootVolumePriority': 'NotBootable'
                            }
                       ]
                       }
    },
    {
        'name': 'OVTC29145_SPT', 'type': SPT_Type,
        'serverProfileDescription': '', 'serverHardwareTypeUri': Server_hardware_type[0],
        'enclosureGroupUri': 'EG:' + EG, 'affinity': 'Bay',
        'hideUnusedFlexNics': True,
        'macType': 'Virtual',
        'wwnType': 'Virtual',
        'serialNumberType': 'Virtual',
        'iscsiInitiatorNameType': 'AutoGenerated',
        'osDeploymentSettings': None,
        'firmware': {'complianceControl': 'Checked', 'manageFirmware': False, 'forceInstallFirmware': False},
        'connectionSettings': {'complianceControl': 'Checked', 'manageConnections': True,
                               'connections': [
                                   {'id': 1, 'name': 'net_147_1', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Flb 1:1-a', 'boot': {"priority": "Primary", "ethernetBootType": "PXE"}},
                                   {'id': 2, 'name': 'net_147_2', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Flb 1:2-a', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 3, 'name': 'mgmt1', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Flb 1:1-b', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 4, 'name': 'mgmt2', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Flb 1:2-b', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 5, 'name': 'vmotion1', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Flb 1:1-c', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 6, 'name': 'vmotion2', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Flb 1:2-c', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 7, 'name': 'iscsi1', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Flb 1:1-d', 'boot': {'priority': 'NotBootable'}},
                                   {'id': 8, 'name': 'iscsi2', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Flb 1:2-d', 'boot': {'priority': 'NotBootable'}}
                               ]
                               },
        'bootMode': {'complianceControl': 'Checked', 'manageMode': True, 'mode': 'UEFIOptimized', 'pxeBootPolicy': 'Auto', 'secureBoot': 'Unmanaged'},
        'boot': {'complianceControl': 'Checked', 'manageBoot': True, 'order': ['HardDisk']},
        'bios': {'complianceControl': 'Unchecked', 'manageBios': False, 'overriddenSettings': []},
        'localStorage': {'complianceControl': 'Unchecked', 'sasLogicalJBODs': [], 'controllers': []},
        'sanStorage': {'complianceControl': 'Checked', 'manageSanStorage': True, 'hostOSType': 'VMware (ESXi)',
                       'sanSystemCredentials': [{'storageSystemUri': vol_storage_sys_uri, 'chapLevel': 'MutualChap'}],
                       'volumeAttachments': [
                           {'id': 1, 'lun': None, 'lunType': 'Auto',
                            'storagePaths': [{'connectionId': 8, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []},
                                             {'connectionId': 7, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []}
                                             ],
                            'volumeUri': 'v:vsa_vol1', 'volumeStorageSystemUri': vol_storage_sys_uri, 'bootVolumePriority': 'NotBootable'
                            }
                       ]
                       }
    }
]

# SPT import payload for CPT
SPT_Import_cpt = [{
    'name': 'OVTC29141_SPT', 'type': SPT_Type,
    'serverProfileDescription': '', 'serverHardwareTypeUri': Server_hardware_type[0],
    'enclosureGroupUri': 'EG:' + EG, 'affinity': 'Bay',
    'hideUnusedFlexNics': True,
    'macType': 'Virtual',
    'wwnType': 'Virtual',
    'serialNumberType': 'Virtual',
    'iscsiInitiatorNameType': 'AutoGenerated',
    'osDeploymentSettings': None,
    'firmware': {'complianceControl': 'Checked', 'manageFirmware': False, 'forceInstallFirmware': False},
    'connectionSettings': {'complianceControl': 'Checked', 'manageConnections': True,
                           'connections': [
                               {'id': 1, 'name': 'net_147_1', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Flb 1:1-a', 'requestedVFs': 'Auto', 'requestedMbps': '2500', 'boot': {'priority': 'NotBootable'}},
                               {'id': 2, 'name': 'net_147_2', 'functionType': 'Ethernet', 'networkUri': 'ETH:net_147', 'portId': 'Auto', 'requestedVFs': 'Auto', 'requestedMbps': '2500', 'boot': {'priority': 'NotBootable'}},
                               {'id': 3, 'name': 'mgmt1', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Auto', 'requestedVFs': 'Auto', 'requestedMbps': '2500', 'boot': {'priority': 'NotBootable'}},
                               {'id': 4, 'name': 'mgmt2', 'functionType': 'Ethernet', 'networkUri': 'ETH:mgmt_nw', 'portId': 'Auto', 'requestedVFs': 'Auto', 'requestedMbps': '2500', 'boot': {'priority': 'NotBootable'}},
                               {'id': 5, 'name': 'vmotion1', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Auto', 'requestedVFs': 'Auto', 'requestedMbps': '2500', 'boot': {'priority': 'NotBootable'}},
                               {'id': 6, 'name': 'vmotion2', 'functionType': 'Ethernet', 'networkUri': 'ETH:vmotion_nw', 'portId': 'Auto', 'requestedVFs': 'Auto', 'requestedMbps': '2500', 'boot': {'priority': 'NotBootable'}},
                               {'id': 7, 'name': 'iscsi1', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Auto', 'requestedVFs': 'Auto', 'requestedMbps': '2500', 'boot': {'priority': 'NotBootable'}},
                               {'id': 8, 'name': 'iscsi2', 'functionType': 'Ethernet', 'networkUri': 'ETH:iscsi_nw', 'portId': 'Auto', 'requestedVFs': 'Auto', 'requestedMbps': '2500', 'boot': {'priority': 'NotBootable'}}
                           ]
                           },
    'bootMode': {'complianceControl': 'Checked', 'manageMode': True, 'mode': 'UEFIOptimized', 'pxeBootPolicy': 'Auto', 'secureBoot': 'Unmanaged'},
    'boot': {'complianceControl': 'Checked', 'manageBoot': True, 'order': ['HardDisk']},
    'bios': {'complianceControl': 'Unchecked', 'manageBios': False, 'overriddenSettings': []},
    'localStorage': {'complianceControl': 'Unchecked', 'sasLogicalJBODs': [], 'controllers': []},
    'sanStorage': {'complianceControl': 'Checked', 'manageSanStorage': True, 'hostOSType': 'VMware (ESXi)',
                   'sanSystemCredentials': [{'storageSystemUri': vol_storage_sys_uri, 'chapLevel': 'MutualChap'}],
                   'volumeAttachments': [
                       {'id': 1, 'lun': None, 'lunType': 'Auto',
                        'storagePaths': [{'connectionId': 8, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []},
                                         {'connectionId': 7, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []}
                                         ],
                        'volumeUri': 'v:vsa_vol1', 'volumeStorageSystemUri': vol_storage_sys_uri, 'bootVolumePriority': 'NotBootable'
                        },
                       {'id': 1, 'lun': None, 'lunType': 'Auto',
                        'storagePaths': [{'connectionId': 8, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []},
                                         {'connectionId': 7, 'isEnabled': True, 'targetSelector': 'Auto', 'targets': []}
                                         ],
                        'volumeUri': 'v:vsa_vol2', 'volumeStorageSystemUri': vol_storage_sys_uri, 'bootVolumePriority': 'NotBootable'
                        }
                   ]
                   }
}
]

profiles_OVTC29141 = [{"type": SP_Type, "name": "OVTC29141_SP1",
                       "serverHardwareUri": 'SH:' + server_hardware_list[0],
                       "serverProfileTemplateUri": "SPT:" + "OVTC29141_SPT"
                       },
                      {"type": SP_Type, "name": "OVTC29141_SP2",
                       "serverHardwareUri": 'SH:' + server_hardware_list[1],
                       "serverProfileTemplateUri": "SPT:" + "OVTC29141_SPT",
                       }
                      ]

profiles_OVTC29143 = [{"type": SP_Type, "name": "OVTC29143_SP",
                       "serverHardwareUri": 'SH:' + server_hardware_list[0],
                       "serverProfileTemplateUri": "SPT:" + "OVTC29143_SPT",
                       }]

profiles_OVTC29144 = [{"type": SP_Type, "name": "OVTC29144_SP_1",
                       "serverHardwareUri": 'SH:' + server_hardware_list_different_Hw[0],
                       "serverProfileTemplateUri": "SPT:" + "OVTC29144_SPT_1",
                       }, {"type": SP_Type, "name": "OVTC29144_SP_2",
                           "serverHardwareUri": 'SH:' + server_hardware_list_different_Hw[1],
                           "serverProfileTemplateUri": "SPT:" + "OVTC29144_SPT_2",
                           }]

profiles_OVTC29155 = [{"type": SP_Type, "name": "OVTC29155_SP_1",
                       "serverHardwareUri": 'SH:' + server_hardware_list[0],
                       "serverProfileTemplateUri": "SPT:" + "OVTC29141_SPT_1",
                       }, {"type": SP_Type, "name": "OVTC29155_SP_2",
                           "serverHardwareUri": 'SH:' + server_hardware_list[1],
                           "serverProfileTemplateUri": "SPT:" + "OVTC29141_SPT_1",
                           }]

profiles_OVTC33064 = [{"type": SP_Type, "name": "OVTC33064_SP1",
                       "serverHardwareUri": 'SH:' + server_hardware_list_1[0],
                       "serverProfileTemplateUri": "SPT:" + "OVTC29141_SPT"
                       },
                      {"type": SP_Type, "name": "OVTC33064_SP2",
                       "serverHardwareUri": 'SH:' + server_hardware_list_1[1],
                       "serverProfileTemplateUri": "SPT:" + "OVTC29141_SPT",
                       }
                      ]

profiles_OVTC33082 = [{"type": SP_Type, "name": "OVTC33082_SP1",
                       "serverHardwareUri": 'SH:' + server_hardware_list_1[0],
                       "serverProfileTemplateUri": "SPT:" + "OVTC29141_SPT"
                       },
                      {"type": SP_Type, "name": "OVTC33082_SP2",
                       "serverHardwareUri": 'SH:' + server_hardware_list_1[1],
                       "serverProfileTemplateUri": "SPT:" + "OVTC29141_SPT",
                       }
                      ]

host_datacenter = 'DC2'

OVTC29145_hardware = [{'type': HCP_Type, 'name': 'OVTC29145', 'server_hardware': ["SGH736WS9C, bay 8"]}]
