# pylint: disable=E0401,E0602
from dto import *

"""# Resource types for X-API-Version=800
APPLIANCE_NETWORK_CONFIGURATION_TYPE = 'ApplianceNetworkConfigurationV2'
TIME_AND_LOCALE_TYPE = 'TimeAndLocale'
USER_AND_PERMISSION_TYPE = 'UserAndPermissions'
ETHERNET_NETWORK_TYPE = 'ethernet-networkV4'
NETWORK_SET_TYPE = 'network-setV4'
FCOE_NETWORK_TYPE = 'fcoe-networkV4'
FC_NETWORK_TYPE = 'fc-networkV4'
LOGICAL_INTERCONNECT_GROUP_TYPE = 'logical-interconnect-groupV4'
INTERCONNECT_TYPE = 'InterconnectV4'
ENCLOSURE_TYPE = 'EnclosureV7'
ENCLOSURE_GROUP_TYPE = 'EnclosureGroupV7'
SERVER_HARDWARE_TYPE = 'server-hardware-8'
STORAGE_SYSTEM_TYPE = 'StorageSystemV4'
STORAGE_POOL_TYPE = 'StoragePoolV4'
STORAGE_VOLUME_TEMPLATE_TYPE = 'StorageTemplateV4'
STORAGE_VOLUME_TYPE = 'StorageVolumeV4'
SERVER_PROFILE_TEMPLATE_TYPE = 'ServerProfileTemplateV6'
SERVER_PROFILE_TYPE = 'ServerProfileV10'
SERVER_PROFILE_COMPLIANCE_PREVIEW_TYPE = 'ServerProfileCompliancePreviewV1'
SAS_LOGICAL_INTERCONNECT_GROUP_TYPE = 'sas-logical-interconnect-groupV2'"""

admin_credentials = {'userName': 'Administrator', 'password': 'wpsthpvse1'}

# Enclosures
ENC1 = 'wpst23'
# Interconnects
ENC1ICBAY1 = '%s, interconnect 1' % ENC1
ENC1ICBAY2 = '%s, interconnect 2' % ENC1
ENC1ICBAY3 = '%s, interconnect 3' % ENC1
ENC1ICBAY4 = '%s, interconnect 4' % ENC1
ENC1ICBAY5 = '%s, interconnect 5' % ENC1
ENC1ICBAY6 = '%s, interconnect 6' % ENC1
# Server Hardware
ENC1SHBAY1 = '%s, bay 1' % ENC1
ENC1SHBAY2 = '%s, bay 2' % ENC1
ENC1SHBAY3 = '%s, bay 3' % ENC1
ENC1SHBAY4 = '%s, bay 4' % ENC1
ENC1SHBAY5 = '%s, bay 5' % ENC1
ENC1SHBAY6 = '%s, bay 6' % ENC1
ENC1SHBAY7 = '%s, bay 7' % ENC1
ENC1SHBAY8 = '%s, bay 8' % ENC1
ENC1SHBAY9 = '%s, bay 9' % ENC1
# Network names
ETH_1_F_106 = 'dev100'
ETH_1_G_107 = 'dev102-vmmigration'
ETH_1_H_108 = 'dev300-pxeboot'

# Server Hardware
SHT_BAY5 = 'BL460c Gen9 1'
WPST23_EG = 'GRP-wpst23'

# BL460c Gen9
# Profile initiator name is user defined.
# PXE primary on LOM1:1-g, secondary on LOM1:1-a, unbootable (US43999)
F444_server_profile = [{
    "type": SERVER_PROFILE_TYPE,
    "serverHardwareUri": 'SH:' + ENC1SHBAY5,
    "serialNumberType": "Virtual",
    "iscsiInitiatorNameType": "AutoGenerated",
    "macType": "Virtual",
    "wwnType": "Virtual",
    "name": "F444_SP",
    "description": "",
    "affinity": "Bay",
    "connectionSettings": {
        "connections": [
            {
                "id": 2,
                "name": "net1-f",
                "functionType": "Ethernet",
                "portId": "Flb 1:1-f",
                "requestedMbps": "2500",
                "networkUri": 'ETH:' + ETH_1_F_106,
                "boot": {"priority": "NotBootable"},
            },
            {
                "id": 3,
                "name": "net1-g",
                "functionType": "Ethernet",
                "portId": "Flb 1:1-g",
                "requestedMbps": "2500",
                "networkUri": 'ETH:' + ETH_1_G_107,
                "boot": {"priority": "NotBootable"},
            },
            {
                "id": 4,
                "name": "net1-h",
                "functionType": "Ethernet",
                "portId": "Flb 1:1-h",
                "requestedMbps": "2500",
                "networkUri": 'ETH:' + ETH_1_H_108,
                "boot":
                    {"priority": "NotBootable"},
            },
        ],
    },
    "boot": {
        "manageBoot": True,
        "order": ["HardDisk"]
    },
    "bootMode": {
        "manageMode": True,
        "mode": "UEFI",
        "pxeBootPolicy": "Auto"
    },
    "firmware": {
        "manageFirmware": False,
        "firmwareBaselineUri": "",
        "forceInstallFirmware": False,
        "firmwareInstallType": None
    },
    "bios": {
        "manageBios": False,
        "overriddenSettings": []
    },
    "hideUnusedFlexNics": True,
    "iscsiInitiatorName": "",
    "osDeploymentSettings": None,
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": []
    },
    "sanStorage": None
}
]

F444_server_profile_template = {
    "type": SERVER_PROFILE_TEMPLATE_TYPE,
    "serverProfileDescription": "",
    "serverHardwareTypeUri": 'SHT:' + SHT_BAY5,
    "enclosureGroupUri": 'EG:' + WPST23_EG,
    "serialNumberType": "Virtual",
    "macType": "Virtual",
    "wwnType": "Virtual",
    "name": "F444_SPT",
    "description": "",
    "affinity": "Bay",
    "connectionSettings":
        {
            "manageConnections": True,
            "connections": [
                {
                    "id": 2,
                    "name": "net1-f",
                    "functionType": "Ethernet",
                    "portId": "Flb 1:1-f",
                    "requestedMbps": "2500",
                    "networkUri": 'ETH:' + ETH_1_F_106,
                    "boot": {
                        "priority": "NotBootable"
                    }
                },
                {
                    "id": 3,
                    "name": "net1-g",
                    "functionType": "Ethernet",
                    "portId": "Flb 1:1-g",
                    "requestedMbps": "2500",
                    "networkUri": 'ETH:' + ETH_1_G_107,
                    "boot":
                        {
                            "priority": "NotBootable"
                        }
                },
                {
                    "id": 4,
                    "name": "net1-h",
                    "functionType": "Ethernet",
                    "portId": "Flb 1:1-h",
                    "requestedMbps": "2500",
                    "networkUri": 'ETH:' + ETH_1_H_108,
                    "boot":
                        {
                            "priority": "NotBootable"
                        }
                },
            ],
        },

    "boot":
        {
            "manageBoot": True,
            "order": ["HardDisk"]
        },
    "bootMode":
        {
            "manageMode": True,
            "mode": "UEFI",
            "pxeBootPolicy": "Auto"
        },
    "firmware":
        {
            "manageFirmware": False,
            "firmwareBaselineUri": "",
            "forceInstallFirmware": False,
            "firmwareInstallType": None
        },
    "bios":
        {
            "manageBios": False,
            "overriddenSettings": []
        },
    "hideUnusedFlexNics": True,
    "iscsiInitiatorNameType": "AutoGenerated",
    "localStorage":
        {
            "sasLogicalJBODs": [],
            "controllers": []
        },
    "sanStorage": None
}
