class FusionDashboardPage(object):
    ID_PAGE_LABEL = "//div[@class='hp-page-label']/h1[text()='Dashboard']"
    ID_LINK_CREATE_ENCLOSURE_GRP = "link=Create enclosure group"
    ID_MENU_ONE_VIEW = "id=hp-main-menu-labels"
    ID_LINK_ADD_SERVER_HW = "link=Add server hardware"
    ID_ELEMENT_SERVER_PROFILE = "xpath=//span[@class='hp-name' and text()='Server Profiles']"
    ID_ELEMENT_SERVER_HARDWARE = "xpath=//span[@class='hp-name' and text()='Server Hardware']"
    ID_ELEMENT_ENCLOSURE = "xpath=//span[@class='hp-name' and text()='Enclosures']"
    ID_ELEMENT_LOGICAL_INTERCONNECT = "xpath=//span[@class='hp-name' and text()='Logical Interconnects']"
    ID_ACTIVITY = "css=div.hp-icon.hp-activity"
    ID_SESSION = "css=div.hp-icon.hp-session"
    ID_HELP = "css=div.hp-icon.hp-help"
    ID_LINK_DASHBOARD = "link=Dashboard"
    ID_LINK_ACTIVITY = "link=Activity"
    ID_LINK_FW_BUNDLE = "link=Firmware Bundles"
    ID_LINK_SERVER_PROFILE = "link=Server Profiles"
    ID_LINK_ENC_GROUP = "link=Enclosure Groups"
    ID_LINK_ENCLOSURE = "link=Enclosures"
    ID_LINK_SERVER_HW = "link=Server Hardware"
    ID_LINK_SERVER_HW_TYPES = "link=Server Hardware Types"
    ID_LINK_LOGICAL_INTERCONNECT_GROUP = "link=Logical Interconnect Groups"
    ID_LINK_LOGICAL_INTERCONNECT = "link=Logical Interconnects"
    ID_LINK_NETWORKS = "link=Networks"
    ID_LINK_NETWORK_SET = "link=Network Sets"
    ID_LINK_INTERCONNECTS = "link=Interconnects"
    ID_LINK_DATACENTER = "link=Data Centers"
    ID_LINK_RACKS = "link=Racks"
    ID_LINK_POWER_DELIVERY_DEVICES = "link=Power Delivery Devices"
    ID_LINK_UNMANAGED_DEVICE = "link=Unmanaged Devices"
    ID_LINK_SETTINGS = "link=Settings"
    ID_LINK_USER_GROUP = "link=Users and Groups"
    ID_INPUT_SEARCH = "id=hp-search-control"
    ID_FIELD_SEARCH = "css=input"
    ID_BTN_LOGOUT = "id=hp-session-logout"
    ID_ELEMENT_SESSION_USER = "xpath//div[@id='hp-session-user' and text()='%s']"

    ID_PAGE_LABEL_TEXT = "xpath=//div[@class='hp-page-label']/h1"
    ID_LINK_ADD_DASHBOARD = "id=hp-dashboard-add-action"
    ID_ADD_DASHBOARD_PANEL_LABEL = "xpath=//*[@id='hp-body-div']//span[text()='Add Dashboard Panel']"
    ID_EDIT_DASHBOARD_PANEL_LABEL = "xpath=//*[@id='hp-body-div']//span[text()='Edit Dashboard Panel']"
    ID_COMBO_ADD_DASHBOARD_PANEL_DROPDOWN = "xpath=.//*[@id='cic-dashboard-add-preset-row']/div/div/div/div"
    ID_COMBO_ADD_DASHBOARD_PANEL_SELECT = "xpath=//li[@id='cic-dashboard-add-preset-row']/div/div/div/ol/li/span[text()='%s']"
    ID_COMBO_ADD_DASHBOARD_RESOURCES_SELECT = "xpath=//*[@id='cic-dashboard-add-general']//li[@data-id='%s']"
    ID_COMBO_ADD_DASHBOARD_RESOURCES_DROPDOWN = "xpath=//*[@id='cic-dashboard-add-general']/fieldset/ol/li[2]/div/div/div/div"
    ID_COMBO_ADD_DASHBOARD_TYPE_DROPDOWN = "xpath=//*[@id='cic-dashboard-add-query']/fieldset[1]/ol/li[1]/div/div/div/div"
    ID_COMBO_ADD_DASHBOARD_TYPE_SELECT = "xpath=//*[@id='cic-dashboard-add-query']//span[text()='%s']"
    ID_TXT_ADD_DASHBOARD_TITLE = "id=cic-dashboard-add-title"
    ID_TXT_ADD_DASHBOARD_QUERY = "id=cic-dashboard-add-filter"
    ID_TXT_ADD_DASHBOARD_CAPTION = "id=cic-dashboard-add-caption"
    ID_TXT_ADD_DASHBOARD_OTHER_LABEL = "id=cic-dashboard-add-other-label"
    ID_BTN_ADD_SLICE = "id=cic-dashboard-add-segment-add"
    ID_TXT_ADD_SLICE_LABEL = "id=cic-dashboard-add-segment-label"
    ID_TXT_ADD_SLICE_QUERY = "id=cic-dashboard-add-segment-query"
    ID_BTN_ADD_SLICE_OK = "xpath=//*[@id='cic-dashboard-add-segment-form']//input[@value='OK']"
    ID_BTN_ADD_SLICE_CANCEL = "xpath=//*[@id='cic-dashboard-add-segment-form']//button[@data-localize='core.details.cancel']"
    ID_BTN_EDIT_DASHBOARD_OK = "id=cic-dashboard-add-ok"
    ID_BTN_EDIT_DASHBOARD_CANCEL = "xpath=//*[@id='cic-dashboard-add-form']//button[text()='Cancel']"
    ID_BTN_ADD_DASHBOARD_ADD = "id=cic-dashboard-add-add"
    ID_BTN_ADD_DASHBOARD_ADD_PLUS = "id=cic-dashboard-add-addplus"
    ID_BTN_ADD_DASHBOARD_CANCEL = "xpath=//*[@id='cic-dashboard-add-form']/footer/div[2]/button"
    ID_LINK_DASHBOARD_NAME = "xpath=//*[@id='hp-dashboard-row']//span[text()='%s']"
    ID_LINK_DASHBOARD_DELETE = "xpath=//*[@id='hp-dashboard-row']//h2[a/span[text()='%s']]/following-sibling::a[@class='hp-delete']"
    ID_BTN_DASHBOARD_DELETE_CONFIRM = "xpath=//*[@id='hp-body-div']/div[8]//button[text()='Yes, remove']"
    ID_BTN_DASHBOARD_DELETE_CANCEL = "xpath=//*[@id='hp-body-div']/div[8]//button[text()='Cancel']"
    ID_LINK_DASHBOARD_EDIT = "xpath=//*[@id='hp-dashboard-row']//h2[a/span[text()='%s']]/following-sibling::a[@class='hp-edit']"
    ID_LINK_ADD_SLICE_EDIT = "xpath=//*[@id='cic-dashboard-add-segments']/tbody/tr/td[text()='%s']/following-sibling::td/div[@class='hp-edit cic-dashboard-add-segment-control']"
    ID_LINK_ADD_SLICE_DELETE = "xpath=//*[@id='cic-dashboard-add-segments']/tbody/tr/td[text()='%s']/following-sibling::td/div[@class='hp-delete cic-dashboard-add-segment-control']"
    ID_COMPONENT_LIST = "xpath = //div[@id='hp-dashboard-row']/div/descendant::span[1]"
    ID_COMPONENT_SUMMARY = "xpath = //div[@id='hp-dashboard-row']/div/descendant::a[span[text()='%s']]"
    ID_NUMBER_OF_OBJECT = "xpath = //div[@id='hp-dashboard-row']/div/descendant::a[span[text()='%s']]/span[2]"
    ID_ELEMENT_COMPONENT = "xpath = //span[@class='hp-name' and text()='%s']"
    ID_NO_SUMMARY_STATUS = "xpath = //header[descendant::span[text()='%s']]/following-sibling::div/ol[1][@style='display: none;']"
    ID_ELEMENT_LIST = "xpath = //div[@class='dataTables_scrollBody']/table/tbody/tr"
    ID_COMPONENT_TABLE_COUNT = "xpath = //header[@class='hp-master-header']/following-sibling::ol/li"
    ID_STATUS_SUMMARY = "xpath = //header[descendant::span[text()='%s']]/following-sibling::div/div/ol[1]"
    ID_CRITICAL_OBJECTS_COUNT = ID_STATUS_SUMMARY + "/li[1]/a/span[@class='hp-count']"
    ID_WARNING_COUNT_SUMMARY = ID_STATUS_SUMMARY + "/li[2]/a/span[@class='hp-count']"
    ID_OK_COUNT_SUMMARY = ID_STATUS_SUMMARY + "/li[3]/a/span[@class='hp-count']"
    ID_COMPONENT_STATUS = "xpath = //span[@class='hp-name' and text()='%s']/ancestor::header/following-sibling::div/descendant::ol[@class='hp-utilization-summary']/descendant::div[@class='hp-label']"  # %s replace with component name


class GeneralDashboardElements(object):
    ID_SELECT_ADD_DASHBOARD_ACTIONS = "xpath=.//*[@id='hp-dashboard-add-action']"
    ID_BUTTON_DASHBOARD_ACTION = "xpath=//*[@id='hp-dashboard-actions']/label/div"
    ID_DASHBOARD_PANEL = "xpath=//*[@id='hp-dashboard-panels']/div/div/header/h2/a/span[text()='%s']"


class AddDashboardPanelElements(object):
    ID_DIALOG_ADD_DASHBOARD_PANEL = "xpath=.//*[@id='cic-dashboard-add-form']"
    ID_DROPDOWN_PANEL = "xpath=.//*[@id='cic-dashboard-add-preset-row']/div/div/div/div"
    ID_SELECT_PANEL = "xpath=.//*[@id='cic-dashboard-add-preset-row']//span[text()='%s']"
    ID_DROPDOWN_RESOURCE = "xpath=.//*[@id='cic-dashboard-add-general']/fieldset/ol/li[2]/div/div/div/div"
    ID_SELECT_RESOURCE = "xpath=.//*[@id='cic-dashboard-add-general']/fieldset/ol/li[2]/div/div/div/ol/li/span[text()='%s']"
    ID_INPUT_TITLE = "xpath=.//*[@id='cic-dashboard-add-title']"
    ID_INPUT_QUERY = "xpath=.//*[@id='cic-dashboard-add-filter']"
    ID_DROPDOWN_DATA_SETS_TYPE = "xpath=.//*[@id='cic-dashboard-add-query']/fieldset[1]/ol/li[1]/div/div/div/div"
    ID_SELECT_DATA_SETS_TYPE = "xpath=.//*[@id='cic-dashboard-add-query']/fieldset[1]/ol/li[1]/div/div/div/ol/li/span[text()='%s']"
    ID_BUTTON_ADD_PLUS = "xpath=.//*[@id='cic-dashboard-add-addplus']"
    ID_BUTTON_ADD = "xpath=.//*[@id='cic-dashboard-add-add']"
    ID_BUTTON_CANCEL = "xpath=.//*[@id='cic-dashboard-add-form']/footer/div[2]/button[text()='Cancel']"
    ID_BUTTON_ADD_SLICE = "xpath=.//*[@id='cic-dashboard-add-segment-add']"
    ID_INPUT_CAPTION = "xpath=.//*[@id='cic-dashboard-add-caption']"
    ID_INPUT_OTHER_LABEL = "xpath=.//*[@id='cic-dashboard-add-other-label']"
    ID_DIALOG_ADD_SLICE_DIALOG = "xpath=.//*[@id='cic-dashboard-add-segment-form']"
    ID_INPUT_ADD_SLICE_LABEL = "//*[@id='cic-dashboard-add-segment-label']"
    ID_INPUT_ADD_SLICE_QUERY = "//*[@id='cic-dashboard-add-segment-query']"
    ID_BUTTON_ADD_SLICE_OK = "xpath=.//*[@id='cic-dashboard-add-segment-form']/footer/div[2]/input"


class RemoveDashboardPanelElements(object):
    ID_REMOVE_DASHBOARD_PANEL = "xpath=.//*[@id='hp-dashboard-panels']/div/div/header/h2/a/span[text()='%s']/../../../a[@class='hp-delete']"
    ID_DIALOG_REMOVE_DASHBOARD_PANEL = "xpath=.//*[@id='hp-body-div']/div/div/div/div/header/h1/span[text()='Remove Dashboard Panel']"
    ID_BUTTON_REMOVE_PANEL_YES_REMOVE = "xpath=.//*[@id='hp-body-div']/div/div/div/div/footer/div/button[text()='Yes, remove']"
