#!/bin/bash
#
# Copyright 2011 Hewlett-Packard Development Company, L.P.
#
# Permission to use, copy, modify, and distribute this software and its
# documentation under the terms of the GNU General Public License is hereby
# granted. No representations are made about the suitability of this software
# for any purpose. It is provided "as is" without express or implied warranty.
# See the GNU General Public License for more details.
#
# Author: Bobby Suber - 4/28/2011 
# 
# Description:
# This script is used to add an ssh key to a remote host.  It's an interactive
# script that reads the conf file and then copy's the public key to the remote host.  
#

#=============================================================================
# usage
#=============================================================================
usage()
{
        echo "usage: $0 -f <conf file>"
        echo ""
}

#=============================================================================
# copy_ssh_ids 
#=============================================================================
copy_ssh_ids()
{

	if [ -f $CONF ]; then
		SERVERIPS=(`grep "=" $CONF | awk 'BEGIN{FS="="} {print $NF}'`)
	else
        	echo "`date`: Warning - Missing $CONF file so exiting..."  
		exit
	fi

	for i in "${SERVERIPS[@]}"
	do
		ssh-copy-id -i ~/.ssh/id_rsa.pub $i 
		ssh -l root $i exit
	done
}

  while [ -n "$(echo $1 | grep '-')" ]; do
          case $1 in
          -f ) CONF=$2
                 shift ;;
          * ) usage
              exit 1
          esac
          shift
  done

  if [ -z "$CONF" ]; then
          usage
          exit 1
  fi

  copy_ssh_ids

