#!/bin/bash

echo 1024 > /proc/sys/net/ipv4/neigh/default/gc_thresh1
echo 4096 > /proc/sys/net/ipv4/neigh/default/gc_thresh2
echo 8192 > /proc/sys/net/ipv4/neigh/default/gc_thresh3

echo "net.ipv4.neigh.default.gc_thresh1 = 1024" >> /etc/sysctl.conf
echo "net.ipv4.neigh.default.gc_thresh2 = 4096" >> /etc/sysctl.conf
echo "net.ipv4.neigh.default.gc_thresh3 = 8192" >> /etc/sysctl.conf
