#!/bin/bash

# Get RH Version
rh_ver=`cat /etc/redhat-release |cut -d\( -f2 |cut -d\) -f1`
echo "Red Hat Release: $rh_ver"

# Remove ifcfg-bonds
cd /etc/sysconfig/network-scripts/
ls |grep bond
cmdCheck=$?
if [ $cmdCheck = 0 ]; then
	rm -f ifcfg-bond*
fi

# Remove /root/tools/scripts bond_ipaddr.conf
if [ -e /root/tools/scripts/bond_ipaddr.conf ]; then
	rm -f /root/tools/scripts/bond_ipaddr.conf
fi

# Remove bond entries from ifcfg-* files.
cd /etc/sysconfig/network-scripts/
netDevices=`ls ifcfg-* |grep -v ifcfg-lo`
for nic in ${netDevices[@]}
do
	cat $nic  |grep -v bond |grep -v SLAVE > /tmp/$nic
	cp -f /tmp/$nic /etc/sysconfig/network-scripts/
done


# Check for duplicate ONBOOT entries and remove.
cd /etc/sysconfig/network-scripts/
if [ $rh_ver == 'Santiago' ]; then
    pxe_nic=`ifconfig |grep -B1 192.168. |grep -v 'inet' |cut -d' ' -f1`
elif [ $rh_ver == 'Maipo' ]; then
    pxe_nic=`ifconfig |grep -B1 192.168. |grep -v 'inet' |cut -d: -f1`
else
     echo "Unknown Linux/RH Version.  Please check /etc/redhat-release for RH version and update script."
     exit 4
fi
inf="ifcfg-$pxe_nic"
netDevices=`ls ifcfg-* |grep -v ifcfg-lo`
for nic in ${netDevices[@]}
do
    if [ "$nic" == "$inf" ]; then
        echo "Found PXE nic: $inf. Skipping."
    else
        # Remove ALL ONBOOT, USERCTL, TYPE and BOOTPROTO entries:
        cat $nic  |grep -v ONBOOT |grep -v USERCTL |grep -v TYPE | grep -v BOOTPROTO > /tmp/$nic
        echo "BOOTPROTO=none" >> /tmp/$nic
        echo "ONBOOT=yes" >> /tmp/$nic
        echo "USERCTL=no" >> /tmp/$nic
        echo "TYPE=Ethernet" >> /tmp/$nic
  	cp -f /tmp/$nic /etc/sysconfig/network-scripts/
    fi
done


exit 0
