#!/bin/bash
LOG=$0.log
CONF="../conf/bond_ipaddr.conf"
SERVER_CONF="../conf/server.conf"

####################################################################################
# Get the server IPs from the server.conf file.  There is not any error
# checking so the user should ensure that the server IPs are correct.  
####################################################################################

if [ -f $SERVER_CONF ]; then
	IPADDRS=(`cat $SERVER_CONF | awk 'BEGIN{FS="="} {print $NF}'`)
else
        echo "`date`: Warning - Missing server_update.conf file so exiting..."  
	exit
fi

####################################################################################
# If LOG already exists in the current directory then rename it 
####################################################################################

if [ -f $LOG ]; then
	TMP_FILE=$(mktemp $LOG.XXXXXXXXXX)
	mv $LOG $TMP_FILE
fi

####################################################################################
# If LOG already exists in the current directory then rename it 
####################################################################################

if [ -f $CONF ]; then
	TMP_FILE=$(mktemp $CONF.XXXXXXXXXX)
	mv $CONF $TMP_FILE
fi

##################################################################	
# Ping each server and if accessible then update the servers  
##################################################################

for ipaddr in ${IPADDRS[@]}
do 
	ping $ipaddr -c 1 >/dev/null 2>&1 
	if [ $? -eq 0 ] ; then
		nPASS=`expr $nPASS + 1`
       		echo "`date`: IP address $ipaddr is reachable" 2>&1 | tee -a $LOG 
       		echo "`date`: Number of bonds is..." 2>&1 | tee -a $LOG 
		ssh root@$ipaddr cat /root/bond_ipaddr.conf | wc -l | tee -a $LOG
		ssh root@$ipaddr cat /root/bond_ipaddr.conf | tee -a $CONF
	else
		nFAIL=`expr $nFAIL + 1`
		SERVER=(`cat server.conf | grep $ipaddr | awk 'BEGIN{FS="="} {print $NR}'`)
        	echo "`date`: IP address $ipaddr is NOT reachable for $SERVER" 2>&1 | tee -a $LOG 
	fi
done


