#!/bin/bash
OUTPUT_DIR=ping
RESULTS_FILE=pingResults.log
IPADDR_FILE=ipaddr.conf
DATA_FILE=pingData.txt

if [ -f $RESULTS_FILE ]; then
	rm -f $RESULTS_FILE
fi

if [ -f $DATA_FILE ]; then
	rm -f $DATA_FILE
fi

grep -n "[1-9]%* packet loss" $OUTPUT_DIR/* >> $RESULTS_FILE 
while read line
do
	filename=(`echo $line | awk 'BEGIN{FS=":"} {print $NR}'`)
	lineNum=(`echo $line | cut -d":" -f 2`)
	ip=(`echo $line | grep -o [0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*`)
	serverProfilePort=(`cat $IPADDR_FILE | grep $ip`)
	packetLoss=(`echo $line | grep -o "[0-9][0-9]*% "`)
	endlineNum=`expr $lineNum + 2`
	lossTime=(`sed -n "$lineNum,${endlineNum}p" $filename | grep "End Time" | grep -o [0-9][0-9]:[0-9][0-9]:[0-9][0-9]`)
	echo "$serverProfilePort $ip $packetLoss $lossTime" >> $DATA_FILE

done <$RESULTS_FILE

