#!/bin/bash
IPADDR="../conf/ipaddr.conf"

usage()
{
        echo "usage: $0 -dir <Raw Data Directory> -log <Logfile name>" 
	echo "example:"
	echo "$0 -dir /tmp/pingBonds/Apr_17_2012_05:56:42 -log ping.data"
	echo ""
}

while [ -n "$(echo $1 | grep '-')" ]; do
         case $1 in
         -dir ) DIR=$2
                shift ;;
         -log ) LOG=$2
                shift ;;
         * ) usage
             exit 1
         esac
         shift
done

if [ -z "$DIR" -o -z "$LOG" ]; then
         usage
         exit 1
fi

if [ ! -f $IPADDR ]; then
	echo "WARNING - Missing $IPADDR"
	exit 1
fi

FILES=`ls $DIR`

echo "Profile-Port, IP, VLAN, Percent, Time" 2>&1 | tee -a $LOG
for log in ${FILES[@]}
do
	ip=`echo "$log" | sed "s|ping/||g" | sed "s|.log||g"`
	profile_port=`cat $IPADDR | grep "$ip" | cut -d " " -f 1`
	vlan=`cat $IPADDR | grep "$ip" | grep -o -E ' [[:digit:]]{1,4} ' | tr -d ' '`
	line_numbers=`cat $DIR/$log | grep -n "packet loss" | cut -d ":" -f 1`
	for line in ${line_numbers[@]}
	do
		start_line=$line
		let end_line=line+2
		percent=`awk -v start=$start_line -v end=$start_line 'NR==start,NR==end' $DIR/$log |  grep -o -E '[0-9]{1,3}%' | tr -d '%'`
		time_stamp=`awk -v start=$start_line -v end=$end_line 'NR==start,NR==end' $DIR/$log | grep "End Time" | grep -o -E '[0-9][0-9]:[0-9][0-9]:[0-9][0-9]'`
		if [ "$vlan" = "" ]; then
			echo "$profile_port, $ip, $percent, $time_stamp" 2>&1 | tee -a $LOG
		else
			echo "$profile_port, $ip, $vlan, $percent, $time_stamp" 2>&1 | tee -a $LOG
		fi
	done
done

