#!/bin/bash
LOG=./$0.log
SERVER_CONF="../conf/server.conf"
ELX="elx-lpfc-8.2.0.128-1_rhel5.src.rpm"
BE2NET="hp-be2net-4.1.402.6-1.src.rpm"
BE2ISCSI="hp-be2iscsi-4.1.402.0-1.src.rpm"
SCRIPT="install_drivers.sh"

#==================================================================================
# get_server_ipaddrs
#==================================================================================
get_server_ipaddrs()
{
	if [ -f $SERVER_CONF ]; then
		IPADDRS=(`cat $SERVER_CONF | awk 'BEGIN{FS="="} {print $NF}'`)
	else
        	echo "`date`: Warning - Missing server.conf file so exiting..."  
		exit
	fi
}

#==================================================================================
# check_log 
#==================================================================================
check_log()
{
	if [ -f $LOG ]; then
		TMP_FILE=$(mktemp $LOG.XXXXXXXXXX)
		mv $LOG $TMP_FILE
	fi
}

#==================================================================================
# verify_rpms
#==================================================================================
verify_rpms()
{
	if [ ! -f $ELX ]; then
        	echo "`date`: Warning - Missing $ELX so exiting..."  
		exit
	fi

	if [ ! -f $BE2NET ]; then
        	echo "`date`: Warning - Missing $BE2NET so exiting..."  
		exit
	fi

	if [ ! -f $BE2ISCSI ]; then
        	echo "`date`: Warning - Missing $BE2ISCSI so exiting..."  
		exit
	fi
}

#==================================================================================
# run_job 
#==================================================================================
run_job()
{
	local ipaddr

	for ipaddr in ${IPADDRS[@]}
	do 
		ping $ipaddr -c 1 >/dev/null 2>&1 
		if [ $? -eq 0 ] ; then
       			echo "`date`: IP address $ipaddr is reachable" 2>&1 | tee -a $LOG 
       			echo "`date`: Copying $SCRIPT to $ipaddr" 2>&1 | tee -a $LOG 
			scp $SCRIPT root@$ipaddr:/root
       			echo "`date`: Copying $ELX to $ipaddr" 2>&1 | tee -a $LOG 
			scp $ELX root@$ipaddr:/root
       			echo "`date`: Executing $SCRIPT for $ELX on $ipaddr" 2>&1 | tee -a $LOG 
			ssh root@$ipaddr /root/$SCRIPT /root $ELX kmod-elx-lpfc
			if [ $? -ne 0 ]; then
        			echo "`date`: WARNING $SCRIPT failed for $ELX.  Check log on server at $ipaddr for more details." 2>&1 | tee -a $LOG 
				continue
			fi
			exit
       			echo "`date`: Copying $BE2NET to $ipaddr" 2>&1 | tee -a $LOG 
			scp $BE2NET root@$ipaddr:/root
       			echo "`date`: Executing $SCRIPT for $BE2NET on $ipaddr" 2>&1 | tee -a $LOG 
			ssh root@$ipaddr /root/$SCRIPT /root $BE2NET kmod-hp-be2net
			if [ $? -ne 0 ]; then
        			echo "`date`: WARNING $SCRIPT failed for $BE2NET.  Check log on server at $ipaddr for more details." 2>&1 | tee -a $LOG 
				continue
			fi
       			echo "`date`: Copying $BE2ISCSI to $ipaddr" 2>&1 | tee -a $LOG 
			scp $BE2ISCSI root@$ipaddr:/root
       			echo "`date`: Executing $SCRIPT for $BE2ISCSI on $ipaddr" 2>&1 | tee -a $LOG 
			ssh root@$ipaddr /root/$SCRIPT /root $BE2ISCSI kmod-hp-be2iscsi
			if [ $? -ne 0 ]; then
        			echo "`date`: WARNING $SCRIPT failed for $BE2ISCSI.  Check log on server at $ipaddr for more details." 2>&1 | tee -a $LOG 
				continue
			fi
		else
			SERVER=(`cat server.conf | grep $ipaddr | awk 'BEGIN{FS="="} {print $NR}'`)
        		echo "`date`: IP address $ipaddr is NOT reachable for $SERVER" 2>&1 | tee -a $LOG 
		fi
	done

}


  check_log
  get_server_ipaddrs
  verify_rpms
  run_job
