#!/usr/bin/ksh
LOG=$0.log
SYSLOG="/var/adm/syslog/syslog.log"
SYSLOG_LINE_NUM_START=0
SYSLOG_LINE_NUM_END=0

#============================================================================e
# get_ppa
#=============================================================================
get_ppa()
{
	echo "# nwmgr -g" 2>&1 | tee -a $LOG
	nwmgr -g 2>&1 | tee -a $LOG
}

#============================================================================e
# get_ips
#=============================================================================
get_ips()
{
	echo "# netstat -in" 2>&1 | tee -a $LOG
	netstat -in 2>&1 | tee -a $LOG
}

#============================================================================e
# get_failover_group_param
#=============================================================================
get_failover_group_param()
{
	FG_ARRAY=$1
	for group in $FG_ARRAY
	do
		echo "" | tee -a $LOG
		echo "# nwmgr -S apa -c $group -v" 2>&1 | tee -a $LOG
		nwmgr -S apa -c $group -v 2>&1 | tee -a $LOG
	done

}

#============================================================================e
# get_syslog_line_num
#=============================================================================
get_syslog_line_num()
{
	typeset var line_num=`cat $SYSLOG | wc -l`
	echo "$line_num"
}

#=============================================================================
# wait_for_done
#=============================================================================
wait_for_done()
{
        typeset var DONE=0
	while read LINE; do
		if [ $LINE = "done" ]; then
			echo "Received done so continuing"			
			break
		else
			echo "Invalid input - $LINE"
			echo "Please try again"
		fi
	done

}

#=============================================================================
# get_nettl_log
#=============================================================================
get_nettl_log()
{
	echo "# nettl -status all" 2>&1 | tee -a $LOG
	nettl -status all 2>&1 | tee -a $LOG
}

#=============================================================================
# get_syslog
#=============================================================================
get_syslog()
{
	typeset var start=$1
	typeset var end=$2

	if [ $end -lt $start ]; then
		echo "`date:` WARNING - It looks like syslog rolled over"
		echo "`date:` The last line before the test was $start"
		echo "`date:` The last line after the test was $end"
	else
		echo "awk -v start=$start -v end=$end 'NR==start,NR==end' $SYSLOG" 2>&1 | tee -a $LOG	
		awk -v start=$start -v end=$end 'NR==start,NR==end' $SYSLOG 2>&1 | tee -a $LOG 
	fi
		
}

#=============================================================================
# get_uname
#=============================================================================
get_uname()
{
	echo "# uname -a" 2>&1 | tee -a $LOG
	uname -a  2>&1 | tee -a $LOG
}

#=============================================================================
# get_model
#=============================================================================
get_model()
{
	echo "# model" 2>&1 | tee -a $LOG
	model 2>&1 | tee -a $LOG
}

#=============================================================================
# get_swlist
#=============================================================================
get_swlist()
{
	echo "# swlist" 2>&1 | tee -a $LOG
	swlist 2>&1 | tee -a $LOG
}

#=============================================================================
# get_kcmodule
#=============================================================================
get_kcmodule()
{
	echo "# kcmodule" 2>&1 | tee -a $LOG
	kcmodule 2>&1 | tee -a $LOG
}

#=============================================================================
# print_contents
#=============================================================================
print_contents()
{
	echo "Contents"  2>&1 | tee -a $LOG 
	echo "1. nwmgr -g" 2>&1 | tee -a $LOG
	echo "2. netstat -in" 2>&1 | tee -a $LOG
	echo "3. nwmgr -S apa -c lan<ppa> -v     //before the test" 2>&1 | tee -a $LOG
	echo "4. nwmgr -S apa -c lan<ppa> -v     //after the test" 2>&1 | tee -a $LOG
	echo "5. nettl -status all" tee -a $LOG
	echo "6. syslog			   //From right before and after the test" 2>&1 | tee -a $LOG
	echo "   awk -v start=$start -v end=$end 'NR==start,NR==end' $SYSLOG" 2>&1 | tee -a $LOG
	echo "7. uname -a" 2>&1 | tee -a $LOG
	echo "8. model" 2>&1 | tee -a $LOG
	echo "9. swlist" 2>&1 | tee -a $LOG
	echo "10. kcmodule" 2>&1 | tee -a $LOG
}

print_contents
echo "" 2>&1 | tee -a $LOG
FAILOVER_GROUPS=$(nwmgr -S apa | grep lan9 | cut -d " " -f1) 
echo "`date`: Getting ppa devices"  2>&1 | tee -a $LOG
get_ppa
echo "" 2>&1 | tee -a $LOG
echo "`date`: Getting IPs"  2>&1 | tee -a $LOG
get_ips
echo "" 2>&1 | tee -a $LOG
echo "`date`: Getting failover group parameters before the test"  2>&1 | tee -a $LOG
get_failover_group_param "$FAILOVER_GROUPS"
echo "" 2>&1 | tee -a $LOG
SYSLOG_LINE_NUM_START=$(get_syslog_line_num)
echo "`date`: Enter \"done\" when the test has completed"
wait_for_done
echo "" 2>&1 | tee -a $LOG
echo "`date`: Getting failover group parameters after the test"  2>&1 | tee -a $LOG
get_failover_group_param "$FAILOVER_GROUPS"
echo "" 2>&1 | tee -a $LOG
echo "`date`: Getting nettl log"  2>&1 | tee -a $LOG
get_nettl_log
echo "" 2>&1 | tee -a $LOG
echo "`date`: Getting syslog"  2>&1 | tee -a $LOG
SYSLOG_LINE_NUM_END=$(get_syslog_line_num)
get_syslog $SYSLOG_LINE_NUM_START $SYSLOG_LINE_NUM_END
echo "" 2>&1 | tee -a $LOG
echo "`date`: Getting uname"  2>&1 | tee -a $LOG
get_uname
echo "" 2>&1 | tee -a $LOG
echo "`date`: Getting model"  2>&1 | tee -a $LOG
get_model
echo "" 2>&1 | tee -a $LOG
echo "`date`: Getting swlist"  2>&1 | tee -a $LOG
get_swlist
echo "" 2>&1 | tee -a $LOG
echo "`date`: Getting kcmodule"  2>&1 | tee -a $LOG
get_kcmodule

