#!/bin/bash

NAME="pingBonds"
CONF="../conf/bond_ipaddr.conf"
PING_SCRIPT="../lib/ping_ip"

if [ ! -f $CONF ]; then
	echo "ERROR: The $CONF file is not found." 
	exit
fi

if [ ! -f $PING_SCRIPT ]; then
	echo "ERROR: The $PING_SCRIPT file is not found." 
	exit
fi

MONTH=`date | awk '{print $2}'`
DAY=`date | awk '{print $3}'`
YEAR=`date | awk '{print $6}'`
TIME_OF_DAY=`date | awk '{print $4}'`
TEST_RUN="$MONTH"_"$DAY"_"$YEAR"_"$TIME_OF_DAY"
LOG_DIR="/tmp/$NAME/$TEST_RUN"

mkdir -p "$LOG_DIR"

bondIpaddr=(`cat $CONF | grep -o -E '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}'`)
for bip in ${bondIpaddr[@]} 
do
	$PING_SCRIPT $bip "$LOG_DIR/$bip.log" &
done


