#!/bin/bash

NAME="ping_gateway"
#PING_SCRIPT="./ping_ip"
PING_SCRIPT="../lib/ping_ip"
NETWORK="192"

if [ ! -f $PING_SCRIPT ]; then
	echo "ERROR: The $PING_SCRIPT file is not found." 
	exit
fi

MONTH=`date | awk '{print $2}'`
DAY=`date | awk '{print $3}'`
YEAR=`date | awk '{print $6}'`
TIME_OF_DAY=`date | awk '{print $4}'`
TEST_RUN="$MONTH"_"$DAY"_"$YEAR"_"$TIME_OF_DAY"
LOG_DIR="/tmp/$NAME/$TEST_RUN"

mkdir -p "$LOG_DIR"

killall ping

# Start a ping to the gateway on every network present
for ips in `route|grep ^$NETWORK |awk '{print $1}'|sed 's/\.0$/\.1/g'`
do
  ip=`echo $ips |sed 's/\.1$/\.0/g'`
  inf=`route|grep ^${ip}|awk '{print$8}'`
  $PING_SCRIPT $ips "$LOG_DIR/$ips.log" $inf &
done


