#!/bin/bash

# Read in rcount.txt file to get the current reboot count
rCounter=$(</root/reboot/rcount.txt)

# Increment the counter and write to file
rCounter=`expr $rCounter + 1`
echo $rCounter > /root/reboot/rcount.txt

if [ $# -eq 1 ]; then
	seconds=$1
else
        echo "usage: $0 <wait time in seconds>" 
        exit 1
fi

sleep $seconds 
reboot

