#!/bin/bash

for ip in $(cat ./bond_server.conf)
do
	echo $ip
	
	#ssh root@$ip ./write_to_disk /media/fcoe &
	#ssh root@$ip "touch ./done"
	#ssh root@$ip "rm -f ./done"
	#ssh root@$ip "rm -f /media/fcoe/write_to_disk.log"
	
	#topNum=$(ssh root@$ip "cat /media/fcoe/write_to_disk.log | grep -oP '\d\d?\d?\d?\Z' | grep -oP '^\d\d?\d?\d?\Z'")
	#lineCount=$(ssh root@$ip "wc -l /media/fcoe/write_to_disk.log")
	#echo "$topNum - $lineCount"
	
	ssh root@$ip "mv ./ifcfg ./ifcfg-upgrade"
	ssh root@$ip "mv ./ifcfg-original ./ifcfg"
	#ssh root@$ip "./remove_bonds &"
done

