#!/bin/bash

if [ $# -eq 1 ]; then
	mntdir=$1
else
	echo "usage: $0 </path-to-disk>"
	echo "example:  $0 /media/fcoe"
	exit
fi

LOG=$0.log
if [ -f $LOG ]; then
	TMP_LOG=$(mktemp $LOG.XXXXXXXX)
	mv $LOG $TMP_LOG
fi

if [ -f done ]; then
	rm -f done
fi

fdisk -l | grep -w "\/dev\/dm"
ret=$?
if [ $ret -ne 0 ]; then
	echo "The device is not configured for multipath so exiting..."
	exit
else
	dmdisk=(`fdisk -l | grep -w "\/dev\/dm" | cut -d" " -f2 | rev | cut -b 2- | rev`)
	mount | grep -w "$dmdisk" &>/dev/null
	mounted=$?
	mount | grep -w "$dmdisk on $mntdir" &>/dev/null
	dmMounted=$?

fi

if [ $dmMounted -ne 0 -a $mounted -ne 0 ]; then
	mkfs -t ext3 $dmdisk
	if [ ! -d $mntdir ]; then
		mkdir $mntdir
	fi
	mount $dmdisk $mntdir
fi

if [ $dmMounted -ne 0 -a $mounted -eq 0 ]; then
	curmntdir=(`mount | grep $dmdisk | cut -d" " -f3`)	
	echo "$dmdisk is already mounted on $curmntdir"
	mntdir=$curmntdir
fi

i=1
DONE=0
while [ $DONE -eq 0 ]; do
	echo "`date` $i" 2>&1 | tee -a $mntdir/$LOG
	sleep 1
	if [ -a done ]; then
		DONE=1
	fi
	let i=i+1
done
	
	
	
	
