class GeneralSANsElements(object):
    ID_DROPDOWN_ACTIONS = "xpath=.//*[@id='cic-sans-actions']/label"
    ID_SANS = "xpath=//*[@id='DataTables_Table_0']/tbody//td[text()='%s']"
    ID_SANS_TITLE = "xpath=//*[@id='cic-sans-details-title'][text()='%s']"
    ID_TEXT_STATE = "xpath=.//*[@id='cic-sans-general-state']"
    ID_TEXT_TYPE = "xpath=.//*[@id='cic-sans-general-type']"
    ID_TEXT_PRINCIPAL_SWITCH = "xpath=.//*[@id='cic-sans-general-prinicpal-switch']"
    ID_TEXT_SAN_MANAGER = "xpath=.//*[@id='cic-sans-general-san-manager']"
    ID_TEXT_ASSOCIATED_NETWORKS = "xpath=.//*[@id='cic-sans-general-associated-network']"
    ID_TEXT_ZONED = "xpath=.//*[@id='cic-sans-zoning-policy-zoned']"
    ID_TEXT_AUTOMATE_ZONING = "xpath=.//*[@id='cic-sans-zoning-policy-automate-zoning']"
    ID_TEXT_ZONING_POLICY = "xpath=.//*[@id='cic-sans-zoning-policy-zoning-policy']"
    ID_TEXT_USE_ALIASES = "xpath=.//*[@id='cic-sans-zoning-policy-use-aliases']"


class EditSANsElements(object):
    ID_SELECT_ACTION_EDIT = "xpath=//*[@id='cic-sans-edit-action']/a[text()='Edit']"
    ID_TOGGLE_AUTOMATE_ZONING = "xpath=.//*[@id='cic-sans-edit-san-automate-zoning-hpToggle']"
    ID_BUTTON_OK = "xpath=.//*[@id='cic-sans-edit-san-ok']"
    ID_DIALOG_EDIT_SANS = "xpath=.//*[@id='cic-sans-edit-san-form']"
    ID_ZONE_NAME_FORMAT = "xpath=.//*[@id='cic-sans-edit-san-zone-name-container']/div/div/span[1]"
    ID_INPUT_ZONE_NAME_FORMAT = "xpath=//*[@id='cic-sans-edit-san-zone-name-container']/div/div/span[@class='hp-cursor']"
    ID_ERROR_MESSAGE_EDIT_SANS = "xpath=.//*[@id='hp-form-message']/div[@class='hp-form-message-details']"
    ID_ZONE_NAME_FORMAT_TOKEN = "xpath=.//*[@id='cic-sans-edit-san-zone-name-container']/div/div/ul/li/span[text()='%s']"
    ID_ZONE_NAME_FORMAT_SERVER_PROFILE = "xpath=.//*[@id='cic-sans-edit-san-zone-name-container']/div/div/span[text()='server profile']"
    ID_ZONE_NAME_FORMAT_SERVER_PROFILE_CONNECTION = "xpath=.//*[@id='cic-sans-edit-san-zone-name-container']/div/div/span[text()='server profile connection']"
    ID_ZONE_NAME_FORMAT_SERVER_INITIATOR_WWPN = "xpath=.//*[@id='cic-sans-edit-san-zone-name-container']/div/div/ul/li/span[text()='server initiator WWPN']"
    ID_ZONE_NAME_FORMAT_STORAGE_SYSTEM = "xpath=.//*[@id='cic-sans-edit-san-zone-name-container']/div/div/ul/li/span[text()='storage system']"
    ID_ZONE_NAME_FORMAT_STORAGE_PORT_GROUP = "xpath=.//*[@id='cic-sans-edit-san-zone-name-container']/div/div/ul/li/span[text()='storage system port group']"
    ID_SELECT_ZONING_POLICY = "xpath=.//*[@id='cic-sans-panel-edit-zoningPolicy']/fieldset/ol/li/div/div/div/div"
    ID_SELECT_ZONING_POLICY_SIAT = "xpath=.//*[@id='cic-sans-panel-edit-zoningPolicy']/fieldset/ol/li/div/div/div/ol/li/span[text()='Single initiator / all targets']"
    ID_SELECT_ZONING_POLICY_SISSS = "xpath=.//*[@id='cic-sans-panel-edit-zoningPolicy']/fieldset/ol/li/div/div/div/ol/li/span[text()='Single initiator / single storage system']"
