#!/bin/sh
echo Running pycodestyle...
git diff  --name-only | grep '\.py' | awk '{print "\x27"$0"\x27"}' | xargs -r pycodestyle
echo Running pylint...
git diff  --name-only | grep '\.py' | awk '{print "\x27"$0"\x27"}' | xargs -r pylint
echo Running rflint...
git diff  --name-only | grep '\.txt$' | awk '{print "\x27"$0"\x27"}' | xargs -r rflint

