@echo off
@echo Running pycodestyle...
for /f "delims=" %%i in ('"git diff --name-only *.py"') do pycodestyle "%%i"
@echo Running pylint...
for /f "delims=" %%i in ('"git diff --name-only *.py"') do pylint "%%i"
@echo Running rflint...
for /f "delims=" %%i in ('"git diff --name-only *.txt *.robot"') do rflint --argumentfile=.rflintrc "%%i"