# (C) Copyright 2015 Hewlett-Packard Development Company, L.P.
# San Storage Server Profile Page Elements for PM-SAN


class ProfileSanStorageElements(object):
    # Elements that are visible from the Create Server Profile Page
    ID_CHKBOX_SAN_STORAGE_ADD = "xpath=//*[@id='cic-profile-add-manage-san']"
    ID_CHKBOX_SAN_STORAGE_EDIT = "xpath=//*[@id='cic-profile-edit-manage-san']"
    ID_OS_TYPE_DROP_DOWN = "xpath=//*[@id='cic-profile-manage-storage-volumes-container']//span[@class='selectBox-arrow']"
    ID_OS_TYPE_SELECT = "xpath=//*[@id='cic-profile-manage-storage-volumes-container']//span[text()='%s']"
    ID_BTN_ADD_STORAGE = "xpath=//*[@id='cic-profile-add-storage-volumes']"
    ID_CONNECTION_BANDWITH = "xpath=//input[@id='cic-profile-connection-bandwith']"
    ID_PROFILE_CREATION_COMPLETED = "xpath=//div[@id='hp-page-notifications']//div[@class='hp-state'][text()='Completed']"
    ID_PROFILE_CREATION_WARNING = "xpath=//div[@id='hp-page-notifications']//div[@class='hp-state'][text()='Warning']"
    ID_PROFILE_EDIT_MENU_DROP_DOWN = "xpath=//*[@id='cic-profile-panel-edit-selector']"
    ID_PROFILE_ADD_MENU_DROP_DOWN = "xpath=//*[@id='cic-profile-add-panel-selector']"
    ID_SAN_STORAGE_LINK_EDIT = "xpath=//*[@id='cic-profile-panel-edit-selector']//a[text()='SAN Storage']"
    ID_SAN_STORAGE_LINK_ADD = "xpath=//*[@data-panel-id='cic-profile-panel-add-storage-volumes']"
    ID_BTN_DELETE_PROFILE_YES = "xpath=//button[@id='cic-profile-delete-ok']"
    ID_CONNECTIONS_LINK_EDIT = "xpath=//*[@data-panel-id='cic-profile-panel-edit-networks']"
    ID_VOLUME_ATTACHMENTS_TABLE_ADD = "xpath=//table[@name='ccic-profile-add-storage-volumes-table']"
    ID_NEW_VOLUME_IN_VOLUME_ATTACHMENTS_TABLE = ID_VOLUME_ATTACHMENTS_TABLE_ADD + "//td[contains(text(),'%s')]"
    ID_NEW_VOLUME_REMOVE_FROM_VOLUME_ATTACHMENTS_TABLE = ID_NEW_VOLUME_IN_VOLUME_ATTACHMENTS_TABLE + "/../td/div[@class='hp-delete']"
    ID_SERVER_HARDWARE_TABLE = "//table[@id='DataTables_Table_1']/tbody/tr/td[2]"
    ID_CSS_PATH = "css=span.hp-page-item-count"
    ID_NUMBER_OF_CONNECTIONS = "xpath=//table[@name='cic-profile-edit-connections-table']/tbody/tr[last()-1]/td[2]"

    # Elements that are visible after clicking Add Volume
    ID_VOLUME_TYPE_DROP_DOWN = "xpath=//div[@class='hp-value'][@data-id='Existing volume']"
    ID_VOLUME_TYPE_NEW = "xpath=//li[@data-id='@_New_Volume_@']"
    ID_VOLUME_SELECT_DROPDOWN = "xpath=//*[@id='cic-profile-storage-volume-div']/div/div[2]"
    ID_VOLUME_SELECT = "xpath=//*[@id='cic-profile-storage-volume-div']//span[text()='%s']"
    ID_BTN_STORAGE_ADD = "xpath=//*[@id='cic-profile-storage-add']"
    ID_BTN_STORAGE_ADD_PLUS = "xpath=//*[@id='cic-profile-storage-addAgain']"
    ID_BTN_CANCEL = "xpath=//a[@class='hp-cancel hp-button']"
    ID_BTN_CANCEL_2 = "xpath=//button[@class='hp-cancel']"

    # Elements that are visible after clicking Existing Volume and Selecting a Volume
    ID_LUN_BTN_AUTO = "xpath=//*[@id='cic-profile-storage-lun-auto']"
    ID_LUN_BTN_MANUAL = "xpath=//*[@id='cic-profile-storage-lun-manual']"
    ID_TEXT_LUN = "xpath=//*[@id='cic-profile-storage-lun-manual-value']"
    ID_BTN_ADD_STORAGE_PATH = "xpath=//*[@id='cic-profile-storage-paths-add']"
    ID_BTN_ADD_STORAGE_PATH_DISABLED = "xpath=//*[@id='cic-profile-storage-paths-add'][@disabled='disabled']"
    ID_BTN_STORAGE_PATHS_REMOVE_ALL = "xpath=//*[@id='cic-profile-storage-paths-remove-all']"
    ID_BTN_STORAGE_PATHS_REMOVE_ALL_DISABLED = "xpath=//*[@id='cic-profile-storage-paths-remove-all'][@disabled='disabled']"
    ID_STORAGE_PATHS_TABLE = "xpath=//table[@name='cic-profile-storage-paths-table']"
    ID_NETWORK_IN_STORAGE_PATH_TABLE = "xpath=//*[@id='cic-profile-storage-paths-table']//a[text()='%s']"
    ID_BTN_EDIT_STORAGE_TARGETS = ID_NETWORK_IN_STORAGE_PATH_TABLE + "/../../..//div[@class='hp-edit']"
    ID_CHKBOX_ENABLE_STORAGE_PATH = ID_NETWORK_IN_STORAGE_PATH_TABLE + "/../../..//input[@class='cic-profile-storage-enabled-checkbox']"
    ID_BTN_REMOVE_STORAGE_PATH = ID_NETWORK_IN_STORAGE_PATH_TABLE + "/../../..//div[@class='hp-delete']"
    ID_MESSAGE_NO_MORE_STORAGE_PATHS = "xpath=//div[@id='cic-profile-storage-paths-no-more-message']"

    # Elements that are visible after clicking on the Gear icon in the Storage Paths Section
    ID_PROFILE_STORAGE_EDIT_TARGETS_AUTO = "xpath=//*[@id='profile-storage-edit-targets-auto']"
    ID_PROFILE_STORAGE_EDIT_TARGETS_MANUAL = "xpath=//*[@id='profile-storage-edit-targets-manual']"
    ID_BTN_OK_STORAGE_TARGETS = "xpath=//*[@id='profile-storage-edit-targets-add']"
    ID_STORAGE_TARGETPORTS_TABLE = "xpath=//*[@id='cic-profile-storage-targetports-table']"
    ID_STORAGE_TARGETPORTS_ENABLE_CHKBOX = ID_STORAGE_TARGETPORTS_TABLE + "//div[text()='%s']/../..//input[@class='enabledCheckBox']"
    ID_BTN_STORAGE_PATHS_CANCEL = "xpath=//*[@id='profile-storage-edit-targets-form']/footer//button[@class='hp-cancel']"

    # Elements that are visible after clicking on Add storage path
    ID_ADD_SPECIFIC_STORAGE_PATHS = "xpath=//*[@class='dataTables_scrollBody']//td[text()='%s']"
    ID_BTN_CONFIRM_ADD_STORAGE_PATH = "xpath=//*[@class='hp-form-controls hp-controls']/button[@class='hp-add hp-primary']"
    ID_BTN_ADD_AGAIN_STORAGE_PATH = "xpath=//*[@class='hp-form-controls hp-controls']/button[@class='hp-add-again']"
    ID_BTN_CANCEL_STORAGE_TARGETS = "xpath=//*[@class='hp-form-controls hp-controls']/button[@class='hp-cancel']"

    # Elements that are visible after clicking New Volume
    ID_NEW_VOLUME_NAME = "xpath=//*[@id='cic-profile-storage-volume-name']"
    ID_NEW_VOLUME_DESCRIPTION = "xpath=//*[@id='cic-profile-storage-volume-description']"
    ID_NEW_VOLUME_STORAGE_POOL_DROP_DOWN = "xpath=//*[@id='cic-profile-storage-pool-div']/div/div[2]"
    ID_NEW_VOLUME_STORAGE_POOL_SELECT = "xpath=//*[@id='cic-profile-storage-pool-div']/div/div[3]//span[text()='%s']"
    ID_NEW_VOLUME_STORAGE_POOL_INPUT = "xpath=//input[@id='cic-profile-storage-pool-input']"
    ID_NEW_VOLUME_CAPACITY = "xpath=//*[@id='cic-profile-storage-volume-capacity']"
    ID_PROVISIONING_DROP_DOWN = "xpath=//li[@id='cic-profile-storage-volume-provisioning-li']/div[@class='hp-select-form']/div[1]"
    ID_PROVISIONING_SELECT = "xpath=//li[@id='cic-profile-storage-volume-provisioning-li']/div/div/ol/li/span[text()='%s']"
    ID_CHKBOX_PERMANENT = "xpath=//*[@id='cic-profile-storage-volume-permanent-input']"

    # Elements that are visible in the san storage section of the server profile page
    ID_SAN_STORAGE_OVERVIEW = "xpath=//div[@id='cic-profile-show-overview-sanstorage']"
    ID_SAN_STORAGE_COUNT_ERROR = ID_SAN_STORAGE_OVERVIEW + "//a[@class='hp-summary-error hp-disabled']//span[text()='%s']"
    ID_SAN_STORAGE_COUNT_WARNING = ID_SAN_STORAGE_OVERVIEW + "//a[@class='hp-summary-warning hp-disabled']//span[text()='%s']"
    ID_SAN_STORAGE_COUNT_OK = ID_SAN_STORAGE_OVERVIEW + "//a[@class-'hp-summary-ok hp-disabled']//span[text()='%s']"
    ID_SAN_STORAGE_PROFILE_LINK = ID_SAN_STORAGE_OVERVIEW + "//a[@class='hp-anchor-uri']"
    ID_SAN_STORAGE_EDIT_ICON = ID_SAN_STORAGE_OVERVIEW + "//a[@id='cic-profile-edit-sanstorage-pane']"
    ID_SAN_STORAGE_TITLE = "xpath=//span[@data-localize='profiles.storage.section-title'][text()='SAN Storage']"
    ID_HOST_OS_TYPE = "xpath=//span[@id='cic-profile-show-storage-volumes-ostype']"
    ID_VOLUME_ATTACHMENTS_TABLE = "xpath=//li[@id='cic-profile-panel-details-storages']//table[@class='dataTable']"
    ID_VOLUME_NAME_IN_TABLE = ID_VOLUME_ATTACHMENTS_TABLE + "//a[text()='%s']"
    ID_VOLUME_PERMANENCE_IN_TABLE = ID_VOLUME_NAME_IN_TABLE + "/../../td[text()='%s']"
    ID_VOLUME_LUN_IN_TABLE = ID_VOLUME_NAME_IN_TABLE + "/../../td[text()='%s']"
    ID_VOLUME_POOL_IN_TABLE = ID_VOLUME_NAME_IN_TABLE + "/../..//a[text()='%s']"
    ID_VOLUME_SIZE_IN_TABLE = ID_VOLUME_NAME_IN_TABLE + "/../../td[text()='%s GiB']"
    ID_VOLUME_PROVISIONING_IN_TABLE = ID_VOLUME_NAME_IN_TABLE + "/../../td[text()='%s']"
    ID_VOLUME_SHARING_IN_TABLE = ID_VOLUME_NAME_IN_TABLE + "/../../td[text()='%s']"
    ID_NETWORKS_TABLE_FOR_VOLUME = ID_VOLUME_NAME_IN_TABLE + "/../../following-sibling::tr[1]//table"
    ID_NETWORK_FOR_VOLUME_IN_TABLE = ID_NETWORKS_TABLE_FOR_VOLUME + "//a[text()='%s']"
    ID_NEWTORK_TYPE_FOR_VOLUME_IN_TABLE = ID_NETWORK_FOR_VOLUME_IN_TABLE + "/../span[text()='%s']"
    ID_NETWORK_SERVER_INITIATOR_IN_TABLE = ID_NETWORK_FOR_VOLUME_IN_TABLE + "/../../..//div[text()='%s']"
    ID_NEWTORK_STORAGE_TARGET_IN_TABLE = ID_NETWORK_FOR_VOLUME_IN_TABLE + "/../../../td[text()='%s']"
    ID_NETWORK_ENABLED_IN_TABLE = ID_NETWORK_FOR_VOLUME_IN_TABLE + "/../../..//td[text()='%s']"
    ID_NO_STORAGE_PATHS_FOR_VOLUME = "xpath=//a[text()='%s']/../../following-sibling::tr[1]//div[text()='No storage paths']"

    # Elements that are visible after clicking on edit profile
    ID_STORAGE_VOLUMES_TABLE = "xpath=//table[@name='ccic-profile-edit-storage-volumes-table']"
    ID_VOLUME_IN_STORAGE_VOLUMES_TABLE = ID_STORAGE_VOLUMES_TABLE + "//a[text()='%s']"
    ID_VOLUME_PERMANENCE_STOR_VOL_TABLE = ID_VOLUME_IN_STORAGE_VOLUMES_TABLE + "/../../td[2]/div"
    ID_VOLUME_LUN_IN_STOR_VOL_TABLE = ID_VOLUME_IN_STORAGE_VOLUMES_TABLE + "/../../td[text()='%s']"
    ID_VOLUME_STOR_POOL_IN_STOR_VOL_TABLE = ID_VOLUME_IN_STORAGE_VOLUMES_TABLE + "/../..//a[text()='%s']"
    ID_VOLUME_SIZE_IN_STOR_VOL_TABLE = ID_VOLUME_IN_STORAGE_VOLUMES_TABLE + "/../../td[text()='%s GiB']"
    ID_VOLUME_PROVISIONING_IN_STOR_VOL_TABLE = ID_VOLUME_IN_STORAGE_VOLUMES_TABLE + "/../../td[text()='%s']"
    ID_VOLUME_SHARING_IN_STOR_VOL_TABLE = ID_VOLUME_IN_STORAGE_VOLUMES_TABLE + "/../../td[text()='%s']"
    ID_VOLUME_EDIT_IN_STOR_VOL_TABLE = ID_VOLUME_IN_STORAGE_VOLUMES_TABLE + "/../..//div[@class='hp-edit']"
    ID_VOLUME_REMOVE_FROM_STOR_VOL_TABLE = ID_VOLUME_IN_STORAGE_VOLUMES_TABLE + "/../../td/div[@class='hp-delete']"
    ID_CONNECTIONS_FOR_VOLUME_TABLE = ID_VOLUME_IN_STORAGE_VOLUMES_TABLE + "/../../following-sibling::tr[1]//table[1]"
    ID_NETWORK_FOR_VOL_IN_STOR_VOL_TABLE = ID_CONNECTIONS_FOR_VOLUME_TABLE + "//a[text()='%s']"
    ID_NEWTORK_TYPE_FOR_VOL_IN_STOR_VOL_TABLE = ID_NETWORK_FOR_VOL_IN_STOR_VOL_TABLE + "/../span[text()='%s']"
    ID_NETWORK_SERVER_INITIATOR_IN_STOR_VOL_TABLE = ID_NETWORK_FOR_VOL_IN_STOR_VOL_TABLE + "/../../..//div[text()='%s']"
    ID_NETWORK_STORAGE_TARGETS_IN_STOR_VOL_TABLE = ID_NETWORK_FOR_VOL_IN_STOR_VOL_TABLE + "/../../../td[text()='%s']"
    ID_NETWORK_ENABLED_IN_STOR_VOL_TABLE = ID_NETWORK_FOR_VOL_IN_STOR_VOL_TABLE + "/../../..//input[@type='checkbox'][@checked]"
    ID_BTN_OK_EDIT_PROFILE = "xpath=//*[@id='cic-profile-edit-ok']"
    ID_BTN_CANCEL_EDIT_PROFILE = "xpath=//*[@id='cic-profile-edit-cancel']"
    ID_BTN_ADD_VOLUME_EDIT_PROFILE = "xpath=//*[@id='cic-profile-edit-storage-volumes']"
    ID_BTN_DELETE_NON_PERMANENT_VOLUME = "xpath=//button[@class='hp-ok hp-primary'][@data-localize='profiles.delete.ok']"
    ID_BTN_CLOSE_EDIT_CONNECTION_WARNING = "xpath=//button[@id='cic-profile-edit-connection-san-confirm-warning-button']"
    ID_BTN_OK_REMOVE_CONNECTION = "xpath=//button[@class='hp-ok hp-primary'][@data-localize='profiles.delete.remove']"

    # Various Errors and Warnings and Messages
    ID_ERROR_NO_STORAGE_VOLUMES = "xpath=//*[@id='cic-profile-add-no-volumes']"
    ID_ERROR_INCORRECT_BANDWITH = "xpath=//*[@id='cic-profile-connection-bandwith-group']//label[@class='hp-error']"
    ID_ERROR_INVALID_EXISTING_VOLUME_NAME = "xpath=//*[@id='cic-profile-storage-volume-div']//div[@class='hp-search-combo hp-error']"
    ID_ERROR_NO_VOLUME_NAME_INPUT = "xpath=//li[@id='cic-profile-storage-volume-name-li']//label[@class='hp-error']"
    ID_ERROR_DESCRIPTION_TOO_LONG = "xpath=//*[@id='cic-profile-storage-volume-description-li']/div/label[@class='hp-error']"
    ID_ERROR_INCORRECT_LUN = "xpath=//li[@id='cic-profile-storage-lun-section']//label[@class='hp-error cic-profile-storage-lun-manual-section']"
    ID_ERROR_INVALID_STORAGE_POOL = "xpath=//*[@id='cic-profile-storage-pool-div']/div[2]/label[@class='hp-error']"
    ID_ERROR_INVALID_CAPACITY = "xpath=//*[@id='cic-profile-storage-capacity-div']/div/label[@class='hp-error']"
    ID_ERROR_LUN_LESS_THAN_ZERO = "xpath=//*[@id='cic-profile-storage-lun-section']//label[text()='Enter a value greater than or equal to 0.']"
    ID_LUN_HELP_MESSAGE = "xpath=//*[@id='cic-profile-storage-lun-section']//label[text()='Specify a number between 0 and 16383. Note that most operating systems will not accept values greater than 254 (255 for Linux)']"
    ID_ERROR_LUN_TOO_BIG = "xpath=//*[@id='cic-profile-storage-lun-section']//label[text()='Enter a value less than or equal to 16383']"
    ID_WARNING_NO_STORAGE_PATHS = "xpath=//*[@id='cic-profile-storage-paths-table-messages']"
    ID_WARNING_STORAGE_PATHS_PROFILE = "xpath=//div[@id='hp-form-message']/div[2]//div[@class='hp-details']"
    ID_WARNING_STORAGE_PATHS_VOLUME = "xpath=//*[@id='hp-form-message']//div[@class='hp-status hp-status-warning']"
    ID_WARNING_DUPLICATE_LUNS = "xpath=//*[@id='hp-form-message']//span[text()='A duplicate LUN was specified.']"
    ID_ERROR_DESCRIPTION_TOO_LONG = "xpath=//*[@id='cic-profile-storage-volume-description-li']//label[@class='hp-error']"
    ID_ERROR_INCORRECT_STORAGE_POOL_NAME = "xpath=//*[@id='cic-profile-storage-pool-div']//label[text()='An existing storage pool must be selected.']"
    ID_CAPACITY_ERROR = "xpath=//*[@id='cic-profile-storage-capacity-div']//label[@class='hp-error']"
    ID_WARNING_UPDATE_PROFILE = "xpath=//div[@id='hp-form-message']/div[2]//div[@class='hp-details']"
    ID_ERROR_NO_STORAGE_TARGETS = "xpath=//div[@class='hp-form-message-summary']/span[text()='Select at least one storage target']"
    ID_MESSAGE_NO_ADDED_VOLUMES = "xpath=//label[@id='cic-profile-show-volumes-message'][text()='No volumes have been added.']"
    ID_WARNING_DELETE_PROFILE_LOSE_SAN = "xpath=//div[@id='cic-profile-san-data-loss-warning']"
    ID_WARNING_UNMANAGE_SAN_STORAGE = "xpath=//div[@id='cic-profile-volume-delete-confirm-warning']"
    ID_WARNING_EDIT_CONNECTION_REMOVE_FROM_SAN = "xpath=//*[@id='cic-profile-edit-connection-san-confirm-warning']"
    ID_WARNING_REMOVE_CONNECTION_REMOVE_FROM_SAN = "xpath=//*[@id='cic-profile-connection-san-delete-confirm-warning']"
    ID_ERROR_DUPLICATE_LUN = "xpath=//span[contains(text(),'The LUN number %s already exists on server profile')]"
