import os
import sys
import environment_data as env

firmware = {"manageFirmware": True, "firmwareBaselineUri": env.FirmwareVersion, "forceInstallFirmware": False,
            "firmwareInstallType": "FirmwareOnlyOfflineMode", "firmwareActivationType": "Immediate"}

serverprofiles = {"name": "ovf1134_serverprofile",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "serverHardwareUri": "SH:" + env.servers[0]["serverHardwareUri"],
                  "serverHardwareTypeUri": "SHT:" + env.servers[0]["serverHardwareTypeUri"],
                  "enclosureGroupUri": "EG:" + env.egs[0]["enclosureGroupUri"],
                  "firmware": {"firmwareInstallType": None, "forceInstallFirmware": False,
                               "manageFirmware": False, "firmwareBaselineUri": None},
                  "affinity": "Bay", "hideUnusedFlexNics": True,
                  "macType": "Virtual", "wwnType": "Virtual",
                  "osDeploymentSettings": {"osDeploymentPlanUri": "dp1With1Nic_StaticAndDhcpNic",
                                           "osCustomAttributes": [{"name": "DomainName", "value": "hpe.com"},
                                                                  {"name": "Hostname", "value": "esxbay1"},
                                                                  {"name": "ManagementNIC.connectionid", "value": "3"},
                                                                  {"name": "ManagementNIC.dhcp", "value": "false"},
                                                                  {"name": "ManagementNIC.vlanid", "value": "0"},
                                                                  {"name": "ManagementNIC.ipv4disable", "value": "false"},
                                                                  {"name": "ManagementNIC.networkuri", "value": "ETH:" + env.networks["mgmt"]},
                                                                  {"name": "ManagementNIC.constraint", "value": "auto"},
                                                                  {"name": "Password", "value": None},
                                                                  {"name": "SSH", "value": "enabled"}],
                                           "osVolumeUri": None},
                  "connectionSettings": env.me_connSettings,
                  "bootMode": {"manageMode": True, "pxeBootPolicy": "Auto", "mode": "UEFIOptimized"},
                  "boot": {"manageBoot": True, "order": []},
                  "bios": {"manageBios": False, "overriddenSettings": []},
                  "localStorage": {},
                  "sanStorage": {"volumeAttachments": [], "manageSanStorage": False}}

new_profile_connection = {"id": 4, "name": "mgmt",
                          "functionType": "Ethernet", "networkUri": "ETH:" + env.networks["private_nw"],
                          "portId": "Auto", "requestedVFs": "0",
                          "macType": "Virtual", "wwpnType": "Virtual",
                          "allocatedMbps": 2500, "maximumMbps": 20000,
                          "boot": {"priority": "NotBootable"}}

# osDeploymentSettings with different attribute values
osDeploymentSettings = {"osDeploymentPlanUri": "dp1With1Nic_StaticAndDhcpNic",
                        "osCustomAttributes": [{"name": "DomainName", "value": "lab.local"},
                                               {"name": "Hostname", "value": "esxbay321"},
                                               {"name": "ManagementNIC.connectionid", "value": "3"},
                                               {"name": "ManagementNIC.dhcp", "value": "false"},
                                               {"name": "ManagementNIC.vlanid", "value": "0"},
                                               {"name": "ManagementNIC.ipv4disable", "value": "false"},
                                               {"name": "ManagementNIC.networkuri", "value": "ETH:" + env.networks["mgmt"]},
                                               {"name": "ManagementNIC.constraint", "value": "auto"},
                                               {"name": "Password", "value": 'admin123'},
                                               {"name": "SSH", "value": "enabled"}],
                        "osVolumeUri": None}

osdSettingsWithUserSpecified = {
    'osDeploymentPlanUri': 'dp1With1Nic_StaticAndDhcpNic', 'osVolumeUri': None,
    'osCustomAttributes': [{'name': 'DomainName', 'value': 'hpe.com'},
                           {'name': 'Hostname', 'value': 'esxbay3'},
                           {'name': 'Password', 'value': None},
                           {'name': 'SSH', 'value': 'enabled'},
                           {'name': 'ManagementNIC.constraint', 'value': 'userspecified'},
                           {'name': 'ManagementNIC.connectionid', 'value': '3'},
                           {'name': 'ManagementNIC.dhcp', 'value': 'false'},
                           {'name': 'ManagementNIC.ipv4disable', 'value': 'false'},
                           {'name': 'ManagementNIC.vlanid', 'value': '0'},
                           {'name': 'ManagementNIC.networkuri', 'value': 'ETH:' + env.networks["mgmt"]},
                           {'name': 'ManagementNIC.ipaddress', 'value': '15.212.167.98'},
                           {'name': 'ManagementNIC.gateway', 'value': '15.212.164.1'},
                           {'name': 'ManagementNIC.netmask', 'value': '255.255.252.0'},
                           {'name': 'ManagementNIC.dns1', 'value': '16.110.135.51'},
                           {'name': 'ManagementNIC.dns2', 'value': '16.110.135.52'}]}
