admin_credentials = {
    'userName': 'Administrator',
    'password': 'hpvse123'
}

ilo_credentials = {
    'username': 'Administrator',
    'password': 'hpvse123'
}

# PCI Vendor and device IDs for known Synergy FC mezz cards
# Not an exhaustive list, will have to add other adapters when available
HP_PCI_VENDOR_ID = 0x103c
HP_PCI_DEVICE_ID_QMH2572 = 0x338e  # QLogic QMH2572 8Gb FC HBA for HP BladeSystem c-Class
HP_PCI_DEVICE_ID_QMH2672 = 0x1939  # HP QMH2672 16Gb FC HBA for BladeSystem c-Class
HP_PCI_DEVICE_ID_LPe1605 = 0x1956  # HP LPe1605 16Gb FC HBA for BladeSystem c-Class
VALID_GEN9_FC_PCI_DEVICE_IDS = [HP_PCI_DEVICE_ID_QMH2572]
VALID_GEN10_FC_PCI_DEVICE_IDS = [HP_PCI_DEVICE_ID_QMH2572, HP_PCI_DEVICE_ID_QMH2672, HP_PCI_DEVICE_ID_LPe1605]

# The server's mezz slot with the FC mezz card used as first boot device
GEN9_FC_DEVICE_MEZZ_SLOT = 2
GEN10_FC_DEVICE_MEZZ_SLOT = 2

EG_NAME = 'EG'

# Enclosures
ENC1 = 'tb2'

GEN8_SH = "SH:" + '%s, bay 9' % ENC1
GEN9_SH = "SH:" + '%s, bay 4' % ENC1
GEN10_SH = "SH:" + '%s, bay 10' % ENC1

server_hardware_uris = [
    {
        'serverHardwareUri': GEN8_SH,
    },
    {
        'serverHardwareUri': GEN9_SH,
    },
    {
        'serverHardwareUri': GEN10_SH,
    },
]

# PROFILE1 SETTINGS
PROFILE1_NAME_PREFIX = 'OVF3218_FC_2_Boot_Target'
PROFILE1_UEFI_NAME = PROFILE1_NAME_PREFIX + " (UEFI)"
PROFILE1_BIOS_NAME = PROFILE1_NAME_PREFIX + " (BIOS)"
PROFILE1_SERVER_PROFILE_TYPE = "ServerProfileV10"


STORESERV_NAME = 'tb3par1'
STORESERV_POOL = 'FC_r1'
STORESERV_VOLUME_NAME = 'OVF3218_vol1'

FC_NETWORK_A = 'FC1'
FC_NETWORK_A_VSAN = 'VSAN20'
FC_NETWORK_B = 'FC2'
FC_NETWORK_B_VSAN = 'VSAN30'

gen9_ris_node = {"server": GEN9_SH,
                 "username": "Administrator",
                 "password": "hpvse123",
                 "path": "/redfish/v1/Systems/1/bios/boot/settings",
                 }

gen10_ris_node = {"server": GEN10_SH,
                  "username": "Administrator",
                  "password": "hpvse123",
                  "path": "/redfish/v1/Systems/1/bios/boot/settings",
                  }

# Start of Data

simplified_UEFI_FC_2x_boot_from_managed_SAN_storage_volume = {
    "type": PROFILE1_SERVER_PROFILE_TYPE,
    "name": PROFILE1_UEFI_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "templateCompliance": "Unknown",
    "serverHardwareUri": None,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "enclosureUri": 'ENC:' + ENC1,
    "affinity": "Bay",
    "associatedServer": None,
    "hideUnusedFlexNics": True,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Virtual",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "requestedVFs": None,
                "allocatedVFs": None,
                "macType": "Physical",
                "wwpnType": "Physical",
                "requestedMbps": "Auto",
                "allocatedMbps": 16000,
                "maximumMbps": 16000,
                "ipv4": None,
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                    "targets": []
                },
                "state": "Deployed",
                "status": "OK",
                "managed": True,
                "networkName": None,
                "lagName": None
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "macType": "Physical",
                "wwpnType": "Physical",
                "requestedMbps": "Auto",
                "allocatedMbps": 16000,
                "maximumMbps": 16000,
                "ipv4": None,
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                    "targets": []
                },
                "state": "Deployed",
                "status": "OK",
                "managed": True,
                "networkName": None,
                "lagName": None
            }
        ]
    },
    "bootMode": {
        "manageMode": True,
        "mode": "UEFI",
        "pxeBootPolicy": "Auto",
        "secureBoot": "Unmanaged"
    },
    "boot": {
        "manageBoot": True,
        "order": [
            "HardDisk"
        ]
    },
    "bios": {
        "manageBios": False,
        "overriddenSettings": [],
    },
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [],
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            }
        ],
    },
    "osDeploymentSettings": None,
}

simplified_BIOS_FC_2x_boot_from_managed_SAN_storage_volume = {
    "type": PROFILE1_SERVER_PROFILE_TYPE,
    "name": PROFILE1_BIOS_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "templateCompliance": "Unknown",
    "serverHardwareUri": None,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "enclosureUri": 'ENC:' + ENC1,
    "affinity": "Bay",
    "associatedServer": None,
    "hideUnusedFlexNics": True,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Virtual",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "requestedVFs": None,
                "allocatedVFs": None,
                "macType": "Physical",
                "wwpnType": "Physical",
                "requestedMbps": "Auto",
                "allocatedMbps": 16000,
                "maximumMbps": 16000,
                "ipv4": None,
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                    "targets": []
                },
                "state": "Deployed",
                "status": "OK",
                "managed": True,
                "networkName": None,
                "lagName": None
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "macType": "Physical",
                "wwpnType": "Physical",
                "requestedMbps": "Auto",
                "allocatedMbps": 16000,
                "maximumMbps": 16000,
                "ipv4": None,
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                    "targets": []
                },
                "state": "Deployed",
                "status": "OK",
                "managed": True,
                "networkName": None,
                "lagName": None
            }
        ]
    },
    "bootMode": {
        "manageMode": True,
        "mode": "BIOS",
        "secureBoot": "Unmanaged"
    },
    "boot": {
        "manageBoot": True,
        "order": [
            "HardDisk", "CD", "USB", "PXE"
        ]
    },
    "bios": {
        "manageBios": False,
        "overriddenSettings": [],
    },
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [],
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            }
        ],
    },
    "osDeploymentSettings": None,
}

simplified_UEFI_FC_1x_boot_from_managed_SAN_storage_volume = {
    "type": PROFILE1_SERVER_PROFILE_TYPE,
    "name": PROFILE1_UEFI_NAME,
    "description": "OVF393 Server Profile",
    "iscsiInitiatorNameType": "AutoGenerated",
    "templateCompliance": "Unknown",
    "serverHardwareUri": None,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "enclosureUri": 'ENC:' + ENC1,
    "affinity": "Bay",
    "associatedServer": None,
    "hideUnusedFlexNics": True,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Virtual",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "requestedVFs": None,
                "allocatedVFs": None,
                "macType": "Physical",
                "wwpnType": "Physical",
                "requestedMbps": "Auto",
                "allocatedMbps": 16000,
                "maximumMbps": 16000,
                "ipv4": None,
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                    "targets": []
                },
                "state": "Deployed",
                "status": "OK",
                "managed": True,
                "networkName": None,
                "lagName": None
            }
        ]
    },
    "bootMode": {
        "manageMode": True,
        "mode": "UEFI",
        "pxeBootPolicy": "Auto",
        "secureBoot": "Unmanaged"
    },
    "boot": {
        "manageBoot": True,
        "order": [
            "HardDisk"
        ]
    },
    "bios": {
        "manageBios": False,
        "overriddenSettings": [],
    },
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [],
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            }
        ],
    },
    "osDeploymentSettings": None,
}

gen9_2target_clp = {
    "oa": "15.242.129.42",
    "username": "Administrator",
    "password": "mccmgmt",
    "bay": "4",
    "validate":
    """
Blade 4 mezz F: NOT FOUND
--------------------------------------
HP FlexFabric 10Gb 2-port 534M Adapter
Mezz=1 DevID=4Eh (off=0300h)
--------------------------------------
  FIP: 0 (off=031Ch)
     PID01: "set netport1 default"
     PID02: "exit"
  FIP: 1 (off=033Ch)
     PID01: "set netport1 default"
     PID02: "exit"
--------------------------------------
QLogic QMH2572 8Gb FC HBA for HP BladeSystem c-Class
Mezz=2 DevID=4Ch (off=0200h)
--------------------------------------
  FIP: 0 (off=021Ch)
     PID01: "set netport1 default"
     PID02: "set netport1 OEMHP_hss=1414"
     PID32: "set netport1 OEMHP_BootEnable=enabled"
     PID33: "set netport1 OEMHP_TargetPortName=21110002AC0085EC"
     PID34: "set netport1 OEMHP_TargetLUN=0001"
     PID35: "set netport1 OEMHP_TargetBootPaths[00]=21110002AC0085EC;0000000000000001"
     PID36: "set netport1 OEMHP_TargetBootPaths[01]=20110002AC0085EC;0000000000000001"
     PID03: "exit"
  FIP: 1 (off=0371h)
     PID01: "set netport2 default"
     PID02: "set netport2 OEMHP_hss=1412"
     PID32: "set netport2 OEMHP_BootEnable=enabled"
     PID33: "set netport2 OEMHP_TargetPortName=21120002AC0085EC"
     PID34: "set netport2 OEMHP_TargetLUN=0001"
     PID35: "set netport2 OEMHP_TargetBootPaths[00]=21120002AC0085EC;0000000000000001"
     PID36: "set netport2 OEMHP_TargetBootPaths[01]=20120002AC0085EC;0000000000000001"
     PID03: "exit"
Blade 4 mezz 3: NOT FOUND
--------------------------------------
HP FlexFabric 10Gb 2-port 536FLB Adapter
Mezz=9 (FLB=1) DevID=40h (off=0300h)
--------------------------------------
  FIP: 0 (off=031Ch)
     PID01: "set netport1 default"
     PID02: "exit"
  FIP: 1 (off=033Ch)
     PID01: "set netport1 default"
     PID02: "exit"
--------------------------------------
HP FlexFabric 10Gb 2-port 536FLB Adapter
Mezz=A (FLB=2) DevID=41h (off=0300h)
--------------------------------------
  FIP: 0 (off=031Ch)
     PID01: "set netport1 default"
     PID02: "exit"
  FIP: 1 (off=033Ch)
     PID01: "set netport1 default"
     PID02: "exit"
"""
}

gen9_1target_clp = {
    "oa": "15.242.129.42",
    "username": "Administrator",
    "password": "mccmgmt",
    "bay": "4",
    "validate":
    """
Blade 4 mezz F: NOT FOUND
--------------------------------------
HP FlexFabric 10Gb 2-port 534M Adapter
Mezz=1 DevID=4Eh (off=0300h)
--------------------------------------
  FIP: 0 (off=031Ch)
     PID01: "set netport1 default"
     PID02: "exit"
  FIP: 1 (off=033Ch)
     PID01: "set netport1 default"
     PID02: "exit"
--------------------------------------
QLogic QMH2572 8Gb FC HBA for HP BladeSystem c-Class
Mezz=2 DevID=4Ch (off=0200h)
--------------------------------------
  FIP: 0 (off=021Ch)
     PID01: "set netport1 default"
     PID02: "set netport1 OEMHP_hss=1414"
     PID32: "set netport1 OEMHP_BootEnable=enabled"
     PID33: "set netport1 OEMHP_TargetPortName=21110002AC0085EC"
     PID34: "set netport1 OEMHP_TargetLUN=0001"
     PID35: "set netport1 OEMHP_TargetBootPaths[00]=21110002AC0085EC;0000000000000001"
     PID36: "set netport1 OEMHP_TargetBootPaths[01]=20110002AC0085EC;0000000000000001"
     PID03: "exit"
  FIP: 1 (off=0371h)
     PID01: "set netport2 default"
     PID02: "set netport2 OEMHP_hss=1412"
     PID03: "exit"
Blade 4 mezz 3: NOT FOUND
--------------------------------------
HP FlexFabric 10Gb 2-port 536FLB Adapter
Mezz=9 (FLB=1) DevID=40h (off=0300h)
--------------------------------------
  FIP: 0 (off=031Ch)
     PID01: "set netport1 default"
     PID02: "exit"
  FIP: 1 (off=033Ch)
     PID01: "set netport1 default"
     PID02: "exit"
--------------------------------------
HP FlexFabric 10Gb 2-port 536FLB Adapter
Mezz=A (FLB=2) DevID=41h (off=0300h)
--------------------------------------
  FIP: 0 (off=031Ch)
     PID01: "set netport1 default"
     PID02: "exit"
  FIP: 1 (off=033Ch)
     PID01: "set netport1 default"
     PID02: "exit"
"""
}

gen10_clp = {
    "oa": "15.242.129.42",
    "username": "Administrator",
    "password": "mccmgmt",
    "bay": "10",
    "validate":
    """
Blade 10 mezz F: NOT FOUND
--------------------------------------
HP FlexFabric 20Gb 2-port 630M Adapter
Mezz=1 DevID=4Eh (off=0300h)
--------------------------------------
  FIP: 0 (off=031Ch)
     PID01: "set netport1 default"
     PID02: "exit"
  FIP: 1 (off=033Ch)
     PID01: "set netport1 default"
     PID02: "exit"
--------------------------------------
HP QMH2672 16Gb FC HBA for BladeSystem c-Class
Mezz=2 DevID=4Ch (off=0200h)
--------------------------------------
  FIP: 0 (off=021Ch)
     PID01: "set netport1 default"
     PID02: "set netport1 OEMHP_hss=1416"
     PID32: "set netport1 OEMHP_BootEnable=enabled"
     PID33: "set netport1 OEMHP_TargetPortName=21110002AC0085EC"
     PID34: "set netport1 OEMHP_TargetLUN=0001"
     PID35: "set netport1 OEMHP_TargetBootPaths[00]=21110002AC0085EC;0000000000000001"
     PID36: "set netport1 OEMHP_TargetBootPaths[01]=20110002AC0085EC;0000000000000001"
     PID03: "exit"
  FIP: 1 (off=0371h)
     PID01: "set netport2 default"
     PID02: "set netport2 OEMHP_hss=1411"
     PID32: "set netport2 OEMHP_BootEnable=enabled"
     PID33: "set netport2 OEMHP_TargetPortName=21120002AC0085EC"
     PID34: "set netport2 OEMHP_TargetLUN=0001"
     PID35: "set netport2 OEMHP_TargetBootPaths[00]=21120002AC0085EC;0000000000000001"
     PID36: "set netport2 OEMHP_TargetBootPaths[01]=20120002AC0085EC;0000000000000001"
     PID03: "exit"
--------------------------------------
HP FlexFabric 10Gb 2-port 536FLB Adapter
Mezz=9 (FLB=1) DevID=40h (off=0300h)
--------------------------------------
  FIP: 0 (off=031Ch)
     PID01: "set netport1 default"
     PID02: "exit"
  FIP: 1 (off=033Ch)
     PID01: "set netport1 default"
     PID02: "exit"
"""
}
