print "Developed By HP India"

FUSION_IP = r'15.212.143.180'  # HP One View Appliance IP
BROWSER = r'firefox'

FUSION_ADMIN_LOGIN = r'Administrator'        # Credentials for login to HP One View
FUSION_ADMIN_PASSWORD = r'hpvse123'


loggerlevel = r'INFO'   # use INFO|DEBUG

# below  are the variable for Natasha_F175
enclosure_uri = r'/rest/enclosures'
sas_interconnect_uri = r'/rest/sas-interconnects'
drive_enclosure_uri = r'/rest/drive-enclosures'
sas_interconnect_state = r'Monitored'
drive_enclosure_state = r'Monitored'
enclosure_state = r'Monitored'
natasha_model = r'Synergy 12Gb SAS Connection Module'
big_Bird_model = r'Synergy D3940 Storage Module'
power_state = r'On'
task_create_status = r'Added SAS logical Interconnect group'
task_delete_status = r'Deleted sas-logical-interconnect-groups successfully'
task_create_status = r'None'
task_delete_status = r'None'
Delete_LIG_Status = r'None'
task_state = r'Completed'
lig_state = r'Active'
permittedInterconnectTypeUri = '/rest/sas-interconnect-types/Synergy12GbSASConnectionModule'


# below variables are for F176.txt
LIG_Names = ['RGLIG14']
bay_list = [[1, 4]]
baylistno = []

UI_LIG_name = 'RGLIGbay1updated'


# Variables for LE Creation New
# EG_NAME = 'RGLE_EG'
# LE_Name = 'RGLE1'
# LE_Enc_Num = 3
EGNAMENO = 'EGforOneencl'
LENAMENO = 'CHO-LE'
logicalEnclosureUri = r'/rest/logical-enclosures'
enclosureGroupUri = r'/rest/enclosure-groups'


# variables for server profile creation
serverProfileUri = r'/rest/server-profiles/'
server_profile_create_status = r'Created server profile: RG_SP0.'
serverHardwareTypeUri = r'/rest/server-hardware-types'


# variables for sas-logical-jbod
LJbodminSizeGB = 1999
LJbodmaxSizeGB = 11446411
sasLogicalJbodType = r'sas-logical-jbod'
sasLogicalInterconnectUri = r'/rest/sas-logical-interconnects/'
sasLogicalJbodUri = r'/rest/sas-logical-jbods'
sasLogicalJbodAttachmentType = r'sas-logical-jbod-attachment'
LE_Create_task_status = r'None'  # r'Logical Enclosure Created successfully.'
sasLJbod_task_create_status = r'None'  # "SAS logical JBOD created successfully."
sasLJbod_task_delete_status = r'None'  # Removed SAS logical JBOD successfully."
numofServerProfiles = 1
# sasLJbodNumPerServerProfile = 1 #  sasLJbodNumPerLI/numofServerProfiles
sasLJbodNumPerLI = 1
num_Jbod_Drives = 1  # Number of Drives in each LJbod
sasLJbodAttachment_create_status = "SAS logical JBOD attachment created successfully."
sasLogicalJbodAttachmentUri = r'/rest/sas-logical-jbod-attachments'
logicalEnclosure_task_delete_status = "SAS logical interconnect deleted successfully."
serverProfileType = "ServerProfileV9"
serverHardwareUri = r'/rest/server-hardware'
SP_Name1 = "CHO_SP"


# Enclosures
ENC1 = 'CN7545022Y'

# Natasha SAS interconnects
ENC1SASICBAY1 = '%s, interconnect 1' % ENC1
ENC1SASICBAY4 = '%s, interconnect 4' % ENC1


# Drive Enclosures (Bigbird)
ENC1DEBAY1 = '%s, bay 1' % ENC1
ENC1DEBAY9 = '%s, bay 7' % ENC1

# Server Hardware
ENC1SHBAY7 = '%s, bay 3' % ENC1


SPpayload1 = {
    "type": "ServerProfileV9",
    "serverHardwareUri": "SH:" + ENC1 + ", bay 3",
    # "serverHardwareTypeUri": "/rest/server-hardware-types/CA134FA9-A437-4B0E-9BD0-1E3AAB68EAFE",
    "enclosureGroupUri": "EG:EGforOneencl",
    "serialNumberType": "Virtual",
    "iscsiInitiatorNameType": "AutoGenerated",
    "macType": "Virtual",
    "wwnType": "Virtual",
    "name": "CHO_SP",
    "description": "",
    "affinity": "Bay",
    "connectionSettings": {
            "connections": []
    },
    "boot": None,
    "bootMode": {
        "manageMode": False
    },
    "firmware": {
        "manageFirmware": False,
        "firmwareBaselineUri": "",
        "forceInstallFirmware": False,
        "firmwareInstallType": None,
        "firmwareScheduleDateTime": "",
        "firmwareActivationType": "Immediate"
    },
    "bios": {
        "manageBios": False,
        "overriddenSettings": []
    },
    "hideUnusedFlexNics": True,
    "iscsiInitiatorName": "",
    "osDeploymentSettings": None,
    "localStorage": {
        "sasLogicalJBODs": [{
            "id": 1,
            "deviceSlot": "Mezz 1",
            "name": "SAS-ljbod-001",
            "numPhysicalDrives": 1,
            "driveMinSizeGB": 1,
            "driveMaxSizeGB": 1000,
            "driveTechnology": "SasHdd",
            "eraseData": "false",
            # "sasLogicalJBODUri": "null"
        }, {
            "id": 2,
            "deviceSlot": "Mezz 1",
            "name": "SAS-ljbod-002",
            "numPhysicalDrives": 1,
            "driveMinSizeGB": 1,
            "driveMaxSizeGB": 1000,
            "driveTechnology": "SasHdd",
            "eraseData": "false",
            # "sasLogicalJBODUri": "null"
        }],
        "controllers": []
    },
    "sanStorage": None,
    "initialScopeUris": []
}


Edit_SP_global = {
    "type": "ServerProfileV9",
    "serverHardwareUri": "SH:" + ENC1 + ", bay 3",
    # "serverHardwareTypeUri": "/rest/server-hardware-types/CA134FA9-A437-4B0E-9BD0-1E3AAB68EAFE",
    "enclosureGroupUri": "EG:EGforOneencl",
    "serialNumberType": "Virtual",
    "iscsiInitiatorNameType": "AutoGenerated",
    "macType": "Virtual",
    "wwnType": "Virtual",
    "name": "CHO_SP",
    "description": "",
    "affinity": "Bay",
    "connectionSettings": {
            "connections": []
    },
    "boot": None,
    "bootMode": {
        "manageMode": False
    },
    "firmware": {
        "manageFirmware": False,
        "firmwareBaselineUri": "",
        "forceInstallFirmware": False,
        "firmwareInstallType": None,
        "firmwareScheduleDateTime": "",
        "firmwareActivationType": "Immediate"
    },
    "bios": {
        "manageBios": False,
        "overriddenSettings": []
    },
    "hideUnusedFlexNics": True,
    "iscsiInitiatorName": "",
    "osDeploymentSettings": None,
    "localStorage": {
        "sasLogicalJBODs": [{
            "id": 1,
            "deviceSlot": "Mezz 1",
            "name": "SAS-ljbod-001",
            "sasLogicalJBODUri": "SASLJBOD:" + "SAS-ljbod-001",
            "numPhysicalDrives": 1,
            "driveMinSizeGB": 1,
            "driveMaxSizeGB": 1000,
            "driveTechnology": "SasHdd",
            "eraseData": "false",
            # "sasLogicalJBODUri": "null"
        },
            {
            "id": 2,
                "deviceSlot": "Mezz 1",
                "name": "SAS-ljbod-002",
                        "sasLogicalJBODUri": "SASLJBOD:" + "SAS-ljbod-002",
                        "numPhysicalDrives": 1,
                        "driveMinSizeGB": 1,
                        "driveMaxSizeGB": 1000,
                        "driveTechnology": "SasHdd",
                        "eraseData": "false",
                        # "sasLogicalJBODUri": "null"
        },
            {"id": 3,
             "deviceSlot": "Mezz 1",
             "name": "SAS-ljbod-003",
             "numPhysicalDrives": 1,
             "driveMinSizeGB": 1,
             "driveMaxSizeGB": 10000,
             "driveTechnology": "SasHdd"
             # "sasLogicalJBODUri": "null"
             }
        ],
        "controllers": []
    },
    "sanStorage": None,
    "initialScopeUris": []
}


# variables for F636
# sas_interconnect_CPU_Reset_status=r'SAS Interconnect CPU reset control request is completed.'
# sas_interconnect_Device_Reset_status=r'SAS Interconnect device reset control request is completed.'
# sas_interconnect_power_control_status=r'SAS Interconnect power control request is completed.'
# sas_interconnect_uid_light_control_status=r'SAS Interconnect UID light control request is completed.'
# drive_enc_device_reset_status=r'DriveEnclosure device reset control request is completed.'
# drive_enc_power_control_status=r'DriveEnclosure power control request is completed.'
# drive_enc_uid_light_control_status=r'DriveEnclosure UID light control request is completed.'

# variables for F636
sas_interconnect_CPU_Reset_status = r'None'
sas_interconnect_Device_Reset_status = r'None'
sas_interconnect_power_control_status = r'None'
sas_interconnect_uid_light_control_status = r'None'
drive_enc_device_reset_status = r'None'
drive_enc_power_control_status = r'None'
drive_enc_uid_light_control_status = r'None'
