admin_credentials = {
    'userName': 'Administrator',
    'password': 'hpvse123'
}

ilo_credentials = {
    'username': 'Administrator',
    'password': 'hpvse123'
}

# PCI Vendor and device IDs for known Synergy FCoE capable mezz cards
HP_PCI_VENDOR_ID = 0x103c
HP_PCI_DEVICE_ID_2820C = 0x8107  # Quiz 10Gb CNA
HP_PCI_DEVICE_ID_3820C = 0x2231  # Bronco 10/20Gb CNA
VALID_FCOE_PCI_DEVICE_IDS = [HP_PCI_DEVICE_ID_2820C, HP_PCI_DEVICE_ID_3820C]

# The server's mezz slot with the FC mezz card used as first boot device
FCOE_DEVICE_MEZZ_SLOT = 3

EG_NAME = 'EG'

# Enclosures
ENC1 = 'MXQ72605PS'

# Gen10 server hardware bay
ENC1SHBAY1 = '%s, bay 1' % ENC1

server_hardware_uris = [
    {
        'serverHardwareUri': 'SH:' + ENC1SHBAY1,
    },
]

# PROFILE1 SETTINGS
PROFILE1_NAME_PREFIX = 'OVF393_Gen10_FCoE_Boot'
PROFILE1_UEFI_NAME = PROFILE1_NAME_PREFIX + " (UEFI)"
PROFILE1_BIOS_NAME = PROFILE1_NAME_PREFIX + " (BIOS)"
PROFILE1_SH = "SH:" + ENC1SHBAY1

STORESERV_NAME = 'tb3par1'
STORESERV_POOL = 'FC_r1'
STORESERV_VOLUME_NAME = 'OVF393_Gen10_vol1'

FCOE_NETWORK_A = 'FCoE-A'
FCOE_NETWORK_A_VSAN = 'VSAN20'
FCOE_NETWORK_B = 'FCoE-B'
FCOE_NETWORK_B_VSAN = 'VSAN30'

ris_node = {"server": ENC1SHBAY1,
            "username": "Administrator",
            "password": "hpvse123",
            "path": "/redfish/v1/Systems/1/bios/boot/settings",
            }

# Start of Data

simplified_UEFI_FCoE_2x_boot_from_managed_SAN_storage_volume = {
    "type": "ServerProfileV9",
    "name": PROFILE1_UEFI_NAME,
    "description": "OVF393 Server Profile",
    "iscsiInitiatorNameType": "AutoGenerated",
    "templateCompliance": "Unknown",
    "serverHardwareUri": PROFILE1_SH,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "enclosureUri": 'ENC:' + ENC1,
    "affinity": "Bay",
    "associatedServer": None,
    "hideUnusedFlexNics": True,
    "macType": "Physical",
    "wwnType": "Virtual",
    "serialNumberType": "Virtual",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FCOE:" + FCOE_NETWORK_A,
                "portId": "Auto",
                "requestedVFs": None,
                "allocatedVFs": None,
                "macType": "Physical",
                "wwpnType": "Virtual",
                "requestedMbps": "2500",
                "allocatedMbps": 16000,
                "maximumMbps": 16000,
                "ipv4": None,
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                    "targets": []
                },
                "state": "Deployed",
                "status": "OK",
                "managed": True,
                "networkName": None,
                "lagName": None
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FCOE:" + FCOE_NETWORK_B,
                "portId": "Auto",
                "macType": "Physical",
                "wwpnType": "Virtual",
                "requestedMbps": "2500",
                "allocatedMbps": 16000,
                "maximumMbps": 16000,
                "ipv4": None,
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                    "targets": []
                },
                "state": "Deployed",
                "status": "OK",
                "managed": True,
                "networkName": None,
                "lagName": None
            }
        ]
    },
    "bootMode": {
        "manageMode": True,
        "mode": "UEFI",
        "pxeBootPolicy": "Auto",
        "secureBoot": "Unmanaged"
    },
    "boot": {
        "manageBoot": True,
        "order": [
            "HardDisk"
        ]
    },
    "bios": {
        "manageBios": False,
        "overriddenSettings": [],
    },
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [],
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "isBootVolume": True,
            }
        ],
    },
    "osDeploymentSettings": None,
}

simplified_BIOS_FCoE_2x_boot_from_managed_SAN_storage_volume = {
    "type": "ServerProfileV9",
    "name": PROFILE1_BIOS_NAME,
    "description": "OVF393 Server Profile",
    "iscsiInitiatorNameType": "AutoGenerated",
    "templateCompliance": "Unknown",
    "serverHardwareUri": PROFILE1_SH,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "enclosureUri": 'ENC:' + ENC1,
    "affinity": "Bay",
    "associatedServer": None,
    "hideUnusedFlexNics": True,
    "macType": "Physical",
    "wwnType": "Virtual",
    "serialNumberType": "Virtual",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FCOE:" + FCOE_NETWORK_A,
                "portId": "Auto",
                "requestedVFs": None,
                "allocatedVFs": None,
                "macType": "Physical",
                "wwpnType": "Virtual",
                "requestedMbps": "2500",
                "allocatedMbps": 16000,
                "maximumMbps": 16000,
                "ipv4": None,
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                    "targets": []
                },
                "state": "Deployed",
                "status": "OK",
                "managed": True,
                "networkName": None,
                "lagName": None
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FCOE:" + FCOE_NETWORK_B,
                "portId": "Auto",
                "macType": "Physical",
                "wwpnType": "Virtual",
                "requestedMbps": "2500",
                "allocatedMbps": 16000,
                "maximumMbps": 16000,
                "ipv4": None,
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                    "targets": []
                },
                "state": "Deployed",
                "status": "OK",
                "managed": True,
                "networkName": None,
                "lagName": None
            }
        ]
    },
    "bootMode": {
        "manageMode": True,
        "mode": "BIOS",
        "secureBoot": "Unmanaged"
    },
    "boot": {
        "manageBoot": True,
        "order": [
            "HardDisk", "CD", "USB", "PXE"
        ]
    },
    "bios": {
        "manageBios": False,
        "overriddenSettings": [],
    },
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [],
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "isBootVolume": True,
            }
        ],
    },
    "osDeploymentSettings": None,
}

ts1_create_UEFI_profiles = [
    simplified_UEFI_FCoE_2x_boot_from_managed_SAN_storage_volume.copy()
]

ts1_create_BIOS_profiles = [
    simplified_BIOS_FCoE_2x_boot_from_managed_SAN_storage_volume.copy()
]
