def make_range_list(start, end, prefix='net_', suffix=''):
    rlist = []
    for x in xrange(start, end + 1):
        rlist.append(prefix + str(x) + suffix)
    return rlist

admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}

vcenter = {'server': '15.199.229.48', 'user': 'rbriggs', 'password': 'thisisit'}

appliance = {'type': 'ApplianceNetworkConfiguration',
             'applianceNetworks':
                 [{'device': 'eth0',
                   'macAddress': None,
                   'interfaceName': 'VLAN 106',
                   'activeNode': '1',
                   'unconfigure': False,
                   'ipv4Type': 'STATIC',
                   'ipv4Subnet': '255.255.0.0',
                   'ipv4Gateway': '192.173.0.1',
                   'ipv4NameServers': ['192.168.0.2'],
                   'app1Ipv4Addr': '192.173.0.10',
                   'ipv6Type': 'UNCONFIGURE',
                   'hostname': 'cic-rb.usa.hp.com',
                   'confOneNode': True,
                   'domainName': 'usa.hp.com',
                   'aliasDisabled': True}]}

timeandlocale = {'type': 'TimeAndLocale', 'dateTime': None, 'timezone': 'UTC', 'ntpServers': ['192.173.0.23'], 'locale': 'en_US.UTF-8'}

users = [{'userName': 'Serveradmin', 'password': 'Serveradmin', 'fullName': 'Serveradmin', 'roles': ['Server administrator'], 'emailAddress': 'sarah@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndRoles'},
         {'userName': 'Networkadmin', 'password': 'Networkadmin', 'fullName': 'Networkadmin', 'roles': ['Network administrator'], 'emailAddress': 'nat@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndRoles'},
         {'userName': 'Backupadmin', 'password': 'Backupadmin', 'fullName': 'Backupadmin', 'roles': ['Backup administrator'], 'emailAddress': 'backup@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndRoles'},
         {'userName': 'Noprivledge', 'password': 'Noprivledge', 'fullName': 'Noprivledge', 'roles': ['Read only'], 'emailAddress': 'rheid@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndRoles'}
         ]

licenses = [{'key': 'YCDC D9MA H9PQ KHX2 V7B5 HWWB Y9JL KMPL TA2E PDRA DXAU 2CSM GHTG L762 HUK7 GB5M KJVT D5KM EFRW DS5R TXXK 6Q22 AK2P 3EW2 AJQ4 HU5V TZZH AB6X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542007 HPOV-NFR1 HP_OneView_16_Seat_NFR 75YYJJECU46C"_3DWNY-6B2KD-D8Z6S-6YR4B-K8GDW'},
            {'key': '9CTC B9MA H9PA GHWY V7B5 HWWB Y9JL KMPL 3ASE NGRE DXAU 2CSM GHTG L762 FN83 EARE KJVT D5KM EFRW DS5R 3XPK 4T22 AK2P 3EW2 AJA6 XUNV TZZX MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542185 HPOV-NFR1 HP_OneView_16_Seat_NFR JJT5JJEC9DC5"_3JNBT-28349-3DJ6L-TBRPP-PDLNR'},
            {'key': '9B3C A99A H9P9 GHUZ U7B5 HWW5 Y9JL KMPL 5AWA 8CBE DXAU 2CSM GHTG L762 7NGZ GDV4 KJVT D5KM EFRW DS5R 5XP8 4XK2 GNSL 9F82 7JKT QVXB XZKH ABB4 NV2C LHXU KN7U 5NA6 BKRK 35QB D8UW R42A X3BN LQ6M 5V9A PM6Q 4MN9 9GGS EZU7 GEMX VUJW CDB5 JVRX 8HEN 2J98 ACPB "TKOPREN HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR ATJUJJEDAT2Y"'},
            {'key': 'QCTG B9MA H9P9 8HW3 V7B5 HWWB Y9JL KMPL 5AKE 8DBA DXAU 2CSM GHTG L762 VYW6 GCN9 KJVT D5KM EFVW DT5J 5XHK 5QK2 AK2P 3EW2 QJQ4 HU5V TZZ7 9B5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542022 HPOV-NFR1 HP_OneView_16_Seat_NFR AACUJJECUT2J"_3DWNY-DZZW8-24Y5Y-NZB2K-YH5R2'},
            {'key': '9CTC C9MA H9PY CHUY V7B5 HWWB Y9JL KMPL VACE 8GRE DXAU 2CSM GHTG L762 7RGY XHBE KJVT D5KM EFVW DT5J VX79 5T22 AK2P 3EW2 9JA6 XUNV TZZH MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542193 HPOV-NFR1 HP_OneView_16_Seat_NFR 9UH2JJECJ4AA"_3JNDQ-Z35J3-D6T6M-5XKZL-WC2W2'},
            {'key': 'YBLG B99A H9PQ 8HVZ U7B5 HWW5 Y9JL KMPL VAWA 8CBE DXAU 2CSM GHTG L762 5NW5 HDV4 KJVT D5KM EFVW DT5J VXP8 4XK2 GNSL 9F82 7JKT QVXB XZKH ABB4 NV2C LHXU KN7U 5NA6 BKRK 35QB D8UW R42A X3BN LQ6M 5V9A PM6Q 4MN9 9GGS EZU7 GEMX VUJW CDB5 JVRX 8HEN 2J98 ACPB "TKOPREN HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR JJADJJEDATCA"'},
            ]

ethernet_networks = [{'name': 'IC',
                      'type': 'ethernet-networkV3',
                      'vlanId': 1001,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'Untagged',
                      'type': 'ethernet-networkV3',
                      'vlanId': None,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Untagged'},
                     {'name': 'Tunnel',
                      'type': 'ethernet-networkV3',
                      'vlanId': None,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tunnel'}]

ethernet_ranges = [{'prefix': 'net_', 'suffix': 'a', 'start': 100, 'end': 200, 'name': None, 'type': 'ethernet-networkV3',
                    'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False,
                    'connectionTemplateUri': None,
                    'ethernetNetworkType': 'Tagged'},
                   {'prefix': 'net_', 'suffix': 'b', 'start': 100, 'end': 200, 'name': None,
                    'type': 'ethernet-networkV3',
                    'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False,
                    'connectionTemplateUri': None,
                    'ethernetNetworkType': 'Tagged'}]

fc_networks = [{'name': 'SAN-A', 'type': 'fc-networkV2', 'linkStabilityTime': 30, 'autoLoginRedistribution': True,
                'connectionTemplateUri': None, 'managedSanUri': None, 'fabricType': 'FabricAttach'},
               {'name': 'SAN-B', 'type': 'fc-networkV2', 'linkStabilityTime': 30, 'autoLoginRedistribution': True,
                'connectionTemplateUri': None, 'managedSanUri': None, 'fabricType': 'FabricAttach'}]

network_sets = []

network_set_ranges = [{'prefix': 'net_', 'suffix': 'a', 'start': 100, 'end': 200, 'name': 'VlanTrunkA', 'type': 'network-set',
                       'networkUris': None, 'nativeNetworkUri': 'net_100a'},
                      {'prefix': 'net_', 'suffix': 'b', 'start': 100, 'end': 200, 'name': 'VlanTrunkB', 'type': 'network-set',
                       'networkUris': None, 'nativeNetworkUri': 'net_100b'}]

fcoe_networks = []

fcoe_ranges = [{'prefix': 'fcoe-', 'suffix': 'a', 'start': 1001, 'end': 1032},
               {'prefix': 'fcoe-', 'suffix': 'b', 'start': 1001, 'end': 1032},
               {'prefix': 'fcoe-', 'suffix': 'c', 'start': 1001, 'end': 1032},
               {'prefix': 'fcoe-', 'suffix': 'd', 'start': 1001, 'end': 1032}]

enc_groups = [{'name': 'EG',
               'type': 'EnclosureGroupV200',
               'enclosureTypeUri': '/rest/enclosure-types/c7000',
               'stackingMode': 'Enclosure',
               'interconnectBayMappingCount': 8,
               'configurationScript': None,
               'interconnectBayMappings':
                   [{'interconnectBay': 1, 'logicalInterconnectGroupUri': 'LIG:LIG1'},
                    {'interconnectBay': 2, 'logicalInterconnectGroupUri': 'LIG:LIG1'},
                    {'interconnectBay': 3, 'logicalInterconnectGroupUri': None},
                    {'interconnectBay': 4, 'logicalInterconnectGroupUri': None},
                    {'interconnectBay': 5, 'logicalInterconnectGroupUri': None},
                    {'interconnectBay': 6, 'logicalInterconnectGroupUri': None},
                    {'interconnectBay': 7, 'logicalInterconnectGroupUri': None},
                    {'interconnectBay': 8, 'logicalInterconnectGroupUri': None}]}]

encs = [{'hostname': '192.173.0.11', 'username': 'Administrator', 'password': 'hpvse1', 'enclosureGroupUri': 'EG:EG',
         'force': False, 'licensingIntent': 'OneViewNoiLO'}]

uplink_sets = {'IC': {'name': 'IC',
                      'ethernetNetworkType': 'Tagged',
                      'networkType': 'Ethernet',
                      'networkUris': ['IC'],
                      'nativeNetworkUri': None,
                      'mode': 'Auto',
                      'logicalPortConfigInfos': [{'bay': '1', 'port': 'X4', 'speed': 'Auto'},
                                                 {'bay': '2', 'port': 'X4', 'speed': 'Auto'}]},
               'Tunnel1': {'name': 'Tunnel1',
                           'ethernetNetworkType': 'Tunnel',
                           'networkType': 'Ethernet',
                           'networkUris': ['Tunnel1'],
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'lacpTimer': 'Long',
                           'logicalPortConfigInfos': [{'bay': '1', 'port': 'X7', 'speed': 'Auto'},
                                                      {'bay': '2', 'port': 'X7', 'speed': 'Auto'}]},
               'Untagged': {'name': 'Untagged',
                            'ethernetNetworkType': 'Untagged',
                            'networkType': 'Ethernet',
                            'networkUris': ['Untagged'],
                            'nativeNetworkUri': None,
                            'mode': 'Auto',
                            'lacpTimer': 'Long',
                            'logicalPortConfigInfos': [{'bay': '1', 'port': 'X8', 'speed': 'Auto'},
                                                       {'bay': '2', 'port': 'X8', 'speed': 'Auto'}]},
               'SAN-A': {'name': 'SAN-A',
                         'ethernetNetworkType': 'NotApplicable',
                         'networkType': 'FibreChannel',
                         'networkUris': ['SAN-A'],
                         'nativeNetworkUri': None,
                         'mode': 'Auto',
                         'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X2', 'speed': 'Auto'}]},
               'SAN-B': {'name': 'SAN-B',
                         'ethernetNetworkType': 'NotApplicable',
                         'networkType': 'FibreChannel',
                         'networkUris': ['SAN-B'],
                         'nativeNetworkUri': None,
                         'mode': 'Auto',
                         'logicalPortConfigInfos': [{'bay': '2', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '2', 'port': 'X2', 'speed': 'Auto'}]},
               'BigPipe-A': {'name': 'BigPipe-A',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': make_range_list(101, 110, 'net_', 'a'),
                            'nativeNetworkUri': None,
                            'mode': 'Auto',
                            'logicalPortConfigInfos': [{'bay': '1', 'port': 'X5', 'speed': 'Auto'},
                                                       {'bay': '2', 'port': 'X5', 'speed': 'Auto'}]},
               'BigPipe-B': {'name': 'BigPipe-B',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': make_range_list(101, 110, 'net_', 'b'),
                            'nativeNetworkUri': None,
                            'mode': 'Auto',
                            'logicalPortConfigInfos': [{'bay': '1', 'port': 'X6', 'speed': 'Auto'},
                                                       {'bay': '2', 'port': 'X6', 'speed': 'Auto'}]},
               }

ligs = [{'name': 'LIG1',
         'type': 'logical-interconnect-groupV3',
         'enclosureType': 'C7000',
         'interconnectMapTemplate': [{'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
                                     {'enclosure': 1, 'enclosureIndex': 1, 'bay': 2, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
                                     ],
         'uplinkSets': [uplink_sets['SAN-A'],
                        uplink_sets['SAN-B'],
                        uplink_sets['BigPipe-A'],
                        uplink_sets['BigPipe-B']],
         'stackingMode': 'Enclosure',
         'ethernetSettings': None,
         'state': 'Active',
         'telemetryConfiguration': None,
         'snmpConfiguration': None}
        ]
telemetry = {'enableTelemetry': True, 'sampleInterval': 400, 'sampleCount': 20}

trapDestinations = [{'trapSeverities': ['Major'],
                     'enetTrapCategories': ['Other'],
                     'fcTrapCategories': ['Other'],
                     'vcmTrapCategories': ['Legacy'],
                     'trapFormat': 'SNMPv1',
                     'trapDestination': '192.168.99.99',
                     'communityString': 'public'}]

snmp = {'snmpAccess': ['192.168.1.0/24'],
        'trapDestinations': trapDestinations}

enet = {'enableFastMacCacheFailover': False}

ranges = [{'name': 'CMAC', 'type': 'Range', 'category': 'id-range-VMAC', 'rangeCategory': 'CUSTOM', 'startAddress': '12:11:11:00:00:00', 'endAddress': '12:11:11:0F:FF:FF', 'enabled': True},
          {'name': 'CWWN', 'type': 'Range', 'category': 'id-range-VWWN', 'rangeCategory': 'CUSTOM', 'startAddress': '10:00:1C:11:00:00:00:00', 'endAddress': '10:00:1C:11:00:0F:FF:FF', 'enabled': True},
          {'name': 'CSN', 'type': 'Range', 'category': 'id-range-VSN', 'rangeCategory': 'CUSTOM', 'startAddress': 'VCU1110000', 'endAddress': 'VCU1110ZZZ', 'enabled': True},
          #{"name": "172", "type": "Range", "startAddress": "172.0.0.2", "endAddress": "172.0.0.10", "rangeCategory": "CUSTOM", "subnet": {"networkId": "172.0.0.0", "domain": "test.domain.hp.com", "subnetmask": "255.255.255.0", "gateway": "172.0.0.1", "dnsServers": []}}
          ]

"""
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'WPST-PAAR63-EN1, bay 1',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PAAR63-EN1', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'Bay1-BL460cGen8-BFS', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_101a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b',
                                     'requestedMbps': '2500', 'networkUri': 'FC:SAN-A',
                                     'boot': {'priority': 'Primary', 'targets': [{'arrayWwpn': '20010002AC003D7E', 'lun': '02'}]}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_101b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''}]},

                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'WPST-PAAR63-EN1, bay 2',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PAAR63-EN1', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Virtual',
                    'name': 'Bay2-BL460cGen8-w2012', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:IC',
                                     'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_101a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b',
                                     'requestedMbps': '2500', 'networkUri': 'FC:SAN-A',
                                     'boot': {'priority': 'NotBootable'}, 'mactype': 'UserDefined', 'wwpnType': 'UserDefined', 'mac': '12:11:11:00:00:00', 'wwpn': '10:00:1C:11:00:00:00:01', 'wwnn': '10:00:1C:11:00:00:00:00'},
                                    {'id': 4, 'name': '4', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b',
                                     'requestedMbps': '2500', 'networkUri': 'FC:SAN-B',
                                     'boot': {'priority': 'NotBootable'}, 'mactype': 'UserDefined', 'wwpnType': 'UserDefined', 'mac': '12:11:11:00:00:01', 'wwpn': '10:00:1C:11:00:00:00:03', 'wwnn': '10:00:1C:11:00:00:00:02'},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c',
                                     'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunkA',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c',
                                     'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunkA',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d',
                                     'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunkB',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d',
                                     'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunkB',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''}]},

"""

server_profiles = [
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'WPST-PAAR63-EN1, bay 3',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PAAR63-EN1', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'Bay3-BL465cGen8-esxi6.0', 'description': 'hosts vCenter6 appliance', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': 'mgmt-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': 'mgmt-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': 'san-a', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-A',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': 'san-b', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-B',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': 'vmotion-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': 'vmotion-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': 'vmnetwork-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': 'vmnetwork-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''}]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'WPST-PAAR63-EN1, bay 9',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PAAR63-EN1', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'Bay9-BL465cGen8-esxi6.0a', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': 'mgmt-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': 'mgmt-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': 'san-a', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-A',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': 'san-b', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-B',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': 'vmotion-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': 'vmotion-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': 'vmnetwork-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': 'vmnetwork-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''}]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'WPST-PAAR63-EN1, bay 10',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PAAR63-EN1', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'Bay10-BL465cGen8-esxi6.0b', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': 'mgmt-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': 'mgmt-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': 'san-a', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-A',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': 'san-b', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-B',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': 'vmotion-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': 'vmotion-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': 'vmnetwork-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': 'vmnetwork-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''}]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'WPST-PAAR63-EN1, bay 11',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PAAR63-EN1', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'Bay11-BL460cGen9-esxi6.0a', 'description': '', 'affinity': 'Bay',
                    'bootMode': {'manageMode': True, 'mode': 'UEFI'},
                    'boot': {'manageBoot': True, 'order': ['HardDisk']},
                    'connections': [{'id': 1, 'name': 'mgmt-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': 'mgmt-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': 'san-a', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-A',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': 'san-b', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-B',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': 'vmotion-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': 'vmotion-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': 'vmnetwork-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': 'vmnetwork-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''}]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'WPST-PAAR63-EN1, bay 12',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PAAR63-EN1', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'Bay12-BL460cGen9-esxi6.0b', 'description': '', 'affinity': 'Bay',
                    'bootMode': {'manageMode': True, 'mode': 'UEFI'},
                    'boot': {'manageBoot': True, 'order': ['HardDisk']},
                    'connections': [{'id': 1, 'name': 'mgmt-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': 'mgmt-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a',
                                     'requestedMbps': '1000', 'networkUri': 'ETH:net_101b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': 'san-a', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-A',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': 'san-b', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b',
                                     'requestedMbps': '4000', 'networkUri': 'FC:SAN-B',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': 'vmotion-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': 'vmotion-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_107b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': 'vmnetwork-a', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108a',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': 'vmnetwork-b', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:net_108b',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''}]},
                ]
