"""
!!!!!!!!!!!!!!!!!!!!!!
REPLACE Encl1 with Encl1 for real hardware!!!!
!!!!!!!!!!!!!!!!!!!!!!
"""


def make_range_list(vrange):
    rlist = []
    for x in xrange(vrange['start'], (vrange['end'] + 1)):
        rlist.append(vrange['prefix'] + str(x) + vrange['suffix'])
    return rlist

admin_credentials = {'userName': 'Administrator', 'password': 'Wpst@hpvse123#!'}

vcenter = {'server': '15.199.230.130', 'user': 'rbriggs', 'password': 'hpvse1'}

appliance = {'type': 'ApplianceNetworkConfiguration',
             'applianceNetworks':
             [{'device': 'eth0',
               'macAddress': None,
               'interfaceName': '15.199.x.x',
               'activeNode': '1',
               'unconfigure': False,
               'ipv4Type': 'STATIC',
               'ipv4Subnet': '255.255.240.0',
               'ipv4Gateway': '15.199.224.1',
               'ipv4NameServers': ['16.110.135.51', '16.110.135.52'],
               'app1Ipv4Addr': '15.199.229.190',
               'ipv6Type': 'UNCONFIGURE',
               'hostname': 'efit-rb.usa.hp.com',
               'confOneNode': True,
               'domainName': 'usa.hp.com',
               'aliasDisabled': True,
               }],
             }

timeandlocale = {'type': 'TimeAndLocale', 'dateTime': None, 'timezone': 'UTC', 'ntpServers': ['ntp.hp.net'], 'locale': 'en_US.UTF-8'}

ranges = [{'name': 'CI-FIT-01-MAC', 'type': 'Range', 'category': 'id-range-VMAC', 'rangeCategory': 'CUSTOM', 'startAddress': 'A2:11:11:00:00:00', 'endAddress': 'A2:11:11:0F:FF:FF', 'enabled': True},
          {'name': 'CI-FIT-01-WWN', 'type': 'Range', 'category': 'id-range-VWWN', 'rangeCategory': 'CUSTOM', 'startAddress': '21:11:11:11:00:00:00:00', 'endAddress': '21:11:11:11:00:0F:FF:FF', 'enabled': True},
          {'name': 'CI-FIT-01-SN', 'type': 'Range', 'category': 'id-range-VSN', 'rangeCategory': 'CUSTOM', 'startAddress': 'VCUBBB0000', 'endAddress': 'VCUBBB0ZZZ', 'enabled': True}]


users = [{'userName': 'Serveradmin', 'password': 'Serveradmin', 'fullName': 'Serveradmin', 'roles': ['Server administrator'], 'emailAddress': 'sarah@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndRoles'},
         {'userName': 'Networkadmin', 'password': 'Networkadmin', 'fullName': 'Networkadmin', 'roles': ['Network administrator'], 'emailAddress': 'nat@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndRoles'},
         {'userName': 'Backupadmin', 'password': 'Backupadmin', 'fullName': 'Backupadmin', 'roles': ['Backup administrator'], 'emailAddress': 'backup@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndRoles'},
         {'userName': 'Noprivledge', 'password': 'Noprivledge', 'fullName': 'Noprivledge', 'roles': ['Read only'], 'emailAddress': 'rheid@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndRoles'}
         ]

licenses = [{'key': 'YCDE D9MA H9P9 8HUZ U7B5 HWW5 Y9JL KMPL MHND 7AJ9 DXAU 2CSM GHTG L762 LFH6 F4R4 KJVT D5KM EFVW DT5J 83HJ 8VC6 AK2P 3EW2 L9YE HUNJ TZZ7 MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEG 3F9V JQY5 "423207356 HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR H3TCJHCGAYAY"'},
            {'key': 'QC3C A9MA H9PQ GHVZ U7B5 HWW5 Y9JL KMPL 2HVF 4FZ9 DXAU 2CSM GHTG L762 7JX5 V5FU KJVT D5KM EFVW DV5J 43LL PSS6 AK2P 3EW2 T9YE XUNJ TZZ7 MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEG 3F9V JQY5 "423207566 HPOV-NFR2 HP_OneView_w/o_iLO_48_Seat_NFR 6H72JHCGY5AU"'}
            ]

ethernet_networks = [{'name': 'RDP',
                      'type': 'ethernet-networkV3',
                      'vlanId': 1001,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'IC',
                      'type': 'ethernet-networkV3',
                      'vlanId': None,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Untagged'},
                     {'name': 'Tunnel1',
                      'type': 'ethernet-networkV3',
                      'vlanId': None,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tunnel'},
                     {'name': 'Tunnel2',
                      'type': 'ethernet-networkV3',
                      'vlanId': None,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tunnel'},
                     ]

ethernet_ranges = [{'prefix': 'net_', 'suffix': '', 'start': 2, 'end': 50, 'name': None, 'type': 'ethernet-networkV3',
                    'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False, 'connectionTemplateUri': None,
                    'ethernetNetworkType': 'Tagged'},
                   {'prefix': 'net_', 'suffix': '', 'start': 51, 'end': 102, 'name': None, 'type': 'ethernet-networkV3',
                    'vlanId': None, 'purpose': 'General', 'smartLink': True, 'privateNetwork': False, 'connectionTemplateUri': None,
                    'ethernetNetworkType': 'Tagged'}]

network_sets = [{'name': 'NS_23', 'type': 'network-set', 'networkUris': ['net_23'], 'nativeNetworkUri': None},
                {'name': 'NS_24', 'type': 'network-set', 'networkUris': ['net_24'], 'nativeNetworkUri': None},
                {'name': 'NS_46', 'type': 'network-set', 'networkUris': ['net_46'], 'nativeNetworkUri': None},
                {'name': 'NS_47', 'type': 'network-set', 'networkUris': ['net_47'], 'nativeNetworkUri': None},
                {'name': 'NS_96', 'type': 'network-set', 'networkUris': ['net_96'], 'nativeNetworkUri': None},
                {'name': 'NS_97', 'type': 'network-set', 'networkUris': ['net_97'], 'nativeNetworkUri': None},
                {'name': 'NS_98', 'type': 'network-set', 'networkUris': ['net_98'], 'nativeNetworkUri': None},
                {'name': 'NS_99', 'type': 'network-set', 'networkUris': ['net_99'], 'nativeNetworkUri': None}]

network_set_ranges = [{'prefix': 'net_', 'suffix': '', 'start': 2, 'end': 22, 'name': 'VlanTrunk1', 'type': 'network-set', 'networkUris': None, 'nativeNetworkUri': None},
                      {'prefix': 'net_', 'suffix': '', 'start': 25, 'end': 45, 'name': 'VlanTrunk2', 'type': 'network-set', 'networkUris': None, 'nativeNetworkUri': 'net_25'},
                      {'prefix': 'net_', 'suffix': '', 'start': 50, 'end': 70, 'name': 'VlanTrunk3', 'type': 'network-set', 'networkUris': None, 'nativeNetworkUri': 'net_50'},
                      {'prefix': 'net_', 'suffix': '', 'start': 75, 'end': 95, 'name': 'VlanTrunk4', 'type': 'network-set', 'networkUris': None, 'nativeNetworkUri': 'net_75'}
                      ]

fc_networks = [{'name': 'SAN-1-A', 'type': 'fc-networkV2', 'linkStabilityTime': 30, 'autoLoginRedistribution': True, 'connectionTemplateUri': None, 'managedSanUri': None, 'fabricType': 'FabricAttach'},
               {'name': 'SAN-2-B', 'type': 'fc-networkV2', 'linkStabilityTime': 30, 'autoLoginRedistribution': True, 'connectionTemplateUri': None, 'managedSanUri': None, 'fabricType': 'FabricAttach'},
               {'name': 'SAN-3-A', 'type': 'fc-networkV2', 'linkStabilityTime': 30, 'autoLoginRedistribution': True, 'connectionTemplateUri': None, 'managedSanUri': None, 'fabricType': 'FabricAttach'},
               {'name': 'SAN-4-B', 'type': 'fc-networkV2', 'linkStabilityTime': 30, 'autoLoginRedistribution': True, 'connectionTemplateUri': None, 'managedSanUri': None, 'fabricType': 'FabricAttach'},
               {'name': 'SAN-5-A', 'type': 'fc-networkV2', 'linkStabilityTime': 30, 'autoLoginRedistribution': True, 'connectionTemplateUri': None, 'managedSanUri': None, 'fabricType': 'FabricAttach'},
               {'name': 'SAN-6-B', 'type': 'fc-networkV2', 'linkStabilityTime': 30, 'autoLoginRedistribution': True, 'connectionTemplateUri': None, 'managedSanUri': None, 'fabricType': 'FabricAttach'},
               ]

fcoe_networks = [{'name': 'fcoe-100', 'type': 'fcoe-network', 'vlanId': 100},
                 {'name': 'fcoe-101', 'type': 'fcoe-network', 'vlanId': 101},
                 ]

fcoe_ranges = [{'prefix': 'fcoe-', 'suffix': 'a', 'start': 1001, 'end': 1032},
               ]

fcoe_ranges = [{'prefix': 'fcoe-', 'suffix': '', 'start': 1000, 'end': 1255},]


enc_groups = [{'name': 'FFF8-8FC20-8FC24',
               'type': 'EnclosureGroupV200',
               'enclosureTypeUri': '/rest/enclosure-types/c7000',
               'stackingMode': 'Enclosure',
               'interconnectBayMappingCount': 8,
               'configurationScript': None,
               'interconnectBayMappings':
               [{'interconnectBay': 1, 'logicalInterconnectGroupUri': 'LIG:LIG-FFF8-8FC20-8FC24'},
                {'interconnectBay': 2, 'logicalInterconnectGroupUri': 'LIG:LIG-FFF8-8FC20-8FC24'},
                {'interconnectBay': 3, 'logicalInterconnectGroupUri': 'LIG:LIG-FFF8-8FC20-8FC24'},
                {'interconnectBay': 4, 'logicalInterconnectGroupUri': 'LIG:LIG-FFF8-8FC20-8FC24'},
                {'interconnectBay': 5, 'logicalInterconnectGroupUri': 'LIG:LIG-FFF8-8FC20-8FC24'},
                {'interconnectBay': 6, 'logicalInterconnectGroupUri': 'LIG:LIG-FFF8-8FC20-8FC24'},
                {'interconnectBay': 7, 'logicalInterconnectGroupUri': None},
                {'interconnectBay': 8, 'logicalInterconnectGroupUri': None}]},
              ]

encs = [{'hostname': '172.18.1.11', 'username': 'dcs', 'password': 'dcs', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'force': False, 'licensingIntent': 'OneViewNoiLO'}]

uplink_sets = {'RDP': {'name': 'RDP',
                       'ethernetNetworkType': 'Tagged',
                       'networkType': 'Ethernet',
                       'networkUris': ['RDP'],
                       'nativeNetworkUri': None,
                       'mode': 'Auto',
                       'logicalPortConfigInfos': [{'bay': '1', 'port': 'X5', 'speed': 'Auto'}]},
               'IC': {'name': 'IC',
                      'ethernetNetworkType': 'Untagged',
                      'networkType': 'Ethernet',
                      'networkUris': ['IC'],
                      'nativeNetworkUri': None,
                      'mode': 'Auto',
                      'logicalPortConfigInfos': [{'bay': '1', 'port': 'X4', 'speed': 'Auto'}]},
               'Tunnel1': {'name': 'Tunnel1',
                           'ethernetNetworkType': 'Tunnel',
                           'networkType': 'Ethernet',
                           'networkUris': ['Tunnel1'],
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'lacpTimer': 'Long',
                           'logicalPortConfigInfos': [{'bay': '1', 'port': 'X3', 'speed': 'Auto'}]},
               'Tunnel2': {'name': 'Tunnel2',
                           'ethernetNetworkType': 'Tunnel',
                           'networkType': 'Ethernet',
                           'networkUris': ['Tunnel2'],
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'lacpTimer': 'Long',
                           'logicalPortConfigInfos': [{'bay': '2', 'port': 'X3', 'speed': 'Auto'}]},
               'SAN-1-A': {'name': 'SAN-1-A',
                           'ethernetNetworkType': 'NotApplicable',
                           'networkType': 'FibreChannel',
                           'networkUris': ['SAN-1-A'],
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'logicalPortConfigInfos': [{'bay': '1', 'port': 'X7', 'speed': 'Auto'}]},
               'SAN-2-B': {'name': 'SAN-2-B',
                           'ethernetNetworkType': 'NotApplicable',
                           'networkType': 'FibreChannel',
                           'networkUris': ['SAN-2-B'],
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'logicalPortConfigInfos': [{'bay': '2', 'port': 'X7', 'speed': 'Auto'}]},
               'SAN-3-A': {'name': 'SAN-3-A',
                           'ethernetNetworkType': 'NotApplicable',
                           'networkType': 'FibreChannel',
                           'networkUris': ['SAN-3-A'],
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'logicalPortConfigInfos': [{'bay': '3', 'port': '1', 'speed': 'Auto'},
                                                      {'bay': '3', 'port': '2', 'speed': 'Auto'}]},
               'SAN-4-B': {'name': 'SAN-4-B',
                           'ethernetNetworkType': 'NotApplicable',
                           'networkType': 'FibreChannel',
                           'networkUris': ['SAN-4-B'],
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'logicalPortConfigInfos': [{'bay': '4', 'port': '1', 'speed': 'Auto'},
                                                      {'bay': '4', 'port': '2', 'speed': 'Auto'}]},
               'SAN-5-A': {'name': 'SAN-5-A',
                           'ethernetNetworkType': 'NotApplicable',
                           'networkType': 'FibreChannel',
                           'networkUris': ['SAN-5-A'],
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'logicalPortConfigInfos': [{'bay': '5', 'port': '1', 'speed': 'Auto'},
                                                      {'bay': '5', 'port': '2', 'speed': 'Auto'}]},
               'SAN-6-B': {'name': 'SAN-6-B',
                           'ethernetNetworkType': 'NotApplicable',
                           'networkType': 'FibreChannel',
                           'networkUris': ['SAN-6-B'],
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'logicalPortConfigInfos': [{'bay': '6', 'port': '1', 'speed': 'Auto'},
                                                      {'bay': '6', 'port': '2', 'speed': 'Auto'}]},
               'BigPipe1': {'name': 'BigPipe1',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': make_range_list(ethernet_ranges[0]),
                            'nativeNetworkUri': None,
                            'mode': 'Auto',
                            'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'},
                                                       {'bay': '1', 'port': 'X2', 'speed': 'Auto'}]},
               'BigPipe2': {'name': 'BigPipe2',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': make_range_list(ethernet_ranges[1]),
                            'nativeNetworkUri': None,
                            'mode': 'Auto',
                            'logicalPortConfigInfos': [{'bay': '2', 'port': 'X1', 'speed': 'Auto'},
                                                       {'bay': '2', 'port': 'X2', 'speed': 'Auto'}]},

               }

icmap = {"interconnectMapEntryTemplates": [{"logicalLocation": {"locationEntries": [{"relativeValue": 1, "type": "Bay"}, {"relativeValue": 1, "type": "Enclosure"}]}, "permittedInterconnectTypeUri": "HP VC FlexFabric-20/40 F8 Module", "enclosureIndex": 1},
                                                                       {"logicalLocation": {"locationEntries": [{"relativeValue": 1, "type": "Bay"}, {"relativeValue": 1, "type": "Enclosure"}]}, "permittedInterconnectTypeUri": "HP VC FlexFabric-20/40 F8 Module", "enclosureIndex": 1},
                                                                       {"logicalLocation": {"locationEntries": [{"relativeValue": 1, "type": "Bay"}, {"relativeValue": 1, "type": "Enclosure"}]}, "permittedInterconnectTypeUri": "HP VC 8Gb 20-Port FC Module", "enclosureIndex": 1},
                                                                       {"logicalLocation": {"locationEntries": [{"relativeValue": 1, "type": "Bay"}, {"relativeValue": 1, "type": "Enclosure"}]}, "permittedInterconnectTypeUri": "HP VC 8Gb 20-Port FC Module", "enclosureIndex": 1},
                                                                       {"logicalLocation": {"locationEntries": [{"relativeValue": 1, "type": "Bay"}, {"relativeValue": 1, "type": "Enclosure"}]}, "permittedInterconnectTypeUri": "HP VC 8Gb 24-Port FC Module", "enclosureIndex": 1},
                                                                       {"logicalLocation": {"locationEntries": [{"relativeValue": 1, "type": "Bay"}, {"relativeValue": 1, "type": "Enclosure"}]}, "permittedInterconnectTypeUri": "HP VC 8Gb 24-Port FC Module", "enclosureIndex": 1}]
    }

icmap = [{'bay': 1, 'enclosure': 1, 'type': 'HP VC FlexFabric-20/40 F8 Module', 'enclosureIndex': 1},
         {'bay': 2, 'enclosure': 1, 'type': 'HP VC FlexFabric-20/40 F8 Module', 'enclosureIndex': 1},
         {'bay': 3, 'enclosure': 1, 'type': 'HP VC 8Gb 20-Port FC Module', 'enclosureIndex': 1},
         {'bay': 4, 'enclosure': 1, 'type': 'HP VC 8Gb 20-Port FC Module', 'enclosureIndex': 1},
         {'bay': 5, 'enclosure': 1, 'type': 'HP VC 8Gb 24-Port FC Module', 'enclosureIndex': 1},
         {'bay': 6, 'enclosure': 1, 'type': 'HP VC 8Gb 24-Port FC Module', 'enclosureIndex': 1},
         ]

# new - added enclosureIndex

icmap = [{'bay': 1, 'enclosure': 1, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
         {'bay': 2, 'enclosure': 1, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
         {'bay': 3, 'enclosure': 1, 'type': 'HP VC 8Gb 20-Port FC Module'},
         {'bay': 4, 'enclosure': 1, 'type': 'HP VC 8Gb 20-Port FC Module'},
         {'bay': 5, 'enclosure': 1, 'type': 'HP VC 8Gb 24-Port FC Module'},
         {'bay': 6, 'enclosure': 1, 'type': 'HP VC 8Gb 24-Port FC Module'},
         ]


ligs = [{'name': 'LIG-FFF8-8FC20-8FC24',
         'type': 'logical-interconnect-groupV3',
         'enclosureType': 'C7000',
         'interconnectMapTemplate': icmap,
         #new
         'enclosureIndexes': [1],
         'interconnectBaySet': 1,
         'redundancyType': 'HighlyAvailable',
         'fcoeSettings': None,
         #end new
         'uplinkSets': [uplink_sets['RDP'].copy(),
                        uplink_sets['IC'].copy(),
                        uplink_sets['Tunnel1'].copy(),
                        uplink_sets['Tunnel2'].copy(),
                        uplink_sets['SAN-1-A'].copy(),
                        uplink_sets['SAN-2-B'].copy(),
                        uplink_sets['SAN-3-A'].copy(),
                        uplink_sets['SAN-4-B'].copy(),
                        uplink_sets['SAN-5-A'].copy(),
                        uplink_sets['SAN-6-B'].copy(),
                        uplink_sets['BigPipe1'].copy(),
                        uplink_sets['BigPipe2'].copy()],
         'stackingMode': 'Enclosure',
         'ethernetSettings': None,
         'state': 'Active',
         'telemetryConfiguration': None,
         'snmpConfiguration': None},
        ]

telemetry = {'enableTelemetry': True, 'sampleInterval': 400, 'sampleCount': 20}

trapDestinations = [{'trapSeverities': ['Major'],
                     'enetTrapCategories': ['Other'],
                     'fcTrapCategories': ['Other'],
                     'vcmTrapCategories': ['Legacy'],
                     'trapFormat': 'SNMPv1',
                     'trapDestination': '192.168.99.99',
                     'communityString': 'public'}]

snmp = {'snmpAccess': ['192.168.1.0/24'],
        'trapDestinations': trapDestinations}

enet = {'enableFastMacCacheFailover': False}

server_profiles = [{'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 1',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay1-BL465cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_96', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_96', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_23', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_23', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'Primary', 'targets': [{'arrayWwpn': '21110002ac00364c', 'lun': '0'}]}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'Secondary', 'targets': [{'arrayWwpn': '20110002ac00364c', 'lun': '0'}]}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 2',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay2-BL465cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_97', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_97', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_24', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_24', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'NotBootable'}},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 3',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay3-BL465cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_98', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_98', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk3', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk3', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_46', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_46', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'NotBootable'}},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 4',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay4-BL465cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b', 'requestedMbps': '2000', 'networkUri': 'FC:SAN-1-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 4, 'name': '4', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b', 'requestedMbps': '2000', 'networkUri': 'FC:SAN-2-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk4', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk4', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'ETH:net_99', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'ETH:net_99', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'NotBootable'}},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 5',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay5-BL460cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_96', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_96', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_23', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_23', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'Primary', 'targets': [{'arrayWwpn': '21110002ac00364c', 'lun': '0'}]}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'Secondary', 'targets': [{'arrayWwpn': '20110002ac00364c', 'lun': '0'}]}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 6',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay6-BL460cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_97', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_97', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_24', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_24', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'NotBootable'}},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 7',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay7-BL460cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_98', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_98', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk3', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk3', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_46', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_46', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'NotBootable'}},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 8',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay8-BL460cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b', 'requestedMbps': '2000', 'networkUri': 'FC:SAN-1-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 4, 'name': '4', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b', 'requestedMbps': '2000', 'networkUri': 'FC:SAN-2-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk4', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk4', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'ETH:net_99', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'ETH:net_99', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'NotBootable'}},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 9',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay9-BL420cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_96', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_96', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_23', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_23', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'Primary', 'targets': [{'arrayWwpn': '21110002ac00364c', 'lun': '0'}]}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'Secondary', 'targets': [{'arrayWwpn': '20110002ac00364c', 'lun': '0'}]}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 10',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay10-BL420cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_97', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_97', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_24', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_24', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'NotBootable'}},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 11',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay11-BL42065cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_98', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-b', 'requestedMbps': '2500', 'networkUri': 'ETH:net_98', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk3', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk3', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_46', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'NS:NS_46', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'NotBootable'}},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 12',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay12-BL420cGen8', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b', 'requestedMbps': '2000', 'networkUri': 'FC:SAN-1-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 4, 'name': '4', 'functionType': 'FibreChannel', 'portId': 'Flb 1:2-b', 'requestedMbps': '2000', 'networkUri': 'FC:SAN-2-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 5, 'name': '5', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk4', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 6, 'name': '6', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-c', 'requestedMbps': '2500', 'networkUri': 'NS:VlanTrunk4', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 7, 'name': '7', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-d', 'requestedMbps': '2500', 'networkUri': 'ETH:net_99', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 8, 'name': '8', 'functionType': 'Ethernet', 'portId': 'Flb 1:2-d', 'requestedMbps': '2500', 'networkUri': 'ETH:net_99', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 9, 'name': '9', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-3-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 10, 'name': '10', 'functionType': 'FibreChannel', 'portId': 'Mezz 1:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-4-B', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 11, 'name': '11', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:1', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-5-A', 'boot': {'priority': 'NotBootable'}},
                                    {'id': 12, 'name': '12', 'functionType': 'FibreChannel', 'portId': 'Mezz 2:2', 'requestedMbps': '8000', 'networkUri': 'FC:SAN-6-B', 'boot': {'priority': 'NotBootable'}},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 13',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay13-BL460cG7', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Lom 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:Tunnel1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:Tunnel2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 14',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay14-BL460cG7', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Lom 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:Tunnel1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:Tunnel2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 15',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay15-BL460cG7', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Lom 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:Tunnel1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:Tunnel2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    ]},
                   {'type': 'ServerProfileV5', 'serverHardwareUri': 'Encl1, bay 16',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:Encl1', 'enclosureGroupUri': 'EG:FFF8-8FC20-8FC24', 'serialNumberType': 'Virtual', 'macType': 'Virtual', 'wwnType': 'Virtual',
                    'name': 'Encl1_Bay16-BL460cG7', 'description': '', 'affinity': 'Bay',
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:RDP', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'Ethernet', 'portId': 'Lom 1:2-a', 'requestedMbps': '2500', 'networkUri': 'ETH:IC', 'boot': {'priority': 'Primary'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 3, 'name': '3', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:Tunnel1', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 4, 'name': '4', 'functionType': 'Ethernet', 'portId': 'Lom 1:1-b', 'requestedMbps': '2500', 'networkUri': 'ETH:Tunnel2', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    ]},
                   ]

true = True
false = False
rc = {'200': 200, '201': 201, '202': 202, '400': 400, '401': 401, '403': 403, '412': 412, '500': 500}

########################################

default_variables = {'admin_credentials': admin_credentials,
                     'appliance': appliance,
                     'encs': encs,
                     'enc_groups': enc_groups,
                     'ethernet_networks': ethernet_networks,
                     'ethernet_ranges': ethernet_ranges,
                     'fc_networks': fc_networks,
                     'fcoe_networks': fcoe_networks,
                     'fcoe_ranges': fcoe_ranges,
                     'licenses': licenses,
                     'ligs': ligs,
                     'network_sets': network_sets,
                     'network_set_ranges': network_set_ranges,
                     'ranges': ranges,
                     'rc': rc,
                     'server_profiles': server_profiles,
                     'uplink_sets': uplink_sets,
                     'users': users,
                     'timeandlocale': timeandlocale,
                     'true': true, 'false': false,
                     'vcenter': vcenter}


def get_variables():

    variables = default_variables
    return variables
