import os
import sys

sys.path.append(os.path.dirname(__file__))

FUSION_USERNAME = 'Administrator'  # Fusion Appliance Username
FUSION_PASSWORD = 'hpvse123'  # Fusion Appliance Password
FUSION_SSH_USERNAME = 'root'  # Fusion SSH Username
FUSION_SSH_PASSWORD = 'hpvse1'  # Fusion SSH Password
# FUSION_SSH_PASSWORD = 'hponeview'        # Fusion SSH Password

FUSION_PROMPT = '#'  # Fusion Appliance Prompt
FUSION_TIMEOUT = 180  # Timeout.  Move this out???
FUSION_NIC = 'bond0'  # Fusion Appliance Primary NIC
FUSION_NIC_SUFFIX = '%' + FUSION_NIC

admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}

appliance = {'type': 'ApplianceNetworkConfiguration',
             'applianceNetworks':
                 [{'device': 'eth0',
                   'macAddress': None,
                   'interfaceName': 'hpcorp',
                   'activeNode': '1',
                   'unconfigure': False,
                   'ipv4Type': 'STATIC',
                   'ipv4Subnet': '255.255.248.0',
                   'ipv4Gateway': '15.245.128.1',
                   'ipv4NameServers': ['16.110.135.52'],
                   'virtIpv4Addr': '15.245.131.12',
                   'app1Ipv4Addr': '15.245.131.13',
                   'app2Ipv4Addr': '15.245.131.14',
                   'ipv6Type': 'UNCONFIGURE',
                   'hostname': 'ar51.feature.usa.hpe.com',
                   'confOneNode': True,
                   'domainName': 'usa.hpe.com',
                   'aliasDisabled': True,
                   }],
             }

ethernet_networks = [{'name': 'wpstDefaultnetwork',
                      'type': 'ethernet-networkV4',
                      'vlanId': '100',
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork1',
                      'type': 'ethernet-networkV4',
                      'vlanId': '101',
                      'purpose': 'Management',
                      'smartLink': True,
                      'privateNetwork': False,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork2',
                      'type': 'ethernet-networkV4',
                      'vlanId': '102',
                      'purpose': 'Management',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork3',
                      'type': 'ethernet-networkV4',
                      'vlanId': '103',
                      'purpose': 'Management',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork4',
                      'type': 'ethernet-networkV4',
                      'vlanId': '104',
                      'purpose': 'Management',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork5',
                      'type': 'ethernet-networkV4',
                      'vlanId': '105',
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork6',
                      'type': 'ethernet-networkV4',
                      'vlanId': '106',
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork7',
                      'type': 'ethernet-networkV4',
                      'vlanId': '107',
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork8',
                      'type': 'ethernet-networkV4',
                      'vlanId': '108',
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork9',
                      'type': 'ethernet-networkV4',
                      'vlanId': '109',
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'wpstnetwork10',
                      'type': 'ethernet-networkV4',
                      'vlanId': '110',
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'}
                     ]
