#!/bin/bash

#=============================================================================
# usage 
#=============================================================================
usage()
{
        echo "usage: $0 -cicip <CIC Appliance IP> -cicu <CIC Appliance User> -cicpw <CIC Appliance PW>" 
	echo ""
}

#=============================================================================
# isJsonshInstalled 
#=============================================================================
isJsonshInstalled()
{
	json=json.sh
	which $json > /dev/null
	
	if [ $? -eq 1 ]; then
		echo "ERROR:  Failed json.sh dependency check.  Please install json.sh"
		exit
	fi
}

#=============================================================================
# getSessionID 
#=============================================================================
getSessionID()
{
	sessionID=`curl -k -X POST -H "Accept:application/json" -H "Content-Type:application/json" -d "{\"userName\":\"$CIC_USER\", \"password\":\"$CIC_PW\"}" https://$CIC_IP/rest/login-sessions`
	echo "sessionID is $sessionID"

	auth=`echo "$sessionID" | awk 'BEGIN{FS=":"} {print $NF}' | sed 's/}//' | sed 's/"//' | sed 's/"//'`
	echo "auth is $auth"

}

#=============================================================================
# deleteSessionID 
#=============================================================================
deleteSessionID()
{
	echo "Deleting the session ID"
	curl -k -X DELETE -H "Accept:application/json" -H "Content-Type:application/json" -H "auth:"$auth https://$CIC_IP/rest/login-sessions
}

#=============================================================================
# getProfileList 
#=============================================================================
getNetworkSet()
{
	tmp_file=$(mktemp /tmp/network-set.XXXXXX)
	json=json.sh

	network_sets=`curl -k -X GET -H "Accept:application/json" -H "Content-Type:application/json" -H "auth:"$auth https://$CIC_IP/rest/network-sets` 
	echo "$network_sets" > $tmp_file

	tmp_json=$(mktemp /tmp/json.XXXXXX)
	$json <"$tmp_file" >> $tmp_json 
	NSETS=`cat $tmp_json | grep "/members/[0-9]\{1,2\}/name string" | awk 'END{FS=" "} {print $NF}'`
	echo -e "\nNetwork Set URI\t\t\t\t\t\t\tNetwork Set"
	for nset in ${NSETS[@]}
	do 
		device=(`cat $tmp_json | grep "$nset" | egrep -o "\/[0-9]{1,4}\/" | tr -d "/"`)
		set_uris=`cat $tmp_json | grep -A 163 "/members/$device/name string $nset" | grep "/members/$device/networkUris/" | awk 'END{FS=" "} {print $NF}'`
		for set_uri in ${set_uris[@]}
		do 	
			echo -e "$set_uri\t$nset"
		done
	done 
	echo -e "\n"
	rm -f $tmp_file; rm -f $tmp_json

}

while [ -n "$(echo $1 | grep '-')" ]; do
	case $1 in
	-cicip ) CIC_IP=$2
	       shift ;;
	-cicu ) CIC_USER=$2
	       shift ;;
	-cicpw ) CIC_PW=$2
	       shift ;;
        * ) usage 
	    exit 1
	esac
	shift
done

if [ -z "$CIC_IP" -o -z "$CIC_USER" -o -z "$CIC_PW" ]; then 
	usage
	exit 1
fi

isJsonshInstalled
getSessionID
getNetworkSet
deleteSessionID


