#!/bin/bash

#=============================================================================
# usage 
#=============================================================================
usage()
{
        echo "usage: $0 -cicip <CIC Appliance IP> -cicu <CIC Appliance User> -cicpw <CIC Appliance PW -puri <Server Profile URI>" 
	echo ""
}

#=============================================================================
# isJsonshInstalled 
#=============================================================================
isJsonshInstalled()
{
	json=json.sh
	which $json > /dev/null
	
	if [ $? -eq 1 ]; then
		echo "ERROR:  Failed json.sh dependency check.  Please install json.sh"
		exit
	fi
}

#=============================================================================
# getSessionID 
#=============================================================================
getSessionID()
{
	sessionID=`curl -k -X POST -H "Accept:application/json" -H "Content-Type:application/json" -d "{\"userName\":\"$CIC_USER\", \"password\":\"$CIC_PW\"}" https://$CIC_IP/rest/login-sessions`
	echo "sessionID is $sessionID"

	auth=`echo "$sessionID" | awk 'BEGIN{FS=":"} {print $NF}' | sed 's/}//' | sed 's/"//' | sed 's/"//'`
	echo "auth is $auth"

}

#=============================================================================
# deleteSessionID 
#=============================================================================
deleteSessionID()
{
	echo "Deleting the session ID"
	curl -k -X DELETE -H "Accept:application/json" -H "Content-Type:application/json" -H "auth:"$auth https://$CIC_IP/rest/login-sessions
}

#=============================================================================
# getProfile 
#=============================================================================
getProfile()
{
	tmp_file=$(mktemp /tmp/server-profile.XXXXXX)
	json=json.sh

	server_profile=`curl -k -X GET -H "Accept:application/json" -H "Content-Type:application/json" -H "auth:"$auth https://$CIC_IP$PROFILE_URI` 
	echo "$server_profile" > $tmp_file

	tmp_json=$(mktemp /tmp/json.XXXXXX)
	$json <"$tmp_file" >> $tmp_json 
	cat $tmp_json
	rm -f $tmp_file; rm -f $tmp_json

}

while [ -n "$(echo $1 | grep '-')" ]; do
	case $1 in
	-cicip ) CIC_IP=$2
	       shift ;;
	-cicu ) CIC_USER=$2
	       shift ;;
	-cicpw ) CIC_PW=$2
	       shift ;;
	-puri ) PROFILE_URI=$2
	       shift ;;
        * ) usage 
	    exit 1
	esac
	shift
done

if [ -z "$CIC_IP" -o -z "$CIC_USER" -o -z "$CIC_PW" -o -z "$PROFILE_URI" ]; then 
	usage
	exit 1
fi

isJsonshInstalled
getSessionID
getProfile
deleteSessionID


