# (C) Copyright 2013 Hewlett-Packard Development Company, L.P.
'''

This file contains all element ID on Fusion Power Delivery Device Page
'''


class FusionPowerDeliveryDevicePage(object):
    ID_PAGE_LABEL = "//div[@class='hp-page-label']/h1[text()='Power Delivery Devices']"
    ID_LINK_ADD_POWER_DELIVERY_DEVICE = "xpath=.//div[@class='hp-master-add']/a[text()='Add power delivery device']"
    ID_LINK_ADD_ENCLOSURE = "link=Add enclosure"
    ID_COMBO_TYPE = "//label[text()='Type']/following-sibling::a"
    ID_INPUT_PDD_IPADDRESS = "xpath=.//*[@id='cic-pdd-hostname']"
    ID_INPUT_PDD_USERNAME = "id=cic-pdd-username"
    ID_INPUT_PDD_PWD = "id=cic-pdd-password"
    ID_BTN_ADD_PLUS_POWER_DELIVERY_DEVICE = "id=cic-pdd-addplus"
    ID_BTN_ADD_PLUS_MANUAL_POWER_DELIVERY_DEVICE = "id=cic-pdd-addplusManual"
    ID_BTN_ADD_POWER_DELIVERY_DEVICE = "id=cic-pdd-add"
    ID_BTN_CANCEL_POWER_DELIVERY = "id=cic-pdd-add-cancel"
    # View
    ID_MENU_TYPE_MAIN_LINK = "css=div.hp-value"
    ID_MENU_TYPE_ALL_TYPES = "xpath=//li[@class='hp-selected' and text()='All types']"
    ID_MENU_TYPE_POWER_FEED = "xpath=//li[@class='hp-selected' and text()='Power Feed']"
    ID_MENU_TYPE_BREAKER_PANEL = "xpath=//li[@class='hp-selected' and text()='Breaker Panel']"
    ID_MENU_TYPE_BRANCH_CIRCUIT = "xpath=//li[@class='hp-selected' and text()='Branch Circuit']"
    ID_MENU_TYPE_RACK_PDU = "xpath=//li[@class='hp-selected' and text()='Rack PDU']"
    ID_MENU_TYPE_LOAD_SEGMENT = "xpath=//li[@class='hp-selected' and text()='Load Segment']"
    ID_MENU_TYPE_OUTLET_BAR = "xpath=//li[@class='hp-selected' and text()='Outlet Bar']"
    ID_MENU_TYPE_OUTLET = "xpath=//li[@class='hp-selected' and text()='Outlet']"

    ID_COMBO_TYPE = "xpath =.//*[@id='cic-pdd-add-form']/div[1]/fieldset/ol/li/label"
    ID_COMBO_ARROW_BTN = "xpath=.//div[@class='hp-form-contents']//a/span[@class='selectBox-arrow']"
    ID_SELECTED_BOX_LABEL = "xpath=.//div[@class='hp-form-contents']//a/span[@class='selectBox-label']"
    ID_SELECT_BOX_LABEL = "xpath=.//*[@id='cic-pdd-add-form']/div[@class='hp-form-contents']/fieldset/ol/li/a"
    ID_AVAILABLE_BOX_LABEL = "xpath=.//div[@class='hp-form-contents']//a/span[@class='selectBox-label']"
    ID_SELECT_DROP_DOWN_LABEL = "xpath=//a[contains(text(),'%s')]"
    ID_INPUT_PDD_NAME = "xpath=.//*[@id='cic-pdd-name']"
    ID_INPUT_PDD_MODEL = "xpath=.//*[@id='cic-pdd-model']"
    ID_INPUT_PDD_CAPACITY = "xpath=.//*[@id='cic-pdd-ratedCapacity']"
    ID_INPUT_PDD_VOLTAGE = "xpath=.//*[@id='cic-pdd-lineVoltage']"
    ID_INPUT_PDD_PARTNUMBER = "xpath=.//*[@id='cic-pdd-partNumber']"
    ID_INPUT_PDD_SERIALNUMBER = "xpath=.//*[@id='cic-pdd-serialNumber']"
    ID_POWER_DELIVERY_DEVICE_LIST = "xpath=.//*[@id='cic-pdd-master-table']/tbody/tr"
    ID_ELEMENT_PDD_NAME_BASE = "xpath=.//*[@id='cic-pdd-master-table']/tbody/tr/td[text()='%s']"
    ID_ACTION_MAIN_BTN = "xpath=//label[text()='Actions']"
    ID_ACTION_MENU_DELETE_PDD = "cic-pdd-delete-action"
    ID_BTN_CONFIRM_DELETE = "id=cic-confirm-ok"
    ID_BTN_ADD_CONNECTION = "id=cic-pdd-add-addPwrConn"
    ID_INPUT_SEARCH_ADDCONN = "xpath=.//*[@id='hp-association-add']/div[@class='hp-filters']/input"
    ID_VOLTS_BOX_LABEL = "xpath=.//fieldset/ol[1]/li/div[label[text()='Volts']]/a"
    ID_POWERFEED_BOX_LABEL = "xpath=.//fieldset/ol[1]/li[label[text()='Power feed']]/div/a"
    ID_ADD_PDU_MSG = "xpath=.//*[@id='hp-form-message']/div/span"
    ID_ADD_PDU_ERR_DETAILS = "xpath=.//*[@id='hp-form-message']/div[@class='hp-form-message-details']"
    ID_CHK_FORCE_ADD_PDU = "xpath=.//*[@id='cic-pdd-force']"
    ID_BTN_PDU_CANCEL = "xpath=.//*[@id='cic-pdd-add-cancel']"
    ID_ADD_STATUS = "xpath=.//*[@id='cic-pdd-master-table']/tbody/tr/td/div[@class='hp-status hp-changing']"
    ID_VERIFY_STATUS = "xpath=.//*[@id='hp-form-message']//div[@class='hp-status hp-changing']"
    ID_ERR_CAPACITY_RANGE = "xpath=.//fieldset/ol/li[label[text()='Rated capacity']]//div/label[@class='hp-error']"
    ID_ERR_VOLTAGE_RANGE = "xpath=.//fieldset/ol/li[label[text()='Line voltage']]//div/label[@class='hp-error']"
    ID_ADD_CONN_CHOICE = "xpath=.//*[@id='hp-add-choices']/tbody/tr/td[text()='%s']"
    ID_BTN_ADDCONN = "xpath=//button[.='Add']"
    ID_BTN_EDIT_ADDCONN = "xpath=//button[.='Add']"
    ID_BTN_ADDCONN_ADDPLUS = "xpath=.//*[@id='hp-association-add']/footer/div/button[text()='Add +']"
    ID_BTN_ADDCONN_CANCEL = "xpath=.//*[@id='hp-association-add']/footer/div/button[text()='Cancel']"
    ID_CONN_VERIFY = "xpath=.//*[@id='cic-pdd-add-powerconnections-assigned']/tbody/tr/td/a[text()='%s']"
    ID_TEXT_VERIFY = "xpath=.//*[@id='hp-add-choices_wrapper']//div[text()='None available']"
    ID_BTN_PDU_ADD_CANCEL_MANUAL = 'id=cic-pdd-add-cancelManual'
    ID_ACTION_MENU_EDIT_PDU = "cic-pdd-edit-action"
    ID_BTN_ADD_CONNECTION_EDITPDU = "id=cic-pdd-edit-addPwrConn"
    ID_ADD_CONN_EDITPDU = "xpath=//div[@class='hp-association-selector']//table//td[.='%s']"
    ID_REMOVE_CONN_EDITPDU = "xpath=.//*[@id='cic-pdd-edit-powerconnections-assigned']/tbody/tr/td[a[text()='%s']]/following::div[@class='hp-close'][1]"
    ID_CONN_EDITPDU = "xpath=.//*[@id='cic-pdd-edit-powerconnections-assigned']/tbody/tr/td[a[text()='%s']]"
    ID_SELECT_BOX_LABEL_EDITPDU = "xpath=.//*[@id='cic-pdd-edit-general']/fieldset/ol/li[@class='cic-pdd-edit-item-optional hp-form-item']/a"
    ID_BTN_EDIT_OK = "xpath=.//*[@id='cic-pdd-edit-ok']"
    ID_SELECT_BOX_OVERVIEW = "xpath=.//*[@id='cic-pdd-panel-selector']/div"
    ID_SELECT_GENERAL = "xpath=.//*[@id='cic-pdd-panel-selector']/ol/li[@class='hp-sub-options']/ol/li/a[text()='General']"
    ID_ITEMS_GENERAL = "xpath=.//fieldset/ol/li/label[text()='%s']/following::div/span[@id='cic-pdd-details-%s']"
    ID_DROPDOWN_OPTION = "xpath=//span[contains(text(),'%s')]"
    ID_PDU_IN_LIST = "xpath=//*/tbody//tr[td[contains(text(), '%s')]][1]/td[2]"
    ID_ADD_IPDU_COMPLETED = "xpath=//div[@id='hp-page-notifications']/div[@class='hp-notification']/header[@class='hp-notification-summary']/div[@class='hp-state' and text()='Completed']"
    ADD_MAX_TIME = 300
