'''
Created on July 02, 2013

This file contains all element ID on Fusion Settings Page
'''

__version__ = "$Revision: 98f42236d1af $"
# $Source$


class FusionSettingsPage(object):
    ID_PAGE_LABEL = "//div[@id='hp-settings-page']/nav/div[1]/h1[text()='Settings']"
    ID_MENU_ACTION_MAIN_BTN = "xpath=//label[text()='Actions']"
    ID_MENU_ACTION_CREATE_SUPPORT_DUMP = "hp-create-dump-link"
    ID_MENU_ACTION_DOWNLOAD_AUDIT_LOGS = "hp-download-audit-logs-link"
    ID_MENU_ACTION_CREATE_SELF_SIGNED_CERT = "hp-create-cert-link"
    ID_MENU_ACTION_CREATE_CERT_SIGNING_REQ = "id=hp-create-csr-link"
    ID_MENU_ACTION_IMPORT_CERTIFICATE = "id=hp-import-cert-link"
    ID_MENU_ACTION_UPDATE = "id=hp-update-appliance"
    ID_MENU_ACTION_EDIT_SUPPORT_ACCESS = "id=hp-support-access"
    ID_MENU_ACTION_CREATE_BACKUP = "id=hp-backup-appliance"
    ID_MENU_ACTION_DOWNLOAD_BACKUP = "id=hp-download-appliance-backup"
    ID_MENU_ACTION_RESTORE_FROM_BACKUP = "id=hp-restore-appliance"
    ID_MENU_ACTION_SHUTDOWN = "id=hp-appliance-reset-link"
    ID_MENU_ACTION_RESTART = "link=Restart"
    # Support Dump
    ID_BTN_YES_CREATE_SUPPORT_DUMP = "id=hp-details-create-dump"
    ID_BTN_CANCEL_SUPPORT_DUMP = "id=hp-details-cancel-dump"
    # Create Self Signed Cert
    ID_INPUT_SELF_SIGN_CERT_COUNTRY = "id=cic-selfsigned-country"
    ID_INPUT_SELF_SIGN_CERT_STATE = "id=cic-selfsigned-state"
    ID_INPUT_SELF_SIGN_CERT_CITY = "id=cic-selfsigned-locality"
    ID_INPUT_SELF_SIGN_CERT_ORGANIZATION_NAME = "id=cic-selfsigned-org"
    ID_INPUT_SELF_SIGN_CERT_ORGANIZATIONAL_UNIT = "id=cic-selfsigned-ou"
    ID_INPUT_SELF_SIGN_CERT_ALTERNATIVE_NAME = "id=cic-selfsigned-alt-name"
    ID_SELF_SIGN_CERT_ID_INPUT_CONTACT_PERSON = "id=cic-selfsigned-contact"
    ID_SELF_SIGN_CERT_ID_INPUT_EMAIL_ADDRESS = "id=cic-selfsigned-email"
    ID_SELF_SIGN_CERT_ID_INPUT_SURNAME = "id=cic-selfsigned-surname"
    ID_INPUT_SELF_SIGN_CERT_GIVEN_NAME = "id=cic-selfsigned-given-name"
    ID_INPUT_SELF_SIGN_CERT_INITIALS = "id=cic-selfsigned-initials"
    ID_INPUT_SELF_SIGN_CERT_DNQUALIFIER = "id=cic-selfsigned-dn"
    ID_BTN_SELF_SIGN_CERT_OK = "id=cic-selfsigned-create-ok"
    ID_BTN_SELF_SIGN_CERT_CANCEL = "id=cic-selfsigned-create-cancel"
    # Create Self Sign Request
    ID_INPUT_SELF_SIGN_REQUEST_COUNTRY = "id=cic-csr-country"
    ID_INPUT_SELF_SIGN_REQUEST_STATE = "id=cic-csr-state"
    ID_INPUT_SELF_SIGN_REQUEST_CITY = "id=cic-csr-locality"
    ID_INPUT_SELF_SIGN_REQUEST_ORG_NAME = "id=cic-csr-org"
    ID_INPUT_SELF_SIGN_REQUEST_ORG_UNIT = "id=cic-csr-ou"
    ID_INPUT_SELF_SIGN_REQUEST_ALTERNATIVE_NAME = "id=cic-csr-alt-name"
    ID_INPUT_ELF_SIGN_REQUEST_CONTACT_PERSON = "id=cic-csr-contact"
    ID_INPUT_SELF_SIGN_REQUEST_EMAIL_ADDRESS = "id=cic-csr-email"
    ID_INPUT_SELF_SIGN_REQUEST_SURNAME = "id=cic-csr-surname"
    ID_INPUT_SELF_SIGN_REQUEST_GIVEN_NAME = "id=cic-csr-given-name"
    ID_INPUT_SELF_SIGN_REQUEST_INITIALS = "id=cic-csr-initials"
    ID_INPUT_SELF_SIGN_REQUEST_DN_QUALIFY = "id=cic-csr-dn"
    ID_INPUT_SELF_SIGN_REQUEST_CHALLENGE_PWD = "id=cic-csr-challenge-password"
    ID_INPUT_SELF_SIGN_REQUEST_CONFIRM_PWD = "id=cic-csr-confirm-password"
    ID_INPUT_SELF_SIGN_REQUEST_UNSTRUCTURED_NAME = "id=cic-csr-unstructured-name"
    ID_BTN_ADD_SELF_SIGN_REQUEST = "id=cic-csr-create-ok"
    ID_BTN_CANCEL_SELF_SIGN_REQUEST = "id=cic-csr-create-cance"
    # IMPORT CERT
    ID_BTN_OTHER_USER_IS_LOGGED = "id=cic-import-logged-in-msg"
    ID_INPUT_CERT = "id=cic-import-base64-text"
    ID_BTN_OK_IMPORT_CERT = "id=cic-import-base64-ok"
    ID_BTN_CANCEL_IMPORT_CERT = "id=cic-import-base64-cancel"
    # EDIT SUPPORT ACCESS
    ID_TOGGLE_ON = "css=li.hp-on"
    ID_TOGGLE_OFF = "css=li.hp-off"
    ID_BTN_OK_SUPPORT_ACCESS = "id=hp-supportaccess-ok-button"
    ID_BTN_CANCEL_SUPPORT_ACCESS = "id=hp-supportaccess-cancel-button"
    # SHUTDOWN and #RESTART APPLIANCE
    ID_BTN_CANCEL_SHUTDOWN = "id=hp-cancel-shutdown"
    ID_BTN_YES_CONFIRM_SHUTDOWN = "id=hp-start-shutdown"
    # VIEW
    ID_COMBO_MENU_VIEW = "css=div.hp-value"
    ID_LINK_OVERVIEW = "id=hp-settings-panel-selector"  # changed from Overview to panel
    ID_LINK_OVERVIEW_DROPDOWN = "xpath=.//*[@id='hp-settings-panel-selector']/div[text()='%s']"
    ID_LICENSE_AVAILABILITY = "xpath=.//*[@id='fs-settings-license-summary-gridPanels']//header/h2[text()='%s']"  # HP OneView w/o iLO, HP OneView
    ID_LINK_DNS = "//span[text()='DNS']"
    ID_LINK_IPV4 = "//span[text()='IPv6']"
    ID_LINK_TIME_PLACE = "//span[text()='Time and Place']"
    ID_LINK_BACKUP = "//span[text()='Backup']"
    ID_LINK_AUTHENTICATION = "//span[text()='Authentication']"
    ID_LINK_DIRECTORIES = "//span[text()='Directories']"
    ID_LINK_CERTIFICATE = "//span[text()='Certificate']"
    ID_LINK_HP_PUBLIC_KEY = "//span[text()='HP Public Key']"
    ID_LINK_SUPPORT = "//span[text()='Support']"
    ID_LINK_LICENSE = "//span[text()='Licenses']"  # added s to License
    ID_LINK_ADDRESS_IDENTIFIER = "//span[text()='Addresses and Identifiers']"
    ID_MENU_ACTION_ADDLICENSE = "id=hp-add-license-link"
    ID_DLG_ADDLICENSE = "xpath=.//*[@id='fs-addLicense-dialog']"
    ID_INPUT_LICENSEKEY = "xpath=.//*[@id='fs-license-licenseKeyValue']"
    ID_DLG_BTN_ADD = "xpath=.//*[@id='fs-license-add']"
    ID_DLG_BTN_ADDPLUS = "xpath=.//*[@id='fs-license-add-again']"
    ID_DLG_BTN_CANCEL = "xpath=.//*[@id='fs-addLicense-cancel']"
    ID_ADDLICENSE_ERR_MSG = "xpath=.//*[@id='hp-form-message']/div[1]/span[contains(text(),'Unable to add')]"
    ID_AVAILABLE_LICENSE = "xpath=.//header/h2[text()='%s']/following::div[contains(@id,'fs-settings-license-summary-availableLicenses')]"
    # CREATE BACKUP
    ID_LABEL_BACKUP_NOTIFICATION = "//div[@id='hp-page-notifications']/div/header"
    ID_LABEL_BACKUP_DETAILS = "css=div.hp-details"
    ID_LABEL_CREATE_BACKUP = "//div[@id='hp-page-notifications']//div[text()='Create backup']"
    # RESTORE BACKUP
    ID_BTN_BROWSE_FILE = "xpath=//input[@id='hp-file-chooser-file' and @class='hp-button hp-file-chooser-file' and @type='file' and  @value='Choose File Button' and @name='file']"
    ID_CHECKBOX_RESTORE_CONFIRMATION = "id=cic-restore-confirmation"
    ID_BTN_RESTORE_FROM_BACKUP = "id=fs-settings-restore-restoreFromBackup"
    ID_LABEL_RESTORING_FROM_BACKUP = "//div[@id='hp-form-message']/div/span[text() = 'Restoring from backp ...']"
    ID_LABEL_RESTORING = "//div[text() = 'Restoring']"
    ID_LABEL_EDIT_SUPPORT_ACCESS = "xpath=.//*[@id='hp-change-page-container']/section/header/h1"
    ID_LABEL_WAITING = "xpath=//div/div/div/div[text()='Waiting']"
    ID_LABEL_PROGRESS = "xpath=//div/div/span[@class='hp-progress']"
    ID_LABEL_RESTART = "xpath=//form/div[text()='Restart will cause all users to be logged out and all ongoing tasks to be cancelled.']"
    ID_LABEL_STARTING = "xpath=//div/div[text()='Starting']"
    ID_LABEL_UNAVAILABLE = "xpath=//div/div[text()='Temporarily unavailable']"
    ID_TEXT_SHUTDOWN = "xpath=//form/div[text()='Shutdown will cause all users to be logged out and all ongoing tasks to be cancelled.']"
    ID_LABEL_CREATE_SUPPORTDUMP = "xpath=//p[contains(.,'Creating a support dump may take a few minutes after which the file download will begin automatically. Meanwhile, you can continue to use the UI normally.')]"
    ID_ACTVITY_SUPPORT_DUMP = "css=nav.hp-sub-nav > div.hp-sidebar-control > div.hp-pin-right"
    ID_CLICK_ACTIVITY = "xpath = .//*[@id='hp-flyout-activities']/li/div[@class='hp-brief']/div[@class='hp-status hp-status-changing']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    ID_TIMESTAMP_SUPPORT_DUMP = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-changing']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    ID_VALIDATE_SUCCESS = "xpath = //header[@class='hp-active']/div[@class='hp-status hp-status-ok']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"  # %s replace with name of interconnect
    ID_TOGGLE_BTN_SERVICE_ACCESS = "xpath=.//*[@id='hp-eula-service-access-toggle-button-hpToggle']"
    ID_LABEL_STATUS = "xpath=.//*[@id='statusLabel']"

    # directory server function objects
    ID_BTN_ADD_DIRECTORY_SETTINGS = "id=add-directory-button"
    ID_SECURITY_EDIT = "xpath=//*[@id='cic-settings-security-edit']"
    # ID_DIRECTORY_NAME = "xpath=//table[@id='security-directories-table']/tbody//td[contains(text(), '%s')]"
    ID_DIRECTORY_NAME = "xpath=//*[@id='security-directories-table']/tbody/tr[*]/td[contains(text(),'%s')]"
    ID_HP_FORM_MESSAGE_DETAILS = "xpath=//span[@class='hp-form-message-details']"

    # Added for 1.10 to fix in 27_remove_directory_servers
    ID_REMOVE_SERVER_X_BUTTON_XPATH = ".//*[@id='security-directories-table']/tbody/tr[1]/td[3]"
    ID_REMOVE_SERVER_YES_BUTTON = "//div[@id='hp-body-div']/div[8]/div/div/div/footer/div/button"
    ID_DIRECTORY_DEL = "xpath=//*[@id='security-directories-table']/tbody/tr[*]/td[contains(text(),'%s')]/parent::*/td[3]/div"

    # directory name
    ID_INPUT_DIR_NAME = "xpath=//*[@id='fs-settings-authn-dir-name-text']"
    # Credentials
    ID_INPUT_AUTHN_USERNAME = "xpath=//*[@id='fs-settings-authn-user-name-text']"
    ID_INPUT_AUTHN_PASSWORD = "xpath=//*[@id='fs-settings-authn-password-text']"
    # add directory button
    ID_BTN_ADD_DIRECTORY = "//*[@id='fs-settings-authn-add-dir-servers']"
    ID_BTN_AUTHENTICATION = "css=div.hp-value"
    ID_BTN_DIRECTORIES = "link=Directories"
    # ip address or host name
    ID_INPUT_IPADDRESS = "xpath=//*[@id='fs-settings-authn-host-name-text']"
    ID_INPUT_SERVER_PORT = "xpath=//*[@id='fs-settings-authn-port-text']"
    ID_INPUT_CERTIFICATE = "xpath=//*[@id='fs-settings-authn-certificate']"
    JS_ID_INPUT_CERTIFICATE = "fs-settings-authn-certificate"
    ID_BTN_DIRECTORY_SERVER_ADD = "xpath=//*[@id='fs-authn-add-dir-server-add']"
    ID_ERROR_MESSAGE = "xpath=.//*[@id='hp-form-message']/div[*]/span"
    ID_BTN_ADD_DIR = "xpath=//*[@id='fs-authn-add-dir-add']"
    ID_SERVER = "xpath=//*[@id='fs-dir-servers-table']/tbody/tr/td[text()='%s']"
    # Search context
    ID_INPUT_UID = "xpath=//*[@id='fs-settings-authentication-add-form']/div/fieldset/ol/li/div/input[@name='uid']"
    ID_INPUT_ORG = "xpath=//*[@id='fs-settings-authentication-add-form']/div/fieldset/ol/li/div/input[@name='org']"
    ID_INPUT_TOP = "xpath=//*[@id='fs-settings-authentication-add-form']/div/fieldset/ol/li/div/input[@name='top']"
    ID_BTN_SETTINGS_EDIT_CANCEL = "id=hp-settings-edit-cancel"
    ID_ELEMENT_DIRECTORIES = "xpath=//*[@id='fs-settings-security-overview-directories']"

    ID_ELEMENT_SERVER_ALREADY_ADDED = "xpath=//div/span[text()='The specified authentication login domain is already configured in the system.']"
    ID_BTN_DIR_SERVER_CANCEL = "id=fs-cancel-add-dir"
    ID_ELEMENT_SECURYTY_HEADER = "xpath=//*[@id='fs-settings-security-panel']/header/a[text()='Security']"

    # EDIT ADDRESS AND IDENTIFIER
    ID_LINK_ADDRESS_AND_IDENTIFIER = "xpath=//*[@id='cic-settings-guid-panel']/header//a[text()='Addresses and Identifiers']"
    ID_LINK_EDIT_ADDRESS_AND_IDENTIFIER = "xpath=//*[@id='cic-settings-guid-panel']/header/a[text()='Edit']"
    ID_DROPDOWN_EDIT_SELECTOR = "css=#cic-addresses-panel-edit-selector > div.hp-value"
    ID_LINK_WWN = "link=World Wide Names"
    ID_LINK_MAC_ADDRESS = "link=MAC Addresses"
    ID_LINK_SERIAL_NO = "link=Serial Numbers"
    ID_CHKBOX_MAC_ENABLE_VIRTUAL = "id=cic-settings-mac-use-virtual"
    ID_BTN_MAC_ADD_CUSTOM_RANGE = "id=cic-settings-macs-add"
    ID_INPUT_ADD_CUSTOM_RANGE_FROM = "id=cic-settings-from-custom"
    ID_INPUT_ADD_CUSTOM_RANGE_TO = "id=cic-settings-to-custom"
    ID_INPUT_ADD_CUSTOM_RANGE_COUNT = "id=cic-settings-count-custom"
    ID_BTN_ADD_CUSTOM_RANGE = "id=cic-settings-guid-add"
    ID_CHKBOX_MAC_ENABLE = "id=cic-settings-edit-checkbox-id-range-VMAC-%s"
    ID_LABEL_ERROR_ADD_CUSTOM = "//label[@class='hp-error']"
    ID_BTN_CANCEL_MAC_CUSTOM_ADD = "id=cic-settings-guid-cancel"
    ID_BTN_AUTO_GENERATED_MAC = "id=cic-settings-macs-add-generated"
    ID_LABEL_AUTO_GENERATED_FROM = "id=cic-settings-from-generated"
    ID_LABEL_AUTO_GENERATED_TO = "id=cic-settings-to-generated"
    ID_BTN_GENERATE = "id=cic-settings-regenerate"
    ID_BTN_AUTO_GENERATE_ADD = "id=cic-settings-guid-add"
    ID_BTN_AUTO_GENERATE_ADD_PLUS = "id=cic-settings-guid-add-again"
    ID_BTN_AUTO_GENERATE_CANCEL = "id=cic-settings-guid-cancel"
    ID_TABLE_MAC_BASE = "xpath=//*[@id='cic-settings-edit-mac-table']"
    ID_CHKBOX_WWN_ENABLE_VIRTUAL = "id=cic-settings-wwn-use-virtual"
    ID_BTN_WWN_ADD_CUSTOM_RANGE = "id=cic-settings-wwns-add"
    ID_CHKBOX_WWN_ENABLE = "id=cic-settings-edit-checkbox-id-range-VWWN-%s"
    ID_BTN_AUTO_GENERATED_WWN = "id=cic-settings-wwns-add-generated"
    ID_TABLE_WWN_BASE = "xpath=//*[@id='cic-settings-edit-wwn-table']"
    ID_CHKBOX_SERIAL_NO_ENABLE_VIRTUAL = "id=cic-settings-sn-use-virtual"
    ID_CHKBOX_SERIAL_NO_ENABLE = "id=cic-settings-edit-checkbox-id-range-VSNN-%s"
    ID_BTN_SERIAL_NO_ADD_CUSTOM_RANGE = "id=cic-settings-sns-add"
    ID_BTN_AUTO_GENERATED_SERIAL_NO = "id=cic-settings-sns-add-generated"
    ID_TABLE_SERIAL_NO_BASE = "xpath=//*[@id='cic-settings-edit-sn-table']"
    ID_BTN_OK = "id=cic-settings-edit-ok"
    ID_EDIT_MESSAGE_SUMMARY = "xpath=//*[@id='hp-form-message']/div[@class='hp-form-message-summary']"
    ID_LABEL_CUSTOM_ADD_OVERLAPPING_ERROR = "xpath=//*[@id='cic-settings-error-field-custom-container']/label"

    # LDAP server objects
    ID_ELEMENT_AD_OR_LDAP_SELECTION = "xpath=.//*[@id='fs-settings-authentication-add-form']/div/fieldset/ol/li/a/span[@class='selectBox-arrow']"
    ID_ELEMENT_LDAP_SELECT = "xpath=.//*[@id='fs-settings-authentication-add-form']/div/fieldset/ol/li[2]/a"

    # Add alert notifications
    ID_LABEL_NOTIFICATIONS = "id=cic-notification-emailview-link"
    ID_LINK_EDIT_NOTIFICATIONS = "xpath=//a[@id='fs-settings-emailnotifications-panel-edit' and text()='Edit']"
    ID_LABEL_EDIT_NOTIFICATIONS = "xpath=//*[@id='hp-change-page-container']//span[text()='Edit Notifications']"
    ID_TXT_EDIT_NOTIFICATIONS_SENDER_EMAIL = "id=cic-notification-emailedit-senderemail"
    ID_TXT_EDIT_NOTIFICATIONS_SENDER_PASSWORD = "id=cic-notification-emailedit-senderemailpassword"
    ID_TXT_EDIT_NOTIFICATIONS_SENDER_SMTP_SERVER = "id=cic-notification-emailedit-smtpserver-servername"
    ID_TXT_EDIT_NOTIFICATIONS_SENDER_SMTP_PORT = "id=cic-notification-emailedit-smtpserver-serverport"
    ID_CHCKBOX_SMTP_OPTIONS = "xpath=//*[@id='cic-notification-emailedit-smtpoptions']"
    ID_ENABLE_ALTER_EMAIL = "//a[@id='cic-notification-alerts-enablebutton-hpToggle' and @class='hp-toggle hp-checked']"
    ID_BTN_ALERTS_ENABLED = "xpath=//*[@id='cic-notification-alerts-enablebutton-hpToggle']//li[@class='hp-on']"
    ID_BTN_OK_EDIT_NOTIFICATIONS = "id=cic-notification-emailedit-ok"

    # Add email alert filter
    ID_BTN_ADD_ALERT_EMAIL_FILTER = "id=cic-notification-alerts-addnotify-button"
    ID_LABEL_ADD_EMAIL_FILTER = "xpath=//*[@id='cic-notification-alert-add-header']/h1[text()='Add Alert Email Filter']"
    ID_BTN_EMAIL_FILTER = "id=cic-notification-addemail-enabled"
    ID_BTN_EMAIL_FILTER_ENABLED = "xpath=//*[@id='cic-notification-addemail-enabled-hpToggle']//li[@class='hp-on']"
    ID_BTN_EMAIL_FILTER_DISABLED = "xpath=//*[@id='cic-notification-addemail-enabled-hpToggle']//li[@class='hp-off']"
    ID_TXT_FILTER = "id=cic-notification-addemail-filter"
    ID_TXT_FILTER_EMAILADDRESSES = "id=cic-notification-addemail-emailaddresses"
    ID_BTN_ADD_EMAIL_FILTER = "cic-notification-alerts-add-button"
