admin_credentials = {
    'userName': 'Administrator',
    'password': 'hpvse123'
}

ilo_credentials = {
    'username': 'Administrator',
    'password': 'hpvse123'
}

EG_NAME = 'EG'

# Enclosures
ENC1 = 'tb2'

SERVER_GEN9 = '%s, bay 4' % ENC1
SERVER_GEN10 = '%s, bay 10' % ENC1

SH_GEN9 = "SH:" + SERVER_GEN9
SH_GEN10 = "SH:" + SERVER_GEN10

server_hardware_uris = [
    {
        'serverHardwareUri': SH_GEN9,
    },
    {
        'serverHardwareUri': SH_GEN10,
    },
]

# PROFILE1 SETTINGS
PROFILE1_NAME_PREFIX = 'OVF4829_FC_2BootVol'
PROFILE1_GEN9_NAME = PROFILE1_NAME_PREFIX + " (Gen9)"
PROFILE1_GEN10_NAME = PROFILE1_NAME_PREFIX + " (Gen10)"
PROFILE1_TYPE = "ServerProfileV10"

PROFILE_TEMPLATE1_NAME_PREFIX = 'OVF4829_FC_2BootVol_SPT'
PROFILE_TEMPLATE1_GEN9_NAME = PROFILE_TEMPLATE1_NAME_PREFIX + " (Gen9)"
PROFILE_TEMPLATE1_GEN10_NAME = PROFILE_TEMPLATE1_NAME_PREFIX + " (Gen10)"
PROFILE_TEMPLATE1_TYPE = "ServerProfileTemplateV6"

# There should really be 2 StorServs for these tests. Tests will work with 1 if that's all you have available
STORESERV1_NAME = 'tb3par1'
STORESERV2_NAME = 'tb3par1'
STORESERV1_POOL = 'FC_r1'
STORESERV2_POOL = 'FC_r1'
STORESERV_VOLUME1_NAME = 'OVF4829_vol1'
STORESERV_VOLUME2_NAME = 'OVF4829_vol2'

# StoreVirtuals
STOREVIRTUAL1_SYSTEM_NAME = 'dl802Cluster'
STOREVIRTUAL1_POOL_NAME = 'dl802Cluster'
STOREVIRTUAL2_SYSTEM_NAME = 'dl801Cluster'
STOREVIRTUAL2_POOL_NAME = 'dl801Cluster'
STOREVIRTUAL_VOLUME1_NAME = 'OVF4829_vol1'
STOREVIRTUAL_VOLUME2_NAME = 'OVF4829_vol2'

FC_NETWORK_A = 'FC-A'
FC_NETWORK_A_VSAN = 'VSAN20'
FC_NETWORK_B = 'FC-B'
FC_NETWORK_B_VSAN = 'VSAN30'

ISCSI_NETWORK_1 = 'UntaggediSCSINetwork'
ISCSI_NETWORK_2 = 'VLAN10iSCSINetwork'

ris_node_gen9 = {"server": SH_GEN9,
                 "username": "Administrator",
                 "password": "hpvse123",
                 "path": "/redfish/v1/Systems/1/bios/boot/settings",
                 }

ris_node_gen10 = {"server": SERVER_GEN10,
                  "username": "Administrator",
                  "password": "hpvse123",
                  "path": "/redfish/v1/Systems/1/bios/boot/settings",
                  }

sp_from_spt_Gen9 = {
    "serverProfileTemplateUri": "SPT:" + PROFILE_TEMPLATE1_GEN9_NAME,
    "name": PROFILE1_GEN9_NAME,
    "serverHardwareUri": SH_GEN9,
}

sp_from_spt_Gen10 = {
    "serverProfileTemplateUri": "SPT:" + PROFILE_TEMPLATE1_GEN10_NAME,
    "name": PROFILE1_GEN10_NAME,
    "serverHardwareUri": SH_GEN10,
}

FIXED_VOL1_NAME = "OVF4829_FixedVol1"
FIXED_VOL2_NAME = "OVF4829_FixedVol2"

fixed_vols = [
    {"properties": {"name": FIXED_VOL1_NAME,
                    "description": "",
                    "storagePool": STORESERV1_POOL,
                    "size": 1073741824,
                    "provisioningType": "Thin",
                    "isShareable": False,
                    },
     "templateUri": "ROOT",
     "isPermanent": True,
     },
    {"properties": {"name": FIXED_VOL2_NAME,
                    "description": "",
                    "storagePool": STORESERV2_POOL,
                    "size": 1073741824,
                    "provisioningType": "Thin",
                    "isShareable": False,
                    },
     "templateUri": "ROOT",
     "isPermanent": True,
     }
]

ts1_gen10_2_target_2_boot_volume_sp = {
    "type": PROFILE1_TYPE,
    "name": PROFILE1_GEN10_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            },
            {
                "id": 2,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME2_NAME,
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Secondary",
            }
        ],
        "sanSystemCredentials": [],
    },
}


ts1_gen9_2_target_2_boot_volume_sp = {
    "type": PROFILE1_TYPE,
    "name": PROFILE1_GEN9_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN9,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            },
            {
                "id": 2,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME2_NAME,
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Secondary",
            }
        ],
        "sanSystemCredentials": [],
    },
}

ts3_gen9_2_target_2_boot_volume_1_conn_sp = {
    "type": PROFILE1_TYPE,
    "name": PROFILE1_GEN9_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN9,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + FIXED_VOL1_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                ],
                "bootVolumePriority": "Primary",
            },
            {
                "id": 2,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + FIXED_VOL2_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                ],
                "bootVolumePriority": "Secondary",
            },
        ],
        "sanSystemCredentials": [],
    },
}

ts4_gen10_2_target_1_boot_volume_sp = {
    "type": PROFILE1_TYPE,
    "name": PROFILE1_GEN10_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            },
        ],
        "sanSystemCredentials": [],
    },
}

ts4_gen9_2_target_1_boot_volume_sp = {
    "type": PROFILE1_TYPE,
    "name": PROFILE1_GEN9_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN9,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            },
        ],
        "sanSystemCredentials": [],
    },
}

ts5_gen10_2_target_1_boot_volume_api800_sp = {
    "type": "ServerProfileV9",
    "name": PROFILE1_GEN10_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "isBootVolume": True,
            },
        ],
    },
}

ts5_gen10_2_target_1_boot_volume_api800_sp_edit = {
    "type": "ServerProfileV9",
    "name": PROFILE1_GEN10_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "isBootVolume": False,
            },
            {
                "id": 2,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME2_NAME,
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "isBootVolume": True,
            }
        ],
    },
}

ts5_gen10_2_target_1_boot_volume_api800_sp_add_volume = {
    "id": 2,
    "lunType": "Auto",
    "volumeUri": None,
    "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
    "volume": {
        "properties": {
            "name": STORESERV_VOLUME2_NAME,
            "storagePool": "SPOOL:" + STORESERV2_POOL,
            "provisioningType": "Thin",
            "size": 2147483648,
            "isShareable": False,
        },
        "isPermanent": False,
        "templateUri": "ROOT:" + STORESERV2_POOL,
    },
    "storagePaths": [
        {
            "connectionId": 1,
            "targetSelector": "Auto",
            "isEnabled": True
        },
        {
            "connectionId": 2,
            "targetSelector": "Auto",
            "isEnabled": True
        }
    ],
    "isBootVolume": True,
}

ts5_gen10_2_target_1_boot_volume_1_data_volume_api800_sp = {
    "type": "ServerProfileV9",
    "name": PROFILE1_GEN10_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "isBootVolume": True,
            },
            {
                "id": 2,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME2_NAME,
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "isBootVolume": False,
            }
        ],
    },
}

ts5_gen10_2_target_2_boot_volume_spt = {
    "type": PROFILE_TEMPLATE1_TYPE,
    "name": PROFILE_TEMPLATE1_GEN10_NAME,
    "serverHardwareTypeUri": "SHT:" + SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "affinity": "Bay",
    "iscsiInitiatorNameType": "AutoGenerated",
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False, "overriddenSettings": []},
    "localStorage": {"sasLogicalJBODs": [], "controllers": []},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                    },
                    {
                        "connectionId": 2,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                    }
                ],
                "volume": {
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                    "properties": {
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "name": STORESERV_VOLUME1_NAME,
                        "description": "",
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "templateVersion": "1.1",
                        "isShareable": False
                    },
                    "isPermanent": False
                },
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "bootVolumePriority": "Primary"
            },
            {
                "id": 2,
                "lun": None,
                "lunType": "Auto",
                "storagePaths": [
                    {
                        "connectionId": 2,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                        "targets": []
                    },
                    {
                        "connectionId": 1,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                        "targets": []
                    }
                ],
                "volume": {
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                    "properties": {
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "name": STORESERV_VOLUME2_NAME,
                        "description": "",
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "templateVersion": "1.1",
                        "isShareable": False
                    },
                    "isPermanent": False
                },
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "bootVolumePriority": "Secondary"
            }
        ],
        "sanSystemCredentials": []
    },
    "category": "server-profile-templates",
    "connectionSettings": {
        "manageConnections": True,
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "boot": {
                    "bootVolumeSource": "ManagedVolume",
                    "priority": "LoadBalanced",
                },
                "lagName": None,
                "managed": True
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "boot": {
                    "bootVolumeSource": "ManagedVolume",
                    "priority": "LoadBalanced",
                },
                "managed": True
            }
        ]
    }
}

ts5_gen10_2_target_1_boot_volume_api800_spt = {
    "type": "ServerProfileTemplateV5",
    "name": PROFILE_TEMPLATE1_GEN10_NAME,
    "serverHardwareTypeUri": "SHT:" + SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "affinity": "Bay",
    "iscsiInitiatorNameType": "AutoGenerated",
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False, "overriddenSettings": []},
    "localStorage": {"sasLogicalJBODs": [], "controllers": []},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                    },
                    {
                        "connectionId": 2,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                    }
                ],
                "volume": {
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                    "properties": {
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "name": STORESERV_VOLUME1_NAME,
                        "description": "",
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "templateVersion": "1.1",
                        "isShareable": False
                    },
                    "isPermanent": False
                },
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "isBootVolume": True
            },
        ],
    },
    "category": "server-profile-templates",
    "connectionSettings": {
        "manageConnections": True,
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "boot": {
                    "bootVolumeSource": "ManagedVolume",
                    "priority": "Primary",
                },
                "managed": True
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "boot": {
                    "bootVolumeSource": "ManagedVolume",
                    "priority": "Secondary",
                },
                "managed": True
            }
        ]
    }
}

ts5_gen10_2_target_1_boot_volume_api800_spt_add_volume = {
    "id": 2,
    "lunType": "Auto",
    "volumeUri": None,
    "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
    "volume": {
        "properties": {
            "name": STORESERV_VOLUME2_NAME,
            "storagePool": "SPOOL:" + STORESERV2_POOL,
            "provisioningType": "Thin",
            "size": 2147483648,
            "isShareable": False,
        },
        "isPermanent": False,
        "templateUri": "ROOT:" + STORESERV2_POOL,
    },
    "storagePaths": [
        {
            "connectionId": 1,
            "targetSelector": "Auto",
            "isEnabled": True
        },
        {
            "connectionId": 2,
            "targetSelector": "Auto",
            "isEnabled": True
        }
    ],
    "isBootVolume": True,
}

ts5_gen10_2_target_1_boot_volume_1_data_volume_api800_spt = {
    "type": "ServerProfileTemplateV5",
    "name": PROFILE_TEMPLATE1_GEN10_NAME,
    "serverHardwareTypeUri": "SHT:" + SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "affinity": "Bay",
    "iscsiInitiatorNameType": "AutoGenerated",
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False, "overriddenSettings": []},
    "localStorage": {"sasLogicalJBODs": [], "controllers": []},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                    },
                    {
                        "connectionId": 2,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                    }
                ],
                "volume": {
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                    "properties": {
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "name": STORESERV_VOLUME1_NAME,
                        "description": "",
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "templateVersion": "1.1",
                        "isShareable": False
                    },
                    "isPermanent": False
                },
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "isBootVolume": True,
            },
            {
                "id": 2,
                "lun": None,
                "lunType": "Auto",
                "storagePaths": [
                    {
                        "connectionId": 2,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                        "targets": []
                    },
                    {
                        "connectionId": 1,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                        "targets": []
                    }
                ],
                "volume": {
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                    "properties": {
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "name": STORESERV_VOLUME2_NAME,
                        "description": "",
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "templateVersion": "1.1",
                        "isShareable": False
                    },
                    "isPermanent": False
                },
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "isBootVolume": False,
            }
        ],
    },
    "category": "server-profile-templates",
    "connectionSettings": {
        "manageConnections": True,
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "boot": {
                    "bootVolumeSource": "ManagedVolume",
                    "priority": "Primary",
                },
                "managed": True
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "boot": {
                    "bootVolumeSource": "ManagedVolume",
                    "priority": "Secondary",
                },
                "managed": True
            }
        ]
    }
}

ts7_2_target_2_boot_volumes_iscsi_sp = {
    "type": PROFILE1_TYPE,
    "name": PROFILE1_GEN10_NAME,
    "serverHardwareUri": SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "bootMode": {"manageMode": True, "mode": "UEFI"},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "bootVolumePriority": "Primary",
                "lun": None,
                "lunType": "Auto",
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                ],
                "volumeUri": None,
                "volume": {
                    "templateUri": "ROOT:" + STOREVIRTUAL1_POOL_NAME,
                    "properties": {
                        "name": STOREVIRTUAL_VOLUME1_NAME,
                        "storagePool": "SP:" + STOREVIRTUAL1_SYSTEM_NAME,
                        "size": 1073741824,
                        "provisioningType": "Thin",
                        "isShareable": False,
                        "dataProtectionLevel": "NetworkRaid0None",
                        "isAdaptiveOptimizationEnabled": False
                    },
                    "isPermanent": False
                },
                "volumeStorageSystemUri": "SSYS:" + STOREVIRTUAL1_SYSTEM_NAME
            },
            {
                "id": 2,
                "bootVolumePriority": "Secondary",
                "lun": None,
                "lunType": "Auto",
                "storagePaths": [
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "volumeUri": None,
                "volume": {
                    "templateUri": "ROOT:" + STOREVIRTUAL2_POOL_NAME,
                    "properties": {
                        "name": STOREVIRTUAL_VOLUME2_NAME,
                        "storagePool": "SP:" + STOREVIRTUAL2_SYSTEM_NAME,
                        "size": 1073741824,
                        "provisioningType": "Thin",
                        "isShareable": False,
                        "dataProtectionLevel": "NetworkRaid0None",
                        "isAdaptiveOptimizationEnabled": False
                    },
                    "isPermanent": False
                },
                "volumeStorageSystemUri": "SSYS:" + STOREVIRTUAL2_SYSTEM_NAME
            }
        ],
        "sanSystemCredentials": [
            {
                "storageSystemUri": "SSYS:" + STOREVIRTUAL1_SYSTEM_NAME,
                "chapLevel": "Chap"
            },
            {
                "storageSystemUri": "SSYS:" + STOREVIRTUAL2_SYSTEM_NAME,
                "chapLevel": "MutualChap"
            }
        ]
    },
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "iSCSIConn",
                "functionType": "iSCSI",
                "networkUri": "ETH:" + ISCSI_NETWORK_1,
                "ipv4": {
                    "ipAddressSource": "DHCP"
                },
                "boot": {
                    "bootVolumeSource": "ManagedVolume",
                    "priority": "Primary",
                    "bootVlanId": None
                },
                "managed": True
            },
            {
                "id": 2,
                "name": "iSCSIVLAN10Conn",
                "functionType": "iSCSI",
                "networkUri": "ETH:" + ISCSI_NETWORK_2,
                "ipv4": {
                    "ipAddressSource": "DHCP"
                },
                "boot": {
                    "bootVolumeSource": "ManagedVolume",
                    "priority": "Secondary",
                    "bootVlanId": None
                },
                "managed": True
            }
        ]
    },
}

ts7_gen10_2_target_2_boot_volume_api800_sp = {
    "type": "ServerProfileV9",
    "name": PROFILE1_GEN10_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN10,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "isBootVolume": True,
            },
            {
                "id": 2,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME2_NAME,
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "isBootVolume": True,
            }
        ],
    },
}

ts7_gen9_2_target_1_secondary_boot_volume_sp = {
    "type": PROFILE1_TYPE,
    "name": PROFILE1_GEN9_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN9,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Secondary",
            },
        ],
        "sanSystemCredentials": [],
    },
}

ts7_gen9_2_target_2_primary_boot_volumes_sp = {
    "type": PROFILE1_TYPE,
    "name": PROFILE1_GEN9_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN9,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            },
            {
                "id": 2,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME2_NAME,
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            }
        ],
        "sanSystemCredentials": [],
    },
}


ts7_gen9_2_target_2_boot_volumes_1_data_volume_sp = {
    "type": PROFILE1_TYPE,
    "name": PROFILE1_GEN9_NAME,
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": SH_GEN9,
    "enclosureGroupUri": "EG:" + EG_NAME,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConnA",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_A,
                "portId": "Auto",
                "boot": {
                    "priority": "Primary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            },
            {
                "id": 2,
                "name": "FCConnB",
                "functionType": "FibreChannel",
                "networkUri": "FC:" + FC_NETWORK_B,
                "portId": "Auto",
                "boot": {
                    "priority": "Secondary",
                    "bootVolumeSource": "ManagedVolume",
                },
                "managed": True,
            }
        ]
    },
    "bootMode": {"manageMode": True, "mode": "UEFI", "pxeBootPolicy": "Auto", "secureBoot": "Disabled"},
    "boot": {"manageBoot": True, "order": ["HardDisk"]},
    "bios": {"manageBios": False},
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV1_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME1_NAME,
                        "storagePool": "SPOOL:" + STORESERV1_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV1_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Primary",
            },
            {
                "id": 2,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME2_NAME,
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "Secondary",
            },
            {
                "id": 3,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV2_NAME,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME2_NAME + "_data",
                        "storagePool": "SPOOL:" + STORESERV2_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV2_POOL,
                },
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": None,
            },
        ],
        "sanSystemCredentials": [],
    },
}
