admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}

users = [{'userName': 'sarah', 'password': 'serveradmin', 'fullName': 'Sarah', 'roles': ['Server administrator'],
          'emailAddress': 'sarah@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
          'type': 'UserAndRoles'},
         {'userName': 'nat', 'password': 'networkadmin', 'fullName': 'Nat', 'roles': ['Network administrator'],
          'emailAddress': 'nat@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
          'type': 'UserAndRoles'},
         {'userName': 'backup', 'password': 'backupadmin', 'fullName': 'Backup', 'roles': ['Backup administrator'],
          'emailAddress': 'backup@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
          'type': 'UserAndRoles'},
         {'userName': 'rheid', 'password': 'readonly', 'fullName': 'Rheid', 'roles': ['Read only'],
          'emailAddress': 'rheid@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
          'type': 'UserAndRoles'}
         ]

licenses = [{
    'key': 'YCDE D9MA H9P9 8HUZ U7B5 HWW5 Y9JL KMPL MHND 7AJ9 DXAU 2CSM GHTG L762 LFH6 F4R4 KJVT D5KM EFVW DT5J 83HJ 8VC6 AK2P 3EW2 L9YE HUNJ TZZ7 MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEG 3F9V JQY5 "423207356 HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR H3TCJHCGAYAY"'},
    {
        'key': 'QC3C A9MA H9PQ GHVZ U7B5 HWW5 Y9JL KMPL 2HVF 4FZ9 DXAU 2CSM GHTG L762 7JX5 V5FU KJVT D5KM EFVW DV5J 43LL PSS6 AK2P 3EW2 T9YE XUNJ TZZ7 MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEG 3F9V JQY5 "423207566 HPOV-NFR2 HP_OneView_w/o_iLO_48_Seat_NFR 6H72JHCGY5AU"'}
]

ethernet_networks = [{'name': 'eth-100',
                      'type': 'ethernet-networkV4',
                      'vlanId': 100,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-a',
                      'type': 'ethernet-networkV4',
                      'vlanId': 200,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-b',
                      'type': 'ethernet-networkV4',
                      'vlanId': 201,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-c',
                      'type': 'ethernet-networkV4',
                      'vlanId': 202,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-d',
                      'type': 'ethernet-networkV4',
                      'vlanId': 203,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-e',
                      'type': 'ethernet-networkV4',
                      'vlanId': 204,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},

                     ]

network_sets = [{'name': 'netset1', 'type': 'network-setV4', 'networkUris': ['network-a']}]

fcoe_networks = {'fcoe-100': {'name': 'fcoe-100', 'type': 'fcoe-networkV4', 'vlanId': 100},
                 'fcoe-100b': {'name': 'fcoe-100b', 'type': 'fcoe-networkV4', 'vlanId': 100},
                 'fcnetwork-a': {'name': 'fcnetwork-a', 'type': 'fcoe-networkV4', 'vlanId': 209},
                 'network-a': {'name': 'network-a', 'type': 'fcoe-networkV4', 'vlanId': 210},
                 'network-b': {'name': 'network-b', 'type': 'fcoe-networkV4', 'vlanId': 211},
                 'no-vlanId': {'name': 'no-vlanId', 'type': 'fcoe-networkV4'},
                 'fcoe-4095': {'name': 'fcoe-4095', 'type': 'fcoe-networkV4', 'vlanId': 4095}}

fcoe_ranges = {'fcoe-range32a': {'prefix': 'fcoe-', 'suffix': 'a', 'start': 1001, 'end': 1032},
               'fcoe-range32b': {'prefix': 'fcoe-', 'suffix': 'b', 'start': 1001, 'end': 1032},
               'fcoe-range32c': {'prefix': 'fcoe-', 'suffix': 'c', 'start': 1001, 'end': 1032},
               'fcoe-range32d': {'prefix': 'fcoe-', 'suffix': 'd', 'start': 1001, 'end': 1032},
               'fcoe-range33': {'prefix': 'fcoe-', 'suffix': '', 'start': 1001, 'end': 1033},
               'fcoe-range30a': {'prefix': 'fcoe-', 'suffix': 'a', 'start': 1001, 'end': 1030},
               'fcoe-range128': {'prefix': 'fcoe-', 'suffix': '', 'start': 1001, 'end': 1128},
               'fcoe-range-delete-20': {'prefix': 'fcoe-', 'suffix': '', 'start': 1109, 'end': 1128}
               }

fc_networks = [{'type': 'fc-networkV4',
                'linkStabilityTime': 30,
                'autoLoginRedistribution': True,
                'name': 'fcnetwork-a',
                'connectionTemplateUri': None,
                'managedSanUri': None,
                'fabricType': 'FabricAttach'}]

enc_group = {'name': 'EG',
             'interconnectBayMappings':
                 [{'interconnectBay': N,
                   'logicalInterconnectGroupUri': None}
                  for N in range(1, 9)]}

enc = {'hostname': '15.199.230.74', 'username': 'Administrator', 'password': 'hpvse1', 'enclosureGroupUri': None,
       'force': False, 'licensingIntent': 'OneViewNoiLO'}

appliance = {'type': 'ApplianceServerConfiguration',
             'applianceNetworks':
                 [{'device': 'eth0',
                   'macAddress': None,
                   'interfaceName': '15.199.x.x',
                   'activeNode': '1',
                   'unconfigure': False,
                   'ipv4Type': 'DHCP',
                   'ipv4Subnet': None,
                   'ipv4Gateway': None,
                   'ipv4NameServers': ['16.110.135.51', '16.110.135.52'],
                   'app1Ipv4Addr': None,
                   'app1Ipv4Alias': None,
                   'app2Ipv4Addr': None,
                   'app2Ipv4Alias': None,
                   'virtIpv4Addr': None,
                   'ipv6Type': 'UNCONFIGURE',
                   'ipv6Subnet': None,
                   'ipv6Gateway': None,
                   'ipv6NameServers': ['16.110.135.51', '16.110.135.52'],
                   'app1Ipv6Addr': None,
                   'app1Ipv6Alias': None,
                   'app2Ipv6Addr': None,
                   'app2Ipv6Alias': None,
                   'virtIpv6Addr': None,
                   'hostname': 'cic-rb.usa.hp.com',
                   'confOneNode': True,
                   'overrideIpv4DhcpDnsServers': False,
                   'domainName': 'usa.hp.com',
                   'searchDomains': ['usa.hp.com'],
                   'bondedTo': None,
                   'aliasDisabled': True,
                   'configurePostgresSslListener': False,
                   'configureRabbitMqSslListener': False,
                   'webServerCertificate': None,
                   'webServerCertificateChain': None,
                   'webServerCertificateKey': None}],
             'time': {'dateTime': None, 'pollingInterval': '120', 'timezone': 'UTC', 'ntpServers': ['ntp.hp.net']},
             'locale': {'locale': 'en_US.UTF-8', 'displayName': None}}

true = True
false = False

rc = {'200': 200, '201': 201, '202': 202, '400': 400, '401': 401, '403': 403, '412': 412, '500': 500}


def make_range_list(vrange):
    rlist = []
    for x in xrange(vrange['start'], (vrange['end'] + 1)):
        rlist.append(vrange['prefix'] + str(x) + vrange['suffix'])
    return rlist


uplink_sets = {'us1': {'name': 'us1',
                       'ethernetNetworkType': 'Tagged',
                       'networkType': 'Ethernet',
                       'networkUris': make_range_list(fcoe_ranges['fcoe-range32a']),
                       'primaryPort': {'bay': '1', 'port': 'X1'},
                       'nativeNetworkUri': None,
                       'mode': 'Failover',
                       'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X2', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X3', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X4', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X5', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X6', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X7', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X8', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X9', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X10', 'speed': 'Auto'}]},
               'us2': {'name': 'us2',
                       'ethernetNetworkType': 'Tagged',
                       'networkType': 'Ethernet',
                       'networkUris': make_range_list(fcoe_ranges['fcoe-range32b']),
                       'primaryPort': {'bay': '3', 'port': 'X1'},
                       'nativeNetworkUri': None,
                       'mode': 'Failover',
                       'logicalPortConfigInfos': [{'bay': '3', 'port': 'X1', 'speed': 'Auto'},
                                                  {'bay': '3', 'port': 'X2', 'speed': 'Auto'},
                                                  {'bay': '3', 'port': 'X3', 'speed': 'Auto'},
                                                  {'bay': '3', 'port': 'X4', 'speed': 'Auto'}]},
               'us3': {'name': 'us3',
                       'ethernetNetworkType': 'Tagged',
                       'networkType': 'Ethernet',
                       'networkUris': make_range_list(fcoe_ranges['fcoe-range32c']),
                       'primaryPort': {'bay': '5', 'port': 'X1'},
                       'nativeNetworkUri': None,
                       'mode': 'Failover',
                       'logicalPortConfigInfos': [{'bay': '5', 'port': 'X1', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X2', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X3', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X4', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X5', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X6', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X7', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X8', 'speed': 'Auto'}]},
               'us33': {'name': 'us-33-exceeds-32',
                        'ethernetNetworkType': 'Tagged',
                        'networkType': 'Ethernet',
                        'networkUris': make_range_list(fcoe_ranges['fcoe-range33']),
                        'primaryPort': {'bay': '4', 'port': 'X1'},
                        'nativeNetworkUri': None,
                        'mode': 'Failover',
                        'logicalPortConfigInfos': [{'bay': '4', 'port': 'X1', 'speed': 'Auto'},
                                                   {'bay': '4', 'port': 'X2', 'speed': 'Auto'},
                                                   {'bay': '4', 'port': 'X3', 'speed': 'Auto'},
                                                   {'bay': '4', 'port': 'X4', 'speed': 'Auto'}]},
               'us1-b': {'name': 'us1-b-removed X10',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': make_range_list(fcoe_ranges['fcoe-range30a']),
                         'primaryPort': {'bay': '1', 'port': 'X1'},
                         'nativeNetworkUri': None,
                         'mode': 'Failover',
                         'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X2', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X3', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X4', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X5', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X6', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X7', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X8', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X9', 'speed': 'Auto'}]},

               'us1-c': {'name': 'us-3-exceeds-32max',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': ['fcoe-1001', 'fcoe-1002', 'fcoe-1003'],
                         'primaryPort': {'bay': '1', 'port': 'X10'},
                         'nativeNetworkUri': None,
                         'mode': 'Failover',
                         'logicalPortConfigInfos': [{'bay': '1', 'port': 'X10', 'speed': 'Auto'}]},
               'us1-d': {'name': 'us1',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': make_range_list(fcoe_ranges['fcoe-range32a']),
                         'primaryPort': {'bay': '1', 'port': 'X1'},
                         'nativeNetworkUri': None,
                         'mode': 'Failover',
                         'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X2', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X3', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X4', 'speed': 'Auto'}]},
               'us1-eth': {'name': 'us1-eth',
                           'ethernetNetworkType': 'Tagged',
                           'networkType': 'Ethernet',
                           'networkUris': ['network-d'],
                           'primaryPort': {'bay': '1', 'port': 'X5'},
                           'nativeNetworkUri': None,
                           'mode': 'Failover',
                           'logicalPortConfigInfos': [{'bay': '1', 'port': 'X5', 'speed': 'Auto'},
                                                      {'bay': '1', 'port': 'X6', 'speed': 'Auto'}]},
               'us2-d': {'name': 'us2',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': make_range_list(fcoe_ranges['fcoe-range32b']),
                         'primaryPort': {'bay': '3', 'port': 'X1'},
                         'nativeNetworkUri': None,
                         'mode': 'Failover',
                         'logicalPortConfigInfos': [{'bay': '3', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '3', 'port': 'X2', 'speed': 'Auto'}]},
               'us2-fc': {'name': 'us2-fc',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'FibreChannel',
                          'networkUris': ['fcnetwork-a'],
                          'primaryPort': {'bay': '3', 'port': 'X3'},
                          'nativeNetworkUri': None,
                          'mode': 'Failover',
                          'logicalPortConfigInfos': [{'bay': '3', 'port': 'X3', 'speed': 'Auto'},
                                                     {'bay': '3', 'port': 'X4', 'speed': 'Auto'}]},
               'us3-d': {'name': 'us3',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': make_range_list(fcoe_ranges['fcoe-range32c']),
                         'primaryPort': {'bay': '5', 'port': 'X1'},
                         'nativeNetworkUri': None,
                         'mode': 'Failover',
                         'logicalPortConfigInfos': [{'bay': '5', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '5', 'port': 'X2', 'speed': 'Auto'},
                                                    {'bay': '5', 'port': 'X3', 'speed': 'Auto'},
                                                    {'bay': '5', 'port': 'X4', 'speed': 'Auto'}]},
               'us3-eth': {'name': 'us3-eth',
                           'ethernetNetworkType': 'Tagged',
                           'networkType': 'Ethernet',
                           'networkUris': ['network-e'],
                           'primaryPort': {'bay': '5', 'port': 'X5'},
                           'nativeNetworkUri': None,
                           'mode': 'Failover',
                           'logicalPortConfigInfos': [{'bay': '5', 'port': 'X5', 'speed': 'Auto'},
                                                      {'bay': '5', 'port': 'X6', 'speed': 'Auto'},
                                                      {'bay': '5', 'port': 'X7', 'speed': 'Auto'},
                                                      {'bay': '5', 'port': 'X8', 'speed': 'Auto'}]},
               'us3-2ics': {'name': 'us2-ics',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': ['fcoe-100'],
                            'primaryPort': {'bay': '5', 'port': 'X5'},
                            'nativeNetworkUri': None,
                            'mode': 'Failover',
                            'logicalPortConfigInfos': [{'bay': '5', 'port': 'X5', 'speed': 'Auto'},
                                                       {'bay': '6', 'port': 'X5', 'speed': 'Auto'}]},
               'unsupported-ics': {'name': 'unsupported-ics',
                                   'ethernetNetworkType': 'Tagged',
                                   'networkType': 'Ethernet',
                                   'networkUris': ['fcoe-100'],
                                   'primaryPort': {'bay': '1', 'port': 'X1'},
                                   'nativeNetworkUri': None,
                                   'mode': 'Failover',
                                   'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'}]},
               'unsupported-ics2': {'name': 'unsupported-ics2',
                                    'ethernetNetworkType': 'Tagged',
                                    'networkType': 'Ethernet',
                                    'networkUris': ['fcoe-100'],
                                    'primaryPort': {'bay': '1', 'port': '1'},
                                    'nativeNetworkUri': None,
                                    'mode': 'Failover',
                                    'logicalPortConfigInfos': [{'bay': '1', 'port': '1', 'speed': 'Auto'}]},
               'duplicate-vlan': {'name': 'duplicate-vlan',
                                  'ethernetNetworkType': 'Tagged',
                                  'networkType': 'Ethernet',
                                  'networkUris': [],
                                  'primaryPort': {'bay': '1', 'port': 'X1'},
                                  'nativeNetworkUri': None,
                                  'mode': 'Failover',
                                  'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'}]},
               }

li_uplink_sets = {'us1': {'name': 'us1',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': [],
                          'fcNetworkUris': [],
                          'fcoeNetworkUris': make_range_list(fcoe_ranges['fcoe-range32a']),
                          'lacpTimer': 'Short',
                          'logicalInterconnectUri': None,
                          'primaryPortLocation': {'bay': '1', 'port': 'X1', 'enclosure': None},
                          'manualLoginRedistributionState': 'NotSupported',
                          'connectionMode': 'Failover',
                          'nativeNetworkUri': None,
                          'portConfigInfos': [{'bay': '1', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X5', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X6', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X7', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X8', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X9', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X10', 'desiredSpeed': 'Auto', 'enclosure': None}]}}

icmap = [{'bay': 1, 'type': 'HP VC Flex-10/10D Module'},
         {'bay': 2, 'type': 'HP VC Flex-10/10D Module'},
         {'bay': 3, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
         {'bay': 4, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
         {'bay': 5, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
         {'bay': 6, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
         {'bay': 7, 'type': 'Cisco Fabric Extender for HP BladeSystem'},
         {'bay': 8, 'type': 'Cisco Fabric Extender for HP BladeSystem'}]

icmap2 = [{'bay': 1, 'type': 'HP VC Flex-10 Enet Module'},
          {'bay': 2, 'type': 'HP VC Flex-10 Enet Module'}]

icmap3 = [{'bay': 1, 'type': 'HP VC 8Gb 20-Port FC Module'}]

icmap4 = [{'bay': 1, 'type': 'HP VC Flex-10/10D Module'},
          {'bay': 2, 'type': 'HP VC Flex-10/10D Module'},
          {'bay': 3, 'type': 'HP VC Flex-10 Enet Module'},
          {'bay': 4, 'type': 'HP VC Flex-10 Enet Module'},
          {'bay': 5, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
          {'bay': 6, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
          {'bay': 7, 'type': 'Cisco Fabric Extender for HP BladeSystem'},
          {'bay': 8, 'type': 'Cisco Fabric Extender for HP BladeSystem'}]

ligs = {'lig1': {'name': 'LIG1',
                 'type': 'logical-interconnect-groupV3',
                 'enclosureType': 'C7000',
                 'interconnectMapTemplate': icmap,
                 'uplinkSets': [uplink_sets['us1'].copy(), uplink_sets['us2'].copy(), uplink_sets['us3'].copy()],
                 'stackingMode': None,
                 'ethernetSettings': None,
                 'state': 'Active',
                 'telemetryConfiguration': None,
                 'snmpConfiguration': None},

        'lig2':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV3',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1'].copy(), uplink_sets['us2'].copy(), uplink_sets['us3'].copy(),
                            uplink_sets['us33'].copy()],
             'stackingMode': None,
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig3':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV3',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1-b'].copy(), uplink_sets['us1-c'].copy(), uplink_sets['us2'].copy(),
                            uplink_sets['us3'].copy()],
             'stackingMode': None,
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig4':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV3',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1-d'].copy(), uplink_sets['us2-d'].copy(), uplink_sets['us3-d'].copy()],
             'stackingMode': None,
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig5':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV3',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1-d'].copy(), uplink_sets['us1-eth'].copy(), uplink_sets['us2-d'].copy(),
                            uplink_sets['us2-fc'].copy(), uplink_sets['us3-d'].copy(), uplink_sets['us3-eth'].copy()],
             'stackingMode': None,
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig6':
            {'name': 'LIG2',
             'type': 'logical-interconnect-groupV3',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us3-2ics'].copy()],
             'stackingMode': None,
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig7':
            {'name': 'LIG3',
             'type': 'logical-interconnect-groupV3',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap2,
             'uplinkSets': [uplink_sets['unsupported-ics'].copy()],
             'stackingMode': None,
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig8':
            {'name': 'LIG3',
             'type': 'logical-interconnect-groupV3',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap3,
             'uplinkSets': [uplink_sets['unsupported-ics2'].copy()],
             'stackingMode': None,
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig9':
            {'name': 'LIG3',
             'type': 'logical-interconnect-groupV3',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['duplicate-vlan'].copy()],
             'stackingMode': None,
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig10':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV3',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap4,
             'uplinkSets': [uplink_sets['us1'].copy(), uplink_sets['us2'].copy(), uplink_sets['us3'].copy()],
             'stackingMode': None,
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None}
        }

telemetry = {'enableTelemetry': True, 'sampleInterval': 400, 'sampleCount': 20}

trapDestinations = [{'trapSeverities': ['Major'],
                     'enetTrapCategories': ['Other'],
                     'fcTrapCategories': ['Other'],
                     'vcmTrapCategories': ['Legacy'],
                     'trapFormat': 'SNMPv1',
                     'trapDestination': '192.168.99.99',
                     'communityString': 'public'}]

snmp = {'snmpAccess': ['192.168.1.0/24'],
        'trapDestinations': trapDestinations}

enet = {'enableFastMacCacheFailover': False}

server_profiles = {'profile1': {"type": "ServerProfileV8",
                                "name": "Profile1",
                                "serverHardwareUri": None,
                                "enclosureGroupUri": None,
                                "enclosureUri": None
                                },
                   'profile2': {"description": "", "wwnType": "Physical", "boot": {"manageBoot": True,
                                                                                   "order": [{"device": "PXE"},
                                                                                             {"device": "CD"},
                                                                                             {"device": "Floppy"},
                                                                                             {"device": "USB"},
                                                                                             {"device": "HardDisk"}]},
                                "serialNumberType": "Physical",
                                "connections": [
                                    {"networkUri": "/rest/ethernet-networks/08318d27-740a-4b44-bbb4-af1c0abda36b",
                                     "portId": "Flb 1:1-a", "requestedMbps": "2500",
                                     "boot": {"priority": "NotBootable"}, "functionType": "Ethernet", "id": 1},
                                    {"requestedMbps": "2500", "functionType": "FibreChannel", "id": 2,
                                     "networkUri": "/rest/fc-networks/354601fd-f30e-420f-bb4d-e2e81de4040c",
                                     "portId": "Flb 1:1-b", "boot": {"priority": "Primary", "targets": [
                                         {"lun": "02", "arrayWwpn": "20010002AC003D7E"}]}},
                                    {"networkUri": "/rest/ethernet-networks/08318d27-740a-4b44-bbb4-af1c0abda36b",
                                     "portId": "Flb 1:2-a", "requestedMbps": "2500",
                                     "boot": {"priority": "NotBootable"}, "functionType": "Ethernet", "id": 3}],
                                "serverHardwareUri": "/rest/server-hardware/30313436-3631-5355-4532-3332424E304E",
                                "macType": "Physical", "serverHardwareTypeUri": "", "name": "Bay1-BL460cGen8-BFS",
                                "firmware": {"firmwareBaselineUri": "", "manageFirmware": False},
                                "enclosureGroupUri": "", "bios": {"overriddenSettings": [], "manageBios": False},
                                "sanStorage": None, "type": "ServerProfileV3"}
                   }

default_variables = {'admin_credentials': admin_credentials,
                     'appliance': appliance,
                     'enc': enc,
                     'enc_group': enc_group,
                     'ethernet_networks': ethernet_networks,
                     'fc_networks': fc_networks,
                     'fcoe_networks': fcoe_networks,
                     'fcoe_ranges': fcoe_ranges,
                     'licenses': licenses,
                     'ligs': ligs,
                     'li_uplink_sets': li_uplink_sets,
                     'network_sets': network_sets,
                     'rc': rc,
                     'server_profiles': server_profiles,
                     'uplink_sets': uplink_sets,
                     'users': users,
                     'true': true, 'false': false}


def get_variables():
    variables = default_variables
    return variables
