# User Login Data
admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}

server_profiles_r4 = [
    {'name': 'r4-1-b1', 'serverHardwareUri': 'r4-1, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b2', 'serverHardwareUri': 'r4-1, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b3', 'serverHardwareUri': 'r4-1, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b4', 'serverHardwareUri': 'r4-1, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b5', 'serverHardwareUri': 'r4-1, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b6', 'serverHardwareUri': 'r4-1, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b7', 'serverHardwareUri': 'r4-1, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b8', 'serverHardwareUri': 'r4-1, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b9', 'serverHardwareUri': 'r4-1, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b10', 'serverHardwareUri': 'r4-1, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b11', 'serverHardwareUri': 'r4-1, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-1-b12', 'serverHardwareUri': 'r4-1, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b1', 'serverHardwareUri': 'r4-2, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b2', 'serverHardwareUri': 'r4-2, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b3', 'serverHardwareUri': 'r4-2, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b4', 'serverHardwareUri': 'r4-2, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b5', 'serverHardwareUri': 'r4-2, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b6', 'serverHardwareUri': 'r4-2, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b7', 'serverHardwareUri': 'r4-2, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b8', 'serverHardwareUri': 'r4-2, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b9', 'serverHardwareUri': 'r4-2, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b10', 'serverHardwareUri': 'r4-2, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b11', 'serverHardwareUri': 'r4-2, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-2-b12', 'serverHardwareUri': 'r4-2, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b1', 'serverHardwareUri': 'r4-3, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b2', 'serverHardwareUri': 'r4-3, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b3', 'serverHardwareUri': 'r4-3, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b4', 'serverHardwareUri': 'r4-3, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b5', 'serverHardwareUri': 'r4-3, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b5', 'serverHardwareUri': 'r4-3, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b6', 'serverHardwareUri': 'r4-3, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b7', 'serverHardwareUri': 'r4-3, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b8', 'serverHardwareUri': 'r4-3, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b9', 'serverHardwareUri': 'r4-3, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b10', 'serverHardwareUri': 'r4-3, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b11', 'serverHardwareUri': 'r4-3, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-3-b12', 'serverHardwareUri': 'r4-3, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b1', 'serverHardwareUri': 'r4-4, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b2', 'serverHardwareUri': 'r4-4, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b3', 'serverHardwareUri': 'r4-4, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b4', 'serverHardwareUri': 'r4-4, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b5', 'serverHardwareUri': 'r4-4, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b5', 'serverHardwareUri': 'r4-4, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b6', 'serverHardwareUri': 'r4-4, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b7', 'serverHardwareUri': 'r4-4, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b8', 'serverHardwareUri': 'r4-4, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b9', 'serverHardwareUri': 'r4-4, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b10', 'serverHardwareUri': 'r4-4, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b11', 'serverHardwareUri': 'r4-4, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-4-b12', 'serverHardwareUri': 'r4-4, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b1', 'serverHardwareUri': 'r4-5, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b2', 'serverHardwareUri': 'r4-5, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b3', 'serverHardwareUri': 'r4-5, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b4', 'serverHardwareUri': 'r4-5, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b5', 'serverHardwareUri': 'r4-5, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b5', 'serverHardwareUri': 'r4-5, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b6', 'serverHardwareUri': 'r4-5, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b7', 'serverHardwareUri': 'r4-5, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b8', 'serverHardwareUri': 'r4-5, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b9', 'serverHardwareUri': 'r4-5, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b10', 'serverHardwareUri': 'r4-5, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b11', 'serverHardwareUri': 'r4-5, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'},
    {'name': 'r4-5-b12', 'serverHardwareUri': 'r4-5, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r4', 'type': 'ServerProfileV8'}
]

server_profiles_r7 = [
    # {'name': 'r7-1-b1', 'serverHardwareUri': 'r7-1, bay 1', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    # {'name': 'r7-1-b2', 'serverHardwareUri': 'r7-1, bay 2', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b3', 'serverHardwareUri': 'r7-1, bay 3', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b4', 'serverHardwareUri': 'r7-1, bay 4', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b5', 'serverHardwareUri': 'r7-1, bay 5', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b6', 'serverHardwareUri': 'r7-1, bay 6', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b7', 'serverHardwareUri': 'r7-1, bay 7', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b8', 'serverHardwareUri': 'r7-1, bay 8', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b9', 'serverHardwareUri': 'r7-1, bay 9', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b10', 'serverHardwareUri': 'r7-1, bay 10', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b11', 'serverHardwareUri': 'r7-1, bay 11', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-1-b12', 'serverHardwareUri': 'r7-1, bay 12', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    # {'name': 'r7-2-b1', 'serverHardwareUri': 'r7-2, bay 1', 'serverHardwareTypeUri': 'SHT:r7','serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    # {'name': 'r7-2-b2', 'serverHardwareUri': 'r7-2, bay 2', 'serverHardwareTypeUri': 'SHT:r7','serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b3', 'serverHardwareUri': 'r7-2, bay 3', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b4', 'serverHardwareUri': 'r7-2, bay 4', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b5', 'serverHardwareUri': 'r7-2, bay 5', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b6', 'serverHardwareUri': 'r7-2, bay 6', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b7', 'serverHardwareUri': 'r7-2, bay 7', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b8', 'serverHardwareUri': 'r7-2, bay 8', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b9', 'serverHardwareUri': 'r7-2, bay 9', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b10', 'serverHardwareUri': 'r7-2, bay 10', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b11', 'serverHardwareUri': 'r7-2, bay 11', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-2-b12', 'serverHardwareUri': 'r7-2, bay 12', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    # {'name': 'r7-3-b1', 'serverHardwareUri': 'r7-3, bay 1', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    # {'name': 'r7-3-b2', 'serverHardwareUri': 'r7-3, bay 2', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-3-b3', 'serverHardwareUri': 'r7-3, bay 3', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-3-b4', 'serverHardwareUri': 'r7-3, bay 4', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    # {'name': 'r7-3-b5', 'serverHardwareUri': 'r7-3, bay 5', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    # {'name': 'r7-3-b6', 'serverHardwareUri': 'r7-3, bay 6', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-3-b7', 'serverHardwareUri': 'r7-3, bay 7', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-3-b8', 'serverHardwareUri': 'r7-3, bay 8', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-3-b9', 'serverHardwareUri': 'r7-3, bay 9', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    {'name': 'r7-3-b10', 'serverHardwareUri': 'r7-3, bay 10', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'}
    # {'name': 'r7-3-b11', 'serverHardwareUri': 'r7-3, bay 11', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'},
    # {'name': 'r7-3-b12', 'serverHardwareUri': 'r7-3, bay 12', 'serverHardwareTypeUri': 'SHT:r7', 'serverProfileTemplateUri': 'SPT:r7', 'type': 'ServerProfileV8'}
]

server_profiles_r8 = [
    {'name': 'r8-1-b5', 'serverHardwareUri': 'r8-1, bay 5', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-1-b6', 'serverHardwareUri': 'r8-1, bay 6', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-1-b7', 'serverHardwareUri': 'r8-1, bay 7', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-1-b8', 'serverHardwareUri': 'r8-1, bay 8', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-1-b9', 'serverHardwareUri': 'r8-1, bay 9', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-1-b10', 'serverHardwareUri': 'r8-1, bay 10', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-1-b11', 'serverHardwareUri': 'r8-1, bay 11', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-1-b12', 'serverHardwareUri': 'r8-1, bay 12', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-2-b5', 'serverHardwareUri': 'r8-2, bay 5', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-2-b6', 'serverHardwareUri': 'r8-2, bay 6', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-2-b7', 'serverHardwareUri': 'r8-2, bay 7', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-2-b8', 'serverHardwareUri': 'r8-2, bay 8', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-2-b9', 'serverHardwareUri': 'r8-2, bay 9', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    # {'name': 'r8-2-b10', 'serverHardwareUri': 'r8-2, bay 10', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-2-b11', 'serverHardwareUri': 'r8-2, bay 11', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-2-b12', 'serverHardwareUri': 'r8-2, bay 12', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-3-b5', 'serverHardwareUri': 'r8-3, bay 5', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-3-b6', 'serverHardwareUri': 'r8-3, bay 6', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-3-b7', 'serverHardwareUri': 'r8-3, bay 7', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-3-b8', 'serverHardwareUri': 'r8-3, bay 8', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-3-b9', 'serverHardwareUri': 'r8-3, bay 9', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-3-b10', 'serverHardwareUri': 'r8-3, bay 10', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-3-b11', 'serverHardwareUri': 'r8-3, bay 11', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'},
    {'name': 'r8-3-b12', 'serverHardwareUri': 'r8-3, bay 12', 'serverHardwareTypeUri': 'SHT:r8', 'serverProfileTemplateUri': 'SPT:r8', 'type': 'ServerProfileV8'}
]

server_profiles_r9 = [
    {'name': 'r9-1-b1', 'serverHardwareUri': 'r9-1, bay 1', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b2', 'serverHardwareUri': 'r9-1, bay 2', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b3', 'serverHardwareUri': 'r9-1, bay 3', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b4', 'serverHardwareUri': 'r9-1, bay 4', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b5', 'serverHardwareUri': 'r9-1, bay 5', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b6', 'serverHardwareUri': 'r9-1, bay 6', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b7', 'serverHardwareUri': 'r9-1, bay 7', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-1-b8', 'serverHardwareUri': 'r9-1, bay 8', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b9', 'serverHardwareUri': 'r9-1, bay 9', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b10', 'serverHardwareUri': 'r9-1, bay 10', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b11', 'serverHardwareUri': 'r9-1, bay 11', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-1-b12', 'serverHardwareUri': 'r9-1, bay 12', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b1', 'serverHardwareUri': 'r9-2, bay 1', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b2', 'serverHardwareUri': 'r9-2, bay 2', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b3', 'serverHardwareUri': 'r9-2, bay 3', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b4', 'serverHardwareUri': 'r9-2, bay 4', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b5', 'serverHardwareUri': 'r9-2, bay 5', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b6', 'serverHardwareUri': 'r9-2, bay 6', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b7', 'serverHardwareUri': 'r9-2, bay 7', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b8', 'serverHardwareUri': 'r9-2, bay 8', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b9', 'serverHardwareUri': 'r9-2, bay 9', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b10', 'serverHardwareUri': 'r9-2, bay 10', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-2-b11', 'serverHardwareUri': 'r9-2, bay 11', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-2-b12', 'serverHardwareUri': 'r9-2, bay 12', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-3-b1', 'serverHardwareUri': 'r9-3, bay 1', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-3-b2', 'serverHardwareUri': 'r9-3, bay 2', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    {'name': 'r9-3-b3', 'serverHardwareUri': 'r9-3, bay 3', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'}
    # {'name': 'r9-3-b4', 'serverHardwareUri': 'r9-3, bay 4', 'serverHardwareTypeUri': 'SHT:r9','serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-3-b5', 'serverHardwareUri': 'r9-3, bay 5', 'serverHardwareTypeUri': 'SHT:r9','serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-3-b6', 'serverHardwareUri': 'r9-3, bay 6', 'serverHardwareTypeUri': 'SHT:r9','serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-3-b7', 'serverHardwareUri': 'r9-3, bay 7', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-3-b8', 'serverHardwareUri': 'r9-3, bay 8', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-3-b9', 'serverHardwareUri': 'r9-3, bay 9', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-3-b10', 'serverHardwareUri': 'r9-3, bay 10', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-3-b11', 'serverHardwareUri': 'r9-3, bay 11', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'},
    # {'name': 'r9-3-b12', 'serverHardwareUri': 'r9-3, bay 12', 'serverHardwareTypeUri': 'SHT:r9', 'serverProfileTemplateUri': 'SPT:r9', 'type': 'ServerProfileV8'}
]

server_profiles_r10 = [
    {'name': 'r10-1-b1', 'serverHardwareUri': 'r10-1, bay 1', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b2', 'serverHardwareUri': 'r10-1, bay 2', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b3', 'serverHardwareUri': 'r10-1, bay 3', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b4', 'serverHardwareUri': 'r10-1, bay 4', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b5', 'serverHardwareUri': 'r10-1, bay 5', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b6', 'serverHardwareUri': 'r10-1, bay 6', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b7', 'serverHardwareUri': 'r10-1, bay 7', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b8', 'serverHardwareUri': 'r10-1, bay 8', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b9', 'serverHardwareUri': 'r10-1, bay 9', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b10', 'serverHardwareUri': 'r10-1, bay 10', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-1-b11', 'serverHardwareUri': 'r10-1, bay 11', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    # {'name': 'r10-1-b12', 'serverHardwareUri': 'r10-1, bay 12', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b1', 'serverHardwareUri': 'r10-2, bay 1', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b2', 'serverHardwareUri': 'r10-2, bay 2', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b3', 'serverHardwareUri': 'r10-2, bay 3', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    # {'name': 'r10-2-b4', 'serverHardwareUri': 'r10-2, bay 4', 'serverHardwareTypeUri': 'SHT:r10','serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b5', 'serverHardwareUri': 'r10-2, bay 5', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b6', 'serverHardwareUri': 'r10-2, bay 6', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b7', 'serverHardwareUri': 'r10-2, bay 7', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b8', 'serverHardwareUri': 'r10-2, bay 8', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b9', 'serverHardwareUri': 'r10-2, bay 9', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b10', 'serverHardwareUri': 'r10-2, bay 10', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b11', 'serverHardwareUri': 'r10-2, bay 11', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-2-b12', 'serverHardwareUri': 'r10-2, bay 12', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    # {'name': 'r10-3-b1', 'serverHardwareUri': 'r10-3, bay 1', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b2', 'serverHardwareUri': 'r10-3, bay 2', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b3', 'serverHardwareUri': 'r10-3, bay 3', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b4', 'serverHardwareUri': 'r10-3, bay 4', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b5', 'serverHardwareUri': 'r10-3, bay 5', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b6', 'serverHardwareUri': 'r10-3, bay 6', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b7', 'serverHardwareUri': 'r10-3, bay 7', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b8', 'serverHardwareUri': 'r10-3, bay 8', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b9', 'serverHardwareUri': 'r10-3, bay 9', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b10', 'serverHardwareUri': 'r10-3, bay 10', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b11', 'serverHardwareUri': 'r10-3, bay 11', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'},
    {'name': 'r10-3-b12', 'serverHardwareUri': 'r10-3, bay 12', 'serverHardwareTypeUri': 'SHT:r10', 'serverProfileTemplateUri': 'SPT:r10', 'type': 'ServerProfileV8'}
]

server_profiles_r15 = [
    {'name': 'r15-1-b1', 'serverHardwareUri': 'r15-1, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-1-b2', 'serverHardwareUri': 'r15-1, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-1-b3', 'serverHardwareUri': 'r15-1, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-1-b4', 'serverHardwareUri': 'r15-1, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-1-b5', 'serverHardwareUri': 'r15-1, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-1-b6', 'serverHardwareUri': 'r15-1, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-1-b7', 'serverHardwareUri': 'r15-1, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-1-b8', 'serverHardwareUri': 'r15-1, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-1-b9', 'serverHardwareUri': 'r15-1, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    # {'name': 'r15-1-b10', 'serverHardwareUri': 'r15-1, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    # {'name': 'r15-1-b11', 'serverHardwareUri': 'r15-1, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    # {'name': 'r15-1-b12', 'serverHardwareUri': 'r15-1, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-2-b1', 'serverHardwareUri': 'r15-2, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-2-b2', 'serverHardwareUri': 'r15-2, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-2-b3', 'serverHardwareUri': 'r15-2, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-2-b4', 'serverHardwareUri': 'r15-2, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-2-b5', 'serverHardwareUri': 'r15-2, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-2-b6', 'serverHardwareUri': 'r15-2, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-2-b7', 'serverHardwareUri': 'r15-2, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-2-b8', 'serverHardwareUri': 'r15-2, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-2-b9', 'serverHardwareUri': 'r15-2, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    # {'name': 'r15-2-b10', 'serverHardwareUri': 'r15-2, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    # {'name': 'r15-2-b11', 'serverHardwareUri': 'r15-2, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    # {'name': 'r15-2-b12', 'serverHardwareUri': 'r15-2, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-3-b1', 'serverHardwareUri': 'r15-3, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-3-b2', 'serverHardwareUri': 'r15-3, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-3-b3', 'serverHardwareUri': 'r15-3, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-3-b4', 'serverHardwareUri': 'r15-3, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-3-b5', 'serverHardwareUri': 'r15-3, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-3-b7', 'serverHardwareUri': 'r15-3, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-3-b8', 'serverHardwareUri': 'r15-3, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-3-b9', 'serverHardwareUri': 'r15-3, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    # {'name': 'r15-3-b10', 'serverHardwareUri': 'r15-3, bay 10', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    # {'name': 'r15-3-b11', 'serverHardwareUri': 'r15-3, bay 11', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    # {'name': 'r15-3-b12', 'serverHardwareUri': 'r15-3, bay 12', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-4-b1', 'serverHardwareUri': 'r15-4, bay 1', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-4-b2', 'serverHardwareUri': 'r15-4, bay 2', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-4-b3', 'serverHardwareUri': 'r15-4, bay 3', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-4-b4', 'serverHardwareUri': 'r15-4, bay 4', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-4-b5', 'serverHardwareUri': 'r15-4, bay 5', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-4-b6', 'serverHardwareUri': 'r15-4, bay 6', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-4-b7', 'serverHardwareUri': 'r15-4, bay 7', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-4-b8', 'serverHardwareUri': 'r15-4, bay 8', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'},
    {'name': 'r15-4-b9', 'serverHardwareUri': 'r15-4, bay 9', 'serverHardwareTypeUri': 'SHT:r4-r15', 'serverProfileTemplateUri': 'SPT:r15', 'type': 'ServerProfileV8'}
]
