admin_credentials = {'userName': 'Administrator', 'password': 'wpsthpvse1'}
ilo_credentials = {'username': 'Administrator', 'password': 'hpvse123'}
cliq_credentials = {'mgmt_ip': '16.71.149.173', 'username': 'admin', 'password': 'admin'}

# Resource types for X-API-Version=800
APPLIANCE_NETWORK_CONFIGURATION_TYPE = 'ApplianceNetworkConfigurationV2'
TIME_AND_LOCALE_TYPE = 'TimeAndLocale'
USER_AND_PERMISSION_TYPE = 'UserAndPermissions'
ETHERNET_NETWORK_TYPE = 'ethernet-networkV4'
FCOE_NETWORK_TYPE = 'fcoe-networkV4'
FC_NETWORK_TYPE = 'fc-networkV4'
NETWORK_SET_TYPE = 'network-setV4'
LOGICAL_INTERCONNECT_GROUP_TYPE = 'logical-interconnect-groupV5'
SAS_LOGICAL_INTERCONNECT_GROUP_TYPE = 'sas-logical-interconnect-groupV2'
ENCLOSURE_GROUP_TYPE = 'EnclosureGroupV7'
INTERCONNECT_TYPE = 'InterconnectV4'
ENCLOSURE_TYPE = 'EnclosureV7'
STORAGE_SYSTEM_TYPE = 'StorageSystemV4'
SERVER_PROFILE_TEMPLATE_TYPE = 'ServerProfileTemplateV6'
SERVER_PROFILE_TYPE = 'ServerProfileV10'
SERVER_PROFILE_COMPLIANCE_PREVIEW_TYPE = 'ServerProfileCompliancePreviewV1'
SAS_LOGICAL_JBOD_TYPE = 'sas-logical-jbodV4'

# Enclosures
ENC1 = 'CN754406XL'
ENC2 = 'CN754404R6'
ENC3 = 'CN754406WB'

# LIG, SASLIG, AND LE
LIG_NAME = 'LIG1'
SASLIG_NAME = 'SASLIG1'
EG_NAME = 'EG1'
LE_NAME = 'LE1'

# Potash interconnects
ENC1ICBAY3 = '%s, interconnect 3' % ENC1
ENC2ICBAY6 = '%s, interconnect 6' % ENC2

# Natasha SAS interconnects
ENC1SASICBAY1 = '%s, interconnect 1' % ENC1
ENC1SASICBAY4 = '%s, interconnect 4' % ENC1

# Drive Enclosures (Bigbird)
ENC1DEBAY1 = '%s, bay 1' % ENC1

# Server Hardware
ENC1SHBAY1 = '%s, bay 1' % ENC1
ENC1SHBAY3 = '%s, bay 3' % ENC1
ENC1SHBAY5 = '%s, bay 5' % ENC1
ENC1SHBAY6 = '%s, bay 6' % ENC1
ENC1SHBAY7 = '%s, bay 7' % ENC1
ENC1SHBAY8 = '%s, bay 8' % ENC1
ENC2SHBAY1 = '%s, bay 1' % ENC2
ENC2SHBAY5 = '%s, bay 5' % ENC2
ENC2SHBAY7 = '%s, bay 7' % ENC2
ENC3SHBAY1 = '%s, bay 1' % ENC3
ENC3SHBAY5 = '%s, bay 5' % ENC3

enclosures = [
    {"type": "EnclosureV400", "name": ENC1, },
    {"type": "EnclosureV400", "name": ENC2, },
    {"type": "EnclosureV400", "name": ENC3, },
]

sasics = [
    {"name": ENC1SASICBAY1, },
    {"name": ENC1SASICBAY4, },
]

sasic_bay1 = [{"name": ENC1SASICBAY1, }, ]
sasic_bay4 = [{"name": ENC1SASICBAY4, }, ]
sasic1_dict = {"name": ENC1SASICBAY1, }
sasic4_dict = {"name": ENC1SASICBAY4, }

ics = [
    {"name": ENC1ICBAY3, },
    {"name": ENC2ICBAY6, },
]
ljb1_name = 'ljb-sas-1'
ljb2_name = 'ljb-sas-2'

SASLI = 'LE1-SASLIG1-1'

ljbs = [{"name": ljb1_name, "type": SAS_LOGICAL_JBOD_TYPE, "description": "",
         "sasLogicalInterconnectUri": SASLI, "initialScopeUris": [],
         "driveEnclosureUris": [ENC1DEBAY1], "numPhysicalDrives": 1, "minSizeGB": "200",
         "maxSizeGB": "450", "driveTechnology": {"deviceInterface": "SAS", "driveMedia": "HDD"},
         "eraseData": False},
        {"name": ljb2_name, "type": SAS_LOGICAL_JBOD_TYPE, "description": "",
         "sasLogicalInterconnectUri": SASLI, "initialScopeUris": [],
         "driveEnclosureUris": [ENC1DEBAY1], "numPhysicalDrives": 1, "minSizeGB": "100",
         "maxSizeGB": "146", "driveTechnology": {"deviceInterface": "SAS", "driveMedia": "HDD"},
         "eraseData": False}, ]
ljb_name_change = {"name": "ljb-sas-1", "value": "ljb1-sas-name-changed2"}

profiles = [{"type": SERVER_PROFILE_TYPE,
             "serverHardwareUri": "SH:" + ENC1SHBAY3,
             "serverHardwareTypeUri": "SHT:SY 680 Gen9:1:Smart Array P542D Controller:3:HP Synergy 3820C 10/20Gb CNA",
             "enclosureGroupUri": "EG:" + EG_NAME,
             "serialNumberType": "Virtual",
             "iscsiInitiatorNameType": "AutoGenerated",
             "macType": "Virtual",
             "wwnType": "Virtual",
             "name": "OVF4571-sp1",
             "description": "",
             "affinity": "Bay",
             "connectionSettings": {"connections": []},
             "boot": {"manageBoot": True, "order": ["HardDisk"]},
             "bootMode": {"manageMode": True, "mode": "UEFI", "secureBoot": "Disabled", "pxeBootPolicy": "Auto"},
             "firmware": {
                 "manageFirmware": False,
                 "firmwareBaselineUri": "",
                 "forceInstallFirmware": False,
                 "firmwareInstallType": None,
                 "firmwareScheduleDateTime": "",
                 "firmwareActivationType": "Immediate"
             },
             "bios": {
                 "manageBios": False,
                 "overriddenSettings": []
             },
             "managementProcessor": {
                 "manageMp": False,
                 "mpSettings": []
             },
             "hideUnusedFlexNics": True,
             "iscsiInitiatorName": "",
             "osDeploymentSettings": None,
             "localStorage": {
                 "sasLogicalJBODs": [{"id": 1,
                                      "deviceSlot": "Mezz 1",
                                      "name": "ljb-sas-1",
                                      "numPhysicalDrives": 1,
                                      "driveMinSizeGB": 200,
                                      "driveMaxSizeGB": 450,
                                      "driveTechnology": "SasHdd",
                                      "eraseData": False,
                                      "persistent": True,
                                      "sasLogicalJBODUri": "SASLJBOD:ljb-sas-1",
                                      "status": None}],
                 "controllers": []},
             "sanStorage": None,
             "initialScopeUris": []
             },
            {"type": SERVER_PROFILE_TYPE,
             "serverHardwareUri": "SH:" + ENC1SHBAY8,
             "serverHardwareTypeUri": "SHT:SY 480 Gen10:1:HPE Smart Array P416ie-m SR G10:3:Synergy 3820C 10/20Gb CNA",
             "enclosureGroupUri": "EG:" + EG_NAME,
             "serialNumberType": "Virtual",
             "iscsiInitiatorNameType": "AutoGenerated",
             "macType": "Virtual",
             "wwnType": "Virtual",
             "name": "OVF4571-sp2",
             "description": "",
             "affinity": "Bay",
             "connectionSettings": {"connections": []},
             "boot": {"manageBoot": True, "order": ["HardDisk"]},
             "bootMode": {"manageMode": True, "mode": "UEFI", "secureBoot": "Disabled", "pxeBootPolicy": "Auto"},
             "firmware": {
                 "manageFirmware": False,
                 "firmwareBaselineUri": "",
                 "forceInstallFirmware": False,
                 "firmwareInstallType": None,
                 "firmwareScheduleDateTime": "",
                 "firmwareActivationType": "Immediate"
             },
             "bios": {
                 "manageBios": False,
                 "overriddenSettings": []
             },
             "managementProcessor": {
                 "manageMp": False,
                 "mpSettings": []
             },
             "hideUnusedFlexNics": True,
             "iscsiInitiatorName": "",
             "osDeploymentSettings": None,
             "localStorage": {
                 "sasLogicalJBODs": [{"id": 1,
                                      "deviceSlot": "Mezz 1",
                                      "name": "ljb-sas-2",
                                      "numPhysicalDrives": 1,
                                      "driveMinSizeGB": 100,
                                      "driveMaxSizeGB": 146,
                                      "driveTechnology": "SasHdd",
                                      "eraseData": False,
                                      "persistent": True,
                                      "sasLogicalJBODUri": "SASLJBOD:ljb-sas-2",
                                      "status": None}],
                 "controllers": []},
             "sanStorage": None,
             "initialScopeUris": []
             }]
