''' Input variables for the test '''

goldenimage_add = [{'name': 'goldenimage_1',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"},
                   {'name': 'goldenimage_2',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"},
                   {'name': 'goldenimage_3',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"},
                   {'name': 'goldenimage_4',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"},
                   {'name': 'goldenimage_5',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"},
                   {'name': 'goldenimage_6',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"},
                   {'name': 'goldenimage_7',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"},
                   {'name': 'goldenimage_8',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"},
                   {'name': 'goldenimage_9',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"},
                   {'name': 'goldenimage_10',
                    'description': 'valid_goldenimage',
                    'file': "valid_file"}
]
