ADMIN_CREDENTIALS = {'userName': 'Administrator', 'password': 'wpsthpvse1'}
FILES = "/etc/pki/tls/certs/cachains/all-certificates.bks"
FUSION_SSH_USERNAME = "root"
FUSION_SSH_PASSWORD = "hpvse1"
FUSION_PROMPT = "#"
FUSION_TIMEOUT = '20'

USER_NAME = "admin"
USER_PASSWORD = "admin"
USER_PASSWORD_WRONG = "wrong_password"
IPDU_SERVER_CA_SIGN = "16.125.79.15"
IPDU_SERVER_CA_SIGN_PDU = [IPDU_SERVER_CA_SIGN + ", PDU 1"]
IPDU_SERVER_CA_SIGN_2NAME = "test-different"
IPDU_SERVER_FORCE = "16.125.79.15"
POWER_DEVICE_BODY = [{"hostname": IPDU_SERVER_CA_SIGN, "username": USER_NAME, "password": USER_PASSWORD, "force": False}]
POWER_DEVICE_BODY_FORCE = [{"hostname": IPDU_SERVER_FORCE, "username": USER_NAME, "password": USER_PASSWORD, "force": True}]
POWER_DEVICE_BODY_WRONG_PWD = [{"hostname": IPDU_SERVER_CA_SIGN, "username": USER_NAME, "password": USER_PASSWORD_WRONG, "force": False}]
POWER_DEVICE_REFRESH_BODY = [{"refreshState": "RefreshPending"}]

CMD = "keytool -list -v -keystore /etc/pki/tls/certs/cachains/leafcerts.bks -storetype BCFKS -storepass sslkeystorepwd | grep -c -i"
CUSTOM_CMD = "keytool -list -v -keystore /etc/pki/tls/certs/cachains/customroots.bks -storetype BCFKS -storepass sslkeystorepwd | grep -c -i"
CA_CERT_NAME = "iPDU_ca_root"
CERTIFICATEINFOV2 = "CertificateInfoV2"
CERTIFICATEDETAILV2 = "CertificateDetailV2"
CERTIFICATE = {'type': CERTIFICATEINFOV2, 'certificateDetails': [{'base64Data': '', 'type': CERTIFICATEDETAILV2}]}
CERTIFICATE_CHAIN = {"type": CERTIFICATEINFOV2, "certificateDetails": [{"base64Data": "", "type": CERTIFICATEDETAILV2}, {"base64Data": "", "type": CERTIFICATEDETAILV2}]}
#IPDU_ROOT_CERT = '-----BEGIN CERTIFICATE-----\nMIIDIjCCAougAwIBAgIBADANBgkqhkiG9w0BAQUFADBrMQswCQYDVQQGEwJVUzET\nMBEGA1UECBMKQ2FsaWZvcm5pYTESMBAGA1UEBxMJUGFsbyBBbHRvMRgwFgYDVQQK\nEw9IZXdsZXR0LVBhY2thcmQxGTAXBgNVBAMTEEhQIFRlc3RIZWFkIFJvb3QwHhcN\nMTcwOTE5MDY1NzU2WhcNMTgwOTE5MDY1NzU2WjBrMQswCQYDVQQGEwJVUzETMBEG\nA1UECBMKQ2FsaWZvcm5pYTESMBAGA1UEBxMJUGFsbyBBbHRvMRgwFgYDVQQKEw9I\nZXdsZXR0LVBhY2thcmQxGTAXBgNVBAMTEEhQIFRlc3RIZWFkIFJvb3QwgZ8wDQYJ\nKoZIhvcNAQEBBQADgY0AMIGJAoGBAMufWjipulr65RVHXtq/Sff/uupNKKobSjhX\neEOUUitLGW3D8uspLyAFDN9MoXMiujVDiOuIreGZayMV9ppfnnW63SzSmjjCgsCB\nM1eHWxysMWf+jR6HlW+DaMRYeziUl7nhP9lqqQWUbTwdOZSQ56gZTLu8bnfD2Uuf\nvPBLGgitAgMBAAGjgdUwgdIwHQYDVR0OBBYEFF5io+7MJCA6DSWKw5V1wZG0+8ze\nMIGVBgNVHSMEgY0wgYqAFF5io+7MJCA6DSWKw5V1wZG0+8zeoW+kbTBrMQswCQYD\nVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTESMBAGA1UEBxMJUGFsbyBBbHRv\nMRgwFgYDVQQKEw9IZXdsZXR0LVBhY2thcmQxGTAXBgNVBAMTEEhQIFRlc3RIZWFk\nIFJvb3SCAQAwCwYDVR0PBAQDAgG2MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEF\nBQADgYEAy2j5WS53jfN0Aim4dTPYXa1+khihTxceymPrDXvxy5ppNfYpKenLVFtb\ndycVse2lqBT1WYEj3r1MRrNW3Lfnpr+Swh1A1NlryaPQ1ZTgKo/WalCxbFURQdPN\nd89BLKdrsWIt3tmyvpY3LgtumICQaRLb05hFhQL0juAruV5lVa4=\n-----END CERTIFICATE-----\n'
IPDU_ROOT_CERT = '-----BEGIN CERTIFICATE-----\nMIIDDTCCAnagAwIBAgIBADANBgkqhkiG9w0BAQUFADBkMQswCQYDVQQGEwJVUzET\nMBEGA1UECBMKQ2FsaWZvcm5pYTESMBAGA1UEBxMJUGFsbyBBbHRvMRgwFgYDVQQK\nEw9IZXdsZXR0LVBhY2thcmQxEjAQBgNVBAMTCUp1ZHkgUm9vdDAeFw0xNzEyMDQw\nNjA3MzVaFw0xODEyMDQwNjA3MzVaMGQxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpD\nYWxpZm9ybmlhMRIwEAYDVQQHEwlQYWxvIEFsdG8xGDAWBgNVBAoTD0hld2xldHQt\nUGFja2FyZDESMBAGA1UEAxMJSnVkeSBSb290MIGfMA0GCSqGSIb3DQEBAQUAA4GN\nADCBiQKBgQCtRsC3EVGfTEybLonIAlNA9uaF/6OP2tgg1MU5vr3VikEcH0mR/sF2\nSLw1ftZZPhJEyloDeqPqNGt+Z9XsT4b6nO2GbxiNzLY3dhBkLlyDobQZLvV5W/5G\niLkNQT73dK94YFaAYwSKGcFZ0VYgCOtKq8y/xy6289IXjNAYxnweywIDAQABo4HO\nMIHLMB0GA1UdDgQWBBSMB28DG73BcYb82Hu8xMS7nn16rDCBjgYDVR0jBIGGMIGD\ngBSMB28DG73BcYb82Hu8xMS7nn16rKFopGYwZDELMAkGA1UEBhMCVVMxEzARBgNV\nBAgTCkNhbGlmb3JuaWExEjAQBgNVBAcTCVBhbG8gQWx0bzEYMBYGA1UEChMPSGV3\nbGV0dC1QYWNrYXJkMRIwEAYDVQQDEwlKdWR5IFJvb3SCAQAwCwYDVR0PBAQDAgG2\nMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEACDYgkbyCkhIyBDYQhgiN\nGuq+OCx9jCrTlaHMKPftbc1Juc2+B6w8rjN+Hgpf3XeUddTIensRjw1ZUYVYXiTJ\nfJ3Vl3pBEwGnUWJ6KcSBFNTAEIxrDMpG/vUrlHEF7VJxF6nRd1A6R62ckDhmTpQa\n98Rf/cUPdk+JYFVG+lDHcW8=\n-----END CERTIFICATE-----\n'
CA_CERTIFICATE = {"members": [{"type": "CertificateAuthorityInfo", "certificateDetails": {"base64Data": "-----BEGIN CERTIFICATE-----\nMIIDFjCCAn+gAwIBAgIJAIIzRKjsgavGMA0GCSqGSIb3DQEBBQUAMGYxCzAJBgNV\nBAYTAlVTMQ4wDAYDVQQIEwVUZXhhczEQMA4GA1UEBxMHSG91c3RvbjEgMB4GA1UE\nChMXSGV3bGV0dC1QYWNrYXJkIENvbXBhbnkxEzARBgNVBAMTCnd3dy5ocC5jb20w\nHhcNMTIxMDI1MTkyOTM1WhcNMjIxMDI0MTkyOTM1WjBmMQswCQYDVQQGEwJVUzEO\nMAwGA1UECBMFVGV4YXMxEDAOBgNVBAcTB0hvdXN0b24xIDAeBgNVBAoTF0hld2xl\ndHQtUGFja2FyZCBDb21wYW55MRMwEQYDVQQDEwp3d3cuaHAuY29tMIGfMA0GCSqG\nSIb3DQEBAQUAA4GNADCBiQKBgQDb5urKuEfMdz4mHtfzX1xo6f+ZNNuXxkhe9fHz\nGFHFvBKOEoooGBQcfPOPxrKJjnxJP15tr8/mtXwdakV0iTB2obtq0xfhHL113/VE\nBJ0DPcjVN+h1MGu86krB5rVLV0tBAHTvV4OtXA3ZQfQ1OTN9j5/ybQZXsVC0bes4\nMR8uDQIDAQABo4HLMIHIMB0GA1UdDgQWBBRI8TUI2+/9ql/8d3tqpcJ7juG/7TCB\nmAYDVR0jBIGQMIGNgBRI8TUI2+/9ql/8d3tqpcJ7juG/7aFqpGgwZjELMAkGA1UE\nBhMCVVMxDjAMBgNVBAgTBVRleGFzMRAwDgYDVQQHEwdIb3VzdG9uMSAwHgYDVQQK\nExdIZXdsZXR0LVBhY2thcmQgQ29tcGFueTETMBEGA1UEAxMKd3d3LmhwLmNvbYIJ\nAIIzRKjsgavGMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAt1ZB2MKL\nXnrPdykEXxYpdLyCHIku45qSsiX3cJIapMM9oNpb2wbhf2ueza2+Wp1j3lPxSRV2\nvx5gmDyBOYawckN7a3L1uNwSNK27JTPBu7Fr9AKlrC8CnM61urSMdfdSDifUXYRz\n2d0UrX+evDfrWBZiBB9BB6PFYeFJ/5QGR5s=\n-----END CERTIFICATE-----", "aliasName": "16.125.33.196", "type": "CertificateDetailV2"}}], "type": "CertificateAuthorityInfoCollection"}
