# DTO Versioning
SERVER_PROFILE_TEMPLATE_DTO_TYPE = "ServerProfileTemplateV7"
SERVER_PROFILE_DTO_TYPE = "ServerProfileV11"

# Credentials
appliance_credentials = {
    'userName': 'Administrator',
    'password': 'hpvse123'
}

# SAN names
FC_SAN_1_NAME = "VSAN20"
FC_SAN_2_NAME = "VSAN30"

# OneView network names corresponding to SANs declared above
FC_SAN_1_NETWORK = "VSAN20Network"
FC_SAN_2_NETWORK = "VSAN30Network"

# RG lookups for SAN networks
FC_SAN_1_URI = "FC:" + FC_SAN_1_NETWORK
FC_SAN_2_URI = "FC:" + FC_SAN_2_NETWORK

# physical WWPNs for the DL FC adapter cards.  Note that these do not have to be accurate at this time since OVF520
# does not do any adapter programming.  They just have to be correctly formatted and unique.  This will change after
# the followup feature to OVF520 adds adapter programming
DL1_WWPN = {"port1": "51:40:2e:c0:01:7c:bf:bc", "port2": "51:40:2e:c0:01:7c:bf:bd"}
DL2_WWPN = {"port1": "51:40:2e:c0:01:7c:bf:be", "port2": "51:40:2e:c0:01:7c:bf:bf"}

# a list of incorrectly formatted WWPNs for negative testing
BAD_WWPNS = ["51:40:2e:c0:zz:7c:bf:bc", "51:40:2e:c0:01:7c:bf:bc:bc", "51:40:2e:c0:01:7c:bf", "1981yyzed0017fbc",
             "51;40:2e:c0:01:7c:bf:bc"]

# DL #1 OneView name and Server Hardware Type name
DL1_NAME = "dl380gen10fc2-ilo.ftc.rdlabs.hpecorp.net"
DL1_SHT_NAME = "DL380 Gen10 1"

# DL #2 OneView name and Server Hardware Type name.  Note that SHT has to be different than DL #1 for transformation API
# testing
DL2_NAME = "172.18.31.3"
DL2_SHT_NAME = "DL360 Gen10 1"

DL1_SH = "SH:" + DL1_NAME
DL1_SHT = "SHT:" + DL1_SHT_NAME
DL2_SH = "SH:" + DL2_NAME
DL2_SHT = "SHT:" + DL2_SHT_NAME

# C7000 server information.  Used for transformation API testing
C7000_EG_NAME = "EG"
C7000_SERVER_NAME = "tb2, bay 10"
C7000_SHT_NAME = "BL460c Gen10 1"

server_hardware_uris = [
    {
        'serverHardwareUri': DL1_SH,
    },
    {
        'serverHardwareUri': DL2_SH,
    }
]

# StoreServ configuration
storage_system_connection_WWPNs = [[], []]
STORESERV_NAME = 'tb3par1'
STORESERV_POOL = 'FC_r1'
STORESERV_VOLUME_PREFIX = 'OVF520_vol'
STORESERV_VOLUME_NAME_DL1 = STORESERV_VOLUME_PREFIX + '1 (DL1)'
STORESERV_VOLUME_NAME_DL2 = STORESERV_VOLUME_PREFIX + '1 (DL2)'

# DL #1 connection information for 1 and 2 connection Server Profiles Templates and Server Profiles
DL1_1_CONNECTION_SP_NAME = "OVF520 DL1 1 connection SP"
DL1_1_CONNECTION_SPT_NAME = "OVF520 DL1 1 connection SPT"
DL1_1_CONNECTION_SPT_URI = "SPT:" + DL1_1_CONNECTION_SPT_NAME
DL1_2_CONNECTION_SP_NAME = "OVF520 DL1 2 connection SP"
DL1_2_CONNECTION_SPT_NAME = "OVF520 DL1 2 connection SPT"
DL1_2_CONNECTION_SPT_URI = "SPT:" + DL1_2_CONNECTION_SPT_NAME

# DL #2 connection information for 1 and 2 connection Server Profiles Templates and Server Profiles
DL2_1_CONNECTION_SP_NAME = "OVF520 DL2 1 connection SP"
DL2_1_CONNECTION_SPT_NAME = "OVF520 DL2 1 connection SPT"
DL2_1_CONNECTION_SPT_URI = "SPT:" + DL2_1_CONNECTION_SPT_NAME
DL2_2_CONNECTION_SP_NAME = "OVF520 DL2 2 connection SP"
DL2_2_CONNECTION_SPT_NAME = "OVF520 DL2 2 connection SPT"
DL2_2_CONNECTION_SPT_URI = "SPT:" + DL2_2_CONNECTION_SPT_NAME

# 1 connection DTOs
####################

dl1_1_connection_spt = {
    "type": SERVER_PROFILE_TEMPLATE_DTO_TYPE,
    "name": DL1_1_CONNECTION_SPT_NAME,
    "description": "DL 1 connection",
    "serverProfileDescription": "DL 1 connection from SPT",
    "serverHardwareTypeUri": DL1_SHT,
    "affinity": None,
    "hideUnusedFlexNics": None,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Physical",
    "iscsiInitiatorNameType": "AutoGenerated",
    "osDeploymentSettings": None,
    "firmware": {
        "manageFirmware": False,
    },
    "connectionSettings": {
        "complianceControl": "CheckedMinimum",
        "manageConnections": True,
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "managed": False,
            }
        ]
    },
    "bootMode": {
        "manageMode": False,
    },
    "boot": {
        "manageBoot": False,
    },
    "bios": {
        "manageBios": False,
    },
    "managementProcessor": {
        "manageMp": False,
    },
    "sanStorage": {
        "manageSanStorage": True,
        "hostOSType": "Windows 2012 / WS2012 R2",
        "sanSystemCredentials": [],
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                    }
                ],
                "volumeUri": None,
                "volume": {
                    "templateUri": "ROOT:" + STORESERV_POOL,
                    "properties": {
                        "isDeduplicated": False,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "name": STORESERV_VOLUME_NAME_DL1,
                        "description": "",
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False
                    },
                    "isPermanent": False
                },
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "bootVolumePriority": "NotBootable"
            }
        ]
    },
}

dl1_1_connection_edit_unassign_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_1_CONNECTION_SP_NAME,
    "serverHardwareTypeUri": DL1_SHT,
    "serverHardwareUri": None,
    "description": "This is an edited unassigned profile",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            }
        ]
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + STORESERV_VOLUME_NAME_DL1,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl2_1_connection_edit_unassign_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL2_1_CONNECTION_SP_NAME,
    "serverHardwareTypeUri": DL2_SHT,
    "serverHardwareUri": None,
    "description": "This is an edited unassigned profile",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL2_WWPN["port1"],
            }
        ]
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + STORESERV_VOLUME_NAME_DL2,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl1_1_connection_edit_assign_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_1_CONNECTION_SP_NAME,
    "serverHardwareTypeUri": DL1_SHT,
    "serverHardwareUri": DL1_SH,
    "description": "This is an edited assigned profile",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            }
        ]
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + STORESERV_VOLUME_NAME_DL1,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl2_1_connection_edit_assign_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL2_1_CONNECTION_SP_NAME,
    "serverHardwareTypeUri": DL2_SHT,
    "serverHardwareUri": DL2_SH,
    "description": "This is an edited assigned profile",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL2_WWPN["port1"],
            }
        ]
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + STORESERV_VOLUME_NAME_DL2,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl1_1_connection_unassigned_sp_from_spt = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_1_CONNECTION_SP_NAME,
    "serverProfileTemplateUri": "SPT:" + DL1_1_CONNECTION_SPT_NAME,
    "serverHardwareUri": None,
}

dl1_1_connection_unassigned_sp_from_spt_with_wwpn = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_1_CONNECTION_SP_NAME,
    "serverProfileTemplateUri": "SPT:" + DL1_1_CONNECTION_SPT_NAME,
    "serverHardwareUri": None,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                # "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                # "macType": "Physical",
                # "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            }
        ]
    },
}

dl1_1_connection_unassigned_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_1_CONNECTION_SP_NAME,
    "description": "This is an unassigned profile",
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": None,
    "serverHardwareTypeUri": DL1_SHT,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Physical",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            }
        ]
    },
    "bootMode": {
        "manageMode": False,
    },
    "boot": {
        "manageBoot": False,
    },
    "bios": {
        "manageBios": False,
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "NotBootable",
                "associatedTemplateAttachmentId": None,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME_DL1,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl1_1_connection_assigned_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_1_CONNECTION_SP_NAME,
    "description": "This is an assigned profile",
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": DL1_SH,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Physical",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            }
        ]
    },
    "bootMode": {
        "manageMode": False,
    },
    "boot": {
        "manageBoot": False,
    },
    "bios": {
        "manageBios": False,
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "NotBootable",
                "associatedTemplateAttachmentId": None,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME_DL1,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl2_1_connection_assigned_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL2_1_CONNECTION_SP_NAME,
    "description": "This is an assigned profile",
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": DL2_SH,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Physical",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL2_WWPN["port1"],
            }
        ]
    },
    "bootMode": {
        "manageMode": False,
    },
    "boot": {
        "manageBoot": False,
    },
    "bios": {
        "manageBios": False,
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "NotBootable",
                "associatedTemplateAttachmentId": None,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME_DL2,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
            }
        ],
        "sanSystemCredentials": [],
    },
}

# 2 connection DTOs
####################

dl1_2_connection_spt = {
    "type": SERVER_PROFILE_TEMPLATE_DTO_TYPE,
    "name": DL1_2_CONNECTION_SPT_NAME,
    "description": "DL 2 connection",
    "serverProfileDescription": "DL 2 connection from SPT",
    "serverHardwareTypeUri": DL1_SHT,
    "affinity": None,
    "hideUnusedFlexNics": None,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Physical",
    "iscsiInitiatorNameType": "AutoGenerated",
    "osDeploymentSettings": None,
    "firmware": {
        "manageFirmware": False,
    },
    "connectionSettings": {
        "complianceControl": "CheckedMinimum",
        "manageConnections": True,
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "managed": False,
            },
            {
                "id": 2,
                "name": "FCConn30",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_2_URI,
                "managed": False,
            }
        ]
    },
    "bootMode": {
        "manageMode": False,
    },
    "boot": {
        "manageBoot": False,
    },
    "bios": {
        "manageBios": False,
    },
    "managementProcessor": {
        "manageMp": False,
    },
    "sanStorage": {
        "manageSanStorage": True,
        "hostOSType": "Windows 2012 / WS2012 R2",
        "sanSystemCredentials": [],
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                    },
                    {
                        "connectionId": 2,
                        "isEnabled": True,
                        "targetSelector": "Auto",
                    }
                ],
                "volumeUri": None,
                "volume": {
                    "templateUri": "ROOT:" + STORESERV_POOL,
                    "properties": {
                        "isDeduplicated": False,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "name": STORESERV_VOLUME_NAME_DL1,
                        "description": "",
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False
                    },
                    "isPermanent": False
                },
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "bootVolumePriority": "NotBootable"
            }
        ]
    },
}

dl1_2_connection_edit_unassign_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_2_CONNECTION_SP_NAME,
    "serverHardwareTypeUri": DL1_SHT,
    "serverHardwareUri": None,
    "description": "This is an edited unassigned profile",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            },
            {
                "id": 2,
                "name": "FCConn30",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_2_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port2"],
            }
        ]
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + STORESERV_VOLUME_NAME_DL1,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl2_2_connection_edit_unassign_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL2_2_CONNECTION_SP_NAME,
    "serverHardwareTypeUri": DL2_SHT,
    "serverHardwareUri": None,
    "description": "This is an edited unassigned profile",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL2_WWPN["port1"],
            },
            {
                "id": 2,
                "name": "FCConn30",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_2_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL2_WWPN["port2"],
            }
        ]
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + STORESERV_VOLUME_NAME_DL2,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl1_2_connection_edit_assign_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_2_CONNECTION_SP_NAME,
    "serverHardwareTypeUri": DL1_SHT,
    "serverHardwareUri": DL1_SH,
    "description": "This is an edited assigned profile",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            },
            {
                "id": 2,
                "name": "FCConn30",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_2_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port2"],
            }
        ]
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + STORESERV_VOLUME_NAME_DL1,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl2_2_connection_edit_assign_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL2_2_CONNECTION_SP_NAME,
    "serverHardwareTypeUri": DL2_SHT,
    "serverHardwareUri": DL2_SH,
    "description": "This is an edited assigned profile",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL2_WWPN["port1"],
            },
            {
                "id": 2,
                "name": "FCConn30",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_2_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL2_WWPN["port2"],
            }
        ]
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": "SVOL:" + STORESERV_VOLUME_NAME_DL2,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl1_2_connection_unassigned_sp_from_spt = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_2_CONNECTION_SP_NAME,
    "serverProfileTemplateUri": "SPT:" + DL1_2_CONNECTION_SPT_NAME,
    "serverHardwareUri": None,
}

dl1_2_connection_unassigned_sp_from_spt_with_wwpn = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_2_CONNECTION_SP_NAME,
    "serverProfileTemplateUri": "SPT:" + DL1_2_CONNECTION_SPT_NAME,
    "serverHardwareUri": None,
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                # "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                # "macType": "Physical",
                # "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            },
            {
                "id": 2,
                # "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_2_URI,
                # "macType": "Physical",
                # "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port2"],
            }
        ]
    },
}

dl1_2_connection_unassigned_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_2_CONNECTION_SP_NAME,
    "description": "This is an unassigned profile",
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": None,
    "serverHardwareTypeUri": DL1_SHT,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Physical",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            },
            {
                "id": 2,
                "name": "FCConn30",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_2_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port2"],
            }
        ]
    },
    "bootMode": {
        "manageMode": False,
    },
    "boot": {
        "manageBoot": False,
    },
    "bios": {
        "manageBios": False,
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "NotBootable",
                "associatedTemplateAttachmentId": None,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME_DL1,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl1_2_connection_assigned_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL1_2_CONNECTION_SP_NAME,
    "description": "This is an assigned profile",
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": DL1_SH,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Physical",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port1"],
            },
            {
                "id": 2,
                "name": "FCConn30",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_2_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL1_WWPN["port2"],
            }
        ]
    },
    "bootMode": {
        "manageMode": False,
    },
    "boot": {
        "manageBoot": False,
    },
    "bios": {
        "manageBios": False,
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "NotBootable",
                "associatedTemplateAttachmentId": None,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME_DL1,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
            }
        ],
        "sanSystemCredentials": [],
    },
}

dl2_2_connection_assigned_sp = {
    "type": SERVER_PROFILE_DTO_TYPE,
    "name": DL2_2_CONNECTION_SP_NAME,
    "description": "This is an assigned profile",
    "iscsiInitiatorNameType": "AutoGenerated",
    "serverHardwareUri": DL2_SH,
    "macType": "Physical",
    "wwnType": "Physical",
    "serialNumberType": "Physical",
    "category": "server-profiles",
    "connectionSettings": {
        "connections": [
            {
                "id": 1,
                "name": "FCConn20",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_1_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL2_WWPN["port1"],
            },
            {
                "id": 2,
                "name": "FCConn30",
                "functionType": "FibreChannel",
                "networkUri": FC_SAN_2_URI,
                "macType": "Physical",
                "wwpnType": "Physical",
                "wwpn": DL2_WWPN["port2"],
            }

        ]
    },
    "bootMode": {
        "manageMode": False,
    },
    "boot": {
        "manageBoot": False,
    },
    "bios": {
        "manageBios": False,
    },
    "sanStorage": {
        "hostOSType": "Windows 2012 / WS2012 R2",
        "manageSanStorage": True,
        "volumeAttachments": [
            {
                "id": 1,
                "lunType": "Auto",
                "volumeUri": None,
                "volumeStorageSystemUri": "SSYS:" + STORESERV_NAME,
                "storagePaths": [
                    {
                        "connectionId": 1,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    },
                    {
                        "connectionId": 2,
                        "targetSelector": "Auto",
                        "isEnabled": True
                    }
                ],
                "bootVolumePriority": "NotBootable",
                "associatedTemplateAttachmentId": None,
                "volume": {
                    "properties": {
                        "name": STORESERV_VOLUME_NAME_DL2,
                        "storagePool": "SPOOL:" + STORESERV_POOL,
                        "provisioningType": "Thin",
                        "size": 2147483648,
                        "isShareable": False,
                    },
                    "isPermanent": False,
                    "templateUri": "ROOT:" + STORESERV_POOL,
                },
            }
        ],
        "sanSystemCredentials": [],
    },
}
