admin_credentials = {'userName': 'Administrator', 'password': 'wpsthpvse1'}

ENC1 = "CN754406XL"
BAY = ", bay 1"
SASICBAY = ", interconnect 1"

LE_NAME = "LE1"
SAS_LI_NAME = "LE1-SASLIG1-1"
SAS_LIG_NAME = "SASLIG1"
EG_NAME = "EG1"

DE = {
    'name': ENC1 + BAY,
    'type': 'DriveEnclosureV2',
    'state': 'Maintenance'
}

SASIC = {
    'name': ENC1 + SASICBAY,
    'type': 'SasInterconnectV3',
    'state': 'Maintenance'
}

SASLI = {
    'name': SAS_LI_NAME
}

DE_LIST = [DE]
SASIC_LIST = [SASIC]

JBOD1 = ENC1 + ', bay 7-jbod1'
JBOD2 = ENC1 + ', bay 7-jbod2'

SERVER_PROFILE = {'type': 'ServerProfileV10',
                  'serverHardwareUri': 'SH:' + ENC1 + ', bay 7',
                  'enclosureUri': 'ENC:' + ENC1,
                  'enclosureGroupUri': 'EG:' + EG_NAME,
                  'serialNumberType': 'Virtual',
                  'macType': 'Virtual',
                  'wwnType': 'Virtual',
                  'name': ENC1 + ', bay 7',
                  'description': ENC1 + ', bay 7-withbothHBA',
                  'affinity': 'Bay',
                  'connectionSettings': {
                      'connections': [{
                          'id': 1,
                          'name': '',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-a',
                          'requestedMbps': '2500',
                          'networkUri': 'ETH:net100',
                          'requestedVFs': 'Auto'
                      }
                      ]
                  },
                  'boot': {'manageBoot': False, 'order': []},
                  'bootMode': {'manageMode': False},
                  'firmware': {'manageFirmware': False,
                               'firmwareBaselineUri': None,
                               'forceInstallFirmware': False,
                               'firmwareInstallType': None
                               },
                  'bios': {'manageBios': False,
                           'overriddenSettings': []
                           },
                  'hideUnusedFlexNics': True,
                  'iscsiInitiatorNameType': 'AutoGenerated',
                  'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                        'deviceSlot': 'Mezz 1',
                                                        'name': JBOD1,
                                                        'numPhysicalDrives': 3,
                                                        'driveMinSizeGB': 50,
                                                        'driveMaxSizeGB': 500,
                                                        'driveTechnology': 'SasHdd'}],
                                   'controllers': [{'logicalDrives': None,
                                                    'deviceSlot': 'Mezz 1',
                                                    'mode': 'HBA',
                                                    'initialize': False},
                                                   {'logicalDrives': None,
                                                    'deviceSlot': 'Embedded',
                                                    'mode': 'HBA',
                                                    'initialize': True}]
                                   },
                  'sanStorage': {'volumeAttachments': [], 'manageSanStorage': False}
                  }

EDIT_PROFILE_ADD_JBOD = {'type': 'ServerProfileV10',
                         'serverHardwareUri': 'SH:' + ENC1 + ', bay 7',
                         'serverHardwareTypeUri': 'SHT:SY 480 Gen9:1:Smart Array P542D Controller:3:HP Synergy 3820C 10/20Gb CNA',
                         'enclosureUri': 'ENC:' + ENC1,
                         'enclosureGroupUri': 'EG:' + EG_NAME,
                         'serialNumberType': 'Virtual',
                         'macType': 'Virtual',
                         'wwnType': 'Virtual',
                         'name': ENC1 + ', bay 7',
                         'description': '',
                         'affinity': 'Bay',
                         'connectionSettings': {
                             'connections': [{
                                 'id': 1,
                                 'name': '',
                                 'functionType': 'Ethernet',
                                 'portId': 'Auto',
                                 'requestedMbps': '2500',
                                 'networkUri': 'ETH:net100',
                                 'requestedVFs': 'Auto'
                             }
                             ]
                         },
                         'boot': None,
                         'bootMode': {'manageMode': False},
                         'firmware': {'manageFirmware': False,
                                      'firmwareBaselineUri': '',
                                      'forceInstallFirmware': False,
                                      'firmwareInstallType': None
                                      },
                         'bios': {'manageBios': False,
                                  'overriddenSettings': []
                                  },
                         'hideUnusedFlexNics': True,
                         'iscsiInitiatorNameType': 'AutoGenerated',
                         'localStorage': {'sasLogicalJBODs': [{'id': 1,
                                                               'deviceSlot': 'Mezz 1',
                                                               'name': JBOD1,
                                                               'sasLogicalJBODUri': 'SASLJBOD:' + JBOD1,
                                                               'numPhysicalDrives': 3,
                                                               'driveMinSizeGB': 50,
                                                               'driveMaxSizeGB': 500,
                                                               'driveTechnology': 'SasHdd'},
                                                              {'id': 2,
                                                               'deviceSlot': 'Mezz 1',
                                                               'name': JBOD2,
                                                               'numPhysicalDrives': 3,
                                                               'driveMinSizeGB': 30,
                                                               'driveMaxSizeGB': 300,
                                                               'driveTechnology': 'SasHdd'}],
                                          'controllers': [{'logicalDrives': None,
                                                           'deviceSlot': 'Embedded',
                                                           'mode': 'HBA',
                                                           'initialize': True},
                                                          {'logicalDrives': None,
                                                           'deviceSlot': 'Mezz 1',
                                                           'mode': 'HBA',
                                                           'initialize': False}]
                                          },
                         'sanStorage': None
                         }

EDIT_PROFILE_DEL_JBOD = {'type': 'ServerProfileV10',
                         'serverHardwareUri': 'SH:' + ENC1 + ', bay 7',
                         'serverHardwareTypeUri': 'SHT:SY 480 Gen9:1:Smart Array P542D Controller:3:HP Synergy 3820C 10/20Gb CNA',
                         'enclosureUri': 'ENC:' + ENC1,
                         'enclosureGroupUri': 'EG:' + EG_NAME,
                         'serialNumberType': 'Virtual',
                         'macType': 'Virtual',
                         'wwnType': 'Virtual',
                         'name': ENC1 + ', bay 7',
                         'description': '',
                         'affinity': 'Bay',
                         'connectionSettings': {
                             'connections': [{
                                 'id': 1,
                                 'name': '',
                                 'functionType': 'Ethernet',
                                 'portId': 'Auto',
                                 'requestedMbps': '2500',
                                 'networkUri': 'ETH:net100',
                                 'requestedVFs': 'Auto'
                             }
                             ]
                         },
                         'boot': None,
                         'bootMode': {'manageMode': False},
                         'firmware': {'manageFirmware': False,
                                      'firmwareBaselineUri': '',
                                      'forceInstallFirmware': False,
                                      'firmwareInstallType': None
                                      },
                         'bios': {'manageBios': False,
                                  'overriddenSettings': []
                                  },
                         'hideUnusedFlexNics': True,
                         'iscsiInitiatorNameType': 'AutoGenerated',
                         'localStorage': {'sasLogicalJBODs': [], 'controllers': []},
                         'sanStorage': {'manageSanStorage': False, 'volumeAttachments': []}
                         }

SASLIG = [{'name': SAS_LIG_NAME,  # Dual SAS switch
           "type": "sas-logical-interconnect-groupV2",
           "enclosureType": "SY12000",
           "enclosureIndexes": [1],
           "interconnectBaySet": "1",
           'interconnectMapTemplate': [
               {'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'Synergy 12Gb SAS Connection Module'},
               {'enclosure': 1, 'enclosureIndex': 1, 'bay': 4, 'type': 'Synergy 12Gb SAS Connection Module'}]}
          ]

EDIT_SASLIG = [{'name': SAS_LIG_NAME,  # Single SAS switch
                "type": "sas-logical-interconnect-groupV2",
                "enclosureType": "SY12000",
                "enclosureIndexes": [1],
                "interconnectBaySet": "1",
                'interconnectMapTemplate': [
                    {'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'Synergy 12Gb SAS Connection Module'}]}
               ]
