# Credentials
admin_credentials = {'userName': 'Administrator', 'password': 'wpsthpvse1'}
oa_credentials = {'username': 'Administrator', 'password': 'hpvse14'}
ilo_credentials = {'username': 'Administrator', 'password': 'hpvse123'}
cliq_credentials = {
    'mgmt_ip': '16.71.149.173',
    'username': 'admin',
    'password': 'admin'}
ssh_credentials = {'username': 'root', 'password': 'hpvse1'}

# Resource types for X-API-Version=1000
SERVER_PROFILE_TYPE = 'ServerProfileV10'

# Enclosures, Interconnects, Server Hardware, LIG, EG, and LE
# Enclosures
ENC1 = 'CN75120D7B'
ENC2 = 'CN75120D77'
ENC3 = 'CN750163KD'
# Potash and Chloride
ENC1ICBAY3 = '%s, interconnect 3' % ENC1  # Potash
ENC1ICBAY6 = '%s, interconnect 6' % ENC1
ENC2ICBAY3 = '%s, interconnect 3' % ENC2  # Potash
ENC2ICBAY6 = '%s, interconnect 6' % ENC2
ENC3ICBAY3 = '%s, interconnect 3' % ENC3
ENC3ICBAY6 = '%s, interconnect 6' % ENC3
# Natasha SAS interconnects
ENC1SASICBAY1 = '%s, interconnect 1' % ENC1
ENC1SASICBAY4 = '%s, interconnect 4' % ENC1
# Drive Enclosures (Bigbird)
ENC1DEBAY1 = '%s, bay 1' % ENC1
# Server Hardware
ENC1SHBAY3 = '%s, bay 3' % ENC1    # SY680 Gen9
ENC1SHBAY5 = '%s, bay 5' % ENC1    # SY660 Gen9
ENC1SHBAY6 = '%s, bay 6' % ENC1    # SY480 Gen10
ENC1SHBAY7 = '%s, bay 7' % ENC1    # SY480 Gen9
ENC1SHBAY8 = '%s, bay 8' % ENC1    # SY480 Gen10
ENC2SHBAY1 = '%s, bay 1' % ENC2    # SY480 Gen9
ENC2SHBAY5 = '%s, bay 5' % ENC2    # SY660 Gen9
ENC2SHBAY7 = '%s, bay 7' % ENC2    # SY480 Gen10
ENC2SHBAY8 = '%s, bay 8' % ENC2    # SY480 Gen10
ENC3SHBAY1 = '%s, bay 1' % ENC3    # SY480 Gen9
ENC3SHBAY5 = '%s, bay 5' % ENC3    # SY680 Gen9
# LIG, EG and LE
LIG_NAME = 'LIG1'
SASLIG_NAME = 'SASLIG1'
EG_NAME = 'EG1'
LE_NAME = 'LE1'

# Name prefixes
NAME_PREFIX = 'Synergy-Ring2-OVF2101-'
PROFILE_NAME_PREFIX = NAME_PREFIX
# SH
SERVER = ENC1SHBAY8
GEN9_SERVER = ENC1SHBAY7
# Profile
PROFILE_NAME = PROFILE_NAME_PREFIX + 'pts2-profile'
PROFILE_SERVER = SERVER
PROFILE_EG = EG_NAME
PTS2_PROFILE_NAME = PROFILE_NAME_PREFIX + 'pts2-profile'
PTS2_PROFILE_SERVER = SERVER
PTS2_PROFILE_EG = EG_NAME

suite_setup_profile = {
    "type": SERVER_PROFILE_TYPE, "name": PROFILE_NAME,
    "serverHardwareUri": 'SH:' + PROFILE_SERVER, "enclosureGroupUri": 'EG:' + PROFILE_EG,
    "iscsiInitiatorNameType": "AutoGenerated", "serialNumberType": "Virtual", "macType": "Virtual", "wwnType": "Virtual", "affinity": "Bay",
    "connectionSettings": {"connections": []},
    "boot": {"manageBoot": False, "order": []},
    "bootMode": {"manageMode": False, "mode": None, "secureBoot": "Unmanaged", "pxeBootPolicy": None},
    "firmware": {"manageFirmware": False, },
    "bios": {"manageBios": False, "overriddenSettings": []},
    "sanStorage": {'manageSanStorage': False, 'volumeAttachments': []},
    "hideUnusedFlexNics": True, "osDeploymentSettings": None,
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [
            {
                "deviceSlot": "Embedded",
                "mode": "Mixed",
                "initialize": True,
                "importConfiguration": False,
                "driveWriteCache": None,
                "logicalDrives": []
            }
        ]
    },

}

pts2_profile_create = {
    "type": SERVER_PROFILE_TYPE, "name": PTS2_PROFILE_NAME,
    "serverHardwareUri": 'SH:' + PTS2_PROFILE_SERVER, "enclosureGroupUri": 'EG:' + PTS2_PROFILE_EG,
    "iscsiInitiatorNameType": "AutoGenerated", "serialNumberType": "Virtual", "macType": "Virtual", "wwnType": "Virtual", "affinity": "Bay",
    "connectionSettings": {"connections": []},
    "boot": {"manageBoot": False, "order": []},
    "bootMode": {"manageMode": False, "mode": None, "secureBoot": "Unmanaged", "pxeBootPolicy": None},
    "firmware": {"manageFirmware": False, },
    "bios": {"manageBios": False, "overriddenSettings": []},
    "sanStorage": {'manageSanStorage': False, 'volumeAttachments': []},
    "hideUnusedFlexNics": True, "osDeploymentSettings": None,
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [
            {
                "deviceSlot": "Embedded",
                "mode": "Mixed",
                "initialize": True,
                "importConfiguration": False,
                "driveWriteCache": "Enabled",
                "logicalDrives": [
                    {
                        "name": "LD1",
                        "raidLevel": "RAID0",
                        "bootable": False,
                        "numPhysicalDrives": 1,
                        "driveTechnology": "SasHdd",
                        "sasLogicalJBODId": None,
                        "accelerator": "ControllerCache",
                    },
                    {
                        "name": "LD2",
                        "raidLevel": "RAID0",
                        "bootable": False,
                        "numPhysicalDrives": 1,
                        "driveTechnology": "SasHdd",
                        "sasLogicalJBODId": None,
                        "accelerator": "ControllerCache",
                    }
                ]
            }
        ]
    }
}

suite_setup_profiles = [suite_setup_profile.copy()]

pts2_profiles_create = [pts2_profile_create.copy()]
