def make_range_list(start, end, prefix='net_', suffix=''):
    rlist = []
    for x in xrange(start, end + 1):
        rlist.append(prefix + str(x) + suffix)
    return rlist


admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}

vcenter = {'server': '15.199.230.130', 'user': 'rbriggs', 'password': 'hpvse1'}

users = [
    {'userName': 'Serveradmin', 'password': 'Serveradmin', 'fullName': 'Serveradmin',
     'permissions': [{'roleName': 'Server administrator'}],
     'emailAddress': 'sarah@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
     'type': 'UserAndPermissions'},
    {'userName': 'Networkadmin', 'password': 'Networkadmin', 'fullName': 'Networkadmin',
     'permissions': [{'roleName': 'Network administrator'}], 'emailAddress': 'nat@hp.com',
     'officePhone': '970-555-0003',
     'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'},
    {'userName': 'Backupadmin', 'password': 'Backupadmin', 'fullName': 'Backupadmin',
     'permissions': [{'roleName': 'Backup administrator'}],
     'emailAddress': 'backup@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
     'type': 'UserAndPermissions'},
    {'userName': 'Noprivledge', 'password': 'Noprivledge', 'fullName': 'Noprivledge',
     'permissions': [{'roleName': 'Read only'}],
     'emailAddress': 'rheid@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003',
     'type': 'UserAndPermissions'}
]

licenses = [{
    'key': 'YCDE D9MA H9P9 8HUZ U7B5 HWW5 Y9JL KMPL MHND 7AJ9 DXAU 2CSM GHTG L762 LFH6 F4R4 KJVT D5KM EFVW DT5J 83HJ 8VC6 AK2P 3EW2 L9YE HUNJ TZZ7 MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEG 3F9V JQY5 "423207356 HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR H3TCJHCGAYAY"'},
    {
        'key': 'QC3C A9MA H9PQ GHVZ U7B5 HWW5 Y9JL KMPL 2HVF 4FZ9 DXAU 2CSM GHTG L762 7JX5 V5FU KJVT D5KM EFVW DV5J 43LL PSS6 AK2P 3EW2 T9YE XUNJ TZZ7 MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEG 3F9V JQY5 "423207566 HPOV-NFR2 HP_OneView_w/o_iLO_48_Seat_NFR 6H72JHCGY5AU"'}
]

ranges = [{'name': 'FCOE-MAC', 'type': 'Range', 'category': 'id-range-VMAC', 'rangeCategory': 'CUSTOM',
           'startAddress': 'AA:AA:AA:00:00:00', 'endAddress': 'AA:AA:AA:00:00:80', 'enabled': True},
          {'name': 'FCOE-WWN', 'type': 'Range', 'category': 'id-range-VWWN', 'rangeCategory': 'CUSTOM',
           'startAddress': '2A:AA:AA:AA:AA:AA:AA:AA', 'endAddress': '2A:AA:AA:AA:AA:AA:AB:29', 'enabled': True},
          {'name': 'FCOE-SN', 'type': 'Range', 'category': 'id-range-VSN', 'rangeCategory': 'CUSTOM',
           'startAddress': 'VCUAAAAAAA', 'endAddress': 'VCUAAAAADT', 'enabled': True}]

ethernet_networks = [{'name': 'eth-100',
                      'type': 'ethernet-networkV4',
                      'vlanId': 100,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'eth-101',
                      'type': 'ethernet-networkV4',
                      'vlanId': 101,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'eth-102',
                      'type': 'ethernet-networkV4',
                      'vlanId': 102,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-a',
                      'type': 'ethernet-networkV4',
                      'vlanId': 200,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-b',
                      'type': 'ethernet-networkV4',
                      'vlanId': 201,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-c',
                      'type': 'ethernet-networkV4',
                      'vlanId': 202,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-d',
                      'type': 'ethernet-networkV4',
                      'vlanId': 203,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},
                     {'name': 'network-e',
                      'type': 'ethernet-networkV4',
                      'vlanId': 204,
                      'purpose': 'General',
                      'smartLink': True,
                      'privateNetwork': False,
                      'connectionTemplateUri': None,
                      'ethernetNetworkType': 'Tagged'},

                     ]

network_sets = [{'name': 'netset1', 'type': 'network-setV4', 'networkUris': ['network-a'], 'nativeNetworkUri': None}]

fcoe_networks = {'fcoe-1': {'name': 'fcoe-1', 'type': 'fcoe-networkV4', 'vlanId': 1},
                 'fcoe-100': {'name': 'fcoe-100', 'type': 'fcoe-networkV4', 'vlanId': 100},
                 'fcoe-2000': {'name': 'fcoe-2000', 'type': 'fcoe-networkV4', 'vlanId': 2000},
                 'fcoe-100b': {'name': 'fcoe-100b', 'type': 'fcoe-networkV4', 'vlanId': 100},
                 'fcnetwork-a': {'name': 'fcnetwork-a', 'type': 'fcoe-networkV4', 'vlanId': 209},
                 'network-a': {'name': 'network-a', 'type': 'fcoe-networkV4', 'vlanId': 210},
                 'network-b': {'name': 'network-b', 'type': 'fcoe-networkV4', 'vlanId': 211},
                 'no-vlanId': {'name': 'no-vlanId', 'type': 'fcoe-networkV4'},
                 'fcoe-4095': {'name': 'fcoe-4095', 'type': 'fcoe-networkV4', 'vlanId': 4095}}

fcoe_ranges = {'fcoe-range32a': {'prefix': 'fcoe-', 'suffix': 'a', 'start': 1001, 'end': 1032},
               'fcoe-range32b': {'prefix': 'fcoe-', 'suffix': 'b', 'start': 1001, 'end': 1032},
               'fcoe-range32c': {'prefix': 'fcoe-', 'suffix': 'c', 'start': 1001, 'end': 1032},
               'fcoe-range32d': {'prefix': 'fcoe-', 'suffix': 'd', 'start': 1001, 'end': 1032},
               'fcoe-range33': {'prefix': 'fcoe-', 'suffix': '', 'start': 1001, 'end': 1033},
               'fcoe-range30a': {'prefix': 'fcoe-', 'suffix': 'a', 'start': 1001, 'end': 1030},
               'fcoe-range128': {'prefix': 'fcoe-', 'suffix': '', 'start': 1001, 'end': 1128},
               'fcoe-range-delete-20': {'prefix': 'fcoe-', 'suffix': '', 'start': 1109, 'end': 1128}
               }

fc_networks = [{'type': 'fc-networkV4',
                'linkStabilityTime': 30,
                'autoLoginRedistribution': True,
                'name': 'fcnetwork-a',
                'connectionTemplateUri': None,
                'managedSanUri': None,
                'fabricType': 'FabricAttach'}]

enc_group = {'name': 'EG',
             'interconnectBayMappings':
                 [{'interconnectBay': 1, 'logicalInterconnectGroupUri': 'LIG:BFS'},
                  {'interconnectBay': 2, 'logicalInterconnectGroupUri': 'LIG:BFS'},
                  {'interconnectBay': 3, 'logicalInterconnectGroupUri': 'LIG:BFS'},
                  {'interconnectBay': 4, 'logicalInterconnectGroupUri': 'LIG:BFS'},
                  {'interconnectBay': 5, 'logicalInterconnectGroupUri': 'LIG:BFS'},
                  {'interconnectBay': 6, 'logicalInterconnectGroupUri': 'LIG:BFS'},
                  {'interconnectBay': 7, 'logicalInterconnectGroupUri': None},
                  {'interconnectBay': 8, 'logicalInterconnectGroupUri': None}]}

encs = [{'hostname': '15.245.129.74', 'username': 'Administrator', 'password': 'hpvse1', 'enclosureGroupUri': 'EG:EG',
         'force': False, 'licensingIntent': 'OneViewNoiLO'}]

ENC1 = 'WPST-PABA58-EN1'
LE = 'WPST-PABA58-EN1'
LIG1 = 'LIG1'
LIG2 = 'BFS'

appliance = {'type': 'ApplianceNetworkConfigurationV2',
             'applianceNetworks':
                 [{'device': 'eth0',
                   'macAddress': None,
                   'interfaceName': 'LIT',
                   'activeNode': '1',
                   'unconfigure': False,
                   'ipv4Type': 'DHCP',
                   'ipv6Type': 'UNCONFIGURE',
                   'hostname': 'f100.usa.hp.com',
                   'confOneNode': True,
                   'domainName': 'usa.hp.com',
                   'aliasDisabled': True,
                   }],
             }

timeandlocale = {'type': 'TimeAndLocale', 'dateTime': None, 'timezone': 'UTC', 'ntpServers': ['ntp.hpecorp.net'],
                 'locale': 'en_US.UTF-8'}

uplink_sets = {'us1': {'name': 'us1',
                       'ethernetNetworkType': 'Tagged',
                       'networkType': 'Ethernet',
                       'networkUris': make_range_list(**fcoe_ranges['fcoe-range32a']),
                       'primaryPort': None,
                       'nativeNetworkUri': None,
                       'mode': 'Auto',
                       'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X2', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X3', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X4', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X5', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X6', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X7', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X8', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X9', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X10', 'speed': 'Auto'}]},
               'us2': {'name': 'us2',
                       'ethernetNetworkType': 'Tagged',
                       'networkType': 'Ethernet',
                       'networkUris': make_range_list(**fcoe_ranges['fcoe-range32b']),
                       'primaryPort': None,
                       'nativeNetworkUri': None,
                       'mode': 'Auto',
                       'logicalPortConfigInfos': [{'bay': '3', 'port': 'X1', 'speed': 'Auto'},
                                                  {'bay': '3', 'port': 'X2', 'speed': 'Auto'},
                                                  {'bay': '3', 'port': 'X3', 'speed': 'Auto'},
                                                  {'bay': '3', 'port': 'X4', 'speed': 'Auto'}]},
               'us3': {'name': 'us3',
                       'ethernetNetworkType': 'Tagged',
                       'networkType': 'Ethernet',
                       'networkUris': make_range_list(**fcoe_ranges['fcoe-range32c']),
                       'primaryPort': None,
                       'nativeNetworkUri': None,
                       'mode': 'Auto',
                       'logicalPortConfigInfos': [{'bay': '5', 'port': 'X1', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X2', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X3', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X4', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X5', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X6', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X7', 'speed': 'Auto'},
                                                  {'bay': '5', 'port': 'X8', 'speed': 'Auto'}]},
               'us33': {'name': 'us-33-exceeds-32',
                        'ethernetNetworkType': 'Tagged',
                        'networkType': 'Ethernet',
                        'networkUris': make_range_list(**fcoe_ranges['fcoe-range33']),
                        'primaryPort': None,
                        'nativeNetworkUri': None,
                        'mode': 'Auto',
                        'logicalPortConfigInfos': [{'bay': '4', 'port': 'X1', 'speed': 'Auto'},
                                                   {'bay': '4', 'port': 'X2', 'speed': 'Auto'},
                                                   {'bay': '4', 'port': 'X3', 'speed': 'Auto'},
                                                   {'bay': '4', 'port': 'X4', 'speed': 'Auto'}]},
               'us1-b': {'name': 'us1-b-removed X10, 30 networks',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': make_range_list(**fcoe_ranges['fcoe-range30a']),
                         'primaryPort': None,
                         'nativeNetworkUri': None,
                         'mode': 'Auto',
                         'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X2', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X3', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X4', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X5', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X6', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X7', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X8', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X9', 'speed': 'Auto'}]},

               'us1-c': {'name': 'us-3-exceeds-32max',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': ['fcoe-1001', 'fcoe-1002', 'fcoe-1003'],
                         'primaryPort': None,
                         'nativeNetworkUri': None,
                         'mode': 'Auto',
                         'logicalPortConfigInfos': [{'bay': '1', 'port': 'X10', 'speed': 'Auto'}]},
               'us1-d': {'name': 'us1',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': make_range_list(**fcoe_ranges['fcoe-range32a']),
                         'primaryPort': None,
                         'nativeNetworkUri': None,
                         'mode': 'Auto',
                         'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X2', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X3', 'speed': 'Auto'},
                                                    {'bay': '1', 'port': 'X4', 'speed': 'Auto'}]},
               'us1-eth': {'name': 'us1-eth',
                           'ethernetNetworkType': 'Tagged',
                           'networkType': 'Ethernet',
                           'networkUris': ['network-d'],
                           'primaryPort': None,
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'logicalPortConfigInfos': [{'bay': '1', 'port': 'X5', 'speed': 'Auto'},
                                                      {'bay': '1', 'port': 'X6', 'speed': 'Auto'}]},
               'us2-d': {'name': 'us2',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': make_range_list(**fcoe_ranges['fcoe-range32b']),
                         'primaryPort': None,
                         'nativeNetworkUri': None,
                         'mode': 'Auto',
                         'logicalPortConfigInfos': [{'bay': '3', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '3', 'port': 'X2', 'speed': 'Auto'}]},
               'us2-fc': {'name': 'us2-fc',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'FibreChannel',
                          'networkUris': ['fcnetwork-a'],
                          'primaryPort': None,
                          'nativeNetworkUri': None,
                          'mode': 'Auto',
                          'logicalPortConfigInfos': [{'bay': '3', 'port': 'X3', 'speed': 'Auto'},
                                                     {'bay': '3', 'port': 'X4', 'speed': 'Auto'}]},
               'us3-d': {'name': 'us3',
                         'ethernetNetworkType': 'Tagged',
                         'networkType': 'Ethernet',
                         'networkUris': make_range_list(**fcoe_ranges['fcoe-range32c']),
                         'primaryPort': None,
                         'nativeNetworkUri': None,
                         'mode': 'Auto',
                         'logicalPortConfigInfos': [{'bay': '5', 'port': 'X1', 'speed': 'Auto'},
                                                    {'bay': '5', 'port': 'X2', 'speed': 'Auto'},
                                                    {'bay': '5', 'port': 'X3', 'speed': 'Auto'},
                                                    {'bay': '5', 'port': 'X4', 'speed': 'Auto'}]},
               'us3-eth': {'name': 'us3-eth',
                           'ethernetNetworkType': 'Tagged',
                           'networkType': 'Ethernet',
                           'networkUris': ['network-e'],
                           'primaryPort': None,
                           'nativeNetworkUri': None,
                           'mode': 'Auto',
                           'logicalPortConfigInfos': [{'bay': '5', 'port': 'X5', 'speed': 'Auto'},
                                                      {'bay': '5', 'port': 'X6', 'speed': 'Auto'},
                                                      {'bay': '5', 'port': 'X7', 'speed': 'Auto'},
                                                      {'bay': '5', 'port': 'X8', 'speed': 'Auto'}]},
               'us3-2ics': {'name': 'us2-ics',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': ['fcoe-100'],
                            'primaryPort': None,
                            'nativeNetworkUri': None,
                            'mode': 'Auto',
                            'logicalPortConfigInfos': [{'bay': '5', 'port': 'X5', 'speed': 'Auto'},
                                                       {'bay': '6', 'port': 'X5', 'speed': 'Auto'}]},
               'unsupported-ics': {'name': 'unsupported-ics',
                                   'ethernetNetworkType': 'Tagged',
                                   'networkType': 'Ethernet',
                                   'networkUris': ['fcoe-100'],
                                   'primaryPort': None,
                                   'nativeNetworkUri': None,
                                   'mode': 'Auto',
                                   'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'}]},
               'unsupported-ics2': {'name': 'unsupported-ics2',
                                    'ethernetNetworkType': 'Tagged',
                                    'networkType': 'Ethernet',
                                    'networkUris': ['fcoe-100'],
                                    'primaryPort': None,
                                    'nativeNetworkUri': None,
                                    'mode': 'Auto',
                                    'logicalPortConfigInfos': [{'bay': '1', 'port': '1', 'speed': 'Auto'}]},
               'duplicate-vlan': {'name': 'duplicate-vlan',
                                  'ethernetNetworkType': 'Tagged',
                                  'networkType': 'Ethernet',
                                  'networkUris': ['eth-100', 'fcoe-100'],
                                  'primaryPort': None,
                                  'nativeNetworkUri': None,
                                  'mode': 'Auto',
                                  'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'}]},
               'BFS': {'name': 'BFS',
                       'ethernetNetworkType': 'Tagged',
                       'networkType': 'Ethernet',
                       'networkUris': ['eth-102', 'fcoe-1002'],
                       'primaryPort': None,
                       'nativeNetworkUri': None,
                       'mode': 'Auto',
                       'logicalPortConfigInfos': [{'bay': '1', 'port': 'X1', 'speed': 'Auto'},
                                                  {'bay': '1', 'port': 'X2', 'speed': 'Auto'}]},
               'BFS-fcoe': {'name': 'BFS-fcoe',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': ['fcoe-1002'],
                            'primaryPort': None,
                            'nativeNetworkUri': None,
                            'mode': 'Auto',
                            'logicalPortConfigInfos': [{'bay': '1', 'port': 'X2', 'speed': 'Auto'}]},
               }

li_uplink_sets = {'us1': {'name': 'us1',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': [],
                          'fcNetworkUris': [],
                          'fcoeNetworkUris': make_range_list(**fcoe_ranges['fcoe-range32a']),
                          'lacpTimer': 'Short',
                          'logicalInterconnectUri': None,
                          'primaryPortLocation': None,
                          'manualLoginRedistributionState': 'NotSupported',
                          'connectionMode': 'Auto',
                          'nativeNetworkUri': None,
                          'portConfigInfos': [{'bay': '1', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X5', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X6', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X7', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X8', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X9', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X10', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'us2': {'name': 'us2',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': [],
                          'fcNetworkUris': [],
                          'fcoeNetworkUris': make_range_list(**fcoe_ranges['fcoe-range32b']),
                          'lacpTimer': 'Short',
                          'logicalInterconnectUri': None,
                          'primaryPortLocation': None,
                          'manualLoginRedistributionState': 'NotSupported',
                          'connectionMode': 'Auto',
                          'nativeNetworkUri': None,
                          'portConfigInfos': [{'bay': '3', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '3', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '3', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '3', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'us3': {'name': 'us3',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': [],
                          'fcNetworkUris': [],
                          'fcoeNetworkUris': make_range_list(**fcoe_ranges['fcoe-range32c']),
                          'lacpTimer': 'Short',
                          'logicalInterconnectUri': None,
                          'primaryPortLocation': None,
                          'manualLoginRedistributionState': 'NotSupported',
                          'connectionMode': 'Auto',
                          'nativeNetworkUri': None,
                          'portConfigInfos': [{'bay': '5', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X5', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X6', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X7', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '5', 'port': 'X8', 'desiredSpeed': 'Auto', 'enclosure': None}
                                              ]},
                  'us3-30': {'name': 'us3',
                             'ethernetNetworkType': 'Tagged',
                             'networkType': 'Ethernet',
                             'networkUris': [],
                             'fcNetworkUris': [],
                             'fcoeNetworkUris': make_range_list(1001, 1030, 'fcoe-', 'c'),
                             'lacpTimer': 'Short',
                             'logicalInterconnectUri': None,
                             'primaryPortLocation': None,
                             'manualLoginRedistributionState': 'NotSupported',
                             'connectionMode': 'Auto',
                             'nativeNetworkUri': None,
                             'portConfigInfos': [{'bay': '5', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X5', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X6', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X7', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X8', 'desiredSpeed': 'Auto', 'enclosure': None}
                                                 ]},
                  'us3-30-x1-x7': {'name': 'us3',
                                   'ethernetNetworkType': 'Tagged',
                                   'networkType': 'Ethernet',
                                   'networkUris': [],
                                   'fcNetworkUris': [],
                                   'fcoeNetworkUris': make_range_list(1001, 1030, 'fcoe-', 'c'),
                                   'lacpTimer': 'Short',
                                   'logicalInterconnectUri': None,
                                   'primaryPortLocation': None,
                                   'manualLoginRedistributionState': 'NotSupported',
                                   'connectionMode': 'Auto',
                                   'nativeNetworkUri': None,
                                   'portConfigInfos': [
                                       {'bay': '5', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                       {'bay': '5', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                       {'bay': '5', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                       {'bay': '5', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None},
                                       {'bay': '5', 'port': 'X5', 'desiredSpeed': 'Auto', 'enclosure': None},
                                       {'bay': '5', 'port': 'X6', 'desiredSpeed': 'Auto', 'enclosure': None},
                                       {'bay': '5', 'port': 'X7', 'desiredSpeed': 'Auto', 'enclosure': None}
                                   ]},
                  'us33': {'name': 'us-33-exceeds-32',
                           'ethernetNetworkType': 'Tagged',
                           'networkType': 'Ethernet',
                           'networkUris': [],
                           'fcNetworkUris': [],
                           'fcoeNetworkUris': make_range_list(**fcoe_ranges['fcoe-range33']),
                           'lacpTimer': 'Short',
                           'logicalInterconnectUri': None,
                           'primaryPortLocation': None,
                           'manualLoginRedistributionState': 'NotSupported',
                           'connectionMode': 'Auto',
                           'nativeNetworkUri': None,
                           'portConfigInfos': [{'bay': '4', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                               {'bay': '4', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                               {'bay': '4', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                               {'bay': '4', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'us-3-networks': {'name': 'us-3-networks',
                                    'ethernetNetworkType': 'Tagged',
                                    'networkType': 'Ethernet',
                                    'networkUris': [],
                                    'fcNetworkUris': [],
                                    'fcoeNetworkUris': ['fcoe-1106', 'fcoe-1107', 'fcoe-1108'],
                                    'lacpTimer': 'Short',
                                    'logicalInterconnectUri': None,
                                    'primaryPortLocation': None,
                                    'manualLoginRedistributionState': 'NotSupported',
                                    'connectionMode': 'Auto',
                                    'nativeNetworkUri': None,
                                    'portConfigInfos': [
                                        {'bay': '5', 'port': 'X8', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'us1-b': {'name': 'us1',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': [],
                            'fcNetworkUris': [],
                            'fcoeNetworkUris': make_range_list(**fcoe_ranges['fcoe-range32a']),
                            'lacpTimer': 'Short',
                            'logicalInterconnectUri': None,
                            'primaryPortLocation': None,
                            'manualLoginRedistributionState': 'NotSupported',
                            'connectionMode': 'Auto',
                            'nativeNetworkUri': None,
                            'portConfigInfos': [{'bay': '1', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                {'bay': '1', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                {'bay': '1', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                {'bay': '1', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'us2-b': {'name': 'us2',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': [],
                            'fcNetworkUris': [],
                            'fcoeNetworkUris': make_range_list(**fcoe_ranges['fcoe-range32b']),
                            'lacpTimer': 'Short',
                            'logicalInterconnectUri': None,
                            'primaryPortLocation': None,
                            'manualLoginRedistributionState': 'NotSupported',
                            'connectionMode': 'Auto',
                            'nativeNetworkUri': None,
                            'portConfigInfos': [{'bay': '3', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                {'bay': '3', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'us3-b': {'name': 'us3',
                            'ethernetNetworkType': 'Tagged',
                            'networkType': 'Ethernet',
                            'networkUris': [],
                            'fcNetworkUris': [],
                            'fcoeNetworkUris': make_range_list(**fcoe_ranges['fcoe-range32c']),
                            'lacpTimer': 'Short',
                            'logicalInterconnectUri': None,
                            'primaryPortLocation': None,
                            'manualLoginRedistributionState': 'NotSupported',
                            'connectionMode': 'Auto',
                            'nativeNetworkUri': None,
                            'portConfigInfos': [{'bay': '5', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                {'bay': '5', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                {'bay': '5', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                {'bay': '5', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                ]},
                  'us-eth': {'name': 'us-eth',
                             'ethernetNetworkType': 'Tagged',
                             'networkType': 'Ethernet',
                             'networkUris': ['network-d'],
                             'fcNetworkUris': [],
                             'fcoeNetworkUris': [],
                             'lacpTimer': 'Short',
                             'logicalInterconnectUri': None,
                             'primaryPortLocation': None,
                             'manualLoginRedistributionState': 'NotSupported',
                             'connectionMode': 'Auto',
                             'nativeNetworkUri': None,
                             'portConfigInfos': [{'bay': '1', 'port': 'X5', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '1', 'port': 'X6', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '3', 'port': 'X3', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '3', 'port': 'X4', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X5', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X6', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X7', 'desiredSpeed': 'Auto', 'enclosure': None},
                                                 {'bay': '5', 'port': 'X8', 'desiredSpeed': 'Auto',
                                                  'enclosure': None}]},
                  'us-spans-2-ics': {'name': 'us-spans-2-ics',
                                     'ethernetNetworkType': 'Tagged',
                                     'networkType': 'Ethernet',
                                     'networkUris': [],
                                     'fcNetworkUris': [],
                                     'fcoeNetworkUris': ['fcoe-1108'],
                                     'lacpTimer': 'Short',
                                     'logicalInterconnectUri': None,
                                     'primaryPortLocation': None,
                                     'manualLoginRedistributionState': 'NotSupported',
                                     'connectionMode': 'Auto',
                                     'nativeNetworkUri': None,
                                     'portConfigInfos': [
                                         {'bay': '2', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                         {'bay': '4', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'us-dup-vlanId': {'name': 'us-dup-vlanId',
                                    'ethernetNetworkType': 'Tagged',
                                    'networkType': 'Ethernet',
                                    'networkUris': ['eth-100'],
                                    'fcNetworkUris': [],
                                    'fcoeNetworkUris': ['fcoe-100'],
                                    'lacpTimer': 'Short',
                                    'logicalInterconnectUri': None,
                                    'primaryPortLocation': None,
                                    'manualLoginRedistributionState': 'NotSupported',
                                    'connectionMode': 'Auto',
                                    'nativeNetworkUri': None,
                                    'portConfigInfos': [
                                        {'bay': '2', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  'BFS': {'name': 'us1',
                          'ethernetNetworkType': 'Tagged',
                          'networkType': 'Ethernet',
                          'networkUris': ['eth-102'],
                          'fcNetworkUris': [],
                          'fcoeNetworkUris': ['fcoe-1002'],
                          'lacpTimer': 'Short',
                          'logicalInterconnectUri': None,
                          'primaryPortLocation': None,
                          'manualLoginRedistributionState': 'NotSupported',
                          'connectionMode': 'Auto',
                          'nativeNetworkUri': None,
                          'portConfigInfos': [{'bay': '1', 'port': 'X1', 'desiredSpeed': 'Auto', 'enclosure': None},
                                              {'bay': '1', 'port': 'X2', 'desiredSpeed': 'Auto', 'enclosure': None}]},
                  }

icmap = [{'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'HP VC Flex-10/10D Module'},
         {'enclosure': 1, 'enclosureIndex': 1, 'bay': 2, 'type': 'HP VC Flex-10/10D Module'},
         {'enclosure': 1, 'enclosureIndex': 1, 'bay': 3, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
         {'enclosure': 1, 'enclosureIndex': 1, 'bay': 4, 'type': 'HP VC FlexFabric 10Gb/24-Port Module'},
         {'enclosure': 1, 'enclosureIndex': 1, 'bay': 5, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
         {'enclosure': 1, 'enclosureIndex': 1, 'bay': 6, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
         ]

icmap2 = [{'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'HP VC Flex-10 Enet Module'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 2, 'type': 'HP VC Flex-10 Enet Module'}]

icmap3 = [{'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'HP VC 8Gb 20-Port FC Module'}]

icmap4 = [{'enclosure': 1, 'enclosureIndex': 1, 'bay': 1, 'type': 'HP VC Flex-10/10D Module'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 2, 'type': 'HP VC Flex-10/10D Module'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 3, 'type': 'HP VC Flex-10 Enet Module'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 4, 'type': 'HP VC Flex-10 Enet Module'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 5, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
          {'enclosure': 1, 'enclosureIndex': 1, 'bay': 6, 'type': 'HP VC FlexFabric-20/40 F8 Module'},
          ]

ligs = {'lig1': {'name': 'LIG1',
                 'type': 'logical-interconnect-groupV4',
                 'enclosureType': 'C7000',
                 'interconnectMapTemplate': icmap,
                 'uplinkSets': [uplink_sets['us1'].copy(), uplink_sets['us2'].copy(), uplink_sets['us3'].copy()],
                 'stackingMode': 'Enclosure',
                 'ethernetSettings': None,
                 'state': 'Active',
                 'telemetryConfiguration': None,
                 'snmpConfiguration': None},

        'lig2':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1'].copy(), uplink_sets['us2'].copy(), uplink_sets['us3'].copy(),
                            uplink_sets['us33'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig2b':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1-b'].copy(), uplink_sets['us2'].copy(), uplink_sets['us3'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig3':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1-b'].copy(), uplink_sets['us1-c'].copy(), uplink_sets['us2'].copy(),
                            uplink_sets['us3'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig4':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1-d'].copy(), uplink_sets['us2-d'].copy(), uplink_sets['us3-d'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig4b':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1-d'].copy(), uplink_sets['us2-d'].copy(), uplink_sets['us3-d'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig5':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us1-d'].copy(), uplink_sets['us1-eth'].copy(), uplink_sets['us2-d'].copy(),
                            uplink_sets['us2-fc'].copy(), uplink_sets['us3-d'].copy(), uplink_sets['us3-eth'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig6':
            {'name': 'LIG2',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['us3-2ics'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig7':
            {'name': 'LIG3',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap2,
             'uplinkSets': [uplink_sets['unsupported-ics'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig8':
            {'name': 'LIG3',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap3,
             'uplinkSets': [uplink_sets['unsupported-ics2'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig9':
            {'name': 'LIG3',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap,
             'uplinkSets': [uplink_sets['duplicate-vlan'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'lig10':
            {'name': 'LIG1',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap4,
             'uplinkSets': [uplink_sets['unsupported-ics'].copy(), uplink_sets['us2'].copy(),
                            uplink_sets['us3'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'BFS':
            {'name': 'BFS',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': icmap4,
             'uplinkSets': [uplink_sets['BFS'].copy()],
             # 'uplinkSets': [uplink_sets['BFS'].copy(), uplink_sets['BFS-fcoe'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None},

        'BFS2':
            {'name': 'BFS',
             'type': 'logical-interconnect-groupV4',
             'enclosureType': 'C7000',
             'interconnectMapTemplate': [],
             'uplinkSets': [],
             # 'uplinkSets': [uplink_sets['BFS'].copy(), uplink_sets['BFS-fcoe'].copy()],
             'stackingMode': 'Enclosure',
             'ethernetSettings': None,
             'state': 'Active',
             'telemetryConfiguration': None,
             'snmpConfiguration': None}

        }

telemetry = {'enableTelemetry': True, 'sampleInterval': 400, 'sampleCount': 20}

trapDestinations = [{'trapSeverities': ['Major'],
                     'enetTrapCategories': ['Other'],
                     'fcTrapCategories': ['Other'],
                     'vcmTrapCategories': ['Legacy'],
                     'trapFormat': 'SNMPv1',
                     'trapDestination': '192.168.99.99',
                     'communityString': 'public'}]

snmp = {'snmpAccess': ['192.168.1.0/24'],
        'trapDestinations': trapDestinations}

enet = {'enableFastMacCacheFailover': False}

"""
profile1 = {'type': 'ServerProfileV8', 'serverHardwareUri': 'WPST-PABA58-EN1, bay 1',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PABA58-EN1', 'enclosureGroupUri': 'EG:EG', 'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'WPST-PABA58-EN1_Bay1-BFS', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:eth-102', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b', 'requestedMbps': '2500', 'networkUri': 'FCOE:fcoe-1002', 'boot': {'priority': 'Primary', 'targets': [{'arrayWwpn': '21110002AC003655', 'lun': '0'}]}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    ]}

profile2 = {'type': 'ServerProfileV8', 'serverHardwareUri': 'WPST-PABA58-EN1, bay 2',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PABA58-EN1', 'enclosureGroupUri': 'EG:EG', 'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'WPST-PABA58-EN1_Bay2', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a', 'requestedMbps': '2500', 'networkUri': 'ETH:eth-102', 'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                   ]}

server_profiles = [profile1.copy(), profile2.copy()]

"""
server_profiles = [{'type': 'ServerProfileV8', 'serverHardwareUri': 'WPST-PABA58-EN1, bay 1',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PABA58-EN1', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'WPST-PABA58-EN1_Bay1-BFS', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:eth-102',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    {'id': 2, 'name': '2', 'functionType': 'FibreChannel', 'portId': 'Flb 1:1-b',
                                     'requestedMbps': '2500', 'networkUri': 'FCOE:fcoe-1002',
                                     'boot': {'priority': 'Primary', 'bootVolumeSource': 'UserDefined',
                                              'targets': [{'arrayWwpn': '21110002AC003655', 'lun': '0'}]}, 'mac': None,
                                     'wwpn': '', 'wwnn': ''},
                                    ]},
                   {'type': 'ServerProfileV8', 'serverHardwareUri': 'WPST-PABA58-EN1, bay 2',
                    'serverHardwareTypeUri': '', 'enclosureUri': 'ENC:WPST-PABA58-EN1', 'enclosureGroupUri': 'EG:EG',
                    'serialNumberType': 'Physical', 'macType': 'Physical', 'wwnType': 'Physical',
                    'name': 'WPST-PABA58-EN1_Bay2', 'description': '', 'affinity': 'Bay',
                    'boot': {'manageBoot': True, 'order': ['CD', 'Floppy', 'USB', 'PXE', 'HardDisk']},
                    'connections': [{'id': 1, 'name': '1', 'functionType': 'Ethernet', 'portId': 'Flb 1:1-a',
                                     'requestedMbps': '2500', 'networkUri': 'ETH:eth-102',
                                     'boot': {'priority': 'NotBootable'}, 'mac': None, 'wwpn': '', 'wwnn': ''},
                                    ]},
                   ]
