Appliance = '16.83.10.176'
admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}
server_hardwares = [{"name": "172.18.31.4", "hostname": "172.18.31.4", "username": "dcs", "password": "dcs", "force": True, "licensingIntent": "OneViewNoiLO", "configurationState": "Managed"},
                    {"name": "172.18.6.6", "hostname": "172.18.6.6", "username": "dcs", "password": "dcs",
                        "force": True, "licensingIntent": "OneViewNoiLO", "configurationState": "Managed"},
                    {"name": "172.18.6.7", "hostname": "172.18.6.7", "username": "dcs", "password": "dcs", "force": True, "licensingIntent": "OneViewNoiLO", "configurationState": "Monitored"}]

host_names = ['172.18.31.4', '172.18.6.6', '172.18.6.7']
host_name_gen10 = '172.18.31.4'
host_name_gen9 = '172.18.6.6'
host_name_gen8 = '172.18.6.7'

sht_gen10 = "DL380 Gen10 1"
sht_gen9 = "DL360 Gen9 1"
sht_gen8 = "DL380p Gen8 1"

ilo_credentials = {'UserName': 'dcs', 'Password': 'dcs'}

SP_1_gen10 = [{"type": "ServerProfileV10",
               "serverHardwareUri": None,
               "serverHardwareTypeUri": "SHT:" + sht_gen10,
               "serialNumberType": "Physical",
               "iscsiInitiatorNameType": "AutoGenerated",
               "macType": "Physical",
               "wwnType": "Physical",
               "name": "SP_1_gen10",
               "description": "",
               "affinity": None,
               "connectionSettings": {
                   "connections": []},
               "boot": {
                   "manageBoot": False},
               "bootMode": {
                   "manageMode": True,
                   "mode": "UEFIOptimized",
                   "secureBoot": "Unmanaged",
                   "pxeBootPolicy": "Auto"},
               "firmware": {
                   "manageFirmware": False,
                   "firmwareBaselineUri": "",
                   "forceInstallFirmware": False,
                   "firmwareInstallType": None,
                   "firmwareScheduleDateTime": "",
                   "firmwareActivationType": "Immediate"},
               "bios": {
                   "manageBios": False},
               "hideUnusedFlexNics": True,
               "iscsiInitiatorName": "",
               "osDeploymentSettings": None,
               "localStorage": {
                   "sasLogicalJBODs": [],
                   "controllers": []},
               "sanStorage": None,
               "initialScopeUris": []
               }]

SP_2_gen10 = [{"type": "ServerProfileV10",
               "serverHardwareUri": None,
               "serverHardwareTypeUri": "SHT:" + sht_gen10,
               "serialNumberType": "Physical",
               "iscsiInitiatorNameType": "AutoGenerated",
               "macType": "Physical",
               "wwnType": "Physical",
               "name": "SP_2_gen10",
               "description": "",
               "affinity": None,
               "connectionSettings": {
                   "connections": []},
               "boot": {
                   "manageBoot": False},
               "bootMode": {
                   "manageMode": True,
                   "mode": "UEFIOptimized",
                   "secureBoot": "Unmanaged",
                   "pxeBootPolicy": "Auto"},
               "firmware": {
                   "manageFirmware": False,
                   "firmwareBaselineUri": "",
                   "forceInstallFirmware": False,
                   "firmwareInstallType": None,
                   "firmwareScheduleDateTime": "",
                   "firmwareActivationType": "Immediate"},
               "bios": {
                   "manageBios": True,
                   "overriddenSettings": []},
               "hideUnusedFlexNics": True,
               "iscsiInitiatorName": "",
               "osDeploymentSettings": None,
               "localStorage": {
                   "sasLogicalJBODs": [],
                   "controllers": []},
               "sanStorage": None,
               "initialScopeUris": []
               }]

SP_3_gen10 = [{"type": "ServerProfileV10",
               "serverHardwareUri": "SH:" + host_name_gen10,
               "serverHardwareTypeUri": "SHT:" + sht_gen10,
               "serialNumberType": "Physical",
               "iscsiInitiatorNameType": "AutoGenerated",
               "macType": "Physical",
               "wwnType": "Physical",
               "name": "SP_3_gen10",
               "description": "",
               "affinity": None,
               "connectionSettings": {
                   "connections": []},
               "boot": {
                   "manageBoot": False},
               "bootMode": {
                   "manageMode": True,
                   "mode": "UEFIOptimized",
                   "secureBoot": "Unmanaged",
                   "pxeBootPolicy": "Auto"},
               "firmware": {
                   "manageFirmware": False,
                   "firmwareBaselineUri": "",
                   "forceInstallFirmware": False,
                   "firmwareInstallType": None,
                   "firmwareScheduleDateTime": "",
                   "firmwareActivationType": "Immediate"},
               "bios": {
                   "manageBios": True,
                   "overriddenSettings": [{"id": "AsrStatus",
                                           "value": "Disabled"}, ],
                   "reapplyState": "NotApplying"},
               "hideUnusedFlexNics": True,
               "iscsiInitiatorName": "",
               "osDeploymentSettings": None,
               "localStorage": {
                   "sasLogicalJBODs": [],
                   "controllers": []},
               "sanStorage": None,
               "initialScopeUris": []
               }]

SP_1_gen9 = [{"type": "ServerProfileV10",
              "serverHardwareUri": None,
              "serverHardwareTypeUri": "SHT:" + sht_gen9,
              "serialNumberType": "Physical",
              "iscsiInitiatorNameType": "AutoGenerated",
              "macType": "Physical",
              "wwnType": "Physical",
              "name": "SP_1_gen9",
              "description": "",
              "affinity": None,
              "connectionSettings": {
                  "connections": []},
              "boot": {
                  "manageBoot": False},
              "bootMode": {
                  "manageMode": True,
                  "mode": "UEFIOptimized",
                  "secureBoot": "Unmanaged",
                  "pxeBootPolicy": "Auto"},
              "firmware": {
                  "manageFirmware": False,
                  "firmwareBaselineUri": "",
                  "forceInstallFirmware": False,
                  "firmwareInstallType": None,
                  "firmwareScheduleDateTime": "",
                  "firmwareActivationType": "Immediate"},
              "bios": {
                  "manageBios": False},
              "hideUnusedFlexNics": True,
              "iscsiInitiatorName": "",
              "osDeploymentSettings": None,
              "localStorage": {
                  "sasLogicalJBODs": [],
                  "controllers": []},
              "sanStorage": None,
              "initialScopeUris": []
              }]

SP_2_gen9 = [{"type": "ServerProfileV10",
              "serverHardwareUri": None,
              "serverHardwareTypeUri": "SHT:" + sht_gen9,
              "serialNumberType": "Physical",
              "iscsiInitiatorNameType": "AutoGenerated",
              "macType": "Physical",
              "wwnType": "Physical",
              "name": "SP_2_gen9",
              "description": "",
              "affinity": None,
              "connectionSettings": {
                  "connections": []},
              "boot": {
                  "manageBoot": False},
              "bootMode": {
                  "manageMode": True,
                  "mode": "UEFIOptimized",
                  "secureBoot": "Unmanaged",
                  "pxeBootPolicy": "Auto"},
              "firmware": {
                  "manageFirmware": False,
                  "firmwareBaselineUri": "",
                  "forceInstallFirmware": False,
                  "firmwareInstallType": None,
                  "firmwareScheduleDateTime": "",
                  "firmwareActivationType": "Immediate"},
              "bios": {
                  "manageBios": True,
                  "overriddenSettings": []},
              "hideUnusedFlexNics": True,
              "iscsiInitiatorName": "",
              "osDeploymentSettings": None,
              "localStorage": {
                  "sasLogicalJBODs": [],
                  "controllers": []},
              "sanStorage": None,
              "initialScopeUris": []
              }]

SP_3_gen9 = [{"type": "ServerProfileV10",
              "serverHardwareUri": "SH:" + host_name_gen9,
              "serverHardwareTypeUri": "SHT:" + sht_gen9,
              "serialNumberType": "Physical",
              "iscsiInitiatorNameType": "AutoGenerated",
              "macType": "Physical",
              "wwnType": "Physical",
              "name": "SP_3_gen9",
              "description": "",
              "affinity": None,
              "connectionSettings": {
                  "connections": []},
              "boot": {
                  "manageBoot": False},
              "bootMode": {
                  "manageMode": True,
                  "mode": "UEFIOptimized",
                  "secureBoot": "Unmanaged",
                  "pxeBootPolicy": "Auto"},
              "firmware": {
                  "manageFirmware": False,
                  "firmwareBaselineUri": "",
                  "forceInstallFirmware": False,
                  "firmwareInstallType": None,
                  "firmwareScheduleDateTime": "",
                  "firmwareActivationType": "Immediate"},
              "bios": {
                  "manageBios": True,
                  "overriddenSettings": [{"id": "AsrStatus",
                                          "value": "Disabled"}, ],
                  "reapplyState": "NotApplying"},
              "hideUnusedFlexNics": True,
              "iscsiInitiatorName": "",
              "osDeploymentSettings": None,
              "localStorage": {
                  "sasLogicalJBODs": [],
                  "controllers": []},
              "sanStorage": None,
              "initialScopeUris": []
              }]

SP_1_gen8 = [{"type": "ServerProfileV10",
              "serverHardwareUri": None,
              "serverHardwareTypeUri": "SHT:" + sht_gen8,
              "serialNumberType": "Physical",
              "iscsiInitiatorNameType": "AutoGenerated",
              "macType": "Physical",
              "wwnType": "Physical",
              "name": "SP_1_gen8",
              "description": "",
              "affinity": None,
              "connectionSettings": {
                  "connections": []},
              "boot": {
                  "manageBoot": False},
              "bootMode": {
                  "manageMode": True,
                  "mode": "UEFIOptimized",
                  "secureBoot": "Unmanaged",
                  "pxeBootPolicy": "Auto"},
              "firmware": {
                  "manageFirmware": False,
                  "firmwareBaselineUri": "",
                  "forceInstallFirmware": False,
                  "firmwareInstallType": None,
                  "firmwareScheduleDateTime": "",
                  "firmwareActivationType": "Immediate"},
              "bios": {
                  "manageBios": False},
              "hideUnusedFlexNics": True,
              "iscsiInitiatorName": "",
              "osDeploymentSettings": None,
              "localStorage": {
                  "sasLogicalJBODs": [],
                  "controllers": []},
              "sanStorage": None,
              "initialScopeUris": []
              }]

SP_2_gen8 = [{"type": "ServerProfileV10",
              "serverHardwareUri": None,
              "serverHardwareTypeUri": "SHT:" + sht_gen8,
              "serialNumberType": "Physical",
              "iscsiInitiatorNameType": "AutoGenerated",
              "macType": "Physical",
              "wwnType": "Physical",
              "name": "SP_2_gen8",
              "description": "",
              "affinity": None,
              "connectionSettings": {
                  "connections": []},
              "boot": {
                  "manageBoot": False},
              "bootMode": {
                  "manageMode": True,
                  "mode": "UEFIOptimized",
                  "secureBoot": "Unmanaged",
                  "pxeBootPolicy": "Auto"},
              "firmware": {
                  "manageFirmware": False,
                  "firmwareBaselineUri": "",
                  "forceInstallFirmware": False,
                  "firmwareInstallType": None,
                  "firmwareScheduleDateTime": "",
                  "firmwareActivationType": "Immediate"},
              "bios": {
                  "manageBios": True,
                  "overriddenSettings": []},
              "hideUnusedFlexNics": True,
              "iscsiInitiatorName": "",
              "osDeploymentSettings": None,
              "localStorage": {
                  "sasLogicalJBODs": [],
                  "controllers": []},
              "sanStorage": None,
              "initialScopeUris": []
              }]

SP_3_gen8 = [{"type": "ServerProfileV10",
              "serverHardwareUri": "SH:" + host_name_gen8,
              "serverHardwareTypeUri": "SHT:" + sht_gen8,
              "serialNumberType": "Physical",
              "iscsiInitiatorNameType": "AutoGenerated",
              "macType": "Physical",
              "wwnType": "Physical",
              "name": "SP_3_gen8",
              "description": "",
              "affinity": None,
              "connectionSettings": {
                  "connections": []},
              "boot": {
                  "manageBoot": False},
              "bootMode": {
                  "manageMode": True,
                  "mode": "UEFIOptimized",
                  "secureBoot": "Unmanaged",
                  "pxeBootPolicy": "Auto"},
              "firmware": {
                  "manageFirmware": False,
                  "firmwareBaselineUri": "",
                  "forceInstallFirmware": False,
                  "firmwareInstallType": None,
                  "firmwareScheduleDateTime": "",
                  "firmwareActivationType": "Immediate"},
              "bios": {
                  "manageBios": True,
                  "overriddenSettings": [{"id": "AsrStatus",
                                          "value": "Disabled"}, ],
                  #                                      {"id": "AdvancedMemProtection",
                  #                                       "value": "OnlineSpareAdvancedEcc"},
                  #                                      {"id": "MemRefreshRate",
                  #                                       "value": "Refreshx2"},
                  #                                      {"id": "PersistentMemBackupPowerPolicy",
                  #                                       "value": "BootWithoutBackupPower"}],
                  "reapplyState": "NotApplying"},
              "hideUnusedFlexNics": True,
              "iscsiInitiatorName": "",
              "osDeploymentSettings": None,
              "localStorage": {
                  "sasLogicalJBODs": [],
                  "controllers": []},
              "sanStorage": None,
              "initialScopeUris": []
              }]

SP_1s = [SP_1_gen10, SP_1_gen9]  # , SP_1_gen8]
SP_2s = [SP_2_gen10, SP_2_gen9]  # , SP_2_gen8]
SP_3s = [SP_3_gen10, SP_3_gen9]  # , SP_3_gen8]

# synergy

syn_ENC = "0000A66101"

LIG_Data = {
    "type": "logical-interconnect-groupV6",
    "uri": None,
    "category": None,
    "eTag": None,
    "created": None,
    "modified": None,
    "ethernetSettings": {
        "type": "EthernetInterconnectSettingsV5"},
    "description": None,
    "state": None,
    "status": None,
    "name": "lig",
    "telemetryConfiguration": {
        "type": "telemetry-configuration",
        "enableTelemetry": True,
        "sampleCount": 12,
        "sampleInterval": 300,
        "consistencyChecking": "ExactMatch",
        "vcfcsampleIntervals": None
    },
    "interconnectMapTemplate": [{'bay': 3, 'enclosure': 1, 'type': "Virtual Connect SE 40Gb F8 Module for Synergy", 'enclosureIndex': 1},
                                {'bay': 6, 'enclosure': 1, 'type': "Virtual Connect SE 40Gb F8 Module for Synergy", 'enclosureIndex': 1}],
    "uplinkSets": [],
    "enclosureType": "SY12000",
    "enclosureIndexes": [1],
    "interconnectBaySet": "3",
    "redundancyType": "Redundant",
    "internalNetworkUris": [],
    "initialScopeUris": []
}

iLO_REDFISH_SESSION_URI = "/redfish/v1/Sessions/"
iLO_REDFISH_VERSION = "4.0"
eg = {"name": "eg", "interconnectBayMappings": [{"interconnectBay": 3, "logicalInterconnectGroupUri": 'LIG:lig'}, {"interconnectBay": 6, "logicalInterconnectGroupUri": 'LIG:lig'}],
      "ipAddressingMode": "External", "ipRangeUris": [], "enclosureCount": 1,
      "osDeploymentSettings": {"manageOSDeployment": False, "deploymentModeSettings": {"deploymentMode": "None", "deploymentNetworkUri": None}},
      "powerMode": "RedundantPowerFeed", "ambientTemperatureMode": "Standard", "initialScopeUris": []}
le = {"name": "LE", "enclosureUris": ['ENC:' + syn_ENC], "enclosureGroupUri": "EG:eg",
      "firmwareBaselineUri": None, "forceInstallFirmware": False, "initialScopeUris": []}

syn_host_names = ['172.18.31.3', '172.18.6.1']
syn_host_name_gen10 = '172.18.31.3'
syn_host_name_gen9 = '172.18.6.1'

syn_sht_gen10 = "SY 660 Gen10 1"
syn_sht_gen9 = "SY 480 Gen9 1"

syn_SP_1_gen10 = [{"type": "ServerProfileV10",
                   "serverHardwareUri": None,
                   "serverHardwareTypeUri": "SHT:" + syn_sht_gen10,
                   'enclosureGroupUri': 'EG:eg',
                   "serialNumberType": "Physical",
                   "iscsiInitiatorNameType": "AutoGenerated",
                   "macType": "Physical",
                   "wwnType": "Physical",
                   "name": "SP_1_gen10",
                   "description": "",
                   "affinity": None,
                   "connectionSettings": {
                       "connections": []},
                   "boot": {
                       "manageBoot": False},
                   "bootMode": {
                       "manageMode": True,
                       "mode": "UEFIOptimized",
                       "secureBoot": "Unmanaged",
                       "pxeBootPolicy": "Auto"},
                   "firmware": {
                       "manageFirmware": False,
                       "firmwareBaselineUri": "",
                       "forceInstallFirmware": False,
                       "firmwareInstallType": None,
                       "firmwareScheduleDateTime": "",
                       "firmwareActivationType": "Immediate"},
                   "bios": {
                       "manageBios": False},
                   "hideUnusedFlexNics": True,
                   "iscsiInitiatorName": "",
                   "osDeploymentSettings": None,
                   "localStorage": {
                       "sasLogicalJBODs": [],
                       "controllers": []},
                   "sanStorage": None,
                   "initialScopeUris": []
                   }]

syn_SP_2_gen10 = [{"type": "ServerProfileV10",
                   "serverHardwareUri": None,
                   "serverHardwareTypeUri": "SHT:" + syn_sht_gen10,
                   'enclosureGroupUri': 'EG:eg',
                   "serialNumberType": "Physical",
                   "iscsiInitiatorNameType": "AutoGenerated",
                   "macType": "Physical",
                   "wwnType": "Physical",
                   "name": "SP_2_gen10",
                   "description": "",
                   "affinity": None,
                   "connectionSettings": {
                       "connections": []},
                   "boot": {
                       "manageBoot": False},
                   "bootMode": {
                       "manageMode": True,
                       "mode": "UEFIOptimized",
                       "secureBoot": "Unmanaged",
                       "pxeBootPolicy": "Auto"},
                   "firmware": {
                       "manageFirmware": False,
                       "firmwareBaselineUri": "",
                       "forceInstallFirmware": False,
                       "firmwareInstallType": None,
                       "firmwareScheduleDateTime": "",
                       "firmwareActivationType": "Immediate"},
                   "bios": {
                       "manageBios": True,
                       "overriddenSettings": []},
                   "hideUnusedFlexNics": True,
                   "iscsiInitiatorName": "",
                   "osDeploymentSettings": None,
                   "localStorage": {
                       "sasLogicalJBODs": [],
                       "controllers": []},
                   "sanStorage": None,
                   "initialScopeUris": []
                   }]

syn_SP_3_gen10 = [{"type": "ServerProfileV10",
                   "serverHardwareUri": "SH:" + syn_host_name_gen10,
                   "serverHardwareTypeUri": "SHT:" + syn_sht_gen10,
                   'enclosureGroupUri': 'EG:eg',
                   "serialNumberType": "Physical",
                   "iscsiInitiatorNameType": "AutoGenerated",
                   "macType": "Physical",
                   "wwnType": "Physical",
                   "name": "SP_3_gen10",
                   "description": "",
                   "affinity": None,
                   "connectionSettings": {
                       "connections": []},
                   "boot": {
                       "manageBoot": False},
                   "bootMode": {
                       "manageMode": True,
                       "mode": "UEFIOptimized",
                       "secureBoot": "Unmanaged",
                       "pxeBootPolicy": "Auto"},
                   "firmware": {
                       "manageFirmware": False,
                       "firmwareBaselineUri": "",
                       "forceInstallFirmware": False,
                       "firmwareInstallType": None,
                       "firmwareScheduleDateTime": "",
                       "firmwareActivationType": "Immediate"},
                   "bios": {
                       "manageBios": True,
                       "overriddenSettings": [{"id": "AsrStatus",
                                               "value": "Disabled"}, ],
                       #                                      {"id": "AdvancedMemProtection",
                       #                                       "value": "OnlineSpareAdvancedEcc"},
                       #                                      {"id": "MemRefreshRate",
                       #                                       "value": "Refreshx2"},
                       #                                      {"id": "PersistentMemBackupPowerPolicy",
                       #                                       "value": "BootWithoutBackupPower"}],
                       "reapplyState": "NotApplying"},
                   "hideUnusedFlexNics": True,
                   "iscsiInitiatorName": "",
                   "osDeploymentSettings": None,
                   "localStorage": {
                       "sasLogicalJBODs": [],
                       "controllers": []},
                   "sanStorage": None,
                   "initialScopeUris": []
                   }]

syn_SP_1_gen9 = [{"type": "ServerProfileV10",
                  "serverHardwareUri": None,
                  "serverHardwareTypeUri": "SHT:" + syn_sht_gen9,
                  'enclosureGroupUri': 'EG:eg',
                  "serialNumberType": "Physical",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "macType": "Physical",
                  "wwnType": "Physical",
                  "name": "SP_1_gen9",
                  "description": "",
                  "affinity": None,
                  "connectionSettings": {
                      "connections": []},
                  "boot": {
                      "manageBoot": False},
                  "bootMode": {
                      "manageMode": True,
                      "mode": "UEFIOptimized",
                      "secureBoot": "Unmanaged",
                      "pxeBootPolicy": "Auto"},
                  "firmware": {
                      "manageFirmware": False,
                      "firmwareBaselineUri": "",
                      "forceInstallFirmware": False,
                      "firmwareInstallType": None,
                      "firmwareScheduleDateTime": "",
                      "firmwareActivationType": "Immediate"},
                  "bios": {
                      "manageBios": False},
                  "hideUnusedFlexNics": True,
                  "iscsiInitiatorName": "",
                  "osDeploymentSettings": None,
                  "localStorage": {
                      "sasLogicalJBODs": [],
                      "controllers": []},
                  "sanStorage": None,
                  "initialScopeUris": []
                  }]

syn_SP_2_gen9 = [{"type": "ServerProfileV10",
                  "serverHardwareUri": None,
                  "serverHardwareTypeUri": "SHT:" + syn_sht_gen9,
                  'enclosureGroupUri': 'EG:eg',
                  "serialNumberType": "Physical",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "macType": "Physical",
                  "wwnType": "Physical",
                  "name": "SP_2_gen9",
                  "description": "",
                  "affinity": None,
                  "connectionSettings": {
                      "connections": []},
                  "boot": {
                      "manageBoot": False},
                  "bootMode": {
                      "manageMode": True,
                      "mode": "UEFIOptimized",
                      "secureBoot": "Unmanaged",
                      "pxeBootPolicy": "Auto"},
                  "firmware": {
                      "manageFirmware": False,
                      "firmwareBaselineUri": "",
                      "forceInstallFirmware": False,
                      "firmwareInstallType": None,
                      "firmwareScheduleDateTime": "",
                      "firmwareActivationType": "Immediate"},
                  "bios": {
                      "manageBios": True,
                      "overriddenSettings": []},
                  "hideUnusedFlexNics": True,
                  "iscsiInitiatorName": "",
                  "osDeploymentSettings": None,
                  "localStorage": {
                      "sasLogicalJBODs": [],
                      "controllers": []},
                  "sanStorage": None,
                  "initialScopeUris": []
                  }]

syn_SP_3_gen9 = [{"type": "ServerProfileV10",
                  "serverHardwareUri": "SH:" + syn_host_name_gen9,
                  "serverHardwareTypeUri": "SHT:" + syn_sht_gen9,
                  'enclosureGroupUri': 'EG:eg',
                  "serialNumberType": "Physical",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "macType": "Physical",
                  "wwnType": "Physical",
                  "name": "SP_3_gen9",
                  "description": "",
                  "affinity": None,
                  "connectionSettings": {
                      "connections": []},
                  "boot": {
                      "manageBoot": False},
                  "bootMode": {
                      "manageMode": True,
                      "mode": "UEFIOptimized",
                      "secureBoot": "Unmanaged",
                      "pxeBootPolicy": "Auto"},
                  "firmware": {
                      "manageFirmware": False,
                      "firmwareBaselineUri": "",
                      "forceInstallFirmware": False,
                      "firmwareInstallType": None,
                      "firmwareScheduleDateTime": "",
                      "firmwareActivationType": "Immediate"},
                  "bios": {
                      "manageBios": True,
                      "overriddenSettings": [{"id": "AsrStatus",
                                              "value": "Disabled"}, ],
                      #                                      {"id": "AdvancedMemProtection",
                      #                                       "value": "OnlineSpareAdvancedEcc"}],
                      "reapplyState": "NotApplying"},
                  "hideUnusedFlexNics": True,
                  "iscsiInitiatorName": "",
                  "osDeploymentSettings": None,
                  "localStorage": {
                      "sasLogicalJBODs": [],
                      "controllers": []},
                  "sanStorage": None,
                  "initialScopeUris": []
                  }]

syn_SP_1s = [syn_SP_1_gen10, syn_SP_1_gen9]  # , SP_1_gen8]
syn_SP_2s = [syn_SP_2_gen10, syn_SP_2_gen9]  # , SP_2_gen8]
syn_SP_3s = [syn_SP_3_gen10, syn_SP_3_gen9]  # , SP_3_gen8]

# c7k
c7k_enc_groups = {"name": "c7k_eg",
                  "interconnectBayMappings": [],
                  "ipRangeUris": [],
                  "enclosureCount": 1,
                  "osDeploymentSettings": None,
                  "configurationScript": "",
                  "powerMode": None,
                  "ambientTemperatureMode": "Standard",
                  "initialScopeUris": []
                  }

c7k_enclosures_managed = [{"username": "dcs",
                           "password": "dcs",
                           "enclosureGroupUri": "EG:c7k_eg",
                           "firmwareBaselineUri": None,
                           "updateFirmwareOn": None,
                           "force": True,
                           "forceInstallFirmware": False,
                           "licensingIntent": "OneViewNoiLO",
                           "initialScopeUris": [],
                           "hostname": "172.18.1.17"}]

c7k_host_names = ['Encl4, bay 5', 'Encl4, bay 3', 'Encl4, bay 2']
c7k_host_name_gen10 = 'Encl4, bay 5'
c7k_host_name_gen9 = 'Encl4, bay 3'
c7k_host_name_gen8 = 'Encl4, bay 2'

c7k_sht_gen10 = "BL460c Gen10 1"
c7k_sht_gen9 = "BL660c Gen9 1"
c7k_sht_gen8 = "BL465c Gen8 1"

c7k_SP_1_gen10 = [{"type": "ServerProfileV10",
                   "serverHardwareUri": None,
                   "serverHardwareTypeUri": "SHT:" + c7k_sht_gen10,
                   'enclosureGroupUri': 'EG:c7k_eg',
                   "serialNumberType": "Physical",
                   "iscsiInitiatorNameType": "AutoGenerated",
                   "macType": "Physical",
                   "wwnType": "Physical",
                   "name": "SP_1_gen10",
                   "description": "",
                   "affinity": "Bay",
                   "connectionSettings": {
                       "connections": []},
                   "boot": {
                       "manageBoot": False},
                   "bootMode": {
                       "manageMode": True,
                       "mode": "UEFIOptimized",
                       "secureBoot": "Unmanaged",
                       "pxeBootPolicy": "Auto"},
                   "firmware": {
                       "manageFirmware": False,
                       "firmwareBaselineUri": "",
                       "forceInstallFirmware": False,
                       "firmwareInstallType": None,
                       "firmwareScheduleDateTime": "",
                       "firmwareActivationType": "Immediate"},
                   "bios": {
                       "manageBios": False},
                   "hideUnusedFlexNics": True,
                   "iscsiInitiatorName": "",
                   "osDeploymentSettings": None,
                   "localStorage": {
                       "sasLogicalJBODs": [],
                       "controllers": []},
                   "sanStorage": None,
                   "initialScopeUris": []
                   }]

c7k_SP_2_gen10 = [{"type": "ServerProfileV10",
                   "serverHardwareUri": None,
                   "serverHardwareTypeUri": "SHT:" + c7k_sht_gen10,
                   'enclosureGroupUri': 'EG:c7k_eg',
                   "serialNumberType": "Physical",
                   "iscsiInitiatorNameType": "AutoGenerated",
                   "macType": "Physical",
                   "wwnType": "Physical",
                   "name": "SP_2_gen10",
                   "description": "",
                   "affinity": "Bay",
                   "connectionSettings": {
                       "connections": []},
                   "boot": {
                       "manageBoot": False},
                   "bootMode": {
                       "manageMode": True,
                       "mode": "UEFIOptimized",
                       "secureBoot": "Unmanaged",
                       "pxeBootPolicy": "Auto"},
                   "firmware": {
                       "manageFirmware": False,
                       "firmwareBaselineUri": "",
                       "forceInstallFirmware": False,
                       "firmwareInstallType": None,
                       "firmwareScheduleDateTime": "",
                       "firmwareActivationType": "Immediate"},
                   "bios": {
                       "manageBios": True,
                       "overriddenSettings": []},
                   "hideUnusedFlexNics": True,
                   "iscsiInitiatorName": "",
                   "osDeploymentSettings": None,
                   "localStorage": {
                       "sasLogicalJBODs": [],
                       "controllers": []},
                   "sanStorage": None,
                   "initialScopeUris": []
                   }]

c7k_SP_3_gen10 = [{"type": "ServerProfileV10",
                   "serverHardwareUri": "SH:" + c7k_host_name_gen10,
                   "serverHardwareTypeUri": "SHT:" + c7k_sht_gen10,
                   'enclosureGroupUri': 'EG:c7k_eg',
                   "serialNumberType": "Physical",
                   "iscsiInitiatorNameType": "AutoGenerated",
                   "macType": "Physical",
                   "wwnType": "Physical",
                   "name": "SP_3_gen10",
                   "description": "",
                   "affinity": "Bay",
                   "connectionSettings": {
                       "connections": []},
                   "boot": {
                       "manageBoot": False},
                   "bootMode": {
                       "manageMode": True,
                       "mode": "UEFIOptimized",
                       "secureBoot": "Unmanaged",
                       "pxeBootPolicy": "Auto"},
                   "firmware": {
                       "manageFirmware": False,
                       "firmwareBaselineUri": "",
                       "forceInstallFirmware": False,
                       "firmwareInstallType": None,
                       "firmwareScheduleDateTime": "",
                       "firmwareActivationType": "Immediate"},
                   "bios": {
                       "manageBios": True,
                       "overriddenSettings": [{"id": "AsrStatus",
                                               "value": "Disabled"}, ],
                       #                                      {"id": "AdvancedMemProtection",
                       #                                       "value": "OnlineSpareAdvancedEcc"},
                       #                                      {"id": "MemRefreshRate",
                       #                                       "value": "Refreshx2"},
                       #                                      {"id": "PersistentMemBackupPowerPolicy",
                       #                                       "value": "BootWithoutBackupPower"}],
                       "reapplyState": "NotApplying"},
                   "hideUnusedFlexNics": True,
                   "iscsiInitiatorName": "",
                   "osDeploymentSettings": None,
                   "localStorage": {
                       "sasLogicalJBODs": [],
                       "controllers": []},
                   "sanStorage": None,
                   "initialScopeUris": []
                   }]

c7k_SP_1_gen9 = [{"type": "ServerProfileV10",
                  "serverHardwareUri": None,
                  "serverHardwareTypeUri": "SHT:" + c7k_sht_gen9,
                  'enclosureGroupUri': 'EG:c7k_eg',
                  "serialNumberType": "Physical",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "macType": "Physical",
                  "wwnType": "Physical",
                  "name": "SP_1_gen9",
                  "description": "",
                  "affinity": "Bay",
                  "connectionSettings": {
                      "connections": []},
                  "boot": {
                      "manageBoot": False},
                  "bootMode": {
                      "manageMode": True,
                      "mode": "UEFIOptimized",
                      "secureBoot": "Unmanaged",
                      "pxeBootPolicy": "Auto"},
                  "firmware": {
                      "manageFirmware": False,
                      "firmwareBaselineUri": "",
                      "forceInstallFirmware": False,
                      "firmwareInstallType": None,
                      "firmwareScheduleDateTime": "",
                      "firmwareActivationType": "Immediate"},
                  "bios": {
                      "manageBios": False},
                  "hideUnusedFlexNics": True,
                  "iscsiInitiatorName": "",
                  "osDeploymentSettings": None,
                  "localStorage": {
                      "sasLogicalJBODs": [],
                      "controllers": []},
                  "sanStorage": None,
                  "initialScopeUris": []
                  }]

c7k_SP_2_gen9 = [{"type": "ServerProfileV10",
                  "serverHardwareUri": None,
                  "serverHardwareTypeUri": "SHT:" + c7k_sht_gen9,
                  'enclosureGroupUri': 'EG:c7k_eg',
                  "serialNumberType": "Physical",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "macType": "Physical",
                  "wwnType": "Physical",
                  "name": "SP_2_gen9",
                  "description": "",
                  "affinity": "Bay",
                  "connectionSettings": {
                      "connections": []},
                  "boot": {
                      "manageBoot": False},
                  "bootMode": {
                      "manageMode": True,
                      "mode": "UEFIOptimized",
                      "secureBoot": "Unmanaged",
                      "pxeBootPolicy": "Auto"},
                  "firmware": {
                      "manageFirmware": False,
                      "firmwareBaselineUri": "",
                      "forceInstallFirmware": False,
                      "firmwareInstallType": None,
                      "firmwareScheduleDateTime": "",
                      "firmwareActivationType": "Immediate"},
                  "bios": {
                      "manageBios": True,
                      "overriddenSettings": []},
                  "hideUnusedFlexNics": True,
                  "iscsiInitiatorName": "",
                  "osDeploymentSettings": None,
                  "localStorage": {
                      "sasLogicalJBODs": [],
                      "controllers": []},
                  "sanStorage": None,
                  "initialScopeUris": []
                  }]

c7k_SP_3_gen9 = [{"type": "ServerProfileV10",
                  "serverHardwareUri": "SH:" + c7k_host_name_gen9,
                  "serverHardwareTypeUri": "SHT:" + c7k_sht_gen9,
                  'enclosureGroupUri': 'EG:c7k_eg',
                  "serialNumberType": "Physical",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "macType": "Physical",
                  "wwnType": "Physical",
                  "name": "SP_3_gen9",
                  "description": "",
                  "affinity": "Bay",
                  "connectionSettings": {
                      "connections": []},
                  "boot": {
                      "manageBoot": False},
                  "bootMode": {
                      "manageMode": True,
                      "mode": "UEFIOptimized",
                      "secureBoot": "Unmanaged",
                      "pxeBootPolicy": "Auto"},
                  "firmware": {
                      "manageFirmware": False,
                      "firmwareBaselineUri": "",
                      "forceInstallFirmware": False,
                      "firmwareInstallType": None,
                      "firmwareScheduleDateTime": "",
                      "firmwareActivationType": "Immediate"},
                  "bios": {
                      "manageBios": True,
                      "overriddenSettings": [{"id": "AsrStatus",
                                              "value": "Disabled"}, ],
                      #                                      {"id": "AdvancedMemProtection",
                      #                                       "value": "OnlineSpareAdvancedEcc"}],
                      "reapplyState": "NotApplying"},
                  "hideUnusedFlexNics": True,
                  "iscsiInitiatorName": "",
                  "osDeploymentSettings": None,
                  "localStorage": {
                      "sasLogicalJBODs": [],
                      "controllers": []},
                  "sanStorage": None,
                  "initialScopeUris": []
                  }]

c7k_SP_1_gen8 = [{"type": "ServerProfileV10",
                  "serverHardwareUri": None,
                  "serverHardwareTypeUri": "SHT:" + c7k_sht_gen8,
                  'enclosureGroupUri': 'EG:c7k_eg',
                  "serialNumberType": "Physical",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "macType": "Physical",
                  "wwnType": "Physical",
                  "name": "SP_1_gen8",
                  "description": "",
                  "affinity": "Bay",
                  "connectionSettings": {
                      "connections": []},
                  "boot": {
                      "manageBoot": False},
                  "bootMode": None,
                  "firmware": {
                      "manageFirmware": False,
                      "firmwareBaselineUri": "",
                      "forceInstallFirmware": False,
                      "firmwareInstallType": None,
                      "firmwareScheduleDateTime": "",
                      "firmwareActivationType": "Immediate"},
                  "bios": {
                      "manageBios": False},
                  "hideUnusedFlexNics": True,
                  "iscsiInitiatorName": "",
                  "osDeploymentSettings": None,
                  "localStorage": {
                      "sasLogicalJBODs": [],
                      "controllers": []},
                  "sanStorage": None,
                  "initialScopeUris": []
                  }]

c7k_SP_2_gen8 = [{"type": "ServerProfileV10",
                  "serverHardwareUri": None,
                  "serverHardwareTypeUri": "SHT:" + c7k_sht_gen8,
                  'enclosureGroupUri': 'EG:c7k_eg',
                  "serialNumberType": "Physical",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "macType": "Physical",
                  "wwnType": "Physical",
                  "name": "SP_2_gen8",
                  "description": "",
                  "affinity": "Bay",
                  "connectionSettings": {
                      "connections": []},
                  "boot": {
                      "manageBoot": False},
                  "bootMode": None,
                  "firmware": {
                      "manageFirmware": False,
                      "firmwareBaselineUri": "",
                      "forceInstallFirmware": False,
                      "firmwareInstallType": None,
                      "firmwareScheduleDateTime": "",
                      "firmwareActivationType": "Immediate"},
                  "bios": {
                      "manageBios": True,
                      "overriddenSettings": []},
                  "hideUnusedFlexNics": True,
                  "iscsiInitiatorName": "",
                  "osDeploymentSettings": None,
                  "localStorage": {
                      "sasLogicalJBODs": [],
                      "controllers": []},
                  "sanStorage": None,
                  "initialScopeUris": []
                  }]

c7k_SP_3_gen8 = [{"type": "ServerProfileV10",
                  "serverHardwareUri": "SH:" + c7k_host_name_gen8,
                  "serverHardwareTypeUri": "SHT:" + c7k_sht_gen8,
                  'enclosureGroupUri': 'EG:c7k_eg',
                  "serialNumberType": "Physical",
                  "iscsiInitiatorNameType": "AutoGenerated",
                  "macType": "Physical",
                  "wwnType": "Physical",
                  "name": "SP_3_gen8",
                  "description": "",
                  "affinity": "Bay",
                  "connectionSettings": {
                      "connections": []},
                  "boot": {
                      "manageBoot": False},
                  "bootMode": None,
                  "firmware": {
                      "manageFirmware": False,
                      "firmwareBaselineUri": "",
                      "forceInstallFirmware": False,
                      "firmwareInstallType": None,
                      "firmwareScheduleDateTime": "",
                      "firmwareActivationType": "Immediate"},
                  "bios": {
                      "manageBios": True,
                      #               "overriddenSettings": [{"id": "AsrStatus",
                      #                                       "value": "Disabled"},
                      #                                      {"id": "AdvancedMemProtection",
                      #                                       "value": "OnlineSpareAdvancedEcc"}],
                      "overriddenSettings": [{"id": "64",
                                              "value": "6"},
                                             {"id": "20",
                                              "value": "1"},
                                             {"id": "49",
                                              "value": "2"}],
                      "reapplyState": "NotApplying"},
                  "hideUnusedFlexNics": True,
                  "iscsiInitiatorName": "",
                  "osDeploymentSettings": None,
                  "localStorage": {
                      "sasLogicalJBODs": [],
                      "controllers": []},
                  "sanStorage": None,
                  "initialScopeUris": []
                  }]

c7k_SP_1s = [c7k_SP_1_gen10, c7k_SP_1_gen9, ]  # c7k_SP_1_gen8]
c7k_SP_2s = [c7k_SP_2_gen10, c7k_SP_2_gen9, ]  # c7k_SP_2_gen8]
c7k_SP_3s = [c7k_SP_3_gen10, c7k_SP_3_gen9, ]  # c7k_SP_3_gen8]
