import copy
from copy import deepcopy

admin_credentials = {
    'userName': 'Administrator',
    'password': 'wpsthpvse1'}
ilo_credentials = {
    'username': 'Administrator',
    'password': 'hpvse123'
}

# LIG, SASLIG, AND LE
LIG_NAME = 'LIG1'
SASLIG_NAME = 'SASLIG1'
EG_NAME = 'EG1'
LE_NAME = 'LE1'

# Enclosures
# Enclosures
ENC1 = 'CN754406XL'
ENC2 = 'CN754404R6'
ENC3 = 'CN754406WB'

ENCSHBAY8 = '%s, bay 8' % ENC2

# PROFILE1 SETTINGS
PROFILE1_NAME = 'SY 480 Gen 10 profile for iLO testing'
PROFILE1_SHT = 'SY 480 Gen10:1:HPE Smart Array P416ie-m SR G10:3:Synergy 3820C 10/20Gb CNA'
PROFILE1_SH = "SH:" + ENCSHBAY8
SERVER_PROFILE_TYPE = 'ServerProfileV10'
SERVER_PROFILE_TEMPLATE_TYPE = 'ServerProfileTemplateV6'
DL680_name = 'CN752806D4'

SERVER2 = ENCSHBAY8
NTS1_SPT_EG = EG_NAME
SHT_SERVER2 = 'SH:' + SERVER2
# PROFILE2 SETTINGS
DL480_name = 'CN770903L2'

server_profiles = {

    "type": SERVER_PROFILE_TYPE,
    "serverHardwareUri": "SH:" + ENCSHBAY8,
    "serverHardwareTypeUri": PROFILE1_SHT,
    "serialNumberType": "Virtual",
    "iscsiInitiatorNameType": "AutoGenerated",
    "macType": "Virtual",
    "wwnType": "Virtual",
    "name": "iLO Testing",
    "description": "",
    "affinity": "Bay",
    "connectionSettings": {
        "connections": []
    },
    "boot": {
        "manageBoot": True, "order": ["HardDisk"]
    },
    "bootMode": {
        "manageMode": True, "mode": "UEFI", "secureBoot": "Disabled", "pxeBootPolicy": "Auto"
    },
    "firmware": {
        "manageFirmware": False, "firmwareBaselineUri": "", "forceInstallFirmware": False, "firmwareInstallType": None, "firmwareScheduleDateTime": "", "firmwareActivationType": "Immediate"
    },
    "bios": {
        "manageBios": False, "overriddenSettings": []
    },
    "managementProcessor": {
        "manageMp": True,
        "mpSettings": [
            {
                "settingType": "AdministratorAccount",
                "args": {
                    "deleteAdministratorAccount": False,
                    "password": "Administrator"
                }
            }
        ]
    },
    "hideUnusedFlexNics": True,
    "iscsiInitiatorName": "",
    "osDeploymentSettings": None,
    "localStorage": {
        "sasLogicalJBODs": [], "controllers": []
    },
    "sanStorage": None
}

server_profile_temp = {
    "type": "ServerProfileTemplateV6",
    "serverProfileDescription": "",
    "serverHardwareTypeUri": 'SHT:' + SHT_SERVER2,
    "enclosureGroupUri": 'EG:' + NTS1_SPT_EG,
    "name": "iLO Testing Temp",
    "description": "",
    "affinity": "Bay",
    "connectionSettings": {
        "connections": [],
        "manageConnections": True
    },
    "boot": {
        "manageBoot": True,
        "order": [
            "HardDisk"
        ]
    },
    "bootMode": {
        "manageMode": True,
        "mode": "UEFI",
        "secureBoot": "Disabled",
        "pxeBootPolicy": "Auto"
    },
    "firmware": {
        "manageFirmware": False,
        "firmwareBaselineUri": "",
        "forceInstallFirmware": False,
        "firmwareInstallType": None,
        "firmwareActivationType": "Immediate"
    },
    "bios": {
        "manageBios": False,
        "overriddenSettings": []
    },
    "managementProcessor": {
        "manageMp": True,
        "mpSettings": [
            {
                "settingType": "AdministratorAccount",
                "args": {
                    "deleteAdministratorAccount": False,
                    "password": "hpvse123"
                }
            }
        ]
    },
    "hideUnusedFlexNics": True,
    "iscsiInitiatorNameType": "AutoGenerated",
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": []
    },
    "sanStorage": None,
    "osDeploymentSettings": None,
    "initialScopeUris": []
}

create_sp = [
    server_profiles.copy(),
]
# Negitive test set password to short expect it to fail
sp_short = deepcopy(server_profiles)
sp_short["managementProcessor"]["mpSettings"][0]["args"]["password"] = "admin"

edit_sp_short = [
    {
        'keyword': 'Edit Server Profile',
        'argument': sp_short.copy(),
        'taskState': 'Error',
        'errorMessage': 'ILO_PASSWORD_TO_SHORT'
    },

]

sp_long = deepcopy(server_profiles)
sp_long["managementProcessor"]["mpSettings"][0]["args"]["password"] = "Administratorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"

edit_sp_Long = [
    {
        'keyword': 'Edit Server Profile',
        'argument': sp_long.copy(),
        'taskState': 'Error',
        'errorMessage': 'ILO_PASSWORD_TO_LONG'
    },
]
# copy server profile but set the iLO admin account to delete
edit_sp_delete = deepcopy(server_profiles)
edit_sp_delete["managementProcessor"]["mpSettings"][0]["args"]["deleteAdministratorAccount"] = True

# restore iLO account and password
edit_sp_restore = deepcopy(server_profiles)
edit_sp_restore["managementProcessor"]["mpSettings"][0]["args"]["password"] = "hpvse123"


create_spt = [
    copy.deepcopy(server_profile_temp)
]

edit_sp_valid_password = [

    copy.deepcopy(edit_sp_restore),
]

edit_sp_delete_admin = [

    copy.deepcopy(edit_sp_delete),
]
del edit_sp_delete_admin[0]["managementProcessor"]["mpSettings"][0]["args"]["password"]

# Profile templates
dynamic_profile_templates_name_pwd = ["spt_short", "spt_admnistrtorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"]
dynamic_profile_templates = []
for profile in dynamic_profile_templates_name_pwd:
    x, pwd = profile.split('_')
    server_profile_temp["managementProcessor"]["mpSettings"][0]["args"]["password"] = pwd
    exec("%s= deepcopy(server_profile_temp)" % profile)
    dynamic_profile_templates.append(globals()[profile])

edit_spt_short_long = [
    {
        'keyword': 'Edit Server Profile Template',
        'argument': dynamic_profile_templates[0],
        'taskState': 'Error',
        'errorMessage': 'ILO_PASSWORD_TO_SHORT'
    },
    {
        'keyword': 'Edit Server Profile Template',
        'argument': dynamic_profile_templates[1],
        'taskState': 'Error',
        'errorMessage': 'ILO_PASSWORD_TO_LONG'
    }
]