#from winnt import NULL
from requests.api import patch

goldenimage = [{'name': 'AB_GoldenImage_ab',
                'description': 'goldenimage',
                'file': "valid_file"}]

planscript = [{"type": "PlanScript",
               "description": "PS 0",
               "name": "AB_mount_script",
               "hpProvided": "false",
               "planType": "General",
               "content": "# (C) Copyright 2015-2015 Hewlett-Packard Development Company, L.P.\n# Script to mount disk in libguesfs virtual appliance for personalizaiton or generalization\nmount /dev/sda5 /\n\n\n# creating tmp dir at local filesystem\n!mkdir -p ./onetime\n!mkdir -p ./state/local\n\n# copying required files for personalization/generalization to local filesysystem\n-copy-out /onetime.tgz .\n-copy-out /state.tgz .\n-copy-out /boot.cfg .\n\n# trying to findout whether onetime.tgz will be picked up during booting or state.tgz will be picked\n# based on that we can process either onetime.tgz or state.tgz for personalization/generalization\n\n-!grep \"onetime.tgz\"  ./boot.cfg >./onetime_found\n-!grep \"state.tgz\" ./boot.cfg > ./state_found"},

              {"type": "PlanScript",
               "description": "ps 1",
               "name": "AB_planscript_for_ab",
               "hpProvided": "false",
               "planType": "deploy",
               "content": "# personalize NIC script \n# (C) Copyright 2015-2015 Hewlett-Packard Development Company, L.P.\n# script to personalize an ESXi image\n# --- set hostname, optionally, enable esx shell, enable ssh, have an extra vmnic bonded\n\n!if [ -s  \"onetime_found\" ]; \\\nthen \\\ncd  onetime; \\\ntar xvpzf ../onetime.tgz; \\\necho esxcli system hostname set -H \"@hostname:esxi@\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard uplink add --uplink-name=vmnic1 --vswitch-name=vSwitch0\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"services.sh restart\" >> etc/rc.local.d/local.sh; \\\nchmod 777   etc/rc.local.d/local.sh; \\\ntar cvpzf ../onetime.tgz *; \\\nelse \\\ncd state; \\\ntar xvpzf ../state.tgz; \\\ncd local; \\\ntar xvpzf ../local.tgz; \\\nmkdir -p etc/rc.local.d; \\\necho esxcli system hostname set -H \"@hostname:esxi@\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard uplink add --uplink-name=vmnic1 --vswitch-name=vSwitch0\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"services.sh restart\" >> etc/rc.local.d/local.sh; \\\nchmod 777   etc/rc.local.d/local.sh; \\\ntar cvpzf ../local.tgz *; \\\ncd ../; \\\ntar cvpzf ../state.tgz local.tgz; \\\ntouch  ../state.tgz; \\\nfi"},

              {"type": "PlanScript",
               "description": "ps 2",
               "name": "AB_umount_script",
               "hpProvided": 'false',
               "planType": "General",
               "content": "-copy-in onetime.tgz /\n-copy-in state.tgz /\numount /"},

              {"type": "PlanScript",
               "description": "ps 3",
               "name": "AB_mount_ps",
               "hpProvided": "false",
               "planType": "General",
               "content": "# (C) Copyright 2015-2015 Hewlett-Packard Development Company, L.P.\n# Script to mount disk in libguesfs virtual appliance for personalizaiton or generalization\nmount /dev/sda5 /\n\n\n# creating tmp dir at local filesystem\n!mkdir -p ./onetime\n!mkdir -p ./state/local\n\n# copying required files for personalization/generalization to local filesysystem\n-copy-out /onetime.tgz .\n-copy-out /state.tgz .\n-copy-out /boot.cfg .\n\n# trying to findout whether onetime.tgz will be picked up during booting or state.tgz will be picked\n# based on that we can process either onetime.tgz or state.tgz for personalization/generalization\n\n-!grep \"onetime.tgz\"  ./boot.cfg >./onetime_found\n-!grep \"state.tgz\" ./boot.cfg > ./state_found"},

              {"type": "PlanScript",
               "description": "ps 4",
               "name": "AB_personalizeAll_ps",
               "hpProvided": "false",
               "planType": "deploy",
               "content": "# personalize NIC script\n# (C) Copyright 2015-2015 Hewlett-Packard Development Company, L.P.\n# script to personalize an ESXi image\n# --- set hostname, add an extra NIC optionally, enable esx shell, enable ssh, \n\n!if [ -s  \"onetime_found\" ]; \\\nthen \\\ncd  onetime; \\\ntar xvpzf ../onetime.tgz; \\\necho esxcli system hostname set -H \"@hostname:esxi@\" >> etc/rc.local.d/local.sh; \\\necho esxcli system hostname set -d \"@DomainName:hpecorp.net@\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network nic list >> test.txt \" >> etc/rc.local.d/local.sh; \\\necho \"VMNIC=\\$(grep -i @MACMGMT.mac:1234@ test.txt | awk '\\''{print \\$1}'\\'')\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard add --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard portgroup add --portgroup-name=ManangementNetwork1 --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard uplink add --uplink-name=\\${VMNIC} --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip interface add --interface-name=vmk1 --portgroup-name=ManangementNetwork1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip interface ipv4 set --interface-name=vmk1 --ipv4=@MACMGMT.ipaddress:15.212.168.184@ --netmask=@MACMGMT.netmask:255.255.252.0@ --type=static\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip route ipv4 add --gateway @MACMGMT.gateway:15.212.168.1@ --network default\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"services.sh restart\" >> etc/rc.local.d/local.sh; \\\nchmod 777   etc/rc.local.d/local.sh; \\\ntar cvpzf ../onetime.tgz *; \\\nelse \\\ncd state; \\\ntar xvpzf ../state.tgz; \\\ncd local; \\\ntar xvpzf ../local.tgz; \\\nmkdir -p etc/rc.local.d; \\\necho esxcli system hostname set -H \"@hostname:esxi@\" >> etc/rc.local.d/local.sh; \\\necho esxcli system hostname set -d \"@DomainName:hpecorp.net@\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network nic list >> test.txt \" >> etc/rc.local.d/local.sh; \\\necho \"VMNIC=\\$(grep -i @MACMGMT.mac:1234@ test.txt | awk '\\''{print \\$1}'\\'')\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard add --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard portgroup add --portgroup-name=ManangementNetwork1 --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard uplink add --uplink-name=\\${VMNIC} --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip interface add --interface-name=vmk1 --portgroup-name=ManangementNetwork1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip interface ipv4 set --interface-name=vmk1 --ipv4=@MACMGMT.ipaddress:15.212.168.184@ --netmask=@MACMGMT.netmask:255.255.252.0@ --type=static\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip route ipv4 add --gateway @MACMGMT.gateway:15.212.168.1@ --network default\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"services.sh restart\" >> etc/rc.local.d/local.sh; \\\nchmod 777   etc/rc.local.d/local.sh; \\\ntar cvpzf ../local.tgz *; \\\ncd ../; \\\ntar cvpzf ../state.tgz local.tgz; \\\ntouch  ../state.tgz; \\\nfi"},

              {"type": "PlanScript",
               "description": "ps 5",
               "name": "AB_umount_ps",
               "hpProvided": 'false',
               "planType": "General",
               "content": "-copy-in onetime.tgz /\n-copy-in state.tgz /\numount /"},

              {"type": "PlanScript",
               "description": "ps 6",
               "name": "AB_nir1",
               "hpProvided": 'false',
               "planType": "General",
               "content": "-copy-in onetime.tgz /\n-copy-in state.tgz /\numount /"},

              {"type": "PlanScript",
               "description": "ps 7",
               "name": "AB_nir2",
               "hpProvided": 'false',
               "planType": "deploy",
               "content": "-copy-in onetime.tgz /\n-copy-in state.tgz /\numount /"},

              {"type": "PlanScript",
               "description": "ps 8",
               "name": "AB_ps_empty",
               "hpProvided": 'true',
               "planType": "deploy",
               "content": "echo \"@volumesize:20480@ >/dev/null\""}]

buildplan = [{'type': 'OeBuildPlanV5',
              'customAttributes': [{'constraints': '{}',
                                    'description': '',
                                    'name': 'hostname',
                                    'value': 'esxi',
                                    'type': 'string'}],
              'buildStep': [{'planScriptUri': 'AB_mount_script',
                             'parameters': None,
                             'serialNumber': '1'},
                            {'planScriptUri': 'AB_planscript_for_ab',
                             'parameters': None,
                             'serialNumber': '2'},
                            {'planScriptUri': 'AB_umount_script',
                             'parameters': None,
                             'serialNumber': '3'}],
              'hpProvided': False,
              'oeBuildPlanType': 'deploy',
              'description': 'Build plan 0',
              'name': 'AB_buildplan_for_ab'},

             {"type": "OeBuildPlanV5",
              "customAttributes": [{"constraints": "{\"ipv4static\":true,\"ipv4dhcp\":false,\"parameters\":[\"gateway\",\"ipaddress\",\"mac\",\"netmask\"]}",
                                    "description": "",
                                    "name": "MACMGMT",
                                    "value": "",
                                    "type": "nic"},
                                   {"constraints": "{}",
                                    "description": "",
                                    "name": "DomainName",
                                    "value": "hpecorp.net",
                                    "type": "string"},
                                   {"constraints": "{}",
                                    "description": "",
                                    "name": "hostname",
                                    "value": "esxi",
                                    "type": "string"}],
              "buildStep": [{"planScriptUri": "AB_mount_ps",
                             "parameters": None,
                             "serialNumber": "1"},
                            {"planScriptUri": "AB_personalizeAll_ps",
                             "parameters": None,
                             "serialNumber": "2"},
                            {"planScriptUri": "AB_umount_ps",
                             "parameters": None,
                             "serialNumber": "3"}],
              "hpProvided": False,
              "oeBuildPlanType": "deploy",
              "description": "Build plan 1",
              "name": "AB_personalizeAll_bp"},

             {"type": "OeBuildPlanV5",
              "customAttributes": [{"constraints": "{\"ipv4static\":true,\"ipv4dhcp\":false,\"parameters\":[\"gateway\",\"ipaddress\",\"mac\",\"netmask\"]}",
                                    "description": "",
                                    "name": "MACMGMT",
                                    "value": "",
                                    "type": "nic"},
                                   {"constraints": "{}",
                                    "description": "",
                                    "name": "DomainName",
                                    "value": "hpecorp.net",
                                    "type": "string"},
                                   {"constraints": "{}",
                                    "description": "",
                                    "name": "hostname",
                                    "value": "esxi",
                                    "type": "string"}],
              "buildStep": [{"planScriptUri": "AB_personalizeAll_ps",
                             "parameters": None,
                             "serialNumber": "1"}],
              "hpProvided": False,
              "oeBuildPlanType": "deploy",
              "description": "Build plan 1",
              "name": "AB_bp_empty"}]

deploymentplan = [{"type": "OEDeploymentPlanV5",
                   "hpProvided": False,
                   "customAttributes": [{"visible": True,
                                         "constraints": "{}",
                                         "editable": True,
                                         "description": "",
                                         "name": "hostname",
                                         "value": "esxi",
                                         "type": "string"}],
                   "goldenImageURI": "AB_GoldenImage_ab",
                   "oeBuildPlanURI": "AB_buildplan_for_ab",
                   "category": "oe-deployment-plans",
                   "description": "",
                   "name": "AB_deploymentplan_for_ab",
                   },

                  {"type": "OEDeploymentPlanV5",
                   "hpProvided": False,
                   "customAttributes": [{"visible": True,
                                         "constraints": "{}",
                                         "editable": True,
                                         "description": "",
                                         "name": "hostname",
                                         "value": "esxi",
                                         "type": "string"},
                                        {"visible": True,
                                         "constraints": "{\"ipv4static\":true,\"ipv4dhcp\":false,\"parameters\":[\"gateway\",\"ipaddress\",\"mac\",\"netmask\"]}",
                                         "editable": True,
                                         "description": "",
                                         "name": "MACMGMT",
                                         "value": "",
                                         "type": "nic"},
                                        {"visible": True,
                                         "constraints": "{}",
                                         "editable": True,
                                         "description": "",
                                         "name": "DomainName",
                                         "value": "hpecorp.net",
                                         "type": "string"}],
                   "goldenImageURI": "AB_GoldenImage_ab",
                   "oeBuildPlanURI": "AB_personalizeAll_bp",
                   "category": "oe-deployment-plans",
                   "description": "# --- set hostname, add an extra NIC optionally, enable esx shell, enable ssh,",
                   "name": "AB_esxi6_dp"},

                  {"type": "OEDeploymentPlanV5",
                   "hpProvided": False,
                   "customAttributes": [{"visible": True,
                                         "constraints": "{}",
                                         "editable": True,
                                         "description": "",
                                         "name": "hostname",
                                         "value": "esxi",
                                         "type": "string"},
                                        {"visible": True,
                                         "constraints": "{\"ipv4static\":true,\"ipv4dhcp\":false,\"parameters\":[\"gateway\",\"ipaddress\",\"mac\",\"netmask\"]}",
                                         "editable": True,
                                         "description": "",
                                         "name": "MACMGMT",
                                         "value": "",
                                         "type": "nic"},
                                        {"visible": True,
                                         "constraints": "{}",
                                         "editable": True,
                                         "description": "",
                                         "name": "DomainName",
                                         "value": "hpecorp.net",
                                         "type": "string"}],
                   "goldenImageURI": "",
                   "oeBuildPlanURI": "AB_personalizeAll_bp",
                   "category": "oe-deployment-plans",
                   "description": "dp without GI",
                   "name": "AB_emptyDP"}]


artifactbundle = [{'name': '!@#$#@#$@##$@#$',
                   'description': 'ab with special Character',
                   'deploymentPlans': [{'resourceUri': 'AB_deploymentplan_for_ab',
                                        'readOnly': False}]},

                  {'name': '',
                   'description': 'ab with blank name',
                   'deploymentPlans': [{'resourceUri': 'AB_deploymentplan_for_ab',
                                        'readOnly': False}]},

                  {'name': 'ab without any artifacts',
                   'description': 'ab without any artifacts'},

                  {'name': '0ab_automate_1',
                   'description': '3ab with deploymentplan only',
                   'deploymentPlans': [{'resourceUri': 'AB_deploymentplan_for_ab',
                                        'readOnly': True}]},

                  {'name': 'One',
                   'description': '4ab with buildplan only',
                   'buildPlans': [{'resourceUri': 'AB_buildplan_for_ab',
                                   'readOnly': False}]},

                  {'name': '2',
                   'description': '5ab to get',
                   'planScripts': [{'resourceUri': 'AB_ps_empty',
                                    'readOnly': False}]},

                  {'name': 'bundle',
                   'description': '6ab without any artifacts',
                   'goldenImages': [{'resourceUri': 'AB_GoldenImage_ab',
                                     'readOnly': False}],
                   'planScripts': [{'resourceUri': 'AB_ps_empty',
                                    'readOnly': False}],
                   'buildPlans': [{'resourceUri': 'AB_bp_empty',
                                   'readOnly': False}],
                   'deploymentPlans': [{'resourceUri': 'AB_deploymentplan_for_ab',
                                        'readOnly': False}]},

                  {'name': 'bundle2',
                   'description': '7ab without any artifacts',
                   'deploymentPlans': [{'resourceUri': 'AB_deploymentplan_for_ab',
                                        'readOnly': False},
                                       {'resourceUri': 'AB_esxi6_dp',
                                        'readOnly': False}]},

                  {'name': 'bundle-file',
                   'description': '8ab without any artifacts',
                   'goldenImages': [{'resourceUri': 'AB_GoldenImage_ab',
                                     'readOnly': False}],
                   'planScripts': [{'resourceUri': 'AB_nir1',
                                    'readOnly': False},
                                   {'resourceUri': 'AB_nir2',
                                    'readOnly': False}],
                   'buildPlans': [{'resourceUri': 'AB_buildplan_for_ab',
                                   'readOnly': False},
                                  {'resourceUri': 'AB_bp_empty',
                                   'readOnly': False}]},

                  {'name': 'cl ESXi Test Plan1',
                   'description': '9ab without GI',
                   'deploymentPlans': [{'resourceUri': 'AB_esxi6_dp',
                                        'readOnly': False}]},

                  {'name': 'CL RHEL Test Deployment Plan1',
                   'description': '10ab to get',
                   'planScripts': [{'resourceUri': 'AB_ps_empty',
                                    'readOnly': False}]},

                  {'name': 'eleven',
                   'description': '11ab to get',
                   'planScripts': [{'resourceUri': 'AB_ps_empty',
                                    'readOnly': False}]},

                  {'name': 'RHEL-7.2-artifact-bundle',
                   'description': '12ab to get',
                   'planScripts': [{'resourceUri': 'AB_ps_empty',
                                    'readOnly': True}]},

                  {'name': 'AB',#OVF1047_TC33
                   'description': '13ab without any artifacts',
                   'planScripts': [{'resourceUri': 'AB_mount_ps',
                                    'readOnly': False},
                                   {'resourceUri': 'AB_personalizeAll_ps',
                                    'readOnly': False},
                                   {'resourceUri': 'AB_umount_ps',
                                    'readOnly': False}],
                   'buildPlans': [{'resourceUri': 'AB_personalizeAll_bp',
                                   'readOnly': False}],
                   'deploymentPlans': [{'resourceUri': 'AB_emptyDP',
                                        'readOnly': False}]},

                  {'name': 'AB1',#OVF1047_TC33
                   'description': '14ab without any artifacts',
                   'planScripts': [{'resourceUri': 'AB_mount_ps',
                                    'readOnly': False},
                                   {'resourceUri': 'AB_personalizeAll_ps',
                                    'readOnly': False},
                                   {'resourceUri': 'AB_umount_ps',
                                    'readOnly': False}],
                   'buildPlans': [{'resourceUri': 'AB_personalizeAll_bp',
                                   'readOnly': False}],
                   'deploymentPlans': [{'resourceUri': 'AB_emptyDP',
                                        'readOnly': False}]}]

artifactbundle_update = [{'name': 'ab_automate_update',
                          'type': 'ArtifactsBundle'},

                         {'name': '!@#$#$',
                          'type': 'ArtifactsBundle'},

                         {'name': '',
                          'type': 'ArtifactsBundle'},

                         {'name': '2',
                          'type': 'ArtifactsBundle'},

                         {'name': 'esxi6AB',
                          'type': 'ArtifactsBundle'},

                         {'name': '1234',
                          'type': 'ArtifactsBundle'}]

artifactbundle_add = [{'name': '/root/Goldenimage/ab_download.zip'},
                      {'name': '/root/Goldenimage/invalid_file.zip'},# OVF1047_TC26
                      {'name': '/root/Goldenimage/invalid_file_type.txt'},#OVF1047_TC35
                      {'name': 'invalid_file'},
                      {'name': '/root/Goldenimage/RHEL.zip'},#OVF1047_TC32
                      {'name': 'RHEL'}]#OVF1047_TC32

artifactbundle_extract = {'name': 'ab_download'}


#planscript update is used for OVF1047_TC34
planscript_update = [{
            "type": "PlanScript",
            "description": "ps3 for update",
            "name": "AB_mount_ps",
            "hpProvided": "false",
            "planType": "deploy",
            "content": "#CONTENT UPDATED \n#CONTENT UPDATED \n#CONTENT UPDATED \n# (C) Copyright 2015-2015 Hewlett-Packard Development Company, L.P.\n# Script to mount disk in libguesfs virtual appliance for personalizaiton or generalization\nmount /dev/sda5 /\n\n\n# creating tmp dir at local filesystem\n!mkdir -p ./onetime\n!mkdir -p ./state/local\n\n# copying required files for personalization/generalization to local filesysystem\n-copy-out /onetime.tgz .\n-copy-out /state.tgz .\n-copy-out /boot.cfg .\n\n# trying to findout whether onetime.tgz will be picked up during booting or state.tgz will be picked\n# based on that we can process either onetime.tgz or state.tgz for personalization/generalization\n\n-!grep \"onetime.tgz\"  ./boot.cfg >./onetime_found\n-!grep \"state.tgz\" ./boot.cfg > ./state_found"},

            {"type": "PlanScript",
            "description": "ps4 for update",
            "name": "AB_personalizeAll_ps",
            "hpProvided": "true",
            "planType": "deploy",
            "content": "#CONTENT UPDATED \n#CONTENT UPDATED \n#CONTENT UPDATED \n# personalize NIC script\n# (C) Copyright 2015-2015 Hewlett-Packard Development Company, L.P.\n# script to personalize an ESXi image\n# --- set hostname, add an extra NIC optionally, enable esx shell, enable ssh, \n\n!if [ -s  \"onetime_found\" ]; \\\nthen \\\ncd  onetime; \\\ntar xvpzf ../onetime.tgz; \\\necho esxcli system hostname set -H \"@hostname:esxi@\" >> etc/rc.local.d/local.sh; \\\necho esxcli system hostname set -d \"@DomainName:hpecorp.net@\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network nic list >> test.txt \" >> etc/rc.local.d/local.sh; \\\necho \"VMNIC=\\$(grep -i @MACMGMT.mac:1234@ test.txt | awk '\\''{print \\$1}'\\'')\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard add --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard portgroup add --portgroup-name=ManangementNetwork1 --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard uplink add --uplink-name=\\${VMNIC} --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip interface add --interface-name=vmk1 --portgroup-name=ManangementNetwork1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip interface ipv4 set --interface-name=vmk1 --ipv4=@MACMGMT.ipaddress:15.212.168.184@ --netmask=@MACMGMT.netmask:255.255.252.0@ --type=static\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip route ipv4 add --gateway @MACMGMT.gateway:15.212.168.1@ --network default\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"services.sh restart\" >> etc/rc.local.d/local.sh; \\\nchmod 777   etc/rc.local.d/local.sh; \\\ntar cvpzf ../onetime.tgz *; \\\nelse \\\ncd state; \\\ntar xvpzf ../state.tgz; \\\ncd local; \\\ntar xvpzf ../local.tgz; \\\nmkdir -p etc/rc.local.d; \\\necho esxcli system hostname set -H \"@hostname:esxi@\" >> etc/rc.local.d/local.sh; \\\necho esxcli system hostname set -d \"@DomainName:hpecorp.net@\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network nic list >> test.txt \" >> etc/rc.local.d/local.sh; \\\necho \"VMNIC=\\$(grep -i @MACMGMT.mac:1234@ test.txt | awk '\\''{print \\$1}'\\'')\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard add --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard portgroup add --portgroup-name=ManangementNetwork1 --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network vswitch standard uplink add --uplink-name=\\${VMNIC} --vswitch-name=vSwitch1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip interface add --interface-name=vmk1 --portgroup-name=ManangementNetwork1\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip interface ipv4 set --interface-name=vmk1 --ipv4=@MACMGMT.ipaddress:15.212.168.184@ --netmask=@MACMGMT.netmask:255.255.252.0@ --type=static\" >> etc/rc.local.d/local.sh; \\\necho \"esxcli network ip route ipv4 add --gateway @MACMGMT.gateway:15.212.168.1@ --network default\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_esx_shell\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/enable_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"vim-cmd hostsvc/start_ssh\" >> etc/rc.local.d/local.sh; \\\necho \"services.sh restart\" >> etc/rc.local.d/local.sh; \\\nchmod 777   etc/rc.local.d/local.sh; \\\ntar cvpzf ../local.tgz *; \\\ncd ../; \\\ntar cvpzf ../state.tgz local.tgz; \\\ntouch  ../state.tgz; \\\nfi"}]
