# (C) Copyright 2013 Hewlett-Packard Development Company, L.P.
'''
This file contains all  element ID on Fusion logical interconnect page or screen
'''


class FusionLogicalInterconnectsPage(object):
    ID_PAGE_LABEL = "//div[@class='hp-page-label']/h1[text()='Logical Interconnects']"
    # ACTION MENU
    ID_ACTION_MAIN_BTN = "xpath=//label[text()='Actions']"
    ID_MENU_ACTION_LS_EDIT = "id=cic-logicalswitch-edit-action"
    ID_MENU_ACTION_UPDATE_FIRMWARE = "link=Update firmware"
    ID_MENU_ACTION_REDISTR_LOGIN = "id=cic-logicalswitch-redistribute-action"
    ID_MENU_ACTION_REAPPLY_CONF = "xpath=//*[@id='cic-logicalswitch-reapply-action']/a"
    ID_MENU_ACTION_CREATE_SUPPORT_DUMP = "id=cic-logicalswitch-supportdump"
    # EDIT LS
    ID_INPUT_INTERVAL_BW_SAMPLES = "id=cic-logicalswitch-switch-edit-interval"
    ID_INPUT_TOTAL_NUMBER_SAMPLES = "id=cic-logicalswitch-switch-edit-samples"
    ID_BTN_OK_LS_EDIT = "id=cic-logicalswitch-edit-update"
    # UPDATE FIRMWARE
    ID_COMBO_FIRMWARE_BASELINE = "//label[text()='Firmware baseline']/following-sibling::a"
    ID_COMBO_UPDATE_ACTION = "//label[text()='Update action']/following-sibling::a"
    ID_CHKBOX_FORCE_FIRMWARE_UPDATE = "id=cic-logicalswitches-updfw-forceupdate"
    ID_BTN_OK_FIRWARE_UPDATE = "id=cic-logicalswitches-updfw-ok"
    ID_BTN_CANCEL_FIRMWARE_UPDATE = "id=cic-logicalswitches-updfw-cancel"
    ID_BTN_YES_UPDATE_CONFIRMATION = "id=cic-logicalswitches-activatefw-ok"
    ID_BTN_CANCEL_CONFIRMATION = "id=cic-logicalswitches-activatefw-cancel"
    # CREATE SUPPORT DUMP
    ID_BTN_YES_CREATE_SUPPORT_DUMP = "id=cic-logicalswitch-create-dump"
    ID_BTN_CANCEL_SUPPORT_DUMP_DIALOGUE = "id=cic-logicalswitch-cancel-dump"
    # LIST LS
    ID_ELEMENT_LOGICAL_SWITCH_BASE = "//td[text()='%s']"  # Replace %s with Logical Switch Name
    # View
    ID_COMBO_MENU_VIEW = "css=div.hp-value"
    ID_LINK_GENERAL = "id=cic-logicalswitch-general-selector"
    ID_LINK_FIRMWARE = "link=Firmware"
    ID_LINK_SWITCH = "id=cic-logicalswitch-switch-selector"
    ID_LINK_LOGICAL_UPLINKS = "id=cic-logicalswitch-uplink-selector"
    ID_LINK_ALERTS = "id=cic-logicalswitch-alerts-selector"
    ID_LINK_RELATED = "link=Related"
    ID_MENU_LINK_LOGICAL_INTERCONNECTS = "link=Logical Interconnects"
    ID_ELEMENT_LI_SELECT_NAME = "xpath=//*[@id='cic-logicalswitch-master-table']//td[contains(text(),'%s')]"
    ID_LI_STATUS_OK = "xpath=//*[@id='cic-logicalswitch-details-status' and @class='crm-logicalswitch-data hp-status hp-status-ok']"
    ID_LI_STATUS_ERROR = "xpath=//*[@id='cic-logicalswitch-details-status' and @class='crm-logicalswitch-data hp-status hp-status-error']"
    ID_ERROR_WARN_MSG = "xpath=//*[@id='hp-page-notifications']/div[1]/header/div[2]/p/span"
    ID_ACTVITY_SUPPORT_DUMP = "css=nav.hp-sub-nav > div.hp-sidebar-control > div.hp-pin-right"
    ID_CLICK_ACTIVITY = "xpath = .//*[@id='hp-flyout-activities']/li/div[@class='hp-brief']/div[@class='hp-status hp-status-changing']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    ID_TIMESTAMP_SUPPORT_DUMP = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-changing']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    ID_VALIDATE_SUCCESS = "xpath = //header[@class='hp-active']/div[@class='hp-status hp-status-ok']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"  # %s replace with name of interconnect
    ID_SUCCESS_SUPPORT_DUMP = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-ok']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    ID_ERROR_SUPPORT_DUMP = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-error']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    # for update firmware tbird
    ID_SELECT_FORCE_OPTION = "//*[@id='cic-logicalswitches-updfw-forceupdate']"
    ID_SELECT_PARALLEL_UPDATE = "//*[@id='cic-logicalswitches-updfw-activation-parallel']"
    ID_SELECT_ORCHESTRATED_UPDATE = "//*[@id='cic-logicalswitches-updfw-activation-orchestrated']"
    ID_NEW_UPDATE_STARTED = "xpath = .//*[@id='hp-page-notifications']/div[1]/header/div[@class='hp-message']/p/span[text()='Update firmware'][1]"

    ID_ACTIVITY_NEW_WARNING_DETAILS = "xpath = .//*[@id='hp-page-notifications']/div[1]/div/div[3]/div/div[3]/ol/li/div[1]/span/p/span"
    ID_ELEMENT_OVERVIEW_LOGICALINTERCONNECT = "xpath=//*[@id='cic-logicalswitch-panel-selector']/ol/li/ol/li/a[text()='Logical Interconnect']"
    ID_ACTIVITY_NEW_ERROR_DETAILS = "xpath= .//header[@class='hp-notification-summary']/div[@class='hp-status hp-status-error']/following-sibling::div[@class='hp-message']/p/span[text()='Update firmware']/following::Div[@class='hp-full']//div[@class='hp-notification-details']/div/p/span"
    ID_INTERCONNECT_ERROR_DETAILS = "xpath=  .//header[@class='hp-notification-summary']/div[@class='hp-status hp-status-error']/following-sibling::div[@class='hp-message']/p/span"

    # Update Firmware
    ID_CLICK_FIRMWARE_ACTIVITY = "xpath=//*[@id='hp-flyout-activities']/li/div[@class='hp-brief']"
    ID_UPDATE_WARNING_MSG = "xpath=//*[@id='hp-flyout-activities']/li/div[@class='hp-full']/div[@class='hp-details-container']//div[@class='hp-details']"
    ID_FIRMWARE_BASELINE = "xpath=.//*[@id='cic-logicalswitch-details-firmwareBaseline']"
    ID_MENU_LINK_LOGICAL_INTERCONNECTS = "link=Logical Interconnects"
    ID_ELEMENT_LI_SELECT_NAME = "//*[@id='cic-logicalswitch-master-table']/tbody/tr/td[text()='%s']"
    ID_LI_STATUS_OK = "//*[@id='cic-logicalswitch-details-status' and @class='crm-logicalswitch-data hp-status hp-status-ok']"
    ID_LI_STATUS_ERROR = "//*[@id='cic-logicalswitch-details-status' and @class='crm-logicalswitch-data hp-status hp-status-error']"
    ID_ERROR_WARN_MSG = "//*[@id='hp-page-notifications']//*/header//*/p/span"
    ID_UPDATE_ACTION = "xpath=.//*/fieldset/ol/li[1]/div/a"
    ID_SELECT_UPDATE_ACTION = "//form[@id='cic-logicalswitches-updfw-form']//li/span[text()='%s']"
    ID_UPDATE_FIRMWARE_BASELINE = "//*[@id='cic-logicalswitches-updfw-dropdown']/div"
    ID_GET_FIRMWAREBASELINE = "xpath = //div[@id='cic-logicalswitches-updfw-dropdown']/a/span[1]"
    ID_CLICK_UPDATE_FiRMWARE_FOR = "xpath =//*[@id='cic-logicalswitches-updfw-dropdown']/div/div/div"
    ID_CLICK_UPDATE_FIRMWARE_FOR_STAGE = "xpath =//form[@id='cic-logicalswitches-updfw-form']//div[@data-id='STAGE']"
    ID_ACTVITY_UPDATE_FIRMWARE = "xpath = .//*[@id='hp-activity-control']"
    ID_FIRMWARE_ERROR = "id=cic-logicalswitches-updfw-error"
    ID_ACTIVITY_BAR = "xpath = .//*[@id='hp-flyout-activities']/li/div[@class='hp-brief']/div[@class='hp-status hp-status-changing']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Update firmware']/following::div[text()='%s']"
    ID_UPDATE_SUCCESS = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-ok']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Update firmware']//following::a[text()='%s']"
    ID_UPDATE_WARNING = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-warning']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Update firmware']//following::a[text()='%s']"
    ID_UPDATE_PROGRESS = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-changing']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Update firmware']//following::a[text()='%s']"
    ID_UPDATE_FAILED = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-error']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Update firmware']//following::a[text()='%s']"
    ID_STATUS_OK = "xpath=//ol[@id='hp-flyout-activities']/li/div/header/div[@class='hp-status hp-status-ok']"
    ID_STATUS_CHANGING = "xpath=//ol[@id='hp-flyout-activities']/li/div/header/div[@class='hp-status hp-status-changing']"
    ID_VALIDATE_ACTIVATE_FIRMWARE = "xpath = .//*[@id='cic-logicalswitches-updfw-action-annotation' and text()='All firmware already activated']"
    # Reapply Configuration
    ID_LIC_LIST = "xpath =//div[@class='dataTables_scrollBody']/table/tbody/tr/td[2]"
    ID_LIC_NAME_BASE = "xpath =//table[@id='cic-logicalswitch-master-table']/tbody/tr/td[text()='%s']"
    ID_HEALTH_STATUS_ERROR = "xpath =//div[@id='hp-page-notifications']/div/header/div[@class='hp-status hp-status-error']"
    ID_CONFIGURE_FAILURE = "xpath = //span[text()='The stacking health has changed to disconnected.']"
    ID_HEALTH_STATUS_WARNING = "xpath =//div[@id='hp-page-notifications']/div/header/div[@class='hp-status hp-status-warning']"
    ID_WARNING_MSG = "xpath =//div[@id='hp-page-notifications']/div/header/div/p/span"
    ID_MENU_ACTION_UPDATE_FRM_GRP = "xpath =//li[@id='cic-logicalswitch-ufg-action']/a[text()='Update from group']"
    ID_UPDATE_FROM_GRP_DIALOG = "xpath =//div[@id='cic-logicalswitch-ufg-dialog']"
    ID_YES_UPDATE_LIC = "xpath =//button[@class='hp-ok hp-primary' and text()='Yes, update']"
    ID_HEALTH_STATUS_OK = "xpath =//div[@id='hp-page-notifications']/div/header/div[@class='hp-status hp-status-ok']"
    ID_UPDATE_FROM_GRP_MSG = "xpath =//div[@id='hp-page-notifications']/div/header/div/p/span[text()='Update from group']"
    ID_CONFIGURATION_SUCCESS_MSG = "xpath =//div[@id='hp-page-notifications']/div/header/div/p/span[text()='Configure logical-interconnect']"
    ID_ELEMENT_LIG_NAME = "xpath=//li/label[text()='Logical Interconnect Group']/following-sibling::div[@id='cic-logicalswitch-show-group']/a"
    ID_ELEMENT_LI_LABEL = "id=cic-logicalswitch-details-title"

    # EDIT Logical Interconnects
    ID_ELEMENT_EDIT_EDIT_LOGICAL_INTERCONNECTS = "//label[text()='Logical Interconnect']"
    ID_LINK_OVERIVEW = "xpath=//div[@id='cic-logicalswitch-panel-selector']/div[text()='Overview']"
    ID_LINK_INTERCONNECT_SETTINGS = "xpath=//li/a[@id='cic-logicalswitch-switch-ethernet-show-switch-settings-selector' and text()='Interconnect settings']"
    ID_ELEMENT_MAC_FAILOVER = "xpath=.//*[@id='cic-interconnect-settings-show-failover']"
    ID_ELEMENT_MAC_REFRESH_INTERVAL = "xpath=.//*[@id='cic-interconnect-settings-show-mac-interval']"
    ID_ELEMENT_IGMP_SNOOPING = "xpath=.//*[@id='cic-interconnect-settings-show-snooping']"
    ID_ELEMENT_IGMP_SNOOPING_INTERVAL = "xpath=.//*[@id='cic-interconnect-settings-show-igmp-interval']"
    ID_ELEMENT_INTERVAL_BETWEEN_SAMPLES = "xpath=//li/div[@id='cic-logicalswitch-switch-show-interval']"
    ID_ELEMENT_TOTAL_NUMBER_OF_SAMPLES = "id=cic-logicalswitch-switch-show-samples"
    ID_ELEMENT_SNMP = "xpath=//div/label[@id='cic-snmp-show-snmp']"
    ID_ELEMENT_SYSTEM_CONTACT = "xpath=//div/label[@id='cic-snmp-show-system-contact']"
    ID_ELEMENT_COMM_STRING = "xpath=//div/label[@id='cic-snmp-show-read-community']"
    ID_ELEMENT_SNMP_TRAP_DEST = "xpath=.//tr[descendant::td[contains(.,'%s')]]//td[1]"
    ID_ELEMENT_SNMP_COMM_STRING = "xpath=.//tr[descendant::td[contains(.,'%s')]]//td[2]"
    ID_ELEMENT_SNMP_FORMAT = "xpath=.//tr[descendant::td[contains(.,'%s')]]//td[3]"
    ID_ELEMENT_SNMP_SEVERITY = "xpath=.//tr[descendant::td[contains(.,'%s')]]//td[4]"
    ID_ELEMENT_SNMP_VCM = "xpath=.//tr[descendant::td[contains(.,'%s')]]//td[5]"
    ID_ELEMENT_SNMP_VCENET = "xpath=.//tr[descendant::td[contains(.,'%s')]]//td[6]"
    ID_ELEMENT_SNMP_VCFC = "xpath=.//tr[descendant::td[contains(.,'%s')]]//td[7]"
    ID_ELEMENT_SNMP_ACCESS = "xpath=.//tr[descendant::td[contains(.,'%s')]]//td[1]"
    ID_INPUT_SUBNET = "id=cic-snmp-add-access-address"
    ID_BUTTON_ADD_SNMP = "xpath=//div[@class='hp-form-controls']/input[@id='cic-snmp-access-add-button']"
    ID_BUTTON_ADD_PLUS_SNMP = ".//*[@id='cic-snmp-access-add-again-button']"
    ID_BUTTON_CANCEL_SNMP = "xpath=//div[@class='hp-form-controls']/a[@class='hp-button hp-cancel']"
    ID_ELEMENT_SNMP_SUBNET = "xpath=//tbody/tr/td[text()='%s']"
    ID_BUTTON_DELETE_SNMP = "//tbody/tr/td[text()='%s']/following-sibling::td[@class='hp-icon']/div[@class='hp-close']"
    ID_CHKBOX_CACHE_FAILOVER = "xpath=.//*[@id='cic-interconnect-settings-edit-failover']"
    ID_INPUT_REFRESHINTERVAL = "xpath=.//*[@id='cic-interconnect-settings-edit-mac-interval']"
    ID_CHKBOX_CACHE_IGMPSNOOPING = "xpath=.//*[@id='cic-interconnect-settings-edit-snooping']"
    ID_INPUT_IDLETTIMEINTERVAL = "xpath=.//*[@id='cic-interconnect-settings-edit-igmp-interval']"
    ID_INPUT_INTSAMPLES = "xpath=//*[@id='cic-logicalswitch-switch-edit-interval']"
    ID_INPUT_TOTALINTSAMPLES = "xpath=//*[@id='cic-logicalswitch-switch-edit-samples']"
    ID_ELEMENT_SNMP = "xpath=//*[@id='cic-snmp-general-snmp-hpToggle']/ol/li[text()='%s']"
    ID_INPUT_SNMP_SYS_CON = "xpath=//*[@id='cic-snmp-general-system-contact']"
    ID_INPUT_SNMP_COMMUNITY = "//*[@id='cic-snmp-general-read-community']"
    ID_ELEMENT_UPLINK_CLOSE = "xpath=.//li[descendant::Div//label//div[text()='%s']]/div/div[@class='hp-edit']/following-sibling::div"
    # ID_ELEMENT_UPLINK_NAME = "xpath=.//label[@class='three-dots-uplink-set' and div[text()='%s']/following::Div[@class='hp-controls']]"
    ID_ELEMENT_UPLINK_NAME = "xpath=.//*[@class='hp-logical-uplinks']//div[text()='%s']"
    ID_INPUT_UPLINK_NAME = "xpath=//*[@id='cic-logicalswitch-edit-uplink-name']"
    ID_COMBO_NETWORK = "xpath=//*[@id='cic-logicalswitch-edit-uplink-fc-network-container']/li/div/div[2]"
    ID_ELEMENT_SEARCHFORANOTHER = "xpath=//*[@id='cic-logicalswitch-edit-uplink-fc-network-container']/li/div/div[3]/div[2]/a"
    ID_ELEMENT_FC_SEARCHFORANOTHER = "xpath=//*[@id='cic-logicalswitch-edit-uplink-fc-ports-container']/li[1]/div/div[3]/div[2]/a"
    ID_ELEMENT_NETWORK_NAME = "xpath=//li/span[contains(text(), '%s')]"
    ID_ELEMENT_INTERCONNECT_EDIT = "xpath=//*[@id='cic-logicalswitch-edit-uplink-fc-ports-container']/li[1]/div/div[2]"
    ID_BTN_UPLINK_OK = "xpath=//*[@id='cic-logicalswitch-update']"
    ID_CHKBOX_UPLINK_PORT = "//*[@id='X%s']"
    ID_BTN_CONFIRM_DELETE_UPLINK = "xpath=.//*[@id='cic-delete-dialog-yes']"
    # ID_BTN_DELETE_UPLINK = "xpath=//li[descendant::Div//label//div[contains(text(),'%s')]]/div/div[@name='cic-switch-template-uplink-show-delete']"
    ID_BTN_DELETE_UPLINK = "xpath=.//*[@id='cic-logicalswitch-edit-uplinks']//li[@class='hp-logical-uplink hp-logical cic-uplink-set' and div[text()='%s']]//div[@class='hp-close cic-uplink-delete-button']"
    ID_VALIDATE_SUCCESS = "xpath = .//header[@class='hp-active']/following::div[@class='hp-notification-details']/div[@class='hp-details hp-unset']/p/span[contains(text(),'Created support dump for logical interconnect %s')]"  # %s replace with name of interconnect
    ID_SUCCESS_SUPPORT_DUMP = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-ok']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    ID_ERROR_SUPPORT_DUMP = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-error']/following::div[@class='hp-activity-message']/p/span[text()='Create support dump']"
    ID_BTN_ADD_SNMP_TRAPS_DEST = "//div[@class='hp-table-controls']/input[@id='cic-snmp-general-add-trap-destination' and @value='Add trap destination']"
    ID_INPUT_TRAP_ADDRESS = "xpath=//div/input[@id='cic-snmp-trap-destination-trap-destination']"
    ID_INPUT_COMMUNITY_STRING = "xpath=//div/input[@id='cic-snmp-trap-destination-community-string']"
    ID_RADIO_SNMPV1 = "xpath=//div/input[@id='cic-snmp-trap-destination-snmpv1']"
    ID_RADIO_SNMPV2 = "xpath=//div/input[id='cic-snmp-trap-destination-snmpv2']"
    ID_EXPAND_SEVERITY = "xpath=//div/div[@class='hp-collapsible hp-collapsed']/label[@id='cic-snmp-trap-destination-severity-status']"
    ID_COLLAPSE_SEVERITY = "xpath=//div/div[@class='hp-collapsible']/label[@id='cic-snmp-trap-destination-severity-status']"
    ID_CHECK_SEVERITY_CRITICAL = "xpath=//li/input[@id='cic-snmp-trap-destination-severity-critical']"
    ID_CHECK_SEVERITY_MAJOR = "xpath=//li/input[@id='cic-snmp-trap-destination-severity-major']"
    ID_CHECK_SEVERITY_MINOR = "xpath=//li/input[@id='cic-snmp-trap-destination-severity-minor']"
    ID_CHECK_SEVERITY_WARNING = "xpath=//li/input[@id='cic-snmp-trap-destination-severity-warning']"
    ID_CHECK_SEVERITY_NORMAL = "xpath=//li/input[@id='cic-snmp-trap-destination-severity-normal']"
    ID_CHECK_SEVERITY_INFO = "xpath=//li/input[@id='cic-snmp-trap-destination-severity-info']"
    ID_CHECK_SEVERITY_UNKNOWN = "xpath=//li/input[@id='cic-snmp-trap-destination-severity-unknown']"
    ID_EXPAND_VCMTRAPS = "xpath=//div/div[@class='hp-collapsible hp-collapsed']/label[@id='cic-snmp-trap-destination-vcmtraps-status']"
    ID_COLLAPSE_VCMTRAPS = "xpath=//div/div[@class='hp-collapsible']/label[@id='cic-snmp-trap-destination-vcmtraps-status']"
    ID_CHECK_VCMTRAPS = "xpath=//li/input[@id='cic-snmp-trap-destination-vcmtraps-legacy']"
    ID_EXPAND_VCENETTRAPS = "xpath=//div/div[@class='hp-collapsible hp-collapsed']/label[@id='cic-snmp-trap-destination-vcenet-status']"
    ID_COLLAPSE_VCENETTRAPS = "xpath=//div/div[@class='hp-collapsible']/label[@id='cic-snmp-trap-destination-vcenet-status']"
    ID_CHECK_VCENETTRAPS_PORT_STATUS = "xpath=//li/input[@id='cic-snmp-trap-destination-vcenet-port-status']"
    ID_CHECK_VCENETTRAPS_PORT_THRESHOLDS = "xpath=//li/input[@id='cic-snmp-trap-destination-vcenet-port-threshold']"
    ID_CHECK_VCENETTRAPS_OTHER = "xpath=//li/input[@id='cic-snmp-trap-destination-vcenet-other']"
    ID_EXPAND_VCFCSTATUS = "xpath=//div/div[@class='hp-collapsible hp-collapsed']/label[@id='cic-snmp-trap-destination-vcfc-status']"
    ID_COLLAPSE_VCFCSTATUS = "xpath=//div/div[@class='hp-collapsible']/label[@id='cic-snmp-trap-destination-vcfc-status']"
    ID_CHECK_VCFCSTATUS_PORT_STATUS = "xpath=//li/input[@id='cic-snmp-trap-destination-vcfc-port-status']"
    ID_CHECK_VCFCSTATUS_OTHER = "xpath=//li/input[@id='cic-snmp-trap-destination-vcfc-other']"
    ID_ELEMENT_DESTINATION = "xpath=//tbody/tr/td[contains(text(),'%s')]"
    ID_BTN_ADD_SNMP_TRAP = "id=cic-snmp-trap-destination-add-button"
    ID_BTN_DELETE_TRAP = "xpath=//tr/td[contains(text(),'%s')]/following-sibling::td[@class='hp-icon']/div[@class='hp-close']"
    ID_BUTTON_REMOVE = "xpath=//div[@class='hp-controls']/button[@class='hp-ok hp-primary' and text()='Yes, remove']"
    ID_BUTTON_CANCEL = "xpath=//div[@class='hp-controls']/button[@class='hp-cancel' and text()='Cancel']"
    ID_BUTTON_EDIT_TRAP = "xpath=//tr/td[contains(text(),'%s')]/following-sibling::td[@class='hp-icon']/div[@class='hp-edit']"
    ID_BUTTON_EDIT_OK = "id=cic-snmp-trap-destination-ok-button"
    ID_BTN_ADD_SNMP_ACCESS = "//*[@id='cic-snmp-general-add-snmp-access']"
    ID_ELEMENT_UPLINK_EDIT = "xpath=//li[descendant::Div//label//div[text()='%s']]/div/div[@class='hp-edit']"
    ID_BTN_ADD_UPLINK_SET = "xpath=//*[@id='cic-switch-template-show-uplink-button']"
    ID_UPLINK_EXISTENCE = "xpath=//*[@id='cic-switch-template-edit-uplinks']//div[@class='hp-ellipsis .hp-ellipsised' and contains(text(),'%s')]"
    ID_INPUT_UPLINK_ADD_NAME = "xpath=//*[@id='cic-logicalswitch-add-uplink-name']"
    ID_ETH_NETWORK_SELECT = "xpath=//li/span[text()='%s']"
    ID_RADIO_ETHERNET = "//*[@id='cic-logicalswitch-add-uplink-ethernet-type']"
    ID_RADIO_AUTO_CONNECTION_MODE = "//*[@id='cic-logicalswitch-add-uplink-auto-conntype']"
    ID_RADIO_FAILOVER_CONNECTION_MODE = "//*[@id='cic-logicalswitch-add-uplink-fail-conntype']"
    ID_LI_STATUS_OK = "//*[@id='cic-logicalswitch-details-status' and @class='crm-logicalswitch-data hp-status hp-status-ok']"
    ID_LI_STATUS_ERROR = "//*[@id='cic-logicalswitch-details-status' and @class='crm-logicalswitch-data hp-status hp-status-error']"
    ID_ERROR_WARN_MSG = "//*[@id='hp-page-notifications']/div[1]/header/div[2]/p/span"
    ID_BTN_ADD_NETWORK_UPLINK_PAGE = "//*[@id='cic-logicalswitch-add-uplink-networks-addNetworks']"
    ID_BTN_ADD_NETWORK_ADD = "//*[@id='hp-association-add']//button[contains(text(),'Add')]"
    ID_CHKBOX_NATIVE_BASE = "//*[@id='cic-logicalswitch-add-uplink-network-assigned']//input[@name='cic-logicalswitch-native-button-%s']"
    ID_BTN_ADD_UPLINK_PORTS = "//*[@id='cic-logicalswitch-add-uplink-ports-addPorts']"
    ID_SEARCH_INPUT_UPLINK_PORT = "//*[@id='hp-association-add']//input"
    ID_BTN_ADD_UPLINK_PORT = "//*[@id='hp-association-add']//button[contains(text(),'Add')]"
    ID_SELECT_TABLE_ADD_PORT = "//*[@id='hp-add-choices']/tbody/tr['%s']/td[contains(text(),'%s')]"
    ID_CHKBOX_FAILOVER_PREFERRED_PORT = ".//*[@id='cic-logicalswitch-add-uplink-ports-assigned']//input[@name='cic-ulogicalswitch-preferred-button-'%s'']"
    ID_RADIO_FIBERCHANNEL = "xpath=//*[@id='cic-logicalswitch-add-uplink-storage-type']"
    ID_CHKBOX_BASE = "xpath=//input[@id='%s']"
    ID_BTN_CREATE_LOGICAL_UPLINK_TEML = "xpath=//*[@id='cic-logicalswitch-add-uplink']"
    ID_NETWORK_COMBO_LIST = "xpath=//*[@id='cic-logicalswitch-add-uplink-fc-network-container']//div[@class='hp-search-combo-control']"
    ID_PORT_COMBO_LIST = "xpath=//*[@id='cic-logicalswitch-add-uplink-fc-ports-container']//div[@class='hp-search-combo-control']"
    # redistrubute login
    ID_ELEMENT_UPLINK_SET = "xpath=//*[@id='cic-logicalswitch-redistribute-table']/tbody/tr/td[2]/label[text()='%s']"
    ID_ELEMENT_INTERCONNECT_PORT = "xpath=//*[@id='cic-logicalswitch-redistribute-table']/tbody/tr/td[text()='%s']"
    ID_ELEMENT_LOGIN = "xpath=//*[@id='cic-logicalswitch-redistribute-table']/tbody/tr/td[text()='%s']/following-sibling::td[2]"
    ID_ELEMENT_STATUS = "xpath=//*[@id='cic-logicalswitch-redistribute-table']/tbody/tr/td[text()='%s']/following-sibling::td[1]"
    ID_BTN_REDISTRIBUTE_LOGIN_OK = "xpath=//*[@id='cic-logicalswitch-redistribute-ok']"
    ID_ELEMENT_REDISTRIBUTE_LOGIN_TITLE = "xpath=.//*[@id='cic-logicalswitch-redistribute-title']"
    # configure port monitoring
    ID_BTN_PORT_MONITORING = "xpath=//*[@id='cic-port-monitor-enable-hpToggle']/ol/li[text()='%s']"
    ID_NETWORKANALYSER_NAME = "xpath=//span[@class='hp-name' and text()='%s']"
    ID_ELEMENT_NETWORKANALYSER = "xpath=//div[@class='hp-search-combo-control']"
    ID_INPUT_PORT_ANALYSER = "xpath=//*[@id='cic-network-analyzer-monitor-port-input']"
    ID_BTN_ADD_PORT = "xpath=//*[@id='cic-portmon-config-add-ports-btn']"
    ID_ELEMENT_ADD_DOWNLINK_PORT = "xpath=//div[@class='hp-search-icon']"
    ID_ELEMENT_DOWNLINK = "xpath=//tr/td[text()='%s']"
    ID_ELEMENT_PORT = "xpath=//tr/td[text()='%s']/following-sibling::td[1]"
    ID_ELEMENT_SERVERHARDWARE = "xpath=//tr/td[text()='%s']/following-sibling::td[2]"
    ID_ELEMENT_SERVERPROFILE = "xpath=//tr/td[text()='%s']/following-sibling::td[3]"
    ID_ELEMENT_INTERCONNECT = "xpath=//tr/td[text()='%s']/preceding-sibling::td"
    ID_BTN_ADDPLUS = "xpath=//button[text()='Add +']"
    ID_BTN_PORT_CANCEL = "css=button.hp-cancel"
    ID_BTN_CONF_PORT_MONITORING = "xpath=//*[@id='cic-configure-port-montior-action']"
    ID_TITLE_CON_PORT_MON = "xpath=//span[text()='Configure port monitoring']"
    ID_BUTTON_UPDATE_CONF_PORT_MON = "xpath=//div[@class='hp-form-controls']/input[@id='cic-port-monitor-config-update-ok']"
    ID_ELEMENT_DOWNLINK_PORT = "xpath=//td[text()='%s']/preceding-sibling::td[text()='%s']"
    ID_CONFIGURE_PORT_ELEMENT_DOWNLINK_PORTS = "xpath=//td[text()='%s']/preceding-sibling::td/a[text()='%s']"
    ID_BTN_PORTMONITOR_OK = "id=cic-port-monitor-config-update-ok"
    ID_ELEMENT_PORTMON_COMPLETED_INPROGRESS = "xpath=//span[text()='Configure port monitoring']"
    ID_ELEMENT_PORTMON_COMPLTED = "xpath=//div[@class='hp-state' and text()='Completed']"
    # firmware  base line validation
    ID_ELEMENT_FIRMWARE_BASELINE = "xpath=//tbody/tr/td[text()='%s']/preceding-sibling::td/a[contains(text(),'%s')]"
    ID_ELEMENT_OVERVIEW = "css=#cic-logicalswitch-panel-selector > div.hp-value"
    ID_ELEMENT_OVERVIEW_FIRMWARE = "xpath=//*[@id='cic-logicalswitch-panel-selector']/ol/li/ol/li/a[text()='Firmware']"
    ID_ELEMENT_BASELINE_VAL = "xpath=//*[@id='cic-logicalswitch-show-firmware-table']/tbody/tr/td[text()='%s']"
    ID_Element_UPDATE_FIRMWARE = "//div[@class='hp-status hp-status-ok' and following-sibling::div/p/span[text()='Update firmware']]/ following-sibling::div[text()='%s']"  # replace %s with inter connect name
    ID_UPDATE_FIRMWARE_DETAILS = "//div[@class='hp-notification-details']/div/p/span"
    ID_ACTIVATE_FIRMWARE_FOR = "id=cic-logicalswitches-updfw-sw-selection-label"
    ID_ACTIVITY_SUSSCESS_DETAILS = "xpath= .//header[@class='hp-active' and div[@class='hp-status hp-status-ok']/following-sibling::div[@class='hp-activity-message']]/following-sibling::div[2]/div/div[1]"
    ID_UPDATE_STATUS = "xpath=.//header[@class='hp-active']/div[@class='hp-status hp-status-ok' or 'hp-status hp-status-warning']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Update firmware']//following::a[text()='%s']"
    ID_ACTIVITY_WARNING_DETAILS = "xpath= .//header[@class='hp-active' and div[@class='hp-status hp-status-warning']/following-sibling::div[@class='hp-activity-message']]/following-sibling::div[2]/div/div"
    ID_TABLE_ITEM = "xpath=//div[@id='cic-logicalswitch-master-table_wrapper']//tbody//td[.='%s']"
    ID_TALBE_ITEM_STATUS = "xpath=//div[@id='cic-logicalswitch-master-table_wrapper']//tbody//td[.='%s']/..//div[contains(@class, 'hp-status-ok')]"

    # firmware update related
    TIMEOUT = 20  # in minutes
    ID_PANEL_SELECTOR = "id=cic-logicalswitch-panel-selector"
    LINK_FIRMWARE = "link=Firmware"
    ID_INTERCONNECT_LIST = "xpath=//*[@id='cic-logicalswitch-show-firmware-table']//a"

    XPATH_INTECONNECTS_INSTALLED_FW = "xpath=//*[@id='cic-logicalswitches-show-firmware']//*[@id='cic-logicalswitch-show-firmware-table']/tbody/tr[%s]/td[4]"
    XPATH_INTECONNECTS_BASELINE_FW = "xpath=//*[@id='cic-logicalswitches-show-firmware']//*[@id='cic-logicalswitch-show-firmware-table']/tbody/tr[%s]/td[5]"
    XPATH_INTERCONNECT_NAME = "xpath=//*[@id='cic-logicalswitches-show-firmware']//*[@id='cic-logicalswitch-show-firmware-table']/tbody/tr[%s]/td[2]"
    XPATH_LI_CONSISTENCY_STATE = "xpath=//*[@id='cic-logicalswitch-show-state']/span"
    ID_LI_ACTIONS = "id=cic-logicalswitch-actions"
    ID_LI_REAPPLY_CONFIGURATION = "id=cic-logicalswitch-reapply-action"
    XPATH_LI_REAPPLY_CONFIG_BUTTON = "xpath=//*[@id='cic-logicalswitch-reapplyconfig-form']//button[@class='hp-ok hp-primary']"

    # Add label
    ID_RESET = "xpath = //a[text()='Reset']"
    ID_DROPDOWN = "xpath=//div[@id='cic-logicalswitch-panel-selector']"
    ID_DROPDOWN_SELECT_LABEL = ID_DROPDOWN + "/descendant::li/a[text()='Labels']"
    ID_EDIT_LABEL = "xpath = //li[@id='hp-labels-show-panel']/label/a[@class='hp-panel-edit' and text()='Edit']"
    ID_LABEL = "xpath = //li[@id='hp-labels-show-panel']/label/span[text()='Labels']"
    ID_EDIT_LABEL_PANEL = "xpath = //header[@id='hp-labels-edit-header']/h1/span[text()='Edit Labels']"
    ID_LABEL_NAME = "xpath = //input[@id='hp-labels-edit-search-input']"
    ID_ADD_LABEL_BTN = "xpath = //button[@id='hp-labels-edit-add']"
    ID_OK_LABEL_BTN = "xpath = //input[@id='hp-labels-edit-ok']"
    ID_ADDED_LABEL = "xpath = //table[@id='hp-labels-show-table']/descendant::a[text()='%s']"
    ID_ALL_LI_LIST = "xpath = //tbody/tr/td[2]"
    ID_SWITCH_FW_DETAILS = "xpath = //li[@id='cic-logicalswitches-show-firmware']/descendant::tbody/tr[%s]"  # replace %s with inter connect number

    ID_FW_LABEL_XPATH = "xpath=//*[@id='cic-logicalswitches-show-firmware']/label"
    ID_LI_XPATH = "xpath=//*[@id='cic-logicalswitch-master-table_wrapper']//table[@id='cic-logicalswitch-master-table']"
    ID_XPATH_DETAILS = "xpath=//*[@id='cic-logicalswitch-show-state']"
    ID_STACKINGMODE = "xpath=//*[@id='cic-logicalswitch-show-stacking-mode']"
    ID_STACK_HEALTH_XPATH = "xpath=//*[@id='cic-logicalswitch-show-stacking-health']"
    ID_NOTVISIBLE_XPATH = "xpath=//*[@id='cic-logicalswitches-show-firmware']/label"
    ID_BAY_INFO_XPATH = "xpath=//*[@id='cic-logicalswitch-show-interconnects']/a"
    ID_EXSTATE_XPATH = "xpath=//*[@id='cic-logicalswitch-show-device-name-1-%s']"
    ID_ACTUAL_STATE_XPATH = "xpath=//*[@id='cic-logicalswitch-show-device-actual-name-1-%s']"
    ID_LI_XPATH_BTN1 = "xpath=//*[@id='cic-logicalswitches-show-firmware']/label"
    ID_XPATH_DRP_DWN_MENU = "xpath=//*[@id='cic-logicalswitches-show-firmware']/label"
    ID_FW_TAB_XAPTH = "xpath=//*[@id='cic-logicalswitches-show-firmware']"
    ID_EX_STATE_XPATHB = "xpath=//*[@id='cic-logicalswitch-show-device-name-1-%s']"
    ID_ACTUAL_STATE_XPATH = "xpath=//*[@id='cic-logicalswitch-show-device-actual-name-1-%s']"
    ID_DRP_MEMU_XPATH_BTNX = "xpath=//*[@id='hp-labels-show-panel']/label/span", "//*[@id='hp-labels-show-panel']/label/a"
    ID_ADD_LABEL_BB = "xpath=//*[@id='hp-labels-edit-add']"
    ID_XPATH_CLICK_OK_BTN = "xpath=//*[@id='hp-labels-edit-ok']"

    ID_UPDATE_ACTION = "xpath=//*[@id='cic-logicalswitches-updfw-form']//div[@class='cic-logicalswitches-updfw-default-body']//label[text()='Update action']/following-sibling::div[@class='hp-form-content']//div[@class='hp-select']/div[@class='hp-value']"
    ID_SELECT_UPDATE_ACTION = "xpath =//*[@id='cic-logicalswitches-updfw-form']//*[@class='hp-select-form']//*[@class='hp-options']//li[span[contains(text(), '%s')]]"

    ID_FIRMWARE_WARNING = "xpath=//form[@id='cic-logicalswitches-updfw-form']//div[@class='hp-status hp-status-warning']"
    ID_TEXT_FIRMWARE_WARNING = "xpath=//form[@id='cic-logicalswitches-updfw-form']//div[@class='hp-status hp-status-warning']/following::span[@class='hp-form-message-text']"
    ID_TEXT_FIRMWARE_WARNING_DETAILS = "xpath=//form[@id='cic-logicalswitches-updfw-form']//div[@class='hp-form-message-details']"

    ID_SELECT_FIRMWARE_DROPDOWN = "xpath =.//*[@id='cic-logicalswitches-updfw-dropdown']/div/div/ol/li/span[text() = '%s']"
    TIMEOUT = 10  # in minutes
    XPATH_UPDATE_COMPLETE = "xpath=//header[@class='hp-notification-summary']/div[@class='hp-state' and text()='Completed']"
    XPATH_UPDATE_STATUS_WARNING = "xpath=//*[@id='hp-page-notifications']/div[@class='hp-notification']/header/div[@class='hp-state' and text()='Warning']"
    XPATH_UPDATE_STATUS_ERROR = "xpath=//*[@id='hp-page-notifications']/div[@class='hp-notification']/header/div[@class='hp-state' and text()='Error']"
    UPDATE_WAIT_TIME = 15  # in seconds
    ID_LIG_ADD_FORM = "id=cic-switchtemplate-add-form"
    ID_BTN_CANCEL_LST11 = "id=cic-switchtemplate-add-close"
    ID_PROGRESS_BAR = "xpath=//*[@class='hp-progress']"
    ID_CMPLETE_XPATH = "xpath=//header[@class='hp-notification-summary']/div[@class='hp-state' and text()='Completed']"
    ID_WARNING_XPATH = "xpath=//header[@class='hp-notification-summary']/div[@class='hp-state' and text()='Warning']"
    ID_ERROR_XPATH = "xpath=//header[@class='hp-notification-summary']/div[@class='hp-state' and text()='Error']"
    ID_ETHERNET_CH_XPATH = "xpath=//*[@id='cic-logicalswitches-updfw-ethernet-activation-div']//*[@class='hp-select-form']"
    ID_ETHERNET_CHANNEL_XPATH = "//*[@id='cic-logicalswitches-updfw-ethernet-activation-div']//*[@class='hp-options']//*[text()='%s']"

    ID_FIBER_FC_CHANNEL_XPATH = "xpath=//*[@id='cic-logicalswitches-updfw-fc-activation-div']//*[@class='hp-select-form']"
    ID_SELECT_FC_XPATHA = "xpath=//*[@id='cic-logicalswitches-updfw-fc-activation-div']//*[@class='hp-options']//*[text()='%s']"
    ID_CHECK_FORCE_FLAG_XPATH = "xpath=//*[@id='cic-logicalswitches-updfw-forceupdate']"

    WAIT_TIME = 12  # in seconds

    FW_UPDATE_TIME = 7200  # in seconds

    ID_FW_CANCEL = "//*[@class='cic-logicalswitches-updfw-cancel cic-logicalswitches-updfw-default-body hp-cancel'][text()='Cancel']"
    ID_UPDATE_ACTION_XPATH = "xpath=//*[@id='cic-logicalswitches-updfw-form']//*[@class='hp-select-form']"

    ID_LE_FW_UPDATE_FORM = "id=cic-logicalswitches-updfw-form"

    XPATH_LE_FW_UPDATE_HP_STATUS_ERROR = "xpath=//*[@id='cic-logicalswitches-updfw-form']//*[@class='hp-status hp-status-error']"

    XPATH_LE_FW_UPDATE_FORM_MESSAGE_SUMMARY = "xpath=//*[@id='cic-logicalswitches-updfw-form']//*[@class='hp-form-message-summary']"
    XPATH_LE_FW_UPDATE_FORM_MESSAGE_DETAILS = "xpath=//*[@id='cic-logicalswitches-updfw-form']//*[@class='hp-form-message-details']"
    ID_INTERCONNECT_LIST = "xpath = //*[@id='cic-logicalswitch-show-firmware-table']//a"
    ID_SWITCH_FW_DETAILS = "xpath = //li[@id='cic-logicalswitches-show-firmware']/descendant::tbody/tr[%s]"
    ID_NEW_UPDATE_SUCCESS = "xpath = .//header[@class='hp-notification-summary']/div[@class='hp-status hp-status-ok']/following-sibling::div[@class='hp-message']/p/span[text()='Update firmware']/following::Div[@class='hp-state']"
    ID_NEW_SELECT_ALERT = "xpath=.//*[@id='hp-page-notifications']/div[2]/ol/li[div[@class='hp-message']//span[text()='Update firmware']][1]"
    ID_ACTIVITY_NEW_SUCCESS_DETAILS = "xpath= .//header[@class='hp-notification-summary']/div[@class='hp-status hp-status-ok']/following-sibling::div[@class='hp-message']/p/span[text()='Update firmware']/following::Div[@class='hp-full']//div[@class='hp-notification-details']/div"

    ID_NEW_UPDATE_WARNING = "xpath = .//header[@class='hp-notification-summary']/div[@class='hp-status hp-status-warning']/following-sibling::div[@class='hp-message']/p/span[text()='Update firmware']/following::Div[@class='hp-state']"

    ID_NEW_UPDATE_ERROR = "xpath = .//header[@class='hp-notification-summary']/div[@class='hp-status hp-status-error']/following-sibling::div[@class='hp-message']/p/span[text()='Update firmware']/following::Div[@class='hp-state']"
    ID_NEW_CLICK_SUCCESS = "xpath=.//*[@id='hp-page-notifications']/div[2]/header/ol/li[3]/div[@class='hp-status hp-status-ok']"
    ID_NEW_CLICK_WARNING = "xpath=.//*[@id='hp-page-notifications']/div[2]/header/ol/li[2]/div[@class='hp-status hp-status-warning']"
    ID_NEW_CLICK_ERROR = "xpath=.//*[@id='hp-page-notifications']/div[2]/header/ol/li[1]/div[@class='hp-status hp-status-error']"
    # Here we need to use index since take  latest  alert message
    ID_NEW_SELECT_ALERT = "xpath=.//*[@id='hp-page-notifications']/div[2]/ol/li[div[@class='hp-message']//span[text()='Update firmware']][1]"
    ID_UPDATE_PROGRESS = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-changing']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Update firmware']//following::a[text()='%s']"
    ID_UPDATE_FAILED = "xpath = .//header[@class='hp-active']/div[@class='hp-status hp-status-error']/following-sibling::div[@class='hp-activity-message']/p/span[text()='Update firmware']//following::a[text()='%s']"
    ID_STATUS_OK = "xpath=//ol[@id='hp-flyout-activities']/li/div/header/div[@class='hp-status hp-status-ok']"
    ID_STATUS_CHANGING = "xpath=//ol[@id='hp-flyout-activities']/li/div/header/div[@class='hp-status hp-status-changing']"
    ID_VALIDATE_ACTIVATE_FIRMWARE = "xpath = .//*[@id='cic-logicalswitches-updfw-action-annotation' and text()='All firmware already activated']"
    ID_FIRMWARE_ERROR = "id=cic-logicalswitches-updfw-error"
    ID_CLICK_MAINPANE = "xpath =.//*[@id='hp-page-notifications']//header/div[@class='hp-aside']//div[@class='hp-timestamp']"
    ID_ELEMENT_OVERVIEW_ACTIVITY = "xpath=.//*[@id='cic-logicalswitch-panel-selector']/ol/li[4]/a"

    ID_ACTIVITY_MESSAGE = "xpath=*//tbody/tr[td[@class='hp-name']//span[normalize-space(text())='%s']][1]"
    ID_TEXT_FWUPDATE_ERROR_MSG = "xpath=//div[@id='cic-logicalswitches-updfw-error']"
    ID_BUTTON_FWUPDATE_CANCEL = "xpath=//button[@class='cic-logicalswitches-updfw-cancel cic-logicalswitches-updfw-default-body hp-cancel']"
    ID_LABEL_BASELINE_NOT_SET = "id=cic-logicalswitches-updfw-baseline-notset"
    ID_FW_DETAILS_CONTAINER = "xpath=.//div[@class='hp-page-notifications']//div[@class='hp-details-container']"

    ID_XPATH_ACT = "xpath=//*[@id='cic-logicalswitch-panel-selector']/div"
    ID_ACTIVITY_XPATH = "//*[@id='cic-logicalswitch-panel-selector']//*[text()='Activity']"
    STAGE_SUCCES_XPATH = "//*[@id='DataTables_Table_12']//*[@role='alert']//*[@class='even hp-alert']//*[@class='hp-name']/p/span[contains(text(),'%s')]"
    ID_FRM_DROP_DWN_XPATH = "xpath=//*[@id='cic-logicalswitch-panel-selector']//*[text()='Firmware']"
    ID_ACTIVIT_XVPATH = "xpath=//*[@id='cic-logicalswitch-panel-selector']//*[text()='Activity']"

    ID_LINK_OVERVIEWB = "//*[@id='cic-logicalswitch-panel-selector']"
    ID_LINK_ACTIVITYB = "link = Activity"
    ID_FILTER_ALL_STATESB = "xpath = //div[@id='hp-activity-state-filter']/div[@class='hp-value' and contains(text(),'All states')]"
    ID_ACTIVITY_DATE_FILTERB = "id=hp-activity-date-filter"
    ID_ACTIVITY_DATE_SELECTB = "//*[@id='hp-activity-date-filter']//li[@data-id='%s']"
    ID_ACTIVITY_VIEWB = "xpath=//div[@id='hp-activity-resource-view']"

    ID_ACTIVITY_MESSAGEB = "xpath=//*[@id='hp-activities']/tbody//*/p/span[text()='%s']"
    XPATH_ACTIVITY_TIMEAGO = "//table[@class='hp-index-table hp-activities dataTable']/tbody/tr[td[@class='hp-name']//span[text()='%s']][1]/td[@class='hp-date']/div[@class='hp-timeago']"
    ID_PANEL_SELECTOR = "id=cic-logicalswitch-panel-selector"
    LINK_FIRMWARE = "link=Firmware"
    XPATH_INTECONNECTS_INSTALLED_FW = "xpath=//*[@id='cic-logicalswitches-show-firmware']//*[@id='cic-logicalswitch-show-firmware-table']/tbody/tr[%s]/td[4]"
    XPATH_INTECONNECTS_BASELINE_FW = "xpath=//*[@id='cic-logicalswitches-show-firmware']//*[@id='cic-logicalswitch-show-firmware-table']/tbody/tr[%s]/td[5]"
    XPATH_INTERCONNECT_NAME = "xpath=//*[@id='cic-logicalswitches-show-firmware']//*[@id='cic-logicalswitch-show-firmware-table']/tbody/tr[%s]/td[2]"

    ID_XPATH_ETHERNET_SELECT = "xpath=//*[@id='cic-logicalswitches-updfw-selected-ethernet-interconnects']//*[@value='SGH420HHYA, interconnect %s' and @type='checkbox']"
    ID_XPATH_FC_SELCTIVE = "xpath=//*[@id='cic-logicalswitches-updfw-selected-fc-interconnects']//*[@value='SGH420HHYA, interconnect %s' and @type='checkbox']"

    ID_LI_STACKING_HEALTH = "id=cic-logicalswitch-show-stacking-health"
    ID_SHOW_SWITCHES = "id=cic-logicalswitch-show-switches"
    ID_GET_FIRMWAREBASELINE = "xpath =//*[@id='cic-logicalswitches-updfw-baseline-value']"

    ID_XPATH_ETHRE_DELAY_XPATH = "xpath =//*[@id='cic-logicalswitches-updfw-ethernet-activation-delay']"
    ID_XPATH_FIBER_DELAY_XPATH = "xpath =//*[@id='cic-logicalswitches-updfw-fc-activation-delay']"
    ID_SELECT_LI_XPATH = "//*[@id='cic-logicalswitch-master-table']//*[text()='%s']"

    ID_XPATH_ETH_INTERCONNECTS = "xpath=//*[@id='cic-logicalswitches-updfw-selected-ethernet-interconnects-error']"
    ID_XPATH_FC_INETRCONNECTS = "xpath=//*[@id='cic-logicalswitches-updfw-selected-fc-interconnects-error']"

    ID_ethrnet_empydelay_err = "//*[@id='cic-logicalswitches-updfw-ethernet-activation-delay-div']//*[@class='hp-form-content hp-has-error']"

    ID_FC_empt_del_err = "//*[@id='cic-logicalswitches-updfw-fc-activation-delay-div']//*[@class='hp-form-content hp-has-error']"
    ID_SELECT_ACTIVITY_VIEW_LI = "id=hp-activity-resource-view"
    ID_COLLAPSE_XPATH = "//tbody/tr[td[@class='hp-name']//span[text()='Update firmware']][1]//*/div[@class='hp-collapser']"
    ID_Notification_ACTXPATH_PATH = "//*[@class='hp-task-notification-container']//*[@class='hp-notification-details']"
