admin_credentials = {'userName': 'Administrator', 'password': 'wpsthpvse1'}

timeandlocale = {'type': 'TimeAndLocale', 'dateTime': None, 'timezone': 'UTC', 'ntpServers': ['ntp.hpecorp.net'], 'locale': 'en_US.UTF-8'}

users = [{'userName': 'Serveradmin', 'password': 'wpsthpvse1', 'fullName': 'Serveradmin', 'roles': ['Server administrator'], 'emailAddress': 'sarah@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'},
         {'userName': 'Networkadmin', 'password': 'wpsthpvse1', 'fullName': 'Networkadmin', 'roles': ['Network administrator'], 'emailAddress': 'nat@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'},
         {'userName': 'Backupadmin', 'password': 'wpsthpvse1', 'fullName': 'Backupadmin', 'roles': ['Backup administrator'], 'emailAddress': 'backup@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'},
         {'userName': 'Noprivledge', 'password': 'wpsthpvse1', 'fullName': 'Noprivledge', 'roles': ['Read only'], 'emailAddress': 'rheid@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'}
         ]

licenses = [{'key': '9A9C DQAA H9PY CHV2 V7B5 HWWB Y9JL KMPL DJKD 5FFM DXAU 2CSM GHTG L762 TT66 VZRY KJVT D5KM EFVW DT5J EBE9 M2CC SPS9 YG66 Z99R MWSN 6Z84 46XT WZJL HH4Q L975 SNJT ZWWC AADW NJ79 CEJC 5S86 FC4X EKSZ X4CP XZLU FMXS FKS6 KKCE 4NMU FGN5 F8CG Z2HX FRJ6 EPM2 2SJV VTFG LS8T XU4E "EVAL-HPOV-NFR1 HPOV-NFR1 HP_OneView_16_Seat_NFR 7T36AEJG7JJ9"_3MBSY-CJZY2-LDVV4-92DQT-L6TTW'},
            {'key': 'AA9C AQAA H9PY CHVY V7B5 HWWB Y9JL KMPL 3JKH 5FVM DXAU 2CSM GHTG L762 MTK7 FYB9 KJVT D5KM EFVW DT5J 4BEM M2SC SPS9 YG66 Z99R MWSN 6Z84 46XT WZJL HH4Q L975 SNJT ZWWC AADW NJ79 CEJC 5S86 FC4X EKSZ X4CP XZLU FMXS FKS6 KKCE 4NMU FGN5 F8CG Z2HX FRJ6 EPM2 2SJV VTFG LS8T XU4E "EVAL-HPOV-NFR1 HPOV-NFR1 HP_OneView_16_Seat_NFR 7T36AEJG7JJ9"_3MBSY-CJZXJ-RDCJQ-55T3M-BP3H2'},
            {'key': 'AA9C DQAA H9PA GHX3 U7B5 HWW5 Y9JL KMPL SR6C MHJU DXAU 2CSM GHTG L762 9AVY WXJY KJVT D5KM EFVW DT5J TFQ9 74C8 SPS9 YG66 Z99R MWSN 6Z84 46XT WZJT HH4Q L975 SNJT ZWWC AADW NJ79 CEJC 5S86 FC4X EKSZ X4CP XZLU FMXS FKS6 KKCE 4NMU FGN5 F8CG Z2HX FRJ6 EPM2 2SJV VTVG LS8T XU4E "EVAL-HPOV-NFR2 HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR 9G6UAEJGUA4U"'},
            {'key': 'QCTG B9MA H9P9 8HW3 V7B5 HWWB Y9JL KMPL 5AKE 8DBA DXAU 2CSM GHTG L762 VYW6 GCN9 KJVT D5KM EFVW DT5J 5XHK 5QK2 AK2P 3EW2 QJQ4 HU5V TZZ7 9B5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542022 HPOV-NFR1 HP_OneView_16_Seat_NFR AACUJJECUT2J"_3DWNY-DZZW8-24Y5Y-NZB2K-YH5R2'},
            {'key': '9CTC C9MA H9PY CHUY V7B5 HWWB Y9JL KMPL VACE 8GRE DXAU 2CSM GHTG L762 7RGY XHBE KJVT D5KM EFVW DT5J VX79 5T22 AK2P 3EW2 9JA6 XUNV TZZH MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542193 HPOV-NFR1 HP_OneView_16_Seat_NFR 9UH2JJECJ4AA"_3JNDQ-Z35J3-D6T6M-5XKZL-WC2W2'},
            {'key': 'YBLG B99A H9PQ 8HVZ U7B5 HWW5 Y9JL KMPL VAWA 8CBE DXAU 2CSM GHTG L762 5NW5 HDV4 KJVT D5KM EFVW DT5J VXP8 4XK2 GNSL 9F82 7JKT QVXB XZKH ABB4 NV2C LHXU KN7U 5NA6 BKRK 35QB D8UW R42A X3BN LQ6M 5V9A PM6Q 4MN9 9GGS EZU7 GEMX VUJW CDB5 JVRX 8HEN 2J98 ACPB "TKOPREN HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR JJADJJEDATCA"'},
            ]

# Enclosures
ENC1 = 'CN75120D7B'

# Interconnects
ENC1ICBAY3 = '%s, interconnect 3' % ENC1
ENC1ICBAY6 = '%s, interconnect 6' % ENC1

# Sas Interconnects
ENC1SASICBAY1 = '%s, interconnect 1' % ENC1

# Drive Enclosures (Bigbird)
ENC1DEBAY7 = '%s, bay 7' % ENC1

# Server Hardware
ENC1SHBAY1 = '%s, bay 1' % ENC1
ENC1SHBAY2 = '%s, bay 2' % ENC1
ENC1SHBAY6 = '%s, bay 6' % ENC1
ENC1SHBAY7 = '%s, bay 7' % ENC1

enclosures = [
    {
        "type": "EnclosureV300",
        "name": ENC1,
        "enclosureTypeUri": "/rest/enclosure-types/SY12000",
        "interconnectBays":
        [
            {"bayNumber": 1, "interconnectModel": "Synergy 12Gb SAS Connection Module", "interconnectUri": "SASIC:%s" % ENC1SASICBAY1},
            {"bayNumber": 2, "interconnectModel": None},
            {"bayNumber": 3, "interconnectModel": "VC SE 40Gb F8 Module", "interconnectUri": "IC:%s" % ENC1ICBAY3},
            {"bayNumber": 4, "interconnectModel": None},
            {"bayNumber": 5, "interconnectModel": None},
            {"bayNumber": 6, "interconnectModel": "VC SE 40Gb F8 Module", "interconnectUri": "IC:%s" % ENC1ICBAY6}
        ],
        "managerBays":
        [
            {"bayNumber": 1, "linkPortState": "Unlinked", "mgmtPortStatus": "OK", "linkPortStatus": "OK"},
            {"bayNumber": 2, "linkPortState": None, "mgmtPortStatus": None, "linkPortStatus": None}
        ],
        "deviceBays":
        [
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": "SH:CN75120D7B, bay 1",
                "deviceFormFactor": "SingleHeightSingleWide",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": True,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": 212,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Present",
                "type": "DeviceBayV300",
                "deviceUri": "SH:CN75120D7B, bay 1",
                "bayNumber": 1,
                "serialConsole": True
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": "SH:CN75120D7B, bay 2",
                "deviceFormFactor": "SingleHeightSingleWide",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": True,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": 189,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Present",
                "type": "DeviceBayV300",
                "deviceUri": "SH:CN75120D7B, bay 2",
                "bayNumber": 2,
                "serialConsole": True
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "serialNumber": "CN7452061Q",
                "coveredByDevice": "DE:CN75120D7B, bay 3",
                "deviceFormFactor": "SingleHeightDoubleWideStorage",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": False,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": 500,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Present",
                "type": "DeviceBayV300",
                "deviceUri": "DE:CN75120D7B, bay 3",
                "bayNumber": 3,
                "serialConsole": True
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "serialNumber": "CN7452061Q",
                "coveredByDevice": "DE:CN75120D7B, bay 3",
                "deviceFormFactor": "SingleHeightDoubleWideStorage",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": False,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": 500,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Subsumed",
                "type": "DeviceBayV300",
                "deviceUri": None,
                "bayNumber": 4,
                "serialConsole": True
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": None,
                "deviceFormFactor": "Empty",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": True,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": True,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": None,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Absent",
                "type": "DeviceBayV300",
                "deviceUri": None,
                "bayNumber": 5,
                "serialConsole": None
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": "SH:CN75120D7B, bay 6",
                "deviceFormFactor": "DoubleHeightSingleWide",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": True,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": False,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": 784,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Present",
                "type": "DeviceBayV300",
                "deviceUri": "SH:CN75120D7B, bay 6",
                "bayNumber": 6,
                "serialConsole": True
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": "SH:CN75120D7B, bay 7",
                "deviceFormFactor": "SingleHeightSingleWide",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": True,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": 166,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Present",
                "type": "DeviceBayV300",
                "deviceUri": "SH:CN75120D7B, bay 7",
                "bayNumber": 7,
                "serialConsole": True
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": None,
                "deviceFormFactor": "Empty",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": True,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": None,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Absent",
                "type": "DeviceBayV300",
                "deviceUri": None,
                "bayNumber": 8,
                "serialConsole": None
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": None,
                "deviceFormFactor": "Empty",
                "availableForHalfHeightDoubleWideProfile": True,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": True,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": None,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Absent",
                "type": "DeviceBayV300",
                "deviceUri": None,
                "bayNumber": 9,
                "serialConsole": None
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": None,
                "deviceFormFactor": "Empty",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": True,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": None,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Absent",
                "type": "DeviceBayV300",
                "deviceUri": None,
                "bayNumber": 10,
                "serialConsole": None
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": None,
                "deviceFormFactor": "Empty",
                "availableForHalfHeightDoubleWideProfile": True,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": True,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": None,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Absent",
                "type": "DeviceBayV300",
                "deviceUri": None,
                "bayNumber": 11,
                "serialConsole": None
            },
            {
                "category": "device-bays",
                "model": None,
                "coveredByProfile": None,
                "bayPowerState": "Unknown",
                "coveredByDevice": "SH:CN75120D7B, bay 6",
                "deviceFormFactor": "DoubleHeightSingleWide",
                "availableForHalfHeightDoubleWideProfile": False,
                "ipv4Setting": None,
                "availableForFullHeightProfile": False,
                "changeState": "None",
                "profileUri": None,
                "availableForHalfHeightProfile": False,
                "deviceBayType": "SY12000DeviceBay",
                "powerAllocationWatts": 0,
                "availableForFullHeightDoubleWideProfile": False,
                "devicePresence": "Subsumed",
                "type": "DeviceBayV300",
                "deviceUri": None,
                "bayNumber": 12,
                "serialConsole": True
            }
        ],
    }
]

sasics = [
    {
        "type": "sas-interconnect",
        "name": ENC1SASICBAY1,
        "serialNumber": "2M220100SL",
        "partNumber": "752953-001",
        "productName": "HPE Synergy 12Gb SAS Connection Module",
        "interconnectTypeUri": "/rest/sas-interconnect-types/HPESynergy12GbSASConnectionModule",
        "enclosureUri": "ENC:%s" % ENC1,
        "status": "OK",
        "sasPorts": [
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "8",
                "portName": "8",
                "name": "8",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "3",
                "portName": "3",
                "name": "3",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "12",
                "portName": "12",
                "name": "12",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "4",
                "portName": "4",
                "name": "4",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "2",
                "portName": "2",
                "name": "2",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "state": "Linked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "10",
                "portName": "10",
                "name": "10",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "5",
                "portName": "5",
                "name": "5",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "9",
                "portName": "9",
                "name": "9",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "7",
                "portName": "7",
                "name": "7",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "11",
                "portName": "11",
                "name": "11",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "6",
                "portName": "6",
                "name": "6",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "linkedPortUri": None,
                "state": "Unlinked",
            },
            {
                "type": "sas-port",
                "enabled": True,
                "portLocation": "1",
                "portName": "1",
                "name": "1",
                "portType": "Downlink",
                "containerDeviceUri": "SASIC:%s" % ENC1SASICBAY1,
                "state": "Linked",
            },
        ]
    },
    {
        "type": "sas-interconnect",
        "name": ENC1SASICBAY1,
        "serialNumber": "2M220101SL",
        "partNumber": "752953-001",
        "productName": "HPE Synergy 12Gb SAS Connection Module",
        "interconnectTypeUri": "/rest/sas-interconnect-types/HPESynergy12GbSASConnectionModule",
        "enclosureUri": "ENC:%s" % ENC1,
        "status": "OK",
    }
]
