admin_credentials = {'userName': 'Administrator', 'password': 'wpsthpvse1'}

timeandlocale = {
    'type': 'TimeAndLocale',
    'dateTime': None,
    'timezone': 'UTC',
    'ntpServers': ['ntp.hpecorp.net'],
    'locale': 'en_US.UTF-8'}

users = [{'userName': 'Serveradmin', 'password': 'wpsthpvse1', 'fullName': 'Serveradmin', 'roles': ['Server administrator'], 'emailAddress': 'sarah@hp.com', 'officePhone': '970-555-0003', 'mobilePhone': '970-500-0003', 'type': 'UserAndPermissions'},
         {'userName': 'Networkadmin',
          'password': 'wpsthpvse1',
          'fullName': 'Networkadmin',
          'roles': ['Network administrator'],
          'emailAddress': 'nat@hp.com',
          'officePhone': '970-555-0003',
          'mobilePhone': '970-500-0003',
          'type': 'UserAndPermissions'},
         {'userName': 'Backupadmin',
          'password': 'wpsthpvse1',
          'fullName': 'Backupadmin',
          'roles': ['Backup administrator'],
          'emailAddress': 'backup@hp.com',
          'officePhone': '970-555-0003',
          'mobilePhone': '970-500-0003',
          'type': 'UserAndPermissions'},
         {'userName': 'Noprivledge',
          'password': 'wpsthpvse1',
          'fullName': 'Noprivledge',
          'roles': ['Read only'],
          'emailAddress': 'rheid@hp.com',
          'officePhone': '970-555-0003',
          'mobilePhone': '970-500-0003',
          'type': 'UserAndPermissions'}
         ]

licenses = [{'key': '9A9C DQAA H9PY CHV2 V7B5 HWWB Y9JL KMPL DJKD 5FFM DXAU 2CSM GHTG L762 TT66 VZRY KJVT D5KM EFVW DT5J EBE9 M2CC SPS9 YG66 Z99R MWSN 6Z84 46XT WZJL HH4Q L975 SNJT ZWWC AADW NJ79 CEJC 5S86 FC4X EKSZ X4CP XZLU FMXS FKS6 KKCE 4NMU FGN5 F8CG Z2HX FRJ6 EPM2 2SJV VTFG LS8T XU4E "EVAL-HPOV-NFR1 HPOV-NFR1 HP_OneView_16_Seat_NFR 7T36AEJG7JJ9"_3MBSY-CJZY2-LDVV4-92DQT-L6TTW'},
            {'key':
                'AA9C AQAA H9PY CHVY V7B5 HWWB Y9JL KMPL 3JKH 5FVM DXAU 2CSM GHTG L762 MTK7 FYB9 KJVT D5KM EFVW DT5J 4BEM M2SC SPS9 YG66 Z99R MWSN 6Z84 46XT WZJL HH4Q L975 SNJT ZWWC AADW NJ79 CEJC 5S86 FC4X EKSZ X4CP XZLU FMXS FKS6 KKCE 4NMU FGN5 F8CG Z2HX FRJ6 EPM2 2SJV VTFG LS8T XU4E "EVAL-HPOV-NFR1 HPOV-NFR1 HP_OneView_16_Seat_NFR 7T36AEJG7JJ9"_3MBSY-CJZXJ-RDCJQ-55T3M-BP3H2'},
            {'key':
                'AA9C DQAA H9PA GHX3 U7B5 HWW5 Y9JL KMPL SR6C MHJU DXAU 2CSM GHTG L762 9AVY WXJY KJVT D5KM EFVW DT5J TFQ9 74C8 SPS9 YG66 Z99R MWSN 6Z84 46XT WZJT HH4Q L975 SNJT ZWWC AADW NJ79 CEJC 5S86 FC4X EKSZ X4CP XZLU FMXS FKS6 KKCE 4NMU FGN5 F8CG Z2HX FRJ6 EPM2 2SJV VTVG LS8T XU4E "EVAL-HPOV-NFR2 HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR 9G6UAEJGUA4U"'},
            {'key':
                'AAAE BQAA H9P9 CHW2 V7B5 HWWB Y9JL KMPL SRWE 8HJU DXAU 2CSM GHTG L762 LAB2 VRJA KJVT D5KM EFVW DT5J TF9K 54C8 SPS9 YG66 Z99R MWSN 6Z84 46XT WZJL HH4Q L975 SNJT ZWWC AADW NJ79 CEJC 5S86 FC4X EKSZ X4CP XZLU FMXS FKS6 KKCE 4NMU FGN5 F8CG Z2HX FRJ6 EPM2 2SJV VTFG LS8T XU4E "EVAL-HPOV-NFR1 HPOV-NFR1 HP_OneView_16_Seat_NFR 7T36AEJG7JJ9"_3G7SK-QDGSY-LRT8D-PWPVP-QWRKW'},
            {'key':
                '9CTC C9MA H9PY CHUY V7B5 HWWB Y9JL KMPL VACE 8GRE DXAU 2CSM GHTG L762 7RGY XHBE KJVT D5KM EFVW DT5J VX79 5T22 AK2P 3EW2 9JA6 XUNV TZZH MB5X 82Z5 WHEF GE4C LUE3 BKT8 WXDG NK6Y C4GA HZL4 XBE7 3VJ6 2MSU 4ZU9 9WGG CZU7 WE4X YN44 CH55 KZLG 2F4N A8RJ UKEC 3F9V JQY5 "423542193 HPOV-NFR1 HP_OneView_16_Seat_NFR 9UH2JJECJ4AA"_3JNDQ-Z35J3-D6T6M-5XKZL-WC2W2'},
            {'key':
                'YBLG B99A H9PQ 8HVZ U7B5 HWW5 Y9JL KMPL VAWA 8CBE DXAU 2CSM GHTG L762 5NW5 HDV4 KJVT D5KM EFVW DT5J VXP8 4XK2 GNSL 9F82 7JKT QVXB XZKH ABB4 NV2C LHXU KN7U 5NA6 BKRK 35QB D8UW R42A X3BN LQ6M 5V9A PM6Q 4MN9 9GGS EZU7 GEMX VUJW CDB5 JVRX 8HEN 2J98 ACPB "TKOPREN HPOV-NFR2 HP_OneView_w/o_iLO_16_Seat_NFR JJADJJEDATCA"'},
            ]

hardware_list = [
    'CN75120D7B, bay 3',
    'CN75120D7B, bay 5',
    'CN75120D7B, bay 7',
    'CN75120D77, bay 1',
    'CN75120D77, bay 5',
    'CN750163KD, bay 1',
    'CN750163KD, bay 5']

# Enclosures
enclosures = [{
    "managerBays": [
        {
            "bayNumber": 1,
            "linkPortState": "Linked",
            "mgmtPortStatus": "OK",
            "linkPortStatus": "OK",
        },
        {
            "linkPortStatus": "OK",
            "mgmtPortStatus": "OK",
            "linkPortState": "Linked",
            "bayNumber": 2
        }
    ],
    "interconnectBays": [
        {
            "bayNumber": 1,
            "interconnectModel": "Synergy 12Gb SAS Connection Module",
            "interconnectUri": "SasIC:CN75120D7B, interconnect 1",
        },
        {
            "bayNumber": 2,
            "interconnectModel": None,
            "interconnectUri": None,
        },
        {
            "bayNumber": 3,
            "interconnectModel": "Virtual Connect SE 40Gb F8 Module for Synergy",
            "interconnectUri": "IC:CN75120D7B, interconnect 3",
        },
        {
            "bayNumber": 4,
            "interconnectModel": "Synergy 12Gb SAS Connection Module",
            "interconnectUri": "SasIC:CN75120D7B, interconnect 4",
        },
        {
            "bayNumber": 5,
            "interconnectModel": None,
            "interconnectUri": None,
        },
        {
            "bayNumber": 6,
            "interconnectModel": "Synergy 20Gb Interconnect Link Module",
            "interconnectUri": "IC:CN75120D7B, interconnect 6",
        }
    ],
    "type": "EnclosureV400",
    "name": "CN75120D7B",
    "enclosureTypeUri": "/rest/enclosure-types/SY12000",
    # "deviceBays": [
    # deviceBays are tested in F170.  No need to repeat.  This way, as bays are moved/changed we only
    # have to fix F170.  Ron Soto 8/15/2016
    # ]
}
]

sasics = [{
    "logicalSasInterconnectUri": None,
    "interconnectIP": "REGEX:fe80::9eb6:54ff:fe90:[a-f0-9]{4}",
    "category": "sas-interconnects",
    "state": "Monitored",
    "stateReason": None,
    "type": "sas-interconnect",
    "enclosureUri": "ENC:CN75120D7B",
    "status": "REGEX:(OK|WARNING)",
    "description": None,
    "productName": "Synergy 12Gb SAS Connection Module",
    "partNumber": "755985-B21",
    "interconnectLocation": {
        "locationEntries": [
            {
                "type": "Bay",
                "value": "1"
            },
            {
                "type": "Port",
                "value": "443"
            },
            {
                "type": "Enclosure",
                "value": "ENC:CN75120D7B"
            },
            {
                "type": "Ip",
                "value": "REGEX:fe80::9eb6:54ff:fe90:[a-f0-9]{4}"
            }
        ]
    },
    "powerState": "On",
    "name": "CN75120D7B, interconnect 1",
    "portCount": 12,
    "uri": "SasIC:CN75120D7B, interconnect 1",
    "enclosureName": "CN75120D7B",
    "sasLogicalInterconnectUri": None,
    "sasPorts": [
        {
            "type": "sas-port",
            "portName": "12",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "12",
            "portLocation": "12",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "12",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "8",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "8",
            "portLocation": "8",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "8",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "11",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "11",
            "portLocation": "11",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "11",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "7",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "7",
            "portLocation": "7",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "7",
            "state": "Linked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "6",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "6",
            "portLocation": "6",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "6",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "9",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "9",
            "portLocation": "9",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "9",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "2",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "2",
            "portLocation": "2",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "2",
            "state": "Linked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "4",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "4",
            "portLocation": "4",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "4",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "3",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "3",
            "portLocation": "3",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "3",
            "state": "Linked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "10",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "10",
            "portLocation": "10",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "10",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "1",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "1",
            "portLocation": "1",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "1",
            "state": "Linked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "5",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "5",
            "portLocation": "5",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "5",
            "state": "Linked",
            "category": "sas-ports",
        }
    ],
    "model": "Synergy 12Gb SAS Connection Module"
},
    {
    "logicalSasInterconnectUri": None,
    "interconnectIP": "REGEX:fe80::9eb6:54ff:fe90:[a-f0-9]{4}",
    "category": "sas-interconnects",
    "state": "Monitored",
    "stateReason": None,
    "type": "sas-interconnect",
    "enclosureUri": "ENC:CN75120D7B",
    "status": "REGEX:(OK|WARNING)",
    "description": None,
    "productName": "Synergy 12Gb SAS Connection Module",
    "partNumber": "755985-B21",
    "interconnectLocation": {
        "locationEntries": [
            {
                "type": "Bay",
                "value": "4"
            },
            {
                "type": "Port",
                "value": "443"
            },
            {
                "type": "Enclosure",
                "value": "ENC:CN75120D7B"
            },
            {
                "type": "Ip",
                "value": "REGEX:fe80::9eb6:54ff:fe90:[a-f0-9]{4}"
            }
        ]
    },
    "powerState": "On",
    "name": "CN75120D7B, interconnect 4",
    "portCount": 12,
    "uri": "SasIC:CN75120D7B, interconnect 4",
    "enclosureName": "CN75120D7B",
    "sasLogicalInterconnectUri": None,
    "sasPorts": [
        {
            "type": "sas-port",
            "portName": "12",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "12",
            "portLocation": "12",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "12",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "8",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "8",
            "portLocation": "8",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "8",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "11",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "11",
            "portLocation": "11",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "11",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "7",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "7",
            "portLocation": "7",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "7",
            "state": "Linked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "6",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "6",
            "portLocation": "6",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "6",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "9",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "9",
            "portLocation": "9",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "9",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "2",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "2",
            "portLocation": "2",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "2",
            "state": "Linked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "4",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "4",
            "portLocation": "4",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "4",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "3",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "3",
            "portLocation": "3",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "3",
            "state": "Linked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "10",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "10",
            "portLocation": "10",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "10",
            "state": "Unlinked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "1",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "1",
            "portLocation": "1",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "1",
            "state": "Linked",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "5",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "5",
            "portLocation": "5",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "5",
            "state": "Linked",
            "category": "sas-ports",
        }
    ],
    "model": "Synergy 12Gb SAS Connection Module"
}
]

verify_sasics_no_port_state = [{
    "logicalSasInterconnectUri": None,
    "interconnectIP": "REGEX:fe80::9eb6:54ff:fe90:[a-f0-9]{4}",
    "category": "sas-interconnects",
    "state": "Monitored",
    "stateReason": None,
    "type": "sas-interconnect",
    "enclosureUri": "ENC:CN75120D7B",
    "status": "REGEX:(OK|WARNING)",
    "description": None,
    "productName": "Synergy 12Gb SAS Connection Module",
    "partNumber": "755985-B21",
    "interconnectLocation": {
        "locationEntries": [
            {
                "type": "Bay",
                "value": "1"
            },
            {
                "type": "Port",
                "value": "443"
            },
            {
                "type": "Enclosure",
                "value": "ENC:CN75120D7B"
            },
            {
                "type": "Ip",
                "value": "REGEX:fe80::9eb6:54ff:fe90:[a-f0-9]{4}"
            }
        ]
    },
    "powerState": "On",
    "name": "CN75120D7B, interconnect 1",
    "portCount": 12,
    "uri": "SasIC:CN75120D7B, interconnect 1",
    "enclosureName": "CN75120D7B",
    "sasLogicalInterconnectUri": None,
    "sasPorts": [
        {
            "type": "sas-port",
            "portName": "12",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "12",
            "portLocation": "12",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "12",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "8",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "8",
            "portLocation": "8",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "8",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "11",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "11",
            "portLocation": "11",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "11",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "7",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "7",
            "portLocation": "7",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "7",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "6",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "6",
            "portLocation": "6",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "6",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "9",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "9",
            "portLocation": "9",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "9",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "2",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "2",
            "portLocation": "2",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "2",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "4",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "4",
            "portLocation": "4",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "4",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "3",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "3",
            "portLocation": "3",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "3",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "10",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "10",
            "portLocation": "10",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "10",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "1",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "1",
            "portLocation": "1",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "1",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "5",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "5",
            "portLocation": "5",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 1",
            "enabled": True,
            "description": None,
            "name": "5",
            "category": "sas-ports",
        }
    ],
    "model": "Synergy 12Gb SAS Connection Module"
},
    {
    "logicalSasInterconnectUri": None,
    "interconnectIP": "REGEX:fe80::9eb6:54ff:fe90:[a-f0-9]{4}",
    "category": "sas-interconnects",
    "state": "Monitored",
    "stateReason": None,
    "type": "sas-interconnect",
    "enclosureUri": "ENC:CN75120D7B",
    "status": "REGEX:(OK|WARNING)",
    "description": None,
    "productName": "Synergy 12Gb SAS Connection Module",
    "partNumber": "755985-B21",
    "interconnectLocation": {
        "locationEntries": [
            {
                "type": "Bay",
                "value": "4"
            },
            {
                "type": "Port",
                "value": "443"
            },
            {
                "type": "Enclosure",
                "value": "ENC:CN75120D7B"
            },
            {
                "type": "Ip",
                "value": "REGEX:fe80::9eb6:54ff:fe90:[a-f0-9]{4}"
            }
        ]
    },
    "powerState": "On",
    "name": "CN75120D7B, interconnect 4",
    "portCount": 12,
    "uri": "SasIC:CN75120D7B, interconnect 4",
    "enclosureName": "CN75120D7B",
    "sasLogicalInterconnectUri": None,
    "sasPorts": [
        {
            "type": "sas-port",
            "portName": "12",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "12",
            "portLocation": "12",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "12",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "8",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "8",
            "portLocation": "8",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "8",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "11",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "11",
            "portLocation": "11",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "11",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "7",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "7",
            "portLocation": "7",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "7",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "6",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "6",
            "portLocation": "6",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "6",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "9",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "9",
            "portLocation": "9",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "9",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "2",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "2",
            "portLocation": "2",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "2",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "4",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "4",
            "portLocation": "4",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "4",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "3",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "3",
            "portLocation": "3",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "3",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "10",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "10",
            "portLocation": "10",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "10",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "1",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "1",
            "portLocation": "1",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "1",
            "category": "sas-ports",
        },
        {
            "type": "sas-port",
            "portName": "5",
            "portType": "Downlink",
            "portStatusReason": "None",
            "phyCount": 4,
            "portIdentifier": "5",
            "portLocation": "5",
            "containerDeviceUri": "SasIC:CN75120D7B, interconnect 4",
            "enabled": True,
            "description": None,
            "name": "5",
            "category": "sas-ports",
        }
    ],
    "model": "Synergy 12Gb SAS Connection Module"
}
]
