''' Data variable file of 164.102 '''
# pylint: disable=invalid-name
# from winnt import NULL
# from requests.api import patch

admin_credentials = {'userName': 'Administrator', 'password': 'admin123'}
ov_appliances = ['fe80::1602:ecff:fe45:eef8', 'fe80::32e1:71ff:fe68:1ba0']
MAC = "14:02:ec:45:ee:f8"
i3s_appliances = [
    'fe80::9eb6:54ff:fe98:c120',
    'fe80::9eb6:54ff:fe98:6628',
    'fe80::1602:ecff:fe46:2730',
    'fe80::9eb6:54ff:fe98:b200']
i3s_enclosure = ['SGH708YL2T', 'MXQ64805PF', 'MXQ64803PV', 'MXQ64801LT']
enclosures_count = '6'
DEFAULT_USER = 'Administrator'
status = '200'
NEW_PASSWORD = 'admin123'
CLUSTERIP = '15.212.164.102'
OV_ACTIVE = 'fe80::1602:ecff:fe45:eef8'
build_server = 'fe80::9932:1c50:6353:7a9'
support_dump_loc = r'C:\support_dump\sd'

fusion_IP = '15.212.164.102'

network = {"type": "ApplianceNetworkConfiguration",
           "applianceNetworks": [{"activeNode": 1,
                                  "unconfigure": False,
                                  "app1Ipv4Addr": "15.212.164.103",
                                  "app1Ipv6Addr": "",
                                  "app2Ipv4Addr": "15.212.164.104",
                                  "app2Ipv6Addr": "",
                                  "virtIpv4Addr": "15.212.164.102",
                                  "virtIpv6Addr": None,
                                  "app1Ipv4Alias": None,
                                  "app1Ipv6Alias": None,
                                  "app2Ipv4Alias": None,
                                  "app2Ipv6Alias": None,
                                  "hostname": "EB2509.test.local",
                                  "confOneNode": True,
                                  "interfaceName": "",
                                  "macAddress": "14:02:ec:45:ee:f8",
                                  "ipv4Type": "STATIC",
                                  "ipv6Type": "UNCONFIGURE",
                                  "overrideIpv4DhcpDnsServers": False,
                                  "ipv4Subnet": "255.255.252.0",
                                  "ipv4Gateway": "15.212.164.1",
                                  "ipv6Subnet": None,
                                  "ipv6Gateway": None,
                                  "domainName": "test.local",
                                  "searchDomains": [],
                                  "ipv4NameServers": [],
                                  "ipv6NameServers": [","],
                                  "bondedTo": None,
                                  "aliasDisabled": True}]}

servers = [{'serverHardwareUri': 'MXQ64805PF, bay 2',
            'serverHardwareTypeUri': 'SY 620 Gen9 1'},
           {'serverHardwareUri': 'SGH708YL2T, bay 5',
            'serverHardwareTypeUri': 'SY 480 Gen9 1'}]

iscsi_subnet = {'type': 'Subnet', 'gateway': '192.168.0.1',
                'networkId': '192.168.0.0', 'subnetmask': '255.255.0.0',
                'dnsServers': [], 'domain': 'deploy.local'}

mgmt_subnet = {
    'type': 'Subnet',
    'gateway': '15.212.164.1',
    'networkId': '15.212.164.0',
    'subnetmask': '255.255.252.0',
    'dnsServers': [
        '16.110.135.51',
        '16.110.135.52'],
    'domain': 'test.local'}

iscsi_ipv4ranges = {
    'type': 'Range',
    'networkId': '192.168.0.0',
    'startAddress': '192.168.20.100',
    'endAddress': '192.168.20.200',
    'name': 'iscsi_nw',
    'subnetUri': ' '}

mgmt_ipv4ranges = {
    'type': 'Range',
    'networkId': '15.212.164.0',
    'startAddress': '15.212.164.105',
    'endAddress': '15.212.164.117',
    'name': 'mgmt_nw',
    'subnetUri': ' '}

sd_body = [{"encrypt": False,
            "errorCode": "CI",
            "userName": "administrator",
            "password": "admin123"},
           {"encrypt": True,
            "errorCode": "CI",
            "userName": "backup",
            "password": "admin123"},
           {"encrypt": False,
            "errorCode": "CI"}]

iscsi_network = {'vlanId': '149', 'networkId': '192.168.0.0',
                 'ethernetNetworkType': 'Tagged', 'subnetUri': '',
                 'purpose': 'ISCSI', 'name': 'iscsi_nw',
                 'smartLink': False, 'privateNetwork': False,
                 'connectionTemplateUri': None, 'type': 'ethernet-networkV4'}

mgmt_network = {'vlanId': '0', 'networkId': '15.212.164.0',
                'ethernetNetworkType': 'Untagged', 'subnetUri': '',
                'purpose': 'Management', 'name': 'mgmt_nw',
                'smartLink': False, 'privateNetwork': False,
                'connectionTemplateUri': None, 'type': 'ethernet-networkV4'}

lig_tbird_3enc1 = {'type': 'logical-interconnect-groupV7',
                   'ethernetSettings': {'type': 'EthernetInterconnectSettingsV7',
                                        'enableIgmpSnooping': False,
                                        'igmpIdleTimeoutInterval': 260,
                                        'enableFastMacCacheFailover': True,
                                        'macRefreshInterval': 5,
                                        'enableNetworkLoopProtection': True,
                                        'enablePauseFloodProtection': True,
                                        'enableRichTLV': False,
                                        'interconnectType': 'Ethernet',
                                        'dependentResourceUri': None,
                                        'name': 'defaultEthernetSwitchSettings',
                                        'category': None,
                                        'uri': '/ethernetSettings'},
                   'description': None,
                   'name': 'LIG-3encprimay',
                   'interconnectMapTemplate': [{'bay': 3,
                                                'enclosure': 1,
                                                'type': 'Virtual Connect SE 40Gb F8 Module for Synergy',
                                                'enclosureIndex': 1},
                                               {'bay': 6,
                                                'enclosure': 2,
                                                'type': 'Virtual Connect SE 40Gb F8 Module for Synergy',
                                                'enclosureIndex': 2},
                                               {'bay': 6,
                                                'enclosure': 1,
                                                'type': 'Synergy 10Gb Interconnect Link Module',
                                                'enclosureIndex': 1},
                                               {'bay': 3,
                                                'enclosure': 2,
                                                'type': 'Synergy 10Gb Interconnect Link Module',
                                                'enclosureIndex': 2},
                                               {'bay': 6,
                                                'enclosure': 3,
                                                'type': 'Synergy 10Gb Interconnect Link Module',
                                                'enclosureIndex': 3},
                                               {'bay': 3,
                                                'enclosure': 3,
                                                'type': 'Synergy 10Gb Interconnect Link Module',
                                                'enclosureIndex': 3}],
                   'enclosureType': 'SY12000',
                   'enclosureIndexes': [1,
                                        2,
                                        3],
                   'interconnectBaySet': '3',
                   'redundancyType': 'HighlyAvailable',
                   'internalNetworkUris': [],
                   'snmpConfiguration': {'type': 'snmp-configuration',
                                         'v3Enabled': True,
                                         'readCommunity': 'public',
                                         'systemContact': '',
                                         'snmpAccess': None,
                                         'enabled': True,
                                         'description': None,
                                         'name': None,
                                         'state': None,
                                         'category': 'snmp-configuration'},
                   'qosConfiguration': None,
                   'uplinkSets': [{'networkUris': ['iscsi_nw'],
                                   'mode':'Auto',
                                   'lacpTimer':'Short',
                                   'primaryPort':None,
                                   'logicalPortConfigInfos':[{'enclosure': '1',
                                                              'bay': '3',
                                                              'port': 'Q1:1',
                                                              'speed': 'Auto'},
                                                             {'enclosure': '1',
                                                              'bay': '3',
                                                              'port': 'Q2:1',
                                                              'speed': 'Auto'},
                                                             {'enclosure': '2',
                                                              'bay': '6',
                                                              'port': 'Q1:1',
                                                              'speed': 'Auto'},
                                                             {'enclosure': '2',
                                                              'bay': '6',
                                                              'port': 'Q2:1',
                                                              'speed': 'Auto'}],
                                   'name': 'uplink_3encl',
                                   'networkType': 'Ethernet',
                                   'ethernetNetworkType': 'ImageStreamer'},
                                  {'networkUris': ['mgmt_nw'],
                                   'mode':'Auto',
                                   'lacpTimer':'Short',
                                   'primaryPort':None,
                                   'nativeNetworkUri': None,
                                   'logicalPortConfigInfos':[{'enclosure': '1',
                                                              'bay': '3',
                                                              'port': 'Q4:1',
                                                              'speed': 'Auto'},
                                                             {'enclosure': '2',
                                                              'bay': '6',
                                                              'port': 'Q4:1',
                                                              'speed': 'Auto'}],
                                   'networkType': 'Ethernet',
                                   'ethernetNetworkType': 'Untagged',
                                   'name': 'uplink_2'}]}
lig_tbird_3enc2 = {'type': 'logical-interconnect-groupV7',
                   'ethernetSettings': {'type': 'EthernetInterconnectSettingsV7',
                                        'enableIgmpSnooping': False,
                                        'igmpIdleTimeoutInterval': 260,
                                        'enableFastMacCacheFailover': True,
                                        'macRefreshInterval': 5,
                                        'enableNetworkLoopProtection': True,
                                        'enablePauseFloodProtection': True,
                                        'enableRichTLV': False,
                                        'interconnectType': 'Ethernet',
                                        'dependentResourceUri': None,
                                        'name': 'defaultEthernetSwitchSettings',
                                        'category': None,
                                        'uri': '/ethernetSettings'},
                   'description': None,
                   'name': 'LIG-3encSecondary',
                   'interconnectMapTemplate': [{'bay': 3,
                                                'enclosure': 1,
                                                'type': 'Virtual Connect SE 40Gb F8 Module for Synergy',
                                                'enclosureIndex': 1},
                                               {'bay': 6,
                                                'enclosure': 2,
                                                'type': 'Virtual Connect SE 40Gb F8 Module for Synergy',
                                                'enclosureIndex': 2},
                                               {'bay': 6,
                                                'enclosure': 1,
                                                'type': 'Synergy 20Gb Interconnect Link Module',
                                                'enclosureIndex': 1},
                                               {'bay': 3,
                                                'enclosure': 2,
                                                'type': 'Synergy 20Gb Interconnect Link Module',
                                                'enclosureIndex': 2},
                                               {'bay': 6,
                                                'enclosure': 3,
                                                'type': 'Synergy 20Gb Interconnect Link Module',
                                                'enclosureIndex': 3},
                                               {'bay': 3,
                                                'enclosure': 3,
                                                'type': 'Synergy 20Gb Interconnect Link Module',
                                                'enclosureIndex': 3}],
                   'enclosureType': 'SY12000',
                   'enclosureIndexes': [1,
                                        2,
                                        3],
                   'interconnectBaySet': '3',
                   'redundancyType': 'HighlyAvailable',
                   'internalNetworkUris': [],
                   'snmpConfiguration': {'type': 'snmp-configuration',
                                         'v3Enabled': True,
                                         'readCommunity': 'public',
                                         'systemContact': '',
                                         'snmpAccess': None,
                                         'enabled': True,
                                         'description': None,
                                         'name': None,
                                         'state': None,
                                         'category': 'snmp-configuration'},
                   'qosConfiguration': None,
                   'uplinkSets': [{'networkUris': ['iscsi_nw'],
                                   'mode':'Auto',
                                   'lacpTimer':'Short',
                                   'primaryPort':None,
                                   'logicalPortConfigInfos':[{'enclosure': '1',
                                                              'bay': '3',
                                                              'port': 'Q1:1',
                                                              'speed': 'Auto'},
                                                             {'enclosure': '1',
                                                              'bay': '3',
                                                              'port': 'Q2:1',
                                                              'speed': 'Auto'},
                                                             {'enclosure': '2',
                                                              'bay': '6',
                                                              'port': 'Q1:1',
                                                              'speed': 'Auto'},
                                                             {'enclosure': '2',
                                                              'bay': '6',
                                                              'port': 'Q2:1',
                                                              'speed': 'Auto'}],
                                   'name': 'uplink_3encl',
                                   'networkType': 'Ethernet',
                                   'ethernetNetworkType': 'ImageStreamer'},
                                  {'networkUris': ['mgmt_nw'],
                                   'mode':'Auto',
                                   'lacpTimer':'Short',
                                   'primaryPort':None,
                                   'nativeNetworkUri': None,
                                   'logicalPortConfigInfos':[{'enclosure': '1',
                                                              'bay': '3',
                                                              'port': 'Q4:1',
                                                              'speed': 'Auto'},
                                                             {'enclosure': '2',
                                                              'bay': '6',
                                                              'port': 'Q4:1',
                                                              'speed': 'Auto'}],
                                   'networkType': 'Ethernet',
                                   'ethernetNetworkType': 'Untagged',
                                   'name': 'uplink_2'}]}

enc_groups_tbird_3enc1 = {'name': 'EG-3encprimay',
                          'powerMode': 'RedundantPowerFeed',
                          'ambientTemperatureMode': 'Standard',
                          'ipAddressingMode': 'External',
                          'ipRangeUris': [],
                          'enclosureCount': 3,
                          'configurationScript': None,
                          'osDeploymentSettings': {'manageOSDeployment': True,
                                                   'deploymentModeSettings': {'deploymentMode': 'Internal',
                                                                              'deploymentNetworkUri': None}},
                          'interconnectBayMappings': [{'interconnectBay': 3,
                                                       'logicalInterconnectGroupUri': 'LIG:LIG-3encprimay'},
                                                      {'interconnectBay': 6,
                                                       'logicalInterconnectGroupUri': 'LIG:LIG-3encprimay'}]}
enc_groups_tbird_3enc2 = {'name': 'EG-3encsecondary',
                          'powerMode': 'RedundantPowerFeed',
                          'ambientTemperatureMode': 'Standard',
                          'ipAddressingMode': 'External',
                          'ipRangeUris': [],
                          'enclosureCount': 3,
                          'configurationScript': None,
                          'osDeploymentSettings': {'manageOSDeployment': True,
                                                   'deploymentModeSettings': {'deploymentMode': 'Internal',
                                                                              'deploymentNetworkUri': None}},
                          'interconnectBayMappings': [{'interconnectBay': 3,
                                                       'logicalInterconnectGroupUri': 'LIG:LIG-3encSecondary'},
                                                      {'interconnectBay': 6,
                                                       'logicalInterconnectGroupUri': 'LIG:LIG-3encSecondary'}]}
les_3enc1 = {
    'name': 'LE-3encprimay',
    'enclosureUris': [
        'ENC:SGH708YL2S',
        'ENC:MXQ64805PF',
        'ENC:SGH708YL2T'],
    'enclosureGroupUri': 'EG:EG-3encprimay',
    'firmwareBaselineUri': None,
    'forceInstallFirmware': False}
les_3enc2 = {
    'name': 'LE-3encsecondary',
    'enclosureUris': [
        'ENC:MXQ64801M6',
        'ENC:MXQ64803PV',
        'MXQ64801LT'],
    'enclosureGroupUri': 'EG:EG-3encsecondary',
    'firmwareBaselineUri': None,
    'forceInstallFirmware': False}
osdeploymentserver = {
    'name': 'OSDS-3enc',
    'description': 'os deployment server',
    'applianceUri': 'MXQ64805PF, appliance 2',
    'mgmtNetworkUri': ['mgmt_nw'],
    'deplManagersType': 'Image Streamer'}
