''' Use this section for the Rack Servers Only  '''
''' Use this section for the Rack Servers Only  '''
''' Use this section for the Rack Servers Only  '''

Rack_admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}
Rack_ilo_credentials = {'username': 'Administrator', 'password': 'password'}

Rack_fusion_ip = '16.83.15.129'
Rack_fusion_ssh_username = 'root'
Rack_fusion_ssh_password = 'hpvse1'
Rack_api_version = '1000'

Rack_test_server_list = [
    {
        'iLOIp': '16.83.13.67',
        'ServerName': 'ILOAF6BNP0009.lr.eml.lab',
        'userName': 'Administrator',
        'password': 'password'
    }]

Rack_test_server_list_rom_upgraded = [
    {
        'iLOIp': '16.83.13.68',
        'ServerName': 'ILOAF6BNP0026.serverenabled.com',
        'userName': 'Administrator',
        'password': 'password'
    }]

Rack_basic_compare_fields = ['Id', 'Name', 'RegistryVersion', '@odata.type']

Rack_server_hardware_type = 'server-hardware-10'
Rack_server_profile_template_type = 'ServerProfileTemplateV6'
Rack_server_profile_type = 'ServerProfileV10'

# Example "DL560 Gen10 1"
Rack_server_hardware_type_name = 'DL580 Gen10 1'

Rack_spt_overridden_setting = [
    {
        "id": "LogUefiDebugMessagesToMemory",
        "value": "Disabled"
    }]

Rack_create_sp_overridden_setting = [
    {
        "id": "LogUefiDebugMessagesToMemory",
        "value": "Enabled"
    }]

Rack_edit_sp_overridden_setting = [
    {
        "id": "LogUefiDebugMessagesToMemory",
        "value": "Disabled"
    }]

# Please keep this empty, this is used internally by the script
Rack_server_fam_and_reg_ver = {}
# Please keep this empty, this is used internally by the script
Rack_bios_details_from_sht = []

Rack_temp = Rack_server_hardware_type_name.split("Gen")
Rack_server_profile_template_name = Rack_temp[0] + 'SPT'
Rack_server_profile_template_description = Rack_server_profile_template_name + ' Description'
Rack_server_profile_name = Rack_temp[0] + "Profile"
Rack_server_profile_description = 'ServerProfileDescription'

Rack_name = Rack_test_server_list[0]['ServerName']
Rack_ip = Rack_test_server_list[0]['iLOIp']
Rack_name2 = Rack_test_server_list_rom_upgraded[0]['ServerName']
Rack_ip2 = Rack_test_server_list_rom_upgraded[0]['iLOIp']

Rack_gen10_with_profiles = [Rack_name]
Rack_gen10_names = [Rack_name]

Rack_gen10s = [
    {
        'name': Rack_name,
        'hostname': Rack_ip,
        'licensingIntent': 'OneViewNoiLO',
        'username': 'Administrator',
        'password': 'password',
        'force': True,
        'configurationState': 'Managed'
    }]

Rack_rom_upgraded_servers = [
    {
        'name': Rack_name2,
        'hostname': Rack_ip2,
        'licensingIntent': 'OneViewNoiLO',
        'username': 'Administrator',
        'password': 'password',
        'force': True,
        'configurationState': 'Managed'
    }]

Rack_gen10_profile_templates = [
    {
        "name": Rack_server_profile_template_name,
        "type": Rack_server_profile_template_type,
        "description": Rack_server_profile_template_description,
        "serverHardwareTypeUri": "SHT:" + Rack_server_hardware_type_name,
        "serverProfileDescription": Rack_server_profile_description,
        "enclosureGroupUri": "",
        "serialNumberType": "Physical",
        "macType": "Physical",
        "wwnType": "Physical",
        "affinity": None,
        "connectionSettings": {"connections": [], "manageConnections": False},
        "boot": {"manageBoot": True, "order": ["CD", "USB", "HardDisk", "PXE"]},
        "bootMode": {"manageMode": True, "mode": "BIOS", "secureBoot": "Unmanaged"},
        "firmware": None,
        "bios": {"manageBios": True, "overriddenSettings": Rack_spt_overridden_setting},
        "hideUnusedFlexNics": True,
        "iscsiInitiatorNameType": "AutoGenerated",
        "localStorage": None,
        "sanStorage": None,
        "osDeploymentSettings": None,
        "initialScopeUris": []
    }]

Rack_gen10_server_profiles = [
    {
        "name": Rack_server_profile_name,
        "description": Rack_server_profile_description,
        "serverProfileTemplateUri": "SPT:" + Rack_server_profile_template_name,
        "type": Rack_server_profile_type,
        "serverHardwareTypeUri": "SHT:" + Rack_server_hardware_type_name,
        "serverHardwareUri": "SH:" + Rack_name,
        "serialNumberType": "Physical",
        "iscsiInitiatorNameType": "AutoGenerated",
        "macType": "Physical",
        "wwnType": "Physical",
        "affinity": None,
        "connectionSettings": {"connections": []},
        "boot": {"manageBoot": True, "order": ["CD", "USB", "HardDisk", "PXE"]},
        "bootMode": {"manageMode": True, "mode": "BIOS", "secureBoot": "Unmanaged"},
        "firmware": None,
        "bios": {"manageBios": True, "overriddenSettings": Rack_create_sp_overridden_setting},
        "hideUnusedFlexNics": None,
        "osDeploymentSettings": None,
        "localStorage": None,
        "sanStorage": None,
        "initialScopeUris": []
    }]

Rack_edit_gen10_profiles = [
    {
        "name": Rack_server_profile_name,
        "description": Rack_server_profile_description + " edited",
        "type": Rack_server_profile_type,
        "serverHardwareTypeUri": "SHT:" + Rack_server_hardware_type_name,
        "serverHardwareUri": "SH:" + Rack_name,
        "iscsiInitiatorName": None,
        "iscsiInitiatorNameType": "AutoGenerated",
        "affinity": None,
        "associatedServer": None,
        "hideUnusedFlexNics": True,
        "firmware": None,
        "macType": "Physical",
        "wwnType": "Physical",
        "serialNumberType": "Physical",
        "category": "server-profiles",
        "status": "OK",
        "state": "Normal",
        "connectionSettings": {"connections": []},
        "bootMode": {"manageMode": True, "mode": "BIOS", "secureBoot": "Unmanaged"},
        "boot": {"manageBoot": True, "order": ["CD", "USB", "HardDisk", "PXE"]},
        "bios": {"manageBios": True, "overriddenSettings": Rack_edit_sp_overridden_setting},
        "localStorage": None,
        "sanStorage": None,
        "osDeploymentSettings": None,
        "refreshState": "NotRefreshing"
    }]

''' Rack Servers Section Ends here  '''
''' Rack Servers Section Ends here  '''
''' Rack Servers Section Ends here  '''

''' Use this section for the C7K Blade Servers Only '''
''' Use this section for the C7K Blade Servers Only '''
''' Use this section for the C7K Blade Servers Only '''

BL_lig1_name = "LIG"
BL_eg1_name = "EG1"
BL_enc1_oa1 = "16.83.10.60"

BL_enc_groups = [
    {
        'name': BL_eg1_name,
        'configurationScript': None,
        'interconnectBayMappings': [
            {
                'interconnectBay': 1,
                'logicalInterconnectGroupUri': 'LIG:' + BL_lig1_name
            },
            {
                'interconnectBay': 3,
                'logicalInterconnectGroupUri': 'LIG:' + BL_lig1_name
            },
            {
                'interconnectBay': 4,
                'logicalInterconnectGroupUri': 'LIG:' + BL_lig1_name
            }]
    }]

BL_enclosures = [
    {
        'hostname': BL_enc1_oa1,
        'username': 'Administrator',
        'password': 'HPHPHPHP',
        'enclosureGroupUri': 'EG:' + BL_eg1_name,
        'force': True,
        'licensingIntent': 'OneView',
        "firmwareBaselineUri": None
    }]

BL_admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}
BL_ilo_credentials = {'username': 'Administrator', 'password': 'password'}

BL_fusion_ip = '16.83.14.227'
BL_fusion_ssh_username = 'root'
BL_fusion_ssh_password = 'hpvse1'
BL_api_version = '1000'

BL_test_server_list = [
    {
        'iLOIp': '16.83.12.176',
        'ServerName': 'PILOT-ENC-3, bay 9',
        'userName': 'Administrator',
        'password': 'password'
    }]

BL_test_server_list_rom_upgraded = [
    {
        'iLOIp': '16.83.13.191',
        'ServerName': 'PILOT-ENC-3, bay 3',
        'userName': 'Administrator',
        'password': 'password'
    }]

# Please keep this empty, this is used internally by the script
BL_server_fam_and_reg_ver = {}
# Please keep this empty, this is used internally by the script
BL_bios_details_from_sht = []

BL_basic_compare_fields = ['Id', 'Name', 'RegistryVersion', '@odata.type']

# Example "DL560 Gen10 1"
BL_server_hardware_type_name = 'BL460c Gen10 Graphics Exp 1'

BL_spt_overridden_setting = [
    {
        "id": "LogUefiDebugMessagesToMemory",
        "value": "Enabled"
    }]

BL_create_sp_overridden_setting = [
    {
        "id": "LogUefiDebugMessagesToMemory",
        "value": "Enabled"
    }]

BL_edit_sp_overridden_setting = [
    {
        "id": "LogUefiDebugMessagesToMemory",
        "value": "Disabled"
    }]

BL_temp = BL_server_hardware_type_name.split("Gen")
BL_server_profile_template_name = BL_temp[0] + 'SPT'
BL_server_profile_template_description = BL_server_profile_template_name + ' Description'
BL_server_profile_name = BL_temp[0] + "Profile"
BL_server_profile_description = 'ServerProfileDescription'
BL_server_hardware_type = 'server-hardware-10'
BL_server_profile_template_type = 'ServerProfileTemplateV6'
BL_server_profile_type = 'ServerProfileV10'

BL_name = BL_test_server_list[0]['ServerName']
BL_ip = BL_test_server_list[0]['iLOIp']
BL_name2 = BL_test_server_list_rom_upgraded[0]['ServerName']
BL_ip2 = BL_test_server_list_rom_upgraded[0]['iLOIp']

BL_gen10_with_profiles = [BL_name]
BL_gen10_names = [BL_name]

BL_gen10s = [
    {
        'name': BL_name,
        'hostname': BL_ip,
        'licensingIntent': 'OneViewNoiLO',
        'username': 'Administrator',
        'password': 'password',
        'force': True,
        'configurationState': 'Managed'
    }]

BL_rom_upgraded_servers = [
    {
        'name': BL_name2,
        'hostname': BL_ip2,
        'licensingIntent': 'OneViewNoiLO',
        'username': 'Administrator',
        'password': 'password',
        'force': True,
        'configurationState': 'Managed'
    }]

BL_gen10_profile_templates = [
    {
        "type": BL_server_profile_template_type,
        "serverProfileDescription": BL_server_profile_description,
        "serverHardwareTypeUri": "SHT:" + BL_server_hardware_type_name,
        "enclosureGroupUri": 'EG:' + BL_eg1_name,
        "serialNumberType": "Virtual",
        "macType": "Virtual",
        "wwnType": "Virtual",
        "name": BL_server_profile_template_name,
        "description": BL_server_profile_template_description,
        "affinity": "Bay",
        "connectionSettings": {"connections": [], "manageConnections": False},
        "boot": {"manageBoot": True, "order": ["CD", "USB", "HardDisk", "PXE"]},
        "bootMode": {"manageMode": True, "mode": "BIOS", "secureBoot": "Unmanaged"},
        "firmware": None,
        "bios": {"manageBios": True, "overriddenSettings": BL_spt_overridden_setting},
        "hideUnusedFlexNics": True,
        "iscsiInitiatorNameType": "AutoGenerated",
        "localStorage": None,
        "sanStorage": None,
        "osDeploymentSettings": None
    }]

BL_gen10_server_profiles = [
    {
        "type": BL_server_profile_type,
        "serverHardwareUri": "SH:" + BL_name,
        "serverHardwareTypeUri": "SHT:" + BL_server_hardware_type_name,
        "serverProfileTemplateUri": "SPT:" + BL_server_profile_template_name,
        "serialNumberType": "Virtual",
        "iscsiInitiatorNameType": "AutoGenerated",
        "macType": "Virtual",
        "wwnType": "Virtual",
        "name": BL_server_profile_name,
        "description": BL_server_profile_description,
        "affinity": "Bay",
        "connectionSettings": {"connections": []},
        "boot": {"manageBoot": True, "order": ["CD", "USB", "HardDisk", "PXE"]},
        "bootMode": {"manageMode": True, "mode": "BIOS", "secureBoot": "Unmanaged"},
        "firmware": None,
        "bios": {"manageBios": True, "overriddenSettings": BL_create_sp_overridden_setting},
        "hideUnusedFlexNics": True,
        "iscsiInitiatorName": "",
        "osDeploymentSettings": None,
        "localStorage": None,
        "sanStorage": None
    }]

BL_edit_gen10_profiles = [
    {
        "type": BL_server_profile_type,
        "name": BL_server_profile_name,
        "description": BL_server_profile_description + "edited",
        "iscsiInitiatorNameType": "AutoGenerated",
        "serverHardwareUri": "SH:" + BL_name,
        "serverHardwareTypeUri": "SHT:" + BL_server_hardware_type_name,
        "affinity": "Bay",
        "hideUnusedFlexNics": True,
        "firmware": None,
        "macType": "Virtual",
        "wwnType": "Virtual",
        "serialNumberType": "Virtual",
        "category": "server-profiles",
        "status": "OK",
        "state": "Normal",
        "connectionSettings": {"connections": []},
        "bootMode": {"manageMode": True, "mode": "BIOS", "secureBoot": "Unmanaged"},
        "boot": {"manageBoot": True, "order": ["CD", "USB", "HardDisk", "PXE"]},
        "bios": {"manageBios": True, "overriddenSettings": BL_edit_sp_overridden_setting},
        "localStorage": None,
        "sanStorage": None,
        "osDeploymentSettings": None,
        "refreshState": "NotRefreshing"
    }]

''' C7K Blade Section Ends Here '''
''' C7K Blade Section Ends Here '''
''' C7K Blade Section Ends Here '''

''' Use this section for the Synergy Servers Only'''
''' Use this section for the Synergy Servers Only'''
''' Use this section for the Synergy Servers Only'''

Syn_fusion_ip = '16.83.10.14'
Syn_fusion_ssh_username = 'root'
Syn_fusion_ssh_password = 'hpvse1'
Syn_api_version = '1000'

Syn_lig1_name = "LIG"
Syn_eg1_name = "EEST_EnclosureGroup"
Syn_enc1_oa1 = "16.83.10.14"

Syn_enc_groups = [
    {
        'name': Syn_eg1_name,
        'configurationScript': None,
        'interconnectBayMappings': [
            {
                'interconnectBay': 1,
                'logicalInterconnectGroupUri': 'LIG:' + Syn_lig1_name
            },
            {
                'interconnectBay': 3,
                'logicalInterconnectGroupUri': 'LIG:' + Syn_lig1_name
            },
            {
                'interconnectBay': 4,
                'logicalInterconnectGroupUri': 'LIG:' + Syn_lig1_name
            }]
    }]

Syn_enclosures = [
    {
        'hostname': Syn_enc1_oa1,
        'username': 'Administrator',
        'password': 'hpvse123',
        'enclosureGroupUri': 'EG:' + Syn_eg1_name,
        'force': True,
        'licensingIntent': 'OneView',
        "firmwareBaselineUri": None
    }]

Syn_admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}
Syn_ilo_credentials = {'username': 'Administrator', 'password': 'password'}

Syn_test_server_list = [
    {
        'iLOIp': '16.83.13.85',
        'ServerName': 'CN744502CH, bay 1',
        'userName': 'Administrator',
        'password': 'password'
    }]

Syn_test_server_list_rom_upgraded = [
    {
        'iLOIp': '16.83.14.186',
        'ServerName': 'CN744502CH, bay 9',
        'userName': 'Administrator',
        'password': 'password'
    }]

# Please keep this empty, this is used internally by the script
Syn_server_fam_and_reg_ver = {}
# Please keep this empty, this is used internally by the script
Syn_bios_details_from_sht = []

Syn_basic_compare_fields = ['Id', 'Name', 'RegistryVersion', '@odata.type']

Syn_server_hardware_type_name = 'SY 480 Gen10 2'
# Example "SY 480 Gen10 1"

Syn_spt_overridden_setting = [
    {
        "id": "PciSlot1Bifurcation",
        "value": "Auto"
    }]

Syn_create_sp_overridden_setting = [
    {
        "id": "AcpiWatchdogTimer",
        "value": "SlotBifurcated"
    }]

Syn_edit_sp_overridden_setting = [
    {
        "id": "AcpiWatchdogTimer",
        "value": "SlotBifurcated"
    }]

Syn_temp = Syn_server_hardware_type_name.split("Gen")
Syn_server_profile_template_name = Syn_temp[0] + 'SPT'
Syn_server_profile_template_description = Syn_server_profile_template_name + ' Description'
Syn_server_profile_name = Syn_temp[0] + "Profile"
Syn_server_profile_description = 'ServerProfileDescription'

Syn_server_hardware_type = 'server-hardware-10'
Syn_server_profile_template_type = 'ServerProfileTemplateV6'
Syn_server_profile_type = 'ServerProfileV10'

Syn_name = Syn_test_server_list[0]['ServerName']
Syn_ip = Syn_test_server_list[0]['iLOIp']
Syn_name2 = Syn_test_server_list_rom_upgraded[0]['ServerName']
Syn_ip2 = Syn_test_server_list_rom_upgraded[0]['iLOIp']

Syn_gen10_syns_with_profiles = [Syn_name]
Syn_gen10_syns_names = [Syn_name]

Syn_gen10_syns = [
    {
        'name': Syn_name,
        'hostname': Syn_ip,
        'licensingIntent': 'OneViewNoiLO',
        'username': 'Administrator',
        'password': 'password',
        'force': True,
        'configurationState': 'Managed'
    }]

Syn_rom_upgraded_servers = [
    {
        'name': Syn_name2,
        'hostname': Syn_ip2,
        'licensingIntent': 'OneViewNoiLO',
        'username': 'Administrator',
        'password': 'password',
        'force': True,
        'configurationState': 'Managed'
    }]

Syn_gen10_profile_templates = [
    {
        "type": Syn_server_profile_template_type,
        "serverProfileDescription": Syn_server_profile_description,
        "serverHardwareTypeUri": "SHT:" + Syn_server_hardware_type_name,
        "enclosureGroupUri": "EG:" + Syn_eg1_name,
        "serialNumberType": "Virtual",
        "macType": "Virtual",
        "wwnType": "Virtual",
        "name": Syn_server_profile_template_name,
        "description": BL_server_profile_template_description,
        "affinity": "Bay",
        "connectionSettings": {"connections": [], "manageConnections": False},
        "boot": {"manageBoot": True, "order": ["CD", "USB", "HardDisk", "PXE"]},
        "bootMode": {"manageMode": True, "mode": "BIOS", "secureBoot": "Unmanaged"},
        "firmware": None,
        "bios": {"manageBios": True, "overriddenSettings": Syn_spt_overridden_setting},
        "hideUnusedFlexNics": True,
        "iscsiInitiatorNameType": "AutoGenerated",
        "localStorage": None,
        "sanStorage": None,
        "osDeploymentSettings": None
    }]

Syn_gen10_server_profiles = [
    {
        "type": Syn_server_profile_type,
        "serverHardwareUri": "SH:" + Syn_name,
        "serverHardwareTypeUri": "SHT:" + Syn_server_hardware_type_name,
        "serverProfileTemplateUri": "SPT:" + Syn_server_profile_template_name,
        "serialNumberType": "Virtual",
        "iscsiInitiatorNameType": "AutoGenerated",
        "macType": "Virtual",
        "wwnType": "Virtual",
        "name": Syn_server_profile_name,
        "description": Syn_server_profile_description,
        "affinity": "Bay",
        "connectionSettings": {"connections": []},
        "boot": {"manageBoot": True, "order": ["CD", "USB", "HardDisk", "PXE"]},
        "bootMode": {"manageMode": True, "mode": "BIOS", "secureBoot": "Unmanaged"},
        "firmware": None,
        "bios": {"manageBios": True, "overriddenSettings": Syn_create_sp_overridden_setting},
        "hideUnusedFlexNics": True,
        "iscsiInitiatorName": "",
        "osDeploymentSettings": None,
        "localStorage": None,
        "sanStorage": None
    }]

Syn_edit_gen10_profiles = [
    {
        "type": Syn_server_profile_type,
        "name": Syn_server_profile_name,
        "description": Syn_server_profile_description + "edited",
        "iscsiInitiatorNameType": "AutoGenerated",
        "serverHardwareUri": "SH:" + Syn_name,
        "serverHardwareTypeUri": "SHT:" + Syn_server_hardware_type_name,
        "affinity": "Bay",
        "hideUnusedFlexNics": True,
        "firmware": None,
        "macType": "Virtual",
        "wwnType": "Virtual",
        "serialNumberType": "Virtual",
        "category": "server-profiles",
        "status": "OK",
        "state": "Normal",
        "connectionSettings": {"connections": []},
        "bootMode": {"manageMode": True, "mode": "BIOS", "secureBoot": "Unmanaged"},
        "boot": {"manageBoot": True, "order": ["CD", "USB", "HardDisk", "PXE"]},
        "bios": {"manageBios": True, "overriddenSettings": Syn_edit_sp_overridden_setting},
        "localStorage": None,
        "sanStorage": None,
        "osDeploymentSettings": None,
        "refreshState": "NotRefreshing"
    }]

''' Synergy Section Ends Here'''
''' Synergy Section Ends Here'''
''' Synergy Section Ends Here'''
