#from winnt import NULL
from requests.api import patch

serverHardwareUri  = "CN7545061K, bay 3"
serverHardwareTypeUri = "SY 480 Gen10 1"
enclosureGroupUri= "EG-3enc"
enclosureUri = "CN7545061K"
depnetwork = "iscsi_nw"
mgmtnetwork = "mgmt_nw"

#change blob url to raw if new url is added
artifactbundle_add = [
        {'ostype': '/root/Goldenimage/HPE-ESX-4.1.zip'}
       # {'ostype': '/root/Goldenimage/RHEL-7.X-4.1.zip'},
       # {'ostype': '/root/Goldenimage/SLES-12-4.1.zip'}
]

artifactbundle = [
        {'name': 'HPE-ESX-4.1'}
       # {'name': 'RHEL-7.X-4.1'},
       # {'name': 'SLES-12-4.1'}
]

serverprofile_3enc_ManagementNIC = [
{
    "type": "ServerProfileV11",
    "serverHardwareUri": serverHardwareUri,
    "serverHardwareTypeUri": serverHardwareTypeUri,
	"serverProfileTemplateUri": None,
    "enclosureGroupUri": enclosureGroupUri,
    "enclosureUri": enclosureUri,
    "serialNumberType": "Virtual",
    "iscsiInitiatorNameType": "AutoGenerated",
    "macType": "Virtual",
    "wwnType": "Virtual",
    "name": "SP-HPE- ESXi -6.0- deploy in single frame non-HA config- 2017-12-15",
    "description": "",
    "affinity": "Bay",
    "firmware": {
        "firmwareBaselineUri": None,
        "manageFirmware": "false",
        "forceInstallFirmware": "false",
        "firmwareInstallType": None,
        "firmwareScheduleDateTime": None,
        "firmwareActivationType": None,
        "reapplyState": "NotApplying"
    },
    "connectionSettings": {
        "reapplyState": "NotApplying",
        "connections": [
            {
            "id": 1,
            "name": "Deployment Network A",
            "functionType": "Ethernet",
            "portId": "Mezz 3:1-a",
            "requestedMbps": "2500",
            "networkUri": depnetwork,
            "mac": None,
            "wwpn": "",
            "wwnn": "",
            "requestedVFs": "Auto",
            "ipv4": {
               "ipAddress": None
            },
            "boot": {
                "priority": "Primary",
            "ethernetBootType": "iSCSI",
                    "iscsi": {
                    "initiatorNameSource": "ProfileInitiatorName",
                    "firstBootTargetIp": None,
                    "secondBootTargetIp": "",
                    "secondBootTargetPort": "",
                    "initiatorName": None,
                    "bootTargetName": None,
                    "bootTargetLun": None
                    }
            }
        }, {
            "id": 3,
            "name": "c1",
            "functionType": "Ethernet",
            "portId": "Auto",
            "requestedMbps": "2500",
            "networkUri": mgmtnetwork,
            "lagName": None,
            "mac": None,
            "wwpn": None,
            "wwnn": None,
            "requestedVFs": "0",
            "ipv4": {},
            "boot": {
                "priority": "NotBootable",
                "iscsi": {}
            }
        }
        ]
    },
    "bootMode": {
        "manageMode": "true",
        "mode": "UEFIOptimized",
        "pxeBootPolicy": "Auto",
        "secureBoot": "Unmanaged"
    },
    "boot": {
        "manageBoot": "true",
        "order": [
            "HardDisk"
        ]
    },
    "bios": {
        "manageBios": "false",
        "overriddenSettings": [],
        "reapplyState": "NotApplying"
    },
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [],
        "reapplyState": "NotApplying"
    },
    "sanStorage": {
        "manageSanStorage": "false",
        "volumeAttachments": [],
        "sanSystemCredentials": [],
        "reapplyState": "NotApplying"
    },
    "osDeploymentSettings": {
        "osDeploymentPlanUri": "HPE- ESXi - deploy in single frame non-HA config- 2017-12-15",
        "forceOsDeployment": "false",
        "osCustomAttributes": [
            {
                "name": "ManagementNIC.dhcp",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.ipaddress",
                "value": "15.212.164.176",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.ipv4disable",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.networkuri",
                "value": mgmtnetwork,
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.dns1",
                "value": "16.110.135.52",
                "constraints": None,
                "type": None
            },
            {
                "name": "Hostname",
                "value": "SGH708YL3C",
                "constraints": "{\"helpText\":\"\"}",
                "type": "hostname"
            },
            {
                "name": "ManagementNIC.dns2",
                "value": "16.110.135.51",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.vlanid",
                "value": "0",
                "constraints": None,
                "type": "integer"
            },
            {
                "name": "ManagementNIC.netmask",
                "value": "255.255.252.0",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.connectionid",
                "value": "3",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.constraint",
                "value": "auto",
                "constraints": None,
                "type": None
            },
            {
                "name": "SSH",
                "value": "enabled",
                "constraints": "{\"options\":[\"enabled\",\"disabled\"]}",
                "type": "option"
            },
            {
                "name": "ManagementNIC.mac",
                "value": "8E:AF:07:F0:00:5D",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.gateway",
                "value": "15.212.164.1",
                "constraints": None,
                "type": None
            },
            {
                "name": "Password",
                "value": None,
                "constraints": None,
                "type": "password"
            },
            {
                "name": "DomainName",
                "value": "SGH708YL3C.com",
                "constraints": "{\"helpText\":\"\"}",
                "type": "fqdn"
            }
        ]
    }
},
{
    "type": "ServerProfileV11",
    "serverHardwareUri": serverHardwareUri,
    "serverHardwareTypeUri": serverHardwareTypeUri,
	"serverProfileTemplateUri": None,
    "enclosureGroupUri": enclosureGroupUri,
    "enclosureUri": enclosureUri,
    "serialNumberType": "Virtual",
    "iscsiInitiatorNameType": "AutoGenerated",
    "macType": "Virtual",
    "wwnType": "Virtual",
    "name": "SP-HPE- ESXi - 6.5-deploy in single frame non-HA config- 2017-12-15",
    "description": "",
    "affinity": "Bay",
    "firmware": {
        "firmwareBaselineUri": None,
        "manageFirmware": "false",
        "forceInstallFirmware": "false",
        "firmwareInstallType": None,
        "firmwareScheduleDateTime": None,
        "firmwareActivationType": None,
        "reapplyState": "NotApplying"
    },
    "connectionSettings": {
        "reapplyState": "NotApplying",
        "connections": [
            {
            "id": 1,
            "name": "Deployment Network A",
            "functionType": "Ethernet",
            "portId": "Mezz 3:1-a",
            "requestedMbps": "2500",
            "networkUri": depnetwork,
            "mac": None,
            "wwpn": "",
            "wwnn": "",
            "requestedVFs": "Auto",
            "ipv4": {
                "ipAddress": None
            },
            "boot": {
                "priority": "Primary",
                "ethernetBootType": "iSCSI",
                "iscsi": {
                    "initiatorNameSource": "ProfileInitiatorName",
                    "firstBootTargetIp": None,
                    "secondBootTargetIp": "",
                    "secondBootTargetPort": "",
                    "initiatorName": None,
                    "bootTargetName": None,
                    "bootTargetLun": None
                }
            }
        },  {
            "id": 3,
            "name": "c1",
            "functionType": "Ethernet",
            "portId": "Auto",
            "requestedMbps": "2500",
            "networkUri": mgmtnetwork,
            "lagName": None,
            "mac": None,
            "wwpn": None,
            "wwnn": None,
            "requestedVFs": "0",
            "ipv4": {},
            "boot": {
                "priority": "NotBootable",
                "iscsi": {}
            }
        }
        ]
    },
    "bootMode": {
        "manageMode": "true",
        "mode": "UEFIOptimized",
        "pxeBootPolicy": "Auto",
        "secureBoot": "Unmanaged"
    },
    "boot": {
        "manageBoot": "true",
        "order": [
            "HardDisk"
        ]
    },
    "bios": {
        "manageBios": "false",
        "overriddenSettings": [],
        "reapplyState": "NotApplying"
    },
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [],
        "reapplyState": "NotApplying"
    },
    "sanStorage": {
        "manageSanStorage": "false",
        "volumeAttachments": [],
        "sanSystemCredentials": [],
        "reapplyState": "NotApplying"
    },
    "osDeploymentSettings": {
        "osDeploymentPlanUri": "HPE- ESXi - 6.5-deploy in single frame non-HA config- 2017-12-15",
        "forceOsDeployment": "false",
        "osCustomAttributes": [
            {
                "name": "ManagementNIC.dhcp",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.ipaddress",
                "value": "15.212.164.176",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.ipv4disable",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.networkuri",
                "value": mgmtnetwork,
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.dns1",
                "value": "16.110.135.52",
                "constraints": None,
                "type": None
            },
            {
                "name": "Hostname",
                "value": "SGH708YL3C",
                "constraints": "{\"helpText\":\"\"}",
                "type": "hostname"
            },
            {
                "name": "ManagementNIC.dns2",
                "value": "16.110.135.51",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.vlanid",
                "value": "0",
                "constraints": None,
                "type": "integer"
            },
            {
                "name": "ManagementNIC.netmask",
                "value": "255.255.252.0",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.connectionid",
                "value": "3",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.constraint",
                "value": "auto",
                "constraints": None,
                "type": None
            },
            {
                "name": "SSH",
                "value": "enabled",
                "constraints": "{\"options\":[\"enabled\",\"disabled\"]}",
                "type": "option"
            },
            {
                "name": "ManagementNIC.mac",
                "value": "8E:AF:07:F0:00:5D",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.gateway",
                "value": "15.212.164.1",
                "constraints": None,
                "type": None
            },
            {
                "name": "Password",
                "value": None,
                "constraints": None,
                "type": "password"
            },
            {
                "name": "DomainName",
                "value": "SGH708YL3C.com",
                "constraints": "{\"helpText\":\"\"}",
                "type": "fqdn"
            }
        ]
    }
}
]

serverprofile_3enc_TeamNIC = [
{
    "type": "ServerProfileV11",
    "serverHardwareUri": serverHardwareUri,
    "serverHardwareTypeUri": serverHardwareTypeUri,
	"serverProfileTemplateUri": None,
    "enclosureGroupUri": enclosureGroupUri,
    "enclosureUri": enclosureUri,
    "serialNumberType": "Virtual",
    "iscsiInitiatorNameType": "AutoGenerated",
    "macType": "Virtual",
    "wwnType": "Virtual",
    "name": "SP-HPE - ESXi 6.0- deploy with multiple management NIC HA config- 2017-12-15",
    "description": "",
    "affinity": "Bay",
    "firmware": {
        "firmwareBaselineUri": None,
        "manageFirmware": "false",
        "forceInstallFirmware": "false",
        "firmwareInstallType": None,
        "firmwareScheduleDateTime": None,
        "firmwareActivationType": None,
        "reapplyState": "NotApplying"
    },
    "connectionSettings": {
        "reapplyState": "NotApplying",
        "connections": [{
            "id": 1,
            "name": "Deployment Network A",
            "functionType": "Ethernet",
            "portId": "Mezz 3:1-a",
            "requestedMbps": "2500",
            "networkUri": depnetwork,
            "mac": None,
            "wwpn": "",
            "wwnn": "",
            "requestedVFs": "Auto",
            "ipv4": {
                "ipAddress": None
            },
            "boot": {
                "priority": "Primary",
                "ethernetBootType": "iSCSI",
                "iscsi": {
                    "initiatorNameSource": "ProfileInitiatorName",
                    "firstBootTargetIp": None,
                    "secondBootTargetIp": "",
                    "secondBootTargetPort": "",
                    "initiatorName": None,
                    "bootTargetName": None,
                    "bootTargetLun": None
                }
            }
        }, {
            "id": 3,
            "name": "c1",
            "functionType": "Ethernet",
            "portId": "Auto",
            "requestedMbps": "2500",
            "networkUri": mgmtnetwork,
            "lagName": None,
            "mac": None,
            "wwpn": None,
            "wwnn": None,
            "requestedVFs": "0",
            "ipv4": {},
            "boot": {
                "priority": "NotBootable",
                "iscsi": {}
            }
        }, {
            "id": 4,
            "name": "c2",
            "functionType": "Ethernet",
            "portId": "Auto",
            "requestedMbps": "2500",
            "networkUri": mgmtnetwork,
            "lagName": None,
            "mac": None,
            "wwpn": None,
            "wwnn": None,
            "requestedVFs": "0",
            "ipv4": {},
            "boot": {
                "priority": "NotBootable",
                "iscsi": {}
            }
        }
        ]
    },
    "bootMode": {
        "manageMode": "true",
        "mode": "UEFIOptimized",
        "pxeBootPolicy": "Auto",
        "secureBoot": "Unmanaged"
    },
    "boot": {
        "manageBoot": "true",
        "order": [
            "HardDisk"
        ]
    },
    "bios": {
        "manageBios": "false",
        "overriddenSettings": [],
        "reapplyState": "NotApplying"
    },
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [],
        "reapplyState": "NotApplying"
    },
    "sanStorage": {
        "manageSanStorage": "false",
        "volumeAttachments": [],
        "sanSystemCredentials": [],
        "reapplyState": "NotApplying"
    },
    "osDeploymentSettings": {
        "osDeploymentPlanUri": "HPE - ESXi 6.0- deploy with multiple management NIC HA config- 2017-12-15",
        "osVolumeUri": None,
        "forceOsDeployment": "false",
        "osCustomAttributes": [
            {
                "name": "ManagementNIC.dhcp",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.ipv4disable",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.networkuri",
                "value": mgmtnetwork,
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC2.networkuri",
                "value": mgmtnetwork,
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.vlanid",
                "value": "0",
                "constraints": None,
                "type": "integer"
            },
            {
                "name": "ManagementNIC.connectionid",
                "value": "3",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.constraint",
                "value": "auto",
                "constraints": None,
                "type": None
            },
            {
                "name": "SSH",
                "value": "enabled",
                "constraints": "{\"options\":[\"enabled\",\"disabled\"]}",
                "type": "option"
            },
            {
                "name": "Hostname",
                "value": "hello",
                "constraints": "{\"helpText\":\"\"}",
                "type": "hostname"
            },
            {
                "name": "ManagementNIC2.dhcp",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC2.ipv4disable",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC2.connectionid",
                "value": "4",
                "constraints": None,
                "type": None
            },
            {
                "name": "Password",
                "value": "hello",
                "constraints": None,
                "type": "password"
            },
            {
                "name": "DomainName",
                "value": "hpe.com",
                "constraints": "{\"helpText\":\"\"}",
                "type": "fqdn"
            },
            {
                "name": "ManagementNIC2.vlanid",
                "value": "0",
                "constraints": None,
                "type": "integer"
            },
            {
                "name": "ManagementNIC2.constraint",
                "value": "auto",
                "constraints": None,
                "type": None
            }
        ]
    }
},
{
    "type": "ServerProfileV11",
    "serverHardwareUri": serverHardwareUri,
    "serverHardwareTypeUri": serverHardwareTypeUri,
	"serverProfileTemplateUri": None,
    "enclosureGroupUri": enclosureGroupUri,
    "enclosureUri": enclosureUri,
    "serialNumberType": "Virtual",
    "iscsiInitiatorNameType": "AutoGenerated",
    "macType": "Virtual",
    "wwnType": "Virtual",
    "name": "SP-HPE - ESXi -6.5- deploy with multiple management NIC HA config- 2017-12-15",
    "description": "",
    "affinity": "Bay",
    "firmware": {
        "firmwareBaselineUri": None,
        "manageFirmware": "false",
        "forceInstallFirmware": "false",
        "firmwareInstallType": None,
        "firmwareScheduleDateTime": None,
        "firmwareActivationType": None,
        "reapplyState": "NotApplying"
    },
    "connectionSettings": {
        "reapplyState": "NotApplying",
        "connections": [{
            "id": 1,
            "name": "Deployment Network A",
            "functionType": "Ethernet",
            "portId": "Mezz 3:1-a",
            "requestedMbps": "2500",
            "networkUri": depnetwork,
            "mac": None,
            "wwpn": "",
            "wwnn": "",
            "requestedVFs": "Auto",
            "ipv4": {
                "ipAddress": None
            },
            "boot": {
                "priority": "Primary",
                "ethernetBootType": "iSCSI",
                "iscsi": {
                    "initiatorNameSource": "ProfileInitiatorName",
                    "firstBootTargetIp": None,
                    "secondBootTargetIp": "",
                    "secondBootTargetPort": "",
                    "initiatorName": None,
                    "bootTargetName": None,
                    "bootTargetLun": None
                }
            }
        },  {
            "id": 3,
            "name": "c1",
            "functionType": "Ethernet",
            "portId": "Auto",
            "requestedMbps": "2500",
            "networkUri": mgmtnetwork,
            "lagName": None,
            "mac": None,
            "wwpn": None,
            "wwnn": None,
            "requestedVFs": "0",
            "ipv4": {},
            "boot": {
                "priority": "NotBootable",
                "iscsi": {}
            }
        }, {
            "id": 4,
            "name": "c2",
            "functionType": "Ethernet",
            "portId": "Auto",
            "requestedMbps": "2500",
            "networkUri": mgmtnetwork,
            "lagName": None,
            "mac": None,
            "wwpn": None,
            "wwnn": None,
            "requestedVFs": "0",
            "ipv4": {},
            "boot": {
                "priority": "NotBootable",
                "iscsi": {}
            }
        }
        ]
    },
    "bootMode": {
        "manageMode": "true",
        "mode": "UEFIOptimized",
        "pxeBootPolicy": "Auto",
        "secureBoot": "Unmanaged"
    },
    "boot": {
        "manageBoot": "true",
        "order": [
            "HardDisk"
        ]
    },
    "bios": {
        "manageBios": "false",
        "overriddenSettings": [],
        "reapplyState": "NotApplying"
    },
    "localStorage": {
        "sasLogicalJBODs": [],
        "controllers": [],
        "reapplyState": "NotApplying"
    },
    "sanStorage": {
        "manageSanStorage": "false",
        "volumeAttachments": [],
        "sanSystemCredentials": [],
        "reapplyState": "NotApplying"
    },
    "osDeploymentSettings": {
        "osDeploymentPlanUri": "HPE - ESXi -6.5- deploy with multiple management NIC HA config- 2017-12-15",
        "osVolumeUri": None,
        "forceOsDeployment": "false",
        "osCustomAttributes": [
            {
                "name": "ManagementNIC.dhcp",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.ipv4disable",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.networkuri",
                "value": mgmtnetwork,
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC2.networkuri",
                "value": mgmtnetwork,
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.vlanid",
                "value": "0",
                "constraints": None,
                "type": "integer"
            },
            {
                "name": "ManagementNIC.connectionid",
                "value": "3",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC.constraint",
                "value": "auto",
                "constraints": None,
                "type": None
            },
            {
                "name": "SSH",
                "value": "enabled",
                "constraints": "{\"options\":[\"enabled\",\"disabled\"]}",
                "type": "option"
            },
            {
                "name": "Hostname",
                "value": "hello",
                "constraints": "{\"helpText\":\"\"}",
                "type": "hostname"
            },
            {
                "name": "ManagementNIC2.dhcp",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC2.ipv4disable",
                "value": "false",
                "constraints": None,
                "type": None
            },
            {
                "name": "ManagementNIC2.connectionid",
                "value": "4",
                "constraints": None,
                "type": None
            },
            {
                "name": "Password",
                "value": "hello",
                "constraints": None,
                "type": "password"
            },
            {
                "name": "DomainName",
                "value": "hello.com",
                "constraints": "{\"helpText\":\"\"}",
                "type": "fqdn"
            },
            {
                "name": "ManagementNIC2.vlanid",
                "value": "0",
                "constraints": None,
                "type": "integer"
            },
            {
                "name": "ManagementNIC2.constraint",
                "value": "auto",
                "constraints": None,
                "type": None
            }
        ]
    }
}
]
