ENC_1 = 'MXQ81804ZF'
ENC_2 = 'MXQ81804ZH'
ENC_3 = 'MXQ81804ZG'

appliance_ip = '15.245.131.251'
admin_credentials = {'userName': 'Administrator', 'password': 'hpvse123'}

networks = {
    'namePrefix': 'net',
    'privateNetwork': False,
    'smartLink': True,
    'purpose': 'General',
    'type': 'bulk-ethernet-networkV1'
}

ns_dto = {
    'type': 'network-setV4',
    'networkUris': None
}

les = {
    'name': 'LE',
    'enclosureUris': [ENC_1, ENC_2, ENC_3],
    'enclosureGroupUri': 'Enc3-EG',
    'firmwareBaselineUri': None,
    'forceInstallFirmware': False
}

uplink_set = {
    'name': 'US1',
    'ethernetNetworkType': 'Tagged',
    'networkType': 'Ethernet',
    'networkUris': None,
    'mode': 'Auto',
    'nativeNetworkUri': None,
    'logicalPortConfigInfos': [
        {'enclosure': '1', 'bay': '3', 'port': 'Q3', 'speed': 'Auto'},
        {'enclosure': '2', 'bay': '6', 'port': 'Q3', 'speed': 'Auto'}
    ]
}

###
# Interconnect bays configurations
# 3 Enclosure, Fabric 3
###

Enc3Map = \
    [
        {'bay': 3, 'enclosure': 1, 'type': 'Virtual Connect SE 100Gb F32 Module for Synergy', 'enclosureIndex': 1},
        {'bay': 6, 'enclosure': 1, 'type': 'Synergy 50Gb Interconnect Link Module', 'enclosureIndex': 1},
        {'bay': 3, 'enclosure': 2, 'type': 'Synergy 50Gb Interconnect Link Module', 'enclosureIndex': 2},
        {'bay': 6, 'enclosure': 2, 'type': 'Virtual Connect SE 100Gb F32 Module for Synergy', 'enclosureIndex': 2},
        {'bay': 3, 'enclosure': 3, 'type': 'Synergy 50Gb Interconnect Link Module', 'enclosureIndex': 3},
        {'bay': 6, 'enclosure': 3, 'type': 'Synergy 50Gb Interconnect Link Module', 'enclosureIndex': 3},
    ]

###
# Logical Interconnect Groups
###
lig = {
    'name': 'Enc3-LIG',
    'interconnectMapTemplate': Enc3Map,
    'enclosureIndexes': [1, 2, 3],
    'interconnectBaySet': 3,
    'redundancyType': 'HighlyAvailable',
    'downlinkSpeedMode': 'SPEED_50GB',
    'uplinkSets': [uplink_set],
}


###
# Enclosure Groups
###
enc_group = {
    'name': 'Enc3-EG',
    'enclosureCount': 3,
    'interconnectBayMappings': [
        {'interconnectBay': 1, 'logicalInterconnectGroupUri': None},
        {'interconnectBay': 2, 'logicalInterconnectGroupUri': None},
        {'interconnectBay': 3, 'logicalInterconnectGroupUri': 'LIG:Enc3-LIG'},
        {'interconnectBay': 4, 'logicalInterconnectGroupUri': None},
        {'interconnectBay': 5, 'logicalInterconnectGroupUri': None},
        {'interconnectBay': 6, 'logicalInterconnectGroupUri': 'LIG:Enc3-LIG'}
    ]
}

###
# Server profiles
###
Profiles = [
    {
        'payload': {
            'name': 'Profile1',
            'serverHardwareUri': ENC_1 + ', bay 1',
            'enclosureUri': ENC_1,
            'enclosureGroupUri': 'Enc3-EG',
            'connectionSettings': {
                    'connections': [
                        {	'name': 'conn1',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-a',
                          'networkUri': 'LNS_1',
                                        'lagName': 'LAG1'
                          },
                        {	'name': 'conn2',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-a',
                          'networkUri': 'LNS_1',
                          'lagName': 'LAG1'
                          },
                        {	'name': 'conn3',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-b',
                          'networkUri': 'LNS_9',
                          },
                        {	'name': 'conn4',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-c',
                          'networkUri': 'LNS_10',
                          },
                        {	'name': 'conn5',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-d',
                          'networkUri': 'LNS_11',
                          },
                        {	'name': 'conn6',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-e',
                          'networkUri': 'LNS_12',
                          },
                        {	'name': 'conn7',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-f',
                          'networkUri': 'LNS_13',
                          },
                        {	'name': 'conn8',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-g',
                          'networkUri': 'LNS_14',
                          },
                        {	'name': 'conn9',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-h',
                          'networkUri': 'LNS_15',
                          },
                        {	'name': 'conn10',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-b',
                          'networkUri': 'LNS_16',
                          },
                        {	'name': 'conn11',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-c',
                          'networkUri': 'LNS_17',
                          },
                        {	'name': 'conn12',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-d',
                          'networkUri': 'LNS_18',
                          },
                        {	'name': 'conn13',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-e',
                          'networkUri': 'LNS_19',
                          },
                        {	'name': 'conn14',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-f',
                          'networkUri': 'LNS_20',
                          },
                        {	'name': 'conn15',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-g',
                          'networkUri': 'LNS_21',
                          },
                        {	'name': 'conn16',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-h',
                          'networkUri': 'LNS_22',
                          }
                    ]
            }
        },
        'IP': '10.13.0.255',
    },
    {
        'payload': {
            'name': 'Profile2',
            'serverHardwareUri': ENC_2 + ', bay 1',
            'enclosureUri': ENC_2,
            'enclosureGroupUri': 'Enc3-EG',
            'connectionSettings': {
                    'connections': [
                        {	'name': 'conn1',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-a',
                          'networkUri': 'LNS_2',
                          },
                        {	'name': 'conn2',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-b',
                          'networkUri': 'LNS_23',
                          },
                        {	'name': 'conn3',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-c',
                          'networkUri': 'LNS_24',
                          },
                        {	'name': 'conn4',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-d',
                          'networkUri': 'RNS_1',
                          },
                        {	'name': 'conn5',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-e',
                          'networkUri': 'LNS_25',
                          },
                        {	'name': 'conn6',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-f',
                          'networkUri': 'LNS_26',
                          },
                        {	'name': 'conn7',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-g',
                          'networkUri': 'LNS_27',
                          },
                        {	'name': 'conn8',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-h',
                          'networkUri': 'RNS_2',
                          },
                        {	'name': 'conn9',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-a',
                          'networkUri': 'LNS_3',
                          },
                        {	'name': 'conn10',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-b',
                          'networkUri': 'LNS_28',
                          },
                        {	'name': 'conn11',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-c',
                          'networkUri': 'LNS_29',
                          },
                        {	'name': 'conn12',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-d',
                          'networkUri': 'LNS_30',
                          },
                        {	'name': 'conn13',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-e',
                          'networkUri': 'LNS_31',
                          },
                        {	'name': 'conn14',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-f',
                          'networkUri': 'LNS_32',
                          },
                        {	'name': 'conn15',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-g',
                          'networkUri': 'LNS_33',
                          },
                        {	'name': 'conn16',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-h',
                          'networkUri': 'LNS_34',
                          }
                    ]
            }
        }
    },
    {
        'payload': {
            'name': 'Profile3',
            'serverHardwareUri': ENC_2 + ', bay 3',
            'enclosureUri': ENC_2,
            'enclosureGroupUri': 'Enc3-EG',
            'connectionSettings': {
                    'connections': [
                        {	'name': 'conn1',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-a',
                          'networkUri': 'LNS_4',
                          },
                        {	'name': 'conn2',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-b',
                          'networkUri': 'LNS_35',
                          },
                        {	'name': 'conn3',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-c',
                          'networkUri': 'LNS_36',
                          },
                        {	'name': 'conn4',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-d',
                          'networkUri': 'LNS_37',
                          },
                        {	'name': 'conn5',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-e',
                          'networkUri': 'LNS_38',
                          },
                        {	'name': 'conn6',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-f',
                          'networkUri': 'LNS_39',
                          },
                        {	'name': 'conn7',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-g',
                          'networkUri': 'LNS_40',
                          },
                        {	'name': 'conn8',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-h',
                          'networkUri': 'LNS_41',
                          },
                        {	'name': 'conn9',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-a',
                          'networkUri': 'LNS_5',
                          },
                        {	'name': 'conn10',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-b',
                          'networkUri': 'LNS_42',
                          },
                        {	'name': 'conn11',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-c',
                          'networkUri': 'LNS_43',
                          },
                        {	'name': 'conn12',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-d',
                          'networkUri': 'LNS_44',
                          },
                        {	'name': 'conn13',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-e',
                          'networkUri': 'LNS_45',
                          },
                        {	'name': 'conn14',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-f',
                          'networkUri': 'LNS_46',
                          },
                        {	'name': 'conn15',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-g',
                          'networkUri': 'LNS_47',
                          },
                        {	'name': 'conn16',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-h',
                          'networkUri': 'LNS_48',
                          },
                    ]
            }
        },
    },
    {
        'payload': {
            'name': 'Profile4',
            'serverHardwareUri': ENC_3 + ', bay 3',
            'enclosureUri': ENC_3,
            'enclosureGroupUri': 'Enc3-EG',
            'connectionSettings': {
                    'connections': [
                        {	'name': 'conn1',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-a',
                          'networkUri': 'LNS_6',
                          },
                        {	'name': 'conn2',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-b',
                          'networkUri': 'LNS_49',
                          },
                        {	'name': 'conn3',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-c',
                          'networkUri': 'LNS_50',
                          },
                        {	'name': 'conn4',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-d',
                          'networkUri': 'LNS_51',
                          },
                        {	'name': 'conn5',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-e',
                          'networkUri': 'LNS_52',
                          },
                        {	'name': 'conn6',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-f',
                          'networkUri': 'LNS_53',
                          },
                        {	'name': 'conn7',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-g',
                          'networkUri': 'LNS_54',
                          },
                        {	'name': 'conn8',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:1-h',
                          'networkUri': 'LNS_55',
                          },
                        {	'name': 'conn9',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-a',
                          'networkUri': 'LNS_7',
                          },
                        {	'name': 'conn10',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-b',
                          'networkUri': 'LNS_56',
                          },
                        {	'name': 'conn11',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-c',
                          'networkUri': 'LNS_57',
                          },
                        {	'name': 'conn12',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-d',
                          'networkUri': 'LNS_58',
                          },
                        {	'name': 'conn13',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-e',
                          'networkUri': 'LNS_59',
                          },
                        {	'name': 'conn14',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-f',
                          'networkUri': 'LNS_60',
                          },
                        {	'name': 'conn15',
                          'functionType': 'Ethernet',
                          'portId': 'Mezz 3:2-g',
                          'networkUri': 'LNS_61',
                          },
                    ]
            }
        },
    }]

add_connection = {
    'name': 'added_connection',
    'functionType': 'Ethernet',
    'portId': 'Mezz 3:2-g',
    'networkUri': 'LNS_8',
}

add_connection2 = {
    'name': 'added_connection2',
    'functionType': 'Ethernet',
    'portId': 'Mezz 3:2-h',
    'networkUri': 'LNS_62',
}

duplicate_connection = {
    'name': 'duplicate_connection',
    'functionType': 'Ethernet',
    'portId': 'Mezz 3:2-h',
    'networkUri': 'LNS_9',
}
